### ISSUE TITLE
CEF Crash on latest MTA Build 1.5.6-release-18671.0.000

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#1001]
**Describe the bug**
When joining a server which uses CEF, the MTA client crashes

**To reproduce**
Join any server which uses CEF webbrowser (For example FFS Gaming)

**Expected behaviour**
MTA client should not crash

**Version**
Client Version = 1.5.6-release-18671.0.000
OS: Windows 7 Ultimate 64Bit

**Additional context**
Version = 1.5.6-release-18671.0.000
Time = Tue Jun 18 16:50:24 2019
Module = E:\MTA San Andreas\mta\cefweb.dll
Code = 0xC0000005
Offset = 0x00003472

EAX=00000000  EBX=00000010  ECX=33A0F48C  EDX=00000000  ESI=33A0F48C
EDI=00000002  EBP=33A0F224  ESP=33A0F21C  EIP=25A73472  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

**Dumps**
[client_1.5.6-release-18671.0.000_cefweb_00003472_5_EMt_5FCB84A4_55F3_00F_48D9A_20190618_1650.rsa.zip](https://github.com/multitheftauto/mtasa-blue/files/3302134/client_1.5.6-release-18671.0.000_cefweb_00003472_5_EMt_5FCB84A4_55F3_00F_48D9A_20190618_1650.rsa.zip)

**Comment by ccw808** [comment]
Please try https://nightly.mtasa.com/mtasa-1.5.6-rc-18674-20190618.exe

**Comment by Dutchman101** [comment]
> Please try https://nightly.mtasa.com/mtasa-1.5.6-rc-18674-20190618.exe

I was able to reproduce it, and can confirm the update fixes it.

**Comment by ffsPLASMA** [comment]
As previous comments mentioned, this version fixes the crash.

**Comment by patrikjuvonen** [comment]
Great! Thanks for the confirmation.
