### ISSUE TITLE
Add third parameter for onChatMessage that contains receiver element when resource executes "outputChatBox"

### ISSUE THREAD

**Issue by nrzull** [multitheftauto/mtasa-blue#1002]
**Is your feature request related to a problem? Please describe.**

When you listening for messages that other resources send to receivers via outputChaBox, you actually can't know direct receiver

**Describe the solution you'd like**

It would be great to have third parameter that will contain player/resource/element. With this feature you can redirect message to the direct receiver using custom output solutions

**Comment by nrzull** [comment]
Actually, I found solution using addDebugHook that listens for outputChatBox calls. It can be closed if this feature is not important for anyone else

**Comment by CrosRoad95** [comment]
This is not a solution. AddDebugHook cause higher cpu usage, for me, each event should contain hidden variable 'sourceResource'

**Comment by xLuxy** [comment]
+1 for sourceResource

**Comment by botder** [comment]
**onChatMessage** only triggers for `sendTo == root` and then only immediate player-type children of the root element receive the chat message, when I look at the MTA code.

https://github.com/multitheftauto/mtasa-blue/blob/1e234b6786bc5c6aab85baba37946d637d00f474/Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L9790-L9816

**Comment by Pirulax** [comment]
Not the most optimal way to do it, but it works, so.
I think can be closed then, or?
