### ISSUE TITLE
getTime should also returns weekday in game

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#1004]
**Is your feature request related to a problem? Please describe.**
In single player we have a weekday in stats, `getTime` function should returns also a weekday.

**Describe the solution you'd like**
getTime should returns weekday in game

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/26044224/59937033-b3b8b800-9451-11e9-93b6-8e148b1bdecb.png)

`0xB7014E` - [byte] Current Weekday (1 through 7)

**Comment by qaisjp** [comment]
Does the weekday have an effect on gameplay?

**Comment by FileEX** [comment]
Yes, in some missions in singleplayer the weekday matters. I think it might be useful eg. for custom missions system, or for days cycle in truck gamemode based on Euro Truck Simulator, because real time in this case is bad idea.

**Comment by qaisjp** [comment]
So this has no effect on multiplayer gameplay?

**Comment by FileEX** [comment]
No, but this would be useful for scripting.

**Comment by CrosRoad95** [comment]
> No, but this would be useful for scripting.

Potential new issues in mta in cost of thing that really is useless and can be easily done by script

**Comment by forkerer** [comment]
> > No, but this would be useful for scripting.
> 
> Potential new issues in mta in cost of thing that really is useless and can be easily done by script

What possible issues could it ever cause? It's literally already tracked by game, giving option to get the value from lua is the right choice.

**Comment by CrosRoad95** [comment]
i can't indicate any potential issue, i took a quick look how this can be implemented

**Comment by FileEX** [comment]
This should not cause any issues, because why? Returns only one more value from a function that has this value, but this value is not returned now.

**Comment by qaisjp** [comment]
I can't see any value in this feature so I'm going to reject this proposal.

If you can come up will real demonstrable uses that doesn't just depend on having a simple day counter exposed, I'll be happy to reopen this.
