### ISSUE TITLE
feature: function `SetServerAnnounceValue`

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1005]
**Is your feature request related to a problem? Please describe.**
You can set announce value for player, but not for server ( except map/gamemode and some other ).

**Describe the solution you'd like**
add function `SetServerAnnounceValue(key, value)`, works same as for player but is related to server

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by Dezash** [comment]
https://wiki.multitheftauto.com/wiki/SetRuleValue
