### ISSUE TITLE
onClientMinimize don't working on window mode

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#1006]
**Describe the bug**
onClientMinimize event isn't triggered if window mode is enabled.

**To reproduce**
Set window mode to on
```lua
addEventHandler('onClientMinimize', root, function()
      print('minimized')
end)
```

it's only working on fullscreen, without diffrence if game is minimized by ALT + TAB or by click outside the window.

**Expected behaviour**
onClientMinimize should also triggered on window mode

**Screenshots**

**Version**
1.5.6

**Additional context**

**Comment by CrosRoad95** [comment]
i already made attempt to resolve this issue
https://github.com/multitheftauto/mtasa-blue/pull/185

**Comment by omakmoh** [comment]
i tired to fix it , but it return false!

**Comment by jushar** [comment]
I'm not sure about this one. Technically, it's not a minimize in window mode.
However, I understand your concerns about the window not being focused or entirely in the background.

What exactly do you use `onClientMinimize/Restore` for?
