### ISSUE TITLE
Crash in CModelInfoSA::ResetAllVehicleDummies

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#1009]
**Describe the bug**
There is a suspicious crash (which looks like a regression/recently introduced bug rather than a memory issue) that occurs in **CModelInfoSA::ResetAllVehicleDummies**. It appears NULL is being passed. 

I believe that PR #390 may have caused it, because there's been a myriad of dummy-related crashes ever since which were never seen in dummy functions before. In this case, suspicion arises also because the crash line is one that @forkerer changed in his diff.

Crash trace: [https://pastebin.com/Nf3pQ6cU](https://pastebin.com/Nf3pQ6cU)

Crash line i referred: [https://github.com/multitheftauto/mtasa-blue/blob/master/Client/game_sa/CModelInfoSA.cpp#L976](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/game_sa/CModelInfoSA.cpp#L976)

The crash is in game_sa.dll and the offsets shift around 0035xxx.
Examples: 
r16588 = 00035641 (crash popularity into the thousands)
r18676 = 00035751

The nature of said crashing line `(pVehicleModel->pVisualInfo->vecDummies[dummy.first] = dummy.second;` and having a nullpointer passed there made me want to dig a little deeper. It may aswell be a bad model case, someone who knows what he's doing can find out more, but upon first asking about this crash in #development I got asked to open an issue immediately.

I certainly think it's worth further investigation.

**To reproduce**
Unknown

**Version**
Crash still exists in r18676

**Comment by Dutchman101** [comment]
[dumps.zip](https://github.com/multitheftauto/mtasa-blue/files/3405788/dumps.zip)

Here are 2 crash dumps from both referred revisions: r16588 and the more recent r18676.

Edit: apparently i attached the wrong zip file and didn't notice on time, corrected

**Comment by ghost** [comment]
I know why this happens. It's because the member `usNumberOfRefs` of CBaseModelInfoSAInterface is not incremented when it is pushed into the container. It needs to be decremented when removed from the container. This will make sure that  the model info does not get unloaded when it's in use.

**Comment by Dutchman101** [comment]
Assigned to @forkerer on request

**Comment by Dutchman101** [comment]
As we determined in #development channel, the crash fix (c2fbcdf) didn't end up resolving it.

Because this knownledge (and developer discussion) shouldn't be limited to those that participated in the discussion, I am re-opening this issue and uploading the development conversation:
[https://imgur.com/a/BHgiqQj](https://imgur.com/a/BHgiqQj) (click once to zoom for it to be readable)

One of the theories is that the model is still getting unloaded when it shouldn't, as a result of which the pointer to the structure containing visual info is invalidated.

The hacky solution that is being suggested (which qaisjp called a potential for unexpected behavior, and I called a last resort in case no one can further debug the exact origin of nullpointer) is the change in PR #963

**Comment by Dutchman101** [comment]
Since this is actually a duplicate of issue #909 i will close it again. My bad.
