### ISSUE TITLE
Can't choose resolutions over RDP

### ISSUE THREAD

**Issue by rambolger** [multitheftauto/mtasa-blue#1013]
**Describe the bug**
When using MTA on a machine that is controlled via Remote Desktop Protocol (please don't ask why lol) it is impossible to select any resolution other than the native one. 

**To reproduce**
1. Initiate RDP session to a remote machine
2. Launch MTA (which was previously configured in windowed mode)
3. Attempt to change resolution in Settings

**Screenshots**
https://cdn.discordapp.com/attachments/308999129412141057/594140235735236610/unknown.png

**Version**
Multi Theft Auto v1.5.6-release-18678

**Additional context**
This is obviously a very exotic use case. Although, it may be helpful for testing/development purposes.

**Comment by Woovie** [comment]
This is working as intended. RDP does odd changes to your video output settings and they don't change back until logging in to the local machine again. You should consider trying Steam remote play instead which runs in the native display without trickery. Add MTA as a non Steam game to do this. I've tested this myself and it works great.
