### ISSUE TITLE
New MTA update seems to have broken youtube cinema experience

### ISSUE THREAD

**Issue by cockerspaniel** [multitheftauto/mtasa-blue#1015]
**Describe the bug**
Ever since an MTA update this week, the video streaming of the youtube theater/ cinema experience scripts in MTA have started to show up in freeze frames. Sound is still OK, but the image doesn't flow well anymore, we get only freeze frames every couple of seconds or so.

**To reproduce**

Steps to reproduce the behaviour:
Go to, for example, Wyesoft server in MTA, and you'll see it in their cinema, which you can go to by writing /cin. Then once inside you write /film and you'll see the freeze frames. However we've been playing on a home server that's active on most nights only at midnight EU time, called stunero.zapto.org:22003. Same problem here too. And I think we tried another server too that had a cinema can't remember, but this pretty much happens on any server so it's a script new mta update issue.

https://forum.mtasa.com/topic/84682-rel-cinema-experience-20-updated-13th-january-2017/
https://community.multitheftauto.com/index.php?p=resources&s=details&id=12950
https://clips.twitch.tv/DeterminedSolidNikudonTebowing

We're all running Windows. Clients are all on 1.5.6. Our server is latest version, and I assume so is wyesoft and any other server with cinema experience script.

**Comment by qaisjp** [comment]
Please run the `ver` command and paste the output here.

**Once you have sent us the output of `ver`**, please can you install [r18664](https://nightly.mtasa.com/mtasa-1.5.6-rc-18664-20190613.exe) and test to see if the problem still happens. **Please DON'T install that link BEFORE sending us the `ver` output.** We need to know exactly what version you're encountering this problem on.

**Comment by Dutchman101** [comment]
I was able to reproduce this on r18668 (where CEF update 09a1f26 landed) and not on r18664 yet, so bug was introduced by CEF update.

Suggested strategy:
A) revert CEF update
B) try updating to latest CEF first (**75.0.13+g2c92fcd+chromium-75.0.3770.100**)

The overall stability of the current CEF version is a problem; there's a new crash (libcef!IsSandboxedProcess @ 023140dc, trace at [https://pastebin.com/Y4vA9t9Q)](https://pastebin.com/Y4vA9t9Q) and somehow css files can bug so (rare) scripts will break when `mtalocal://` is present. I'm not sure if adding issues for these other bugs is worth it, pending the decision on what we'll do directly as a result of this video bug.

In addition to aforementioned crash, 2 silent crashes also arrived (on quit; no impact): 01bf78ee and 01bf6f3e

**Comment by qaisjp** [comment]
cc @Jusonex

**Comment by cockerspaniel** [comment]
The result of ver before we installed r18664 was v1.5.6-release-18678

However we installed another server with 18664 and we're still getting the bug. The only explanation given that you didn't reproduce the bug on 18664 that I can think of, is that we must be installing it incorrectly, somehow putting the new CEF in the 18664 but the server owner is telling me that's not possible, that it comes with the install.

**Comment by Dutchman101** [comment]
> 
> 
> The result of ver before we installed r18664 was v1.5.6-release-18678
> 
> However we installed another server with 18664 and we're still getting the bug. The only explanation given that you didn't reproduce the bug on 18664 that I can think of, is that we must be installing it incorrectly, somehow putting the new CEF in the 18664 but the server owner is telling me that's not possible, that it comes with the install.

The bug depends only on client and is always reproducable on client build r18668 till latest, that's really all that matters for this issue and the triaging is complete. Thanks for your input though, we're working on it.

It should have never reached the update build and we apologize

**Comment by cockerspaniel** [comment]
Oh no need to apologise, thank you for this wonderful open source software

**Comment by jushar** [comment]
It's a bug in CEF that has been reported. Therefore, I'm gonna revert CEF to the last working version.

**Comment by patrikjuvonen** [comment]
CEF was updated to the latest version today by Jusonex so let us know if the problem still occurs.
