### ISSUE TITLE
Error loading font! (verdana.ttf)

### ISSUE THREAD

**Issue by Cereal-Killa** [multitheftauto/mtasa-blue#1019]
**Describe the bug**
The app crashes upon launch claiming that verdana.ttf cannot be found.
Tried to run in admin mode, compatibility mode, checked folder permissions,
none worked.

**To reproduce**
Run MTA on a Windows 10 1809 PC that exhibits the same font issue.

**Expected behaviour**
The app should find the font and launch successfully.

**Screenshots**
![2019-07-03_14-08-03](https://user-images.githubusercontent.com/25939765/60611347-80a0ed80-9d9c-11e9-8f46-c810cb4b9ed3.png)

![2019-07-03_14-05-11](https://user-images.githubusercontent.com/25939765/60611351-826ab100-9d9c-11e9-88ba-0923426f039f.png)

![2019-07-03_14-04-34](https://user-images.githubusercontent.com/25939765/60611356-84cd0b00-9d9c-11e9-966f-72a8fa1a4959.png)

**Version**
1.5.6-9.18678.0.000

[logfile.txt](https://github.com/multitheftauto/mtasa-blue/files/3356115/logfile.txt)
[MTADiag-Log-2019-7-2_10-41-31.txt](https://github.com/multitheftauto/mtasa-blue/files/3356116/MTADiag-Log-2019-7-2_10-41-31.txt)
[CEGUI.log](https://github.com/multitheftauto/mtasa-blue/files/3356117/CEGUI.log)

**Comment by Cereal-Killa** [comment]
Found a fix.

Windows 10 1803 or later seems to install new fonts
under the user profile folder and not C:\Windows\Fonts
like the app expects.

1. Delete the font Verdana, the usual way using the Fonts manager.
2. Copy verdana.ttf to a folder you can find it later.
3. Open the command prompt with administrator privileges.
4. Navigate to the folder you saved verdana.ttf.
5. execute "copy verdana.ttf c:\Windows\fonts"

**Comment by qaisjp** [comment]
Thanks for the report. ~~I think we should keep an eye on this as this manual work should not be required.~~ Oh, 1803 is May 2019, and not Windows Insider. @Cereal-Killa, did you reinstall the Verdana font causing it to go into the user profile folder?
