### ISSUE TITLE
Add restrictDebugHooksFor function for preventing of abusing addDebugHook function

### ISSUE THREAD

**Issue by nrzull** [multitheftauto/mtasa-blue#1030]
**Is your feature request related to a problem? Please describe.**
The problem is that `addDebugHook` can intercept function calls and then pass fake or modified arguments to hooked function. This ability has huge security vulnerability, because you can intercept `fetchRemote` and pass fake data, or you can intercept `logIn` and get user password. This can be shown in situations, when someone create closed resource and you really don't know what this resource does. Actually you can disallow of using `addDebugHook` in acl.xml, but what if you don't have such ability? As an example, you share your closed resource between end-users, and this resource should verify itself that it wasn't modified or has some steps to reproduce before start. It relies on `fileExists`. The first thing that you maybe want to do is to disable `addDebugHook` calls via calling itself and then skipping execution. But if end-user's resource loads before your resource, then you will not be able to protect yourself. **You really can't trust someone who will use your closed resource or trust resources whose sources are closed.**

**Describe the solution you'd like**
It would be good to have something like `restrictDebugHooksFor` that cannot be hookable and can remove all already registered hook callbacks for events/functions

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by sbx320** [comment]
This is not a security issue. 

1) If you do login via a resource that you don't trust, you can't trust that it only sends the login info to `logIn` either. This has nothing to do with `addDebugHook`.
2) Verifying that a resource hasn't been modified is not possible in any reasonable way. Even without `addDebugHook` I can simply overwrite whatever standard MTA functions that you use to protect your script. For example the following would override a check for a "important" file:
```
_fileExists = fileExists
function fileExists(path, ...) 
     if path == "important" then return true end
     return _fileExists(path, ...)
end 
```

For 1) avoid running untrusted scripts.
For 2) avoid distributing scripts that you don't want to be modified.

**Comment by qaisjp** [comment]
I agree with @sbx320. Perhaps we could maybe limit/guard `addDebugHook` behind an ACL entry, but this would have to be a separate issue.

> [can't] trust resources whose sources are closed

Correct. MTA does put some work into making sure resources are appropriately sandboxed, but you should probably read the code of resources you download, and you should probably never run compiled resources on your server [that you haven't written yourself].

> You really can't trust someone who will use your closed resource

Correct. There's nothing we can do here, really. Server owners have the power to decide what runs on their own server. They can compile their own server and bypass any limitations you set.

If you are hoping to sell a resource...
- ...and are trying to prevent scripters from modifying your closed-source resource, you will need to make that a clause in the license you issue to your customers
- ...and are trying to prevent piracy, you will have to chase it up yourself

If you are hoping to improve the security of your own servers, you will need to set up granular permissions.

**Comment by CrosRoad95** [comment]
at least could be supports addDebugHook ( and releted )  blacklisting in mtaserver.conf

**Comment by ccw808** [comment]
Password argument of account functions is masked out when using addDebugHook
