### ISSUE TITLE
Memory leak in our BASS implementation

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#1033]
**Describe the bug**
There is a memory leak in our implementation of BASS, as the library developer (Un4seen studios) has notified us of.

See below the notification, which includes details on the leak:
![BASSleak](https://user-images.githubusercontent.com/12105539/62103043-8a364c00-b29b-11e9-8d62-d0b0c795d3ec.png)

The leak is supposedly in this location: [https://github.com/multitheftauto/mtasa-blue/blob/4d4692ead2d8c6fc8afd4c40ab46791cbbbf9c24/Client/mods/deathmatch/logic/CBassAudio.cpp#L763](https://github.com/multitheftauto/mtasa-blue/blob/4d4692ead2d8c6fc8afd4c40ab46791cbbbf9c24/Client/mods/deathmatch/logic/CBassAudio.cpp#L763)

For the record, @botder did some investigation before, see below:
![bd](https://user-images.githubusercontent.com/12105539/62103358-87882680-b29c-11e9-862b-98f3f76e7d4b.png)

**Comment by ghost** [comment]
So we just need to replace `BASS_FX_BPM_BeatFree` with `BASS_FX_BPM_Free`, right? How can I reproduce the memory leak? I'd like to take a look.

**Comment by Dutchman101** [comment]
> How can I reproduce the memory leak? I'd like to take a look.

I believe this flaw is the reason why the game process usage consistently grows with 0.3 to 0.7 MB in usage every second that you're playing a remote audio stream.. (which it doesn't **consistently** in the absence of a stream) although I believe that would previously have reached a ceiling (or partially free up) before f01dfdd, which means that while the memory wasting has always been present the last update might have caused a change in behavior, for which I'm glad that we're still on nightly until we figure out if I'm seeing ghosts or not.

But anyways, as I said, no matter the version of BASS, there has always been a gradual increase in usage when a stream is running and i believe it's due to this.. if it's not, then its hard to measure it. The purpose of filing this issue is to fix our integration, as it evidently does contain incorrect code that causes some sort of memory leak. You don't need to measure the leak itself to do that..
