### ISSUE TITLE
CEGUI guiSetProperty crash

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1039]
**Describe the bug**
Crash

Version = 1.5.6-release-18706.0.000
Time = Sat Aug  3 21:52:25 2019
Module = D:\mta 156\mta\cgui.dll
Code = 0xE06D7363
Offset = 0x001A5988

EAX=0177EDE8  EBX=0177EE94  ECX=00000003  EDX=00000000  ESI=0BF4709C
EDI=0BF75988  EBP=0177EE40  ESP=0177EDE8  EIP=7545FD62  FLG=00000216
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

**To reproduce**
just run
```lua
gridlist = guiCreateGridList( 0, 0, 0, 0, false) -- size doesn't matter
guiSetProperty(gridlist, "ColumnHeader", "crash" )
```

**Expected behaviour**
don't crash

**Screenshots**

**Version**
/

**Additional context**
found by mistake

**Comment by botder** [comment]
CEGUI bug: http://cegui.org.uk/mantis/view.php?id=171
