### ISSUE TITLE
Make bad numberstrings error instead of warn

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1043]
See:
- https://github.com/multitheftauto/mtasa-blue/commit/51a2c78c9d24f3f7321d25694653a24e39cfda86 "Fix bad numberstrings becoming 0", and
- https://github.com/multitheftauto/mtasa-blue/commit/73692fd0883c6afbab58971c6f77b3cf62b88f6e "Make bad numberstrings warn instead of error"

This warning has been around since 1.5.3. I propose we make this an error in 1.6.

Please discuss and express your (dis)approval.

**Comment by Pirulax** [comment]
I totally agree, there's no reason you would accept a bad number string, the user can explicitly check if its a bad numberstring or not. This may just cause misbehaving.

Also, Im pretty sure its rare you have a bad numberstring, but even if you do, you dont want it to modify anything into a possibly incorrect state.
