### ISSUE TITLE
Support for .dff .col .txd to manipulation via dffapi

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1046]
**Is your feature request related to a problem? Please describe.**
Currently it is hard to modify/create/edit .dff .col .txd files ( without using of external tools )

**Describe the solution you'd like**
Add new element type, availiable client and server side called for example `DFFBuilder`, `COLBuilder`, `TXDBuilder` which allows you to do everything with those files
For each element add plenty of functions to manipulate them ( read, edit, write )
**Describe alternatives you've considered**
/
**Additional context**
branch i created and script which successfully creates working .dff file
https://github.com/CrosRoad95/mtasa-blue/blob/a924e2153eeb572f1e86d221592a5bf1ca6b9f86/Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp#L1334-L1365

**Comment by qaisjp** [comment]
i liked @forkerer's suggestion of

> I would suggest expanding current DFF element to support that, the one returned by engineLoadDFF

**Comment by ghost** [comment]
>Currently it is hard to modify/create/edit .dff .col .txd files 

You can modify and create DFF, COL, and even TXD files with MTA/GTA functions. You can check my PR to see how I do it.
