### ISSUE TITLE
Add a event to check fetchRemote download progress

### ISSUE THREAD

**Issue by syynek** [multitheftauto/mtasa-blue#1048]
**Is your feature request related to a problem? Please describe.**
fetchRemote does not contain any possibility to check the progress of a download. 

**Describe the solution you'd like**
Adding an event like "onClientFetchRemoteProgress" to check the progress of a download.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by CrosRoad95** [comment]
#660

**Comment by Dutchman101** [comment]
The issue is a duplicate of #612 and as mentioned, it's being worked on in PR #660

**Comment by qaisjp** [comment]
Duplicate of #612
