### ISSUE TITLE
decodeString does not return false with wrong key

### ISSUE THREAD

**Issue by moon91210** [multitheftauto/mtasa-blue#1053]
**Describe the bug**
decodeString returns a weird string with characters and spaces when a wrong key is supplied

edit: teaDecode does the same thing

**To reproduce**
local encoded = encodeString('tea', 'hello', {key = '123'})
local decoded = decodeString('tea', encoded, {key = 'abc'}) -- supply wrong key
print(type(decoded), #decoded, decoded) -- unexpected output

**Expected behaviour**
decodeString should return false if a wrong key was supplied?

**Version**
Multi Theft Auto v1.5.6-release-18763

**Comment by CrosRoad95** [comment]
it doesn't works in that way, mta don't know if key match specified string and sometimes you simply need "weird string" return from decodeString ( to decode images/models etc )

**Comment by moon91210** [comment]
Well, the wiki says otherwise so it confused me. I added another step by hashing the original input and and the decoded string and then comparing the hashes which suits my needs.

**Comment by botder** [comment]
**decodeString** should only `return false` when you supplied invalid arguments to the function call, but it won't try to analyse the deciphered result string (how would you validate binary input - you simply can't) and then decide if it's correct or not.
