### ISSUE TITLE
Find out why a vehicle model's visual info may be nullptr

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#1057]
**Describe the bug**
Find out why [this](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/game_sa/CModelInfoSA.cpp#L978) may be a nullptr sometimes, and fix underlying bug.
See #963 for the original hacky workaround fix.

**Expected behaviour**
Visual info should not be nullptr.

**Version**
Multi Theft Auto v1.5.6-release-18769

**Comment by Einheit-101** [comment]
Maybe this happens when a vehicle is not streamed in or too far away (just a thought)

**Comment by forkerer** [comment]
Researching it a bit right now, the structure is nulled in `CVehicleModelInfo::DeleteRwObject`, specifically in instruction at address `0x004C98D2`. RIght now i think that there is no underlying bug at all, just the order of our operations is invalid. It seems it's going like `disconnect > reset vehicle model (makes struct nullptr) > try to reset dummies position for already deleted model`, and it should go `disconnect > reset dummies > reset model`

**Comment by forkerer** [comment]
Exact point in MTA codebase where it is triggered is `CClientDFF::RestoreModels -> CClientDFF::InternalRestoreModel -> CModelInfoSA::RestoreOriginalModel -> ((void(__cdecl*)(unsigned short))FUNC_RemoveModel)(static_cast<unsigned short>(m_dwModelID));`
the structure is zeroed in the `FUNC_RemoveModel` call
