### ISSUE TITLE
isElementData

### ISSUE THREAD

**Issue by dmi7ry** [multitheftauto/mtasa-blue#1060]
**Is your feature request related to a problem? Please describe.**
If I set `false` using `setElementData()` then it is not possible to find out if there is data with the required key or not, because both cases will return `false`.

**Describe the solution you'd like**
add function `isElementData()`

**Describe alternatives you've considered**
It is possible to get all data using `getAllElementData()` and then check a required key, but it may seriously affect the performance.

**Additional context**
no

**Comment by patrikjuvonen** [comment]
I disagree that we need a new function to check if element data by key exists. I think it's more about using element data with appropriate values when checking with `getElementData`. If the key doesn't exist or is false, it doesn't really make a difference.

**Comment by PlatinMTA** [comment]
Well, maybe getElementData could return nil instead of false (if it doesnt already do that). The other thing you could do is change the value, or create another elementData with other key to make sure that it exists.

I also think that it really isn't necessary, but I also don't see any harm if someone makes it.

**Comment by dmi7ry** [comment]
> If the key doesn't exist or is false, it doesn't really make a difference.

It makes a difference. For example, my element data may has any value except `false`. But once I want remove it. I could just add check `if not getElementData(element, "key") then removeElementData(element, key) end`

**Comment by CrosRoad95** [comment]
i made many servers, many script i never hadn't use something like isElementData
👉 [close]

**Comment by dmi7ry** [comment]
> Well, maybe getElementData could return nil instead of false (if it doesnt already do that).

It returns `false` and it won't be changed.

**Comment by dmi7ry** [comment]
> i made many servers, many script i never hadn't use something like isElementData
> 👉 [close]

Don't worry, once you will grow to it.

**Comment by Citizen01** [comment]
as everyone said it is not "needed" because for such a use case of the element data, you just have to invert the element data name and use true instead.
But that's not because everyone who commented they can get around this, it is steal a "cool to have" feature.

**Comment by dmi7ry** [comment]
> as everyone said it is not "needed" because for such a use case of the element data, you just have to invert the element data name and use true instead.
> But that's not because everyone who commented they can get around this, it is steal a "cool to have" feature.

I can't invert the name and use `true` because it's one of valid values. As I said, in my case it can contain any value including `true`.

**Comment by Citizen01** [comment]
> > as everyone said it is not "needed" because for such a use case of the element data, you just have to invert the element data name and use true instead.
> > But that's not because everyone who commented they can get around this, it is steal a "cool to have" feature.
> 
> I can't invert the name and use `true` because it's one of valid values. As I said, in my case it can contain any value including `true`.

I don't understand, can you show me an example ?

**Comment by patrikjuvonen** [comment]
Mixing types is not a very nice thing to do in code. Sure some devs are more type strict than others but I don't see the big benefit other than allowing for more less consistent / unreliable code practices to flourish which is already slightly bad at this point.

**Comment by dmi7ry** [comment]
> Mixing types is not a very nice thing to do in code. Sure some devs are more type strict than others but I don't see the big benefit other than allowing for more less consistent / unreliable code practices to flourish which is already slightly bad at this point.

Sure. But sometime we are work with legacy and just can't change things. There are some workarounds, but `isElementData()` would be a simplest and the most efficient way to achieve the result.

**Comment by Pirulax** [comment]
I mean sure, if ya'll really want it..

**Comment by qaisjp** [comment]
@patrikjuvonen what about an extra result?

```
data, ok = getElementData(element, ...)
```

This is inspired by Go's API for maps (and `getElementData` is just a glorified map).

It saves on having an extra (oddly-named) function, and saves a bit of scripting effort since you're rarely going to want to just the `ok` on its own anyway.

Worth noting that `removeElementData` also exists.

(To be honest, I'd prefer this approach over a new function, as proposed in #1163)
