### ISSUE TITLE
dxCreateTexture raw data problem

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1062]
**Describe the bug**
dxCreateTexture wrongly detects raw data

**To reproduce**
just run this resource, can't create texture from raw data, but if you same raw data save as file, windows open it without any issue
[dxcreatetexure.zip](https://github.com/multitheftauto/mtasa-blue/files/3514511/dxcreatetexure.zip)

**Expected behaviour**
provided raw data should be detected as raw data

**Screenshots**
/

**Version**
newstest, debug

**Additional context**
open bark5.jpg in paint and save it instantly, problem disapear

**Comment by ccw808** [comment]
File is missing jpeg [tail bytes](https://www.file-recovery.com/jpg-signature-format.htm) which makes loading unreliable
