### ISSUE TITLE
Increase max characters for reason in kickPlayer

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#1068]
**Is your feature request related to a problem? Please describe.**
Character limit is set to 64 for the reason message using kickPlayer function. Writing a larger string will be cut off in the message box. 

For example: "You have been kicked/banned by X for X days - Reason: You didn't behav....."

**Describe the solution you'd like**
Increase max characters for reason string to 128 or 256.

**Describe alternatives you've considered**
Shorten the actual reason string to fit the max characters resulting in weird grammar/sentences.

**Comment by qaisjp** [comment]
Seems reasonable
