### ISSUE TITLE
Make browser size (0,0) an error

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1069]
See 2336f780e6dcd250e2aecfe81fe9e5f95ca5d1d4 and https://github.com/multitheftauto/mtasa-blue/issues/1044#issuecomment-522348316 for further details.

**Comment by patrikjuvonen** [comment]
I have pushed a commit a26417f into the [next branch](https://github.com/multitheftauto/mtasa-blue/tree/next) that fixes this issue.
