### ISSUE TITLE
Remove deprecated mtalocal URL scheme

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1071]
See https://github.com/multitheftauto/mtasa-blue/commit/b8e2994b4395cd8e0654e62398387249bb0c0fdf and https://github.com/multitheftauto/mtasa-blue/issues/1044#issuecomment-522348316.

**Comment by patrikjuvonen** [comment]
I have pushed a commit c4c01e2 into the [next branch](https://github.com/multitheftauto/mtasa-blue/tree/next) that fixes this issue.
