### ISSUE TITLE
fileOpen uses wrong directory when the resource was zipped

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1087]
**Describe the bug**
fileOpen doesnt use the `resources` directory if a resource was zipped. Instead, it tries to open the file inside the `unzipped` directory.

**To reproduce**
1.) Start this resource: [test.zip](https://github.com/multitheftauto/mtasa-blue/files/3592432/test.zip)
2.) execute the `test` command twice in the server console

**Expected behaviour**

fileOpen should always check `resources` directory first and then `unzipped` directoy

**Version**
Server: r18957

**Comment by haron4igg** [comment]
First introduced in: r16256
https://buildinfo.mtasa.com/?Revision=16256
