### ISSUE TITLE
Model not unload with stop resource

### ISSUE THREAD

**Issue by XaskeL** [multitheftauto/mtasa-blue#1089]
**Describe the bug**
Model not unload with stop resource. Also, the "engineRestoreModel" function had no effect on this. The first screenshot shows that I started and stopped the resource again. But the model was not unloaded from any of my players.

I disconnected from the server and connected. The model has been unloaded. But with those who did not have the model unloaded (they left it on the client), I began to see how in the second screenshot.

Steps to reproduce the behaviour:
1. Run the resource.
2. Stop the resource.

https://upload.mtasa.com/u/645466933/bear.zip_

**Expected behaviour**
I thought, as usual, the model will be unloaded when the resource is stopped or a special function is called.

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/64914625-6469e700-d723-11e9-9473-6953dc71d369.png)
![image](https://user-images.githubusercontent.com/923242/64914628-6c298b80-d723-11e9-9e7e-6a8cf4996922.png)

**Version**
Multi Theft Auto v1.5.7-release-18957 (client)
Windows 10 1903.

**Comment by botder** [comment]
Can you upload the resource ZIP here on GitHub?

**Comment by XaskeL** [comment]
> Can you upload the resource ZIP here on GitHub?
finally saw how to do it
[bear.zip](https://github.com/multitheftauto/mtasa-blue/files/3602946/bear.zip)

**Comment by PlatinMTA** [comment]
It looks like a problem with the bones, doesn't it?

**Comment by XaskeL** [comment]
video with problem
https://youtu.be/otOYEZDykrI
please tell me when it can be removed. I do not want to leave this in the public domain.

**Comment by PlatinMTA** [comment]
> video with problem
> https://youtu.be/otOYEZDykrI
> please tell me when it can be removed. I do not want to leave this in the public domain.

wtf was that

**Comment by ghost** [comment]
At the moment it looks like the resource is not being removed properly (or it's children):
![image](https://user-images.githubusercontent.com/8040605/64914523-fd185b00-d753-11e9-8c7c-8e54c4a89a31.png)
![image](https://user-images.githubusercontent.com/8040605/64914532-53859980-d754-11e9-8e3e-2e80ff819586.png)

isnt `getResourceRootElement(getResourceFromName("bear"))` supposed to return false / an empty table ?

**Comment by ghost** [comment]
Okay, another weird thing:
1.) start resource
2.) change model to 309
3.) stop resource
4.) change model to something else and then back to 309

The model somehow resets but leaves the txd / dff in txdroot / dffroot of that resource.
