### ISSUE TITLE
Video problem of html

### ISSUE THREAD

**Issue by 669344682** [multitheftauto/mtasa-blue#1091]
**Describe the bug**
MTASA cannot load .webm video of html.

Steps to reproduce the behaviour:
1. Add video path to meta.xml
2. Add Video(autoplay) path to HTML
3. Join the server and resource start
4. Brower be created
5. Cannot play the video

code: https://forum.mtasa.com/topic/119947-video-of-html-problem/

**Expected behaviour**
Video autoplay on the browser is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/66273258-397a3b00-e86a-11e9-9327-450c4f0d4e31.png)

**Version**
1.5.7

**Comment by Lightins** [comment]
Same problem after 1.5.7 update. It would be good to get some answer from MTA team if they have already read this and are aware about this bug.

**Comment by Dutchman101** [comment]
> Same problem after 1.5.7 update

No.. MTA CEF has never been able to play webm videos. One of the consequences is that some YouTube videos cannot be played (it will display "your browser doesn't support this video format"). I have seen this issue since ever..

**Comment by Skraund** [comment]
I also have such a bug, I think there is an error due to changes to the local path for HTML in 1.5.7, because when I try to load an HTML document with "Hello World", an error 404 appears. The path is registered according to the rules from Wiki.

**Comment by thisdp** [comment]
MTA CEF could play webm videos before, I can prove it https://youtu.be/ZIq24zS5byI

**Comment by Lightins** [comment]
Since Aug 2015, we replaced the custom mtalocal:// URL scheme with http://mta/resourceName/blah.html. This mtalocal:// URL scheme will now be removed.

Looks like the problem is cant now get files from other resources, only from local.

-- WORKS

http://mta/local/avatar.png

-- BROKEN

http://mta/cache/avatar.png

**Comment by botder** [comment]
> Looks like the problem is cant now get files from other resources, only from local.

Works fine for me.

**Comment by Lightins** [comment]
Cant open file if file is not added to meta.xml, so for example if im doing some caching then I cant get files. After 1.5.7 update this is broken, maybe some security issue? But about this I didnt saw in changelog.

**Comment by Skraund** [comment]
I seem to have found a problem. In my opinion, the whole thing is in the new client 1.5.7. I think so, because I installed the client version 1.5.6-9.14334.0 and the server of the latest version 1.5.7 and everything worked as soon as I updated the client to 1.5.7 - it stopped working. I think the problem is in this commit: https://github.com/multitheftauto/mtasa-blue/commit/b8e2994b4395cd8e0654e62398387249bb0c0fdf?diff=unified

**Comment by Woesshhh** [comment]
i also got the same problem. In older MTA versions html webm player was working but right now it isn't working anymore.

**Comment by Turbesz** [comment]
will it ever be fixed this problem?!

**Comment by 669344682** [comment]
The Bug of video still has, Please official developers solve it, thanks a lot.

**Comment by Woesshhh** [comment]
please admins, can you take a look at this problem. Im still waiting to get this problem fixed.

**Comment by patrikjuvonen** [comment]
This bug still exists in 20503.

I am able to play webm videos from a remote source but not from a local source.

**Comment by theSarrum** [comment]
It's actually a CEF issue.
https://bitbucket.org/chromiumembedded/cef/issues/2836/cefstreamreader-createforfile

**Comment by Woesshhh** [comment]
'Since Aug 2015, we replaced the custom mtalocal:// URL scheme with http://mta/resourceName/blah.html. This mtalocal:// URL scheme will now be removed. See GitHub #1071.'

this bug came after this update. You can find this update here: https://wiki.multitheftauto.com/wiki/Changes_in_1.5.7

**Comment by patrikjuvonen** [comment]
We could try cherry-picking this upstream PR that attempts to fix this issue: https://bitbucket.org/chromiumembedded/cef/pull-requests/286/fixed-an-issue-where-expected-content

**Comment by 669344682** [comment]
> ~We could try cherry-picking this upstream PR that attempts to fix this issue: https://bitbucket.org/chromiumembedded/cef/pull-requests/286/fixed-an-issue-where-expected-content~
> 
> Nevermind. We can't do it :/

Please fix this bug, thanks a lot!

**Comment by thisdp** [comment]
> > ~We could try cherry-picking this upstream PR that attempts to fix this issue: https://bitbucket.org/chromiumembedded/cef/pull-requests/286/fixed-an-issue-where-expected-content~
> > Nevermind. We can't do it :/
> 
> Please fix this bug, thanks a lot!

This is a problem of CEF, not MTA.

**Comment by theSarrum** [comment]
Fixed in #1397
