### ISSUE TITLE
Blend mode is ignored in TileBatcher

### ISSUE THREAD

**Issue by StrixG** [multitheftauto/mtasa-blue#1097]
**Describe the bug**
The blend mode is forced to `blend` when drawing a shader or a texture with any addressing except `wrap`.

**To reproduce**
1. Download [blendtest.zip](https://github.com/multitheftauto/mtasa-blue/files/3623857/blendtest.zip) and start it.
2. Change blend mode using the `blend overwrite` command.
3. Blending won't change on `clamp`, `mirror`, `border` textures.

**Expected behaviour**
The blend mode should change.

**Screenshots**
![image](https://user-images.githubusercontent.com/8400907/65088457-b9268f80-d9b9-11e9-81d4-5634d7f2e3a9.png)

**Version**
Multi Theft Auto v1.5.7-release-20210

**Additional context**
PrimitiveBatcher may also be affected.

**Comment by StrixG** [comment]
The problem was solved by removing [these lines](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/core/Graphics/CTileBatcher.cpp#L144-L160). But I don't know what else these lines could affect.

**Comment by qaisjp** [comment]
Those lines were added here https://github.com/multitheftauto/mtasa-blue/commit/22fcca68d623317b720755a89a2f7b4ba1e66eb7#diff-73554a1f255a16a79a0dc76c3f221347L81-L99

**Comment by ccw808** [comment]
That should fix it
