### ISSUE TITLE
setPlayerTeam does not set player nickname color

### ISSUE THREAD

**Issue by Vadya963** [multitheftauto/mtasa-blue#1101]
**Describe the bug**
after re-adding a player to the team, the color of the nickname does not change

**To reproduce**
1. create team with any color
2. add players and kick it out
3. add player again

**Expected behaviour**
if the color of the team was red when creating the team, then the color of the nickname should be red, but it is white

**Version**
MTA 1.5.7-release-20279

**Additional context**
the color of the player getting through getPlayerNametagColor

**Comment by botder** [comment]
Can you provide a minimal script to reproduce this issue?

**Comment by Vadya963** [comment]
```lua
local team = createTeam("myTeam", 255, 0, 0)
addCommandHandler ("teamcreate",
function (playerid)
    setTimer(function ()
        if getPlayerTeam ( playerid ) then
            setPlayerTeam(playerid, nil)
            print("no team")
            iprint(getPlayerNametagColor(playerid))
        else
            setPlayerTeam(playerid, team)
            print("team myTeam")
            iprint(getPlayerNametagColor(playerid))
        end
    end, 2000, 2)
end)
```
[2019-09-27 00:02:43] INFO: team myTeam
[2019-09-27 00:02:43] INFO: 255    0    0
[2019-09-27 00:02:45] INFO: no team
[2019-09-27 00:02:45] INFO: 255    255    255
it works

```lua
local team = createTeam("myTeam", 255, 0, 0)
addCommandHandler ("teamcreate",
function (playerid)
	setPlayerNametagColor(playerid, 0,255,0)
    setTimer(function ()
        if getPlayerTeam ( playerid ) then
            setPlayerTeam(playerid, nil)
            print("no team")
            iprint(getPlayerNametagColor(playerid))
        else
            setPlayerTeam(playerid, team)
            print("team myTeam")
            iprint(getPlayerNametagColor(playerid))
        end
    end, 2000, 2)
end)
```
[2019-09-27 00:06:23] INFO: team myTeam
[2019-09-27 00:06:23] INFO: 0    255    0
[2019-09-27 00:06:25] INFO: no team
[2019-09-27 00:06:27] INFO: 0    255    0
it doesn't work

**Comment by Vadya963** [comment]
is it normal that it works like this?

**Comment by botder** [comment]
You used `setPlayerNametagColor` to set a forced nametag color, of course it won't use the team's color in that case.

https://github.com/multitheftauto/mtasa-blue/blob/185f57c7483dfeec656fdd656c6dac8bf57a93f0/Client/mods/deathmatch/logic/CClientPlayer.cpp#L140-L164
