### ISSUE TITLE
attachTrailerToVehicle no longer works with Tractor and Farm Trailer

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#1102]
**Describe the bug**
My farmer script which attaches the farm trailer to the tractor for planting seeds, no longer works.

**To reproduce**
Be driving the "Tractor" (531)
srun trailer = createVehicle(610, -2422, -610, 132)
srun attachTrailerToVehicle(me.vehicle, trailer)

Before r20212 it would warp the trailer so that it's attached, now the trailer doesn't move.

**Version**
Narrowed down to @botder's commit v1.5.7-release-20212 which has these 2 changes:

https://github.com/multitheftauto/mtasa-blue/commit/89978b5c7845c997bde24d3a36f320cafba56bcd
https://github.com/multitheftauto/mtasa-blue/commit/6f5e2b15d97dc3ca325288ff3e964d2a5e2aa0a6

**Additional context**

**Comment by ArranTuna** [comment]
It seems to work if trying with a car, but not working with 610 or 611 which are both trailers.

**Comment by botder** [comment]
Farm trailer (610) is towable by Tractor, that's a bug in my commit. Trailer (611) is not towable by Tractor, neither Tow truck - the trailer gets teleported to world center on tow attach and you can't use the tow bar or hook to do it manually.
