### ISSUE TITLE
Add areVehicleLightsOn serverside

### ISSUE THREAD

**Issue by NetroX1993** [multitheftauto/mtasa-blue#1104]
**Describe the solution you'd like**
 Have areVehicleLightsOn serverside.

**Additional context**
The Wiki says that areVehicleLightsOn is available serverside since 1.5.7 r19626. I'm currently using v1.5.7-release-20288 and its only available clientside.

**Comment by qaisjp** [comment]
Documentation bug fixed in https://wiki.multitheftauto.com/index.php?title=Template:Vehicle_functions&oldid=65399

I'll leave this to @StrixG to figure out if it's technically feasible ;)

**Comment by StrixG** [comment]
I don't think this is feasible since different players could have different in-game time. For one player the lights would be on at night and for the other are off. The lights state can't be synced properly.
