### ISSUE TITLE
Add isNextMapDM

### ISSUE THREAD

**Issue by forget** [multitheftauto/mtasa-blue#1105]
**Is your feature request related to a problem? Please describe.**
I don't think it should be called a problem, rather say a suggestion.

**Describe the solution you'd like**
I would like to see a function similar to https://wiki.multitheftauto.com/wiki/IsMapDM which can check for the next map if it is to be set as it hasnt been identified yet. - 'isNextMapDM'

**Describe alternatives you've considered**
I tried to identify a function as 'isNextMapDM' although you must edit Race gamemode.

**Additional context**
-

**Comment by CrosRoad95** [comment]
it makes no sense, i vote close this issue

**Comment by Haxardous** [comment]
it can be done by scripting & you can submit a pull request to add that feature by yourself to the race gamemode here: https://github.com/multitheftauto/mtasa-resources
