### ISSUE TITLE
'toggleControl' does not work correctly

### ISSUE THREAD

**Issue by rk-r** [multitheftauto/mtasa-blue#1107]
**Describe the bug**
toggleControl is not disabling shots when I press "TAB".

**To reproduce**
No error...

**Expected behaviour**
I was using ### toggleControl to disable **uzi** shooting. It worked normally, when I click the mouse it does not fire but if I press the '**TAB**' key it fires normally as if there was no toggleControl.I was using toggleControl to disable uzi shooting. It worked normally, when I click the mouse it does not fire but if I press the 'TAB' key it fires normally as if there was no **toggleControl**.

**Screenshots**
No images ...

**Version**
- 1.5.7 (last)
- windows7
-->

**Additional context**
I tested with other players the same problem happened to them was not just me.

**Comment by Haxardous** [comment]
~~instead of using toggleControl, you can use onClientPlayerWeaponFire instead for that~~

**Comment by dmi7ry** [comment]
> instead of using toggleControl, you can use onClientPlayerWeaponFire instead for that

#852

**Comment by TheNormalnij** [comment]
`toggleControl( 'action', false )`
Be happy

**Comment by qaisjp** [comment]
I think we should add a note to wiki about using `'action', false`.  I don't think this is an actual bug?
