### ISSUE TITLE
Main Menu: News-related phrases are not translated

### ISSUE THREAD

**Issue by jhxp** [multitheftauto/mtasa-blue#1108]
**Describe the bug**
A bunch of News UI-related phrases are hardcoded, therefore they are not translated in the app and not available in Pootle.

**To reproduce**
Steps to reproduce the behaviour:
1. Start MTA:SA, then set any non-English language.
2. Press `key to open Console, then type in _help_.
You may notice that description for _reloadnews_ command is not translated.
3. Type in _reloadnews_ command.
You may notice that command result is not translated.
4. In the _News_ window that opens, you may notice that some elements are not translated:
- window title (News)
- window buttons (Visit latest news article, Ok)

If the _News_ window does not open, simply click on any of the The Latest News article entries on the right side of the Main Menu.

**Expected behaviour**
Above-mentioned News UI-related phrases are available for translation.

**Screenshots**
![1-5-7-news-hardcoded-phrases](https://user-images.githubusercontent.com/11490010/65832467-69529d00-e2c4-11e9-907f-e3dc36ddc833.png)

**Version**
1.5.7

**Additional context**
none

**Comment by Haxardous** [comment]
about help command, after restarting client with a different language it’ll change to the chosen language so restarting client is required

**Comment by qaisjp** [comment]
The `reloadnews` command is actually a developer command. Perhaps we should flag it as such & make it so that the command no longer exists when you connect to a server (so that servers can actually use `addCommandHandler` against it).
