### ISSUE TITLE
exported resource methods for "protected" resources

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1112]
`webadmin` and `runcode` resources are being restricted. Is there a specific reason for this ? Malicious code can be injected anywhere. (for ex. `admin` resource)

Link: https://github.com/multitheftauto/mtasa-blue/blob/5325a5c98a5c1836d43e79a910a5a876019fb333/Server/mods/deathmatch/logic/CResource.cpp#L1639

In my opinion these "restriction" should be removed.

PS: Sorry for picking incorrect label.

**Comment by ccw808** [comment]
Added here: https://github.com/multitheftauto/mtasa-blue/commit/2abdc3756dad454e8dbc4a79af54803275b79cf1#diff-a3bb413592653e6b114992f09da83417R1708

**Comment by ccw808** [comment]
Required for legacy reasons
