### ISSUE TITLE
setCursorPosition returns true even if MTA main window isn't focused in Windows

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1113]
**Describe the bug**
setCursorPosition returns true even if MTA window isn't focused. When you have game in window mode or you have borderless mode, setCursorPosition returns true. 
You can't determine by any function or any event if player is in game. 

**To reproduce**
Watch YouTube: https://youtu.be/zjQcOE3c_V8
Script: https://pastebin.com/HgvuZb6x

Why it's important for me: https://youtu.be/OItkIjldqBM?t=14

**Expected behaviour**
There's should be function for check if MTA isn't focused or setCursorPosition shouldn't return true if MTA isn't focused

**Screenshots**
Look at "to reproduce"

**Version**
Multi Theft Auto v1.5.7-release-20288

**Comment by CrosRoad95** [comment]
i think could be solved in way i proposed almost 2 years ago #185

**Comment by qaisjp** [comment]
I think we'd be happy with you reviving that PR @CrosRoad95

**Comment by CrosRoad95** [comment]
i remember i had a problems with doing it in way proposed by botder, i think he should finish it

**Comment by Lpsd** [comment]
This is now resolved by #2371
