### ISSUE TITLE
Debugscripts reveals full path using file operation

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#1114]
**Describe the bug**
File operations reveal full path in debugscript.
Could be related to: https://github.com/multitheftauto/mtasa-blue/commit/1d4c2a2f68aae5c694057c3f453d5c57d015e489

**To reproduce**
Use file operations like fileOpen/fileClose
The screenshot below shows a map resource script which has been downloaded with fetchRemote and executed with fileOpen.

**Expected behaviour**
Debugscript should only show the sandbox filepath

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/66268663-8e508e00-e837-11e9-8790-be5d26e73101.png)

**Version**
Client:
Multi Theft Auto v1.5.7-release-20288
Copyright (C) 2003 - 2019 Multi Theft Auto

Server:
Server info for 164.132.203.95:22003
Ver: 1.5.6-9.18721.0
AC: [Allowed client files: None] [Disabled AC: None] [Enabled SD: 15,16,22,31,32,33,35]
Voice: Disabled
Glitches: None
Bullet sync weapons: 22,23,24,25,26,27,28,29,30,31,32,33,34
Vehicle extrapolation: Disabled
Tick rates: Plr:100  Cam:500  Ped:400  UnocVeh:1000  KeyRot:100  KeyJoy:100
Syncer distances: Ped:100  UnoccupiedVehicle:130

**Comment by ccw808** [comment]
@sbx320 maybe caused by 1d4c2a2

**Comment by qaisjp** [comment]
> The screenshot below shows a map resource script which has been downloaded with fetchRemote and **executed with fileOpen.**

What do you mean by **this**?

**Comment by ffsPLASMA** [comment]
> > The screenshot below shows a map resource script which has been downloaded with fetchRemote and **executed with fileOpen.**
> 
> What do you mean by **this**?

The script file gets downloaded and loaded into sandbox via file functions. As ccw808 already mentioned, its most likely a side effect of the file operation update.

**Comment by qaisjp** [comment]
"loaded into sandbox via file functions"

There are no "file functions" that execute code. Do you mean `loadstring`?

**Comment by qaisjp** [comment]
> loaded into sandbox via file functions

There are no "file functions" that execute code. Do you mean `loadstring`?

Please can you provide more details, or even better, an example resource to reproduce this? I am having trouble reproducing this.

**Comment by ffsPLASMA** [comment]
Only one map resource produces this debug output.
When looking at the compiled script, you can see the default mta path in first line.
When decompiled, its gone, so I guess the script was compiled in a weird way.


[script.zip](https://github.com/multitheftauto/mtasa-blue/files/4615738/script.zip)

I guess this issue can be closed?

**Comment by qaisjp** [comment]
How old is that script? I'm surprised it even runs (do we allow compiled scripts pre-luac?)

**Comment by ffsPLASMA** [comment]
The map was uploaded december 2016 to our server.

**Comment by qaisjp** [comment]
Nevermind, I guess it was not compiled with obfuscation
