### ISSUE TITLE
Players can't crouch when they have 1 HP

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1115]
**Describe the bug**
You can't crouch when you set your HP to 1.

**To reproduce**
1. run toggleControl(getPlayerFromName("MrDadosz"), "crouch", true)
2. run setElementHealth(getPlayerFromName("MrDadosz"), 100)
now you can crouch
3. run setElementHealth(getPlayerFromName("MrDadosz"), 1)
now you can't crouch
4. run toggleControl(getPlayerFromName("MrDadosz"), "crouch", true)
you can't crouch
5. run setElementHealth(getPlayerFromName("MrDadosz"), 2)
now you can crouch

**Expected behaviour**
Player should can crouch everytime, even when he has 1 HP.

**Screenshots**
https://youtu.be/u4dZs_IERDs

**Version**
Multi Theft Auto v1.5.7-release-20288
MTA:SA Server v1.5.6-release-16609 and MTA:SA Server v1.5.7-release-18957 - same results

**Comment by ArranTuna** [comment]
I remember some bug report from many years ago where you can't use jetpack properly when 1 HP.

**Comment by MrDadosz** [comment]
@ArranTuna Yea, this bug still exists, you can't go any direction with jetpack with 1 HP. 
You could crouch in 1.5.6 (maybe in older 1.5.7 version too), it's new bug and it's annoying on some servers, where after dying and respawning you have 1 HP.
