### ISSUE TITLE
dxDrawMaterialLine3D cannot get the texture

### ISSUE THREAD

**Issue by 669344682** [multitheftauto/mtasa-blue#1116]
**Describe the bug**

dxDrawMaterialLine3D cannot get the texture after one minute that the onClientPreRender was triggered.
debug: dxDrawMaterialLine3D got nil at argument 7

**Code**
The dxDrawImageOnElement is as same as the official wiki one in the useful function page.
client:
```lua
addEventHandler("onClientPreRender",root,function()
  for k,v in ipairs(getElementsByType("player")) do
    if getElementData(v,"accountData_state") == "true" then
      local x,y,z = getElementPosition(v)
      local policeduty = dxCreateTexture( "file/policeduty.png" )
      exports.srp_usefulfunctions:dxDrawImageOnElement(v,policeduty,20,0.02,0.01)
    end
  end
end)
```

meta.xml
```xml
<meta>
	<script type="client" src="c_nametag.lua"/>


	<file src="file/policeduty.png"/>
</meta>
```

**Version**

**Comment by xLuxy** [comment]
Please provide a reproducable code snippet.

**Comment by AfuSensi** [comment]
You are making a new texture every time ```onClientPreRender``` gets ran. 
It should be created only once and reused after.
Are you sure youre not just running out of memory?

**Comment by thisdp** [comment]
You didn't give MTASA enough time to finish the textu

**Comment by 669344682** [comment]
Thanks a lot
