### ISSUE TITLE
onPickupHit event OR setElementDimension doesn't work well

### ISSUE THREAD

**Issue by ItsFlorkast** [multitheftauto/mtasa-blue#1118]
Hello, I have tried to make a pickup in other dimensions, but this event not working in other dimensions. Also, when I use setElementDimension for pickup I got error
`Bad argument @ 'setElementDimension' [Expected element at argument 1, got boolean]`

1- make a pickup with createPickup function
2- set the pickup dimension to any dimension expect 0 with setElementDimension  function
3- make "onPickupHit" event and do anything, see example
4- start the script and set your player to the dimension of pickup.

thats it 

here my script as an example

```
pickup = createPickup(2806.99463, 2271.81152, 181.26875,1318,0,0)
setElementDimension(pickup ,3)



addEventHandler("onPickupHit",root,function(player)
if source == pickup then
destroyElement(pickup)
end

end)
```

MTA version: Multi Theft Auto v1.5.7-release-20288

**Comment by botder** [comment]
`pickup = createPickup(2806.99463, 2271.81152, 181.26875, 1318, 0, 0)` is incorrect

`createPickup(x, y, z, type, amount/weapon/model, respawnTime, ammo)` you were missing **type**

**Comment by ItsFlorkast** [comment]
Same problem.

**Comment by MrDadosz** [comment]
Tried right now, it's working fine.

run pickup = createPickup(-478,-113,63.70, 0,0); setElementDimension(pickup, 1); addEventHandler("onPickupHit", pickup, function(plr) outputDebugString("working"); destroyElement(source) end)

Code destroyed pickup and showed info in debugscript.

**Comment by botder** [comment]
> Same problem.

Works for me, if I use `type` 3 for custom pickup.

**Comment by ItsFlorkast** [comment]
I think because I added root in addEventHandler? maybe

**Comment by Anteeiiku** [comment]
can anyone try this? because I have tried this but nothing happened
```

Pickups = {
{2813.69897, 2274.06128, 181.26875 , 5 }
}

addEventHandler("onResourceStart",resourceRoot,function()

for k,v in ipairs (Pickups) do
Pickup = createPickup(v[1],v[2],v[3],3,1318,0,0)
setElementDimension(Pickup,4)
end

end)

addEventHandler("onPickupHit",root,function(player)

destroyElement(source)

end)


```

**Comment by botder** [comment]
Please close the issue if you can't provide a working example.
