### ISSUE TITLE
Hydraulics stops working when using setVehicleHandling with player inside vehicle

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1121]
**Describe the bug**
When you set maxVelocity with setVehicleHandling function and you're inside vehicle, you can't use it. Hydraulics is still mounted but vehicle behave like it has no hydraulics, you can honk instead of lifting a car.

**To reproduce**
1. create vehicle with upgrade 1087
2. try to use hydraulics [you can]
3. run vehicle = getPedOccupiedVehicle(getPlayerFromName("MrDadosz")); setVehicleHandling(vehicle, "maxVelocity", 100)
4. try to use hydraulics [you can't]

**Version**
v1.5.7-release-20288

**Additional context**
You can fix it with script:
```lua
if getVehicleUpgradeOnSlot(vehicle, 9) == 1087 then
	removeVehicleUpgrade(vehicle, 1087)
	addVehicleUpgrade(vehicle, 1087)
end
```
But it shouldn't happen.

**Comment by qaisjp** [comment]
Thanks for the bug report. By the way, you can use the following snippet when writing issues to syntax highlight your code:

````markdown
```lua
your
    code
here
```
````

**Comment by MrDadosz** [comment]
There's second problem about fixing it by script, maybe it's related. When you remove and add hydraulics and you have mounted nitro, bind for it won't work. You can see nitrous bottle, you can use hydraulics but you can't use nitro.

**Comment by FileEX** [comment]
> There's second problem about fixing it by script, maybe it's related. When you remove and add hydraulics and you have mounted nitro, bind for it won't work. You can see nitrous bottle, you can use hydraulics but you can't use nitro.

Cannot reproduce.

```lua
srun addVehicleUpgrade(me.vehicle, 1010) -- add nitro
srun addVehicleUpgrade(me.vehicle, 1087) -- add hydra
srun removeVehicleUpgrade(me.vehicle, 1087) -- remove hydra
srun addVehicleUpgrade(me.vehicle, 1087) -- add hydra again
```
