### ISSUE TITLE
Use vs19 if vs17 failure in win-build.bat

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1122]
**Describe the bug**
win-build.bat throws erros even i have vs17 ( and 19 ) installed

**To reproduce**
be CrosRoad95 and run win-build.bat with vs17 and vs19

**Expected behaviour**
Should work :(

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/66859715-206d3a80-ef8c-11e9-95fd-2766bee898b7.png)

**Version**
/

**Additional context**
Swamp > samp

**Comment by sbx320** [comment]
Does this still happen after b908aa8684b305a5c2fe564e6211c458022eb23d?

**Comment by ccw808** [comment]
Yes
