### ISSUE TITLE
DDoS like behaviour with playSound3D (again!)

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#1124]
**Describe the bug**
creating a 3D sound element (stream url) at the position of local player but in another domension
results in DDoS like connection / disconnection attacks to the streaming URL

**To reproduce**

start runcode
crun setElementPosition(localPlayer,0,0,5)
crun sound=playSound3D ('http://127.0.0.1:8000/listen.pls', 0,0,2 ) 
crun setElementDimension(sound,1)

from the control panel of the shoutcast server:
![grafik](https://user-images.githubusercontent.com/12788736/67099340-0fa40b00-f1be-11e9-88c7-83b038490538.png)

**Expected behaviour**
There should be no connection to the audio source when player and sound element are in different dimensions.

**Version**
Multi Theft Auto v1.5.7-release-20314

**Additional context**

**Comment by xLive** [comment]
I hope the problem will be solved,
 Any way you can disable external sounds from the settings if you want to _play_ in a server they trying to attack you.

**Comment by ccw808** [comment]
afb2a70 did not fix it

**Comment by Dutchman101** [comment]
Fixed in a99ea2c (not any of the above)
