### ISSUE TITLE
"accuracy" doesn't exists in MTA source code, but it's on wiki

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1125]
**Describe the bug**
https://wiki.multitheftauto.com/wiki/GetObjectProperty and https://wiki.multitheftauto.com/wiki/SetObjectProperty
"accuracy" doesn't exist in source code but it's on wiki

**To reproduce**
1. `crun getObjectProperty(getElementsByType("object")[1], "accuracy")`
2, Bad argument @ 'getObjectProperty' [Expected object-property at argument 2, got string 'accuracy']

**Version**
 v1.5.7-release-20288

**Comment by Unde-R** [comment]
I think It's fixed.
