### ISSUE TITLE
Make possible skip GTA:SA screen

### ISSUE THREAD

**Issue by stoneage-mta** [multitheftauto/mtasa-blue#1132]
**Is your feature request related to a problem? Please describe.**

I may be wrong, but I think 200% of players hate this screen, so it would be fair to add an option to skip this boring screen.
**Describe the solution you'd like**
![unknown](https://user-images.githubusercontent.com/38073795/67580431-ba677c80-f71c-11e9-8a83-0827d48f42a2.png)

**The most boring screen in the world:**
![Screenshot_1](https://user-images.githubusercontent.com/38073795/67580480-ca7f5c00-f71c-11e9-9f10-9aecce141071.png)

**Comment by Haxardous** [comment]
This can’t be possible, all rights go to R* & MTA doesn’t want any legal issues, read the text below to understand. 

You made something, you have the rights for it.

**Comment by ArranTuna** [comment]
99.99% sure this won't be done because it would have been done by now already when the other bits were removed because of what Hazardous said.
