### ISSUE TITLE
bitExtract is broken (client side)

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#1135]
**Describe the bug**
bitExtract doesn't work (client side)

**To reproduce**

> function toRGBA(color)
> 	local b = bitExtract(color, 0, 8)
> 	local g = bitExtract(color, 8, 8)
> 	local r = bitExtract(color, 16, 8)
> 	local a = bitExtract(color, 24, 8)
>     return r, g, b, a
> end
> 
> local color = tocolor(123, 234, 196, 255)
> print(toRGBA(color))

**--> Always return 255**
**Serverside working properly**

> Clientside Runcode: tocolor(255, 200, 100, 255)
> Result: -14236 [number]
> 
> srun bitExtract("-14236", 0, 8)
> Result: 100 [number]
> srun bitExtract("-14236", 8, 8)
> Result: 200 [number]

**Version**
Multi Theft Auto v1.5.7-release-20325
Tested also on
Multi Theft Auto v1.5.7-release-20332

**Comment by ghost** [comment]
This is not a bug. You're not properly extracting rgba.
(In your case, `b` should also be 8 bytes)

Here's a working example:
```lua
local color = tocolor(123, 234, 196, 255) 
local b = bitExtract(color, 0, 8)
local g = bitExtract(color, 8, 8)
local r = bitExtract(color, 16, 8)
local a = bitExtract(color, 24, 8)

iprint("color rgb", r, g, b, a)
```

// request close

**Comment by Xenius97** [comment]
Not working with that! I forgot put back to 8, I tested.

**Comment by Xenius97** [comment]
This is a real bug, I tested everything but it's broken! It worked 3-4 days ago. I think mta developers update something.

**Comment by ghost** [comment]
It still works for me on latest nightly. Can you share full example code ?.

![image](https://user-images.githubusercontent.com/8040605/67608788-12889800-f78a-11e9-916a-56bc54c96e6d.png)

```lua
local color = -14236
local b = bitExtract(color, 0, 8)
local g = bitExtract(color, 8, 8)
local r = bitExtract(color, 16, 8)
local a = bitExtract(color, 24, 8)

iprint("color rgb", color, r, g, b, a)
```
does work as expected on client.

**Comment by Xenius97** [comment]
My code is in first post. For me it returns 255 255 255 255 always. I tested with runcode and with that script, only serverside working.

**Comment by Einheit-101** [comment]
I can not confirm this bug either. I am using this on my server for a decade and i just tested it in map editor, mta build v1.5.7-release-20288

**Comment by Xenius97** [comment]
Working with Multi Theft Auto v1.5.7-release-20324

**Comment by StrixG** [comment]
Can confirm this bug on Multi Theft Auto v1.5.7-release-20332. It seems like updating to VS2019 has broken some functions.

**Comment by ccw808** [comment]
Please test latest build on https://nightly.mtasa.com/

**Comment by Xenius97** [comment]
@ccw808 not working

Runcode: bitExtract(tocolor(200, 100, 50, 150), 0, 8)
Result: 255 [number]
Runcode: bitExtract(tocolor(200, 100, 50, 150), 8, 8)
Result: 255 [number]

**Comment by Dutchman101** [comment]
> Can confirm this bug on Multi Theft Auto v1.5.7-release-20332. It seems like updating to VS2019 has broken some functions.

It could be that vs2019 broke more than the single other case known: 53121a3
But no stress, so far it's just a nightly

**Comment by ccw808** [comment]
`argStream.ReadNumber` is broken when reading negative values into an unsigned variable

See https://developercommunity.visualstudio.com/content/problem/519454/using-static-cast-to-cast-a-large-negative-double.html

**Comment by ccw808** [comment]
Please test latest build

**Comment by Xenius97** [comment]
Fixed, thank you @ccw808
