### ISSUE TITLE
getKeyState("rctrl") and getKeyState("lctrl") always return true when holding Ralt with UK keyboard

### ISSUE THREAD

**Issue by thisdp** [multitheftauto/mtasa-blue#1139]
**Describe the bug**
getKeyState("rctrl") and getKeyState("lctrl") always return true when holding Ralt with UK keyboard
While onClientKey doesn't get triggered.
**To reproduce**
Steps to reproduce the behaviour:
1.[See this Image](https://cdn.discordapp.com/attachments/278520948347502592/638351960872976385/unknown.png)
2. Press ralt
3. Both getKeyState("rctrl") and getKeyState("rctrl") return true even you don't hold them

**Comment by thisdp** [comment]
`[https://github.com/multitheftauto/mtasa-blue/issues/url](url)

**Comment by thisdp** [comment]
[](https://cdn.discordapp.com/attachments/442684706904080406/638354021215764501/unknown.png)

**Comment by qaisjp** [comment]
Duplicate of #367

**Comment by thisdp** [comment]
> Duplicate of #367

Not the same problem. This problem is about R ALT affecting CTRL

**Comment by qaisjp** [comment]
> This happens for "lshift", "lalt", "lctrl", "rshift", "ralt", "rctrl" as well.

The above text is in the issue text.

**Comment by thisdp** [comment]
> > This happens for "lshift", "lalt", "lctrl", "rshift", "ralt", "rctrl" as well.
> 
> The above text is in the issue text.

But it doesn't mention "UK Keyboard"

**Comment by qaisjp** [comment]
Oh I see, `ralt` affecting `ctrl`. Hmm, okay. Seems related.

**Comment by thisdp** [comment]
> Oh I see, `ralt` affecting `ctrl`. Hmm, okay. Seems related.

Maybe related, because getKeyState is buggy. lol anyway.

**Comment by botder** [comment]
@thisdp can you test with latest nightly again? This issue might be already resolved.
Can you also test issue #367 too?
I have included a simple test resource.

[keystate.zip](https://github.com/multitheftauto/mtasa-blue/files/5793094/keystate.zip)

**Comment by thisdp** [comment]
Fixed! Thanks
