### ISSUE TITLE
onClientPlayerWeaponSwitch should trigger for remote players

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1141]
**Is your feature request related to a problem? Please describe.**
onClientPlayerWeaponSwitch doesn't trigger when weapon slot is changed for remote players.

**Describe the solution you'd like**
It should trigger also for remote players. If possible.

**Describe alternatives you've considered**
At the moment, there's no possibility to detect changes for weapon slot, the only possibility is using loop. (for render usage f.e)

**Additional context**
It would be very nice, if we could detect those changes on client-side by event provided by MTA.
I think this is possible to do, since onClientPlayerWeaponFire triggers for local/remote player.

**Comment by sbx320** [comment]
We'd probably need a new event name, as scripts may rely on the event triggering only for the local player.
