### ISSUE TITLE
libcef.dll crash

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#1147]
**Describe the bug**
libcef.dll crash

**To reproduce**
Randomly happens

**Log**
>  ** -- Unhandled exception -- **
> 
> Version = 1.5.7-release-20339.0.000
> Time = Fri Nov  8 09:49:01 2019
> Module = D:\Games\MTA San Andreas\MTA\libcef.dll
> Code = 0x80000003
> Offset = 0x00AE0F10
> 
> EAX=666C8B01  EBX=666C8AD8  ECX=00000000  EDX=00000000  ESI=666DD8B8
> EDI=00000500  EBP=3D1CF78C  ESP=3D1CF6B0  EIP=5A440F10  FLG=00000202
> CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
> 
> ** -- End of unhandled exception -- **
> 
> 
> ** -- Unhandled exception -- **
> 
> Version = 1.5.7-release-20343.0.000
> Time = Fri Nov  8 09:55:40 2019
> Module = D:\Games\MTA San Andreas\MTA\libcef.dll
> Code = 0x80000003
> Offset = 0x00AE0F10
> 
> EAX=6AD1FD01  EBX=6AD1FD38  ECX=00000000  EDX=00000000  ESI=6AFAD440
> EDI=00000500  EBP=418CF78C  ESP=418CF6B0  EIP=5A4C0F10  FLG=00000202
> CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
> 
> ** -- End of unhandled exception -- **

**Version**
Multi Theft Auto v1.5.7-release-20343

**Additional context**
Dumps: [https://upload.mtasa.com/u/128198394/dumps.zip_](https://upload.mtasa.com/u/128198394/dumps.zip_)

**Comment by Lpsd** [comment]
Please provide steps to reproduce the crash, preferably a very simple code snippet.

FYI, this is most likely related to creating multiple browsers in a short space of time, whether you are doing this on purpose or there is some dodgy logic in your code.

**Comment by Xenius97** [comment]
@Lpsd I can't provide with code, because i don't know why CEF crashes. This began after we started to use engineRequestModel
I have 10 dumps, in first message.

https://github.com/multitheftauto/mtasa-blue/issues/1137

**Comment by Lpsd** [comment]
engineRequestModel isn't related to CEF, so it won't be to do with usage of that function.

Someone else should be able to provide more info.

**Comment by Pirulax** [comment]
I guess 2 eventHandlers are called from another threads which causes the event triggerer to fuck up somehow.
