### ISSUE TITLE
Restarting the resource doesnt stop passwordHash

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#1152]
**Describe the bug**

Alright, so I put cost = 20, just for fun, and noticed that if I restart the resource the hashing keeps going.

**To reproduce**

```lua
passwordHash("lol", "bcrypt", {cost = 20}, function() end)
```

**Expected behaviour**

stop the async hashing.

**Version**

Multi Theft Auto v1.5.7-release-20288

**Comment by Pirulax** [comment]
Oh well, shouldnt be hard to fix by myself.

**Comment by Pirulax** [comment]
Should I fix it?
Or its not that important?

**Comment by qaisjp** [comment]
It's in the backlog, so a planned feature. Please do send a pull request!

**Comment by qaisjp** [comment]
I don't think this is fixable. These functions use `std::thread` underneath.

See https://en.cppreference.com/w/cpp/thread/thread: `(destructor) | destructs the thread object, underlying thread must be joined or detached`

Also see "How do I terminate a thread in C++11?" https://stackoverflow.com/a/12207835/1517394

There are other suggestions here but I don't think this is worth working on: https://stackoverflow.com/questions/13893060/i-want-to-kill-a-stdthread-using-its-thread-object

I propose just marking this as _wontfix_ and closing it.

**Comment by Citizen01** [comment]
Might just be qualified as an inconvenient behavior rather than a real bug if you ask me.

**Comment by qaisjp** [comment]
> Should I fix it?

If you have a potential fix to suggest please feel free to reopen (or request a reopen)
