### ISSUE TITLE
CEF web browser crash

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1156]
**Describe the bug**
Destroying the browser and recreating it on the render causes crash in most cases

**To reproduce**
```
addCommandHandler( "crashme", function( )
	local browser = guiCreateBrowser( 0, 0, 100, 100, true, true )

	addEventHandler( "onClientRender", root, function ( )
		if not DO_ON_NEXT_FRAME then return end

		destroyElement( browser )
		
		browser = guiCreateBrowser( 0, 0, 100, 100, true, true )

		DO_ON_NEXT_FRAME = nil
	end )

	setTimer( function()
		DO_ON_NEXT_FRAME = true
	end, 50, 5 )
end )
```

**Version**
1.5.7-release-20348.0.000

**Additional context**
Version = 1.5.7-release-20348.0.000
Time = Mon Nov 18 16:31:34 2019
Module = C:\Windows\SYSTEM32\D3D9.DLL
Code = 0xC0000005
Offset = 0x0005D3DC

EAX=0DD60C28  EBX=0A8EEB00  ECX=00000000  EDX=00000000  ESI=672BC110
EDI=672BC170  EBP=0177FB8C  ESP=0177FB78  EIP=7196D3DC  FLG=00210202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

[dumps.zip](https://github.com/multitheftauto/mtasa-blue/files/3858384/dumps.zip)

**Comment by ghost** [comment]
Another one
```
addCommandHandler ( "crashme2", function( )	
	local browsers = {}
	
	local function createBrowsers( )
		for i = 1, 5 do
			browsers[i] = createBrowser( 100, 100, true, true )
			
			addEventHandler( "onClientBrowserCreated", browsers[i], function ( )
				loadBrowserURL( browsers[i], "http://mta/local/empty.html" )
			end )
		
			addEventHandler( "onClientBrowserDocumentReady", browsers[i], function( url )
				DO_ON_NEXT_FRAME = true
			end )
		end
	end
	createBrowsers( )
	
	addEventHandler( "onClientRender", root, function( )
		if DO_ON_NEXT_FRAME then		
			for i = 1, 5 do
				destroyElement( browsers[i] )
			end			
			createBrowsers( )

			DO_ON_NEXT_FRAME = nil 
		end
	end )
end )
```
[dumps2.zip](https://github.com/multitheftauto/mtasa-blue/files/3858563/dumps2.zip)

**Comment by patrikjuvonen** [comment]
Seems like a waste of time to try to fix.
