### ISSUE TITLE
setElementVisibleTo returns true even if it does not work

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#1171]
**Describe the bug**
When using setElementVisibleTo on things that you can't change the visibility of (like vehicles, objects or custom elements) you will get a true returned by the function, even tho it should return false

**To reproduce**

Just run this:
```lua
local veh = createVehicle(421, 2104.2, -1734.4, 13.6)
outputChatBox(tostring(setElementVisibleTo(veh, root, true)))
outputChatBox(tostring(setElementVisibleTo(veh, root, false)))
```

**Expected behaviour**
This should return false as it does not work

**Version**
Windows 10 Client: v1.5.7-release-20348
Windows 10 Server: v1.5.7-realease-20320

**Comment by Lpsd** [comment]
Oops, I thought this was resolved on master but it's on that guy's fork. I'll test it later and merge.
