### ISSUE TITLE
Crash offset 0x01D07772 in libcef.dll

### ISSUE THREAD

**Issue by haron4igg** [multitheftauto/mtasa-blue#1180]
Player continuosly crashing during connection to game-server.

```
** -- Unhandled exception -- **

Version = 1.5.7-release-20357.0.000
Time = Fri Dec  6 20:37:14 2019
Module = C:\Program Files\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0x80000003
Offset = 0x01D07772

EAX=6B36FD28  EBX=00000000  ECX=6191DB4C  EDX=00000008  ESI=6B36FD40
EDI=6B36FD58  EBP=6B36FD34  ESP=6B36FD28  EIP=79767772  FLG=00000206
CS=001B   DS=0023  SS=0023  ES=0023   FS=003B  GS=0000

** -- End of unhandled exception -- **
```

[client_1_5_7-release-20357_0_000_libcef_01d07772_3_CPrMb_5774DE53_55F3_1D0_CDF47_20191206_2037_rsa.zip](https://github.com/multitheftauto/mtasa-blue/files/3933818/client_1_5_7-release-20357_0_000_libcef_01d07772_3_CPrMb_5774DE53_55F3_1D0_CDF47_20191206_2037_rsa.zip)

**Comment by patrikjuvonen** [comment]
@haron4igg Is this still an active issue?

**Comment by haron4igg** [comment]
It was appearing under some sircumstances, which is not possible to reproduce anymore. Probably related to heavy rendering activity in CEF on weak PC. Since i changed implementation of that feature, it wasn't appearing anymore within those user.

**Comment by patrikjuvonen** [comment]
Okay, if this happens again please provide crash dump and reproduction code.
