### ISSUE TITLE
MTA Crash when streaming in custom IDs created with engineRequestModel

### ISSUE THREAD

**Issue by Brian9221** [multitheftauto/mtasa-blue#1182]
**Describe the bug**
Many players and I keep facing a random crash related to custom ped IDs obtained with engineRequestModel. The crash usually happens when streaming in the ped. 

Version = 1.5.7-release-20348.0.000
Time = Sat Dec  7 19:09:34 2019
Module = C:\Program Files (x86)\MTA San Andreas 1.5\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x00050931

EAX=01C3D5B0  EBX=1B4AD140  ECX=01C3D5B0  EDX=01A90000  ESI=01C3D5B0
EDI=4D91D510  EBP=0177F96C  ESP=0177F934  EIP=48764C2A  FLG=00210297
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

--

Version = 1.5.7-release-20357.0.000
Time = Fri Dec  6 20:25:05 2019
Module = C:\Program Files (x86)\MTA San Andreas 1.5\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x00050952

EAX=2A4AFA08  EBX=1933E730  ECX=2CC0BD18  EDX=0000000F  ESI=273723D0
EDI=4BF4A858  EBP=0177F96C  ESP=0177F930  EIP=00000000  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

--

I have installed the latest MTA nightly. the 2 offsets above are the most common crash outputs of those players who keep facing this issue.

If necessary I'll make a test resource to check this bug.

**Comment by ccw808** [comment]
Possibly caused by https://github.com/multitheftauto/mtasa-blue/blob/7aa58dff62986f27d0f304b953e26098072428ba/Client/mods/deathmatch/logic/CClientModelRequestManager.cpp#L150 being called during CClientModelRequestManager::DoPulse()

**Comment by ArranTuna** [comment]
If you need more crash info there will be probably hundreds of crash recordings in that MTA crash handler thingy from today and yesterday, many players have complained about the crashing.

**Comment by Brian9221** [comment]
Another common crash offset:

** -- Unhandled exception -- **

Version = 1.5.7-release-20357.0.000
Time = Sun Dec  8 13:26:39 2019
Module = C:\Program Files (x86)\MTA San Andreas 1.5\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x0005094F

EAX=00003489  EBX=17CDE438  ECX=34890152  EDX=0000000F  ESI=2EC7E500
EDI=4245B370  EBP=0028F984  ESP=0028F94C  EIP=599B094F  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **

**Comment by ccw808** [comment]
Please provide a resource which causes the crash

**Comment by Brian9221** [comment]
I sent you a forum PM with a copy of the resource we're currently using and that is responsible of crashes. @ccw808
