### ISSUE TITLE
New Account Events

### ISSUE THREAD

**Issue by Lettify** [multitheftauto/mtasa-blue#1184]
This is just an idea for developing new events for server accounts.

Occasionally, I thought about two events. One would be triggered when changing the password of an account. Another could be triggered when an account is deleted. 

More account events can be created, but these two are good examples.

I hope you understood what I said. Thank you very much for your attention.

**Comment by Lpsd** [comment]
You can script your own custom events to do this. You could even create a wrapper for the `setAccountPassword` and `removeAccount` functions to trigger your custom event automatically.
