### ISSUE TITLE
Add db connections to work with getElementsByType

### ISSUE THREAD

**Issue by DNL291** [multitheftauto/mtasa-blue#1185]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to return the active DB connections through a native function, only by returning the element directly from dbConnect.

**Describe the solution you'd like**
Doing this for **getElementsByType** is the most viable solution I can think of.

**Additional context**
This would make it possible to make scripts in which returns the active connections and manage them without having to use the returned element from the function. Or even for simpler tasks such as running _getElementsByType ("db-connection")_ via runcode.

**Comment by ccw808** [comment]
DB connections are excluded from getElementsByType for security reasons
