### ISSUE TITLE
Add `getPedTargetRange`

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1186]
**Is your feature request related to a problem? Please describe.**

`getPedTargetRange` aswell as `getPlayerTargetRange` were added but they were actually never 'implemented'.

**Describe the solution you'd like**

This function should retrieve a ped's target range when he is aiming with a weapon.

**Describe alternatives you've considered**

Add `getPedTargetRange` (or remove it from the source code since it was never working)

**Additional context**

https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp#L667

**Comment by qaisjp** [comment]
Despite a stub already existing in the code, this is going to be treated as a brand new feature request. Please fill in the fields, explain the functionality and why you think it should be added, thank you!

**Comment by ghost** [comment]
> Despite a stub already existing in the code, this is going to be treated as a brand new feature request. Please fill in the fields, explain the functionality and why you think it should be added, thank you!

done

**Comment by qaisjp** [comment]
If someone needs this function, please feel free to open an issue detailing what you need this feature for and how you are going to use it.
