### ISSUE TITLE
set/getServersideElementData

### ISSUE THREAD

**Issue by javadomidi** [multitheftauto/mtasa-blue#1187]
an unoverrideable data by client
instead of saving datas in a resource and sharing it via exports or events

**Comment by AfuSensi** [comment]
You could protect element data with the event `onElementDataChange` and checking its source to determine if it should be canceled.
Check https://wiki.multitheftauto.com/wiki/Script_security
In my opinion, this function isnt really necessary.

**Comment by qaisjp** [comment]
Yes, this sort of function will never be added.

Although, contrary to my previous statements, I agree, maybe it should be possible to declare certain keys as "protected", "unsynced" or "private", perhaps using some sort of prefix...
