### ISSUE TITLE
Add setElementType function

### ISSUE THREAD

**Issue by goodluck456** [multitheftauto/mtasa-blue#1189]
**Is your feature request related to a problem? Please describe.**
In one of my scripts that requires many players to test it, it's pretty much impossible to get many players to test it. So one of the ways this could be solved is by adding a setElementType function.

**Describe the solution you'd like**
If this function were to be added, it might allow us to be able to create peds and then setting them as player elements. By setting them as player elements, we can use those peds, or players in this case, for debugging purposes. In this function, you would choose an already existing element and then choose its new element type.

**Describe alternatives you've considered**
Not that I know of.

**Additional context**

**Comment by AfuSensi** [comment]
I think this would break the game.
Putting a ped element to a player element wouldnt magically make it an actual player.
I feel like your approach to debugging isnt right. If you want to check your script with multiple players, you need multiple players. Either a virtual machine or by having actual players join your server for debugging. Changing elements of peds would not help with that.

**Comment by Einheit-101** [comment]
Or change "player" to "ped" in your script file and test it really with peds instead, which may not be always possible. But if you think just faking players by creating brainless peds would be enough, it will work in your case.

**Comment by qaisjp** [comment]
I agree there should be better ways to test interaction with multiple players, but I don't think this is the way to do it.

I doubt this sort of function will _ever_ be implemented, so it's better for me to close it than leave it open forever.
