### ISSUE TITLE
Add "ipb" to default startup resources

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#1217]
Would it be a good idea to add [ipb](https://github.com/multitheftauto/mtasa-resources/tree/master/%5Badmin%5D/ipb) (ingame performance browser) to default startup resources in mtaserver.conf?

I think that sending high usage warnings to all online admins when a script begins to mess up (or starts getting abused by someone to cause load) can be really helpful, and I can't think of any cons. Since we always aim to provide ideal configuration..

**Comment by Dutchman101** [comment]
Should we also use it for local and map editor configs? I think that can also be helpful to identify problems during the creation process (e.g scripting, or loading maps that demand too much so they can notice and resolve it on the spot)

**Comment by qaisjp** [comment]
Good idea (I doubt non-scripters use the local server anyway)

**Comment by CrosRoad95** [comment]
what about `map performance browser` focused on map, rendering ect? not really scripts?

**Comment by Dutchman101** [comment]
qaisjp Today at 5:38 PM
@Dutchman101 go for the commit

Done, fixed in 2bebc75
