### ISSUE TITLE
An opportunity to pass preprocessor definitions for shaders

### ISSUE THREAD

**Issue by tederis** [multitheftauto/mtasa-blue#1220]
**Is your feature request related to a problem? Please describe.**
D3DX effects offer us an argument for passing preprocessor definition. It's would be great to add an opportunity to pass these defines to shader simply by calling `dxCreateShader(string filepath / string raw_data [, float priority = 0, float maxDistance = 0, bool layered = false, string elementTypes = "world,vehicle,object,other", string defines = "" ])`. It also would be helpful because in some cases shaders contain reusable parts. We can write just one shader for many cases simply putting correspondig macros among the codelines. It also opens a simple way to activate debug parts within a shader without any shader modifications.

**Describe the solution you'd like**
I suggest to add a new argument to function dxCreateShader. In example `dxCreateShader(string filepath / string raw_data [, float priority = 0, float maxDistance = 0, bool layered = false, string elementTypes = "world,vehicle,object,other", string defines = "" ])`.

**Describe alternatives you've considered**
There is no alternative at the moment

**Comment by qaisjp** [comment]
sounds reasonable. why is `defines` a string? i don't have much experience with shaders but i'd expect it to be a table?

**Comment by tederis** [comment]
> sounds reasonable. why is `defines` a string? i don't have much experience with shaders but i'd expect it to be a table?

I supposed the same syntax as elementTypes argument. Like "DEFINE1,DEFINE2,etc". But tables would be more powerful: `{ ["DEF1"] = true, ["DEF2"] = "0", ["DEF3"] = 5.43 }`. Yes, I think we should use the table instead.

**Comment by qaisjp** [comment]
Something to also consider would be ordering of defines, assuming defines can include other defines :)

**Comment by tederis** [comment]
> Something to also consider would be ordering of defines, assuming defines can include other defines :)

Ordering of defines is upon the coder. If any suspicious cases appear the compiler should tackle it and throw an error message. In theory :)

**Comment by qaisjp** [comment]
Indeed although a dictionary like you presented above would not have any order. It would be to be something like this:

```lua
defines = { 
    { DEF1 = true },
    { DEF2 = "Hello $DEF1" },
    { ["ADD(a,b)"] = "(a+b)" },
    "SUB(a,b) (a-b)"
}
```

If that makes sense to you? Not sure if a plain string is better than a nested table in this case.

**Comment by tederis** [comment]
> Indeed although a dictionary like you presented above would not have any order. It would be to be something like this:
> 
> ```lua
> defines = { 
>     { DEF1 = true },
>     { DEF2 = "Hello $DEF1" },
>     { ["ADD(a,b)"] = "(a+b)" },
>     "SUB(a,b) (a-b)"
> }
> ```
> 
> If that makes sense to you? Not sure if a plain string is better than a nested table in this case.

My bad. I'm sorry. I just misunderstood you somehow. You are right, the best way to approach a correct order is using the structure you have proposed. So, finally we have a function `dxCreateShader( string filepath / string raw_data [, float priority = 0, float maxDistance = 0, bool layered = false, string elementTypes = "world,vehicle,object,other", table defines = { { def0 = value0 }, { def1 = value1 }, ... } ] )`
