### ISSUE TITLE
Regression: double chat messages if player is in team

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#1223]
**Describe the bug**
As a result of d2c53c7, a player that is part of a team will see all chat messages being duplicated, if there is a custom chathandler on the server (cancelling `onPlayerChat` and processing the messages itself). Therefore, the change breaks existing scripts.

You can say that it's a niche issue, but one of the default MTA resources (`freeroam`) uses a custom chathandler and therefore is affected. MTA should never break any existing scripts.

**To reproduce:**
1. Start a resource with a custom chathandler, e.g:

```lua
addEventHandler("onPlayerChat", root,
    function(msg, type)
        if type == 0 then
            cancelEvent()

            if isElement(source) then
                local r, g, b = getPlayerNametagColor(source)
                outputChatBox(getPlayerName(source) .. ": #FFFFFF" .. msg:gsub("#%x%x%x%x%x%x", ""), root, r, g, b, true)
                outputServerLog("CHAT: " .. getPlayerName(source) .. ": " .. msg)
            end
        end
    end
)
```

2. Create and enter a team
3. Send a message in the global chat
4. Observe the double messages (of everyone on the server, including yourself):
![dup](https://user-images.githubusercontent.com/12105539/73044098-70e81400-3e68-11ea-9dc6-9c2412d235d6.png)

**Version**
Server: v1.5.7-release-r20391

**Additional context**
Not reproducible on Server: v1.5.7-release-r20386 so it's clearly a result of d2c53c7

**Comment by Dutchman101** [comment]
24a233f doesn't fix this issue.

Did you test your fix, @xLuxy?

**Comment by ghost** [comment]
Yes i did @Dutchman101, test resource was attached in that PR including a screenshot of it working.

**Comment by Dutchman101** [comment]
> Yes i did @Dutchman101, test resource was attached in that PR including a screenshot of it working.

I can still reproduce this using the exact same steps as in this issue's description (Server r20397).

Note: my repro is easily performed and simplified by getting all default resources, running play (freeroam) mode, creating a team using admin panel and putting yourself into this team through the panel. Then write something in chat. This in itself is proof that it continues affecting existing gamemodes/scripts.. (I can't try your repro resource right now)
