### ISSUE TITLE
bug, GetResourceFromName value "false"

### ISSUE THREAD

**Issue by cyberdzot** [multitheftauto/mtasa-blue#1227]
This function does not work on the server side (Linux) at least, but it works on the Windows server.
https://wiki.multitheftauto.com/wiki/GetResourceFromName

Does not work, it meant that it gets the value (false) instead of the resource itself.

**Comment by cyberdzot** [comment]
I noticed that on another hosting the server-side function (Linux) works well. Server assemblies are the same ...
What could be the problem?

**Comment by ghost** [comment]
Request close - see https://discordapp.com/channels/278474088903606273/366384007535001612/671027677674733568 and my comment below.

He tried the following code which would never work properly because getResources is not guranteed to return the running resource first. This is also why he has warnings simlar like ```Bad argument @ 'startResource' [Expected resource-data at argument 1, got nil]```

```lua
local startupResources =
{
    'script_1',
    'script_2',
}
local endupResources    = {}
local resName            = getResourceName( getThisResource() )
local allResources        = {}



local checkAllResources =
function()
    local all_res_table            = getResources()
    for _, res in pairs( all_res_table ) do
        local name                = getResourceName( res )
        allResources[ name ]    = res
    end
end

local startRes =
function( res )
    startResource( res )
end

addEventHandler( 'onResourceStart', root,
function( res )
    
    local next_res    = startupResources[ 1 ]
    if next_res ~= nil then
        local curr_res    = getResourceName( res )
        local end_res    = endupResources[ #endupResources ]

        if curr_res == resName then
            checkAllResources()
        end
        if curr_res == end_res or curr_res == resName then
            table.insert( endupResources, next_res )
            table.remove( startupResources, 1 )
            setTimer( startRes, 100, 1, allResources[ next_res ] )
        end
    end
end
)
```
