### ISSUE TITLE
vehicle moving when engine is off

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1231]
When the engine state is false and I press the key to move the vihicle to back, the car starts to move. Speed is very low, but vehicle moves. Also when the vehicle is moving backwards freely (when the speed is typed and the engine state is false), pressing the key to move the vehicle to back maintains the current speed, instead of stopping smoothly.

**Comment by tut001** [comment]
What you're getting is the effect of not applying hand brake. The car should be able to freely move forwards/backwards when on a slope, even if the engine is idling or completely off.
I'm not sure if this is really a bug, but am certain it can be scripted to prevent it from rolling when engine is off.

**Comment by dmi7ry** [comment]
> I'm not sure if this is really a bug

It is definitely not a bug

**Comment by Woovie** [comment]
This is standard GTA San Andreas behavior.
