### ISSUE TITLE
getResourceFromName returns false with loaded resources in client side

### ISSUE THREAD

**Issue by thisdp** [multitheftauto/mtasa-blue#1232]
**Describe the bug**
getResourceFromName returns false when the target resource is not started in client side.

**To reproduce**
1. getResourceFromName( theLoadedResource )

**Expected behaviour**
getResourceFromName should return a resource instead of false even the resource doesn't get started.

**Version**
Client Side: 1.5.7 9.20358.1

**Comment by qaisjp** [comment]
What are you using this for? ~~Are you sending the resource element through an event?~~ (edit: oh, this is _fromName_, so there's no handle to a resource)

**Comment by thisdp** [comment]
> What are you using this for? Are you sending the resource element through an event?

check whether the resource exists and whether the resource is started in client

**Comment by ccw808** [comment]
Maintaining a list of loaded resources (which could run into thousands) on each client is impractical and could possibly be a security & privacy issue as well

**Comment by thisdp** [comment]
> Maintaining a list of loaded resources (which could run into thousands) on each client is impractical and could possibly be a security & privacy issue as well

But why this point didn't imply on wiki?

**Comment by qaisjp** [comment]
> But why this point didn't imply on wiki?

Where should it say this on the wiki? Please feel free to update it 🙂.

**Comment by thisdp** [comment]
> > But why this point didn't imply on wiki?
> 
> Where should it say this on the wiki? Please feel free to update it 🙂.

Because nobody tell me why it returns false. I ask in discord, and somebody tell me report this as a bug. lol

**Comment by qaisjp** [comment]
Ah, that's what you mean.

Yeah, I think this was a side effect of us simply not making the client aware of resources in the "loaded" state. That might be the reason it wasn't documented.

 Thank you very much for updating the wiki!
