### ISSUE TITLE
New function dxDrawModel

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1237]
Hi! I suggest creating a new function to draw _skin_ or _vehicle_ or _object_ or _weapon_ on the screen.

**Syntax:**
```
dxDrawModel(
    int skin/vehicle/object/weapon,
    float leftX,
    float topY,
    float rightX = leftX,
    float bottomY = topY,
    int color = white,
    float mRotX,
    float mRotY,
    float mRotZ,
    ...
)
```

**Arguments**
- **skin/vehicle/object/weapon** - id of skin or vehicle or object or weapon
- **leftX, topY, rightX, bottomY** - positions on screen
- **color** - color of model, example color of vehicle
- **mRotX, mRotY, mRotZ** - rotation of model
- ... and other arguments

This function will be useful for example:
- buying weapons
- сar tuning
- selecting object for building
...

**Comment by Lpsd** [comment]
This can be done with Lua and shaders - in fact there's already a resource that does this: https://wiki.multitheftauto.com/wiki/Resource:Object_preview

**Comment by Petya0x44** [comment]
> This can be done with Lua and shaders - in fact there's already a resource that does this: https://wiki.multitheftauto.com/wiki/Resource:Object_preview

Maybe it will be better if this function will be integrate into MTA?

**Comment by Lpsd** [comment]
I don't think there's any reason to implement this into MTA - it works fine with Lua/shaders.

**Comment by qaisjp** [comment]
I'm inclined to agree with the @Lpsd. Is there any particular reason why you'd like this function in MTA and why the resource does not work for you?

**Comment by Petya0x44** [comment]
> I'm inclined to agree with the @Lpsd. Is there any particular reason why you'd like this function in MTA and why the resource does not work for you?

I did not say that this resource does not work for me. I think this function would make work easier for a programmer who does not need to look for this resource as long as it is integrated into the MTA and the player does not need to download the extra resource... Although I may not be right as these reasons are not good enough. That was my suggestion, thank you for your feedback

**Comment by ffsPLASMA** [comment]
Maybe instead of first argument being the model ID, use an element instead. Currently you can apply shaders only to model IDs and world textures. A feature on C++/Lua side to apply a texture to a single element would be great.

**Comment by CrosRoad95** [comment]
My project, #1211 will let you do this but in slightly different way

**Comment by Lpsd** [comment]
> Maybe instead of first argument being the model ID, use an element instead. Currently you can apply shaders only to model IDs and world textures. A feature on C++/Lua side to apply a texture to a single element would be great.

@ffsPLASMA You can already do this, see the 3rd argument (`targetElement`) of `engineApplyShaderToWorldTexture`

**Comment by ffsPLASMA** [comment]
Yes but you still need to create shader. Wouldn't it be better performancewise if you just apply the texture with desired pos/rot to the element instead of using shader rendertargets?

**Comment by qaisjp** [comment]
Thank you very much for the suggestion. 

> make work easier for a programmer who does not need to look for this resource as long as it is integrated into the MTA

I agree we definitely should make utilities like these easier to find. I think this is the core problem we need to solve, rather than integrating this into MTA directly.
