### ISSUE TITLE
Compiling Lua changes the return value of getComponentPosition method

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#1239]
By compiling your script on [luac.mtasa.com](https://luac.mtasa.com/) (using **option 3**) it changes the return values of the getComponentPosition method.

I have only tested this with the `getComponentPosition` method, and can confirm that this only occurs using extra obfuscation option 3 (the other obfuscation options work fine).

Example code:

```lua
function init()
	local vehicle = createVehicle(411, 0, 0, 0)
	
	local x, y, z = vehicle:getComponentPosition("chassis")
	
	iprint(x, y, z)
end
addEventHandler("onClientResourceStart", resourceRoot, init)
```

**Uncompiled**
Prints: 0, 0, 0

**Compiled**
Prints: vector3: { x = 0.000, y = 0.000, z = 0.000 }, nil, nil

Note: other OOP methods such as `getPosition` return a Vector3 in all cases - haven't had chance to look into the code for `getComponentPosition` yet, but it should be returning a Vector3 by default too.

Wonder if this happens with other methods too?

**Comment by ccw808** [comment]
It seems that :getComponentPosition will only return a Vector3 if the client min_mta_version is 1.5.5-9.11710 or higher

**Comment by ccw808** [comment]
See #1240
