### ISSUE TITLE
Rocket doesn't trigger onClientVehicleDamage for Rhino

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1248]
**Describe the bug**
Rocket doesn't trigger onClientVehicleDamage for Rhino (tank).

**To reproduce**
Run this script, watch /debugscript 3 for output. You wouldn't see any output from rocket (but from fire which rocket created - yes)

[script.zip](https://github.com/multitheftauto/mtasa-blue/files/4181537/script.zip)

**Expected behaviour**
It should trigger for rocket.

**Screenshots**
-

**Version**
Client: Multi Theft Auto v1.5.7-release-20358.2
Server: Multi Theft Auto v1.5.7-release-20358

**Additional context**
-

**Comment by MegadreamsBE** [comment]
The question is, does the tank actually get any damage from the rocket? If it doesn't get any damage at all I can easily see why this event isn't getting triggered.

**Comment by sbx320** [comment]
A rhino is not damaged by rockets, hence no damage event is triggered. As far as I know you can only damage a rhino with collisions and fire.
