### ISSUE TITLE
[Discussion] Module SDK

### ISSUE THREAD

**Issue by StiviiK** [multitheftauto/mtasa-blue#1249]
I think it would be nice if there were a new module SDK as the current one is really outdated. What does the rest think about this? 
Here's an example of a new SDK:
https://github.com/eXo-OpenSource/mtasa-module-sdk
_It was mostly developed by @Jusonex. I made some adjustments and integrated Luna for easy CPP -> Lua OOP binding._

**Note:** Didn't know where to start that discussion, so I hope that it is here okay.

**Comment by qaisjp** [comment]
The module SDK will be deprecated with the introduction of #680.

There's also some more information at #1244.

**Comment by StiviiK** [comment]
>The module SDK will be deprecated with the introduction of #680.

Ah okay, I see. Then I can close this issue.
