### ISSUE TITLE
font:destroy() does not work

### ISSUE THREAD

**Issue by Balabanovi** [multitheftauto/mtasa-blue#1256]
**Describe the bug**
Dx font cannot be destroyed using OOP method font:destroy()

**To reproduce**
`font = DxFont("font.ttf");
font:destroy()`

**Expected behaviour**
Dx font should be destroyed.

**Screenshots**

**Version**
Client: Multi Theft Auto v1.5.7-release-20358.5.001
Server: 1.5.7-release-20359

**Additional context**

**Comment by Woovie** [comment]
I tested and replicated.
