### ISSUE TITLE
Server time on Client side

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1262]
Add new functions on **client** side:

- getServerRealTime() - get server time on client side
- getServerTickCount() - get amount of time that server has been running in milliseconds on client side

**Comment by ghost** [comment]
This can be easily coded in Lua. Why do we need client-side functions for it?

**Comment by patrikjuvonen** [comment]
You can script this in Lua fairly easily, or find an existing script that does it for you. I made an example a while ago [here](https://github.com/patrikjuvonen/mtasa-random-resources/tree/master/time).
