### ISSUE TITLE
Windows CI build job throws warning

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1269]
Window CI build throws the following warning:
![download](https://user-images.githubusercontent.com/8040605/75632542-65250580-5bfd-11ea-961a-12a74990676c.png)

Build log: https://github.com/multitheftauto/mtasa-blue/pull/1266/checks?check_run_id=478205579

//cc: @qaisjp

**Comment by qaisjp** [comment]
Send link please?

**Comment by xLuxy** [comment]
Added,

**Comment by qaisjp** [comment]
thanks, see https://github.com/actions/cache/issues/153

should be easy to just upgrade from `windows-2016`

**Comment by qaisjp** [comment]
The `Create build artifacts` step in the above commit fails because MTA actually can't build. See [this line](https://github.com/multitheftauto/mtasa-blue/runs/478391296#step:7:109), copied below: 

```
Could not find MSBuild. Make sure you have Visual Studio 2017 installed
Press any key to continue . . . 
```

So, basically, this fix is potentially blocked by VS 2019.
