### ISSUE TITLE
Game does not show main menu with DXVK enabled

### ISSUE THREAD

**Issue by divadsn** [multitheftauto/mtasa-blue#1274]
**Describe the bug**
Game does not show main menu with DXVK enabled.

**To reproduce**
1. Install MTA via [Lutris](https://lutris.net/)
2. Open configuration for MTA
3. Set Wine version to 5.3 in runner options
4. Set DXVK with version 1.5.5 enabled in runner options
5. Game freezes after intro and no main menu is shown

**Expected behaviour**
Main menu should show up as in GTA San Andreas with DXVK enabled.

**Screenshots**
Will provide screen recording if needed.

**Version**
MTA client: 1.5.7
OS: Manjaro Linux 19.0

**Additional context**
GTA San Andreas and SA:MP are fully functional with DXVK enabled.

**Comment by qaisjp** [comment]
If you want to get MTA to work you can try installing Wine manually (or using Linuxbrew if you have that), and then following [these instructions](https://gist.github.com/qaisjp/778ed99ac8a8dcb93f797a28ba5f8303).

**Comment by divadsn** [comment]
Well MTA does work, but not with DXVK enabled, and GTA SA performance on wined3d is poor.

**Comment by divadsn** [comment]
https://youtu.be/fMYMEyyPUws

The FPS counter in the top left corner stops refreshing after the intro screen with on MTA.

**Comment by CrossFire10100** [comment]
I have the same problem on Arch Linux. It's a MTA problem it seems.

**Comment by TheNormalnij** [comment]
OS: Ubuntu 20.04
GPU: NVIDIA GT 1050
Video driver:  nvidia-440.82
Wine: wine-staging 5.6
GTA logo shows, but MTA menu does not starts. Some MTA forks works fine
Multi Theft Auto_d3d9.log:
```info:  Game: Multi Theft Auto.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1050:
info:    Driver: 440.82.0
info:    Vulkan: 1.1.119
info:    Memory Heap[0]: 
info:      Size: 4096 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 23982 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) UHD Graphics 630 (CFL GT2):
info:    Driver: 20.0.4
info:    Vulkan: 1.2.131
info:    Memory Heap[0]: 
info:      Size: 23982 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:  Process set as DPI aware

**Comment by divadsn** [comment]
@TheNormalnij which MTA forks do work with DXVK, are these also 1.5.7 version based?

**Comment by qaisjp** [comment]
We'd need to know what commit they are based off, otherwise we will have trouble figuring out which commit breaks DXVK support. You can help by testing/bisecting older versions from https://nightly.mtasa.com to help us find that commit.

**Comment by TheNormalnij** [comment]
mtasa-1.5.7-rc-18957 (oldest) does not work
mtasa-1.4.1-rc-7382 same issue

**Comment by divadsn** [comment]
mtasa-1.5.7-rc-20510 still not working, here is the output log:
https://del.dog/otumejagam.txt

Edit: Tried to auto-connect to a server to check if it works but now it doesn't launch at all.

**Comment by divadsn** [comment]
On latest Wine 5.5 with fshack and DXVK 1.6L it seems to work, but still does not show the main menu.

![Screenshot_20200416_015058](https://user-images.githubusercontent.com/28547847/79399855-bc502100-7f84-11ea-9a08-54afe2aaaa6e.png)

Another crash log: https://del.dog/ceghypucof.txt

**Comment by CrossFire10100** [comment]
What MTA;SA version is that?

**Comment by divadsn** [comment]
> What MTA;SA version is that?

mtasa-1.5.7-rc-20510 from https://nightly.mtasa.com/

**Comment by tiago4171** [comment]
I have a question @divadsn 
Is The MTASA used to run with DXVK on earlier versions? 
I've migrated for Linux and I don't know if it used to run or not. Here MTASA is running with OKAY performance with "[Gallium Nine](https://github.com/iXit/wine-nine-standalone)".

For the Devs of MTA I constantly having this error message after the black screen: 
![Print MTASA](https://user-images.githubusercontent.com/21028458/79713614-b5871e00-82a4-11ea-9bf0-a467e141ee21.png)
I don't know if this is somehow helpful, but as I could see no one provided any error message. 
On my free time I will try other manners of debuggging.

**Comment by TheNormalnij** [comment]
However, MTA with DXVK is _very_ unstable. I'm really don't recommend use DXVK.

**Comment by tiago4171** [comment]
> However, MTA with DXVK is _very_ unstable. I'm really don't recommend use DXVK.

Is there a way to start debugging it with DXVK enabled? Maybe it's not MTA fault
I've tested a lot of MTA versions, even the 1.4.1 ones and no sucess with DXVK enabled. I've tried to match the versions of the releases of both projects(DXVK and MTA) just to find out if a older version would work and again no sucess. I'm very worried about that and I want help to fix that issue

**Comment by divadsn** [comment]
> > However, MTA with DXVK is _very_ unstable. I'm really don't recommend use DXVK.
> 
> Is there a way to start debugging it with DXVK enabled? Maybe it's not MTA fault
> I've tested a lot of MTA versions, even the 1.4.1 ones and no sucess with DXVK enabled. I've tried to match the versions of the releases of both projects(DXVK and MTA) just to find out if a older version would work and again no sucess. I'm very worried about that and I want help to fix that issue

Well, it wouldn't be an issue if the base game would not work with DXVK, but the alternative SA:MP and GTA SA alone work flawlessly with DXVK, giving huge performance benefits.

**Comment by TheNormalnij** [comment]
There is another issue. GTA SA logo does not fade out. You can connect to server if you use mtasa:// link and you can see the join message in the console log.

**Comment by qaisjp** [comment]
> You can connect to server if you use mtasa:// link and you can see the join message in the console log.

This is interesting. Does the rest of the game work? Might it be an issue with CEGUI?

**Comment by TheNormalnij** [comment]
I can see only GTA logo but i can blindly login with console

**Comment by AlexTMjugador** [comment]
DXVK developers approach to debugging this kind of issues usually involves [recording an apitrace](https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace) of DirectX calls made by the affected process (in this case, MTA: SA). Maybe you could try capturing apitraces and replaying them with different DXVK versions, so you can check if it was a regression on DXVK's part, and in general gain insight on why it breaks.

**Comment by divadsn** [comment]
When running the game with DXVK v1.8.1 enabled on wineprefix, the problem is still present, so it is definitely something MTA specific. In some rare cases, the game won't even start the intro and crashes completely, which was not happening before.

On the other hand, MTA 1.5.8 runs very well on AMDGPU, but this is mainly due to WineD3D's OpenGL implementation.

Edit: Now I see how @qaisjp was able to give a [Gold rating on WineHQ](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38051) :eyes:

**Comment by jolty1** [comment]
Looks like now DXVK 1.9.2 and Wine 7.0 rc4 will run MTA just fine.

![Screenshot_20220104_192954](https://user-images.githubusercontent.com/42779428/148119594-7a85d4e4-53bc-4b0a-a1d8-3060793b6ae9.png)
![Screenshot_20220104_195410](https://user-images.githubusercontent.com/42779428/148119601-401578b0-f549-4c5b-94fa-bfacd460673a.png)

**Comment by divadsn** [comment]
Great news for Linux gaming, sadly I lost interest into this game (thanks Dutchman), therefore I am closing this issue.
