### ISSUE TITLE
Unexpected server behaviour

### ISSUE THREAD

**Issue by brzys** [multitheftauto/mtasa-blue#1276]
**Describe the bug**
Unfortunately, this is a totally random issue for me. No increased server memory usage, there is enough disk space etc. 

What happens?
- server fails to restart resources and open / save XML files (only XML! fileOpen is fine)
```
[20-03-05 17:49:16] Stopping resource
[20-03-05 17:49:16] ERROR: Error saving '...pathtoserver/multitheftauto_linux_x64/mods/deathmatch/acl.xml'
[20-03-05 17:49:16] Resource 'resource' changed, reloading and starting
[20-03-05 17:49:16] ERROR: Couldn't parse meta file for resource 'resource' [Line 0: Failed to open file]
```
Running resources work fine, restarting unloads them, /refresh can't restore them.

- can't connect to internal HTTP Server on default port
- fetchRemote returns cURL error 6 with each request
- server can't copy cached resources to `resource-cache/http-client-files/`

The server used same resource pack for a year without any issues, after updating to build +20000 (unfortunately I don't remember the exact one, but the same works with 20423) I have to restart server daily.
I don't understand how those issues are connected with each other...

**To reproduce**
cannot reproduce, maybe you can give me any cause of this behaviour?

**Expected behaviour**
no issues with server functionality

**Version**
1.5.7 build 20423 linux x64

**Comment by qaisjp** [comment]
Potential permissions issue?

**Comment by brzys** [comment]
> Potential permissions issue?

Server runs with root permissions. Still, this would break fileOpen

**Comment by ccw808** [comment]
Might be caused by running out of file handles.
Try these Linux commands when the error next occurs:
1. Get the pid of mta-server e.g.:
`pidof mta-server`
2. If pid was 123 for example, then show number of file handles with the command:
`lsof -p 123 | wc -l`

**Comment by brzys** [comment]
Thanks for fast response, seems we have a reason... I'll keep in touch if it is anything connected with software or rather some bad scripts.
