### ISSUE TITLE
MTA Discord Rich Presence

### ISSUE THREAD

**Issue by ZUNII** [multitheftauto/mtasa-blue#1280]
**Is your feature request related to a problem? Please describe.**
I would like to see a MTA Discord Rich Presence because I am a person I would like to show what I am playing / watching or listening to on discord.

**Describe the solution you'd like**
/

**Additional context**
https://i.imgur.com/WZBgVwN.png

**Comment by Lpsd** [comment]
This has already been done. A pull request has been made, which is almost ready to be merged. See #1031

**Comment by qaisjp** [comment]
Duplicate of #721
