### ISSUE TITLE
string.dump currently not working

### ISSUE THREAD

**Issue by FilkodonAwang** [multitheftauto/mtasa-blue#1281]
**Describe the bug**
string.dump() currently not working.

**To reproduce**
Run this script:
`
local a = function(msg)
	outputChatBox("function->"..tostring(msg))
end

local b = loadstring(string.dump(a))

a("a")
b("b")
`

Please paste reproduction resources (zip files) directly into this section.
[class_try.zip](https://github.com/multitheftauto/mtasa-blue/files/4302630/class_try.zip)

**Expected behaviour**
After the script runned, I have the cloned function of a in b.

**Screenshots**
![image](https://user-images.githubusercontent.com/48822215/76153875-25fe2500-60d3-11ea-81be-020eb0cca459.png)

**Version**
server/client version: 1.5.7 (both running on Windows)

**Additional context**
I didn't find any changelog that says this function disallowed or depricated.

**Comment by qaisjp** [comment]
I can reproduce this on latest master both on official release and custom builds. I suspect it was 'disabled' because it could maybe be used to circumvent script protection.

Trying to find the relevant commit...

**Comment by FilkodonAwang** [comment]
I see, then I will use metatables to implement class 'inheritance'.
Thank you for the answer!

**Comment by qaisjp** [comment]
Btw I'd recommend https://github.com/kikito/middleclass or https://github.com/sbx320/lua_utils
