### ISSUE TITLE
base64Decode bug?

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1289]
**Describe the bug**
`iprint("base64Decode",base64Decode("UABpAG4AZwAgAA=="))` should print `Ping ` with space at the end, but it prints it: 
![image](https://user-images.githubusercontent.com/22455534/76566609-654ebc00-64ad-11ea-8896-14f6cfda1159.png)

if yout put it here https://www.base64decode.org/ you got correct output

**To reproduce**
i described above

**Expected behaviour**
function should return `Ping `
**Screenshots**
/

**Version**
newstest

**Additional context**

and this one base64 got produced by  c#
```
public static string ToBase64(string s)
{
    byte[] buffer = System.Text.Encoding.Unicode.GetBytes(s);
    return System.Convert.ToBase64String(buffer);
}
``` with `Ping ` as input

looks like mta can't handle base64 of unicode characters

**Comment by ccw808** [comment]
https://www.base64decode.org/ with UTF-8 selected gives `P�i�n�g� �`
Your C# example uses UTF-16 not UTF-8
