### ISSUE TITLE
dxDrawPrimitive colors are always white

### ISSUE THREAD

**Issue by StrixG** [multitheftauto/mtasa-blue#1299]
**Describe the bug**
dxDrawPrimitive colors are always white. 

**To reproduce**
1. Download and start [primitivecolor.zip](https://github.com/multitheftauto/mtasa-blue/files/4343686/primitivecolor.zip)
2. Click on screen to draw a trianglefan.
3. You can see that trianglefan color is white.

**Expected behaviour**
dxDrawPrimitive should display correct colors.

**Version**
Reproduced on:
v1.5.7-release-20447
v1.5.7-release-20417

Can't reproduce on v1.5.7-release-20416 and lower

**Comment by qaisjp** [comment]
vs2019 issue which someone fixed for dxDrawLine I think. but i can't find the commit

although could be same issue as #1148

**Comment by patrikjuvonen** [comment]
> vs2019 issue which someone fixed for dxDrawLine I think. but i can't find the commit
> 
> although could be same issue as #1148

This is the commit: https://github.com/multitheftauto/mtasa-blue/commit/53121a3b3084b7e503d57be122f8649dd0bb09a8

Probably needs changes to the way https://github.com/multitheftauto/mtasa-blue/blob/53121a3b3084b7e503d57be122f8649dd0bb09a8/Shared/sdk/CScriptArgReader.h#L1008 works.

Ping @botder
