### ISSUE TITLE
Add support for SVG

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#1300]
Currently, the only way to render an SVG is by creating a transparent CEF browser and loading the SVG through the browser.

I think it would be useful to have SVG support built-in to MTA, which would most likely need less resources than creating a CEF instance just to display a single SVG.

I propose a function that returns an `xmlnode` (since we already have XML parsing built in) but wrapped as a custom type to identify that it's an svg (something like `svgnode`)

```lua
svgnode svgCreate(string rawData / filePath) -- Further parameters may be added for important options
```
Since an SVG is essentially just XML data, and the `svgnode` type is basically just an alias/wrapper for `xmlnode`, it would be compatible with most of the existing xml* functions (such as xmlNodeSetAttribute).

Would it be better for code readability to again wrap/alias the existing xml functions with an `svg` prefix instead? (e.g: `xmlNodeSetAttribute` -> `svgNodeSetAttribute`).

As for actually displaying the SVG, a function would be provided to get the SVG texture as a render target (which would be automatically updated if the SVG data is changed at all) - such as:

```lua
svgGetTexture(svgnode svgRootNode)
```

I'd like some other input on this, as you may have some better ideas. I do plan to implement this myself, however.

**Comment by quiret** [comment]
I suggest not svgGetTexture but svgGetPixels in the known format so that the pixels can be applied to a render-target. But I am not experienced with SVG at all. Could we discuss the scope of this issue/suggestion? What kind of complexity would be coming toward MTA? Why not implement it as MTA resource instead of natively? Do you have a specific library in mind? Is hardware-acceleration desired?

Personally as a scripter, I would greatly appreciate the ability to draw shapes onto render targets, but there is already a lot of capability with the dx functions. Do you think that SVG would be easy to implement with the existing function set?

**Comment by qaisjp** [comment]
svg support is definitely non-trivial both API wise and implementation wise.

can you find any 'game engines' that support this? it would give a good idea on what our API could provide, but also whether the entire feature is practical/feasible. i checked two 'engines' and one doesn't support it (love2d) and the other will import svgs but convert to 2d sprites (unity).

**Comment by dmi7ry** [comment]
Very fast rasterizer — [Blend2D](https://blend2d.com), although I don't know is it possible to use with MTA or not.

Actually it would be very useful to get support of vector graphics (radar/F11 map, HUD, interfaces, etc)

P.S. It's not a SVG engine, but 2D vector graphics engine. If you want exactly SVG then check [AmanithSVG](https://www.amanithsvg.com/) (works over OpenCV, AFAIR)

**Comment by CrosRoad95** [comment]
if someone has premake file for blend2d or other project which has premake inside, i could try add it into mta ( i don't want to waste time of figuring out how to make premake from cmake )

**Comment by qaisjp** [comment]
If you want to quickly try it out without bothering with making a `premake5.lua` file, you can try doing this https://github.com/premake/premake-core/issues/658

**Comment by Lpsd** [comment]
[lunasvg](https://github.com/sammycage/lunasvg) branch based on this [fork](https://github.com/spaxio/lunasvg) (to add support for premake and dllexport) -> https://github.com/Lpsd/mtasa-blue/tree/lunasvg

Current problem is [here](https://github.com/Lpsd/mtasa-blue/blob/1f10a5ce260b5397d5b1033356d4490416fcb1f9/Client/mods/deathmatch/logic/CClientVectorGraphic.cpp#L68-L69), can't work out why the bitmap data is `NULL` 

I've also created a [branch](https://github.com/Lpsd/mtasa-blue/tree/lunasvg-alt) which adds [plutosvg](https://github.com/sammycage/plutosvg) (same author as lunasvg) to handle the rendering/bitmap output (instead of lunasvg doing it directly), but it has the exact same issue. Not sure if problem with vendor or something I'm doing.

Feel free to investigate 😄

**Comment by sammycage** [comment]
I'm interested in this issue. `lunasvg::Bitmap::data` becomes NULL when `SVGDocument::documentHeight` or `SVGDocument::documentWidth` is zero. I need an SVG file or data for further research.

**Comment by Lpsd** [comment]
Hi @sammycage  - you can see how I'm initializing the document here: https://github.com/Lpsd/mtasa-blue/blob/3cc4015858efeccfbe4c15438c9cea035d18e929/Client/mods/deathmatch/logic/CClientVectorGraphic.cpp#L31

That's the only place where I currently create, or edit the document.

**Comment by Lpsd** [comment]
I've debugged the `SVGDocument::documentWidth()` and `SVGDocument::documentHeight()` return values, they seem fine (picture shows documentWidth, but I checked height too).

![image](https://user-images.githubusercontent.com/40902730/104941491-0bf7c900-59ab-11eb-8490-79400c7b9903.png)

Also, this is how the Bitmap instance looks

![image](https://user-images.githubusercontent.com/40902730/104942117-ef0fc580-59ab-11eb-99c7-eeb18b52c04c.png)

**Comment by Lpsd** [comment]
I've debugged the `SVGDocumentImpl::documentWidth` and `SVGDocumentImpl::documentHeight` return values, they seem fine.

![image](https://user-images.githubusercontent.com/40902730/104942595-90971700-59ac-11eb-937d-4ff05cec25ac.png)

Also, here's how the Bitmap instance looks.

![image](https://user-images.githubusercontent.com/40902730/104942725-ba503e00-59ac-11eb-8d21-bcfbef474bd8.png)

**Comment by Lpsd** [comment]
I debugged right the way through to `SVGGeometryElement::render` (after calling `SVGDocument::renderToBitmap`) and you can see the values of the canvas after drawing (they look like garbage to me?)

![image](https://user-images.githubusercontent.com/40902730/104944786-a0642a80-59af-11eb-9fa8-011939b79bcc.png)

**Comment by Lpsd** [comment]
`SVGDocument::toString` also returns valid SVG data (tested by running in browser)

**Comment by sammycage** [comment]
is [sourceData](https://github.com/Lpsd/mtasa-blue/blob/3cc4015858efeccfbe4c15438c9cea035d18e929/Client/mods/deathmatch/logic/CClientVectorGraphic.cpp#L75) `NULL`?. Because from the screenshots above, everything seems fine

**Comment by Lpsd** [comment]
`sourceData` isn't NULL, however I assumed the data it did contain was garbage. Does that look right?

![image](https://user-images.githubusercontent.com/40902730/104950596-dce85400-59b8-11eb-94b8-95051150cbb5.png)

**Comment by sammycage** [comment]
Everything is perfect....

Test if the data is garbage

```cpp

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

...
Bitmap bitmap = m_pDocument->renderToBitmap(width, height, 96.0, 0x46C2D4FF);

// Lock surface
D3DLOCKED_RECT LockedRect;
surface->LockRect(&LockedRect, nullptr, 0);

auto surfaceData = static_cast<byte*>(LockedRect.pBits);
auto sourceData = static_cast<const byte*>(bitmap.data());

stbi_write_png("didilooklikeagarbage.png", bitmap.width(), bitmap.height(), 4, static_cast<void*>(sourceData), 0);
....

```

**Comment by Lpsd** [comment]
Actually it's fine... so I guess I'm doing something wrong when rendering. Oops, my bad :sweat_smile:

Thanks for the great library @sammycage !

![image](https://user-images.githubusercontent.com/40902730/104954185-aeba4280-59bf-11eb-9d0b-4a837a053021.png)
