### ISSUE TITLE
kickPlayer does not accept server console as responsiblePlayer parameter

### ISSUE THREAD

**Issue by Dark-Dragon** [multitheftauto/mtasa-blue#1301]
**Describe the bug**
Using kickPlayer with the server console as the responsiblePlayer parameter will return a bad argument warning and will not work. After talking to qaisjp we came to the conclusion that it seems reasonable to accept the server console.

**To reproduce**
Easiest way to reproduce it is using the admin panels run code feature, because it already has acl access:
1. Open admin panel
2. Navigate to Resources -> Execute command
3. Type in or copy `kickPlayer(getPlayerFromName(""),getElementByIndex("console", 0))`
4. Type your in-game name in getPlayerFromName("")
5. Click to run server-sided
5. See error

**Expected behaviour**
The function should accept the server console as the responsiblePlayer argument instead of returning a bad argument warning and the player should be kicked.

**Version**
(343, 474, MTA:SA Server, 1.5.7-9.20358.0, 1.5.7, Release, Windows, 1.5.7-release-20358)

**Additional context**
This error currently stops the votemanager resource from kicking players after a successful kick vote.

**Comment by qaisjp** [comment]
_`git blame`_

Ah, looks like it was my fault... https://github.com/multitheftauto/mtasa-blue/commit/5c64c8cafc0a957edf55317c27cdd03f3f69af62
