### ISSUE TITLE
Browser/GuiBrowser won't capture AltGr combined characters (For Spanish keyboard layout)

### ISSUE THREAD

**Issue by PerikiyoXD** [multitheftauto/mtasa-blue#1303]
**Describe the bug**
Trying to input any Right Alt / AltGr combined characters won't be sent to the browser

**To reproduce**
1.  **CHANGE KEYBOARD LAYOUT TO SPANISH - Spanish (Spain)**
2. Download the resource attached [browser_bug_altgr.zip](https://github.com/multitheftauto/mtasa-blue/files/4356551/browser_bug_altgr.zip)
3. Start server and resource attached.
4. Start client and connect.
5. Input all numbers from 1 to 0 while holding AltGr into the input field.
6. Try to input the same sucession of characters into the upper-left edit box. There it should work.

**Expected behaviour**
In the browser input field, you're expecting this string
"|@#~€¬7890"

**Screenshots**
Tried to input character AltGr-2 (@) 3 times before opening console.
![imagen](https://user-images.githubusercontent.com/3116368/77105445-f7ab0e80-6a1d-11ea-8622-c5f2c35faa12.png)
but, as seen by the log, it's not typing the character.

**Version**
- Client: 1.5.7-release-20447
- Server: 1.5.7-9.20358.0

**Additional context**
[Discord conversation](https://discordapp.com/channels/278474088903606273/667831778563719182/690248067462856893)

**Comment by PerikiyoXD** [comment]
Seems to be a bug with CEF OSR.

Tested with http://opensource.spotify.com/cefbuilds/cef_binary_80.0.8%2Bgf96cd1d%2Bchromium-80.0.3987.132_windows32_client.tar.bz2

`cefclient.exe`
Works fine
![imagen](https://user-images.githubusercontent.com/3116368/77213323-be9c9800-6b0a-11ea-8646-5c242b904330.png)

`cefclient.exe --off-screen-rendering-enabled`
Doesn't work at all!
![imagen](https://user-images.githubusercontent.com/3116368/77213345-cf4d0e00-6b0a-11ea-8032-b910c170cf7a.png)

Going to fill a bug report @ CEF anyway

**Comment by PerikiyoXD** [comment]
A bug report has been already filled about this. 

Confirmed this is a regression, since this version works just fine
[79.3945 binary](http://opensource.spotify.com/cefbuilds/cef_binary_79.1.38%2Bgecefb59%2Bchromium-79.0.3945.130_windows32_client.tar.bz2)

PLEASE, vote here so the issue is resolved ASAP. 

https://bitbucket.org/chromiumembedded/cef/issues/2892/osr-generated-characters-from-keyboard

**Comment by qaisjp** [comment]
Thank you so much for debugging this and tracking it down!

**Comment by PerikiyoXD** [comment]
This is resolved using version 81.2.15+ge07275d+chromium-81.0.4044.92 and a little adjustment to CWebCore. Commit & PR soon.

**Comment by PerikiyoXD** [comment]
Thanks to Mike Wiedenbauer who contributed to CEF to fix this issue!

**Comment by qaisjp** [comment]
https://bitbucket.org/chromiumembedded/cef/pull-requests/297/osr-generated-characters-from-keyboard/diff

**Comment by PerikiyoXD** [comment]
![imagen](https://user-images.githubusercontent.com/3116368/78962539-ab229280-7af4-11ea-9b5e-54ae8bcd486f.png)
Fixed

**Comment by qaisjp** [comment]
Fixed in r20506 - https://buildinfo.mtasa.com/?SHA=245551cc7628593cfe419358d950fb93236bc077
