### ISSUE TITLE
"Select device" hides under other program without MTA icon on a taskbar

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1305]
**Describe the bug**
When you run MTA and you have more than 1 monitor or NVIDIA Optimus and you click any other program, window with graphics/monitor selection will hide under other programs and if you don't know about it, you won't know why MTA isn't starting. There's no MTA icon in the taskbar and it won't be displayed in front of every program (that would be the best option)

**To reproduce**
1. run MTA
2. click any other program

https://youtu.be/sCCFAWXGPw4

**Version**
Windows, newest version

**Comment by qaisjp** [comment]
There must be other places where this happens too

**Comment by Lordmau5** [comment]
If I may add onto this:
That is default GTA behavior if you have more than 1 monitor, so MTA isn't really at *fault* here
I personally don't know if it'd be possible to have it override / hook that device selection window and instead move that device selection into the ingame settings? (Could be useful for #1304 as well maybe, unless the extra info will for sure not be messing with the base game settings file)

Also, when it opens that small device selection window, it will position it where the mouse was at at that given moment. So if you would move to a 2nd monitor and do things on there (e.g. Discord or similar) and that window comes up, it will be positioned over there (at least that's what happened in my cases)
