### ISSUE TITLE
Not being able to access resource manager

### ISSUE THREAD

**Issue by N3xT** [multitheftauto/mtasa-blue#1313]
**Describe the bug**
Simply, not being able to access resource manager if you're missing trailing "/". for example:
http://ip:port/resourcebrowser/ = works
http://ip:port/resourcebrowser = doesn't work

**To reproduce**
Steps to reproduce the behaviour:
1. Access your resource manager without the trailing "/"
2. It will return a 404 page

**Expected behaviour**
It should explain what's the problem exactly, or just fixes the URL by itself.

**Comment by Unde-R** [comment]
I think this issue is either invalid or already fixed because It's working fine for me

**Comment by botder** [comment]
Without the trailing slash, relative paths will be wrong inside the served HTML response.

**Comment by botder** [comment]
In-built HTTP server redirects you to the default resource, if set, with a trailing slash. Please check if your browser is functional and handles `Location` redirects in the intended way.

https://github.com/multitheftauto/mtasa-blue/blob/21b179e69561226810f3073fad5ca9e07d15b672/Server/mods/deathmatch/logic/CHTTPD.cpp#L162-L166
