### ISSUE TITLE
MTA doesn't validate files 

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1316]
**Describe the bug**
There's should be possibility to add validate option to files in MTA - some of players are cheating on servers by replacing models/textures/collisions by changing file permissions (disabling write). Now you have to check files manually, you have to make your own "anticheat" comparing MD5 between server and client. You can't replace scripts, but you can replace everything else.
 
**To reproduce**
1. replace server modification (dff/txd/col)
2. disable permission to write for every Windows account
3. voila, you have your custom model instead of server model.

**Screenshots**

![image](https://user-images.githubusercontent.com/923242/77481372-6d96e780-6e1b-11ea-8d0a-1c086741b87d.png)

![image](https://user-images.githubusercontent.com/923242/77481379-7091d800-6e1b-11ea-83f7-4d215910f36d.png)

**Version**
newest, Windows

**Comment by ccw808** [comment]
Does enabling [SD #23](https://wiki.multitheftauto.com/wiki/Anti-cheat_guide#.3Cenablesd.3E.3C.2Fenablesd.3E) fix this?

**Comment by MrDadosz** [comment]
Thanks. I tried it and it's working, couldn't find it before. I think it should be enabled at default. It seems to me that many people creating servers don't know about this option, and Lua script protection is enabled by default (same errors in console like when you enable SD 23, uses script as cache="false" without saving it on disk).

**Comment by PlatinMTA** [comment]
Well, <script/> has a "validate" attribute in meta.xml, I think it would be natural to make the <file/> have a "validate" attribute too.

**Comment by qaisjp** [comment]
The validate attribute on `<script />` is for compatibility checks, not for preventing download corruption

**Comment by patrikjuvonen** [comment]
It seems this issue is invalid and requires only [SD #23](https://wiki.multitheftauto.com/wiki/Anti-cheat_guide#.3Cenablesd.3E.3C.2Fenablesd.3E) to be enabled by the server as said above by ccw.
