### ISSUE TITLE
Collision positions for colshapes are not updated when attached to an element

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#1317]
When attaching a colshape to an object, the collision position for the colshape is not updated, so onColShapeHit will not trigger when walking into the "visual" position of the colshape (viewed with /showcol).

I've included a test resource below. I'm running `v1.5.7-release-20358.5.001`

[colshape.zip](https://github.com/multitheftauto/mtasa-blue/files/4378360/colshape.zip)

**Comment by Citizen01** [comment]
Does it stay where it has been created ? or does it follow the object but at the center of the model ?
Because I remember years ago that it was attached successfully but not taking into account the offset provided so a marker attached to a car and with an offset so it is (let's say) just behind the trunk would not trigger when walking in the marker but was being triggered if I jumped onto the roof (so the col is kinda stuck to the 0, 0, 0 position of the vehicle it is attached to.

**Comment by Lpsd** [comment]
I've tested the following:

- Create an object 3 units in front of the player.
- Create a colshape at 0, 0, 0
- Add an "onColShapeHit" which outputs to debugscript when player hits
- Attach the colshape to the object (using `attachElements`)
- Walk player to object, colshape hit NOT detected
- Teleport player to 0, 0, 0 - colshape hit detected
- Walk player away from 0, 0, 0 and move object to random location on the map
- Teleport back to 0, 0, 0 - colshape hit NOT detected

Without looking into the code, my conclusion from this is that `attachElements` is not updating the actual "hitbox" position for the colshape. However, `setElementPosition` does update the hitbox position for the colshape (even when used on the object it is attached to, since it cascades), which essentially means there's an offset on the hitbox from the object position and the initial colshape position.

Solution: make `attachElements` also update the hitbox position for colshapes.

I'll submit a PR tomorrow, it's late now.

**Comment by Lpsd** [comment]
Following on to my previous message, I added an extra step to the end of my above test, by walking the player back into the object after moving it with `setElementPosition` (when both the object and colshape are attached) and the "onColShapeHit" event triggers. 

This means that there is no offset after using `setElementPosition` as it fixes the "hitbox" position for the colshape.

I'm currently working on this, PR later on.
