### ISSUE TITLE
Caddy (vehicle) plays incorrect door/entry animation

### ISSUE THREAD

**Issue by tut001** [multitheftauto/mtasa-blue#1318]
**Describe the bug**
When entering Golf Caddy ID 457, it plays a door opening animation both when entering from passenger and driver side.

**To reproduce**
1. Spawn ID 457
2. Enter from either passenger or driver seat
3. Notice you're opening an invisible door

**Expected behaviour**
The player should enter the vehicle by directly stepping inside.

**Screenshots**
N/A

**Version**
Client: Multi Theft Auto v1.5.7-release-20460

**Additional context**
Qaisjp suspects the vs2019 issue may be related
Strix later found the answer, https://github.com/multitheftauto/mtasa-blue/issues/1318#issuecomment-669616427

**Comment by zo3n** [comment]
Tractor as well
by the way noticed something about this invisible door:

you know when you normally enter a vehicle, and door remains open, so when you let go of W, the player closes the door automatically by also doing animation of doing it?
if this happens with invisible door of tractor, ped will attempt to close the door always, whenever letting go of W key, but it'll never close because it doesn't exist

**Comment by zo3n** [comment]
Just to show it off better, here's a video demonstration:
https://streamable.com/u7p9m

**Comment by qaisjp** [comment]
Thank you so much for the video! Please can you install https://nightly.mtasa.com/mtasa-1.5.7-rc-20417-20200301.exe and check if that still happens?

**Comment by zo3n** [comment]
That fixed it. Both Caddy and Tractor act normal now.

**Comment by qaisjp** [comment]
Thanks for confirming. Okay, definitely a VS 2019 problem. Release the kraken!

**Comment by zo3n** [comment]
Uh, problem reappeared in version 20488

**Comment by Dutchman101** [comment]
> 
> 
> Uh, problem reappeared in version 20488

No.. it just hasn't been fixed yet, the build you tested with (which you said "fixed" it) was simply an old build from before upgrading to VS2019.

This is probably undefined behavior somewhere that gets exposed with VS2019 only, and it needs to be located in order to get fixed.

**Comment by ccw808** [comment]
Does the bug occur with a custom (debug or release) build?

**Comment by ghost** [comment]
> 
> 
> Does the bug occur with a custom (debug or release) build?

I can reproduce it on both, and sometimes this happens: https://cdn.discordapp.com/attachments/366384007535001612/725386799610069083/2020-06-24_21-23-39.mp4
In the video, we can see how the vehicle door closing animation gets played in a loop. It happens randomly.

**Comment by Dutchman101** [comment]
> Tractor as well

Many more vehicles are affected.. for example, **kart, mower, vortex, bandito, baggage**.. the list goes on beyond that. It seems like all vehicles without door are affected, those with "jump (or step) right in" animation.

@ccw808 if there's any GTA hook optimization in netcode like last time with a similar hard-to-locate VS2019 bug, this information can help narrow it down?

**Comment by ccw808** [comment]
> there's any GTA hook optimization in netcode like last time

I think the problem is in the OS code

**Comment by StrixG** [comment]
This issue is caused by c2dc4633e334f0531762b9f561e1c789d9801186 and is not related to VS2019

**Comment by ghost** [comment]
This is strange. I can still reproduce this bug.

**Comment by Vadya963** [comment]
there is no error, the client: 20621 server: 20624

**Comment by ghost** [comment]
> there is no error, the client: 20621 server: 20624

yes
> This is strange. I can still reproduce this bug.

 I was using the old server build. Full rebuild fixed the issue.
