### ISSUE TITLE
debugscript returns "debugscript: Your debug mode was set to 0" if using a character value.

### ISSUE THREAD

**Issue by Haxardous** [multitheftauto/mtasa-blue#1322]
debugscript will set it's status to "0" whenever typing "debugscript (any *word* character)".

how to reproduce the bug:
1. type /debugscript 1 or 2 or 3 for e.g. (debugscript 3)
2. type /debugscript word for e.g. (debugscript a)
and it'll return "debugscript: Your debug mode was set to 0"

**Comment by PlatinMTA** [comment]
I guess this happens bcuz atoi will return 0 in failure to read a number, too lazy to check

Btw I can reproduce the bug

**Comment by qaisjp** [comment]
maybe this bug is actually a feature

**Comment by Pirulax** [comment]
Im pretty sure its intended, because when you fuck up, you can just type in "debugscript ", then smash ur keyboard, and press enter in the smashing process, and then alt+f4

**Comment by Unde-R** [comment]
Dont mind this, I did something wrong.

**Comment by qaisjp** [comment]
Fixed in 8f25c22 via #1602
