### ISSUE TITLE
Problems with vehicle components and animations

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1325]
Hello! On my server, the components of the car tuning break down (example in the screenshot). This happens after I go to a foreign server. And when I go to my server, there is such a problem. I also noticed that after entering other servers, then my animations do not work. The problem is solved only after restarting the MTA client. But this is not an option. It turns out that the MTA client does not clean client information when a player visits other servers, hence the question: how can I clean this information myself so that players do not restart the client? But why doesn't the client do this?
engineRestoreModel and resetVehicleComponentPosition did not help
screenshot: https://sun1-26.userapi.com/ex21gf2Lb7TGCNXpFI6ydWQiaZVxXDihPwLFPw/G1lGeiyP6oE.jpg

**Comment by qaisjp** [comment]
Please use the bug report template here https://github.com/multitheftauto/mtasa-blue/issues/new?labels=bug&template=bug_report.md
