### ISSUE TITLE
Discord presence shows "out of 0 players" for older servers

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1328]
**Describe the bug**

discord presence shows `x/0 players` when the server is older than the discord presence update

**To reproduce**

1. checkout an older master
2. build server
3. start server (DO NOT STOP THE SERVER)
4. checkout latest master
5. build client
6. start client and connect to server
7. observe `1/0 Player` in your rich presence

**Expected behaviour**

It should just say `1 Player`

**Screenshots**

![image](https://user-images.githubusercontent.com/923242/77712168-f99b4180-6fca-11ea-9897-0738e4437fe3.png)

**Version**

client 2e02ebec08c8dd0c2b05cd698f60473848c2fa5f (master)
server 2d6851972d11ad08c412fb77c8883c29efc96f1d (master^^)

**Additional context**

valve please fix

**Comment by qaisjp** [comment]
@0x416c69 if you have the time, please can you fix this? 🙂

**Comment by 0x416c69** [comment]
I think it's better to write this somewhere for people who accept PRs in case they forgot:

Check if the contributor incremented BitStream version and if he did check commits that have been pushed after the pull request and see if they incremented BitStream version too and if there was a commit, update the pull request BitStream version.

Incrementing for my PR which resulting in fixing this issue: https://github.com/multitheftauto/mtasa-blue/pull/1330

**Comment by qaisjp** [comment]
~~you mean https://github.com/multitheftauto/mtasa-blue/wiki/BitStream ?~~

~~i guess we should include a link to that page in the code somewhere~~

my bad. yes i'll add this to the potentially upcoming contributors guide
