### ISSUE TITLE
Have an enum class for individual bit stream versions

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1331]
**Is your feature request related to a problem? Please describe.**

I get frustrated looking at magic numbers that refer to a new feature. Also, it's easy to forget to increment magic numbers.

**Describe the solution you'd like**

An enum class for individual bit stream versions. E.g. here https://github.com/multitheftauto/mtasa-blue/commit/a0ce68f284487ba636e839b06c103bc2442d95e0 we can use `BitStreamVersion::discord_presence`.

**Describe alternatives you've considered**

n/a

**Additional context**

This will also make it so that bumping bit stream versions will always result in (an easy to resolve) merge conflict. We can make sure it's always added to the end of the list.

**Comment by sbx320** [comment]
We should also use this opportunity to remove outdated branches for old bitstream versions. I'm pretty certain we still have branches for some 1.3 revisions in there (which are never taken).

**Comment by qaisjp** [comment]
https://github.com/multitheftauto/mtasa-blue/pull/1737 https://github.com/multitheftauto/mtasa-blue/pull/1752 https://github.com/multitheftauto/mtasa-blue/pull/1749
