### ISSUE TITLE
Discord should automatically move dll files

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1333]
**Is your feature request related to a problem? Please describe.**

It is annoying for win-create-projects to tell me to click win-install-data when CEF doesn't make me do it

**Describe the solution you'd like**

This is a super quick win.

the goal is to copy from `"Shared/data/MTA San Andreas/MTA/discord_game_sdk.dll"` to `Bin/MTA/discord_game_sdk.dll`

which would make these lines go away https://github.com/multitheftauto/mtasa-blue/blob/fa6bdb61bc0d2613debac92803fd752d43216eac/utils/buildactions/install_discord.lua#L47-L48

**Describe alternatives you've considered**

n/a

**Additional context**

Do what cef does and use a `postbuildcommand`: https://github.com/multitheftauto/mtasa-blue/blob/fa6bdb61bc0d2613debac92803fd752d43216eac/vendor/cef3/premake5.lua#L20-L25

The `{COPY}` stuff is described here https://github.com/premake/premake-core/wiki/Tokens#command-tokens

`postbuildcommands` doc: https://github.com/premake/premake-core/wiki/postbuildcommands

**Comment by botder** [comment]
@patrikjuvonen any progress on this? Can you resolve this issue until the end of the month?
