### ISSUE TITLE
Fix Discord rich presence API

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1335]
**Describe the bug**

The name `setPlayerDiscordJoinParams` is temporary and we need to come up with something that is more platform agnostic

Or allow a server to "require" a discord package and do Discord-specific stuff within that module (but only if that module is available).

**Additional context**

Filing this as an issue so that we sort it out before releasing 1.6.

**Comment by patrikjuvonen** [comment]
Closed in favor of #2499
