### ISSUE TITLE
Increase kick time on the unstable connections

### ISSUE THREAD

**Issue by VadimMuhtarov** [multitheftauto/mtasa-blue#1339]
I am not sure if this is MTA or server side settings, but I can't play it via LTE connection without kicks due to packet loss.

**Comment by qaisjp** [comment]
Please edit your issue and use the feature request template - https://github.com/multitheftauto/mtasa-blue/issues/new?labels=enhancement&template=feature_request.md

**Comment by qaisjp** [comment]
Need more details on what kind of "kick" you're talking about. Are you being kicked (https://wiki.multitheftauto.com/wiki/KickPlayer) or timing out? Include that in your updated issue
