### ISSUE TITLE
Walk and aim doesn't work everytime

### ISSUE THREAD

**Issue by umitemre** [multitheftauto/mtasa-blue#1356]
**Describe the bug**
I've set weapon skills to move and shoot and jump while having a heavy gun (minigun)
Jumping when having a heavy weapon works fine but move and aim or shoot doesn't work everytime. I'm pressing W, A, S, D keys for couple of times and than it works afterwards and stops if I lift my finger up and only works after couple of tryings.

Here's the code
[https://gist.github.com/umitemre/b25d9fdb9e6d8f6e28a2c8fde3a721f3](https://gist.github.com/umitemre/b25d9fdb9e6d8f6e28a2c8fde3a721f3)

Output:

[2020-04-07 02:26:13] Before 568, 1
[2020-04-07 02:26:13] After 56, 3

[2020-04-07 02:26:13] std
[2020-04-07 02:26:13] Before 56, 3
[2020-04-07 02:26:13] After 56, 3

[2020-04-07 02:26:13] pro
[2020-04-07 02:26:13] Before 56, 3
[2020-04-07 02:26:13] After 56, 3

56 means:

0x000020 | 0x000010 | 0x000008
(move and shoot) (move and aim) (aim freely)

Please see: [https://wiki.multitheftauto.com/wiki/Weapon_Flags](https://wiki.multitheftauto.com/wiki/Weapon_Flags])

**To reproduce**
1. Use above script for server-side code.
2. Try using a minigun while walking.

**Expected behaviour**
It should move and shoot. 

**Version**
Server version: 1.5.7
Client version: 1.5.7-9.20358.5

**Comment by Addlibs** [comment]
Related to #502. I've checked the code and moving with minigun while aiming and/or firing works as long as my FPS limit is set to 70 or lower. At 71 it starts to glitch.

**Comment by umitemre** [comment]
I can confirm that lowering FPs to 70 solved this problem. I don't know if it's a bug or not so I leave this topic as it is.

**Comment by lopezloo** [comment]
Duplicate of #502
