### ISSUE TITLE
xmlLoadString doesn't work

### ISSUE THREAD

**Issue by Zangomangu** [multitheftauto/mtasa-blue#1362]
**Describe the bug**
xmlLoadString doesn't work on client or server atm.
It yields "Unable to load XML string".

**To reproduce**
[test.zip](https://github.com/multitheftauto/mtasa-blue/files/4455090/test.zip)

**Version**
Both client and server
Latest 20502
Doesn't work in 20447 either.
Windows 10

EDIT:
Tested in 19626 where it was added, doesnt work there either.

**Comment by umitemre** [comment]
I can confirm that this bug still exists on  1.5.7-9.20447.2

Can you specify a version which this function works?

**Comment by qaisjp** [comment]
At least 20507 https://buildinfo.mtasa.com/?Revision=20507&Branch=

**Comment by umitemre** [comment]
I’ve installed latest nightly build as today and it is working just fine. Although I have found an exception and I’m going to further investigate it and post the results if any minor bugs exists on the client code. 

Also I saw you have added this to 1.6 milestone. Is that mean this will not be available in any 1.5.7 releases?

**Comment by qaisjp** [comment]
We renamed the 1.6 milestone to 1.5.8. I thought that would update the timelines in all issues but I guess it didn't. Oh well. It's in `master`, so it will arrive on the 1.5.7 nightlies.

Please keep us posted about the exception you found.

**Comment by umitemre** [comment]
> We renamed the 1.6 milestone to 1.5.8. I thought that would update the timelines in all issues but I guess it didn't. Oh well. It's in `master`, so it will arrive on the 1.5.7 nightlies.
> 
> Please keep us posted about the exception you found.

Exception is invalid. My XML was broken, couldn't notice at first.
