### ISSUE TITLE
Our Discord integration violates the GPL

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1370]
**Describe the bug**

We cannot link with Discord's Game SDK as the Game SDK is not available under a free license.

**Describe the solution you'd like**

Use the legacy [`discord-rpc`](https://github.com/discord/discord-rpc) library instead, which _is_ available under a free license (MIT).

This issue also pauses any _mass rollouts_ of binaries until it has been resolved.

**Describe alternatives you've considered**

Contact all historical contributors and change our license. Doing this is not practical at this point in time—it will take a long time, and it's faster to just change our code.

**Version**

245551c

**Additional context**

Discord announcement of the Game SDK with extensive bikeshedding on this matter: https://github.com/discord/discord-rpc/issues/290#issuecomment-488151732

Relevant conversation in #mta.dev: https://discordapp.com/channels/278474088903606273/366384007535001612/697937233151524884

**Comment by Disinterpreter** [comment]
> Use the legacy discord-rpc library instead, which is available under a free license (MIT).

The problem is discord-rpc is an archived project and it can be contain some vulnerabilities.

**Comment by 0x416c69** [comment]
![image](https://user-images.githubusercontent.com/10671711/79071873-36697700-7cf3-11ea-8fb3-7a99f64e082d.png)

Just tell me what you decide, I don't know anything about this statement though:

> The problem is discord-rpc is an archived project and it can be contain some vulnerabilities.

I have wrote my discord integration in such a way that it is totally easy to switch back to discord-rpc so just say the words, we'll get rid of trash from MTA repo in an instant.

**Comment by qaisjp** [comment]
Yes please. Down the line we can fork `discord-rpc` or move to a community fork.

**Comment by 0x416c69** [comment]
I'm a little busy, how much time we have for 1.6 release approximately?

**Comment by qaisjp** [comment]
Last week I would have said 1.6 in about June/July.

But this week we've been *thinking* (not confirmed or finalised - no decision has been made) about releasing 1.5.8 mid-May, and 1.6 end of year. (The 1.6 milestone will be renamed to 1.5.8.)

**Comment by dartic2k** [comment]
Any update on the 1.6 release date?

**Comment by Timic3** [comment]
Documenting IPC (which GameSDK uses) is planned, which should bring a library with a better license than GameSDK. Or well, just directly implement IPC connection, which might seem easier.
