### ISSUE TITLE
Prevent setTimer from being executed continuously on every frame

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#1371]
**Is your feature request related to a problem? Please describe.**
Some people may think it's clever to use `setTimer(fn, 0, 0)` to execute code on every frame (to draw DX GUI for example)

`setTimer` is not intended for this, and in some cases may cause issues. Any value <0-49> should not be allowed to be repeated continuously (as was the case before 5910ddf introduced intervals below 50ms)

**Describe the solution you'd like**
`setTimer(fn, <0-49>, 0)` should return false and not execute.

For confirmation, `setTimer(fn, <0-49>, 1)` would be fine.

At a minimum, if we're not happy about blocking code in specific situations (following on from #1348), a warning should be displayed.

**Comment by stoneage-mta** [comment]
```lua
function test() 
    local x, y, z = getElementPosition(localPlayer)
    dxDrawLine3D(x, y, z, x, y, z + 2)
    
    setTimer(test, 0, 1)
end
setTimer(test, 0, 1)
```
and what if people do like?

**Comment by Lpsd** [comment]
In your scenario it would be possible to prevent the `setTimer` inside the function from being executed, providing the function was called from a timer which also meets the conditions described above.

I've thought about this some more and I believe there's too many edge cases to consider where `setTimer(fn, <0-49>, 0)` (or a "recursive" `setTimer(fn, <0-49>, 1)`) may be used reasonably. For example, checking for a value which is precisely updated every <0-49> ms. Here's an implementation using both `setTimer` and `onClientRender`.

```lua
local checkIntervalMs = 5
function checkValue()
    if (someValue == true) then
        doSomething()
    end
end
setTimer(checkValue, checkIntervalMs, 0)
```
vs
```lua
local checkIntervalMs = 5
local lastCheckedMs = getTickCount()
function checkValue()
    if (lastCheckedMs + checkIntervalMs  == getTickCount()) then
        lastCheckedMs = getTickCount()
        if (someValue == true) then
            doSomething()
        end
    end
end
addEventHandler("onClientRender", root, checkValue)
```

The `setTimer` solution is actually cleaner and requires less code. Implementing my initial suggestion would therefore just be dictating user implementation (when both are perfectly valid).

Therefore by the power of the rubber duck I'm closing this issue as it's not necessary.

Final thought: following on from #1348 I do think we could implement a "library" of poor code-design detection, which in this instance would throw a warning when `setTimer` is specifically used with a 0ms interval repeatedly (in that case, the "warning" would suggest using onClientRender). I'll think about it some more and maybe open a separate issue.
