### ISSUE TITLE
Single player object not exists in MTA

### ISSUE THREAD

**Issue by christophercampbell1** [multitheftauto/mtasa-blue#1374]
**Describe the bug**
I started to re-make the single player container crane SF mission, but the crane arm object is not exists in MTA. (Invalid model ID)

**To reproduce**
Just create an object with modelId 1382

**Expected behaviour**

**Screenshots**

**Version**
Maybe in all versions.
But I tested it in:
- Client 1.5.7-release-20488
- Server 1.5.7-release-20397

**Additional context**
1379, MagnoCrane_02, Cranes_DYN2_CJ, 150, 4
1380, MagnoCrane_01, Cranes_DYN2_CJ, 150, 0
1381, MagnoCrane_04, Cranes_DYN2, 150, 0
1382, MagnoCrane_03, Cranes_DYN2_CJ, 150, 4  <---- This one

**Comment by patrikjuvonen** [comment]
Seems 1382 is deliberately skipped in the generator here: https://github.com/multitheftauto/mtasa-blue/blob/master/Client/utils/gentable/gentable_objmodels.cpp#L59-L60

This skip was made by https://github.com/multitheftauto/mtasa-blue/commit/f9299d4e64f806cb7c54e0e169d4748715d9711a titled "Many objects crash the Editor"

Original Mantis Bug Tracker issue at mantis-4270

cc @darkdreamingdan

**Comment by PlatinMTA** [comment]
Just to point out, in SAMP (base on https://dev.prineside.com/) the object 1382 does not exist, but it was added as a custom model (id: 11703). Maybe something is wrong with that object? It appears that some objects simply crash MTA for no reason and 1382 was one of them.

Also 1382 isn't listed as an ID that it's not used by the game.

**Comment by TheNormalnij** [comment]
Fixed via #1684

**Comment by TheNormalnij** [comment]
But this object causes crash on destroy
