### ISSUE TITLE
Change of behaviour in getColorFromString #1261

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#1393]
**Describe the bug**

I noticed that the behavoir of this function changed and can cause now bugs in many old scripts.
The function originaly only expected strings with preceeding # sign.
Now this functions also accepts strings/numbers without preceeding # sign which causes unexpected behavoir in old scripts, because old scripts expected it to return false when it doesn't have a preceding # sign.

**To reproduce**

https://github.com/multitheftauto/mtasa-resources/blob/aeed6838b79756002f6ac46af1baf4a5476d9493/%5Bgamemodes%5D/%5Brace%5D/race/racemap.lua#L237
```lua
function DMRaceMapObject:parseValue(val)
	if type(val) ~= 'string' then
		return val
	end
	if #val == 0 then
		return false
	end
	local r, g, b = getColorFromString(val)
	if r then
		return { r, g, b }
	end
	val = table.maptry(val:split(','), tonumber) or val
	if type(val) == 'table' and #val == 1 then
		val = val[1]
	end
	return val
end
```
for example this function in race gamemode expected it to return false
this could also break servers that have added custom attributes for .map files and didn't expect such a change
there are propably many other cases too

**Expected behaviour**

return false when it does not have a preceeding #

**Version**

with introduction of nightly version r20477

**Additional context**

cc @patrikjuvonen
#1261

**Comment by patrikjuvonen** [comment]
Perhaps we should revert the change and commit it in the next breaking release (1.6) and adjust race gamemode accordingly.

**Comment by thisdp** [comment]
we should accept both with # and without #

**Comment by qaisjp** [comment]
`getColorFromString` to me, depsite the function name, sounds like it's specifically supposed to be for hex strings, rather than "any way to get a color from a string".

Are you sure we should keep that change when the revert is reverted?

**Comment by patrikjuvonen** [comment]
> `getColorFromString` to me, depsite the function name, sounds like it's specifically supposed to be for hex strings, rather than "any way to get a color from a string".
> 
> Are you sure we should keep that change when the revert is reverted?

Discussion related to the change should take place in #1258.
