### ISSUE TITLE
"Fix invincible peds (#777)" introduces a player post-death bug

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#1404]
**Describe the bug**
The change e43d34f has bugged the behavior of player ped right after death.

**To reproduce**
1. Spawn
2. Kill yourself (`setElementHealth(localPlayer,0)`)
3. Observe the bugged behavior as seen in this video:
[https://streamable.com/v0egjq](https://streamable.com/v0egjq)

What is bugged: player can control their dead ped for a couple of seconds, which means either jump once (after which they'll be stuck), or fire a weapon in free aim if they were wielding one upon death. Additionally, the "up into the sky" cam behavior for wasted players is broken.

The correct behavior (including the cam): [https://streamable.com/y32vl6](https://streamable.com/y32vl6)
This video was taken on build r20515, right before the bug got introduced.

**Version**
Client r20518

@FileEX

**Comment by qaisjp** [comment]
Yeah I think we should just revert #777 until it is fixed.

**Comment by Addlibs** [comment]
As a follow up, if there's no resource respawning player automatically, they remains dead on the server but alive on all clients (except the local client if killed by killPed or /kill etc.), vehicle position  (but not player position if on foot) continues to sync and the player can effectively drive cars if gets killed by gunfire etc. while driving, which could be problematic for a number of servers. This appears to only happen while there's another alive player in proximity faciliating the sync. If all players nearby are dead, vehicle position does not appear to sync.
