### ISSUE TITLE
Allow scripts to access the transferbox CEGUI element

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#1409]
**Is your feature request related to a problem? Please describe.**
Currently if you want to create a custom transferbox (download progress) UI, you need to create a custom download manager to track the download progress - which is an awful lot of extra work for such a simple thing.

**Describe the solution you'd like**
The transferbox CEGUI element should be accessible from Lua from a function such as `getTransferBox`

This would allow you to use `guiProgressBarGetProgress` to apply the current download progress on your own UI progressbar (DXGUI for example) and also hide the default transferbox.

**Describe alternatives you've considered**

If we're not happy to give direct access to the transferbox CEGUI element, we could instead implement the following functions:

```lua
int getTransferBoxProgress()
bool setTransferBoxVisible(bool visible)
```

**Comment by CrosRoad95** [comment]
#171
