### ISSUE TITLE
/msg duplicating when sent by Server Console

### ISSUE THREAD

**Issue by Lord-Henry** [multitheftauto/mtasa-blue#1410]
**Describe the bug**
When someone uses /msg on Server Console to someone online, that player receives the message twice.

**To Reproduce**
1. Start a local server.
2. Log-in the server.
3. Go to Server Console and use /msg to send a message to your own character.
4. Go to the game and see the same message twice.

**Expected behavior**
Server Console should send the message only once.

**Screenshots**
Server Console:
![screenshot 2020-04-25 144418](https://user-images.githubusercontent.com/35237817/80287018-65c1b000-8705-11ea-863d-901de2e2e934.png)
Game chat:
![screenshot 2020-04-25 144515](https://user-images.githubusercontent.com/35237817/80287025-72de9f00-8705-11ea-9932-bf361e46016e.png)

**Version**
- server/client version: 1.5.7-20447)
- Windows 10 PRO

**Additional context**
It seems that are 2 hard coded scripts doing the same thing. Each one sending a message to the player.

**Comment by PlatinMTA** [comment]
It's an MTA issue, i just checked (stopped every resource on the server except resourcebrowser) and the msg from console outputs this:

![image](https://user-images.githubusercontent.com/23291573/80304114-8a13a000-878a-11ea-8568-af1c381e9e38.png)
![image](https://user-images.githubusercontent.com/23291573/80304125-926bdb00-878a-11ea-9d71-7b51fbad9d99.png)
