### ISSUE TITLE
Add CI check for debug build

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1412]
**Is your feature request related to a problem? Please describe.**

Debug builds on macOS (and possibly Linux) were broken because of some shared code using Windows-only APIs.

**Describe the solution you'd like**

CI should also check that debug built fine.

**Additional context**

Example here: bf5a39c14

**Comment by buepas** [comment]
I think the label `good first issue` does not apply well to this issue, since only trusted contributors are allowed to make changes to the build workflow

**Comment by buepas** [comment]
As added with #1500 that should be easily doable. The only question I got is, how the docker-image used in the workflow differs from local docker building, because the files are not identical!
