### ISSUE TITLE
Make ped respawnable

### ISSUE THREAD

**Issue by thisdp** [multitheftauto/mtasa-blue#1416]
**Is your feature request related to a problem? Please describe.**
We can not respawn a dead ped now.
This related to element data sync and network resource taking.
**Describe the solution you'd like**
Make ped respawnable, we can have the same effect as spawnPlayer.

**Comment by qaisjp** [comment]
Is this a duplicate of #414?

**Comment by thisdp** [comment]
> Is this a duplicate of #414?

spawnPed, instead of destroy and create again.

**Comment by qaisjp** [comment]
> instead of destroy and create again

#414 doesn't mention destroying and creating again

**Comment by qaisjp** [comment]
Duplicate of #414
