### ISSUE TITLE
Server names appearing blank

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-blue#1432]
**Describe the bug**
There are some servers that has missing names. To summarize the issue, Server names show up just fine when it's first rendered on screen but disappaers and shows blank immediately. (or maybe after refresh operation is done.)

**To reproduce**

Open Server Browser, scroll around and you'll see that some servers have blank names. Here's a video that explains it:
https://cdn.discordapp.com/attachments/307874986721542144/707645848745410590/MTA__San_Andreas_2020-05-06_19-31-20.mp4

**Expected behaviour**
Server names should be showing instead of appearing blank

**Screenshots**
Here's server browser when first opened:
![1unknown](https://user-images.githubusercontent.com/24281147/81475197-5a957680-9213-11ea-9c41-c19524c96214.png)

here it is after (2 servers have blank names)
![2unknown](https://user-images.githubusercontent.com/24281147/81475209-726cfa80-9213-11ea-8b05-0694794aa180.png)

**Version**
This bug doesn't appear on stable version(v1.5.7-release-20447) of MTA but it's present in  v1.5.7-release-20520

**Additional context**
I use built-in auto updater in settings > advanced to get nightly versions. 
![image](https://user-images.githubusercontent.com/24281147/81475456-04c1ce00-9215-11ea-8890-5ba488e8b348.png)

**Comment by StrixG** [comment]
This bug appeared in r20462 with the Discord integration

**Comment by qaisjp** [comment]
Did it go away in [r20528](https://buildinfo.mtasa.com/?Revision=20528&Branch=) /  https://github.com/multitheftauto/mtasa-blue/commit/f6d1ffe35e1292651043bfc709f4aa577ffcdc83

**Comment by StrixG** [comment]
r20462 also changed something in [CServerList](https://github.com/multitheftauto/mtasa-blue/commit/850c76d4cc88fe085d389d5a6e46f0cd2da1996e#diff-c281c2fdef699e9b6996ef1b87a8efde). Maybe these changes caused it.

**Comment by CrosRoad95** [comment]
you can just name server using hard space: alt + 0 1 6 0
and it looks like:
![image](https://user-images.githubusercontent.com/22455534/82239479-1869e480-9939-11ea-9203-021d3a028cc1.png)

**Comment by zo3n** [comment]
Also note that player count is incorrect for those blank servers as well. When you refresh the list, their correct name appears with their player count (e.g 38/100) and then 1 second later when it becomes blank again, player count also changes to (e.g 0/100)

**Comment by ccw808** [comment]
Possible issue: https://github.com/multitheftauto/mtasa-blue/commit/850c76d4cc88fe085d389d5a6e46f0cd2da1996e#r39262444

**Comment by qaisjp** [comment]
> Possible issue:
>
> https://github.com/multitheftauto/mtasa-blue/blob/850c76d4cc88fe085d389d5a6e46f0cd2da1996e/Client/core/CQueryReceiver.cpp#L158-L159
>
> `i` should be incremented even when the `if` statement is false

Nice find. I've done [a diff](https://www.diffchecker.com/plyVy91i), significant changes shown below:

![image](https://user-images.githubusercontent.com/923242/82247568-81a02680-993e-11ea-878f-ceced03e7d0b.png)


/cc @0x416c69

**Comment by qaisjp** [comment]
Have a patch ready for testing in #1446
