### ISSUE TITLE
getValidPedModels() won't check if and id was allocated as a ped skin after ID 312

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#1436]
**Describe the bug**
getValidPedModels checks every ID from 0 to 312 to see if they are in fact ped skins. However it doesn't check if, for example, ID 3188 is a ped skin or not.

**Expected behaviour**
getValidPedModels() should also check if the allocable skins ID had been in fact allocated.

**Version**
Multi Theft Auto v1.5.7-release-20520

**Comment by qaisjp** [comment]
Thanks for reporting this.

When this is fixed, we should include information on the [`getValidPedModels`](https://wiki.multitheftauto.com/wiki/GetValidPedModels) page explaining that ped models from [`engineRequestModel`](https://wiki.multitheftauto.com/wiki/engineRequestModel) are included, and therefore those models could disappear from this table.
