### ISSUE TITLE
engineLoadDFF can't load some dff's from buffer.

### ISSUE THREAD

**Issue by TheNormalnij** [multitheftauto/mtasa-blue#1444]
**Describe the bug**
Some DFF's ( all have 0x2B anim section in beginning ) can't be loaded from buffer. 
From file these dff's load well.

**To reproduce**
[testDff.zip](https://github.com/multitheftauto/mtasa-blue/files/4639181/testDff.zip)
Use command /testdff from this test resouce

**Expected behaviour**
I can load this dff from buffer.

**Version**
Multi Theft Auto v1.5.7-release-20537

**Comment by TheNormalnij** [comment]
Seems  like a small issue in CheckFile method in CNet.

**Comment by Pirulax** [comment]
interesting, but why does it work just fine when loading it from a file?

**Comment by qaisjp** [comment]
> interesting, but why does it work just fine when loading it from a file?

Because we use a specific heuristic to detect if a string is actually a DFF, and it didn't work correctly for all DFFs
