### ISSUE TITLE
Server crashed some time after modifying and restarting a script

### ISSUE THREAD

**Issue by Grafu** [multitheftauto/mtasa-blue#1461]
**Describe the bug**
[https://upload.mtasa.com/u/465363034/dumps.zip_](https://upload.mtasa.com/u/465363034/dumps.zip_)

No information at the tail of server.log . Just modified and restarted a script some time ago before the crash.

**To reproduce**

Not sure

**Expected behaviour**

Should not crash like this.

**Version**

MTA:SA Server v1.5.7-release-20512
Linux Debian Buster 10.4

**Comment by qaisjp** [comment]
This is a problem that is being resolved in net, thanks for the report!
