### ISSUE TITLE
setCameraMatrix bug

### ISSUE THREAD

**Issue by borsuczyna** [multitheftauto/mtasa-blue#1462]
Hello I found setCameraMatrix bug (look radar, fix is setCameraTarget after resource restart)
video: https://youtu.be/LODogKhtfAM

**Comment by qaisjp** [comment]
Please can you provide a simple script to reproduce this?

**Comment by Lpsd** [comment]
Please update your issue to follow the [bug report template](https://github.com/multitheftauto/mtasa-blue/issues/new?labels=bug&template=bug_report.md).

Can you provide a basic resource to reproduce the issue?

**Comment by qaisjp** [comment]
Duplicate of #1463
