### ISSUE TITLE
dxDrawMaterialPrimitive crashes MTA

### ISSUE THREAD

**Issue by thisdp** [multitheftauto/mtasa-blue#1487]
**Describe the bug**
Calling dxDrawMaterialPrimitive crashes MTA

**To reproduce**
```lua
local img = dxCreateTexture("texture.png")
addEventHandler("onClientRender",root,function()
    local tab = {
        {200,200,0xFFFFFFFF,0,0},
        {400,200,0xFFFFFFFF,1,1},
        {400,400,0xFFFFFFFF,1,1},
    }
    dxDrawMaterialPrimitive("trianglestrip",img,true,unpack(tab))
end)
```

**Expected behaviour**
dxDrawMaterialPrimitive shouldn't crash MTA

**Screenshots**
![image](https://user-images.githubusercontent.com/30386052/83398869-ce055f00-a432-11ea-9e01-3bed6389450c.png)

**Version**
Client: Multi Theft Auto v1.5.7-release-20519

**Comment by Pirulax** [comment]
Maybe provide us some crash dumps? It seems like its `assert`, because its a seg fault, and `assert` works by segfaulting.

**Comment by thisdp** [comment]
[client_1.5.7-release-20519.0.000_core_000fab27_5_DGMb_0100007F_55F3_004_87E65_20200530_1907.rsa.zip](https://github.com/multitheftauto/mtasa-blue/files/4739732/client_1.5.7-release-20519.0.000_core_000fab27_5_DGMb_0100007F_55F3_004_87E65_20200530_1907.rsa.zip)

**Comment by Pirulax** [comment]
Not the public one, I cant debug it. I need the private one.

**Comment by Pirulax** [comment]
Well, i could just test it by myself actually..
