### ISSUE TITLE
Trigger onClientVehicleEnter/Exit when warping/removing ped

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#1492]
**Describe the solution you'd like**
I think that vehicle enter/exit events should be triggered when using functions warpPedIntoVehicle and removePedFromVehicle

**Describe alternatives you've considered**

**Additional context**

**Comment by ricksterhd123** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/159d291eb164a1456aeb43edd745cb21816b7662/Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L4144

https://github.com/multitheftauto/mtasa-blue/blob/159d291eb164a1456aeb43edd745cb21816b7662/Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L4189

**Comment by FileEX** [comment]
Oh, okay but client vehicle events also should be triggered when use warpPedzintoVehicle and removePedFromVehicle also on server-side. Because the localPlayer (client) is in vehicle (or without), but without enter/exit client events

**Comment by ricksterhd123** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/fd17e0765131c98a4bdde414f05fc72fcbe1b611/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L9780
https://github.com/multitheftauto/mtasa-blue/blob/fd17e0765131c98a4bdde414f05fc72fcbe1b611/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L9831

Is this not working?

**Comment by StrixG** [comment]
I've tested all related events and noticed that `onVehicleExit` and `onPlayerVehicleExit` events don't work for peds (excluding players). All other events seem to be working fine.

Test video: https://youtu.be/gDebqJROpx8
Test resource: [test_enterexitvehicle.zip](https://github.com/multitheftauto/mtasa-blue/files/4731524/test_enterexitvehicle.zip)
Commands: `create, warp, warpped, remove, removeped`

**Comment by ricksterhd123** [comment]
According to wiki: "The player class represents pedestrians controlled by clients. A player object is created when a client connects to the server and destroyed when he quits. Players cannot be created or destroyed otherwise." Both onVehicleExit and onPlayerVehicleExit only take player elements. 

My best guess is that peds were client-side at some point but now they're are shared. Maybe onVehicleExit should give a ped instead of a player and it has also just come to my attention that onVehicleExit and onPlayerVehicleExit seem to do the same thing but source is different.

**Comment by FileEX** [comment]
It's don't working for players.

In resource1 i have
```lua
addEventHandler('onClientVehicleEnter', root, function(plr,seat)
	if (plr == localPlayer and seat == 0) then
		if (show) then
			initalizeInteraction(true); -- bindKey
		end
	end
end);

addEventHandler('onClientVehicleExit', root, function(plr,seat)
	if (plr == localPlayer and seat == 0) then
		if (show) then
			initalizeInteraction(false); -- uninbKey
		end
	end
end);
```
And i have in resource2
```lua
warpPedIntoVehicle(el,veh)
```

What's problem? - After warping player to vehicle, key isn't binding. Player have exit from vehicle and enter again to bind key.

**I warp player on server-side** this is source of problem?

**Comment by StrixG** [comment]
Your example works perfectly fine for me and the key binds.
[resources.zip](https://github.com/multitheftauto/mtasa-blue/files/4801408/resources.zip)
