### ISSUE TITLE
Transparent attribute in createBrowser/guiCreateBrowser doesn't work

### ISSUE THREAD

**Issue by Rob3681** [multitheftauto/mtasa-blue#1493]
**Describe the bug**
If you set the transparent attribute to true in createBrowser/guiCreateBrowser and load a page without a background, the background in MTA is white and not transparent. This problem did not occur in 20561. It is probably new since 20566. Maybe this is related to commit 42cb6691357adb135e91f50b2355836f2c5a9e07?

**Version**
Multi Theft Auto v1.5.7-release-20566

**Reproduction steps**

1. Apply following patch to `webbrowser` resource to enable browser transparency

   ```diff
	diff --git a/[gameplay]/webbrowser/WebBrowserGUI.lua b/[gameplay]/webbrowser/WebBrowserGUI.lua
	index 6e82888..32b2a75 100644
	--- a/[gameplay]/webbrowser/WebBrowserGUI.lua
	+++ b/[gameplay]/webbrowser/WebBrowserGUI.lua
	@@ -20,7 +20,7 @@ function WebBrowserGUI:constructor()
	        self.m_ButtonClose:setProperty("HoverTextColour", "FF990909")
	        self.m_ButtonClose:setFont("default-bold-small")
	
	-       self.m_Browser = GuiBrowser(5, 62, sizeX - 10, sizeY - 67, false, false, false, self.m_Window)
	+       self.m_Browser = GuiBrowser(5, 62, sizeX - 10, sizeY - 67, false, true, false, self.m_Window
	```
2. Go to `mtasa.com/asdfasdf` to see 404 page
3. Background should be transparent. It is white!

**Comment by qaisjp** [comment]
Screenshot from @Pirulax:

![image](https://user-images.githubusercontent.com/923242/83940062-b551cc00-a7d9-11ea-93b0-cb499afa6956.png)

**Comment by qaisjp** [comment]
Relevant issue upstream: https://bitbucket.org/chromiumembedded/cef/issues/2938/osr-transparent-background-broken-since

**Comment by Xenius97** [comment]
Confirmed. CEF is broken.

![101750591_1102357803483668_1448336552483054696_n](https://user-images.githubusercontent.com/6568348/83941598-f0a9c600-a7ec-11ea-8dd0-1aa886b5ec51.png)
