### ISSUE TITLE
processLineOfSight cannot collide with "seeThroughStuff" even when its specified as argument

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#1512]
**Describe the bug**
The title says it all, processLineOfSight will never report a hit with an object that has "seeThroughStuff" as collision material specified (Some fences that can be shot through). 
Interestingly, isLineOfSightClear works correctly and reports a hit.

**To reproduce**
1. Go to editor
2. Place object 1412 right in front of your camera while your camera is facing north
3. Run this code:
crun x, y, z = getCameraMatrix() hit = isLineOfSightClear(x, y, z, x, y+10, z, false, false, false, true, false, true, false) outputChatBox("hit: "..tostring(hit))
4. see that isLineOfSightClear was able to collide with your fence
5. Now run this code:
crun x, y, z = getCameraMatrix()  hit, _, _, _, elem, _, _, _, mat = processLineOfSight(x, y, z, x, y+5, z, false, false, false, true, false, true, false, true) outputChatBox("hit: "..tostring(hit))
6. No hit reported, but "seeThroughStuff" is checked

**Expected behaviour**
processLineOfSight should hit

**Multi Theft Auto v1.5.7-release-20565**

**Additional context**
These fences use collision materials 52 or 55, which can be shot through. This material is specified as "seethrough". I know, its confusing, but thats how it is.
This bug is the reason why you can click these fences in the editor, but you cant see their name. The ray flies through them and reports a hit position behind the fence.

**Comment by CrosRoad95** [comment]
try change all ( to make sure flag is set ) surfaces "seethrough" to true/false and see what's the result https://wiki.multitheftauto.com/wiki/EngineSetSurfaceProperties

**Comment by Einheit-101** [comment]
It performs as expected, processLineOfSight literally stops working.
crun for i=0, 200 do engineSetSurfaceProperties(i, "seethrough", true) end
-> No more hits detected

**Comment by Pirulax** [comment]
If we can belive the 're3' reversed code, deep down this is what `seeThroughStuff` does:
```cpp
if(!ignoreSeeThrough || model.spheres[i].surface != SURFACE_GLASS && model.spheres[i].surface != SURFACE_TRANSPARENT_CLOTH)
```
(Same for boxes and triangles in the model)

Code [here](https://github.com/GTAmodding/re3/blob/b77d044729c41fb35599525b27357e1b7d7f173a/src/core/Collision.cpp#L1182)

Edit: Seems a little odd, this probably isnt the code used in SA, because here, after setting the flag by hand, it works.

**Comment by Pirulax** [comment]
I think we need the SA source code to solve the problem. @saml1er maybe you have some info on this one?

**Comment by Pirulax** [comment]
@Einheit-101 what happens if you manually set `seeThru` flags for modelid's that you know are `seeThru`?
Does `engineGetSurfaceProperties` by default return the correct value for `seeThru` for the above mentioned modelids?

**Comment by Einheit-101** [comment]
-engineGetSurfaceProperties returns TRUE (correct)
-Manually enabling the surface property works, but does not solve the bug, processLineOfSight still cant see these objects
**-Manually disabling seethrough on all materials does not work either, processLineOfSight cant see the fence even when seethrough is disabled!**


**After doing some more investigation i will close this issue in favor of https://github.com/multitheftauto/mtasa-blue/issues/1513 because that one combines all issues with processLineOfSight together.**
