### ISSUE TITLE
More target elements for engineApplyShaderToWorldTexture

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#1514]
**Description**
Currently engineApplyShaderToWorldTexture can only use peds, players, vehicles and objects as target elements. I would like to see other visual elements available aswell:
-Effects (Very and most important)
-Searchlights
-Markers
-Pickups
-Blips
-Projectiles

**Comment by qaisjp** [comment]
Duplicate of #1111
