### ISSUE TITLE
Fixing the whole gta_sa.exe mods

### ISSUE THREAD

**Issue by mertcan4555** [multitheftauto/mtasa-blue#1523]
I noticed that if we open gta_sa with 7-Zip, We will see 2 .data files, if staffs block every change in the .data file which is 256 kb, there will not be any exe mods because this file edits the game pyhsics.

For example: this file has the information of bugged and not blocked offsets which i reported.

![Adsız](https://user-images.githubusercontent.com/53582398/84661288-d2497600-af22-11ea-9ee9-28d28884a103.jpg)

P.S sorry for not following the rules, I am new at github.

**Comment by Lpsd** [comment]
This issue doesn't follow the issue template - and is already being worked on.
