### ISSUE TITLE
Hash function return string is not in lowercase anymore

### ISSUE THREAD

**Issue by botder** [multitheftauto/mtasa-blue#1526]
**Describe the bug**
Before the changes to the Lua argument parser, **hash** used to return a lowercase hexadecimal string.

**Old code**
https://github.com/multitheftauto/mtasa-blue/blob/a4f447ae8047b6d2d65077f093adff69b16b3246/Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp#L90-L95

**New code**
https://github.com/multitheftauto/mtasa-blue/blob/629f96bedf261c8ba1da5d165d141988555d0034/Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp#L50-L53
https://github.com/multitheftauto/mtasa-blue/blob/629f96bedf261c8ba1da5d165d141988555d0034/Shared/sdk/SharedUtil.Hash.hpp#L593-L598
https://github.com/multitheftauto/mtasa-blue/blob/629f96bedf261c8ba1da5d165d141988555d0034/Shared/sdk/SharedUtil.Hash.hpp#L519-L531

**Expected behaviour**
Output must be in lowercase.

**Comment by qaisjp** [comment]
```diff
-      return GenerateHashHexString(hashFunction, strSourceData);
+      return GenerateHashHexString(hashFunction, strSourceData).ToLower();
```

Just this?

**Comment by botder** [comment]
LGTM
