### ISSUE TITLE
Add on(Client)ElementDimensionChange

### ISSUE THREAD

**Issue by AfuSensi** [multitheftauto/mtasa-blue#1539]
**Is your feature request related to a problem? Please describe.**
Currently you need to keep checking an element's dimension to detect a change. This should ideally be handled by an event.

**Describe the solution you'd like**
Implement `onElementDimensionChange` and `onClientElementDimensionChange` events.
Similar to `onElementModelChange` and `onClientElementModelChange`

**Describe alternatives you've considered**
Constantly comparing `getElementDimension` to the previous value.
`addDebugHook` hooked to `setElementDimension`, yikes.

**Additional context**
There's actually a [closed pr](https://github.com/multitheftauto/mtasa-blue/pull/239), but it looks like it has been abandoned.
It also does not include a client variant of this proposed event, which is important in scripts that do client side dimension handling, like a race car hide resource that puts elements in another dimension to hide them from localPlayer.

**Comment by Pirulax** [comment]
This seems like useful, +1
