### ISSUE TITLE
string.len  counts characters incorrectly

### ISSUE THREAD

**Issue by Hiroszek** [multitheftauto/mtasa-blue#1540]
Text: "Blad" Characters: 4
Text: "Błąd" Characters: 6
Text: "Cma" Characters: 3
Text: "Ćma" Characters: 4

As you can see above, it counts Polish characters twice

**Comment by Disinterpreter** [comment]
I think the problem was solved. But for the history.

https://wiki.multitheftauto.com/wiki/Server_Scripting_Functions#UTF8_Library
