### ISSUE TITLE
'Download Resources' Button

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1552]
I'll be cool to have a 'Download Resources' button in Server Browser that would allow to download Client-Sided resources from Fast DL without actually connecting to the server - this can make server less loaded when a lot of players connect into the new server(at the server start f.e.).
Could be disabled in server settings if files are f.e. secured by script after connection, security reasons.

**Comment by Pirulax** [comment]
There's that beautiful template, and you still managed to delete it?

**Comment by Allerek** [comment]
> There's that beautiful template, and you still managed to delete it?

Imo template for few words isnt that necessary.

**Comment by Pirulax** [comment]
Yeah, okay.
I believe you can add external HTTP server**S**, so downloading while connecting shouldn't cause any problems

**Comment by Allerek** [comment]
> Yeah, okay.
> I believe you can add external HTTP server**S**, so downloading while connecting shouldn't cause any problems

It will not cause a problem, but still player would have to connect to server, when a lot of players connect on new server start-it causes a lot of load, this could reduce it.

**Comment by znvjder** [comment]
We cant add an external http server. For this work we need to use a new port from which we could retrieve resources.

**Comment by qaisjp** [comment]
Thanks for the report.

Please edit your original post and fill in this template:

```
**Is your feature request related to a problem? Please describe.**
<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->

**Describe the solution you'd like**
<!-- A clear and concise description of what you want to happen. -->

**Describe alternatives you've considered**
<!-- A clear and concise description of any alternative solutions or features you've considered. -->

**Additional context**
<!-- Add any other context or screenshots about the feature request here. -->
```

Once you've edited your original post, leave another comment and we'll reopen the issue.

In this case, the first field in the above template will help us understand exactly the problem you're trying to solve. This allows us to explore multiple solutions, some of which may be more user friendly.

In the future when filing issues on any open source project, I'd recommend you use the template as the maintainers usually put them there for a reason. Putting some effort into your issue report goes a long way.

Thanks again!
