### ISSUE TITLE
GraphQL as a way of quering elements

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1565]
**Is your feature request related to a problem? Please describe.**
Performance in general, would reduce amount of code

**Describe the solution you'd like**
Make possible to do graphql requests to get every element and its every property

**Describe alternatives you've considered**
⛔ 

**Additional context**
example way of quering elements
```lua
elements = queryElements([[
query getVehiclesByModel($model: Int)
{
  vehicle(model: $model)
  {
    element, model, color, interior, dimension,
    customData
    {
      owner, blabla // getElementData(element, "owner"), getElementData(element, "blabla")
    }
  }
}
]],
 { "model" = 404 },
 -- here optional array of elements, or element from hierarchy to start search, by default root
)
for i,v in ipairs(elements.vehicle)do
  print(v.element, v.model, v.color, v.interior, v.dimension, v.customData.owner, v.customData.blabla)
end
```

equivalent of:
```lua
local vehicles404 = {}
for i,v in ipairs(getElementsByType("vehicle"))do
  if(getVehicleModel(v) == 404)then
    table.insert(vehicles404,{
      element = v,
      model = getElementModel(v)
      color = {getVehicleColor(v)},
      interior = getElementInterior(v),
      dimention = getElementDimension(v),
      customData = {
         owner = getElementData(v, "owner"),
         blabla = getElementData(v, "blabla"),
       }
    })
  end
end
```

**Comment by jushar** [comment]
There's only a little use case for this in my opinion. In most cases that I'm aware of the filter operations are relatively simple. Also, MTA doesn't store the elements in a way that would allow fast searching (i.e. indexes).

If you need it for a specific use-case, I'd recommend a Lua-only implementation like https://github.com/bjornbytes/graphql-lua
