### ISSUE TITLE
dxDrawPrimitive* & dxDrawMaterialPrimitive* color bug

### ISSUE THREAD

**Issue by christophercampbell1** [multitheftauto/mtasa-blue#1581]
**Describe the bug**
When you use one of the functions in the title, and apply a color with alpha < 255, the output color is different.

**To reproduce**
[primitivebug.zip](https://github.com/multitheftauto/mtasa-blue/files/4997972/primitivebug.zip)

**Expected behaviour**
Work the way like other dxDraw*

**Screenshots**
Both have the same colors, but the left have smaller alpha than 255
![mta-screen_2020-07-29_14-21-09](https://user-images.githubusercontent.com/52787694/88799732-3492c900-d1a7-11ea-8c60-a4d7f02cdf47.png)

**Version**
Client v1.5.7-release-20604
Server v1.5.7-release-20582

**Additional context**
Because i'm using the dxDrawMaterialPrimitive3D for my custom water cannon effect, the current workaround is the texture replacement shader with color manipulating.

**Comment by Pirulax** [comment]
Haven't looked at the code, but afaik @CrosRoad95 used SColorARGB, or whatever for passing the value around, when he shouldve used SColor. @qaisjp probably can say more about this

**Comment by qaisjp** [comment]
I don't think that would cause the issue. SColorARGB (et al.) are only constructors, I'd be surprised if there was a runtime difference. 

<details><summary>Additional Information</summary>

Good:

```cpp
SColor x = SColorARGB(255, 255, 0, 0)
```

Bad:

```cpp
SColorARGB y = SColorARGB(255, 255, 0, 0)
```

`SColorARGB` inherits from `SColor` and I believe the only difference is that it provides a different constructor.

https://github.com/multitheftauto/mtasa-blue/blob/deada6058cfdee17cac994eb66c25c40408c35a6/Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h#L204-L208

</details>

**Comment by Pirulax** [comment]
Tbh, I think we should change this non-sense behaviour, and add some magic:
```cpp
SColor SColorARGB(unsigned char a, etc...) { return {r, g, b, a}; }
```
But this is off topic, I just wanted to share my opinion
