### ISSUE TITLE
chat text editing functionality improvements...

### ISSUE THREAD

**Issue by Zorono** [multitheftauto/mtasa-blue#1586]
***Is your feature request related to a problem? Please describe.***
not related directly...
It'd be great if you added the ability to use **Left/Right Keyboard arrows** to switch between my **Chat's input characters**... (just like a simple text editor) instead of rewriting the whole text again just to correct a single word...

***Describe alternatives you've considered***
rewriting the whole text again just to correct a single word...

**Comment by MrDadosz** [comment]
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/755

**Comment by qaisjp** [comment]
Duplicate of #755
