### ISSUE TITLE
Add isPlayerJoiningFirstTime

### ISSUE THREAD

**Issue by xPREDATORx** [multitheftauto/mtasa-blue#1587]
**Is your feature request related to a problem? Please describe.**
To a big extent, yes. I've posted this [issue](https://github.com/multitheftauto/mtasa-blue/issues/1123) but sadly didn't come to a direct solution. The bug in that issue can be reset by restarting MTA.
With this function added, server owners can force players, who joined the server after playing on a different one, to restart their MTA before or during playing on the server.
**Describe the solution you'd like**
Add a simple server-sided function called isPlayerJoiningFirstTime(player) which returns a boolean, **false** if the player joined other servers before joining yours after launching MTA, **true** otherwise.

**Describe alternatives you've considered**

**Additional context**
Once again, this could give server owners the possibility to force players to restart their MTA before or during playing on the server, which resets this [bug](https://github.com/multitheftauto/mtasa-blue/issues/1123).
Obviously, the function could have other beneficial use.

**Comment by qaisjp** [comment]
Hi, thanks for your proposal but I think we should focus on fixing the underlying bugs rather than facilitate this sort of hacky workaround.
