### ISSUE TITLE
getBoundKeys() doesnt react for unbindKey()

### ISSUE THREAD

**Issue by Cyber52** [multitheftauto/mtasa-blue#1596]
**Describe the bug**
`getBoundKeys()` after calling `unbindKey()` returns outdated value

**To reproduce**
Client-side:
```lua
iprint(1, getBoundKeys("aaaa")) -- 1, false
bindKey("x", "down", "aaaa")
iprint(2, getBoundKeys("aaaa")) -- 2, { x = "down" }
unbindKey("x", "down", "aaaa")
iprint(3, getBoundKeys("aaaa")) -- 3, { x = "down" }
```

**Expected behaviour**
It should return `false` in the last call

**Version**
- server/client version: MTA:SA Server v1.5.7-release-18957 / Multi Theft Auto v1.5.7-release-20582

**Comment by qaisjp** [comment]
Does this change behaviour with commands showing up in Settings -> Keybinds?

**Comment by Cyber52** [comment]
> Does this change behaviour with commands showing up in Settings -> Keybinds?

After calling `unbindKey()` function it is not visible in binds list in settings so it works correctly.

**Comment by qaisjp** [comment]
What did it do before?
