### ISSUE TITLE
OOP vehicle:setHandling() not working

### ISSUE THREAD

**Issue by onikyannn** [multitheftauto/mtasa-blue#1608]
Tested on 1.5.7-9.20582.0

**Comment by AlexTMjugador** [comment]
What's exactly "not working"? Can you describe what you did and how did you expect MTA to react?

The next time, please follow the issue template when creating new issues as best as you can, because it is designed to ease troubleshooting, testing, discussion and fixes.

**Comment by gptrk0** [comment]
Alex is right, please follow the template.

And it looks good for me.
![image](https://i.imgur.com/KY3uDPh.png)

**Comment by onikyannn** [comment]
Thank you and sorry, was my mistake
