### ISSUE TITLE
toggleControl(thePlayer, "steer_forward", true) returns true, but doesn't actually work

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#1610]
**Describe the bug**
Trying to disable the "steer_forward" when entering certain vehicles, i discovered that enabling it on server-side doesn't actually work.

toggleControl() even returns true after setting "steer_forward" to true.

**THIS ONLY HAPPENS ON SERVER-SIDE, CLIENT-SIDE WORKS JUST FINE**

**To reproduce**
```lua
for _,thePlayer in ipairs(getElementsByType("player")) do
    toggleControl(thePlayer, "steer_forward", false)
    -- A 5 second timer so you can try to steer_forward
    setTimer(toggleControl, 5000, 1, thePlayer, "steer_forward", true)
end
```

**Expected behaviour**
"steer_forward" should be enabled again just like in clientside.

**Version**
Server: v1.5.7-release-20568
Client: v1.5.7-release-20582

**Additional context**
I didn't test it with "steer_back"

**Comment by Unde-R** [comment]
I don't get your point, tested the code works fine but no idea

**Comment by Unde-R** [comment]
> I don't get your point, tested the code works fine but no idea

got same results on both serverside and clientside.

**Comment by PlatinMTA** [comment]
> I don't get your point, tested the code works fine but no idea

steer_forward is working after toggling it back to true?

I'll test it again in a clean server in a moment

**Comment by Unde-R** [comment]
> > I don't get your point, tested the code works fine but no idea
> 
> steer_forward is working after toggling it back to true?
> 
> I'll test it again in a clean server in a moment

You just edited your code before it was:
`setTimer(toggleControl, 5000, 1, thePlayer, "steer_forward", true)`

**Comment by PlatinMTA** [comment]
Yeah my bad, but I can't make it work on a clean server anyway. Thanks and sorry for the trouble.

**Comment by Unde-R** [comment]
and yeah It's working fine.
