### ISSUE TITLE
White-shadow bug

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1614]
**Describe the bug**
Kind of white shadow on some map objects that dont seem to appear in single player. The bug only exsits on engine-placed objects, if you place object by yourself it wont happen.

**To reproduce**
Go in this place(LS-LV main bridge, and play with camera distance on Map Editor).

**Expected behaviour**
No white shadow.

**Screenshots**
https://cdn.discordapp.com/attachments/675031717106679819/743415893429583932/unknown.png https://cdn.discordapp.com/attachments/675031717106679819/743415915332501535/unknown.png https://cdn.discordapp.com/attachments/675031717106679819/743416967297237002/unknown.png

**Version**
Multi Theft Auto v1.5.7-release-20621

**Comment by tederis** [comment]
It looks like a typical specular. When a sun direction and a camera direction is about the same this may occur.
