### ISSUE TITLE
Detect when player left MTA Window with Windowed mode

### ISSUE THREAD

**Issue by Arci224** [multitheftauto/mtasa-blue#1632]
**Is your feature request related to a problem? Please describe.**
I want new function like a `onClientMinimaze`, which detect when player left window of MTA:SA. Because `onClientMinimaze ` function only with Full screen. And new function like a `onClientRestore`

**Describe the solution you'd like**
Add new Event Handler like `onClientLeftMTAWindow` which detect when player exit MTA Window and `onClientEnterMTAWindow` which detect when player enter MTA Window.
 
**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by Unde-R** [comment]
> I want new function like a `onClientMinimaze`, which detect when player left window of MTA:SA. Because `onClientMinimaze ` function only with Full screen. And new function like a `onClientRestore`
>
`onClientMinimize` & `onClientRestore` are events not functions.
They already exist but need some improvements.
[onClientRestore](https://wiki.multitheftauto.com/wiki/OnClientRestore)
[onClientMinimize](https://wiki.multitheftauto.com/wiki/OnClientMinimize)

**Comment by Arci224** [comment]
@Unde-R uhhh, yes sorry my bad.

**Comment by Arci224** [comment]
I think on that can be used Closed PR #185 .. (If it is still actual and can be usable.)
