### ISSUE TITLE
Texture bugs

### ISSUE THREAD

**Issue by LCorttez** [multitheftauto/mtasa-blue#1647]
everyone complains about a texture error that is becoming common, I hope you can fix it.
So far is all I know about it.

**Comment by Vadya963** [comment]
let them update to the latest version

**Comment by Einheit-101** [comment]
tbh sounds like a fault from your server, or maybe related with https://github.com/multitheftauto/mtasa-blue/issues/1394

**Comment by AlexTMjugador** [comment]
Please follow the issue template when you create a new issue, it's better for everyone. Otherwise, this issue may be closed as invalid, because it doesn't provide enough information to understand and fix it.

Can someone elaborate on what's this "texture error" all about?
