### ISSUE TITLE
attached markers having 2 ids causes server crash

### ISSUE THREAD

**Issue by KWKSND** [multitheftauto/mtasa-blue#1659]
[KWKTest.zip](https://github.com/multitheftauto/mtasa-blue/files/5191508/KWKTest.zip)

this resource will crash the server 6 seconds after you run it

if you attach a marker to an object, 
then destroy all of the object's attached elements other than the marker, 
then try to change anything about the marker the server will crash instantly.
due to the fact there are now 2 ids for a marker, the marker now exists but does not exist with a resource like this.

**Comment by qaisjp** [comment]
Probably caused by #1327 / #1363 / #1364

cc @Lpsd
