### ISSUE TITLE
Forklift bug

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1660]
If create more 5 vehicle "forklift" (id: 530) then lift don't work. But if you move away from other vehicles, the lift will work.

**Video**
https://www.youtube.com/watch?v=B7dytTnHTjc

**Comment by Einheit-101** [comment]
Interesting, does that bug affect other vehicles with special properties aswell? For example Towtruck?

**Comment by lopezloo** [comment]
Duplicate of #621
