### ISSUE TITLE
Vehicle wheel states aren't synced by default

### ISSUE THREAD

**Issue by bum8hj** [multitheftauto/mtasa-blue#1662]
**Is your feature request related to a problem? Please describe.**
- Wheel states (inflated, flat, etc.) are not synced across clients.
e.g. When I shoot someone's vehicle tire and it gets popped, only the driver (could be for passengers too, I'm not sure) of that vehicle sees them flat.

**Describe the solution you'd like**
- Wheel states should be synced across clients by default.
i.e. If I (player A) shoot the wheels of player B's car, it should look flat for me and others, and not just for player B.

**Describe alternatives you've considered**
none

**Additional context**
Since the vehicle damage models are synced (a broken door, would be broken for every player), why shouldn't the wheel states be synced too?

**Comment by PlatinMTA** [comment]
bullet_sync will kinda hotfix the issue, but the wheel state should be synced anyway, bullet_sync enabled or not

**Comment by MrDadosz** [comment]
i reported that on MantisDB and on github ( https://github.com/multitheftauto/mtasa-blue/issues/868 ), maybe it should be fixed in 1.5.8? Lights and wheels are desynced.

**Comment by botder** [comment]
Fixed in commit fe48d0968042b0bc5e5375c0c2f8f9ee2ed951ba (pull request #2399).
