### ISSUE TITLE
string.format more than 0x80000000 (32bit limit)

### ISSUE THREAD

**Issue by rifleh700** [multitheftauto/mtasa-blue#1667]
**Describe the bug**
string.format("%X", num) don't work with numbers more than 0x80000000.

**To reproduce**
```lua
iprint("0x7FFFFFFF: ", string.format("%X", 0x7FFFFFFF)) -- 7FFFFFFF
iprint("0x80000000: ", string.format("%X", 0x80000000)) -- 80000000
iprint("0x80000001: ", string.format("%X", 0x80000001)) -- 80000000 (just floored to 0x80000000)
```

**Version**
server: 1.5.7-20642
client: 1.5.7-20632
os: windows 7 32bit

**Additional context**
On older builds it works normally (i.e. server v1.5.7-release-20582)

**Comment by Pirulax** [comment]
~~the lua module is 32 bit on client side(and on the 32 bit server).
Possible solution would be to, somewhere in the C code of string.format, change that `int` to `long long`. Not sure how good of an idea that is tho / how useful it would be.

Edit: Not sure if `tostring` works? Perhaps try rounding it with math.floor to get the same result. If it still doesnt work try hacking it together with bitwise functions that are available in MTA. (What I mean is that you, in theory could bitshift a > 32 bit number into 2x < 32 bit numbers, and then `tostring(lowerHalf) .. tostring(upperHalf)`
Im pretty sure actually that there is some kind of workaround useful function on the Wiki.~~

Edit: Didn't read the "additional context" section. My bad.

**Comment by qaisjp** [comment]
> On older builds it works normally (i.e. server v1.5.7-release-20582)

We need to find the commit that causes this

**Comment by StrixG** [comment]
@qaisjp https://github.com/multitheftauto/mtasa-blue/commit/c174c73cb170e7732fc4f49681fb13780775e2a2
r20627

**Comment by qaisjp** [comment]
Nice. Should we update the build server again and hope for the best @ccw808?

**Comment by ccw808** [comment]
Yes, please apply the update

**Comment by sbx320** [comment]
Updating the build server didn't change anything. 

However looking at the code for `string.format`, it always casted to a `long` when formatting as a hex number. Changing that to a `long long` via the configuration option solves the issue.

I'm however not sure why this has ever worked. My best guess is some change in the optimizer (previously doing a transparent `long` -> `long long` by skipping the cast, and now doing the direct `long -> int` "conversion"). In any case we can just make Lua use `long long` for formatting, as all C++11 compilers are required to provide `long long`. Please retest in next nightly.
