### ISSUE TITLE
List only my servers

### ISSUE THREAD

**Issue by Daniel-kenobi** [multitheftauto/mtasa-blue#1669]
good morning, i want to make the list of servers only list some specific servers that are in my database, is it possible to do this? what classes should i change? Sorry for the question, I haven't worked with C ++ for many years and I have this project to deliver, I thank you in advance

**Comment by StrixG** [comment]
Please, ask your question in [MTA Discord](http://mtasa.com/discord). GitHub is not the appropriate place for such questions.
