### ISSUE TITLE
Can't watch youtube videos due to non working button

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#1671]
**Describe the bug**
Unclickable button on youtube prevents watching videos (unless you already managed to accept cookies)

**To reproduce**
Open youtube or a youtube video using in-game browser. (eg start webbrowser then click on that browser icon then go to youtube.com) and after 5 seconds some cookies thing comes up that you can't accept because the "I agree button" does not work.

**Expected behaviour**
For the buttons to work as I'm sure it would work in a normal browser, does CEF need an upgrade or is it because it's some non whitelisted domain messing it up?

**Screenshots**

![image](https://user-images.githubusercontent.com/253404/93794756-6ae14780-fc30-11ea-96a7-1b8697bc80ab.png)

**Version**
Multi Theft Auto v1.5.7-release-20644

**Additional context**

**Comment by HexonDev** [comment]
Same here on Multi Theft Auto v1.5.7-release-20644
I whitelisted the domain with `requestBrowserDomains` function but it didn't solve the problem

**Comment by qaisjp** [comment]
This definitely sounds like we need to whitelist an additional domain by default. Probably whichever domain is causing the images to break, font to be incorrect, and presumably JavaScript to break.

**Comment by Woovie** [comment]
Can you provide a test script? I'll gladly look into it.

**Comment by HexonDev** [comment]
> 
> 
> Can you provide a test script? I'll gladly look into it.

Yes, here is my code
[ytradio.zip](https://github.com/multitheftauto/mtasa-blue/files/5257950/ytradio.zip)

**Comment by ArranTuna** [comment]
webbrowser is a default resource just start it then click the browser button and go to youtube.com

**Comment by Woovie** [comment]
Thanks, I'll investigate and see what is wrong.

**Comment by Woovie** [comment]
I cannot replicate. Is there a particular page or thing I should do on youtube.com?

![image](https://user-images.githubusercontent.com/7304619/93817807-53916280-fc0e-11ea-8139-56902f8624fc.png)

I never got that popup.

**Comment by ArranTuna** [comment]
Because you previously accepted cookies, you'll need to clear them first.

**Comment by jayceon123** [comment]
The buttons works for me on DX and GUI browser too.
Multi Theft Auto v1.5.7-release-20637

**Comment by ArranTuna** [comment]
What youtube / google domains have you got whitelisted?

**Comment by jayceon123** [comment]
![image](https://user-images.githubusercontent.com/34610037/93819893-a1cd5280-fc5c-11ea-9307-4a46365472dd.png)

**Comment by Woovie** [comment]
I still can't replicate, nor do I see an easy way to clear cookies we've documented. Do you have a solution to clear them? I can't find one.

**Comment by ArranTuna** [comment]
I've tried adding ssl.gstatic.com to see if made any different (it didn't) and I've tried downgrading to the same revision (20637) and that didn't help either.

Also google.com doesn't even work for the same reason.

This whitelist thing is really annoying, all the websites I've tried so far are broken, mainly images don't appear.

I don't know where CEF is storing cookies, I tried checking file read / writes on resource monitor while browsing websites that likely stored cookies but didn't see any file activity.

**Comment by Dark-Dragon** [comment]
Allowing www.gstatic.com seems to make the button functional for me. It should then prompt for consent.google.com and you're fine.

**Comment by AfuSensi** [comment]
I suggest taking a look at the output of [onClientBrowserResourceBlocked](https://wiki.multitheftauto.com/wiki/OnClientBrowserResourceBlocked) next time you encounter this problem.

**Comment by ArranTuna** [comment]
> 
> 
> I suggest taking a look at the output of [onClientBrowserResourceBlocked](https://wiki.multitheftauto.com/wiki/OnClientBrowserResourceBlocked) next time you encounter this problem.

Thanks. I added this example from there to the web browser resource:

```
addEventHandler("onClientBrowserResourceBlocked", self.m_Window, function(url, domain, reason)
	if (reason == 0) then
		lastBrowser = source
		requestBrowserDomains({domain}, false, function(accepted, newDomains)
		if (accepted == true) then
			reloadBrowserPage(lastBrowser)
		end
		lastBrowser = nil
		end)
	end
end)
```

and it asks for a load of different domains:

googleads.g.doubleclick.net
fonts.gstatic.com
stats.g.doubleclick.net
www.gstatic.com
yt3.ggpht.com
ssl.google-analytics.com
www.google.co.uk
fonts.googleapis.com
consent.google.co.uk

In fact even if these got added to default whitelist it might not fix it because I just did it again and now there's some different domains being requested.

And they don't all come in 1 go it has to reload the page about 4 times. At least now the browser is functional as a browser.

I don't even understand how this domain whitelist protects anyone when chances are if anyone did send anyone to a malicious domain or whatever they'd just accept it without thinking or knowing that the domain is malicious. Especially when they have to accept all sorts of garbage like just to get on youtube.com look at what I had to accept just by going on 2 youtube videoes:

![image](https://user-images.githubusercontent.com/253404/93993012-2667c000-fd86-11ea-8dd5-b87666a140a6.png)

**Comment by AlexTMjugador** [comment]
> I don't even understand how this domain whitelist protects anyone when chances are if anyone did send anyone to a malicious domain or whatever they'd just accept it without thinking or knowing that the domain is malicious.

If users do indeed not accept shady domains, it is a pretty effective security measure. But, as you said, if accepting all those domains is needed just to get YouTube working, I feel that it is also easy that the users feel "fatigued", so they dismiss the implications of what are they actually accepting.

To improve on this, I came across some ideas for improvements that may reduce the burden on the user without compromising its security that much, although I don't know how easy they are to implement:

- When a user accepts a domain and loads a web page on it, assume that any other domains that page (or a script loaded by that page) tries to load are trustworthy and accept them automatically. For its own reputation, a trustworthy website usually doesn't try to load resources in shady domains, unless the content of that website is user-generated and it somehow escaped any moderation policy of that site, which I think is rare (and, if the user accepts a known non-moderated user content website, even expected). If we implement this approach, I think we should warn the users about this additional implication that accepting a domain will have.
- Check the URL of the resource that is being loaded against a comprehensive nasty website list like [Google Safe Browsing](https://developers.google.com/safe-browsing/v4), and block the resource if there is a match without user intervention. Currently, that list only contains sites that [serve malware, phishing and shady software](https://developers.google.com/safe-browsing/v4/reference/rest/v4/ThreatType), and not "distasteful" sites in general, but from a security standpoint it should be enough to protect users. Of course, using a list like this raises the question of whether we can trust its maintainer to keep it accurate, updated and not biased, but, in the case of Google's list, I think it's worth mentioning that both Chrome and Firefox (and probably other browsers too) already use it to block access to nasty websites.

**Comment by ArranTuna** [comment]
I think the dependencies should be automatically accepted. This will fix most websites being broken without any real security implication.

**Comment by qaisjp** [comment]
We already have a wildcard whitelist here:

https://github.com/multitheftauto/mtasa-blue/blob/4be08f43961d3414c84787730a9ad372c5407b81/Client/cefweb/CWebCore.cpp#L255-L256

We can immediately extend that to include, or whatever is necessary for YouTube to be functional:

```
*.gstatic.com
*.ggpht.com
*.googleapis.com
```

Pull requests welcomed and we can merge it asap to fix this issue's YouTube problem. (We don't need all of the entries because some of them are just for ads.)

The other ideas are interesting and I think we could discuss that in more detail in a brand new issue. I agree approval fatigue is problematic.

**Comment by Dutchman101** [comment]
> **Expected behaviour**
> For the buttons to work as I'm sure it would work in a normal browser, does CEF need an upgrade or is it because it's some non whitelisted domain messing it up?

The root cause is that Google recently refactored their consent system, said pop-up is a new design and it will now block you from doing anything on most Google services until accepted. They wanted more intrusive/pushy consent pop ups, and their resources weren't whitelisted in MTA.
