### ISSUE TITLE
mta sa freezing problem / bug

### ISSUE THREAD

**Issue by xskybox** [multitheftauto/mtasa-blue#1674]
Hello , im bob , i am recently having a freezing issue on MTA 1.5.7 last version , so when i am playing normal and i press f8 , the game freezes with no mouse movment and the audio keeps going normal , i go to task manager to end the "gtasa.exe" task and its using "02% , 05%" of the cpu , i am having this issue for a long time and i just want to ask for a solution.
the bug is shown in these 2 videos : https://youtu.be/Pm3e76QcORY https://youtu.be/8cDuQLXacOg

Contact info :
My Discord is : "!                    TheCrazyBob#3039" (with spaces)
My Email : thecrazybob06@gmail.com
My Insta : thecrazybob_

**Comment by Vadya963** [comment]
client 1.5.7-20651 there is no freeze

**Comment by ghost** [comment]
Maybe you have bind something on F8, do you face this issue in all server? Because it can be caused of bad script. Also make sure that no apps using F8 shorcut or something simillar.

**Comment by Dutchman101** [comment]
Please, first get [client support](https://forum.mtasa.com/forum/83-client/) for this issue. It's very likely to be something on your end.
