### ISSUE TITLE
isElementWithinMarker bug

### ISSUE THREAD

**Issue by Vadya963** [multitheftauto/mtasa-blue#1678]
**Describe the bug**
If you attach a marker to a vehicle, the isElementWithinMarker function will work on the 10th attempt. Works on 20645 and doesn't work on 20646

**To reproduce**
run this code
```lua
local marker = false
addCommandHandler ( "vehicle",
function ( localPlayer )
	local x,y,z = getElementPosition( localPlayer )
	local vehicle = createVehicle( 596, x,y,z )
	marker = createMarker( x,y,z, "cylinder", 1.5 )
	attachElements( marker, vehicle, 0,-4,-1 )
end)

addCommandHandler ( "checkmarker",
function ( localPlayer )
	print(isElementWithinMarker( localPlayer, marker ))
end)
```

**Expected behaviour**
it should always work

**Version**
1.5.7-20651

**Comment by Pirulax** [comment]
[r20646](https://github.com/multitheftauto/mtasa-blue/commit/a94fcb64202d1f43f633bfb83ef24ce347502b81)

I don't see anything that could directly cause this issue. Maybe @saml1er can help?

**Comment by ghost** [comment]
I can't reproduce this bug.

**Comment by Vadya963** [comment]
and you are in the marker?

**Comment by Vadya963** [comment]
I'll record a video

**Comment by ghost** [comment]
> 
> 
> and you are in the marker?

yes

EDIT: The new nightly will be up shortly, then you can test it again and see if it helps. I made some changes to the marker code in 90f429649cfe219c376d875c0014e680e2bc2d9d.

**Comment by Vadya963** [comment]
everything works, thank you
