### ISSUE TITLE
Force people to opt back into Default release type when they update to 1.5.8

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1708]
**Is your feature request related to a problem? Please describe.**

people went to nightly because of discord rich presence, and are prolly still on nightly unnecessarily

**Describe the solution you'd like**

Ideally when they update MTA they get a window saying "We've reset you back to Default, please go change your settings again if you want Nightly updates." or something like that

**Describe alternatives you've considered**

**Additional context**

**Comment by qaisjp** [comment]
i have little idea how to do this correctly without writing some hacky workaround that tracks the most recent update version

**Comment by PlatinMTA** [comment]
Would it be a good idea to add a node in coreconfig.xml meaning that they had already been reseted back to Default? So it only happens once and it can be read directly from the config at the start.

Also it should be added by default in new releases so it doesn't happend again. Maybe the node should have a number value that can be changed in the future if some future update makes a lot of users go to nightly again, so we dont need to create a new node every time that happens.

Thinking again this method seems like a hack, idk if its a good idea anymore.

**Comment by qaisjp** [comment]
yeah. tbh fuck it we can do this later, we don't need to block 158 with this

**Comment by Woovie** [comment]
I'm pinning for visibility. This issue is a current top priority so we can merge all of our PRs.

**Comment by qaisjp** [comment]
OK, [r20670](https://buildinfo.mtasa.com/?Revision=20670&Branch=) has landed and has been fully rolled out.

We can merge branches now as long as we don't bump `nightly` in the MTAHQ auto-updater system for a while, so that players are forced back onto Default. **This is because the forced opt-out will only happen if they are on r20670, and not if they are upgraded to any revision above r20670**.

I'd suggest **not bumping `nightly`** for 1 week, but we might want to stretch that longer (2 weeks) to make sure we get the most players currently on nightly. cc @ccw808 and @Dutchman101 for visibility, since you both frequently bump nightly.

**Test 1: making sure these builds work fine**

I downloaded the nightly installer and can confirm it immediately showed the "Please opt back in" popup message, and the `build_type` set to `0`. That's good 👍 

Then I restarted MTA to test that the popup does not appear again, and that worked fine. Then I cleared the registry setting.

**Test 2: rollout**

I installed the previous nightly and made sure I was set to have auto-updates. Then I bumped `nightly` in the MTAHQ auto-updater to r20670. After a few minutes, I opened MTA and the auto-updater appeared. After updating MTA, the popup message appeared again, and it all worked fine just like in **Test 1**.
