### ISSUE TITLE
Sync vehicle tire states

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#1740]
**Is your feature request related to a problem? Please describe.**

currently setVehicleWheelStates(getPedOccupiedVehicle(localPlayer), ...) does not sync the wheel states automaticly
while setVehiclePanelState(getPedOccupiedVehicle(localPlayer), ...) does sync automcliy between clients

**Describe the solution you'd like**

automaticly sync wheel states

**Describe alternatives you've considered**

manually syncing with triggerServer/ClientEvent or setElementData

**Comment by botder** [comment]
Fixed in commit fe48d0968042b0bc5e5375c0c2f8f9ee2ed951ba (pull request #2399).
