### ISSUE TITLE
setObjectBreakable as a Shared function

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1751]
**Is your feature request related to a problem? Please describe.**
setObjectBreakable should be Shared function because calling it to every player in Lua is not efficient with lot of objects

**Describe the solution you'd like**
Make that function shared, saves a lot of work and performance when you have lot of objects.

**Comment by PlatinMTA** [comment]
this is a duplicate of #990, but yeah this function should be a shared one, not clientside only

**Comment by StrixG** [comment]
Duplicate of #990
