### ISSUE TITLE
dxGetTextHeight

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1756]
**Is your feature request related to a problem? Please describe.**
Its related to a problem where we have to do a lot of math to calculate the final height of the text.

**Describe the solution you'd like**
Function that calculates text height based on
`x` `y` `rightX` `bottomY` `font` `scale`

**Describe alternatives you've considered**
We can do it now by going through every word, checking if its out of `rightX` using
`dxGetTextWidth` on the words that we have checked until now with 'while' loop.
Then we can calculate new height using `dxGetFontHeight`, and add it on every new line until we are out of words.

^Not that hards, but doing 'while' on very long messages when we have a lot of them(like custom chatbox) can really be harmful for performance.

**Additional context**
Add plox <3

**Comment by StrixG** [comment]
You can use [dxGetTextSize](https://wiki.multitheftauto.com/wiki/DxGetTextSize).
```lua
local textWidth, textHeight = dxGetTextSize("Long message", 50, 1, "default", true)
```
Does this function solve your problem?
