### ISSUE TITLE
extinguishFire in onClientVehicleDamage causes MTA crash

### ISSUE THREAD

**Issue by Tru-KaaN** [multitheftauto/mtasa-blue#1757]
**Describe the bug**
Using **extinguishFire** in **onClientVehicleDamage** causes MTA crash if vehicle caught fire by Molotov, Rocket or any explosion.

**To reproduce**
Use this code, throw a molotov and drive your vehicle through fire, you will probably get MTA crash.

> addEventHandler("onClientVehicleDamage", root, function()
    if source == getPedOccupiedVehicle(localPlayer) then
        local x,y,z = getElementPosition(localPlayer)
        extinguishFire(x,y,z, 30)
    end
end)

**Expected behaviour**
Fire should be gone and vehicle shouldn't get any more damage.

**Screenshots**
Not needed

**Additional context**
Tested multiple times in 3 different servers and crashed each time.

Crash info:

> Version = 1.5.8-release-20668.0.000
Time = Mon Oct 26 02:22:53 2020
Module = C:\Program Files (x86)\GTA San Andreas\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x0013A6FF
EAX=00001965  EBX=00B71F84  ECX=00000000  EDX=00B9BC20  ESI=00B71F80
EDI=140ED300  EBP=0028FD6C  ESP=0028FC28  EIP=0053A6FF  FLG=00210206
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

**Comment by Proxy-99** [comment]
still happens in 1.6 after testing
The program '[148] Multi Theft Auto_d.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
