### ISSUE TITLE
 Allow CJ's clothing objects to be replaced to implement my shader system.

### ISSUE THREAD

**Issue by BaronScr** [multitheftauto/mtasa-blue#1762]
**Is your feature request related to a problem? Please describe.**
the only problem is not to allow the changing of clothing objects, as this ends up limiting the use of developmental creativity. --

**Describe the solution you'd like**

I recently developed a system of clothing for other skins, similar to grozz. but I had an even bolder idea, why not use the GTA system itself and implement my clothing system? therefore, it would be even more optimized and easier to develop within the garments, including for modelers, just like in GTAV, but even if only for CJ my system has an implementation of textures where I could make unlimited models of the DFF, however for this idea I need the MTA to allow the replacement of the objects of the clothes for the realization of this idea..

**Describe alternatives you've considered**

I noticed that CJ's dff have internal dffs such as DFF: 1 DFF: 2 DFF: 3 one for the lean body another for the muscular body and another for the fat body, I took into consideration that if these parts have the replacement released I will be able to implement my shader, thus making the body part slim for both male and female as well as the other 2 using only the custom clothes system that I developed and posted on my channel..

**Additional context**
 you can see the system working on a skin that is not CJ through this link:  https://www.youtube.com/watch?v=RhUMWSCJXVg.

**Comment by tut001** [comment]
There's an existing issue for this, please see #1017

**Comment by qaisjp** [comment]
Duplicate of #1017
