### ISSUE TITLE
bitstream.h warning: function converting 'NetBitStreamInterface' to itself will never be used

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1770]
**Describe the bug**

build warning
```cpp
../Shared/sdk/net/bitstream.h:384:13: warning: conversion function converting 'NetBitStreamInterface' to itself will never be used
    virtual operator NetBitStreamInterface&() { return *this; }
            ^
```

**To reproduce**

build mta

**Expected behaviour**

no warning

**Additional context**

should be an easy fix, just remove the function?

**Comment by Pirulax** [comment]
It's a virtual function, and removing it might corrupt the ABI.
(Because I presume the actual function is in the net code)

**Comment by qaisjp** [comment]
Okay, I'll assign to ccw then
