### ISSUE TITLE
create functions does not assign unique id to the element

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1773]
**Is your feature request related to a problem? Please describe.**
```lua
a = createVehicle(404, 0,0,0)
b = createVehicle(404, 0,0,0)
c = createVehicle(404, 0,0,0)
iprint(getElementID(a), getElementID(b), getElementID(c)) -- will print 3 empty strings
```
Mta should assign random id, now this function is useless but can be helpful for referencing elements in databases, outside mta.
Now you have manually assign id - literraly noone doing it

**Describe the solution you'd like**
Assign random unique id to elements, if someone notice backward compatibility problems, this option could be enabled in some sort of config

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by LosFaul** [comment]
there is setElementID:
https://wiki.multitheftauto.com/wiki/SetElementID

the string ids are also used since forever by (gamemode) maps in .map files

also automatic random ids would only cause more RAM usage when it's not even needed

**Comment by Pirulax** [comment]
The "more RAM usage" is pretty negligible .
My main concern is backwards compatibility, as im pretty sure there are scripts that rely on this being an empty string by default.
Also "referencing elements in databases" isn't a thing if you assign random IDs..
Theres no real use of assigning a  random id, thats why `setElementID` exists.

**Comment by sbx320** [comment]
Afaik the main reason for the element ids is to be able to refer to objects in a .map from a script. I can't see any benefit of assigning random IDs to objects.

**Comment by qaisjp** [comment]
I agree

**Comment by qaisjp** [comment]
Also why would you want to reference a temporary element in a database? Once the resource or server restarts, MTA would end up assigning it a new ID.
