### ISSUE TITLE
Latest 1.5.8 Update Breaks Mipmapping Support

### ISSUE THREAD

**Issue by quiret** [multitheftauto/mtasa-blue#1774]
**Describe the bug**
After updating MTA:SA 1.5.8 today I immediatly noticed that all my GTA:SA textures look very grainy. I went to investigate further by comparing with an older MTA:SA build on my laptop. The problem does appear on both my computers so I can exclude a bug of my Graphics drivers. It does also not appear on 1.5.7.

**EDIT: I did previously saw that it did work on 1.5.8. But strangely enough I could not download a build from nightly.mtasa.com that did not have the bug! I have no idea but the one I first had prior to updating MTA:SA did not have the bug. What is going on?**

**How it is supposed to look**
![mipmapped_1 5 8_working](https://user-images.githubusercontent.com/7682485/97708867-b7cefe00-1ab9-11eb-834f-03df2747e558.png)

**How it is looking after the update**
![mipmapped_1 5 8_broken](https://user-images.githubusercontent.com/7682485/97708882-be5d7580-1ab9-11eb-8226-f6450c9d49f3.png)

This bug is hard to describe because images do come with filters already applied to them if you save them as PNG. So it might look as if some mipmapping is done but trust it me **it is not**.

In order to fully see the effect of missing mipmaps I advise you to turn the MTA:SA graphics settings to the lowest available option and to mipmap all of the GTA:SA textures using my [Magic.TXD](https://osdn.net/projects/magic-txd/) tool. To celebrate the occassion I have built a very special MTA:SA Beta edition of Magic.TXD just for the MTA:SA project. It has not been released before. Download it here:

[magictxd_x64_portable.zip](https://github.com/multitheftauto/mtasa-blue/files/5466062/magictxd_x64_portable.zip)

**To reproduce**
1. start MTA:SA 1.5.7 and set your graphics settings to the lowest possible BEFORE joining any game
2. join a freeroam MTA server and go to the docks area as depicted on the screenshots above
3. verify that the textures are blurry in the distance
4. now download + start the latest MTA:SA 1.5.8 build and go to the same area
5. you will notice that the loading time of the client was much longer and that the textures are very grainy. this is a sign that mipmapping is disabled.

**Expected behaviour**
Mipmapping is supposed to work. The mipmapped textures are inside of the TXD archives of GTA:SA. The filtering mode of textures should be set so that mipmapping is being done. TXD archives of GTA:SA should not be patched by MTA:SA. This is not a valid fix for the black roads bug because the data files of GTA:SA ship broken in the final game + mipmaps are a great performance optimization. Mipmapping should not be disabled by default because it is not intuitive.

**Screenshots**
See above.

**Version**
Working client version: 1.5.7.
Not working client version: 1.5.8 at time of writing

**Comment by Woovie** [comment]
Thank you for filing this issue. Can you provide the exact build on each device? Run `ver` in console.

**Comment by quiret** [comment]
Now I tried both Multi Theft Auto v1.5.8-release-20698 and 20672. Sorry but it appears that I was mistaken. No released version of 1.5.8 (between 20672 and 20698) does appear to support the client TXD mipmaps. I swear that it did work a week ago. Is this some kind of cheat prevention measure gone wrong?

Sorry for the delay. I had to download a RC from nightly.mtasa.com to find one where the bug did not exist. And I failed!

**Comment by Woovie** [comment]
I doubt it's AC, since 1.5.8 release we've begun pushing some PRs with actual changes and not just fixing/maintenance releases, so it's likely we may have broken something. Can you try the first 1.5.8 release from nightly and see if that is still affected?

**Comment by qaisjp** [comment]
Potentially related to #1776.

**Comment by quiret** [comment]
@Woovie Thank you for your understanding attitude for this issue. I am very passionate about all things MTA and want only the best for this multiplayer mod. I have just tested 20668 but the issue does also exist on it:

![grainy_20668](https://user-images.githubusercontent.com/7682485/97739657-6ede7000-1ae0-11eb-9b89-df0aa3c483b4.png)

I am really baffled. What is the root cause of this?

**Comment by Woovie** [comment]
Thanks for further testing. We will have to go through our changes and find what caused this. Thank you for reporting. We'll get back to this quickly I'm sure.

**Comment by quiret** [comment]
Not entirely sure what you guys have done but the bug has magically disappeared! And I did not even download another MTA:SA build. Thank you for fixing this issue! I hope it does not reappear. Quite some people did see the effects of this issue. Somebody even reported 100% SSD disk usage (me included, actually. very very laggy game).

**Comment by qaisjp** [comment]
Definitely linked to https://github.com/multitheftauto/mtasa-blue/issues/1776#issuecomment-719721851 then.

Please close if you're happy
