### ISSUE TITLE
Problems with the modified gta3.img

### ISSUE THREAD

**Issue by ZbyK77** [multitheftauto/mtasa-blue#1776]
**Describe the bug**

Today players started reporting problems with the MTA when they have modified gta3.img. Some people can't see their substitutions, and while playing, they may disconnect with the reason "File error reading gta3.img". Others cannot join any server, the game stops responding while downloading resources... However, if you manage to enter, the game is impossible because it stutters severely when loading the map

I have uploaded a replacement for one vehicle, it doesnt work on any MTA server, even on a local server. (in gta:sa works)
The player sent me his gta3.img file with more replacements, here is a video of entering the local server:
https://www.youtube.com/watch?v=2zl5EY5cdKg

**To reproduce**

a)
1. Replace any vehicle (there may be a road, etc.)
2. Create a local server and create a replaced vehicle,

b)
1. Download gta3.img that I got from the player (https://drive.google.com/file/d/110aPqjYNWLCxRBITJCyD2MXkPH67jgrw/view)
2. Upload the file to "Rockstar Games\Grand Theft Auto San Andreas\models\gta3.img"
3. Attempt to enter any server

**Expected behaviour**

The omission should be displayed and entering the server should be trouble-free.

**Screenshots**
Examples of errors submitted by players
![tstkkSR](https://user-images.githubusercontent.com/65454704/97730368-0f7a6300-1ad4-11eb-8f89-01ca820b29c4.png)
![gr8dY08 (1)](https://user-images.githubusercontent.com/65454704/97730375-11442680-1ad4-11eb-9be0-71b5a78c6763.png)

**Version**
client
Multi Theft Auto v1.5.8-release-20698
Copyright (C) 2003 - 2020 Multi Theft Auto

**Additional context**
--

**Comment by TheNormalnij** [comment]
20669 - gta started, but sometimes gta freezes

**Comment by PlatinMTA** [comment]
I have a good chunk of users with this problem too. Gonna see if I can ask some of them to help us find which version broke this thing.

**Comment by ccw808** [comment]
Might have been an issue at MTAHQ
Try now to see if it's fixed

**Comment by quiret** [comment]
MTAHQ... what a terrible beast ;)

**Comment by ZbyK77** [comment]
Everything works as it should. Thank you.
