### ISSUE TITLE
Make lua files can be loaded as a module

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1780]
**Is your feature request related to a problem? Please describe.**
idea is simple, if you can load c/c++ code into server, why not lua as well? If you want to add some function you sometimes don't need c/c++ for it.

**Describe the solution you'd like**
make "loadmodule" accept .lua files
With it, you can recreate ml_system module in lua with literraly 4 lines of code:
```lua
local execute = os.execute;
function system(command)
  return execute(command)
end
```
It makes every resource can use `system` function while still os.execute prints "unsafe function was called"

Inside module you would be able to use extra set of functions, including dangerous ones.
it will make people can very easy write any module they want ( pretty useful )
example "onElementCreated" - you can overwrite every `create` function and manually call event.

**Describe alternatives you've considered**
/

**Additional context**

demo:
https://github.com/multitheftauto/mtasa-blue/compare/master...CrosRoad95:luamodule-lua?expand=1

[module example.zip](https://github.com/multitheftauto/mtasa-blue/files/5468938/module.example.zip)

foo.lua put into `server\mods\deathmatch\modules` folder and add `<module src="foo.lua"/>` to server config or type `loadmodule foo` command

**Comment by CrosRoad95** [comment]
i think it would be even better, if instead of changing mta code, just default module can be added to mta by default enabled which adds that functionality

**Comment by AlexTMjugador** [comment]
Isn't this issue already covered by #680, or are you thinking in another way to implement this enhancement that will be forwards compatible with that PR?

**Comment by Allerek** [comment]
He means, that instead of .so and .dll files as modules, we should allow Lua files, so that we can add global functions to avoid exporting etc.
