### ISSUE TITLE
ways to disallow custom hud.txd  , particle.txd and custom effects files in Models Folder

### ISSUE THREAD

**Issue by mtasa02020** [multitheftauto/mtasa-blue#1793]
hi

i want ways to disallow custom hud.txd  , particle.txd and custom effects in Models Folder

because custom of hud.txd  , particle.txd and custom effects.fxp , effectsPC.txd , fronten_pc.txd , misc.txd , fronten1.txd , fronten2.txd , fronten3.txd in GTA SA Models folder

can be used for unfair advantages

so i want way to disallow custom them

example : enable SD # 40 To disallow custom hud.txd  , particle.txd and disallow custom effects.fxp , effectsPC.txd , fronten_pc.txd , misc.txd , fronten1.txd , fronten2.txd , fronten3.txd in GTA SA Models folder  

if this wrong section , please don't Close my Issue , i'm newbie

**Comment by Lpsd** [comment]
You can use the `onPlayerModInfo` event for this.

https://wiki.multitheftauto.com/wiki/OnPlayerModInfo

**Comment by mtasa02020** [comment]
no i can't



onPlayerModInfo event for gta3.img and gta_int.img (only) !!!!!!!



please open my issue

**Comment by mtasa02020** [comment]
> You can use the `onPlayerModInfo` event for this.
> 
> https://wiki.multitheftauto.com/wiki/OnPlayerModInfo



no i can't

onPlayerModInfo event for gta3.img and gta_int.img only !!!!!!!

please open my issue
