### ISSUE TITLE
getElementBoneMatrix returns an userdata value instead of a matrix table

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#1805]
**Is your feature request related to a problem? Please describe.**
Currently getElementBoneMatrix returns an userdata value that i cannot access except with ultra-slow matrix vector functions.
All other matrices returned by getElementMatrix() are simple tables. All functions can use the tables without problems, so i see no reason for the current userdata solution.

**Describe the solution you'd like**
Return a table instead of the userdata value.

**Comment by Pirulax** [comment]
Let's add an argument then `bTableReturn`

**Comment by Einheit-101** [comment]
Maybe Saml1er has a reason why it is an userdata value, but i see absolutely no benefit from it, only problems

**Comment by LosFaul** [comment]
i agree with Einheit
in non oop mode: <oop>false</oop>
it should return a table instead of userdata
