### ISSUE TITLE
fetchRemote does not support formFields arrays

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1807]
**Describe the bug**
```lua
local sendOptions = {
    method = "POST",
    formFields = {
        a = {1,2,3}, // empty
        b = "123", // ok
        c = 123, // ok
        d = {{1,2,3},{3,2,1}} // empty
    },
}

fetchRemote( "https://webhook.site/3ac86286-0483-411c-b979-494da96ba55e", sendOptions, function()end )
```
`a`, and `d` are always empty

**To reproduce**
as above

**Expected behaviour**
only `d` should be empty

**Screenshots**
/

**Version**
newstest

**Additional context**
i used webhook.site to test it

**Comment by ImSkully** [comment]
Bumping for visibility, this is still an issue.

@CrosRoad95 Did you ever find an alternative solution for this?
