### ISSUE TITLE
Inaccurate setCameraTarget

### ISSUE THREAD

**Issue by Xyrusek** [multitheftauto/mtasa-blue#1823]
**Describe the bug**
Crosshair never sets there, where should be.

**To reproduce**
1. Upload script.rar to resources.
2. Type 'refresh' in console.
3. When resource 'script' load, start script.
4. Get some weapon(maybe from admin panel)
5. Shoot
[script.zip](https://github.com/multitheftauto/mtasa-blue/files/5524800/script.zip)

**Expected behaviour**
I want to set crosshair position, to position of seconds ped.

**Screenshots**
![image](https://user-images.githubusercontent.com/35786599/98827101-bf39c400-2436-11eb-90fc-1a63c9ea5cd9.png)

**Version**
Client: v1.5.8-release-20698.2
Server: 1.5.8
Platform: Windows 10

**Additional context**
---

**Comment by Lpsd** [comment]
You don't use `setPedAimTarget` anywhere in your example resource. Please provide a valid resource for testing.

**Comment by Einheit-101** [comment]
setPedAimTarget doesnt even work on local player, or did i miss something?

**Comment by Xyrusek** [comment]
> You don't use `setPedAimTarget` anywhere in your example resource. Please provide a valid resource for testing.

I got wrong function name in title, resource was correct.

**Comment by TheNormalnij** [comment]
GTA doesn't uses screen center for crosshair
