### ISSUE TITLE
Client-side: changing a 4 doors vehicle model to a 2 doors model while being a passenger in 3rd or 4th seats will get you a network trouble

### ISSUE THREAD

**Issue by Shuubaru** [multitheftauto/mtasa-blue#1833]
**Describe the bug**
If you enter as a passenger (3rd or 4th seats) in a 4 door vehicle, and then change the model to a 2 door vehicle you will get a network trouble. Changing it back to a 4 door model wont fix it (server or client side), so you will have to reconnect.

**To reproduce**

Steps to reproduce:
1. create a 4 door vehicle `/cv sentinel`
2. enter as a passenger using 3rd or 4th door
3. change model to 2 door vehicle, like an infernus: `crun setElementModel(getCameraTarget(), 411)`
4. you will get frozen with network trouble, forced to reconnect.

**Expected behaviour**
You should be kicked out of the car, and this behavior be synced to avoid any sync problem, which server side setElementModel already does.

**Screenshots**

In this video I show I could reproduce it after using custom models from engineRequestModel function, but this can also be reproduced with default ids, as I explained before:

[https://streamable.com/v889k4](url)

**Version**
Multi Theft Auto v1.5.8-release-20723
both server and client.

**Additional context**
Since custom ids are already a thing in MTA, and they can only be used with client sided setElementModel, I believe this can be (probably) a problem in the future.

**Comment by Pirulax** [comment]
Interesting. 
~~It wasn't a problem when `engineReplaceModel` warped you out of the vehicle.~~
My bad. This was done using `setElementModel`.
Edit: This is kinda unsolvable, as this is done client side. And while the server think's youre in a vehicle, your client disagrees, because you've changed the model. The way to fix this it to not set the model on the client side, but on the server.

**Comment by Allerek** [comment]
> Interesting.
> ~It wasn't a problem when `engineReplaceModel` warped you out of the vehicle.~
> My bad. This was done using `setElementModel`.
> Edit: This is kinda unsolvable, as this is done client side. And while the server think's youre in a vehicle, your client disagrees, because you've changed the model. The way to fix this it to not set the model on the client side, but on the server.

We can check for amounts of doors before replacing model, then if your seat is higher than amount of doors you should be kicked from vehicle with triggering the proper event.

**Comment by Pirulax** [comment]
I remember fixing this issue, but didn't commit it for whatever reason..
Until then, wrap them out of the vehicle yourself.

**Comment by Fernando-A-Rocha** [comment]
Issue can be closed AFAIK
