### ISSUE TITLE
Replace quick connect button

### ISSUE THREAD

**Issue by XeNikk** [multitheftauto/mtasa-blue#1834]
**Is your feature request related to a problem? Please describe.**
The quick connect button doing the same as server browser.

**Describe the solution you'd like**
It should be replaced with last server or name of last server which you connected.

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by PlatinMTA** [comment]
pretty sure that we already had a request like this before, but i can't find it

eitherway, the quick connect from 1.0.4 made more sense that the actual one, so we should really change it or delete it enterily

**Comment by Lpsd** [comment]
See #1306
