### ISSUE TITLE
setObjectScale doesn't work in the onClientPedsProcessed event

### ISSUE THREAD

**Issue by Vadya963** [multitheftauto/mtasa-blue#1836]
**Describe the bug**
if we create an object on the server or client and reduce it, the object will be the standard size in the event. 

**To reproduce**
run the code
```lua
addEventHandler ( "onClientPedsProcessed", root,
    function ( )
        local obj = getElementData( localPlayer, "obj" )
        if obj then
            local x,y,z = getElementPosition(localPlayer)
            setElementPosition( obj, x,y,z+1 )
            setObjectScale( obj, 0.5 )
        end
    end
)
addEventHandler( "onClientResourceStart", resourceRoot,
function ( startedRes )
    local obj = createObject( 1946, 0,0,0 )
    setElementData( localPlayer, "obj", obj)
end)
```

**Expected behaviour**
the object should shrink

**Screenshots**
onClientRender
https://imgur.com/YKvy302
onClientPedsProcessed
https://imgur.com/SCGjniT

**Version**
1.5.8-20724

**Additional context**
I think the object should decrease, since the event was made so that there was no lag. I mean, if it is used in the bone_attach resource, it will be of no use
https://www.youtube.com/watch?v=U95ls5931lE

**Comment by PlatinMTA** [comment]
I can confirm this issue
