### ISSUE TITLE
Make getVehicleWheelFrictionState return an enum string

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1845]
**Describe the solution you'd like**

#1839 should return a enum string instead of a number

**Comment by Pirulax** [comment]
IMHO the author of the PR should've done this, instead of someone else, but whatever.

**Comment by LosFaul** [comment]
i think numbers are fine and it would also be a bit inconsistent using strings now because of existing functions:
https://wiki.multitheftauto.com/wiki/GetVehicleWheelStates

**Comment by Pirulax** [comment]
Oh well, you're right.

**Comment by qaisjp** [comment]
Okay, since a lot of vehicle state thingies use numbers, let's not do this.
