### ISSUE TITLE
Newest nightly extremely unstable

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#1862]
**Describe the bug**
Crash on reconnect or even just moving around the map on newest nightly, the fix for crash on reconnect didn't fix it.

**To reproduce**
Join s2.cit.gg and login then reconnect or even just moving around and get crash.
If it doesn't crash then try again try changing your skin '/vipskin' maybe one like 10xx (so engineRequestModel gets called) 

**Expected behaviour**
Not crashing.

**Screenshots**
I warped some where busy:

Version = 1.5.8-release-20732.0.000
Time = Sun Nov 22 19:12:50 2020
Module = C:\Program Files (x86)\Rockstar Games\GTA San Andreas\proxy_sa.exe
Code = 0xC0000005
Offset = 0x0116D0D1

EAX=FFFFFFFF  EBX=00000000  ECX=009625E4  EDX=00015202  ESI=00000186
EDI=00000000  EBP=0177F918  ESP=0177F8F8  EIP=0156D0D1  FLG=00010293
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

Instantly crashed when I logged in:

Version = 1.5.8-release-20732.0.000
Time = Sun Nov 22 19:17:43 2020
Module = C:\Program Files (x86)\Rockstar Games\GTA San Andreas\proxy_sa.exe
Code = 0xC0000005
Offset = 0x001A49D4

EAX=00000000  EBX=0177F22C  ECX=448FAF74  EDX=00000000  ESI=00000000
EDI=2B63EE68  EBP=00000000  ESP=0177F0C0  EIP=005A49D4  FLG=00210246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

Crashed after 30 seconds:

Version = 1.5.8-release-20732.0.000
Time = Sun Nov 22 19:19:38 2020
Module = C:\Program Files (x86)\Rockstar Games\GTA San Andreas\proxy_sa.exe
Code = 0xC0000005
Offset = 0x001A49D4

EAX=00000000  EBX=0177F504  ECX=43CDF80C  EDX=00000000  ESI=00000000
EDI=44610A00  EBP=00000000  ESP=0177F394  EIP=005A49D4  FLG=00210246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

**Version**
1.5.8-release-20732.0.000

**Additional context**

**Comment by TheNormalnij** [comment]
Can't repro in r20734

**Comment by ArranTuna** [comment]
Yes is stable now.
