### ISSUE TITLE
AMD Memory Tweak getting detected as a cheat

### ISSUE THREAD

**Issue by colistro123** [multitheftauto/mtasa-blue#1871]
Hello, I'm using a third party tool to lower my GPU's memory clock and your application is detecting it as a cheat.
I basically can't run my RX 580 without downclocking it to 1500 mhz with third party tools, since it has micron memory chips and most of them are faulty and the warranty won't cover (way past it). If I don't down clock I get hard system hangs at the default 2000 mhz clock and have to restart the machine. The third party software I'm using to downclock the card is open source.
https://github.com/Eliovp/amdmemorytweak/blob/master/win/WinAMDTweak.cpp

![image](https://user-images.githubusercontent.com/923242/100120825-4db73800-2e70-11eb-8c30-ea629345fd02.png)
![image](https://user-images.githubusercontent.com/923242/100120844-527bec00-2e70-11eb-8996-e48f935c03ad.png)

Assuming this is detecting stuff loaded on memory perhaps I could close the tool once I'm done changing the memory clock, which is  something I haven't tried.

**Comment by Allerek** [comment]
This should be blocked as it writes data directly into memory.

**Comment by colistro123** [comment]
> 
> 
> This should be blocked as it writes data directly into memory.

Only to the GPU address space. While it's true that one can easily inject modules by patching vendor dlls and writing assembly code in them, this is not the case here. Anyhow, I'll probably just close this report anyway, since I noticed MTA is just checking for applications running in the background, so I can simply downclock the card and close the application. No big deal, I just prefer to leave it running since the drivers may randomly change the clock and then I get an unexpected crash, which has happened before.

**Comment by qaisjp** [comment]
> Assuming this is detecting stuff loaded on memory perhaps I could close the tool once I'm done changing the memory clock, which is something I haven't tried.

Your screenshot says `AC #4 AMD Memory Tweak (close)`, so please try closing the application to see if that fixes the problem.

**Comment by colistro123** [comment]
Closing the tool solves the issue as expected. 🎉

**Comment by Dutchman101** [comment]
There is a valid reason why this tool should be blocked from running while MTA is active - we just can't explain, for security reasons

**Comment by avail** [comment]
lol
