### ISSUE TITLE
Some Wiki functions arent highlighted properly.(Users cant change this)

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1872]
**Is your feature request related to a problem? Please describe.**
Some functions on wiki arent highlighted properly in examples.

**Describe the solution you'd like**
Post in comments more non-highlighted functions.
engineRequestModel 
![image](https://user-images.githubusercontent.com/12304071/100161732-4dd82780-2eb2-11eb-9a00-5a456cd4a60e.png)
engineFreeModel
![image](https://user-images.githubusercontent.com/12304071/100161776-69dbc900-2eb2-11eb-80a0-345bf8a79624.png)
createExplosion
![image](https://user-images.githubusercontent.com/12304071/100161847-87109780-2eb2-11eb-9d0e-01511f576044.png)
extinguishFire/createFire

**Comment by MegadreamsBE** [comment]
Don't think that issues with the wiki belong here though?

**Comment by Pirulax** [comment]
I think this is an okay place for Wiki issues, as there isn't any other way(is there?).

@Dutchman101 is the wiki expert afaik.

**Comment by qaisjp** [comment]
Correct location: https://forum.mtasa.com/forum/11-siteforumdiscordmantiswiki-related/
