### ISSUE TITLE
Cef, webassembly, unable to use .dll files

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1874]
**Describe the bug**
Mta just don't let client download .dll files

**To reproduce**
download resource:  [mtablazor.zip](https://github.com/multitheftauto/mtasa-blue/files/5599090/mtablazor.zip)
start it, you will notice all .dll fail to download
copy all of them from server to client and restart resource - gui starts to work ( just style is broken )

**Expected behaviour**
Dll's should be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/100276484-eaa5ce00-2f61-11eb-8175-e926902eb2cd.png)
![image](https://user-images.githubusercontent.com/22455534/100277834-217ce380-2f64-11eb-8b42-331424d7c0be.png)

After i manually copied dll's, it working
![image](https://user-images.githubusercontent.com/22455534/100277472-7d933800-2f63-11eb-8543-ea578c5221c0.png)

**Version**
current

**Additional context**
version you can put into your eg. xampp htdocs folder and it working perfectly
[htdocs.zip](https://github.com/multitheftauto/mtasa-blue/files/5599060/htdocs.zip)

**Comment by qaisjp** [comment]
Nice...ish find

**Comment by Lpsd** [comment]
Are there any security implications here?

**Comment by qaisjp** [comment]
1. Practically, not for CEF.
2. I'm not 100% sure what the reasons are for blocking downloads of a particular extension, assuming that's what is happening here. You could just download a `.txt` and then `fileRename` to a `.dll` would probably work.

**Comment by ccw808** [comment]
>     2\. You could just download a `.txt` and then `fileRename` to a `.dll` would probably work.

Renaming won't work. Downloading PE files is currently blocked

**Comment by CrosRoad95** [comment]
allowing .dll let everyone literraly use any nuget packet written in c#, clientside in cef. Example i yesterday show that it is possible to run higher version of lua inside cef using https://github.com/neolithos/neolua

**Comment by ccw808** [comment]
Is it 100% safe to execute arbitrary x86 code inside CEF?

**Comment by qaisjp** [comment]
Yes. https://webassembly.org/docs/security/

~~as long as CEF is up to date. I guess we could delay this until after we implement a CEF updater that isn't bound to MTA updates~~ This is not x86, this is wasm.

**Comment by qaisjp** [comment]
as long as CEF is up to date. I guess we could delay this until after we implement a CEF updater that isn't bound to MTA updates

**Comment by qaisjp** [comment]
Although, more accurately, this is not x86

**Comment by MegadreamsBE** [comment]
I wonder, would you be able to bypass this by scrambling up the bytes. sending the file and then reversing the scrambling process? That and renaming the file.

**Comment by ccw808** [comment]
MTA will not save PE files
Maybe it's possible to change the PE header but still have CEF load them?

**Comment by CrosRoad95** [comment]
i don't want to make workaround for it, i just want to make mta download it as any other model, texture or music file

**Comment by MegadreamsBE** [comment]
> MTA will not save PE files

Ah, smart.

**Comment by ERAGON007** [comment]
bump

Maybe this can be fixed in 1.6 stable release?
