### ISSUE TITLE
The creation of new models of cars through the game files

### ISSUE THREAD

**Issue by lexa-makeev** [multitheftauto/mtasa-blue#1876]
Greetings to the developers of MTA! I would like to ask you, here you have made the engineRequestModel function for creating new car models, would you like to make it possible to implement new cars directly through the vehicle. ide and actually upload to img, and not upload models to the server, because this is not very convenient.

**Comment by qaisjp** [comment]
Please use the issue template, otherwise use [the forum](https://forum.mtasa.com/forum/81-suggestions/). Thanks.
