### ISSUE TITLE
isElementWithinPickup(hardcoded)

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#1878]
**Is your feature request related to a problem? Please describe.**
Yes, as now we have to do it based on a colshape or https://wiki.multitheftauto.com/wiki/IsElementWithinPickup

**Describe the solution you'd like**
Make it a hardcoded function

**Describe alternatives you've considered**
There are soma alternatives as i described in first point

**Comment by Pirulax** [comment]
I think the solution mentioned on the wiki is perfectly fine:
```lua
isElementWithinColShape(getElementColShape(pickup))
```
