### ISSUE TITLE
Bikes rotation seems to go to the thousands when streamed in and it tries to correct it

### ISSUE THREAD

**Issue by redeibarnabas** [multitheftauto/mtasa-blue#1879]
https://streamable.com/f6xmky

Reproduction:
Spawn a bike
or
Spawn a bike, go far enough so it will stream out, and go back to it.

Sometimes it even becomes invisible for some time.

Client and Server version: v1.5.8-release-20737

**Comment by MegadreamsBE** [comment]
Also can happen if you switch your current vehicle to be a bike. It's just a visual glitch though it seems.

EDIT: Video given to me by Unix/Nathan: https://streamable.com/zsm0mt
