### ISSUE TITLE
Setting water level outside world is not working on server side

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#1881]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6568348/100518391-85d0ba80-3191-11eb-9f87-e2c863cfc85f.png)
Setting water level outside world is not working on server side.

**To reproduce**
setWaterLevel(-5, true, true, true, true) works on client side but not works on server side

**Version**
Multi Theft Auto v1.5.8-release-20732

**Comment by TheNormalnij** [comment]
Update your server
