### ISSUE TITLE
Support modified handling with new vehicle model IDs

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#1898]
**Is your feature request related to a problem? Please describe.**
If a new vehicle model ID is added with engineRequestModel you must create that vehicle with a normal vehicle ID server side and set it on each client to the new ID. But the problem is that changing a vehicle model causes it's handling to be reset. Therefore it's impossible to have synced modified handling because each client is changing the model ID at a different time.

**Describe the solution you'd like**
For whatever you have set with setVehicleHandling to carry over to the new vehicle ID when you change it client side.

**Describe alternatives you've considered**
- Calling setVehicleHandling every time a new client changes the ID is obviously infeasible on any busy server since that is data that gets sent out to all clients.
- There is no setVehicleHandling client side either.

**Additional context**
You'll need a new nightly that has engineRequestModel("vehicle") support.

**Comment by Pirulax** [comment]
Closing in favor of #1835 

It deals with this issue, since it'll allow the model to be allocated server side (thus no hackery needed to use the model client side)

**Comment by Fernando-A-Rocha** [comment]
Multi Theft Auto v1.5.9-release-21022

Still broken in this version, after @BCG2000 's awesome PRs that got merged which make added vehicles work.

Issue should be re-opened, this is quite critical as added vehicles can't have custom handling (it gets reset everytime setElementModel is called clientside on the serverside vehicle acting as the add-on).
