### ISSUE TITLE
There was a problem validating your serial.

### ISSUE THREAD

**Issue by kecsmar** [multitheftauto/mtasa-blue#1906]
I am using a Linux Mint **(not VM)** and this message keeps saying that MTA can't validate my serial.
I followed the instructions, but it's still not working.

![The window](https://user-images.githubusercontent.com/75141177/101285826-9ca58b80-37e7-11eb-805f-ddcca48ff32b.png)

**Comment by Dutchman101** [comment]
Please create a topic in the [client support board](https://forum.mtasa.com/forum/83-client/)

**Comment by qaisjp** [comment]
([Existing topic link](https://forum.mtasa.com/topic/128435-there-was-a-problem-validating-your-serial/))
