### ISSUE TITLE
Flare Support

### ISSUE THREAD

**Issue by hasanyilmaz4006** [multitheftauto/mtasa-blue#1927]
**Is your feature request related to a problem? Please describe.**
Our team wants to make Aviation CLEO mods to MTA:SA we made afterburner, hud and others... But we cant make multi-flare script because createProjectile not working with flares.

**Describe the solution you'd like**
Adding flare support to  createProjectile

**Comment by Unde-R** [comment]
Do you mean the flare from the hydra?

**Comment by Allerek** [comment]
You can create custom object with 2DFX effect on it.

Also i belive https://wiki.multitheftauto.com/wiki/CreateEffect have this effect
