### ISSUE TITLE
Frozen peds rotation is bugged.

### ISSUE THREAD

**Issue by redeibarnabas** [multitheftauto/mtasa-blue#1928]
**Describe the bug**
Creating a ped and then freezing it will mess with it's rotation. Set the peds rotation to 90, freeze it and the peds rotation will be 270.

Edit:
It's not 180, it's random, but still consistent. Like the same ped in the same position will always be rotated to one rotation, but give a different ped a different rotation and it's different.

**To reproduce**
Spawn a ped, set the rotation and freeze it.

**Version**
Multi Theft Auto v1.5.8-release-20761
MTA:SA Server v1.5.8-release-20737

**Comment by DREFTHUN** [comment]
Edit:
It's not 180, it's random, but still consistent. Like the same ped in the same position will always be rotated to one rotation, but give a different ped a different rotation and it's different.

**Comment by Pirulax** [comment]
Please correct your post then.

**Comment by ArranTuna** [comment]
You have the server config setting latency_reduction on?

**Comment by redeibarnabas** [comment]
I can't check right now, but I looked it up and that's probably what causes a lot of my problems. Will check in the morning and manage the issue accordingly.

**Comment by redeibarnabas** [comment]
That was the problem. Issue is irrelevant, can be closed.

**Comment by ArranTuna** [comment]
I'm 99% sure that this latency reduction bug is reported so will close it.

**Comment by tederis** [comment]
In the past, I have already faced with a similar bug. In case we are talking about the same bug, the reason was the matrix resetting when ped's sync packet arrived. This can be fixed.

**Comment by dmi7ry** [comment]
In addition to the Tederis' comment. It may be fixed with just a delay before set the element's rotation and freezing it. But sometimes it just won't work even with a big delay (like 5-10 seconds).
