### ISSUE TITLE
Kicked by VF #6 B09-Z01

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#1934]
**Describe the bug**
Spawn in a position outside the map results in a kick. For example x * 6000, y * 6000

**To reproduce**
x * 6000, y * 6000

**Expected behaviour**

**Screenshots**

**Version**
MTA 1.5.8

**Additional context**
I'm not sure this is a bug

**Comment by patrikjuvonen** [comment]
@ccw808

Also found a forum thread about the same code from 2015: https://forum.mtasa.com/topic/75836-kicked-by-vf-6-b09-z01/

**Comment by patrikjuvonen** [comment]
Unable to reproduce.
