### ISSUE TITLE
Ped task bug when fighting near to a vehicle (nightly)

### ISSUE THREAD

**Issue by jayceon123** [multitheftauto/mtasa-blue#1942]
**Describe the bug**
When fighting near to a vehicle with the special fighting (RMB+F), the player trying to enter the vehicle.

**To reproduce**
1. Spawn a vehicle near to you (or find one)
2. Start fighting with RMB+F combo
3. The player starts sliding fast to the vehicle

**Expected behaviour**
Normal behavior as before

**Version**
All nightly version affected after **r20739**

**Comment by Zangomangu** [comment]
Thanks for reporting this, I'll submit a fix for this tomorrow.

**Comment by Pirulax** [comment]
In theory its introduced by 94c6aba
