### ISSUE TITLE
Player entering vehicle instead of fighting in some circumstances

### ISSUE THREAD

**Issue by ccw808** [multitheftauto/mtasa-blue#1949]
Below is copied from forum post https://forum.mtasa.com/topic/128737-hitting-problem/

**Describe the bug**
Some servers have their own fighting system which support GTA fighting styles. The player fights by holding mouse button 2 and pressing F, but since the last MTA update something broke and by hitting this way the character gets into the car, which he didn't do before. 

**To reproduce**
1. Enter server with own fighting system
2. Hold mouse button 2 and press F
3. Player will enter nearby vehicle

**Expected behaviour**
Player to do hitting action and not enter vehicle

**Version**
Problem appears in 20762 but not in 20698

**Comment by Zangomangu** [comment]
This is fixed in latest nightly see https://github.com/multitheftauto/mtasa-blue/commit/7439bf7180598618d2a832fd0748fd2e1d1b45a1

**Comment by ccw808** [comment]
Duplicate of #1942
