### ISSUE TITLE
Multithreaded resources

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1954]
**Is your feature request related to a problem? Please describe.**
Unable to squeeze more power from servers cpu

**Describe the solution you'd like**
Add multithreading.
I made example, demo of my approach simillar to sockets.
You just send data to multithreaded running resource, and resource uses special function, to get last argument you sent.

To prevent race conditions and other problem with thread, function need to have enabled "thread safe" functionality and only that functions are availiable. By default all functions are disabled.

MT resource should not let you modify any element on the server, but might be helpful with database connections, file handling, sending triggers to other resources, to client and in general process data - path finding, images/models processing

I'm focusing this feature to advanced users only. I can't use "addEventHandler" in MT resource because it will cause blocking on main thread

**Describe alternatives you've considered**
/

**Additional context**
in my demo branch, add `<multithreading>true</multithreading>` to resource that are you going to run in background
https://github.com/multitheftauto/mtasa-blue/compare/master...CrosRoad95:multithreading-test?expand=1

![image](https://user-images.githubusercontent.com/22455534/103281000-03c2f400-49d2-11eb-8a0c-97faf693741f.png)

If it get approved, i'll continue working on it.

**Comment by botder** [comment]
I would rather name these **daemon resources** (running in background). The whole scripting integration is absolutely designed for single-thread usage, this isn't going to be easy.

Which functionality is going to be included/enabled in these resources?
Is it going to be server only or are you going to support clients too?

**Comment by CrosRoad95** [comment]
> Which functionality is going to be included/enabled in these resources?

functions responsible for: Database, file, xml, utility, triggerEvent, triggerClientEvent and maybe other functions as well

> Is it going to be server only or are you going to support clients too?

in initial pr only serverside who suffer the most due lack of cpu time

**Comment by CrosRoad95** [comment]
anyone have suggestion about names of functions?
it need function to read data sent to this resource, and some variant of "call" function especially for "daemon resources"

**Comment by MegadreamsBE** [comment]
Personally I'd prefer to see #918 implemented instead as it has a lot more flexibility to it.

**Comment by Pirulax** [comment]
You don't necessarily need multithreading. Lua already supports cooperative multitasking with coroutines, which, if used correctly, can be really good.

**Comment by MegadreamsBE** [comment]
> You don't necessarily need multithreading. Lua already supports cooperative multitasking with coroutines, which, if used correctly, can be really good.

Certain projects, like Sphene the SCM Interpreter, can benefit heavily from having multithreading so it would still be very useful to have it. We already make extensive use of coroutines but all that ends up doing for us is allow us to process other things in-between while generally slowing down everything else in return.

**Comment by CrosRoad95** [comment]
>You don't necessarily need multithreading.

some things like reading and processing files, path finding ect. will always cause high cpu usage spike no matter if you use coroutines or not.

@botder should i make in in way described in #918 ?

**Comment by LosFaul** [comment]
> 
> 
> You don't necessarily need multithreading. Lua already supports cooperative multitasking with coroutines, which, if used correctly, can be really good.

coroutines are no real multithreading (they are still single threaded)
and there we would be again at our start point everything runs still on one cpu thread
but we want to use more than one cpu thread

**Comment by gta191977649** [comment]
> > You don't necessarily need multithreading. Lua already supports cooperative multitasking with coroutines, which, if used correctly, can be really good.
> 
> coroutines are no real multithreading (they are still single threaded)
> and there we would be again at our start point everything runs still on one cpu thread
> but we want to use more than one cpu thread

coroutines are good, but not an optimal solution especially for the tasks that are requiring demanding computational power. e.g. NPCs. 
The main downside is its theory still running in the same threads as the normal Lua code does, thus it still can blockage the rendering pipe (Drop FPS) when comes in large computation.
However, you can use it to avoiding long execution error if you don't want your script being killed by the MTA.
So yeah, the real multithreading would definitely benefit the old San Andreas engine a lot and create more possibilities for the scripters, especially the ones that involve a large number of NPCs.  It will be a lifesaver for us who are trying to optimize these tasks.
