### ISSUE TITLE
Hidden variables

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1957]
**Is your feature request related to a problem? Please describe.**
they are just stupid

**Describe the solution you'd like**
add function "getContext()" or "getCurrentContext()" which return table of hidden variables in current context. In future add them only to this function, not as hidden variable

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by botder** [comment]
Unfortunately, this is not a good solution and we would still have to support the old approach with overwritten global variables to avoid breaking backwards compatibility with existing scripts.
