### ISSUE TITLE
Linux armhf/aarch64 Server

### ISSUE THREAD

**Issue by Disinterpreter** [multitheftauto/mtasa-blue#1961]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Executable server for armhf devices (rpi, pine64, thousand brands chinese microcomputers, smarphones?) and other ARM devices.

**Describe alternatives you've considered**
https://github.com/ptitSeb/box86 

**Additional context**
Many companies will start new "challenge" for dominating ARMHF devices and I think we can be ready for new aarm64 servers in future.

How to test at your computer: https://gist.github.com/rnagarajanmca/c8d1a086d3b0546575be0811b9a863c3

For compilling from amd64: https://packages.debian.org/unstable/gcc-aarch64-linux-gnu

This issue with low priority, for a backlog label.

**Comment by botder** [comment]
Added after 8c5643e1b28768caf87d390d8c969a3b2f3497e1
