### ISSUE TITLE
Disable logIn function by default

### ISSUE THREAD

**Issue by xLive** [multitheftauto/mtasa-blue#1965]
**Is your feature request related to a problem? 
Please describe.**
After https://github.com/multitheftauto/mtasa-blue/commit/8178743d1fc6bcd2b4adbc5b0dbef372dd84a32a malicious scripts can use `logIn` function to log in to any admin account and do whatever they want

**Describe the solution you'd like**
`logIn` function should be by default restricted to admin or super moderator ACL

**Describe alternatives you've considered**
Do nothing

**Comment by Citizen01** [comment]
can you give a real use case ?
I was thinking about members of a server who can submit maps as resources but then it's the responsabilty of the server owner to not give such permissions to those kind of "outsider" resources.

**Comment by ccw808** [comment]
The `logIn` function requires a password. How can malicious scripts get round that?

**Comment by StrixG** [comment]
> The `logIn` function requires a password. How can malicious scripts get round that?

It doesn't require a password after https://github.com/multitheftauto/mtasa-blue/commit/8178743d1fc6bcd2b4adbc5b0dbef372dd84a32a.
I'm sorry. I didn't think about malicious use of this feature.
We could make ACL right that allows to skip password argument and enable it only for *SuperModerator*, *Admin* ACL groups.

**Comment by patrikjuvonen** [comment]
Seems that PR clearly made a mistake in judgement when approving and merging.

The whole PR took a day to get merged. Should wait longer in the future.

**Comment by patrikjuvonen** [comment]
I think that commit should be reverted and a fix be implemented ASAP.

Edit: I have opened a new PR that reverts the login behavior changes at #1966.

**Comment by xLive** [comment]
> can you give a real use case ?
> I was thinking about members of a server who can submit maps as resources but then it's the responsabilty of the server owner to not give such permissions to those kind of "outsider" resources.

Most people are stupid enough to use those "outsider" resources
this is why functions like `setAccountPassword` is disabled by default right?

**Comment by Pirulax** [comment]
Well, disabling it might break backwards compatibility. As stated above, we should only restrict it's use without a password.

**Comment by patrikjuvonen** [comment]
Fixed by #1966

Please open a new PR/issue about reinstating the now reverted changes to get them re-evaluated into MTA.
