### ISSUE TITLE
New parser, return `std::vector<std::tuple<...>>` issue

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1973]
**Describe the bug**
"attempt to index a number value" error gets thrown when trying to use function 

**To reproduce**
make for example std::vector<std::tuple<float, float, floatt>> as a return type, it will compile but will throw errors as above.

**Expected behaviour**
It should just return a table like `{ {1,2,3}, {1,2,3}, ... }`

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/103457962-c4fba980-4d03-11eb-8309-346c65d0d786.png)

**Version**
@CrosRoad95 please add this

**Additional context**
Possible solutions:
1. Make special case, when tuple is in vector - treat tuple as a table
2. Forbid vector of tuples at compile time. Add information to use vector in vector instead.

**Comment by Pirulax** [comment]
Yes this won't work. I have a fixed it but I'm lazy to test it. If you would test it I can make a PR.
My fix essentially would pack tuples into a table, and that would be the table key value, that is, in English:
```lua
{ -- this is the vector array
    {...tuple values...}
}
```
I presume this is what you want, right?
A temporary fix is to use `array<tuple<>, 1`. This will basically create an array with 1 tuple in it, this should in theory work, altough I'm not sure.

**Comment by sbx320** [comment]
https://github.com/multitheftauto/mtasa-blue/pull/1981
