### ISSUE TITLE
isTransferBoxAlwaysVisible returns old state when setting is changed

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#1985]
**Describe the bug**
`isTransferBoxAlwaysVisible()` returns the old state when setting is changed while transfer box is not visible.

`m_alwaysVisible` is only changed according to the settings value when transfer box icon is visible.

**To reproduce**
1. Toggle the always setting while you're not being transferred any files
2. Run `crun isTransferBoxAlwaysVisible()`
3. Change the setting via menu
4. Run `crun isTransferBoxAlwaysVisible()` (same old value)

**Expected behaviour**
Value to have updated.

**Version**
r20788

**Additional context**
- I'd probably add a new `CTransferBox::SetAlwaysVisible` function which is called from `CSettings` upon save/ok (like other settings do), instead of checking and updating setting in `DoPulse`
- Reported initially by [DREFT](https://discord.com/channels/278474088903606273/366384007535001612/795786138211057731) on Discord
- Oversight by PR reviewers

**Comment by botder** [comment]
I can confirm this and will resolve this quickly.

**Comment by botder** [comment]
Fixed in 805dcd7eb26ee3ebe6785b22a5968b981b8cf0a4 (should be in revision >= 20790)
