### ISSUE TITLE
Weird animation when trying to get into a vehicle from water

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#1990]
**Describe the bug**
While in the water, try to get into the nearest vehicle.

**To reproduce**
1. Start runcode
2. Run this commands:
```lua
srun createVehicle ( 411, -182, 269, 4, 0, 0, 90 )
srun setElementPosition ( me, -181, 274, 0 )
```
3. Press F/G

**Expected behaviour**
Player should have a swimming animation.

**Screenshots**
![mta-screen_2021-01-08_03-17-04](https://user-images.githubusercontent.com/12110157/103959168-0b1b9780-5160-11eb-944d-f962247279b4.png)

**Version**
Client: Multi Theft Auto v1.5.8-release-20794
Server: MTA:SA Server v1.5.8-release-20794

**Additional context**
This issue appeared after PR #1986 was merged.

**Comment by patrikjuvonen** [comment]
Does the player enter the vehicle?

**Comment by theSarrum** [comment]
> Does the player enter the vehicle?

No, everything is ok, except for this animation (which is in the screenshot above) when the player doesn't move.

**Comment by botder** [comment]
My second fix prevents the client from sending the enter-request if the ped is in water and the vehicle model is not enterable when in water. Before the fix, the client would send the request to the server, the server would then allow it, the client then proceeds to set the complex task to enter the vehicle and then breaks the ped's animation.
