### ISSUE TITLE
A function to remove absolutely everything from the map

### ISSUE THREAD

**Issue by Gaimo** [multitheftauto/mtasa-blue#2000]
**Is your feature request related to a problem? Please describe.**

removeWorldModel does not delete the sea, I need the map completely deleted to start a new map, we are in a project to redo some cities in Brazil. It is even possible to delete all objects on the map, but there are still some areas with sea.

**Describe the solution you'd like**

Delete everything on the map, including the sea, have a completely clean map, to reconstruct everything from scratch.

**Describe alternatives you've considered**

```
for n=1,19999,1 do
    removeWorldModel(n, 10000, 0, 0, 0);
end
    
setOcclusionsEnabled(false);
```

**Additional context**

https://i.ibb.co/zS8ZJtd/image.png

Another alternative, could have one or more dimensions completely clean.

**Comment by Lpsd** [comment]
Use https://wiki.multitheftauto.com/wiki/SetWaterLevel (this is actually used as an example to reset the whole map on https://wiki.multitheftauto.com/wiki/RemoveWorldModel)

Note: it may be worth visiting our scripting channels on the MTA Discord for help, before submitting an issue/feature request on GitHub.

**Comment by Gaimo** [comment]
In the forum they told me to come here, but it worked here, sorry.
