### ISSUE TITLE
Base32 support

### ISSUE THREAD

**Issue by Inder00** [multitheftauto/mtasa-blue#2002]
**Describe the solution you'd like**
Add `base32` support programically.
Base32 is used by two-factor-authentication (ex. TOTP) to generating secret tokens.

Shared functions:
- `string base32Encode( string value )`
- `string base32Decode( string value )`,
- `string encodeString( string "base32", string value )`
- `string decodeString( string "base32", string value )`

**Comment by Pirulax** [comment]
I think we should add a `baseEncode/Decode` function instead.
The syntax would look like this:
```cpp
baseEncode(string value, int radix = 64)
```
Radix is the base, so 32, 64, 128, etc...

**Comment by Nico8340** [comment]
#3312

**Comment by ghost** [comment]
This issue can be closed, as #3312 was merged.
