### ISSUE TITLE
Hmac support

### ISSUE THREAD

**Issue by Inder00** [multitheftauto/mtasa-blue#2003]
**Describe the solution you'd like**
Add `hmac` support programically.
Hmac is used by two-factor-authentication (ex. TOTP) to generating time-based (for TOTP) codes.
Algorithms that can be used are already built into the MTA, and they are `sha1`, `sha256`, `sha512`.

Shared functions:
- `string hmac( string value, string key, string algorithm )`

**Comment by Addlibs** [comment]
A Lua workaround I've developed some time ago using the `hash` function
```Lua
local algorithmBlockSize = {
    ["md5"] = 64,
    ["sha1"] = 64,
    ["sha224"] = 64,
    ["sha256"] = 64,
    ["sha384"] = 128,
    ["sha512"] = 128,
}
function hmac(key, message, hashAlgorithm)
    local blockSize = algorithmBlockSize[hashAlgorithm]
    assert(blockSize, "Invalid hash algorithm")

    if #key > blockSize then
        key = hash(key)
    end

    local i_key_pad = key:gsub('.', function(a) return string.char(bitXor(string.byte(a), 0x36)) end) .. string.rep(string.char(0x36), blockSize - #key)
    local o_key_pad = key:gsub('.', function(a) return string.char(bitXor(string.byte(a), 0x5c)) end) .. string.rep(string.char(0x5c), blockSize - #key)

    return hash(hashAlgorithm, o_key_pad .. hash(hashAlgorithm, i_key_pad .. message):gsub('..', function(hexval) return string.char(tonumber(hexval, 16)) end))
end
```
This is mostly based on the [pseudo code from Wikipedia](https://en.wikipedia.org/wiki/HMAC#Implementation).

Some assertions here to make sure it works correctly (I know, this key and message are very short and probably not adequate for proper exhausiving testing of the algorithms but those are the hmacs I've precomputed at the time and never bothered changing them.
```Lua
assert(hmac("abc", "hello", "sha1") == "d373670db3c99ebfa96060e993c340ccf6dd079e", "Unexpected result for hmac-sha1")
assert(hmac("abc", "hello", "sha224") == "de525f00279fe5b768fe1f634bd42c4d5355860fc23e68de03625b0b", "Unexpected result for hmac-sha224")
assert(hmac("abc", "hello", "sha256") == "f3166a3a404599d2046ed2aae479b37d54b51d2e85259c9e314042753be7d813", "Unexpected result for hmac-sha256")
assert(hmac("abc", "hello", "sha384") == "f93d8092f94b63dc810460948103d224fa3a2c0da1ec313cd77f198fb60706f2d211bb191184b96d76b76d384fe6953d", "Unexpected result for hmac-sha384")
assert(hmac("abc", "hello", "sha512") == "7b458e1a9dda7dcff225037f22ddb4d2c47b706fe380a70a4952d9905f4c0aae1d52bcbf014a33b769e8029771fe92cbd8337ba3a2580ad46788985567cb7a3e", "Unexpected result for hmac-sha512")
assert(hmac("abc", "hello", "md5") == "798c3638ef28c16af376b4501b60b992", "Unexpected result for hmac-md5")
```

But I do agree having this built in as a hardcoded function would be much easier to use and (perhaps) faster as this code makes multiple calls to hardcoded functions whereas I'm sure just one Lua-to-C call would be faster.

**Comment by AlexTMjugador** [comment]
> But I do agree having this built in as a hardcoded function would be much easier to use and (perhaps) faster as this code makes multiple calls to hardcoded functions whereas I'm sure just one Lua-to-C call would be faster.

From a security standpoint, it is also a good idea for MTA to implement these kind of functions. I think almost anybody would trust a cryptographic primitive more if it is implemented in MTA or a well-known and audited library than if it is implemented by some random script made by some random person.

**Comment by sbx320** [comment]
I'd only add this to `encodeString`/`decodeString`. No reason to add additional functions which would do the same.

hmac is most likely available via cryptopp so this should be relatively simple to implement.

**Comment by cleopatradev** [comment]
> I'd only add this to /. No reason to add additional functions which would do the same.`encodeString``decodeString`
> 
> hmac is most likely available via cryptopp so this should be relatively simple to implement.

https://github.com/multitheftauto/mtasa-blue/blob/master/vendor/cryptopp/hmac.h
