### ISSUE TITLE
Add skins from server

### ISSUE THREAD

**Issue by talhatugsat** [multitheftauto/mtasa-blue#2004]
It would be great if each server could add their own custom view.
![image](https://user-images.githubusercontent.com/51381316/104691269-f66a7100-5716-11eb-9eb0-6adb9ea6c0a2.png)

**Comment by redeibarnabas** [comment]
dx can be modified however you want to. Those files shouldn't be accessed by the server.

**Comment by talhatugsat** [comment]
No, I'm not saying that server access.
I'm saying every server add there, if player quitting game then remove added file

**Comment by talhatugsat** [comment]
if that's the case We get rid of (gui or dx)lib usage.

**Comment by redeibarnabas** [comment]
Useless imo

Removes the freedom of costumization from players

**Comment by talhatugsat** [comment]
It is useless to costume the players on the server that is already using completely lib

**Comment by redeibarnabas** [comment]
You can just make one and share it with the players and they can choose if they want to use it or not.

**Comment by patrikjuvonen** [comment]
Duplicate of #329
Related to #273 
Related to #1459
