### ISSUE TITLE
playSound - on(Client)SoundComplete

### ISSUE THREAD

**Issue by fresholia** [multitheftauto/mtasa-blue#2005]
**Is your feature request related to a problem? Please describe.**
The event can be triggered when the local music we run in the playSound function finishes playing

**Describe the solution you'd like**
on(Client)SoundComplete

Example:
```lua
local sound = playSound("sound.mp3")
addEventHandler("onClientSoundComplete", sound,
    function()
        --finish
    end
)
```

**Comment by Vadya963** [comment]
https://wiki.multitheftauto.com/wiki/OnClientSoundStopped
