### ISSUE TITLE
Javascript as a secondary language

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#2007]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
Because javascript is popular, have many benefits over lua with almost the same syntax, i decided to make an attempt of adding javascript as a secondary language to mta. I decided to use V8 <https://v8.dev/> the same engine that chrome and cef in mta uses. It may bring new people to mta that already know js.

My general concept
1. "script" tag in meta.xml, accept attribute that tell, is it lua ( default ), or javascript. `<script src="foo.js" lang="js">`
2. V8 has own "turbo-jit", thats feature i want to enable by default and if possible, never turn off.
3. mta functions will be located into some module, like "mta", simply `import * as mta from "mta"` to get access to the api.
4. javascript will availiable both, client and serverside
5. lua and javascript could communicate via events only, and exports across resources
6. New argument parser would generate functions for javascript without any programmer effort. `lua_State*` is for lua, there should be variant for javascript state as well.
7. i don't want to compile iinto mta everything, that why i decided to make another project that only purpose is to be simple interface for mta ( with functions like "new state", execute  code, call thing, get things ect ). Just headers for v8 takes 500KB of space.
8. All .dls and .lib files i'm going to download from google apis in same way as cef, example link: https://storage.googleapis.com/chromium-v8/official/canary/v8-win32-libs-rel-8.9.276.zip there are also 64 bit versions for every possible platform.

**Describe alternatives you've considered**
/

**Additional context**
Branch i'm working on: https://github.com/CrosRoad95/mtasa-blue/tree/Javascript

Right now i'm trying to make simplest hello world..

**Comment by patrikjuvonen** [comment]
Converted to discussion.

**Comment by patrikjuvonen** [comment]
This should be created as discussion thread instead of an issue.

https://github.com/multitheftauto/mtasa-blue/discussions
