### ISSUE TITLE
Lua modules

### ISSUE THREAD

**Issue by fresholia** [multitheftauto/mtasa-blue#2012]
**Is your feature request related to a problem? Please describe.**
Using Lua files as modules

**Describe the solution you'd like**
Lua modules can be added as follows
```
deathmatch/
      lua_modules/
          async/
              index.lua
```
~
index.lua:
```lua
local async = {}

function async.foreach(tbl, callback)
--todo
end

return async
```

It can also be used from any system as follows:
```lua
local async = require("async")

async.foreach({1,2}, function(i)

end)
```

In addition, ready-made lua modules on the internet can be added in this way.

**Comment by patrikjuvonen** [comment]
This issue has been requested many times. Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/1780

Please search for existing issues before creating new ones thank you!
