### ISSUE TITLE
QRCode Generation Support

### ISSUE THREAD

**Issue by Inder00** [multitheftauto/mtasa-blue#2019]
**Describe the solution you'd like**
Add `generating qrcodes` support programically.
QRCodes can be used ex. for two factor authentication.

Shared functions:
- `texture generateQRCode( string content, int width, int height )`

**Comment by Disinterpreter** [comment]
what's about porting it to MTA?
https://github.com/speedata/luaqrcode

**Comment by prnxdev** [comment]
You can use API for that and then use `fetchRemote` to generate image.

**Comment by patrikjuvonen** [comment]
No.
