### ISSUE TITLE
More fire functions

### ISSUE THREAD

**Issue by Dante383** [multitheftauto/mtasa-blue#2024]
Currently, there are only two fire functions available from Lua: createFire and extinguishFire. createFire returns bool, not fire element type so extinguishFire is based on coordinates. However, in the MTA source code you can find following fire-related functions:
https://github.com/multitheftauto/mtasa-blue/blob/a0410c68945b6b3d9225c8c90af2bb6b1cda5eaa/Client/game_sa/CFireSA.cpp

SetTimeToBurnOut, GetTimeToBurnOut - which would be nice, currently you can only manipulate the size parameter in createFire to get more/less burning time

IsBeingExtinguished - would be nice for some firefighter jobs or something like that, you won't have to calculate it in onClientPlayerWeaponFire anymore 

GetStrength & SetStrength would be a nice addition too, i guess

There is also GetPosition & SetPosition 

The issue I see is however with backwards compatibility, currently createFire returns bool and it would return fire element. I think we could add parameter to createFire which would specify whether it should return boolean or fire element

**Comment by Dante383** [comment]
Oh, and maybe some events - onClientFireExtinguishStart, onClientFireExtinguishStop

**Comment by PlatinMTA** [comment]
There is already an issue about this problem on #888

**Comment by Dante383** [comment]
Oh, that's right. Sorry, didn't see it
