### ISSUE TITLE
In MTA the stuff i write gets sent as squares and stuff

### ISSUE THREAD

**Issue by zysta0** [multitheftauto/mtasa-blue#2033]
In MTA the stuff i write gets sent as squares and stuff, does anyone have a solution to that problem? Some fonts are lines and some are squares
![Ekran Alıntısı](https://user-images.githubusercontent.com/77770817/105286697-e3004f80-5bc7-11eb-95b2-3b1299bc127e.PNG)
When i paste it in the notepad it looks normal
![F](https://user-images.githubusercontent.com/77770817/105286741-f3182f00-5bc7-11eb-846d-dd2acbadbafc.PNG)
I gave the name to the notepad its still normal
![X](https://user-images.githubusercontent.com/77770817/105286759-f9a6a680-5bc7-11eb-8f75-dfd717b04de6.PNG)
Its normal in discord as well
![c](https://user-images.githubusercontent.com/77770817/105286786-01fee180-5bc8-11eb-8135-5d8c7896f644.PNG)
it's normal for everyone while this only happens to me.

**Comment by redeibarnabas** [comment]
Have you tried reinstalling MTA or selecting another font for the chat?

**Comment by Lpsd** [comment]
yup, sounds like some corrupt files in your MTA installation, or even Windows.

**Comment by patrikjuvonen** [comment]
Please follow the instructions on this topic: https://forum.mtasa.com/topic/32071-mtadiag-diagnostic-tool-for-mtasa-support-section-information/ and post the issue on the Client Support forum.

**Comment by zysta0** [comment]
> Have you tried reinstalling MTA or selecting another font for the chat?

yes but didn't work


> yup, sounds like some corrupt files in your MTA installation, or even Windows.

yes but i don't know which one
