### ISSUE TITLE
Add-on vehicle behaving weird

### ISSUE THREAD

**Issue by R4ven47** [multitheftauto/mtasa-blue#2034]
After requesting a model and using setElementModel
on every client, player reports issue of seeing vehicle doors constantly moving.
Other issues include: 'Network Trouble' when player tries to get inside vehicle

**To reproduce**
1. Download the reproduction resource
2. Create a vehicle server-side and enter it
3. Use '/request' command
4. See bug
Reproduction resource: 
[model_requesting.zip](https://github.com/multitheftauto/mtasa-blue/files/5851382/model_requesting.zip)

**Expected behaviour**
 Normal vehicle doors movement in all clients with the ability of players getting into the vehicle.

**- server/client version: 1.5.8**

**Comment by Allerek** [comment]
'Add-on' vehicles are not ready, they are still being in a recode process, we shouldnt care about current system much, as its being reworked.
https://github.com/multitheftauto/mtasa-blue/pull/1936
https://github.com/multitheftauto/mtasa-blue/pull/1924
