### ISSUE TITLE
Player is not able to leave Vehicle, which is about to explode with 0 health

### ISSUE THREAD

**Issue by haron4igg** [multitheftauto/mtasa-blue#2048]
When vehicle is on fire with 0 health, player is not able to leave car anymore.
Issue appeared in: #1748

**Comment by ghost** [comment]
I can confirm that, @Zangomangu would be nice if you could fix it :)

**Comment by Zangomangu** [comment]
Yeah will do shortly, I can see the check wasnt there before when exiting, might've thought 0 hp was instant explode
