### ISSUE TITLE
gtaRenderHook + MTA

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2051]
**Describe the solution you'd like**
As we all want to introduce DX11 to MTA, we could start working on implementing
https://github.com/petrgeorgievsky/gtaRenderHook
to MTA, it comes with:

- DX11/Vulkan API for GTA
- Better optimization
- Allows better graphics for game
- It mostly uses our GPU memory, which is faster than RAM
- MIT Licensed

Its still 'in creation', but we could try to make a test-build, just to test if there is any sense in future of doing this.

**Comment by PlatinMTA** [comment]
saml1er wanted to work on this according to #1061, but didn't have the time and it seems like quite a bit of work.

**Comment by fresholia** [comment]
Discussions about this topic are ongoing on development discord #directx11 channel.

**Comment by LosFaul** [comment]
@tederis had an alternative suggestion what could be used too

https://github.com/DiligentGraphics/DiligentEngine

but yeah main discussion is on discord
