### ISSUE TITLE
Add raw variable for HTTP Web Interface

### ISSUE THREAD

**Issue by Disinterpreter** [multitheftauto/mtasa-blue#2052]
**Is your feature request related to a problem? Please describe.**
MTA WEB HTTP add variable `raw` for accepting data

**Describe alternatives you've considered**
Form-data but it is bad for example for JSONRPC

**Additional context**
https://wiki.multitheftauto.com/wiki/Resource_Web_Access
We have some variables, so we need add new:
```
    table requestHeaders: This is a table containing all the headers that were requested with the page. You can set returned headers using httpSetResponseHeader.
    table form: This is a table containing all the form data submitted to the page using HTTP POST combined with any variables passed in the querystring with HTTP GET.
    table cookies: This is a table of all the cookies. You can modify cookies using httpSetResponseCookie.
    string hostname: This is a string containing the IP address or hostname that requested the page.
    string url: This is the URL of the page.
    account user: This is the account of the current user.
```
![image](https://user-images.githubusercontent.com/3816155/106118692-71934480-6165-11eb-99bc-58890fc30c5c.png)

**Comment by Disinterpreter** [comment]
This issue is really simple to do.
1. `ipoHttpRequest` gives us the raw as `sBody`
2. You can just add `args.PushString(ipoHttpRequest->sBody);` to here after `querystring`
https://github.com/multitheftauto/mtasa-blue/blob/a0410c68945b6b3d9225c8c90af2bb6b1cda5eaa/Server/mods/deathmatch/logic/CResourceHTMLItem.cpp#L86
3. and add `raw` as new argument to here after `querystring`
https://github.com/multitheftauto/mtasa-blue/blob/a0410c68945b6b3d9225c8c90af2bb6b1cda5eaa/Server/mods/deathmatch/logic/CResourceHTMLItem.cpp#L165
As I did:
`strScript += "function renderPage ( requestHeaders, form, cookies, hostname, url, querystring, raw, user )\n";`

That's all.


Test is like
add in `meta.xml` html file like `<html src="index.htm" />`
with the code
```
<*
iprint(raw)
httpWrite("ok")
*>
```

**Comment by botder** [comment]
Do you mind explaining the issue this is supposed to solve for you?

**Comment by Disinterpreter** [comment]
> 
> 
> Do you mind explaining the issue this is supposed to solve for you?

For example, I want to work with MTA HTTP Resources as JSONRPC. It's okay it should work, but in JSONRPC standards I must to send data as a raw. But at the moment MTA http system cannot work with raw data. Same it useful for every manual handling of HTTP packages, like extra requests (POST/DELETE/etc..) we just look `requestHeaders` and take data from raw without any `forms`.
