### ISSUE TITLE
Add onElementInteriorChange

### ISSUE THREAD

**Issue by gptrk0** [multitheftauto/mtasa-blue#2056]
**Is your feature request related to a problem? Please describe.**
We have onElementDimensionChange since r20724, but **onElementInteriorChange is still missing**.

**Describe the solution you'd like**
Add **onElementInteriorChange** and **onClientElementInteriorChange**, which will be triggered when element's interior changed by setElementInterior

**Comment by Fernando-A-Rocha** [comment]
I've personally felt the need to have this a lot of times
Maybe onElementDimensionChange too?

**Comment by Dutchman101** [comment]
> Maybe onElementDimensionChange too?

That's what he mentioned in the OP.. it was recently added, See [https://wiki.multitheftauto.com/wiki/OnElementDimensionChange](https://wiki.multitheftauto.com/wiki/OnElementDimensionChange) and [https://wiki.multitheftauto.com/wiki/OnClientElementDimensionChange](https://wiki.multitheftauto.com/wiki/OnClientElementDimensionChange)

Btw, this suggestion just got implemented in 0105943 so closing
Nice to finally have the combination of both, yeah.

@Patrick2562: once you get to it, please add wiki pages for the 2 events added in 0105943: [https://wiki.multitheftauto.com/wiki/OnClientElementInteriorChange](https://wiki.multitheftauto.com/wiki/OnClientElementInteriorChange) and [https://wiki.multitheftauto.com/wiki/OnElementInteriorChange](https://wiki.multitheftauto.com/wiki/OnElementInteriorChange) as well ;)
