### ISSUE TITLE
Add clearDebugBox function

### ISSUE THREAD

**Issue by LVRENT** [multitheftauto/mtasa-blue#2059]
**Is your feature request related to a problem? Please describe.**
As I'm restarting my local server very often to test the changes made, my debug box gets filled with informations that I want cleared out at restart. Example: At every restart, the server outputs "Connected to the MySQL database server." to let me know if the server successfully connects to the MySQL. It gets "spammed" if I can say like that.

It will be nice if we can have a function like **clearDebugBox** to clear the debug logs like we have clearChatBox for the chat. This way, we can call the function whenever we want (especially for me in the onResourceStart event).

**Describe the solution you'd like**
Add **clearDebugBox** serverside.

**Describe alternatives you've considered**
We can use **/cleardebug** to clear the debug box but it's annoying to do that on every resource restart.

**Additional context**
Nothing.

**Comment by PlatinMTA** [comment]
If you are going to use outputDebugString() and then you want to clear the debug box, then maybe you should use outputServerLog() for serverside scripts.

**Comment by redeibarnabas** [comment]
It could be useful. But for now you can just bind it.

**Comment by LVRENT** [comment]
Closing it as the request was implemented some time ago.
