### ISSUE TITLE
http server and mta server connection

### ISSUE THREAD

**Issue by talhatugsat** [multitheftauto/mtasa-blue#2066]
httpserver will be able to send data to the server if we enter the correct password that we will add to mtaserver.conf.

![my paint](https://user-images.githubusercontent.com/51381316/106615932-04751a00-657e-11eb-9e8f-8c588469a355.png)

**Comment by botder** [comment]
HTTP authentication is solved with accounts. Authorization is solved with ACL.
What else do you need or what is the problem you're facing?

**Comment by talhatugsat** [comment]
I did some research but could not find an example of how to do it.
I can't send data from my website to my server

**Comment by Disinterpreter** [comment]
What do you want to send?

**Comment by talhatugsat** [comment]
For example, you can update your account password on the site

**Comment by Disinterpreter** [comment]
> 
> 
> For example, you can update your account password on the site

if you want to update the password **on the site** just call the method over `fetchRemote`

**Comment by talhatugsat** [comment]
no, just the opposite
website -> mta

**Comment by Disinterpreter** [comment]
> 
> 
> no, just the opposite
> website -> mta

so, several days ago I did the work with `body` on internal MTA webserver, so you can use that.
Read here: https://github.com/multitheftauto/mtasa-blue/issues/2052

**Comment by talhatugsat** [comment]
> > no, just the opposite
> > website -> mta
> 
> so, several days ago I did the working with `body` on internal MTA webserver, so you can use that.
> Read here: #2052

very thanks

**Comment by patrikjuvonen** [comment]
Please use the scripting help channels on Discord or forums for help.
