### ISSUE TITLE
setBrowserVolume doesn't work

### ISSUE THREAD

**Issue by RatajVaver** [multitheftauto/mtasa-blue#2071]
**Describe the bug**

setBrowserVolume function doesn't work at all (or at least not with YouTube videos)

**To reproduce**
1. Create browser and load some YouTube video URL.
2. Use setBrowserVolume for either that specific browser, or even globally.
3. There's no change in volume, even if used with 0 to turn it off.

**Expected behaviour**

setBrowserVolume should work just like setSoundVolume

**Version**
1.5.8-release-20779

**Comment by patrikjuvonen** [comment]
Pretty much same as #451 except this concerns setBrowserVolume function

Merging issues together.
