### ISSUE TITLE
Error loading fonts!

### ISSUE THREAD

**Issue by se16n** [multitheftauto/mtasa-blue#2076]
Hi,
After recent update i've faced with following error message.

> Error loading fonts!
> DefaultResourceProvider::load - cgui/unifont.tts does not exist

In MTA\cgui folder there's only unifont-5.1.20080907.ttf font exist.

**Comment by botder** [comment]
[Download](https://mtasa.com/download) MTA:SA from the homepage and reinstall it.
Furthermore, this should've been asked on our Discord server.
