### ISSUE TITLE
Add link to discord on https://www.multitheftauto.com/

### ISSUE THREAD

**Issue by se16n** [multitheftauto/mtasa-blue#2077]
**Is your feature request related to a problem? Please describe.**

Discord server is missing on the front page of https://www.multitheftauto.com/

**Describe the solution you'd like**

Put link to discord server on https://www.multitheftauto.com/

**Describe alternatives you've considered**

You can get to discord only if you found somebody mentioned it.

**Additional context**

**Comment by Vadya963** [comment]
if you click on the wiki and scroll down, you can see a link to discord

**Comment by se16n** [comment]
> 
> 
> if you click on the wiki and scroll down, you can see a link to discord

That's the issue. It's not intuitive at all.

Official site's front page is the central landing place. Link to youtube and twitter is already there, while discord is the main place for conversations and it's not.

**Comment by Dante383** [comment]
It'd be also a good idea to remove IRC from main wiki page - it doesn't work anymore (i checked today and i checked last month)

**Comment by Fernando-A-Rocha** [comment]
^ This is actually very important and relevant for getting people involved in the community. I'm sure still a lot of MTA players (new or not) don't use MTA's official discord

Something needs to be done about this section: https://i.imgur.com/SjN8NUe.png

**Comment by patrikjuvonen** [comment]
We are currently waiting for @ccw808 to merge and deploy the changes to the main site proposed on Feb 9.

**Comment by patrikjuvonen** [comment]
Discord link has now been deployed to the frontpage.
