### ISSUE TITLE
Disabling MTA internal chatbox messages

### ISSUE THREAD

**Issue by muratdogdas** [multitheftauto/mtasa-blue#2087]
**Is your feature request related to a problem? Please describe.**
When we're creating a login system, this problem always happens. 
The [logIn](https://wiki.multitheftauto.com/wiki/LogIn) function sending a message to chatbox when its successful even if developer doesn't want it.

**Describe the solution you'd like**
An optional argument will add to the logIn function. By this way if developer wants to disable the message. he/her will easly set that argument to false.

**Comment by Lpsd** [comment]
This can probably be resolved by #1020 (with some tweaks). I'll need to revive the branch and look at it again, it's been a while.

You'd be able to use `onClientChatMessage` to check if a message was sent from MTA (internal). You could then do a simple string search for "logged in" (or whatever static text the internal message contains) and cancel the event.

**Comment by muratdogdas** [comment]
> This can probably be resolved by #1020 (with some tweaks). I'll need to revive the branch and look at it again, it's been a while.
> 
> You'd be able to use `onClientChatMessage` to check if a message was sent from MTA (internal). You could then do a simple string search for "logged in" (or whatever static text the internal message contains) and cancel the event.

#1020 is looking good, but if we're talking about making it much easier to use, an optional message argument or a function for disabling the hardcoded messages will be the best solution for that. Because authentication functions are sending messages more than just "logged in". Maybe we can create an `outputHardcodeMessages` function?

**Comment by redeibarnabas** [comment]
It is easy to use what are you talking about?

if messageType == 4 and string.find(text, "login:") then
    cancelEvent()
end

**Comment by muratdogdas** [comment]
> It is easy to use what are you talking about?
> 
> if messageType == 4 and string.find(text, "login:") then
> cancelEvent()
> end

Don't agree with you, why am I need to add these lines to every resource that needs to disable internal messages?

**Comment by redeibarnabas** [comment]
You don't. You just need this once.

**Comment by muratdogdas** [comment]
Btw I choose the wrong name for the issue. What I am trying to explain is all of the hard-coded messages sent to the chat box.

**Comment by redeibarnabas** [comment]
function disableHardcoded(text, r, g, b, messageType)
    if messageType == 4 then
        cancelEvent()
    end
end
addEventHandler("onClientChatMessage", root, disableHardcoded)

**Comment by muratdogdas** [comment]
OH, I see right now. Sorry for the novice ideas :)

**Comment by muratdogdas** [comment]
@Lpsd On the wiki page, the messageType argument is added for the onClientChatMessage event but when I try to use it, returns nil. My server version is the latest stable Linux version, and the client version is recommended/minimum

`addEventHandler("onClientChatMessage", root, function(msg, r, g, b, testd)
         print(msg, testd)
end)
`

![image](https://user-images.githubusercontent.com/58406664/108166684-93993a80-7105-11eb-86be-47e342eee51a.png)

**Comment by redeibarnabas** [comment]
PR isn't merged yet for some unknown reason

**Comment by muratdogdas** [comment]
I don't realize that because I'm not good at Github. Instead of hardcoded messages, every message type is returning nil as well. How can I check is message an action message or something like that

**Comment by Lpsd** [comment]
@ratasky the PR is not merged, so you won't be able to use it yet.

Even when the PR is merged, you will need to use the latest nightly version of MTA.

I will work on the PR at some point in the next week, it shouldn't take long to revive and merge.

**Comment by Lpsd** [comment]
@ratasky Also, can you link me to the "wiki page" where you found `messageType` as a parameter to the event? It's definitely not listed here: https://wiki.multitheftauto.com/wiki/OnClientChatMessage (and shouldn't be yet, since the PR is not merged).

**Comment by redeibarnabas** [comment]
I added it before even testing it, rookie mistake of me. But whenever the PR is merged an undo will just do to the last change.

**Comment by muratdogdas** [comment]
@Lpsd It has now been removed, but there were a messageType parameter and description table for it. when I posted the picture earlier today.
