### ISSUE TITLE
Add setChatBoxCharacterLimit (increase default chatbox character limit)

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#2090]
**Describe the feature request**
Add a new scripting function (or configuration to opt-in) that expands the character limit of default chatbox

For more information, refer to this popular suggestion: [https://forum.mtasa.com/topic/58855-chat-length-max-allowed-symbols/](https://forum.mtasa.com/topic/58855-chat-length-max-allowed-symbols/) which is the reason for adding this to the tracker

**Describe the solution you'd like**
Allow servers to increase and control the chatbox character limit if they desire so

**Describe alternatives you've considered**
The alternative is a custom chatbox. But it should be trivial for us to support it natively, in the default chatbox.
Especially for such a trivial change, a lot of scripters don't want to hop to writing a custom chatbox as the complications (and adaptations needed in their other resources) outweigh the feature that they gain. It is a popular suggestion for a reason, imagine the ease of using a scripting function or other toggle (with configurable character limit) for this.

**Comment by Fernando-A-Rocha** [comment]
I very much support this implementation. Would do wonders for a lot of servers 🙏

**Comment by Lpsd** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/a0410c68945b6b3d9225c8c90af2bb6b1cda5eaa/Client/core/CChat.h#L22

**Comment by Lpsd** [comment]
We should definitely keep the original limit as default, who knows what that could break in existing scripts.

I was going to suggest integrating this into the proposed `setChatboxLayout` and existing `getChatboxLayout` functions, to keep things clean. However, I don't think this value should be changed by the client itself (for example, through the settings menu), the server should be the one enforcing this limit.

(most, if not all properties that you can get/set with the chatbox layout functions can also be changed by the client via settings GUI, I'd rather keep things consistent)

Therefore, `setChatboxCharacterLimit` seems fine (notice the case).

Each time a player leaves/joins a server, this limit should be set back to the original (96). The server can then decide if it wants to increase the limit.

```lua
setChatboxCharacterLimit(int limit) -- sets limit (must be 0 or greater)
setChatboxCharacterLimit() -- resets the limit
```

**Comment by Dutchman101** [comment]
> Each time a player leaves/joins a server, this limit should be set back to the original (96). The server can then decide if it wants to increase the limit

All sounds good, but can you clarify just this? I would expect servers need to set a custom limit only once (e.g on server startup) like with many configurable things

Btw, on second thought - is a scripting function (per this request) or mtaserver.conf entry (with setServerConfigSetting compatibility) more suited? To just put the default of 96 in config, and let servers edit it.

**Comment by Fernando-A-Rocha** [comment]
> Each time a player leaves/joins a server, this limit should be set back to the original (96). The server can then decide if it wants to increase the limit.

This got me confused as well. I think the limit should need to be set once with a function like setChatboxCharacterLimit that you described or a server config setting, both seem fitting.

**Comment by Lpsd** [comment]
Player joins a server which sets limit to 256.

Player quits the server and joins new server. Player now has 256 chat message limit, when the current server hasn't set anything.

All I'm saying is that we need to set the chatbox limit back to default each time a player joins a server.

**Comment by Lpsd** [comment]
`setChatboxCharacterLimit` would be a clientside function, therefore it needs to be ran for each client you want to adjust the limit for (e.g `onClientResourceStart`)

The limit should only be enforced for the duration of the connection to that server. Once they leave, the limit is set back to the default (96).

I don't think we should add a server-side version of this function. There's no real need for it, and without looking into the code properly I'm not sure what additional data we'd need to share with the server in order to have a server-sided function. Since the chatbox itself is (obviously) mostly clientside code, it's easier just to have a clientside Lua function for this :)

**Comment by LosFaul** [comment]
shouldn't a server not tell the client which character limit to set on join?

**Comment by Lpsd** [comment]
I'll probably add `getChatboxCharacterLimit` too since it's not really any more effort.

**Comment by Fernando-A-Rocha** [comment]
Oh gotcha! Makes total sense, lovely
