### ISSUE TITLE
Add the setPedScale()

### ISSUE THREAD

**Issue by mmertjuju** [multitheftauto/mtasa-blue#2096]
**Describe the feature request**
I cant change the ped size, it needs a new dff and txd file to change it, can the ped size enlargememt function be added without using a file? 

**Describe the solution you'd like**
A new function that will function, like the setObjectScale function.

**Describe alternatives you've considered**
How does the setObjectScale function work. The setPedScale function can also do that.

**Comment by Lpsd** [comment]
Use the ped morph shader from https://wiki.multitheftauto.com/wiki/Shader_examples

I don't think we should add a separate function for scaling the ped. You can use the shader above for dynamic scaling stuff, for anything else you should really be creating custom DFF/TXD's.

(even for custom TXD's, you can use generic shaders)

**Comment by mmertjuju** [comment]
Thanks but I am not creating/writing the shader, and the shader you suggested is breaking the ped. I want to shrink the vertical. And the file is needed to shrink vertically. When uploading a file, MB also increases.

**Comment by Lpsd** [comment]
As far as I'm aware `setObjectSize` is utilizing some engine functions that already exist in SA, but there isn't any kind of counterpart for peds/players - so it's not as simple as cut and pasting some code and renaming it `setPedSize`.

Anyone, feel free to investigate this, but I feel it's more pain than it's worth when there are already solutions for this. 

> the file is needed to shrink vertically. When uploading a file, MB also increases.

Seems like a non-issue really. I'm sure the client won't grumble at a MB or two of extra download. Custom DFF is currently the best solution to your problem.

**Comment by Lpsd** [comment]
If you want to provide some code which reproduces an issue you're facing with current functionality, to achieve the desired result, then please go ahead - otherwise I'll likely close this, as the solution already exists (and there aren't really any alternatives, aside from the shader mentioned above).

**Comment by mmertjuju** [comment]
Thanj you we used the dff file
