### ISSUE TITLE
Grenade bug which is here for 5 years and it's still not fixed and by day to day it's ruining atmosphere

### ISSUE THREAD

**Issue by Helter5** [multitheftauto/mtasa-blue#2099]
Grenade bug*
As the bug that is here with us for a long time - like 5 years and it's still not fixed and it's ruining atmosphere of clanwars and arenas on all Shooter/Hunter servers
(topic from 2019 https://github.com/multitheftauto/mtasa-blue/issues/1123)

As there it was explained ^^ but I'll explain it once more again:
How can you trigger Grenade bug?*
- You'll go to some Freeroam server (any, also you can use Host Game) and will take Grenade/Satchel. If grenade, you'll start throwing grenades under you and die by it. Then you'll join some server and you have triggered grenade bug. Same it's working with Satchel.

What's grenade?*
https://youtu.be/RraAIjzOet0
- A lot of times it's exploding over they player, so he die instantly instead of burning. I'll add few videos of explanation:
00:00 - 00:10 | You can see, that he has grenade and I don't, so his shoot disappeared for me, because I don't have grenade and it sticked with mine and exploded. It wouldn't happened, if he wouldn't use grenade bug.
00:11 - 00:23 | Clearly you can see, that he hit him, but he didn't die, because Hardy was using grenade. If he wouldn't, he would die. This can happen only with grenade.
00:24 - 00:30 | You can see, that the player hit Chiki, but he started burning, because the player who hit him was using grenade.
00:31 - 00:35 | Same situation as last one.
00:36 - 00:46 | Same situation as in 00:11 - 00:23. Zeroxy hit Vndtt, but he didn't die because he was using grenade. He got just -40hp. This can happen only with this bug.
00:47 - 00:53 | He shooted corner and it teleported to Lonnex because of grenade.

- You should fix this bug because it's ruining atmosphere of fun and it's hard to fix it by normal script. FFS made some script, but it's not working well. You can still trigger grenade and it's also kicking players who aren't using it or who came from PTP - mode which can trigger grenade bug, because there you can use 'Grenade'

Please take care of it..

**Comment by se16n** [comment]
Hell @Helter5 
I think it's better to stick with original issue and make this issue as a comment.

**Comment by patrikjuvonen** [comment]
Duplicate. Please add your comments to the issue #1123
