### ISSUE TITLE
Twitter feed doesn't display on frontpage

### ISSUE THREAD

**Issue by se16n** [multitheftauto/mtasa-blue#2100]
**Describe the bug**

Twitter feed doesn't displays on https://www.multitheftauto.com/.

**To reproduce**

Navigate to on https://www.multitheftauto.com/.

**Expected behaviour**

Tweeter feed displays message from MTA's twitter account on https://www.multitheftauto.com/

**Comment by patrikjuvonen** [comment]
Unable to reproduce. Need more information, such as your browser details (for example sharing the link from https://www.whatismybrowser.com/)

![Untitled](https://user-images.githubusercontent.com/22572159/109302489-01e6a700-7842-11eb-97a8-ba05e1316f8c.png)

**Comment by se16n** [comment]
@patrikjuvonen Issue seems to be related to disconnect.me plugin. Thank you, Patrik.
