### ISSUE TITLE
Typo in bug report template

### ISSUE THREAD

**Issue by se16n** [multitheftauto/mtasa-blue#2101]
**Describe the bug**

OLD: **Expected behaviour**
NEW: **Expected behavior**.

**Comment by bum8hj** [comment]
**behavior** is the **American** spelling
**behaviour** is the **British** spelling

Pretty sure it doesn't count as a typo

**Comment by se16n** [comment]
@bum8hj haha, my spellchecker is configured to check US spelling, thank you for letting know!
