### ISSUE TITLE
installer: MTA complete uninstall doesn't remove all files, folders and traces

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#2107]
**Describe the bug**
If you uninstall MTA and select "No" on the following dialog:

**Would you like to keep your data files (such as resources, screenshots and server configuration)? If you click no, any resources, configurations or screenshots you have created will be lost.**

The expected behavior would be that all MTA files and traces are cleaned. But that's not the case.

We are currently missing out on clearing some leftover registry entries:

**Registry leftover overview**

Location: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\UFH\SHC`

The name of each entry in SHC will be a short number and depend per user. For an example, see screenshots at the bottom.
But independent of their naming, it pertains to the below MTA entries (data contained in the entry):

Entry 1:

```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MTA San Andreas 1.5\MTA San Andreas.lnk
C:\Program Files (x86)\MTA San Andreas 1.5\Multi Theft Auto.exe
```

Entry 2:

```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MTA San Andreas 1.5\MTA Server.lnk
C:\Program Files (x86)\MTA San Andreas 1.5\server\MTA Server.exe
```

Entry 3:

```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MTA San Andreas 1.5\Uninstall MTA San Andreas.lnk
C:\Program Files (x86)\MTA San Andreas 1.5\Uninstall.exe
```

**To reproduce**
1. Install and run MTA
2. Run the MTA uninstaller (Uninstall.exe) and make sure to select "No" when it asks you if you want to keep some files (as per the issue description)
3. Observe the remaining files, folders and regkeys as in the issue description

**Expected behaviour**
Ideally, MTA should clean all files, folders and regkey traces after a full uninstall. We are really close to that point, so it's probably worth including these things that are being missed out on and make the uninstaller do an even better job.

**Screenshots**
All of the listed registry leftovers visualized in a tree
![reg](https://user-images.githubusercontent.com/12105539/109927040-efe28980-7cc3-11eb-9661-abe695ffd321.png)

**Version**
MTA:SA 1.5.8 r20802

**Comment by Dutchman101** [comment]
The recent commits 3811d8c and 15a03c1 appear to have sorted out some of the points

commit desc:
1) Remove 'Multi Theft Auto: San Andreas All' registry key if 'Common' is the only registry key left
2) Removes 'MTA San Andreas All' directory if 'Common' is the only directory left. This only affects 'C:\ProgramData\MTA San Andreas All'

**Comment by patrikjuvonen** [comment]
Further improvements made https://github.com/multitheftauto/mtasa-blue/compare/a74f57ab04eb...7d8843ce892d

Remaining is the .lnk references in that SHC path, but not sure if that's something we actually must clean up or is that a temporary thing.
