### ISSUE TITLE
Chatbox text manipulation changes

### ISSUE THREAD

**Issue by LVRENT** [multitheftauto/mtasa-blue#2109]
**Is your feature request related to a problem? Please describe.**

If we type some text (or a command) in the chatbox and we do a typo, we need to clear character-by-character to correct it; we also can't copy it or cut it (I don't know if it's for security reasons). It will be nice if we can manipulate the text by using the CTRL+A, CTRL+C and CTRL+X combinations. This is possible with the GUI inputs.

**Describe the solution you'd like**

Add some options to manipulate the text we currently type in the chatbox: Select all text, copy it or cut it.

**Describe alternatives you've considered**

We can't do the above suggestions in others way AFAIK.

**Comment by xLive** [comment]
Duplicate of #755

**Comment by LVRENT** [comment]
Oh, sorry, I didn't noticed that. I will close it now.
