### ISSUE TITLE
Mark getElementMatrix as deprecated.

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2111]
**Is your feature request related to a problem? Please describe.**
getElementMatrix(table matrixes in general) are pretty poor way to get the result, object matrixes should be used instead, we have a tip about that on wiki https://wiki.multitheftauto.com/wiki/Matrix#Why_not_stick_to_the_good_ol.27_tables.3F

**Describe the solution you'd like**
Mark getElementMatrix as deprecated.

**Describe alternatives you've considered**
Warning about they may be deprecated in future versions and object matrix should be used instead?

**Additional context**
PepeSad

**Comment by LosFaul** [comment]
NO
a lot people do not want to use MTA api oop functions for performance reasons

**Comment by Allerek** [comment]
> NO
> a lot people do not want to use MTA api oop functions for performance reasons

Table matrixes are considered as 'do not use' at least since  22 November 2014‎.
7 years, since everyone knows they are crap...

**Comment by LosFaul** [comment]
> 
> 
> > NO
> > a lot people do not want to use MTA api oop functions for performance reasons
> 
> Table matrixes are considered as 'do not use' at least since 22 November 2014‎.
> 7 years, since everyone knows they are crap...

this is nothing more than an opinion in the wiki...
and opinions and practice are two different things
also different people have different preferences what they are working with

**Comment by redeibarnabas** [comment]
No

**Comment by sbx320** [comment]
There's no reason to deprecate `getElementMatrix` right now. If oop is disabled, there's no alternative to using it.
