### ISSUE TITLE
dxDrawMaterialLine3D dont change face to rotation

### ISSUE THREAD

**Issue by mmertjuju** [multitheftauto/mtasa-blue#2113]
**Describe the bug**
When I add a picture to the floor with the dxDrawMaterialLine3D function, the rotation of the picture does not change.

**To reproduce**
local redcircle = dxCreateTexture("red.png")
x,y,z = -2422.68555, -608.78986, 132.56250
size = 1
addEventHandler("onClientRender", root,
function()
    local _, _, rZ = getElementPosition(getLocalPlayer())--but its dont working
    dxDrawMaterialLine3D(x+size, y+size, z-0.95, x-size, y-size, z-0.95, redcircle, size*2,tocolor(255, 255, 255, 255),  x, y, rZ)
end)

**Expected behaviour**
Add the rotation for dxDrawMaterialLine3D.

**Screenshots**
![mta-screen_2021-03-09_05-03-14](https://user-images.githubusercontent.com/52877837/110408077-0f97fa00-8096-11eb-90f0-0cbf067464ae.png)
![mta-screen_2021-03-09_05-03-19](https://user-images.githubusercontent.com/52877837/110408086-1292ea80-8096-11eb-838a-ceae7b1280b8.png)
![mta-screen_2021-03-09_05-03-25](https://user-images.githubusercontent.com/52877837/110408092-158ddb00-8096-11eb-834f-69bacdc84173.png)
![mta-screen_2021-03-09_05-03-32](https://user-images.githubusercontent.com/52877837/110408101-19216200-8096-11eb-88f6-aa0e8548b084.png)

**Version**
1.5.7-9.20621.0
Windows

**Additional context**
local redcircle = dxCreateTexture("red.png")
x,y,z = -2422.68555, -608.78986, 132.56250
size = 1
addEventHandler("onClientRender", root,
function()
    dxDrawMaterialLine3D(x, y, z + 1, x, y, z, redcircle, size*2,tocolor(255, 255, 255, 255))
end)
![mta-screen_2021-03-09_05-23-08](https://user-images.githubusercontent.com/52877837/110408970-8da8d080-8097-11eb-9a77-89efad28326a.png)

**Comment by redeibarnabas** [comment]
Easy fix is to use a render target and rotate it inside that.

**Comment by Lpsd** [comment]
Issue can be resolved via code. Marked as invalid and closed.

Please visit our Discord for scripting help in future before submitting issues.

**Comment by mmertjuju** [comment]
> Easy fix is to use a render target and rotate it inside that.

but very using cpu

**Comment by mmertjuju** [comment]
> Issue can be resolved via code. Marked as invalid and closed.
> 
> Please visit our Discord for scripting help in future before submitting issues.
Nobody could find the solution. Because I want something different. I want the picture will appear on the floor. But whichever direction the actor is facing, he will turn in that direction in the picture.

**Comment by redeibarnabas** [comment]
> > Easy fix is to use a render target and rotate it inside that.
> 
> 
> 
> but very using cpu

Not really. Just make sure you optimize it correctly.

**Comment by mmertjuju** [comment]
> > > Easy fix is to use a render target and rotate it inside that.
> > 
> > 
> > but very using cpu
> 
> Not really. Just make sure you optimize it correctly.

The function already has a rotation, but it works incorrectly, why should I create a new rotation function?

**Comment by Lpsd** [comment]
Because your code is incorrect, you're using the wrong rotation and position values.

As per your history of raised issues (including this), I would strongly advise you to visit our Discord and ask for help there, or alternatively visit the scripting section on the forum, before this issue turns into your personal support thread. 

Currently this is a code issue, not an MTA issue.
