### ISSUE TITLE
Nitrous bug

### ISSUE THREAD

**Issue by mertcan4555** [multitheftauto/mtasa-blue#2120]
**Describe the bug**
You can easily crash a race server if there is a collectible nitrous object

**To reproduce**
Firstly, you need a friend to reproduce. After you get a friend just get in the nitrous object together(nitrous object must be respawnable), 1 minute of waiting in the nitrous object will cause much lag and finally the server will crash.

Please paste reproduction resources (zip files) directly into this section.
--> I think original race.zip file is suitable

**Screenshots**
![maxresdefault](https://user-images.githubusercontent.com/53582398/111044922-6f0e5500-845c-11eb-8568-49125ed46b9b.jpg)
(think like the red circle is the nitrous object and red car is a player and the yellow one is another player, if they can take the nos at the same time; the bug will work.)
-->

**Version**

**Comment by botder** [comment]
You are in the wrong place. This repository is for Multi Theft Auto: San Andreas server/client only.
