### ISSUE TITLE
SQL multi line query error "not an error" with "multi_statements=1"

### ISSUE THREAD

**Issue by rifleh700** [multitheftauto/mtasa-blue#2126]
**Describe the bug**
Lua multi line query causes warning "not an error" and ruins query

**To reproduce**
1. Set DB connection option "multi_statements=1"
2. Write multiline SQL query
3. Add ';' symbol to end of query
4. Add new line and tab symbols after ';' symbol
5. Execute query
6. warning: not an error

```lua
local connection = dbConnect("sqlite", "test.db", nil, nil, "multi_statements=1;")
dbExec(connection, [[
	CREATE TABLE IF NOT EXISTS some1 (id INTEGER);
	]]
) -- warning: dbExec failed; (0) not an error
dbExec(connection, [[
	CREATE TABLE IF NOT EXISTS some1 (id INTEGER);
]]
) -- ok
dbExec(connection, [[
	CREATE TABLE IF NOT EXISTS some1 (id INTEGER)
	]]
) -- ok
```

**Version**
MTA:SA Server v1.5.8-release-20802

**Comment by Lpsd** [comment]
`multi_statements` is nothing to do with multiline Lua strings. See https://dev.mysql.com/doc/internals/en/multi-statement.html

**Comment by rifleh700** [comment]
> 
> 
> `multi_statements` is nothing to do with multiline Lua strings. See https://dev.mysql.com/doc/internals/en/multi-statement.html

U cant reproduce bug without multiline Lua string, or without multi_statements. U must use both to reproduce

**Comment by Lpsd** [comment]
First example in your code, MySQL is expecting another statement after the semicolon, due to `multi_statements` being enabled. The only thing after that is whitespace (a blank query), more specifically the TAB character.

The second example works because there's no whitespace after the semicolon.

The third example works because there's no semicolon, so MySQL isn't looking for additional statements.

**Comment by Lpsd** [comment]
> U cant reproduce bug without multiline Lua string, or without multi_statements. U must use both to reproduce

That may be the case, however there is still no inherent relationship between the two. That's a separate issue (must be clarified in your original post and title).

**Comment by Lpsd** [comment]
Actually, this isn't an issue. The return code `(0) not an error` describes this perfectly. It's not an error, you simply passed some whitespace as a statement, which it can't do anything with. Refer to my previous comment on the first example in your code.

**Comment by rifleh700** [comment]
> 
> 
> First example in your code, MySQL is expecting another statement/query after the semicolon, due to `multi_statements` being enabled. The only thing after that is whitespace (a blank query).
> 
> The second example works because there's no whitespace after the semicolon.
> 
> The third example works because there's no semicolon, so MySQL isn't looking for additional queries/statements.

seems u are right, but
```lua
dbExec(connection, "CREATE TABLE IF NOT EXISTS some1 (id INTEGER); ") -- one space, ok
dbExec(connection, "CREATE TABLE IF NOT EXISTS some1 (id INTEGER);  ") -- two spaces, warning
```

**Comment by Lpsd** [comment]
It's something within the MySQL configuration (or it's just a part of MySQL) which must allow for a single space after a statement's closing semicolon. Anything after that will be considered part of the next statement, and in the case of whitespace/blank chars, it returns status code 0.

**Comment by rifleh700** [comment]
> 
> 
> It's something within the MySQL configuration (or it's just a part of MySQL) which must allow for a single space after a statement's closing semicolon. Anything after that will be considered part of the next statement, and in the case of whitespace/blank chars, it returns status code 0.

this is a little strange. i have spent full day at this shitty warning. "not an error" doesnt say any helpful info. thx man

**Comment by Lpsd** [comment]
Status codes are usually generalized. You can probably find more information in the MySQL error/debug logs.

**Comment by rifleh700** [comment]
> 
> 
> Status codes are usually generalized. You can probably find more information in the MySQL error/debug logs.

I found it with SQLite, so i have only console and db.log with dat very helpful "not an error"
