### ISSUE TITLE
Attached players desync after reconnect

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#2127]
**Describe the bug**
Attach a player to an object, reconnect to the server, the attached player will hangs in the air. `getElementAttachedTo`/`isElementAttached` functions also don't know that the player is attached.

**To reproduce**
Steps to reproduce:
1. /start runcode
2. 
```lua
srun player = _players["NAME"]
srun object = createObject(1754, 0, 0, 3)
srun attachElements(player, object, 1, 1, 1)
````
3.
```lua
crun player = _players["NAME"]
srun getElementAttachedTo(player)
crun getElementAttachedTo(player)
srun isElementAttached(player)
crun isElementAttached(player)
```
4. Reconnect
5. Repeat step 3

**Expected behaviour**
MTA should sync attached players for new players.

**Screenshots**
https://youtu.be/alG83F9aUKM

**Version**
Client: Multi Theft Auto v1.5.8-release-20833
Server: MTA:SA Server v1.5.8-release-20802

**Additional context**
I determined that this line is responsible for this issue. If you comment out the check `pTempEntity->GetType() != CCLIENTPLAYER`, then the player will be attached for new players ([video](https://youtu.be/DZllu3eLaZ4)). But probably it was added for a reason and maybe this check make sense.
https://github.com/multitheftauto/mtasa-blue/blob/4ce9eb33595b478c47ea755555c1c9ff3a7e6098/Client/mods/deathmatch/logic/CPacketHandler.cpp#L4094

**Comment by Pirulax** [comment]
That check is really weird..
Why would it check if the element to attach is not a player?
@ccw808 You're veteran here, maybe you have an idea?

**Comment by ghost** [comment]
> Attach a player to an object

It's worth to note this also happens if you attach player to vehicle, it will give similar result. Everyone who used glue resource probably saw it, at least once.
