### ISSUE TITLE
setColPolygonHeight breaks existing scripts

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#2140]
**Describe the bug**
Before setColPolygonHeight was added, you were in a polygon if below Z 0 now it seems that the default is 0 instead of what it used to be which I guess was like -9999 this has broken various scripts (server and client)

**To reproduce**
crun mine = createColPolygon(577.974, 1013.38, 577.974, 1013.38, 800.598, 857.003, 649.925, 710.787, 386.814, 871.242)
crun setElementPosition(localPlayer, 520.16, 878.003, -38.515)
crun isElementWithinColShape(localPlayer, mine) -- returns false but used to be true
crun setColPolygonHeight(mine, -9999, 9999)
crun isElementWithinColShape(localPlayer, mine) -- returns true now

**Expected behaviour**
Correct me if I'm wrong but new features shouldn't ever break existing scripts like this does. The default shouldn't be 0 it should be whatever it was before.

**Screenshots**

**Version**
Multi Theft Auto v1.5.8-release-20836
MTA:SA Server v1.5.8-release-20833

**Additional context**
PR that must have caused this bug: https://github.com/multitheftauto/mtasa-blue/pull/1908

**Comment by ArranTuna** [comment]
Also the default isn't even 0:

Executing client-side command: mine = createColPolygon(577.974, 1013.38, 577.974, 1013.38, 800.598, 857.003, 649.925, 710.787, 386.814, 871.242)
Command executed!
Executing client-side command: getColPolygonHeight(mine)
Command results: 1.1754943508223e-38 [number], 3.4028234663853e+38 [number]

Hack fix to run on startup (30 second timer to hope that all scripts have started by then)

setTimer(function() for i, col in ipairs(getElementsByType("colshape")) do if (getColShapeType(col) == 4) then setColPolygonHeight(col, -999, 9999) end end end, 30000, 1)

**Comment by sbx320** [comment]
The default is `std::numeric_limits<float>::min()`, which is the minimum representable *positive* value for a float (hence a value just above zero). This should be `std::numeric_limits<float>::lowest()` instead (the minimum *negative*) value.

**Comment by patrikjuvonen** [comment]
Thanks for the report, fix will be in an upcoming nightly.

**Comment by Pirulax** [comment]
~~I think that refactor was done by me.~~ Didn't know `min` is the lowest positive value. Thanks.
