### ISSUE TITLE
FUI BANIDO POR MTA REASON SEM MOTIVO

### ISSUE THREAD

**Issue by BrayanYY** [multitheftauto/mtasa-blue#2147]
FUI BANIDO DE TODOS OS SERVIDOR DO MTA POR MOTIVO HW HOOFER
Eu tava online em um servidor, ausente, e quando eu voltei para o computador jogar eu tava banido em todos os servidores
ALGUEM ME AJUDA TO DESDE ONTEM SEM JOGAR

**Comment by botder** [comment]
Appeal your permanent ban on the forum (https://forum.mtasa.com/forum/180-ban-appeals/), this is the wrong place.
