### ISSUE TITLE
File watcher

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#2156]
**Is your feature request related to a problem? Please describe.**
No, just a useful feature for different applications

**Describe the solution you'd like**
Add file watcher - event triggered when something change in "resources" folder and outside.

**Describe alternatives you've considered**
/

**Additional context**
Test branch i made: https://github.com/CrosRoad95/mtasa-blue/tree/FileWatcher
How it works in practice: https://user-images.githubusercontent.com/22455534/112715298-a14d9700-8edf-11eb-80a8-0809761101d0.mp4
Lib i used: https://github.com/SpartanJ/efsw

**Comment by fresholia** [comment]
Why do we need this? Where can we use it?

**Comment by Pirulax** [comment]
It's nice, but it raises security concerns, since this way you might be able to gather all files in a directory.
So we can't really allow directory watchers, only file ones.
But other than that it seems useful. Where would you use it tho? I dont see a lot of use cases in MTA.
