### ISSUE TITLE
Cannot get in as passenger (G) inside vehicles made using engineRequestModel

### ISSUE THREAD

**Issue by SDabdlmounaim96** [multitheftauto/mtasa-blue#2166]
**Describe the bug**
Pressing G to get inside add-on vehicles created with the feature of engineRequestModel does not work

**My add-on method**
-- on client side i request new IDs and use them to replace as addon vehicles
-- i create the vehicle normally on server side and set it's elementdata for example "model", "ferrari"
-- back on client side by that previous element data trigger, i fetch the newly generated vehicle ID by that model string "ferrari" and change the vehicle model

-- all in all, everything works nicely so far, the added vehicles work fine, the only issue i faced is not being able to get in them as passenger, 

-- i did a test, while keeping my code EXACTLY as it is, and only disabling the line that changes vehicle model (setElementModel)
solves the issue, so to help the mta dev team fix this, i can HINT towards that mta thinks that server side created vehicle is now a CLIENT side created vehicle due to the model being replaced

-- TEST number 2 : instead of replacing the elementModel with one of those newly generated IDs i replace it with id 400 (landstalker) and that doesn't cause any Bugs or issues, so i assume the newly vehicle model ids generated by engineRequestModel aren't being recognized as proper vehicles !

Please paste reproduction resources (zip files) directly into this section.
-- i unfortunately didn't make any reproduction files

**Expected behaviour**
-- when i press G on server side created vehicles that have their model changed client side to a newly generated ID (using engineRequestModel) to get in as passenger normally

**Version**
- Client v1.5.8-release-20839
- Server v1.5.8-release-20802

- Windows 10

**Comment by ghost** [comment]
I have the same problem with that. when I try to enter the vehicle as a passenger it is not possible

**Comment by Pirulax** [comment]
Does this happen with client-side vehicles as well?
Eg.: `Vehicle(engineRequestModel("vehicle"), ....)`
It might be the server not accepting your `vehicle in` packet, as on the server the given door doesn't exist.

**Comment by ghost** [comment]
tested only on the server side

it's probably a bug after setElementModel

**Comment by ghost** [comment]
has this bug been fixed yet?

**Comment by gta191977649** [comment]
Nah, i also encounter this bug on the latest nightly builds 20210426, hopefully it will be resolve soon

**Comment by gta191977649** [comment]
> has this bug been fixed yet?

Nah, i also encounter this bug on the latest nightly builds 20210426, hopefully it will be resolve soon
