### ISSUE TITLE
\r\n is not appended to log when buffer is full

### ISSUE THREAD

**Issue by Dezash** [multitheftauto/mtasa-blue#2177]
**Describe the bug**
When outputting log messages of 2047 characters, the next log message does not start in a new line.

**To reproduce**

```
addCommandHandler("testlog", function()
	outputServerLog(string.rep("1", 2047))
	outputServerLog("this message will be in the same line")

	outputDebugString(string.rep("1", 2047))
	outputDebugString("this message will be in the same line")
end)
```

**Expected behaviour**
Every log message should start in a new line

**Screenshots**

![image](https://user-images.githubusercontent.com/11979849/113566248-ffcbf100-9614-11eb-926c-bd1302722e25.png)

**Version**
MTA:SA Server v1.5.8-release-20802

**Additional context**
Does not happen on Client

**Comment by patrikjuvonen** [comment]
On client we append a new line before we print the line to console or log.

On server this is not the case.

**Comment by Pirulax** [comment]
This can be fixed when we switch to C++20 and `std::format` is available.
(Since then we could just replace all the LogPrintf stuff with std::format)
