### ISSUE TITLE
getPedOccupiedVehicle() and bindKey() combinations were broken after #2123

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2183]
**Describe the bug**
Before, the bindKey() was called before any other key and wasn't added in a queue. This was changed on #2123 and brought an issue for binds on keys like "G" or "F". 

Because getPedOccupiedVehicle(player) returns true when the player starts entering a vehicle, if you bind a key to "F" and do a simple check (``if not getPedOccupiedVehicle(thePlayer) then``) the if statment will return false, when before #2123 it returned true because of the order of the key presses.

**To reproduce**
[test.zip](https://github.com/multitheftauto/mtasa-blue/files/6289962/test.zip)

```lua
-- serverside
local thePlayer = getRandomPlayer()
spawnPlayer(thePlayer, 0, 0, 3)
local veh = createVehicle(423, 3, 3, 3)

function skereCMD(thePlayer, cmd)
	if not getPedOccupiedVehicle(thePlayer) then
		outputChatBox("SKERE")
	end
end
addCommandHandler("skere", skereCMD, false, false)
bindKey(thePlayer, "F", "down", "skere")
```

How it works after r20844
1) Download and run the resource test in r20844 (clientside)
2) Try entering the vehicle, you will be able but no message chat will appear.
3) If you get far away from the vehicle (in order to not get into it) then a message will appear.

How it worked before r20844
1) Download and run the resource test in r20839 (clientside)
2) Try entering the vehicle, you will be able and a message will appear
3) Same message will appear every time you press the key, no matter if you started to enter a vehicle of not.

**Expected behaviour**
Don't break backwards compatibility, or make a way to adjust it.

For the test: The message should appear always, getting into the vehicle or not (except if you are inside the vehicle, of course).

**Video**
Disclaimer: I was on my custom server, but no resource should have been disturbing the test, and I'm pretty sure this didn't happen before.

https://youtu.be/WwwyG90V-Xw

**Version**
r20844 (clientside)

**Additional context**
I think that the changes brought with #2123 are more important that the issue with the getPedOccupiedVehicle() and the bindKey, but probably this isn't the only logical statment that was changed because of the queue added to the binds.

I don't like the idea of reverting #2123, provided that it actually does help with performance in an important amount. I suggest that getPedOccupiedVehicle() gets an extra argument so we can check if the ped is already into the car or is just entering it (and isPedInVehicle too if possible, pretty pls).

Something like:

```lua
vehicle getPedOccupiedVehicle ( ped thePed, [ bool checkEntering = true ] )
```

checkEntering will determine if the player is considered inside the vehicle while entering (true) or only when inside (false). The only other way to check this is with events.

I brought this issue up mostly because a lot of my users are having problems with some binds which do this check. ``isPedInVehicle`` is not good because it has the same issue as the getPedOccupiedVehicle() one (but it doesn't return a vehicle, which is faster).

**Comment by patrikjuvonen** [comment]
We discussed this issue briefly with @sbx320 before making the PR. He said it is an edge case and probably relatively unlikely to cause issues.

**Comment by PlatinMTA** [comment]
> We discussed this issue briefly with @sbx320 before making the PR. He said it is an edge case and probably relatively unlikely to cause issues.

Sadly it's causing issues in my server because of my implementation of certain key binds. The only way I got to hotfix it is storing data on a table after ``onPedVehicleEnter`` event or using elementdata, which is not ideal imo.

Do we have an estimated gain in performance anyway? If it's huge then I guess it's worth it, but if it's not then it could break more old resources and gamemodes that do checks like that which is really not worth it.

**Comment by patrikjuvonen** [comment]
> > We discussed this issue briefly with @sbx320 before making the PR. He said it is an edge case and probably relatively unlikely to cause issues.
> 
> Sadly it's causing issues in my server because of my implementation of certain key binds. The only way I got to hotfix it is storing data on a table after `onPedVehicleEnter` event or using elementdata, which is not ideal imo.
> 
> Do we have an estimated gain in performance anyway? If it's huge then I guess it's worth it, but if it's not then it could break more old resources and gamemodes that do checks like that which is really not worth it.

It is significant and must not be reverted. However we can look at some workaround for this use case.

**Comment by patrikjuvonen** [comment]
I'm not able to reproduce this issue with the script provided. How many binds do you have on F key?

If it doesn't work it means you have at least 2 binds on the same key, the third one won't be executed until next frame.
