### ISSUE TITLE
Serverside colshape.elementsWithin returns nil

### ISSUE THREAD

**Issue by Yamsha75** [multitheftauto/mtasa-blue#2185]
**Describe the bug**
There are three ways to get elements within colshape `col`:
- `getElementsWithinColshape(col)`
- `col:getElementsWithin()`
- `col.elementsWithin`

The third option returns `nil` on serverside. Works correctly on clientside

**To reproduce**
Code below returns `nil`
```lua
srun col=createColSphere(0,0,0,1) return col.elementsWithin
```

**Expected behaviour**
Should work correctly on serverside, just as is presented in [the wiki](https://wiki.multitheftauto.com/wiki/GetElementsWithinColShape).

**Screenshots**
None

**Version**
v1.5.8-release-20802

**Additional context**
[Conversation with @Pirulax](https://discord.com/channels/278474088903606273/667831778563719182/830473071721971793)

**Comment by Pirulax** [comment]
Fix #2186
Could you test it please?
Ping me on discord if yes.
