### ISSUE TITLE
Allow table as argument for createColPolygon

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2191]
**Is your feature request related to a problem? Please describe.**
Yeah, for now createColPolygon takes positions as seperate arguments, which is weird i guess.

**Describe the solution you'd like**
We should allow a numeric-indexed table for createColPolygon starting with third argument, why this wasn't a thing initially?
This will lead to possibility to easily create shapes with different amount of corners, current version can lead to a very long lines for function which makes it unreadable, and it doesnt allow to dynamically manage amount of corners.(we cant have f.e. table with colshapes and their corners and jus make a simple loop with createColPolygon, as some of polygons could have different amount of corners.

**Comment by Yamsha75** [comment]
You can always do something like this:
```lua
x, y = <number>, <number>
vertices = {{x=<number>, y=<number>}, ...}
local colshapePosition = Vector2(x, y) -- colshape's "center" position
local coords = {} -- colshape's zone vertices' (x, y) positions
for index, vertex in ipairs(vertices) do
    coords[index] = Vector2(vertex.x, vertex.y)
end

-- try creating the actual colshape
local colshape = createColPolygon(colshapePosition, unpack(coords))
```
Or if you dislike Vector2:
```lua
x, y = <number>, <number>
vertices = {{x=<number>, y=<number>}, ...}
local colshapePositionX, colshapePositionY = x, y -- colshape's "center" position
local coords = {} -- colshape's zone vertices' (x, y) positions
for _, vertex in ipairs(vertices) do
    table.insert(coords, vertex.x)
    table.insert(coords, vertex.y)
end

-- try creating the actual colshape
local colshape = createColPolygon(colshapePositionX, colshapePositionY, unpack(coords))
```
