### ISSUE TITLE
Add <directory src="..."/> to meta.xml

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2200]
**Is your feature request related to a problem? Please describe.**
Yeah, for now only server-side can get access to files that arent passed in meta.xml, that would allow us to add a lot of files to meta with just one line.

**Describe the solution you'd like**
We could add new tag  to meta.xml
`<directory src="..."/> `
Will include all files within directory, just like

`<file src="..."/>`

**Describe alternatives you've considered**
`<file src="folder/*"/>` maybe? Also would be cool to add
`<file src="folder/*.extension/>`

**Additional context**

> Welcome to the H.E.V. mark IV protective system, for use in hazardous environment conditions.
> High impact reactive armour activated
> Atmospheric contaminant sensors activated
> Vital sign monitoring activated
> Automatic medical systems engaged
> Defensive weapon selection system activated
> Munition level monitoring activated
> Communications interface online
> Have a very safe day!

**Comment by CrosRoad95** [comment]
it was suggested like 100 times, someone need to decide whatever this should be added, or not

**Comment by Disinterpreter** [comment]
> 
> 
> it was suggested like 100 times, someone need to decide whatever this should be added, or not

is PR exist for it?

**Comment by sbx320** [comment]
In what order would files be loaded?

**Comment by Allerek** [comment]
> In what order would files be loaded?

I guess A-Z ordering.

**Comment by LosFaul** [comment]
> 
> 
> > In what order would files be loaded?
> 
> I guess A-Z ordering.

you can't make any random order since some script files depend on other script files

**Comment by Allerek** [comment]
> > > In what order would files be loaded?
> > 
> > 
> > I guess A-Z ordering.
> 
> you can't make any random order since some script files depend on other script files

But we don't talk about script files, we talk about 'files', `<file src="/*"/>` or `<directory`
Would not include Lua files.

**Comment by LosFaul** [comment]
> 
> 
> > > > In what order would files be loaded?
> > > 
> > > 
> > > I guess A-Z ordering.
> > 
> > 
> > you can't make any random order since some script files depend on other script files
> 
> But we don't talk about script files, we talk about 'files', `<file src="/*"/>` or `<directory`
> Would not include Lua files.

that was sadly not clear enough that you only mean files ^^
i thought files were only an example

**Comment by Allerek** [comment]
> > > > > In what order would files be loaded?
> > > > 
> > > > 
> > > > I guess A-Z ordering.
> > > 
> > > 
> > > you can't make any random order since some script files depend on other script files
> > 
> > 
> > But we don't talk about script files, we talk about 'files', `<file src="/*"/>` or `<directory`
> > Would not include Lua files.
> 
> that was sadly not clear enough that you only mean files ^^
> i thought files were only an example

Nah, adding script files shouldn't be available to add with <directory> as we might include a file with other extension to be as a script, which is a Security Breach(someone may put malicious lua file saved f.e. as '.png', and since we could add it with <directory> someone might just not find it.

**Comment by Pirulax** [comment]
It would've been nicer to open this as a discussion tho.

**Comment by Allerek** [comment]
Go ahead then, #meta-directory-parser on discord maybe?
