### ISSUE TITLE
mtasa_x64-1.5.8-rc-20851-20210408.exe is broken

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#2202]
**Describe the bug**
mtasa_x64-1.5.8-rc-20851-20210408.exe introduces a crash which occurs when the server is started

**To reproduce**
Run this or the newest 64 bit server nightly and get crash.

**Expected behaviour**
Not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/253404/115427479-6a765280-a1f9-11eb-8029-c2c12e58354a.png)

Weird that 2 lines are appearing on 1 and in log it looks like: Oh nevermind that's because that thing about MTA Blue is what first appears when you start a server and it's running in a bat file so "Starting resources..." must be where it crashes.

[2021-04-20 17:54:17] Starting resources...==================================================================

**Version**
x64-1.5.8-rc-20851-20210408

**Additional context**
Uploaded 3 of the public crash dumps:

[public.zip](https://github.com/multitheftauto/mtasa-blue/files/6344957/public.zip)

**Comment by Vadya963** [comment]
6 versions have already been released

**Comment by ArranTuna** [comment]
Yes, and they all crash. Using trial and improvement I narrowed it down to 20851 being the one that introduces the unstable code.

**Comment by botder** [comment]
Please try again with 20860

**Comment by ArranTuna** [comment]
[server_1.5.8-release-20860_deathmatch64_001bc360_5_20210420_1842.rsa.zip](https://github.com/multitheftauto/mtasa-blue/files/6345224/server_1.5.8-release-20860_deathmatch64_001bc360_5_20210420_1842.rsa.zip)

20860 is broken too.

**Comment by botder** [comment]
Are you using a server module?

**Comment by ArranTuna** [comment]
I've tried disabling the module we use and that seems to stop the crash. This is the 64 bit version of ml_sockets that we use:

[ml_sockets.zip](https://github.com/multitheftauto/mtasa-blue/files/6345414/ml_sockets.zip)

**Comment by botder** [comment]
I have prepared a commit to fix this crash and it should be available in the next nightly. I am going to push it to upstream in a moment.

**Comment by ArranTuna** [comment]
New nightly works, thanks botder.
