### ISSUE TITLE
Implementing Tarantool (NoSQL DBMS) support

### ISSUE THREAD

**Issue by Disinterpreter** [multitheftauto/mtasa-blue#2208]
**Is your feature request related to a problem? Please describe.**
Yet another good DBMS, it would pretty to use instead of MongoDB(we still haven't it anyway) in MTA.

**Describe the solution you'd like**
We need document-oriented database in some case. All of exist implementations of databases in MTA only relation databases.

Advantages: 
+ a document-oriented database
+ scalable (master-slave / master-master)
+ contains lua interpreter for queries (SQL as well too)
+ spaces can be in-memory

**Describe alternatives you've considered**
MongoDB, but Tarantool is the db which works with Lua, so it would better for us.

**Additional context**
https://en.wikipedia.org/wiki/Tarantool
https://github.com/tarantool/tntcxx

**Comment by Pirulax** [comment]
Why would a document-orientated DB be useful in MTA?
Could you provide some examples?

**Comment by Disinterpreter** [comment]
> 
> 
> Why would a document-orientated DB be useful in MTA?
> Could you provide some examples?

1. Non-SQL conception (can be easier for special cases, like you can put a table with your inventory slots and take it when it need for you)
2. Map reduce (you can balancing your load between db-servers, they will be communicate between themselves) / **sharding** / **replications** (yes, it is easier than in MySQL)
3. Lua management, yes you can write something similar ["storage functions"](https://www.tarantool.io/en/doc/latest/tutorials/lua_tutorials/#insert-one-million-tuples-with-a-lua-stored-procedure) if you need a little logic in your DB.
4. It is not a replacement of MySQL, [it can work both](https://www.tarantool.io/en/doc/latest/reference/reference_rock/dbms/)
5. Faster and can store more data than it need.
6. Other cases https://www.tarantool.io/en/patterns/

For other reasons you just can take a look a difference between MySQL/PgSQL and MongoDB(The most popular DODB).

In this issue I'm not talking about MySQL is bad. I want to say, they can work together. MySQL for slow data, like storage account data; Tarantool for large and dynamic data(you can store huge lua tables there).

If we make great functions for Tarantool, it would look like below. No need difficult SQL requests anymore.
```lua
local tar = tarantool({
    host           = '127.0.0.1',
    port           = 3301,
    user           = 'gg_tester',
    password       = 'pass',
    socket_timeout = 2000,
    connect_now    = true,
})
local data, err = tar:ping()
local data, err = tar:insert('profiles', { 1, "nick 1" })
local data, err = tar:select('profiles', 'uid', 1)
local ok, err = tar:disconnect()
```

**Comment by Pirulax** [comment]
From what I can see this could be implemented as a separate module?
Also, from what I read all data resides in memory, which just won't work on client (and we have no db stuff on the client anyways), so IMHO a module would do.

**Comment by Disinterpreter** [comment]
> 
> 
> From what I can see this could be implemented as a separate module?
> Also, from what I read all data resides in memory, which just won't work on client (and we have no db stuff on the client anyways), so IMHO a module would do.

1. Yes, it is server-only
2. Why I don't do it like a module? There are two problems: Memory leaks, i can't control it; Async(is it need?), I don't know how to do it.

Anyway. Modules are good. But they're closer to for personal use right now. I want to suggest this feature not only by myself. Supporting tarantool is simpler than PgSQL, and profits for MTA higher.

**Comment by 0xCiBeR** [comment]
I mean if mysql is natively supported why not have other dbs natively supported when there is a lot of gain in supporting it.

**Comment by patrikjuvonen** [comment]
Problem is the more we add the more we need to maintain. Modules are great for this because they achieve the same things and can be maintained separately.

We already have a lot of vendor stuff that isn't being maintained properly.

MongoDB for MTA: https://github.com/mabako/luamongo-mta

**Comment by Disinterpreter** [comment]
> We already have a lot of vendor stuff that isn't being maintained properly.
> MongoDB for MTA: https://github.com/mabako/luamongo-mta

And we already have a lot of modules that isn't being maintained properly i.e https://wiki.multitheftauto.com/wiki/Modules/MTA-MySQL

Are you sure that this mongodb module can:
- compile to x64
- have async functions
- works fine with latest version of database
- works fine with latest version of MTA
- memory leaks is solved?

**Comment by patrikjuvonen** [comment]
> > We already have a lot of vendor stuff that isn't being maintained properly.
> > MongoDB for MTA: https://github.com/mabako/luamongo-mta
> 
> And we already have a lot of modules that isn't being maintained properly i.e https://wiki.multitheftauto.com/wiki/Modules/MTA-MySQL
> 
> Are you sure that this mongodb module can:
> - compile to x64
> - have async functions
> - works fine with latest version of database
> - works fine with latest version of MTA
> - memory leaks is solved?

It's dated, yes. Make a fork or write from scratch. Why add yet another system to MTA? It doesn't mean it will be maintained any more or better than a dedicated module repository. Then after a few years abandoned like the rest.

**Comment by Disinterpreter** [comment]
> It's dated, yes. Make a fork or write from scratch. Why add yet another system to MTA? It doesn't mean it will be maintained any more or better than a dedicated module repository. Then after a few years abandoned like the rest.

I tried it... I tried to make a PostgreSQL module, but I screwed up, there are few problems which I can't solve. I knew about it, but when I started I've seen it and learned. The first problem is async, the second problem is converting lua tables into understandable for C++ type. 

So, I write these issues because these features is really useful for many scripters, and I think in the first of all we decide is it need for MTA? I think it is need and not as module. Because MySQL placed into base MTA code. 


P.S. modules is really interesting topic which ask many questions for scipters and team, I suppose it should move in discussions.

**Comment by Pirulax** [comment]
Agreed module support is pretty bad. 
We should export `ArgumentParser` into the SDK, along with `CIdArray` stuff so people can actually allocate userdatas. (RN it's not really possible, because it'll break MTA)

**Comment by Disinterpreter** [comment]
I did a workaround solution(with HTTP), but it would be better to see this feature with a native support

https://forum.mtasa.com/topic/131195-tarantool-use-case-and-workaround/

**Comment by patrikjuvonen** [comment]
Use a module.
