### ISSUE TITLE
onColShapeHit sometimes isn't called for polygons

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#2211]
**Describe the bug**
If we drive the vehicle at high speed, e.g. 150+ km / h, onColShapeHit for colPolygon is not always called. For sphere, cuboid, and possibly the rest, this is not the case.

**To reproduce**
createColPolygon and drive it with high speed

**Expected behaviour**
onColShapeHit should be always called for polygons

**Screenshots**

**Version**
1.5.8

**Additional context**

**Comment by Lpsd** [comment]
Duplicate of #942
