### ISSUE TITLE
engineReplaceModel is not replacing 3D markers

### ISSUE THREAD

**Issue by TFP-dev** [multitheftauto/mtasa-blue#2213]
**Describe the bug**
Function engineReplaceModel is not replacing 3D marker model. GTA is caching marker models at address 0xC7C6DC, so replacing 3D marker model takes effect only when placing marker as normal object.

**To reproduce**
1. Use engineReplaceModel with id 1559 or 1316 or 1317.
2. Markers are not replaced if using createMarker, but they are replaced if using createObject.

**Expected behaviour**
Abbility to replace marker models.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/72511827/116620030-8d171280-a941-11eb-8298-975706f7615b.png)

![obraz](https://user-images.githubusercontent.com/72511827/116620053-97391100-a941-11eb-8b2b-20d1e6abf077.png)

**Version**

- server/client v1.5.8-release-20845

**Additional context**

**Comment by Lpsd** [comment]
Making the suggested changes could break backwards compatibility, whereby servers who are replacing those models don't expect the marker itself to change when created via createMarker (there would have to be an optional arg defaulting to false on whether to load custom marker models).

Then there's the question of whether it's even feasible (or worth it) to "fix" this. I have some doubts - and I also believe it would make more sense to solve this using Lua (make the marker invisible and put your custom model in the same position).

Personally I don't agree with changing / adding this, there's already simple enough ways to solve this using Lua.
