### ISSUE TITLE
Is there any way I can see which resource created a car or a ped?

### ISSUE THREAD

**Issue by ikaio** [multitheftauto/mtasa-blue#2214]
On my server there are a lot of mods and I don't want to look at them one by one so I would like to know

**Comment by stoneage-mta** [comment]
This is not the right place to ask this kind of question, please use the forums or discord scripting channels.

**Comment by Lpsd** [comment]
https://discord.com/invite/mtasa
https://forum.mtasa.com/forum/71-scripting/
