### ISSUE TITLE
lua special chars returns two bytes

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#2219]
**Describe the bug**
```lua
local str = 'łódka'
local sb = string.sub(str,0,1)

local sa = string.sub(str,0,2)

print(sb)
print(sa)

local bb = string.sub(str,2,3)
local ba = string.sub(str,3,4)

print(bb)
print(ba)
```
This bug is for ą,ę,ć,ś,ź,ż,ó,ł and maybe for others language

**Expected behaviour**
It should returns only normal character e.g 'ł'

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/117471881-982cfc80-af58-11eb-8162-d974e2117199.png)

**Version**
1.5.8

**Additional context**

**Comment by LosFaul** [comment]
it's not a bug
ASCII for example has only 256 characters with a single byte
so this special language characters simply don't fit into the 256 set anymore
that's why extra bytes are required for UTF formats to represent more than 256 characters

**Comment by LosFaul** [comment]
i should add that
mta has added utf api many years ago
so you can work with utf characters:
https://wiki.multitheftauto.com/wiki/Shared_Scripting_Functions#UTF8_Library

**Comment by Pirulax** [comment]
Works as expected. Lua uses ANSI C, which uses ASCII.
