### ISSUE TITLE
Disable global ban system for servers

### ISSUE THREAD

**Issue by notnorelock** [multitheftauto/mtasa-blue#2220]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As a banned permanently player & scripter at Multi Theft Auto: San Andreas, servers can disable global bans for global banned players, but if they detect injected cheat (like injected DLL or something like that), MTA would crash or shutdown.

**Additional context**
none

**Comment by stoneage-mta** [comment]
A really nice idea if you want to help cheat developers :)

**Comment by Dutchman101** [comment]
No, people that are globally banned are not welcome on MTA while they are banned.. and that's a decision from MTA (not server owners).. there are plenty of other obvious and security reasons, such as the one mentioned by iDannz.

Please don't use the bugtracker for these kind of things in the future, thanks

**Comment by Lpsd** [comment]
What a great feature! Let's make it so banned players are no longer banned, but the AC can do its original job and ban them again!

**Comment by CrosRoad95** [comment]
play sa-mp instead

**Comment by boversoneg** [comment]
no
