### ISSUE TITLE
after turning on the music in the car for after 5 seconds

### ISSUE THREAD

**Issue by gabrieldimitry** [multitheftauto/mtasa-blue#2222]
I've tried all possible ways to resolve the error

**Comment by stoneage-mta** [comment]
I'm not sure about what you mean, but I'd say it's a server-related problem. Please try to get in touch with the server staff (they should fix their scripts), and next time follow guidelines to create an issue here.

**Comment by Citizen01** [comment]
As iDannz said, contact the admins of the servers you play on, not MTA. I'm closing this issue.
If you are a scripter and you think you found a bug, reopen this issue with a code snippet we can use to reproduce the problem.
