### ISSUE TITLE
Server 1.5.9 won't support various distro's (like Debian) unless action is taken

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#2229]
**Describe the issue**
As a result of the OVH fire, we had to reconfigure our Linux build agents / relevant build server stuff from scratch.

The consequence of this is that it is not possible to use recent MTA server builds (newer than r20837 - built after 10 March, the date of OVH fire) on any Linux distribution that uses **glibc** version lower than 2.29. For instance, this means practically dropping support for Debian, as only the unreleased Debian 11 (unstable) will support the required glibc version.

You'll be faced with an error like this when trying to launch MTA server:
```
MTA:BLUE Server for MTA:SA

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /em
ul/dev2/x64/deathmatch.so)

ERROR: Loading mod (/emul/dev2/x64/deathmatch.so) failed!
Press Q to shut down the server!
```
The exact reason hasn't been properly investigated yet, but @sbx320 has said that it "might be a new symbol that needs to be added to the redef stuff" and i would guess it's the result of using the latest toolchains when reconfiguring our build server, without accounting for certain things

**Version**
- Build r20837 and newer (for readers' notice, last working Linux server build is [r20833](https://nightly.mtasa.com/multitheftauto_linux_x64-1.5.8-rc-20833.tar.gz))

**Additional context**
My personal opinion was that this should be a blocker for the release of 1.5.9 (which is pretty close), but @sbx320 has disagreed and thinks it's not a very big deal - he said `it doesn't matter if there's no day 1 linux support for 1.5.9`

I think it does matter, and it deeply concerns me that MTA would practically drop support for popular Linux distro's like Debian (as Debian 11 is unreleased.. otherwise _forcing_ everyone to upgrade) with Debian being 1 of the most popular distro's within the MTA server hosting landscape. I believe that many other distributions (and / or versions thereor) would become unsupported as well due to being bound to older glibc versions, but I don't have an overview.

MTA server should remain working out of the box on the widest amount of hosting environments as possible, as it has done for years. I am afraid it will be a huge disappointment for server owners and MTA hosting companies otherwise. Therefore, i vouch for making this issue a blocker for the release of 1.5.9, having to be resolved first.

**Comment by ccw808** [comment]
> As a result of the OVH fire, we had to reconfigure our Linux build agents / relevant build server stuff from scratch.

The backup of the Linux build agents was from before when Jusonex made modifications to fix the version issues. We could always ask Jusonex what he did

**Comment by PlatinMTA** [comment]
It should be a blocker. I do use Debian and I won't update my OS just because I can't run the latest MTA Server version. I don't think that the clients would really mind to play on a 1.5.8 server while 1.5.9 is live. I think that a lot of servers would simply not upgrade until this problem is fixed, and that would kinda defeat the purpose of realeasing a new version.

**Comment by sbx320** [comment]
This likely requires a similar fix to what I applied in https://github.com/multitheftauto/mtasa-blue/issues/943

**Comment by jushar** [comment]
The OVH build server just used a deployment of the [Dockerfile](https://github.com/multitheftauto/mtasa-blue/blob/master/Dockerfile) which uses sbx' compatibility fix.

I suppose re-building the image caused a libc/compiler update and therefore produced the error.
Consequently, I think sbx is right about the missing new symbol in the compat stuff.

So there are essentially two possible solutions:
1) Add the missing symbols (sbx documented it quite well: https://github.com/multitheftauto/mtasa-blue/tree/master/utils/compat)
2) Downgrade to the old docker image. This is probably not very easy, because I've recently deleted (the now unused) MTA acccount on DockerHub since MTA uses the GitHub container registry now.

**Comment by Dutchman101** [comment]
> It should be a blocker. I do use Debian and I won't update my OS just because I can't run the latest MTA Server version. I don't think that the clients would really mind to play on a 1.5.8 server while 1.5.9 is live. I think that a lot of servers would simply not upgrade until this problem is fixed, and that would kinda defeat the purpose of realeasing a new version.

I intend to put this issue as a blocker in 5 days, unless any other team opinions (besides sbx320's) are against it in the meanwhile, or if im told not to do that

**Comment by botder** [comment]
Buildserver agents have been updated to the latest Docker image for compiling the code.
Server revisions from 20870 (and newer) work now on older Linux distributions.

**Comment by StifflersMom** [comment]
```
$ ./mta-server64 -v
libncursesw.so.6: cannot open shared object file: No such file or directory
ERROR: Could not load ./x64/core.so
* Check installed data files.
Press enter to continue...

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

```

multitheftauto_linux_x64-1.5.8-rc-20881 on Ubuntu 18.04.5 LTS.
Ubuntu 18.04.5 LTS uses ncurses5...

**Comment by Dutchman101** [comment]
> ```
> $ ./mta-server64 -v
> libncursesw.so.6: cannot open shared object file: No such file or directory
> ERROR: Could not load ./x64/core.so
> * Check installed data files.
> Press enter to continue...
> 
> $ cat /etc/lsb-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
> ```
> 
> multitheftauto_linux_x64-1.5.8-rc-20881 on Ubuntu 18.04.5 LTS.
> Ubuntu 18.04.5 LTS uses ncurses5...

Is this a similar type of issue as this (#2229) and #2258? In that case, the build agent thingy seems to have spawned a flurry of new issues and we can't be sure none are left so easily.

Then please open a new issue on the tracker for this 'libncursesw' problem, @StifflersMom

**Comment by botder** [comment]
@StifflersMom Please try again with nightly 1.5.8-rc-20889

**Comment by Allerek** [comment]
> @StifflersMom Please try again with nightly 1.5.8-rc-20889

![image](https://user-images.githubusercontent.com/12304071/125505612-921d076f-29d5-4419-b985-0dbb24c94aa7.png)
![image](https://user-images.githubusercontent.com/12304071/125505702-ea2ccfe1-9e64-4eee-9b63-8d3c9c72d956.png)

**Comment by botder** [comment]
It should work with 20896 now.

**Comment by StifflersMom** [comment]
> 
> 
> It should work with 20896 now.

Yes, it works 👍
