### ISSUE TITLE
Can't change marker alpha for "Arrow" type

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#2230]
**Describe the bug**
You can't change the marker alpha with "arrow" marker type

**To reproduce**
Create 'arrow' marker and set alpha argument to 0

**Expected behaviour**
Alpha should working

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/119477745-85d00280-bd4f-11eb-9afd-9adfc089c8a8.png)

**Version**
1.5.8

**Additional context**

**Comment by PlatinMTA** [comment]
Duplicate of #1860
