### ISSUE TITLE
Variant Bug (Lights, Lightbars)

### ISSUE THREAD

**Issue by Whitee303** [multitheftauto/mtasa-blue#2233]
The lights on the tow truck do not synchronize. The point is, sometimes they work and sometimes they don't. After Restart - Works... (Variants) 
The problem is also that the lightbar works for others and not for you

https://imgur.com/gJ1HR8S
Works after restart

**Comment by Allerek** [comment]
Looks like resource problem to me

**Comment by Lpsd** [comment]
Please use the scripting channels on our community Discord or forum to investigate the issue with your code. 

Also, please use the issue template in future, it's there for a reason - this is not a valid issue.
