### ISSUE TITLE
Forum Ban Resulting in System Wide Server Ban

### ISSUE THREAD

**Issue by IcantThinkOfAnymoreNames** [multitheftauto/mtasa-blue#2236]
**Describe the bug**
I was banned from your forum by Dutchman for trying to report bugs there. I have been on MTA for years and understandably have used many accounts to help improve this community.

**To reproduce**
Go to Fourm
Attempt to report Bugs
Get harassed by Dutchman
Receive many trumped up warnings about things that exist only in his mind.
Receive multiple forum bans for no legitimate reasoning, that is never appealable to someone who isn't Dutchman, making this an autocracy.
Lose faith in MTA and return to FiveM where adults are running the show.

**Expected behaviour**
I expected a rational process where grievances do not hold hostage 5 years of my work, or access to my own independent server based community, on a single person's judgement, personally deriding insults, and systemically unaccountable behavior.

**Screenshots**
none

**Version**
101

**Additional context**
You have a tough job. That is made worse by exaggerating the facts to favor your own actions. I am not a disrupter, and when you disagree with me, you do so against the facts. Like spelling behavior with u, it isn't all about you. You are a Professional, and should never abuse your power, over people who are just trying to help.

Remove my server ban, I have never once done anything to deserve this.

And in all cases you will not hear from me again. I am done trying to help MTA. And like the dozen GTA-mps before you, When you get so bad you are unusable, I'll go somewhere else, I'll make their system better. I will not post on mta forum ever again.

"Disconnected: You were Kicked by #AC4 - UNACCEPTABLE FORUM BEHAVIOR - XABACHE / MTAUSER"

**Comment by AlexTMjugador** [comment]
GitHub Issues is not for appealing bans. If you're trying to appeal a global MTA, follow [these instructions](https://forum.mtasa.com/topic/116414-ban-appeals-information-how-to-appeal-your-global-ban/).

**Comment by IcantThinkOfAnymoreNames** [comment]
I am not appealing the ban, I am reporting a bug as the title evidences more so than the post. Pardon this oversight. Thank you for requesting greater context. Your forum ban, for "unacceptable" forum behavior, has extended system wide. Your forum ban, is a system wide ban. This seems like an error to me.

Could you explain why a forum ban is a system wide ban please?

**Comment by PlatinMTA** [comment]
🧂🧂🧂

Please go to the forum post and follow the instructions, is not that hard. This place is for reporting actual bugs and features, so other developers (voluntarily) can work on them.

**Comment by IcantThinkOfAnymoreNames** [comment]
Thank you for the information, I did do that. This is also not at all what this dicussion is about.

I am not appealing a forum ban. End of that discussion.

Why is a "Forum ban" system wide? This is a system question. Is this a bug, or a feature?

**Comment by PlatinMTA** [comment]
The answer is on that post.

**Comment by IcantThinkOfAnymoreNames** [comment]
I did not see this, could you provide more context please.

**Comment by IcantThinkOfAnymoreNames** [comment]
You did not answer my question....

Unrelated to my forum ban.

Speaking in general.

Is a forum ban, a system wide MTA all services ban? Is this a purposeful feature, or a bug?

**Comment by Lpsd** [comment]
Your system wide MTA ban is intentional
