### ISSUE TITLE
Github posts are being locked without resolution of the bug being discussed.

### ISSUE THREAD

**Issue by IcantThinkOfAnymoreNames** [multitheftauto/mtasa-blue#2238]
Your system wide MTA ban is intentional

_Originally posted by @Lpsd in https://github.com/multitheftauto/mtasa-blue/issues/2236#issuecomment-850729680_

From an MTA system operations perspective, (and again NOT trying to appeal an individual forum ban) Could you explain the logic or reasoning behind a forum ban, being applied to my own personal MTA server?

Is this meant to be a form of punitive payback? I have allegedly harmed your forum, and you want to exercise your system wide and therefore godlike power over me? Is this the intent of a forum ban, being applied system wide? Are you trying to rule by fear?

Re:
https://forum.mtasa.com/topic/131057-ac-4-error-not-detecting-trainer-false-positive-detecting-old-nvidia-drivers/
https://github.com/multitheftauto/mtasa-blue/issues/2236
https://github.com/multitheftauto/mtasa-blue/issues/2237

The GitHub deleter appears to be https://github.com/Lpsd

**Comment by Lpsd** [comment]
No, GitHub is not for ban related discussion, in any capacity.
