### ISSUE TITLE
I am being personally harassed by Lpsd

### ISSUE THREAD

**Issue by IcantThinkOfAnymoreNames** [multitheftauto/mtasa-blue#2240]
<div class="timeline-comment-header clearfix d-block d-sm-flex" style="box-sizing: border-box; display: flex; align-items: center; padding-right: 16px; padding-left: 16px; color: var(--color-text-secondary); flex-direction: row-reverse; background-color: var(--color-bg-tertiary); border-bottom: 1px solid var(--color-border-primary); border-top-left-radius: 6px; border-top-right-radius: 6px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><h3 class="timeline-comment-header-text f5 text-normal" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1px; font-size: 14px !important; font-weight: 400 !important; min-width: 0px; padding-top: 8px; padding-bottom: 8px; flex: 1 1 auto;"><strong class="css-truncate" style="box-sizing: border-box; font-weight: 600;"><a class="author Link--primary css-truncate-target width-fit" show_full_name="false" data-hovercard-type="user" data-hovercard-url="/users/Lpsd/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/Lpsd" style="box-sizing: border-box; background-color: initial; color: var(--color-text-secondary); text-decoration: none; max-width: 125px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: inline-block; vertical-align: top;">Lpsd</a><span>&nbsp;</span></strong>commented<span>&nbsp;</span><a href="https://github.com/multitheftauto/mtasa-blue/issues/2239#issuecomment-850734769" id="issuecomment-850734769-permalink" class="Link--secondary js-timestamp" style="box-sizing: border-box; background-color: initial; color: var(--color-text-secondary) !important; text-decoration: none;"><relative-time datetime="2021-05-29T00:24:54Z" class="no-wrap" title="May 28, 2021, 5:24 PM MST" style="box-sizing: border-box; white-space: nowrap !important;">2 minutes ago</relative-time></a><span class="js-comment-edit-history" style="box-sizing: border-box;"></span></h3></div><div class="edit-comment-hide" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><task-lists disabled="" sortable="" style="box-sizing: border-box;">holy shit, what is wrong with you</task-lists></div>

--
The above statment is a personally insulting slander. 

I came here to report a system bug with mta, and I have received nothing but personally motivated insults.

Would it not be easier to answer my issue, and follow up if questions continue?

Re:
https://github.com/multitheftauto/mtasa-blue/issues/2236
https://github.com/multitheftauto/mtasa-blue/issues/2237
https://github.com/multitheftauto/mtasa-blue/issues/2238

**Comment by Lpsd** [comment]
![jebaited](https://user-images.githubusercontent.com/40902730/120052542-b8168400-c01d-11eb-8ecf-ed0a2d643f6b.png)
