### ISSUE TITLE
Github conversations are being locked by LPSD

### ISSUE THREAD

**Issue by IcantThinkOfAnymoreNames** [multitheftauto/mtasa-blue#2241]
Seems like you have enough bugs to deal with today. I will leave you to resolve them in due time. And report this entire event to 10k uniques a month on FiveM until resolved.

Re:
https://github.com/multitheftauto/mtasa-blue/issues/2236
https://github.com/multitheftauto/mtasa-blue/issues/2237
https://github.com/multitheftauto/mtasa-blue/issues/2238
https://github.com/multitheftauto/mtasa-blue/issues/2240

Have a nice day.

**Comment by turret001** [comment]
Thank you, have a great day.
