### ISSUE TITLE
getValidPedModels

### ISSUE THREAD

**Issue by ShuffleGTAO** [multitheftauto/mtasa-blue#2242]
Hi, i found a problem with getValidPedModels, this return that model id 273 is valid, but is not valid. This this does not exists.

**Comment by Lpsd** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp#L175-L181

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Server/mods/deathmatch/logic/CPlayerManager.cpp#L323-L329

yikes, i'm sure we can come up with something better than this 😄

**Comment by Pirulax** [comment]
> yikes, i'm sure we can come up with something better than this 😄

probably a static array?

**Comment by ShuffleGTAO** [comment]
Yes, its a table and table.insert in this table, next i'm check by if that models which i choose is in table, if it is then return false, so where is problem?

**Comment by Lpsd** [comment]
> Yes, its a table and table.insert in this table, next i'm check by if that models which i choose is in table, if it is then return false, so where is problem?

we're talking about the MTA code for the `getValidPedModels` function, not your scripts.

**Comment by ShuffleGTAO** [comment]
Yes, so i talking about this function how i use her..so i'm asking where is problem with this function that returns bad model?

**Comment by Lpsd** [comment]
`getValidPedModels` does not return 273. This is a problem with your scripts.

Please use the scripting channels on the MTA discord to get help with your scripts.

https://mtasa.com/discord
