### ISSUE TITLE
Change GetValidPedModels to use a static array

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#2244]
Transferred from #2242 - the original "issue" was incorrect (getValidPedModels does not return 273 as claimed), however the MTA code still made me sigh.

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp#L175-L181

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Server/mods/deathmatch/logic/CPlayerManager.cpp#L323-L329

As suggested by @Pirulax, we should probably use a static array instead.

**Comment by patrikjuvonen** [comment]
@Lpsd Is this still relevant?

**Comment by Lpsd** [comment]
@patrikjuvonen no, looks like it was resolved in other commits above

**Comment by patrikjuvonen** [comment]
> @patrikjuvonen no, looks like it was resolved in other commits above

Ok thanks!
