### ISSUE TITLE
Player dont get a damage from fire

### ISSUE THREAD

**Issue by nikitafloy** [multitheftauto/mtasa-blue#2252]
**Describe the bug**
I dont get a damage when player on fire.

**To reproduce**
1. Drop molotov
2. Run on fire

**Expected behaviour**
I must to loose health

**Version**
Multi Theft Auto v1.5.8-release-20845

**Additional context**
Code, which i removed and fixed error:

```lua
addEventHandler("onClientRender", getRootElement(), function()
        for k, player in ipairs(getElementsByType("player")) do
            if getElementHealth(player) >= 1 then
                local width, height = guiGetScreenSize()
                local lx, ly, lz = getWorldFromScreenPosition(width / 2, height / 2, 10)
                setPedLookAt(player, lx, ly, lz)
            end
        end
    end
)`

**Comment by Pirulax** [comment]
yeah `setPedLookAt` does some weird stuff, I remember someone saying it has issues.

**Comment by PlatinMTA** [comment]
> **Describe the bug**
> I dont get a damage when player on fire.
> 
> **To reproduce**
> 
> 1. Drop molotov
> 2. Run on fire
> 
> **Expected behaviour**
> I must to loose health
> 
> **Version**
> Multi Theft Auto v1.5.8-release-20845
> 
> **Additional context**
> Code, which i removed and fixed error:
> 
> ```lua
> addEventHandler("onClientRender", getRootElement(), function()
>         for k, player in ipairs(getElementsByType("player")) do
>             if getElementHealth(player) >= 1 then
>                 local width, height = guiGetScreenSize()
>                 local lx, ly, lz = getWorldFromScreenPosition(width / 2, height / 2, 10)
>                 setPedLookAt(player, lx, ly, lz)
>             end
>         end
>     end
> )`
> ```

The workarround is to not call ``setPedLookAt`` every frame, do it every 2nd, 3rd or even 4th or 5th frame.

**Comment by Lpsd** [comment]
> The workarround is to not call `setPedLookAt` every frame, do it every 2nd, 3rd or even 4th or 5th frame.

I'm assuming this still cancels fire damage on the frames it's called, effectively slowing the damage?

**Comment by Lpsd** [comment]
Also, with `setElementBoneRotation` you can implement your own version of `setPedLookAt`. Not sure what the performance implications of that are though.

**Comment by StrixG** [comment]
Duplicate of #626
