### ISSUE TITLE
MTA:SA for Android 

### ISSUE THREAD

**Issue by alycardinal** [multitheftauto/mtasa-blue#2256]
**Hello, MTA:SA developers!**

**I'm a very big fan of yours!** Recently I started trying to develop a port of your multiplayer on an Android device ( https://gitlab.com/alycardinal/home-846/-/tree/master/4b25dc61bb30ff6101a5e24f8e8e5a63 ) The main menu is already almost completely developed, the game is patched and even a small protection is made. So please, I count on your help in developing this project, however, not so long ago I ran into some problems that prevent me from connecting to PC servers, I tried to recreate network module ( https://gitlab.com/alycardinal/mtasa-network-module-android ), but I, as I said earlier, have problems with this. Could you somehow contribute to the possibility of connecting to your servers with Android, for example, to make your library with a network module that can be used to connect to PC servers? 

**Thank you in advance for your answer.**

**screenshots:**
https://ibb.co/RPW2LMc
https://ibb.co/z6kNWp4

**Comment by ffsPLASMA** [comment]
Can you show us a video of android client connecting and playing on local (android) server?

**Comment by alycardinal** [comment]
> Can you show us a video of android client connecting and playing on local (android) server?

I kind of already wrote that I have problems with this, only debug cleared singleplayer is available with gui & other functions/patches. You can see the source code, the link I gave above. There you can see the full scope of the work done.

https://ibb.co/MNDxxHw

**Comment by Lpsd** [comment]
While this is cool, it's not the correct place. This has very little relation to the mtasa-blue repo code wise - it's a separate project, in essence.

If you have any questions about MTA's networking or need help with the code base then head over to our development Discord: https://discord.gg/GNN6PRtTnu
