### ISSUE TITLE
requestBrowserDomain window has clipping text

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#2257]
**Describe the bug**
Window from ``requestBrowserDomain`` function is to small for some languages (e.g Polish), because labels are clipped.

**To reproduce**

**Expected behaviour**
The window should automatically fit the text

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/121014602-7367b700-c79a-11eb-82dd-967b0b155a17.png)

**Version**
1.5.8

**Additional context**

**Comment by Pirulax** [comment]
IIRC there is a wordwrap attribute for labels. Perhaps we could make the window taller, and enable wordwrap?
