### ISSUE TITLE
Simplify MTA Server files/folders locations

### ISSUE THREAD

**Issue by LVRENT** [multitheftauto/mtasa-blue#2266]
**Is your feature request related to a problem? Please describe.**
MTA has its own structure related to the files used on the server (and I'm speaking strictly on Windows). To reach the "resources" folder, it's a long-way, somehow. We need to go to the SERVER/mods/deathmatch/resources.

**Describe the solution you'd like**
If there's nothing to block a change like this, it will be nice to simplify the files and folders paths to be more close to the server "root" folder. An example of path I think of: "SERVER/resources/". More short. Yeah, it will override with the root files like "core.dll", "MTA Server.exe" and so on, but they won't be replaced by the files in the "deathmatch" folder.

**Describe alternatives you've considered**
I use (like maybe many of us) a shortcut to the "resources" folder,  to do changes to my gamemode.

**Additional context**
This change is only related to the file locations. This may include some changes to the source on how these files operate with each other but I don't think it will be too hard. Also, if there are any conflicting issues with this one, tell me and I will close it.

**Comment by Lpsd** [comment]
Use a symbolic link - we aren't going to change the whole structure of MTA server folders.
