### ISSUE TITLE
Some capital (e.g. cyrillic) letters don't work in CEF

### ISSUE THREAD

**Issue by nanky187** [multitheftauto/mtasa-blue#2270]
**Describe the bug**

Capital Latin letters do not work in CEF-drawed input fields.

**To reproduce**

1. Create an example input field with "text" type.
2. Try typing a Capital Latin letters like(ĄŚĘĆÓŁ).

**Expected behaviour**

Capital Latin letters should be presented.

**Screenshots**

None

**Version**

1.5.8

**Additional context**

None

**Comment by Dutchman101** [comment]
Please be more specific than "1.5.8" about the build, would be nice if you can try reproduce with both of these:

1) [https://nightly.mtasa.com/mtasa-1.5.8-rc-20845-20210323.exe](https://nightly.mtasa.com/mtasa-1.5.8-rc-20845-20210323.exe)
2) [https://nightly.mtasa.com/mtasa-1.5.8-rc-20881-20210619.exe](https://nightly.mtasa.com/mtasa-1.5.8-rc-20881-20210619.exe)

@nanky187

**Comment by nanky187** [comment]
I reproduced it on both and both don't work.
This problem also occurs in older builds.

**Comment by Dutchman101** [comment]
> I reproduced it on both and both don't work.
> This problem also occurs in older builds.

Ok, thanks for checking
