### ISSUE TITLE
toggleControl next_weapon and previous_weapon takes sniper zoom with Q and A!

### ISSUE THREAD

**Issue by mihayy5** [multitheftauto/mtasa-blue#2275]
**Describe the bug**
Toggling *next_weapon* and *previous_weapon* controls off will also toggle sniper zoom off with Q and A keys!
*Note: Mouse wheel will still zoom in/out
next_weapon = zoom_in **&** previous_weapon = zoom_out*

**To reproduce**
1. toggleControls off.
2. Take sniper.
3. Press Q or A to zoom in/out.
4. Doesn't work.

**Expected behaviour**
Expected to zoom in or out depending on the key.

**Version**
Latest version from the MTA website: 1.5.8
Server: 1.5.8-9.20881.0
Client: v1.5.8-release-20881

**Comment by androksi** [comment]
I can confirm the issue.

**Comment by Allerek** [comment]
Its most likely due to this check
https://github.com/multitheftauto/mtasa-blue/blob/70272f9a91f3217963239df55ca103f8dff4b566/Client/core/CKeyBinds.cpp#L1249
I'll check more about that later today.

**Comment by ghost** [comment]
If i recall correctly disabling jump won't let you zoom as well when holding LSHIFT.

**Comment by Allerek** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/70272f9a91f3217963239df55ca103f8dff4b566/Client/core/CKeyBinds.cpp#L1325

^If we set the breakpoint here, with `if` statement to break only 
"if action == ZOOM_IN"
and try to press Q, it wont break for some reason(breaks on if action == PREVIOUS_WEAPON). It looks like GTA Hardcoded 'NEXT/PREVIOUS Weapon' to ZOOM_IN/OUT. 

Maybe we should make an IF statement with checking if player is using scope/zoom? Share your opinions.

**Comment by mihayy5** [comment]
I'm not used to cpp, but in the line you shared there is this check that checks 

if (action == action) 

But where does actually 'action' get defined ?

**Comment by Allerek** [comment]
> I'm not used to cpp, but in the line you shared there is this check that checks
> 
> if (action == action)
> 
> But where does actually 'action' get defined ?

`pTemp` is temporary pointer to they keyBind that holds the same action as main key that was pressed, so `->action` is its action, and 

`action` is action of original key
https://github.com/multitheftauto/mtasa-blue/blob/70272f9a91f3217963239df55ca103f8dff4b566/Client/core/CKeyBinds.cpp#L1315

So this `if` statement is literally:
`if temporaryKey have same action as action then proceed`

**Comment by lopezloo** [comment]
After 4a4bcbc413ad33b56acd7284c81361187c7df8d6 it's no longer possible to control zoom using `next_weapon` / `previous_weapon` binds.
