### ISSUE TITLE
onClientElementInteriorChange is triggered even if the element has not changed its interior

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#2280]
**Describe the bug**
As the title says, the `onClientElementInteriorChange` event is triggered even if the element has not changed its interior.

**To reproduce**
Steps to reproduce:
1. Type `/debugscript 3`
2. Start runcode
3. `crun setElementPosition(me, 0, 0, 3)`
4. `crun addEventHandler("onClientElementInteriorChange", root, function(oldInterior, newInterior) iprint(source, oldInterior, newInterior) end)`
5. `crun vehicle = createVehicle(411, 1, 0, 3)`
5.1. Nothing in the debug console
5.2. `crun setElementInterior(vehicle, 0)`
5.3. Output: `elem:vehicle[Infernus]14ED1BC8    0    0` - the old and the new interior are the same
6. `crun createPed(22, 1, 0, 3)`
6.1. Output: `elem:ped[22]2DE24EB0    0    0` - the debug console shows that the element has changed its interior, although we just created it

**Expected behaviour**
The event should not be triggered.

**Version**
Client: Multi Theft Auto v1.5.8-release-20887

**Comment by Lpsd** [comment]
cc @Patrick2562

**Comment by Allerek** [comment]
Well, its not that big of a problem, it should be left, maybe someone will get a good use of it?
May be confusing for some people debugging code, that that event should be triggered(as the function is called), but it isn't.(Regarding the fact that we could mention that on wiki)

**Comment by patrikjuvonen** [comment]
I think we should just avoid sending the event if the old and new interior are same. Nothing more special than that is needed.

**Comment by patrikjuvonen** [comment]
cc @Patrick2562
