### ISSUE TITLE
how to edit mta versions ant other

### ISSUE THREAD

**Issue by moriokii** [multitheftauto/mtasa-blue#2281]
how to edit mta versions and other like MTA_DM_BUILDTAG_SHORT

**Comment by Dutchman101** [comment]
Please don't use the issue tracker for anything outside of its purposes (like bug reports). If you have questions like that, you can go to the [MTA development discord](http://discord.gg/GNN6PRtTnu), the [MTA discord](http://discord.gg/mtasa) or [Open Source Contributors subforum](https://forum.mtasa.com/forum/107-open-source-contributors/).
