### ISSUE TITLE
Vehicles explode only after they get streamed-in for the client

### ISSUE THREAD

**Issue by bum8hj** [multitheftauto/mtasa-blue#2294]
**Describe the bug**
_Not a really good description, but..._
When a streamed-out vehicle explodes, it does not explode for your client until you get close to the vehicle and it streams in - then will the vehicle actually explode and `onClientVehicleExplode` gets triggered.
Edit: _I think this description doesn't go well with the steps below, idk how else to explain it, lmao_

**To reproduce**
Steps to reproduce the behaviour:
1. start a server and start the `play` resource
2. download and start [this resource](https://github.com/multitheftauto/mtasa-blue/files/6940223/explosionbug.zip) `explosionbug`
3. wait for the vehicle to explode, then press G
4. wait for the chatbox message, then press H
5. repeat 3-4 if you want to

**Expected behaviour**
Not sure to be honest, but the vehicle shouldn't explode when it gets streamed in, since the explosion should have already happened when your player was out of the vehicle's stream distance (if that makes sense).

**Video**
https://i.imgur.com/BSPgmyK.mp4

**Version**
v1.5.8-release-20912 _(client & server)_

**Additional context**
~~I'm guessing it has to do with [this commit](https://github.com/multitheftauto/mtasa-blue/commit/8b30d7a4e43e6460a8203bb89b7133365a3e6a85), but I'm not sure.~~

**Comment by botder** [comment]
> since the explosion should have already happened when your player was out of the vehicle's stream distance (if that makes sense)

If there is nobody syncing the vehicle explosion, should it be marked as exploded immediately or should the server wait for a little while before doing so?

Edit: The referenced commit is not related, it was about vehicles still exploding after being fixed.

**Comment by bum8hj** [comment]
> If there is nobody syncing the vehicle explosion, should it be marked as exploded immediately or should the server wait for a little while before doing so?

Maybe immediately – and when it gets streamed-in (a player starts syncing it?) it would just show the blown vehicle model without an explosion.
However, `onClientVehicleExplosion` won't trigger then, so I don't think that's a good idea.

**Comment by ApeLsiN4eG** [comment]
Better description:

1. Vehicle explodes but doesn't respawn. When it gets streamed-out and then streamed-in - the blown vehicle (with blown model) blows up with no explosion again (with camera shaking and "animation"). Repeat indefinitely. Not a big problem for real.
2. Vehicle explodes (doesn't matter if it is streamed-in or streamed-out) and respawns while streamed-out. When it gets streamed-in, it shows up on fire, even on respawn (https://youtu.be/Rmv2EJfS-O0). He didn't mention it. That's how we noticed that bug. It also may cause some weird situations (https://youtu.be/G6lZ1GYdmO8, watch from 0:25).
3. Vehicle explodes and respawns, both while streamed-in. Everything is ok.

I am not a developer, but I think it is related to #2102. Kinda sus.
