### ISSUE TITLE
Add on(Client)ElementDataRemoved

### ISSUE THREAD

**Issue by fresholia** [multitheftauto/mtasa-blue#2297]
**Is your feature request related to a problem? Please describe.**
OnClientElementDataChange trigger does not work when removeElementData is used.

**Describe the solution you'd like**
Let's add a new event called on(Client)ElementDataRemoved.

**Describe alternatives you've considered**
Maybe existing event (onElementDataChange) should be triggered as 'false'

**Comment by theSarrum** [comment]
I can't reproduce. Code:
```lua
start runcode
crun addEventHandler(localPlayer and "onClientElementDataChange" or "onElementDataChange", root, function(...) iprint(eventName, source, ...) end)
srun addEventHandler(localPlayer and "onClientElementDataChange" or "onElementDataChange", root, function(...) iprint(eventName, source, ...) end)
srun setElementData(me, "key", 1)
srun removeElementData(me, "key")
```

Result:
```
INFO: "onClientElementDataChange"    elem:player[#EB0C0CSarrum]    "key"    nil    1
INFO: "onElementDataChange"          elem:player[#EB0C0CSarrum]    "key"    nil    1
INFO: "onClientElementDataChange"    elem:player[#EB0C0CSarrum]    "key"    1    nil
INFO: "onElementDataChange"          elem:player[#EB0C0CSarrum]    "key"    1    nil
```

**Comment by Lpsd** [comment]
@cleoppa Please can you confirm if you're still able to reproduce the issue using the example code above?

If not, then please provide your own code to reproduce the issue.
