### ISSUE TITLE
Bug(?) with triggerClientEvent

### ISSUE THREAD

**Issue by ShuffleCodes** [multitheftauto/mtasa-blue#2299]
Hi, i dont know that is bug but...

triggerClientEvent dont work. For example

SERVER SIDE

for _,v in ipairs(getElementsByType("player"))do
    triggerClientEvent("test",v)
end

CLIENT SIDE

addEvent("test",true)
addEventHandler("test",root,function()
    print("Test")
end)

And in debugscript 3 appears to me : "Server triggered clientside event test, but event is not added clientside"

In meta everything is good. I add that this problem is in all resources, not in only this.

**Comment by botder** [comment]
You have to wait for the resources to start on the client for it to work.
You can either guess when it happens or send a triggerServerEvent to tell the serverside that the client resource for a player has started.
See #2150 (**Add onPlayerResourceStart event**)
