### ISSUE TITLE
Add callback arguments to encodeString

### ISSUE THREAD

**Issue by Shuubaru** [multitheftauto/mtasa-blue#2303]
**Is your feature request related to a problem? Please describe.**

Currently, we cannot provide extra arguments to callback function in **encodeString** and since this function is called asynchronously when a callback function is provided, we cannot, for example, save the callback content into a file with certain name if we are processing multiple files with different size. Small files will be simply processed faster than bigger ones.

**Describe the solution you'd like**
Please, let us to parse extra arguments to the callback function. Or simply make callback functions to process in queue instead of asynchronously, just like latent events, so we can at least make a table to match every call.

**Describe alternatives you've considered**
Probably sorting files by size before encoding them might do the job, but to be honest I'm not sure if that would work out since I have not tested it.

**Additional context**
nada

**Comment by ghost** [comment]
Duplicate of #1705

**Comment by Shuubaru** [comment]
> Duplicate of #1705

Oh sorry, i actually search it beforehand but i couldnt find that topic.
