### ISSUE TITLE
Add setPedBleeding

### ISSUE THREAD

**Issue by ThomasNightfire** [multitheftauto/mtasa-blue#2306]
Add a two functions for ped bleeding (blood paddles creating around ped) like in singleplayer

- bool setPedBleeding(ped ped, bool bleed)
- bool isPedBleeding(ped ped)

**Comment by Fernando-A-Rocha** [comment]
Could allow making invisible peds with no collisions and making them bleed to create blood pools?

**Comment by patrikjuvonen** [comment]
~There doesn't seem to be a built-in feature for this (someone correct me if I'm wrong)~, however you can use the existing [fxAddBlood](https://wiki.multitheftauto.com/wiki/FxAddBlood) function to continuously splatter around blood, and if we add https://github.com/multitheftauto/mtasa-blue/pull/1003, we can create the blood pools too.

EDIT: And wrong I was indeed, @StrixG found a missing ped flag for bleeding 🙂

**Comment by patrikjuvonen** [comment]
And wrong I was indeed, @StrixG found a missing ped flag for bleeding 🙂
