### ISSUE TITLE
Large file can't loaded by fileOpen() on client side

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#2311]
**Describe the bug**
Hello, I'm trying to read IMG over 1.0 GB on the client by using function `engineLoadIMGContainer` provided by [@thisdp ](https://wiki.multitheftauto.com/wiki/EngineLoadIMGContainer),  the client is unable to load the file always returned 0 even I just trying to read the first 10 bytes of the file, initially, I thought it might be related to the limitation of 32bit (since we had that in SA engine), however, I try to load it with the 32bit of MTA server, it worked smoothly, thus I think it might be a bug related to the client.

**Screenshots**
![image](https://user-images.githubusercontent.com/2988235/129932428-9a51e7cb-2f3a-48ae-9248-14b628f7640c.png)

`fileOpen()` & `fileGetSize()` load in `32bit MTA-Server`
![image](https://user-images.githubusercontent.com/2988235/129932259-e1cd3d9d-75a2-461b-bcd5-ee2a51cd90e9.png)
however if we switch the same code to the `client`
![image](https://user-images.githubusercontent.com/2988235/129932789-0da19661-670a-4feb-9575-7c7d1f8ce6da.png)

**Version**

Using `MTASA-1.5.8-rc-20927-20210818`

**Comment by ffsPLASMA** [comment]
I guess its a hardcoded limit within MTA. Take a look here: https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp

DEFAULT_MAX_FILESIZE is defined as 52428800 which get used for fileCreate and fileOpen to check for file size. You could try to increase the limit and see if it fixes the problem.

**Comment by Pirulax** [comment]
Why is there a limit though.. In `fileOpen`.. Sounds really unreasonable.

**Comment by thisdp** [comment]
> I guess its a hardcoded limit within MTA. Take a look here: https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> 
> DEFAULT_MAX_FILESIZE is defined as 52428800 which get used for fileCreate and fileOpen to check for file size. You could try to increase the limit and see if it fixes the problem.

DEFAULT_MAX_FILESIZE seems to be https://wiki.multitheftauto.com/wiki/FileSetPos

**Comment by ffsPLASMA** [comment]
> 
> 
> > I guess its a hardcoded limit within MTA. Take a look here: https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> > DEFAULT_MAX_FILESIZE is defined as 52428800 which get used for fileCreate and fileOpen to check for file size. You could try to increase the limit and see if it fixes the problem.
> 
> DEFAULT_MAX_FILESIZE seems to be https://wiki.multitheftauto.com/wiki/FileSetPos

Yep youre right. Maybe there are some client only checks in CScriptFile class since they are not identical between client and server.
This kinda looks "suspicious" though its a dead end, at least for us https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/mods/deathmatch/logic/CScriptFile.cpp#L37

**Comment by Lpsd** [comment]
This definition should be moved elsewhere so it can be accessed globally (for example, this value was needed in the SVG PR, however I had to copy the value instead of being able to use it directly).

We should be able to increase this with no problem. Maybe ~2GB for client (or dynamic based on memory available for MTA?), more for server.... thinking ~8GB?

**Comment by zo3n** [comment]
What about a Lua function to set our own max size?

**Comment by Lpsd** [comment]
> What about a Lua function to set our own max size?

The only way I can see that being useful is for sandboxing scripts once the default filesize limit is increased (for example, in a multi-gamemode environment, so the script doesn't try loading a huge file to freeze the client/server).

**Comment by AlexTMjugador** [comment]
> Why is there a limit though.. In `fileOpen`.. Sounds really unreasonable.

I second this question. Files are usually not meant or expected to be memory-mapped or entirely loaded to main memory, so the only practical concern should be running out of file descriptors (i.e. exceeding the maximum number of open files the OS allows), not out of address space. Why does this limit exist in the first place?

~~Edit: I'm thinking that maybe the limit could have something to do with a way to prevent race conditions (i.e. security reasons), but anyway to me the proper way to do so is to use file locks, which are mandatory in Windows.~~

Edit 2: screw that, I don't see how limiting file size may meaningfully prevent relevant race conditions from happening.

**Comment by Lpsd** [comment]
"Why?" does not have an answer unless you can dig up the dev back in ~200X who added this arbitrary limit.

as I said, we can *probably* increase this without any worry, however our file implementation needs reviewing as a whole (briefly discussed on the MTA dev discord), so we should probably open another issue to address that.

**Comment by thisdp** [comment]
> "Why?" does not have an answer unless you can dig up the dev back in ~200X who added this arbitrary limit.
> 
> as I said, we can _probably_ increase this without any worry, however our file implementation needs reviewing as a whole (briefly discussed on the MTA dev discord), so we should probably open another issue to address that.

Actually, fileOpen works, but fileRead always return an empty string when the file is large ( maybe 1.5GB ). And "DEFAULT_MAX_FILESIZE" is not regarded as max file size, it should be explained as "Max Position Larger Than Current File Size". I compiled a custom build, everything works fine.

**Comment by thisdp** [comment]
The issue was not about fileRead, it is because the MTA Server doesn't send the large file to the client. This issue should be closed.

**Comment by gta191977649** [comment]
It's due to the MTA gives up to transfer file that exceeded certain size, I've tested again, if i manually moved the img into the client cache and it works, i'll close this issue by now.
