### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by Abasalt-yar** [multitheftauto/mtasa-blue#2318]
**Additional context**
I'm wondering if it's possible to add support for MongoDB because sometimes using another database may be good in some circumstances

**Comment by dmi7ry** [comment]
https://github.com/multitheftauto/mtasa-blue/issues/2208

**Comment by Lpsd** [comment]
btw -> https://github.com/mabako/luamongo-mta

**Comment by Abasalt-yar** [comment]
> btw -> https://github.com/mabako/luamongo-mta

that's for almost 9 years ago, 
Is it ok with these? 
https://github.com/multitheftauto/mtasa-blue/issues/2208#issuecomment-850836740

**Comment by patrikjuvonen** [comment]
Use a module.
