### ISSUE TITLE
Add on(Client)TickCount event

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2321]
Hi,

My idea a new event: on(Client)TickCount
This is a great event to skip unnecessary timers.

Example:
```
local currentTick = getTickCount()
local tick1, tick2 = currentTick, currentTick
addEventHandler("onClientTickCount", root, function(currentTick)
  if currentTick-tick1 > 2000 then
   print("2 seconds passed do something")
   tick1 = currentTick
 end
  if currentTick-tick2 > 5000 then
    print("5 seconds passed do something else")
    tick2 = currentTick
  end
end)
```

**Comment by PlatinMTA** [comment]
onClientRender executes every new frame, I don't think we need more (or can do more) than that.

```lua
local tickTarget = getTickCount()+2000
local fpsCount = 0
addEventHandler("onClientRender", root, function()
    fpsCount = fpsCount + 1
    
    local tick = getTickCount()
    if tick > tickTarget then
        print("fuck yeah 2 whole seconds passed and", fpsCount, "frames have been rendered since then")
        tickTarget = tick+2000
        fpsCount = 0
    end
end)
```

**Comment by Lpsd** [comment]
yeah this is completely unnecessary when we already have onClientRender

**Comment by Xenius97** [comment]
OnClientRender triggers 30-60 times per second.
OnClientTick triggers 1 times / sec. :)

**Comment by PlatinMTA** [comment]
The title is misleading then, it should be something like ``onClientSecond`` or something like that. Eitherway I don't think it's worth it considering you can already do that with ``onClientRender`` and the performance hit should be minimal (having it on C won't help at all for this kind of operation afaik).

**Comment by Lpsd** [comment]
this is still invalid when you can use setTimer with a 1ms, or 1s repetition, for quite some time now.

I know your original issue mentioned "not using unnecessary timers" - but can you tell us why using a timer (example below) would be bad for you?

```lua
setTimer(function()
    iprint("hey look, I'm triggering once per second!", getTickCount())
end, 1000, 0)

setTimer(function()
    iprint("hey look, I'm triggering once per milisecond!", getTickCount())
end, 1, 0)
```

**Comment by Pirulax** [comment]
Timers would be way faster than using our shit event system.
