### ISSUE TITLE
Server: Set 32-bit modules directory to "x86/modules"

### ISSUE THREAD

**Issue by LVRENT** [multitheftauto/mtasa-blue#2322]
**Is your feature request related to a problem? Please describe.**
A idea for the next major release is to move the 32-bit server modules to "x86/modules" for better file arrangement and a clearer structure to the files we can modify in the "deathmatch" folder.
The x86 modules are placed under "mods/deathmatch" folder.
The x64 modules are placed under "x64/modules" (root folder).
The thing with the "do that in 1.6" is because 1.6 is a backwards-incompatible release and it won't break the 1.5 scripts or structure.

**Describe the solution you'd like**
Move the modules from "mods/deathmatch" to "x86/modules".
Why? I think as it was possible to do it with the x64 modules (I understand why), it is possible to do that with the x86's too.

The x64 files were moved in the [1.5 update](https://wiki.multitheftauto.com/wiki/Changes_in_1.5) as following:
**Server: Bugfixes & Changes
Set 64 bit modules directory to "x64/modules"**

**Describe alternatives you've considered**
There aren't, but it isn't a problem too.

**Comment by fresholia** [comment]
If we want better file path we need to delete the "mods/deathmatch" path completely

**Comment by Disinterpreter** [comment]
That is an interesting issue.
Theoretically we can port mta-server to new architecture like arm64 (and I think we have to do it in future), so different classifications have sense.

**Comment by Allerek** [comment]
Yeah, whole MTA folders structure should be reworked. "mods/deatchmatch" is leftover from old versions. I'll try to create graphical interpretation of how should it look today.

**Comment by LVRENT** [comment]
I actually tried to open an issue some months ago about reworking the entire file path system but Lpsd said me I can use symbolic links instead: #2266; If he isn't ok with that, at least let's rework the module paths.

**Comment by patrikjuvonen** [comment]
It's not just "directory naming", we need to get rid of the whole "mod" context.
