### ISSUE TITLE
createBrowser error

### ISSUE THREAD

**Issue by nikitafloy** [multitheftauto/mtasa-blue#2329]
**Describe the bug**
when i change browser size from 0, 0 to 1, 1 (relative) and 1, 1 to 1, 1 - i get this error

**To reproduce**
I use this code for hide/show browser, because this is faster, than creating&loading methods.
And yes, it consumes memory...

```lua
addEventHandler('onClientResourceStart', resourceRoot, function ()
    if not guiBrowser then
        guiBrowser = guiCreateBrowser(0, 0, 1, 1, true, true, true)
    end
    
    browser = guiGetBrowser(guiBrowser)
    
    addEventHandler("onClientBrowserCreated", browser, function()
        loadBrowserURL(source, "http://mta/local/html/index.html")
        guiSetSize(guiBrowser, 0, 0, true)
        addEventHandler("onClientBrowserDocumentReady", browser, function ()
            bindKey('F3', 'down', function ()
                if show then
                    show = false
                    guiSetSize(guiBrowser, 0, 0, true)
                end
            end)
        end)
    end)
end)
```

**Screenshots**
https://imgur.com/fhCxl7H

**Version**
[ { "number": 344, "netcode": 474, "name": "MTA:SA Client", "sortable": "1.5.8-9.20927.0", "mta": "1.5.8", "type": "Release", "os": "Windows", "tag": "1.5.8-release-20927" } ]

[ { "number": 344, "netcode": 474, "name": "MTA:SA Server", "sortable": "1.5.8-9.20927.0", "mta": "1.5.8", "type": "Release", "os": "Windows", "tag": "1.5.8-release-20927" } ] 

**Additional context**
I think this is a bug.
The browser was expected to resize without errors.
Initially, I thought that the problem was in the JS code, but even on the simplest example, the MTA crashes.

**Comment by Lpsd** [comment]
Thanks for the report, will need testing to confirm - but this should be fixed.

However, you shouldn't be resizing a browser to 0, 0 in order to hide it (this shouldn't be possible) - use `guiSetVisible` instead.
