### ISSUE TITLE
Add 3 missing ped skin

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2338]
Hello,

I've found 3 missing skins. These skins are in the default game but they are not added to MTA. (OG Loc Burger and another burger guy and a man in purple clothes)

I'm attaching screenshots.
![Screenshot_20210904-205910_YouTube](https://user-images.githubusercontent.com/6568348/132105339-e5f808d7-7052-4e18-bb7d-c56ec72d9cec.jpg)
![Screenshot_20210904-205805_YouTube](https://user-images.githubusercontent.com/6568348/132105343-280b256f-c657-44a4-8ecb-299faff6f88b.jpg)
![Screenshot_20210904-205750_YouTube](https://user-images.githubusercontent.com/6568348/132105344-62ddb977-3a0d-451d-826e-16951824b4bb.jpg)
![Screenshot_20210904-205734_YouTube](https://user-images.githubusercontent.com/6568348/132105345-10e93d27-f4ae-4307-a3b5-bd0679048a0c.jpg)

**Comment by MegadreamsBE** [comment]
Those are cutscene peds. They are not compatible with existing peds as they have a lot more bones. They are actually objects with animations applied to them.

**Comment by patrikjuvonen** [comment]
Here's a rough list (probably inaccurate) of what those cutscene skins look like

![skins](https://user-images.githubusercontent.com/22572159/132106277-4b87417d-23f0-40bb-b406-b16007a4750d.png)

**Comment by patrikjuvonen** [comment]
You can find a lot of these fixed cutscene models and skins online, for example: https://www.gtagarage.com/mods/show.php?id=25755
