### ISSUE TITLE
i cannot join or host any server, it just says that im kicked out always.

### ISSUE THREAD

**Issue by rokspass** [multitheftauto/mtasa-blue#2339]
**Describe the bug**

**To reproduce**

**Expected behaviour**

**Screenshots**

**Version**

**Additional context**

**Comment by rokspass** [comment]
.

**Comment by rokspass** [comment]
please help

**Comment by MegadreamsBE** [comment]
This is much more appropriate for the Discord server (https://discord.gg/mtasa #help-support channel). This is not directly related to MTA's codebase nor did you actually even bother to give any information.
