### ISSUE TITLE
MTA HIS NOT BEEN INSTALLED PROPERLY, PLEASE REINSTALL

### ISSUE THREAD

**Issue by paduzika** [multitheftauto/mtasa-blue#2341]
meu mta esta com esse erro a mais de 1 ano, ja tentei muita coisa ja fui atras de virus atualizei drivers e nada resolve por favor alguem que puder ajudar sobre isso

**Comment by MegadreamsBE** [comment]
This is much more appropriate for the Discord server (https://discord.gg/mtasa #help-support channel). This is not directly related to MTA's codebase. Please don't see the issues section on Github as being a support section. It is not...
