### ISSUE TITLE
Can't disable wind sounds without changing interior

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2346]
**Describe the bug**
If you try to disable wind sounds without setting interior it will be not disabled. It wil be only disabled after change interior.

**To reproduce**
```
crun setAmbientSoundEnabled("general", false) setWorldSoundEnabled(0, 0, false) setWorldSoundEnabled(0, 29, false) setWorldSoundEnabled(0, 30, false)

crun setAmbientSoundEnabled("general", true) setWorldSoundEnabled(0, 0, true) setWorldSoundEnabled(0, 29, true) setWorldSoundEnabled(0, 30, true)
```

**Video**
*****

**Version**
Multi Theft Auto v1.5.8-release-20938

**Comment by botder** [comment]
You can cancel the sound immediately since 1.5.5-9.11860, see
https://wiki.multitheftauto.com/wiki/SetWorldSoundEnabled
```
setWorldSoundEnabled(0, 0, false, true)
setWorldSoundEnabled(0, 29, false, true)
setWorldSoundEnabled(0, 30, false, true)
```
