### ISSUE TITLE
Interiors lack radio

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#2349]
**Describe the bug**
Some interiors in SA has defined audio zones, some of these zones are supposed to play radio. It doesn't work in MTA.

**To reproduce**
Go to Binco interior:
`
run me.position = Vector3(208.942, -102.377, 1005.258) me.interior = 15
`

**Expected behaviour**
Radio in interiors (ex. Binco) should play like it does in single player.

**Video**
http://youtu.be/qonn6DDIK8w

**Version**
Multi Theft Auto v1.5.8-release-20927

**Additional context**
MTA mess with radio somehow, there are NOPs present which disables it and it affects interior radios too.

Additionaly, if player teleports straight from interior which has background sound (but not radio) to interior which has radio defined, the sound from previous interior doesn't stop.

Kinda moved from https://bugs.multitheftauto.com/view.php?id=8565
There was patch for it: #22
From what I remember the issue with this patch was that it was also changing the last vehicle radio station ID, so if player left such interior and entered vehicle, the radio would be turned off by default. It could be fixed by actually playing radio but not saving station ID.

**Comment by patrikjuvonen** [comment]
See also #423
