### ISSUE TITLE
Disableable bullet impact force on vehicles

### ISSUE THREAD

**Issue by ThatG-I** [multitheftauto/mtasa-blue#2356]
**Is your feature request related to a problem? Please describe.**
When the game is running at high FPS(100) the physics calculations are abit wonky. When a custom weapon shoots and hits a vehicle, the impact force of the bullet has behond doubled. So, it throws the car around like a toy.

When running the physics at the correct FPS(35) then when a bullet impacts the vehicle it pushes the vehicles down a very very tiny bit. This is like the og game.

**Describe the solution you'd like**
I want to be able to disable the bullet impact force on vehicles. So, that when the game is running at high FPS it don't throw the car around everywhere.

**Describe alternatives you've considered**
I've solved this problem, but it's horrible. I've had to make my own horrible hitreg system to deal with this problem.

The hitreg system uses the LOD object of the vehicle and attaches it to the vehicle. I disabled the weapon damage for vehicles and I only allowed it to hit the LOD then I pass on the damage to the vehicle. 

The problem with this hacky solution is that it also creates many more new problems. Attaching the LOD object to the vehicles, when they Collide with each other it drops the FPS a fair amount and also does some weird physics calculations where it throws you around somtimes. So, to deal with this problem I had to use [SetElementCollidableWith](https://wiki.multitheftauto.com/wiki/SetElementCollidableWith) in the [OnClientVehicleCollision](https://wiki.multitheftauto.com/wiki/OnClientVehicleCollision) event to remove the collisions of the vehicle with the LOD object etc and then cache the ones that has already hit.

This horrible solution could be solved by just having the bullet impact forces on vehicles disableable.

**Additional context**
[OnClientVehicleDamage](https://wiki.multitheftauto.com/wiki/OnClientVehicleDamage) is the closest I found relating to anything to do with physical damage, so I'm assuming this might be related to the bullet impact. I don't know.

**Comment by Einheit-101** [comment]
Duplicate of 
https://github.com/multitheftauto/mtasa-blue/issues/1346

**Comment by lopezloo** [comment]
Duplicate of #1346
