### ISSUE TITLE
Banimento de contas no MTA.

### ISSUE THREAD

**Issue by thebestofsh4rk** [multitheftauto/mtasa-blue#2358]
Uma coisa recorrente que torna a experiência de jogo um lixo! Esse app da ban na MÁQUINA, ao invés de banir a conta do USUÁRIO INFRATOR. Esse sistema é completamente errado, visto que ao banir a máquina, vários outros players que jogam corretamente ficam impossibilitados de jogar na lan house. Uma lan house é frequentada por n usuários, se o usuário fez algo incorreto no game, ele deve ser banido, não à máquina!

**Comment by botder** [comment]
It's technically impossible to ban a specific human from MTA - we can only issue machine bans. If you still want to appeal a **permanent** machine ban, do it in the forum: https://forum.mtasa.com/forum/180-ban-appeals/
