### ISSUE TITLE
Saber quem cometeu infração de banimento.

### ISSUE THREAD

**Issue by thebestofsh4rk** [multitheftauto/mtasa-blue#2360]
No atual sistema MTA não é possível saber quem efetuou infração de banimento, visto que pega o nome do programa instalado na máquina ao invés de pegar a conta com login e senha do usuário infrator. Sem isso não é possível localizar o infrator para aplicar medida punitiva. Exemplo: Aqui está aparecendo  "kaio1706", mas se eu mudar o nome, vai aparecer o nome que eu colocar nas opções, não aparece o login da pessoa que tomou o ban. Aqui no caso o cara pode logar na lan house, ser banido e colocar qualquer outro nome aleatório em opções que vai parecer que aquela pessoa cometeu à infração.

**Comment by MegadreamsBE** [comment]
It is not technically possible (and if so, would be anti-privacy) to allow for servers to track banned individuals rather than the pc they have used. This was already pointed out in another issue earlier. Please don't misuse Github issues for stuff like this...
