### ISSUE TITLE
Add isClientReady

### ISSUE THREAD

**Issue by fresholia** [multitheftauto/mtasa-blue#2362]
**Is your feature request related to a problem? Please describe.**
Checks whether the clientside of the system is loaded on the client in requests sent from the server to the player.

**Describe the solution you'd like**
Scripts can be written more interactively by adding such a function and event.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ghost** [comment]
Wait for #2150 or use createElement + setElementParent on player: https://github.com/srslyyyy/custom-data/blob/main/custom_data/SElementData.lua#L331 - later use this parent instead of root/check whether player belong to it.

**Comment by patrikjuvonen** [comment]
So client would only be ready if no client-side scripts are being loaded?

**Comment by Lpsd** [comment]
This wouldn't work.

I join a sever - I'm not marked as ready by `isClientReady` until every resource has started.... but how did we work out what "every resource" is?

Nevermind - now all the resources have started and I'm marked as "ready".

But what about when another resource gets started? Suddenly I'm not "ready" anymore whilst that resource is loading, even though I was just confirmed to be "ready" moments ago.

Also, out of curiosity, what was your desired use-case for something like this?

**Comment by PlatinMTA** [comment]
> Also, out of curiosity, what was your desired use-case for something like this?

The only use case I can find is for something like this:

```lua
function doSomething(thePlayer)
    if not isClientReady(thePlayer) then
        return false
    end
    -- do things
    return true
end
```

Obviously you have better ways to do this, I could think of a table that has for keys the clients that loaded, so you only check ``lua
if table[client] then``, but idk maybe a C implementation could be sligthly faster.

**Comment by Lpsd** [comment]
Closing since it can be resolved through #2150 - which is already merged.

**Comment by fresholia** [comment]
Thanks for PR @Lpsd! ^-^

```lua
local resourceLoadedPlayers = {}

function isClientReady(player)
    return resourceLoadedPlayers[player]
end

addEventHandler("onPlayerResourceStart", root,
    function(resource)
        if resource == getThisResource() then
            resourceLoadedPlayers[source] = true
        end
    end
)
```

**Comment by PlatinMTA** [comment]
Remember to clean the value onQuit.

```lua

addEventHandler("onPlayerQuit", root,
    function()
        resourceLoadedPlayers[source] = nil
    end
)
```
