### ISSUE TITLE
Get rid of all dxDrawText arguments

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#2363]
**Is your feature request related to a problem? Please describe.**
Too many arguments

**Describe the solution you'd like**
make option to create some style userdata to pass it into dxDrawText class
pseudocode:
```
style = createStyle({ fontSize: 10 })
dxDrawText("tete", style)
```

**Describe alternatives you've considered**
No alternative

**Additional context**
For years this function grown in amount of arguments, this function keep getting harder and harder to use.
Also this amount of checks cause function to be slower as well

**Comment by Inder00** [comment]
I want it

**Comment by Allerek** [comment]
This would also allow to split arguments in few lines, which is cool and more readable.

**Comment by Vadya963** [comment]
it would be even cooler if it was like this
dxDrawText("tete", { fontSize: 10 })

**Comment by CrosRoad95** [comment]
> it would be even cooler if it was like this
> dxDrawText("tete", { fontSize: 10 })

no, because "createStyle" would return userdata for faster access for c++

**Comment by PlatinMTA** [comment]
Does this kill backwards compatibility or its just a more efficent way to run dxDrawText? If it's the latter I like this idea, but if it's the former then I'm against it.

What I mean with a more efficent way to run dxDrawText is that you have this way, with styles, and another way which is the current one.

Seeing that draw functions are really slow we should try to get the most of it as possible. The real rn alternative is using renderTargets, which can improve the performance a lot and are pretty simple to implement, but they also have some sidedowns.

**Comment by CrosRoad95** [comment]
> Does this kill backwards compatibility or its just a more efficent way to run dxDrawText? If it's the latter I like this idea, but if it's the former then I'm against it.
> 
> What I mean with a more efficent way to run dxDrawText is that you have this way, with styles, and another way which is the current one.
> 
> Seeing that draw functions are really slow we should try to get the most of it as possible. The real rn alternative is using renderTargets, which can improve the performance a lot and are pretty simple to implement, but they also have some sidedowns.

my approach with userdata at second argument is easy to make compatibile with older versions, it also make it faster due you already keep in memory all properties you want

**Comment by Inder00** [comment]
@CrosRoad95 make a pull request to that

**Comment by wicky-r** [comment]
(might be a bad idea)
I think, a get (maybe with set) function would be great for custom UI scripts or other stuff. So, it can be useful more.

```lua
var getStyleValue(userdata style, string key = "*")
bool setStyleValue(userdata style, string key, var value)

--[[
  if the `key` parameter is `*`, get function will return the style as a table<object> with all data in it
  So, people can save the styles to a file with some more code lines
]]
```

```lua
-- in some custom ui script
function initializeComponentStyle(self, style)
     self.title_font_size  = getStyleValue(style, "fontSize")
     self.background_color = getStyleValue(style, "color")
end

function windowCreate(style)
     local self = {}

     initializeComponentStyle(self, style)
     ...
end
```
(The function name might be bad, sorry i'm bad in naming)

**Comment by Pirulax** [comment]
I dont think we want this.
All this adds extra run time penalty.

Theres an extension for VSC with MTA function syntax, use that + function argument labels.
Sadly this isn't Python with named arguments.
