### ISSUE TITLE
"onPlayerVehicleEnter" gets triggered when a serverside ped enters the vehicle

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2367]
**Describe the bug**
onPlayerVehicleEnter triggers when a ped is warped inside a vehicle.

**To reproduce**
```lua
function onStart()
    local ped = createPed(178, 0, 0, 3)
    local veh = createVehicle(411, 2, 2, 3)
    
    warpPedIntoVehicle(ped, veh)
end
addEventHandler("onResourceStart", resourceRoot, onStart)

function onVehicleEnter()
    print(getElementType(source), "entered the vehicle")
end
addEventHandler("onPlayerVehicleEnter", root, onVehicleEnter)

```

**Expected behaviour**
Only players should trigger that event

**Version**
Server: r20739

**Additional context**
Didn't test on newer versions, didn't test making the ped enter a normal way

**Comment by Zangomangu** [comment]
20739 is 10 months old (I believe it's the initial 1.5.8 release)

This has been fixed in #1748 so can be closed
