### ISSUE TITLE
Objects set to unbreakable in map file still break

### ISSUE THREAD

**Issue by R4ven47** [multitheftauto/mtasa-blue#2370]
**Describe the bug**
- Objects set to breakable="false" in map remain breakable (hay boxes, object ID 996, object ID 3280 and many more)

**To Reproduce**
- Set any of the objects I mentioned above to breakable="false"

**Expected behavior**
- Objects become unbreakable and do not fall apart after a heavy weight passes on them

**Screenshots**

**Version**
- 1.5.8 stable

**Comment by Vadya963** [comment]
you can use this function engineSetModelPhysicalPropertiesGroup and set the value to 0 for the model
