### ISSUE TITLE
Server crashing by kicking player using triggerLatentServerEvent

### ISSUE THREAD

**Issue by Xyrusek** [multitheftauto/mtasa-blue#2386]
**Describe the bug**
Server is crashing, while you use triggerLatentServerEvent to kick player in event "onClientRender".
Edit: not only in "onClientRender" event, also in command handlers from client.

**To reproduce**
1. Start resource "testResource"
2. Use command /kickme
3. Wait 5 seconds, and server will crash in moment you will be kicked
[testResource.zip](https://github.com/multitheftauto/mtasa-blue/files/7261035/testResource.zip)

**Expected behaviour**
Kicking player without server crash.

**Version**
Client: v1.5.8-release-20957
Server: v1.5.8-release-20957
Platform: Windows 10

**Comment by Inder00** [comment]
Xyrusek is a hecker!

**Comment by MegadreamsBE** [comment]
> Xyrusek is a hecker!

No idea how this is relevant.

Either way I cannot reproduce this issue using the given test resource on Windows 10 running MTA nightly 20995.

**Comment by botder** [comment]
Can't reproduce in a Debug build.

**Comment by PlatinMTA** [comment]
I did have a similar problem a while back #1134

This certanly happens, but it's inconsistent. In my case it did happen twice while restarting a resource that sended a lot of latent events, both ways.

**Comment by theSarrum** [comment]
I was able to reproduce the issue with x64 windows server.

**Comment by MegadreamsBE** [comment]
> I was able to reproduce the issue with x64 windows server.

Which version?

**Comment by Xyrusek** [comment]
Maybe version without "onClientRender" will be helpfull(case I described as edit in "Describe the bug").
1. Start resource "testResource2"
2. Use command /kickme <reason>
[testResource2.zip](https://github.com/multitheftauto/mtasa-blue/files/7261782/testResource2.zip)

**Comment by theSarrum** [comment]
> Which version?

r20995. Also tested on 20668 and the same issue.
