### ISSUE TITLE
Use Modified GTA:SA Files button is missing in some cases.

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2387]
**Describe the bug**
This button is sometimes missing from menu, it returns if you modify certain files

**To reproduce**
If you decide to modify some .txd(like hud.txd) button is not visible, sometimes you can even replace models and it wont be visible. Sometimes it causes .dff to load when joining server, but .txd remains blank.

**Expected behaviour**
Always be there? Just in case

**Screenshots**
![image](https://user-images.githubusercontent.com/12304071/135496254-011a17ab-a945-46b2-a9fb-87b1d61b14ff.png)
![image](https://user-images.githubusercontent.com/12304071/135496274-7d873fbe-eab1-478e-a882-6e6ffa8c8225.png)

**Version**
Multi Theft Auto v1.5.8-release-20957

**Additional Context**
It sometimes appears if you modify `data` folder.

**Comment by Dutchman101** [comment]
The checkbox only applies to certain GTA data files, that can impact game balance/fair play. If those files are modded and you don't enable the checkbox, MTA will try to bypass the mods (so you won't feel their effects - as if your GTA wasn't modded) as far compatibility goes.. the more intrusive your mods are, the less likely it'll work out. 

Either way, some of the GTA data files to which this system applies are listed at [https://wiki.multitheftauto.com/wiki/Anti-cheat_guide#.3Cclient_file_name.3D.22data.2Fcarmods.dat.22_verify.3D.220.22.2F.3E](https://wiki.multitheftauto.com/wiki/Anti-cheat_guide#.3Cclient_file_name.3D.22data.2Fcarmods.dat.22_verify.3D.220.22.2F.3E), you can see that makes it an opt-in system (server decides if it wants to take the risk of abuse associated with certain mods) and is why you can't join 99% of MTA servers if you modded files to which it applies, and enabled the checkbox to use modified GTA files. But for the earlier mentioned reason, if you leave it disabled, most likely you'll be able to join everywhere.

> The checkbox only applies to certain GTA data files

So this is expected..
