### ISSUE TITLE
Client side bindKey command triggers server side too

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2390]
**Describe the bug**
If a client side command is bounded to key, it will be executed in server side too. If you use callback in bindKey function it will work, but you can't change keybind in MTA Settings.

**To reproduce**
[test.zip](https://github.com/multitheftauto/mtasa-blue/files/7264690/test.zip)

**Expected behaviour**
If command is only client side, doesn't trigger server. Or add an argument to bindKey, to disable triggering serverside.

**Screenshots**
![image](https://user-images.githubusercontent.com/6568348/135575713-76e8a023-b080-4e70-84dd-d3348e719570.png)

**Version**
Multi Theft Auto v1.5.8-release-20995

**Comment by Inder00** [comment]
Its not bug Its feature

**Comment by Lpsd** [comment]
This doesn’t actually appear to be an issue. The command isn’t triggered serverside - onPlayerCommand just lets you know what command was executed by a player, regardless of if it’s client or server (or even internal).

You can even deduce which side the command was executed on, by checking if it’s a registered server command - if not, then it’s client (or internal).
