### ISSUE TITLE
setCameraShakeLevel(0)

### ISSUE THREAD

**Issue by LiraGamer** [multitheftauto/mtasa-blue#2394]
**Describe the bug**
After using setCameraShakeLevel, when returning to level zero, it continues to shake this is clearly a bug of the function

**To reproduce**
client side

block execute from timer .. 

if datat.hunger <= 35 and getCameraShakeLevel() == 0 then
    setCameraShakeLevel(150);
elseif datat.hunger > 35 and getCameraShakeLevel() > 0 then
    setCameraShakeLevel(0);
end

**Version**
last version client and server

**Comment by Lpsd** [comment]
ignoring the `datat.hunger` checks (which should not be part of your code example), you have a logic issue.

Please provide a more consistent and reproducible code snippet that doesn’t include random variables / checks that we’re unable to run ourselves (as we don’t know what the value of that variable should be).

We’re also missing context of when this code snippet is ran - in a command handler? In a render event? Please clarify.

Here’s a good example of code to reproduce the potential issue:

```lua
addCommandHandler("shake", function()
    setCameraShakeLevel(getCameraShakeLevel() == 0 and 150 or 0)
end)
```

this will toggle the shake level between 0 and 150 when the command is used

**Comment by Lpsd** [comment]
As mentioned earlier this is appears to be an issue with your code - I'm unable to reproduce using the example code above. Please visit our [Discord](https://discord.gg/mtasa) scripting channel if you need further help.
