### ISSUE TITLE
Could not use dbConnect with MySQL on Ubuntu 16.04

### ISSUE THREAD

**Issue by Daemant** [multitheftauto/mtasa-blue#2396]
**Describe the bug**
When I try to use dbConnect with MySQL server, it raises an error:
```
[21-10-02 14:31:38] ERROR: Could not load /opt/server/x64/dbconmy.so - libssl.so.1.1: cannot open shared object file: No such file or directory
[21-10-02 14:31:38] WARNING: [system]/mysql/server.luac:27: Bad usage @ 'dbConnect' [Could not connect]
```
This error is rased on every MySQL connection - local and remote, not encrypted, and I think encrypted too.
I tried to do system `apt upgrade`, but last available version of openssl for 16.04 is `OpenSSL 1.0.2g  1 Mar 2016`, which provides only `libssl.so.1.0.0`.

**Version**
Tested on builds 21002, 20929 and 20833.
21002 and 20929 have the same error. 20833 works correctly.
Tested on Ubuntu 16.04, 18.04 and 20.04. The bug reproduces only on 16.04.

**Additional context**
Maybe it associated with some MySQL lib update, because there is one more change I noticed between 20833 and 20929 behaviour: the newer build uses `utf8` as the default connection charset, when older uses `latin1` (or maybe system-provided).

**Comment by patrikjuvonen** [comment]
Without having troubleshooted this myself yet, have you considered upgrading your Ubuntu version?

It is not necessarily in our best interest to support older versions of particular distributions even if we would be able to do it somehow.

**Comment by Inder00** [comment]
Install libssl-dev and openssl

**Comment by Dutchman101** [comment]
Just like issue #2229 and #2258, this is caused by rebuilding our Linux agent after the OVH fire.. 

But the question about whether or not its worth fixing remains, as using such an old distribution version in 2021 is bad practice.

**Comment by Daemant** [comment]
> Without having troubleshooted this myself yet, have you considered upgrading your Ubuntu version?

Yes, update is considered, but have not done yet.

> Install libssl-dev and openssl

They are already the "newest" for 16.04:
`libssl-dev is already the newest version (1.0.2g-1ubuntu4.20).`
`openssl is already the newest version (1.0.2g-1ubuntu4.20).`

**Comment by sbx320** [comment]
Given that support for 16.04 ended in April, I don't think we should bother supporting it any further either.
