### ISSUE TITLE
Issue with camera target after 1.5.9 release

### ISSUE THREAD

**Issue by R4ven47** [multitheftauto/mtasa-blue#2402]
**Describe the bug**
Removing a player from a vehicle then warping them to a very far away vehicle causes camera to be stuck on the initial one instead of the camera being set on the new vehicle.
Please note that this happens randomly, and that the ped gets warped to a different dimension and a custom map in that dimension as well. The ped's dimension is set beforehand, so is the vehicle's.

**Expected behaviour**
Camera moving along with the ped when being warped to the farther vehicle, as it was the case before the 1.5.9 release.

**Screenshots**
![image](https://user-images.githubusercontent.com/70843164/136276367-4361a635-71e9-43ac-89b5-3cc3697007b2.png)
![image](https://user-images.githubusercontent.com/70843164/136276387-cb69c3bc-d769-46b5-90a9-4e205f018707.png)

**Comment by botder** [comment]
Since you didn't include the MTA client version in your issue description, you should try the latest [MTA nightly](https://nightly.mtasa.com/mtasa-1.5.9-rc-21006-20211005.exe). Revision 21003 includes a fix.

**Comment by R4ven47** [comment]
> Since you didn't include the MTA client version in your issue description, you should try the latest [MTA nightly](https://nightly.mtasa.com/mtasa-1.5.9-rc-21006-20211005.exe). Revision 21003 includes a fix.

I've mentioned that it is 1.5.9, the one that was dropped for everybody as an update, Specifically 1.5.9 9.21002.0
NOTE: Provided more specific details after a conversation with botder in Discord, issue persists even with 21003, 21005 and 21006.

**Comment by TheNormalnij** [comment]
[CClientPed::WarpIntoVehicle](https://github.com/multitheftauto/mtasa-blue/pull/1753/files#diff-25862afc0e3088d4619017944046a0d75c9a75a9ffbdb666216bb3a9478453fdL1463-L1465)
I think this changes should be reverted.

**Comment by lopezloo** [comment]
Reproduction:
```
run veh = Vehicle(411, 0, 0, 5)
run me:warpIntoVehicle(veh)
run veh2 = Vehicle(411, -2404.000, -598.000, 132.648)
run me:warpIntoVehicle(veh2)
```
