### ISSUE TITLE
setVehicleDummyPosition bug on "light_front_second" dummy

### ISSUE THREAD

**Issue by SDabdlmounaim96** [multitheftauto/mtasa-blue#2405]
pretty self explanatory from the image, when changing the dummy position of "light_front_main" which is "headlights" in the dff, it changes normally and correctly, 

but the problem shows up when trying to change "light_front_second" position, which is "headlights2" in the dff, it changes the dummy position, but forgets to change the position of it's clone on the other side ( mirror on the X axis )

![bug report light](https://user-images.githubusercontent.com/74945954/136643865-e3680a42-8d68-460c-8693-b9ad126ae0dd.png)

**Comment by patrikjuvonen** [comment]
cc @botder
