### ISSUE TITLE
engineResetModelLODDistance on some non existent models causes client crash

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#2416]
**Describe the bug**
engineResetModelLODDistance on some non existent models causes client crash

**To reproduce**

crun engineResetModelLODDistance(20000)

**Expected behaviour**

no crash :)

**Screenshots**

**Version**

Version = 1.5.9-release-21005.0.000

**Additional context**

**Comment by patrikjuvonen** [comment]
See #837, #446, and #299

**Comment by Fernando-A-Rocha** [comment]
can be closed ^ :)

**Comment by patrikjuvonen** [comment]
Continue at #837
