### ISSUE TITLE
I have warning number 4 AC why this happened and I want to

### ISSUE THREAD

**Issue by ASWWEA** [multitheftauto/mtasa-blue#2425]
**Describe the bug**

**To reproduce**

**Expected behaviour**

**Screenshots**

**Version**

**Additional context**

**Comment by ASWWEA** [comment]
I have warning number 4 AC why this happened and I want to

**Comment by ASWWEA** [comment]
man ban I became

**Comment by patrikjuvonen** [comment]
Hello,

This GitHub repository is only for development matters.

Please visit our forums at https://forum.mtasa.com/forum/180-ban-appeals/ to appeal your ban.
