### ISSUE TITLE
Supporting setVehicleHandling on the client side, for vehicles created on the server side. (Custom vehicles, engineRequestModel)

### ISSUE THREAD

**Issue by ZbyK77** [multitheftauto/mtasa-blue#2427]
**Is your feature request related to a problem? Please describe.**

To create a vehicle with a custom ID (engineRequestModel), you need to create the vehicle on the server side, then change the model on the client side. Unfortunately, changing the model resets the handling of the vehicle, and it is not possible to change the handling through the client side, so handling cannot be set for a custom vehicle.

**Describe the solution you'd like**
Adding the ability to edit handling on the client side for vehicles created on the server side.

**Describe alternatives you've considered**
I used this solution which doesnt work for setVehicleHandling due to the described problem.
```
-- c-side
local v1,v2 = getVehicleVariant(source)
local handling = getVehicleHandling(source)
setElementModel(source,4542)
setVehicleVariant(source,v1,v2) -- return true, and I wish the setVehicleHandling function would work like this.
for i,v in pairs(handling) do
	setVehicleHandling(source,i,v) -- return false, because the vehicle is created on the server side. :(
end
```

**Comment by Brian9221** [comment]
I think this is more a bug than an enhancement, in fact MTA team has fixed some incompatibility between server-clients to the new models related to door sync.

**Comment by LightSrc** [comment]
I have also encountered this problem. I hope that dev team are aware of this bug and will find solution soon.

**Comment by Inder00** [comment]
- If we change the vehicle on the client side using setElementModel it resets the vehicle handling.
- If we change the vehicle on the client side and then set the handling everything works fine.

**Comment by ZbyK77** [comment]
I would like to point out that it is about changing the handling on the client's side, when the vehicle is created on the server side.


> * If we change the vehicle on the client side using setElementModel it resets the vehicle handling.

Everything is correct here, when we change the model, the handling resets.


> * If we change the vehicle on the client side and then set the handling everything works fine.

But when we want to change handling later, we can't do it (c-side).

Example:

```
-- client side
addCommandHandler("handling_client",function(cmd)
	local veh = getPedOccupiedVehicle(localPlayer) -- Currently: Infernus (411)
	if veh then
		local ori_hand = getVehicleHandling(veh) -- return mass: 1400
		setElementModel(veh,410) -- true
		local bf_hand = getVehicleHandling(veh) -- return mass: 1000
		local ret = setVehicleHandling(veh,"mass",500) -- return false
		local af_hand = getVehicleHandling(veh) -- return mass: 1000 (It should: 500)
		iprint(cmd,veh,ori_hand.mass,bf_hand.mass,ret,af_hand.mass)
	end
end)
```
Return:
`[2022-01-05 23:43:23] INFO: "handling_client"    elem:vehicle[Manana]0000961D    1400    1000    false    1000`

Handling will change only when we do it on the server side.
![image](https://user-images.githubusercontent.com/65454704/148300971-7b969dcf-e7ec-454f-a12c-4d9e3ac218a1.png)
(setVehicleHandling)

**Comment by Inder00** [comment]
> I would like to point out that it is about changing the handling on the client's side, when the vehicle is created on the server side.
> 
> > * If we change the vehicle on the client side using setElementModel it resets the vehicle handling.
> 
> Everything is correct here, when we change the model, the handling resets.
> 
> > * If we change the vehicle on the client side and then set the handling everything works fine.
> 
> But when we want to change handling later, we can't do it (c-side).
> 
> Example:
> 
> ```
> -- client side
> addCommandHandler("handling_client",function(cmd)
> 	local veh = getPedOccupiedVehicle(localPlayer) -- Currently: Infernus (411)
> 	if veh then
> 		local ori_hand = getVehicleHandling(veh) -- return mass: 1400
> 		setElementModel(veh,410) -- true
> 		local bf_hand = getVehicleHandling(veh) -- return mass: 1000
> 		local ret = setVehicleHandling(veh,"mass",500) -- return false
> 		local af_hand = getVehicleHandling(veh) -- return mass: 1000 (It should: 500)
> 		iprint(cmd,veh,ori_hand.mass,bf_hand.mass,ret,af_hand.mass)
> 	end
> end)
> ```
> 
> Return: `[2022-01-05 23:43:23] INFO: "handling_client" elem:vehicle[Manana]0000961D 1400 1000 false 1000`
> 
> Handling will change only when we do it on the server side. ![image](https://user-images.githubusercontent.com/65454704/148300971-7b969dcf-e7ec-454f-a12c-4d9e3ac218a1.png) (setVehicleHandling)

The pull request I created fixes a bug that was causing the handling resets.
The setVehicleHandling functionality on vehicles created by the server from the client side enables PR #1935
