### ISSUE TITLE
Disable camera collisions for detached vehicle parts and projectiles

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#2434]
**Is your feature request related to a problem? Please describe.**
I propose disabling camera collisions for detached vehicle parts and projectiles by default because it's annoying and looks like oversight from R* side.

**Describe the solution you'd like**
Make these objects non collidable with camera.

**Additional context**
GTA already disables camera collisions for other small objects like fences so I think this proposal fits very well.

**Comment by Einheit-101** [comment]
maybe even add support for setElementCollisionsEnabled / setElementCollidableWithType

**Comment by lopezloo** [comment]
Turns out it's not even currently possible to do that via scripting:
```lua
crun engineSetObjectGroupPhysicalProperty(122, "avoid_camera", false)
```

It disables camera collisions for script created objects with grenade model but not for projectiles thrown by players.
