### ISSUE TITLE
Calling engineRequestModel with the ID of a custom model crashes the game

### ISSUE THREAD

**Issue by 3aGl3** [multitheftauto/mtasa-blue#2436]
**Describe the bug**
When calling engineRequestModel with the ID returned from another engineRequestModel call as parent it crashes the game.

**To reproduce**
Execute the following code.
```lua
crun id = engineRequestModel("vehicle")
crun id2 = engineRequestModel("vehicle", id)
crun Vehicle(id2, me.position + Vector3(0, 0, 4))
```

**Expected behaviour**
Either have the game load the model properly or have it throw a script error.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8626590/141678861-6b5dd302-4ec1-4477-bbdf-795ece2368ad.png)

**Version**
Server and Client Version 1.5.9

**Comment by Xenius97** [comment]
Why are you using requested model id as parent id?

**Comment by Yamsha75** [comment]
> Why are you using requested model id as parent id?

It doesn't matter. Whether this is inteded use or not, it should not result in a game crash.

**Comment by 3aGl3** [comment]
> 
> 
> Why are you using requested model id as parent id?

I wanted to test out the feature and simply added a command that applies a custom model to your car, with the cars current model as the parent. If you call the command twice you crash your client. Then again, does it even matter?

**Comment by Xenius97** [comment]
NEVER use custom id as parent id. EngineRequest clones DEFAULT models to new id. If you use non exiting model id as parent the result is crash. This crash is only because of your spaghetti code, you can fix this via scripting.

**Comment by Lpsd** [comment]
Regardless of the scripting error, the client should not crash if it can be avoided. This can be fixed.

**Comment by Fernando-A-Rocha** [comment]
Thanks Normalnij

**Comment by lopezloo** [comment]
Reproduction code was incomplete. You also need to create vehicle with this new ID.
