### ISSUE TITLE
playSound3D doesn't work in all dimensions when set to -1

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#2444]
**Describe the bug**

playSound3D doesn't work in all elements when set to -1 by using the settlement dimension function, it only plays at dim 0.

**To reproduce**

```
local radio = playSound3D("https://23153.live.streamtheworld.com/SMOOTH953_AAC48.aac",0,0,5)
setSoundMinDistance(radio,50)
setSoundMaxDistance(radio,100)
setElementDimension(radio,-1)
```

Try to test in dimensions other than 0
furthermore, `playSound3D` also doesn't work with `setElementInterior` either.

**Expected behaviour**

playSound3D should play in all dimensions like other elements does.

**Version**
 1.5.9-release-21031

**Comment by PlatinMTA** [comment]
Was it ever supposed to work that way? The -1 dimension change was made fairly recently, so I don't think anybody updated the sounds.

It should work this way tho.

For time time being you could do something like this:

```lua

addEventHandler("onClientElementDimensionChange", localPlayer, 
    function (_, new)
        setElementDimension(sound, new)
    end
)
```
