### ISSUE TITLE
Dune & Dumper have wrong vehicle type name

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2447]
**Describe the bug**
Dune and Dumper have Monster Truck type

**To reproduce**
getVehicleType()

**Version**
Multi Theft Auto v1.5.9-release-21024.1

**Comment by Allerek** [comment]
> **Describe the bug** Dune and Dumper have Monster Truck type
> 
> **To reproduce** getVehicleType()
> 
> **Version** Multi Theft Auto v1.5.9-release-21024.1

I think its based on the way the game is interpeting it, so its not MTA Problem.

**Comment by bum8hj** [comment]
Seems right considering how similar they are to the Monster when it comes to flipping over vehicles with the wheels.

But yeah, it's a bit odd.

**Comment by Lpsd** [comment]
This is correct behaviour. All vehicles fit under one of these types: https://github.com/multitheftauto/mtasa-blue/blob/16769b8d1c94e2b9fe6323dcba46d1305f87a190/Server/mods/deathmatch/logic/CVehicle.h#L99-L112

If you want the actual vehicle name, use [getVehicleName](https://wiki.multitheftauto.com/wiki/GetVehicleName)
