### ISSUE TITLE
Better document playSFX & playSFX3D volume using MTA Volume setting

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2450]
**Describe the bug**
playSFX & playSFX3D volume uses MTA Volume setting

**Expected behaviour**
Use SFX Volume setting

**Version**
Multi Theft Auto v1.5.9-release-21043

**Comment by patrikjuvonen** [comment]
Not sure. SFX volume means GTA volume. The playSFX functions play sounds through MTA bass library and not GTA's internal audio engine. Maybe renaming the options to be more clear should be better.

Maybe better off describing them on the Wiki pages.

**Comment by gta191977649** [comment]
> Not sure. SFX volume means GTA volume. The playSFX functions play sounds through MTA bass library and not GTA's internal audio engine. Maybe renaming the options to be more clear should be better.
> 
> Maybe better off describing them on the Wiki pages.

I think it's okey to let the  sound play through the bass dll by default behaviour, but I suggest it's would be nice if we have some ability to fetch player's GTA settings, e.g. radio volume, in this case we can build a fully customize radio system has the ability using the GTA volume settings.

**Comment by Pirulax** [comment]
It should be possible to add an option to the function to use GTA volume. 
OR add a function to get the current GTA volume setting, and let the user calculate the required volume manually.

**Comment by patrikjuvonen** [comment]
> I think it's okey to let the sound play through the bass dll by default behaviour, but I suggest it's would be nice if we have some ability to fetch player's GTA settings, e.g. radio volume, in this case we can build a fully customize radio system has the ability using the GTA volume settings.

That's off topic. Make a new issue, or look at the existing few issues that are already related to this subject. #783 #327 #451 

I don't see any reason to change this current behavior.

I have edited Wiki to reflect the way this works.
