### ISSUE TITLE
Add setObjectBreakable to the shared function

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#2455]
**Is your feature request related to a problem? Please describe.**

Since we have  `setElementDoubleSided` in shared function, why don't we also add setObjectBreakable into the shared function?
thus we can set ObjectBreakable property directly on a server-sided created object like the `setObjectBreakable` function does.
**Describe the solution you'd like**

add `setObjectBreakable` to the serverside like `setElementDoubleSided`

Please consider
Thanks!

**Comment by Fernando-A-Rocha** [comment]
Unfortuantely this is duplicate of #990 :) @gta191977649

**Comment by gta191977649** [comment]
> Unfortuantely this is duplicate of #990 :) @gta191977649

oh i didn't notice that
