### ISSUE TITLE
Changing GTA San Andreas Singleplayer HUD affects MTA

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2458]
**Describe the bug**
If you disable part of your HUD in GTASA then it will affect your MTA and you will be unable to display the default HUD.

**To reproduce**
Open your GTA San Andreas (gtasa.exe), go to config and disable your hud.
Open MTA and join a server, you won't be able to see your hud.

Even using ``setPlayerHudComponentVisible`` will not work.

```lua
start runcode
crun isPlayerHudComponentVisible("health")
crun setPlayerHudComponentVisible("health", true)
crun isPlayerHudComponentVisible("health")
```

**Expected behaviour**
You should be able to see your HUD regardless of your GTASA config

**Screenshots**
![image](https://user-images.githubusercontent.com/23291573/146651979-b0e4ca5a-1d5d-4d98-a8ce-c67984a0317e.png)

**Version**
All versions (this is an old bug)

**Additional context**
MTA should have an option to disable your hud in the configuration. I understand that maybe MTA wants players to be able to choose whenever your HUD is visible or not, but after years of being a server owner I can't even remember how many times people had asked me why the couldn't see their HUD only to notice that they had disabled it on their GTASA.

**Comment by TheNormalnij** [comment]
I can't reproduce this bug on windows 10.

**Comment by PlatinMTA** [comment]
> I can't reproduce this bug on windows 10.

I'm using windows 10 tho. Are you sure you are changing the hud on the correct instalation of gtasa?
