### ISSUE TITLE
Establish Crowdin integration

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#2466]
**Is your feature request related to a problem? Please describe.**
We moved from our Pootle server to Crowdin. We have no automated way of generating, importing or exporting translations at this time.

**Describe the solution you'd like**
Create Crowdin integration using their existing documentation.

**Describe alternatives you've considered**
Doing it all manually.

**Additional context**
Documentation for integrations should be out there and should be fairly easy.

#2525 #2508 #2505

**Comment by comradekingu** [comment]
That is a solid downgrade. Consider using Weblate instead.
https://docs.weblate.org/en/latest/vcs.html?highlight=github#github-repositories  https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

**Comment by patrikjuvonen** [comment]
Related: #2525
