### ISSUE TITLE
Poor svg quality (svgCreate, createBrowser)

### ISSUE THREAD

**Issue by flashmta** [multitheftauto/mtasa-blue#2492]
**Describe the bug**

It appears that when drawing svg's (using `svgCreate` or loading it via browser) the texture has crisp edges compared to a png created by `dxCreateTexture`

**To reproduce**

[qualitytest.zip](https://github.com/multitheftauto/mtasa-blue/files/7790082/qualitytest.zip)

**Expected behaviour**

Svg edges should look smooth for both `svgCreate` and `createBrowser`

**Screenshots**

![Przechwytywanie](https://user-images.githubusercontent.com/58608570/147690842-d5f84c37-30e8-4894-99da-3194d84c5154.PNG)

**Version**

Multi Theft Auto v1.5.9-release-21048

**Comment by Lpsd** [comment]
there isn't anything more to be done on MTA side - we are using [lunasvg](https://github.com/sammycage/lunasvg) to produce a bitmap from SVG.

**Comment by flashmta** [comment]
I don't know if that matters but I've figured out that if you use `dxSetBlendMode("add")` before drawing, the texture seems to look fine but the issue with that is you are unable to use alpha channel or it's only changed partially (if svg has different colors)

**Comment by dmi7ry** [comment]
> I don't know if that matters but I've figured out that if you use `dxSetBlendMode("add")` before drawing, the texture seems to look fine but the issue with that is you are unable to use alpha channel or it's only changed partially (if svg has different colors)

I guess premultiplied aplha would help

**Comment by flashmta** [comment]
> > I don't know if that matters but I've figured out that if you use `dxSetBlendMode("add")` before drawing, the texture seems to look fine but the issue with that is you are unable to use alpha channel or it's only changed partially (if svg has different colors)
> 
> I guess premultiplied aplha would help

Got it to work, thank you
