### ISSUE TITLE
Constant "protocol 14" error at 255 players

### ISSUE THREAD

**Issue by vorty123** [multitheftauto/mtasa-blue#2497]
**Describe the bug**
We experienced a lot of protocol 14 errors at random intervals. During these intervals, players could not connect to our server. We observed that this error occurs when our online player count is exactly 255. Because protocol 14 has something to do with "0", I think that some value overflows at 255 (8bit limit), and gets a zero, but after some time, it fixes itself.

**To reproduce**
Have exactly 255 online players.
Try to connect.

**Version**
Latest server version

**Comment by vorty123** [comment]
Video demonstration:
https://www.youtube.com/watch?v=kR1RrmlZrNk

**Comment by botder** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/bd62e563e082533e3c35df877cf99ccdd54f5be8/Client/mods/deathmatch/logic/CPacketHandler.cpp#L355-L360

**Comment by botder** [comment]
Code demonstration:
https://godbolt.org/z/WfEboGbsf
