### ISSUE TITLE
Replacing vehicle model triggers onClientElementStreamIn & onClientElementStreamOut

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2509]
**Describe the bug**
Replacing vehicle model triggers onClientElementStreamIn & onClientElementStreamOut

**To reproduce**
Replace a default vehicle with a mod

**Expected behaviour**
Doesn't trigger onClientElementStreamIn & onClientElementStreamOut

**Screenshots**
![image](https://user-images.githubusercontent.com/6568348/149093634-ca2b22c1-bab1-4570-9da1-6ebe7aaf68fa.png)

**Version**
Multi Theft Auto v1.5.9-release-21048

**Additional context**
[test.zip](https://github.com/multitheftauto/mtasa-blue/files/7852991/test.zip)

**Comment by Fernando-A-Rocha** [comment]
Does it trigger onClientElementStreamIn when the model of the vehicle is changed even if it is far away from you? e.g. in another dimension

Because if it only does it when the element is already streamed in then I think this behavior is acceptable

**Comment by Lpsd** [comment]
This is intended behaviour.

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/mods/deathmatch/logic/CClientDFF.cpp#L363-L366

I guess it's also useful as a kind of callback, to let you know when the model has been replaced (if object is already streamed in).

**Comment by Lord-Henry** [comment]
It's useful because "onElementModelChange" is not being called. So we need this behaviour as is.
