### ISSUE TITLE
Merge the two fire extinguish functions into one extinguishFire

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#251]
**Is your feature request related to a problem? Please describe.**
Right now we've got two functions for extinguishing fire, making it a bit redundant:
- extinguishAllFires
- extinguishFireInRadius

**Describe the solution you'd like**
Merge the two fire extinguish functions into one _extinguishFire_ function.
Proposed syntax: `extinguishFire ( [ float x, float y, float z [, float radius = 1.0 ] ] )`

**Describe alternatives you've considered**
None

**Additional context**
Requested originally by @qaisjp 
I'm going to look at this now, feel free to assign me to it.
Should be a quick and small tweak. Will also not affect backwards compatibility, as these functions were newcomers to 1.5.6 anyway.

**Comment by qaisjp** [comment]
Originally a [card](https://github.com/multitheftauto/mtasa-blue/projects/4#card-11510868)! 🎉 for the first issue.
