### ISSUE TITLE
setVehiclesLODDistance() & setPedsLodDistance() can't override player settings

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#2510]
**Describe the bug**
setVehiclesLODDistance() & setPedsLodDistance() values are being clamped to values based on user video settings.

**To reproduce**
Disable "Render vehicles always in high quality" option in video settings.
Stay away from some vehicles to see their low LOD models.
`crun setVehiclesLODDistance(300)`
... no effect

**Expected behaviour**
setVehiclesLODDistance() & setPedsLODDistance() should be able to override player settings (?).

**Version**
v1.5.9-release-21067

**Additional context**
- Originally reported [here](https://github.com/multitheftauto/mtasa-blue/pull/2347#issuecomment-1008150235).
- https://github.com/multitheftauto/mtasa-blue/pull/832/commits/2308f5a940cc9e4ebee7701649ab87e05f8e8ed1

**Comment by patrikjuvonen** [comment]
Late comment, but from what I remember, this was desired behavior, we were leaning on the player having final control over how much is being rendered on their system. But there might have been a bug too, can't remember the exact behavior pattern we were going for.

**Comment by lopezloo** [comment]
When I first introduced `setVehiclesLODDistance` in #113 it was supposed to be overridable by scripts. IMO it should be up to scripters. As far as I remember there was indeed some bug with that function. I think it wasn't resetting properly on disconnect or something? Anyway, it was later fixed along with changing this behaviour in 2308f5a940cc9e4ebee7701649ab87e05f8e8ed1.
