### ISSUE TITLE
Remove separated functions for hashes

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2512]
**Is your feature request related to a problem? Please describe.**
There is hash function, which contains few hashes to select, but we also have some of them available separately. I think there's no point to keep those functions, as they do the same exact thing.

**Describe the solution you'd like**
Remove separated functions for sha256/md5 etc.

**Describe alternatives you've considered**
Leaving as it is.

**Additional context**
Would require bwc breaking version.

**Comment by Inder00** [comment]
Backwards compatibility

**Comment by Xenius97** [comment]
Remove is not a good option. Maybe addig a big warning text is better.

**Comment by Inder00** [comment]
> Remove is not a good option. Maybe addig a big warning text is better.

I fully agree.
https://github.com/multitheftauto/mtasa-blue/blob/ebf54d4fcfe9b0b5600c2b632595029ea97f2b3f/Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp#L98-L103
There is one usage of that warning.

**Comment by ghost** [comment]
> Backwards compatibility

> Additional context
> Would require bwc breaking version.

> Remove is not a good option. Maybe addig a big warning text is better.

Why would you want to keep dupped functions, i see no point in it. This is also why i mentioned that it would need bwc breaking version in order to introduce it, MTA can't be stuck in this hell, where it supports bwc for all the time, it needs to move on, and so do you. Imho - this is one of reasons why development goes so slow, because you need to care for bwc when doing something.

**Comment by botder** [comment]
There is zero cost in keeping these functions there, since the hashing algorithms will never change, but there is cost involved in deprecating/removing these functions. And backwards compatibility is very comfortable for the scripters.
