### ISSUE TITLE
Add onClientPlayerChat

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2517]
**Is your feature request related to a problem? Please describe.**
There is no way to find out when the localPlayer has wrote something in chat. Not to be confused with ``isChatBoxInputActive``. We should have a way to tell when the localPlayer used /say /me or /team. The only way to do this right now is by sending a trigger from the server to the client, which is not efficent.

**Describe the solution you'd like**
Add an event called ``onClientPlayerChat`` that will trigger when localPlayer sends a message, similar to ``onPlayerChat``. Only localPlayer should work.

**Describe alternatives you've considered**
Other alternatives are not so good. For example, having ``isChatBoxInputActive`` return a second value that has all the text that is visible on the input box of the chat. This could be used by malicious scripters to try and read users passwords, so it's a no.

**Additional context**
None.

**Comment by Lpsd** [comment]
Doesn't [onClientChatMessage](https://wiki.multitheftauto.com/wiki/OnClientChatMessage) already do this? Not sure if you can attach that event just to localPlayer or not though (but surely we can change that).

#2462 may also help here (better distinguishing between message types)

**Comment by PlatinMTA** [comment]
> Doesn't [onClientChatMessage](https://wiki.multitheftauto.com/wiki/OnClientChatMessage) already do this? Not sure if you can attach that event just to localPlayer or not though (but surely we can change that).
> 
> #2462 may also help here (better distinguishing between message types)

Ah yeah, it does do that. Thanks. I thought it worked more like ``onChatMessage`` in the sense that the source element is always the root element.
