### ISSUE TITLE
Male sounds on female skins

### ISSUE THREAD

**Issue by etrnl1337** [multitheftauto/mtasa-blue#2520]
As i've wanted to check my custom skin models for male noises on women skins and vice versa, i saw that default skins with ID 77 and 298 have MALE sounds while they are woman (298 are catalina so its 100% women, 77 is like 50/50 because it's skin of some homeless and it's hard to differentiate).

Is it on purpose, is it a bug or it doesn't matter? i don't know, i'll let you decide and do your job to improve MTA.

cver:

Multi Theft Auto v1.5.9-release-21048
Copyright (C) 2003 - 2021 Multi Theft Auto

sver:
MTA:SA Server v1.5.9-release-21006

**Comment by Pirulax** [comment]
Ped voices and stuff are all defined in `data/peds.ide` inside your GTASA root folder (where the `gta_sa.exe` is)
So, unless it's not like this in the default game, it's not an MTA bug.
Also, IIRC you can set the voice type of a skin, no?

**Comment by Xenius97** [comment]
@etrnl1337 you can use setPedVoice

**Comment by AlexTMjugador** [comment]
All special skins (including Catalina's) are defined in `peds.ide` to be males:

```
298, special09, generic, CIVMALE, STAT_STD_MISSION, man, 1FFF, 0, null, 9,9, PED_TYPE_SPC,0 ,0
```

The same applies to the skin with ID 77:

```
77, SWMOTR1, sWMOtr1, CIVMALE, STAT_TRAMP_MALE, man,1000,0, null,1,4,PED_TYPE_GEN,VOICE_GEN_SWMOTR1,VOICE_GEN_SWMOTR1
```

So I'd say this is not a MTA bug. It's how R* decided that these peds should sound.

**Comment by etrnl1337** [comment]
Thanks a lot!

I didn't know that there is such function as setPedVoice, it will become very useful for me. Thank y'all / closing.
