### ISSUE TITLE
Remove async task usage and callbacks from SVG functions

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#2521]
After some discussion on Discord (due to the points mentioned in #2477) I'll be removing async task usage and callbacks from SVG functions entirely.

D3D9 stuff is not thread safe, XML stuff is not thread safe (in this case, even with #2477 , destructors still matter), and more...

Callbacks are useless for the SVG functions if we aren't doing stuff async.

SVG was introduced in the 1.5.9 release. Obviously, any scripts using the callback args will not work after this has been done (hard error in Lua due to "extra" arg supplied). However, I'm actually fine with making these changes (soon) into nightly, before 1.6 - I don't think many people are using SVG right now - and considering SVG is currently pretty unstable in some situations with callbacks, I don't see an issue with resolving that for the sake of minor bwc concerns.

**Comment by Inder00** [comment]
Bomb has been defused.
