### ISSUE TITLE
Vehicle sun glare effect is globally applied although disabled by default

### ISSUE THREAD

**Issue by Vampiiree** [multitheftauto/mtasa-blue#2526]
**Describe the bug**
#2495 was recently released so I decided to test it to see if it was working fine then I noticed that this effect was working a server that didn't enable it.

**To reproduce**
1. Open a local server or map editor (in my case).
2. Runcode `setWorldSpecialPropertyEnabled("vehiclesunglare",true)`
3. Join a server directly

**Expected behaviour**
The sun glare effect shouldn't be applied globally when connecting to servers that didn't set it true. The PR mentions that it's disabled by default.

**Screenshots**
https://www.youtube.com/watch?v=h07vvifwY8Q

**Version**
Multi Theft Auto v1.5.9-release-21125

**Additional context**
It stops working if you reopen your client.

**Comment by patrikjuvonen** [comment]
cc @gta191977649

**Comment by gta191977649** [comment]
Thanks for report, please see check PR [2527](https://github.com/multitheftauto/mtasa-blue/pull/2527)
