### ISSUE TITLE
Changing resolution without game restart

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2531]
**Is your feature request related to a problem? Please describe.**
Changing resolution without game restart

**Describe the solution you'd like**
In the default game you can change resolution without game restart.

**Comment by Fernando-A-Rocha** [comment]
Ok but must require that the player is not connected to any server as this would break many scripts who only do guiGetScreenSize() once.

**Comment by Xenius97** [comment]
> Ok but must require that the player is not connected to any server as this would break many scripts who only do guiGetScreenSize() once.

Then add onClientPlayerResolutionChange to update it.

**Comment by FileEX** [comment]
It's not good idea - This can be (and probably would be) break scripts backwards compatibility

**Comment by bum8hj** [comment]
**I'd rather reconnect than restart.**

**Suggestion 1:**
If you're in a server and you change your resolution, it could say something like 'Disconnect from the server to apply changes'.

**Suggestion 2:**
Or if you don't mind complicating things :mreow:, you can go with what's suggested above, but add an option to the server config to enable changing resolution without reconnecting/restarting. Easier said than done...

**Comment by Pirulax** [comment]
Nobody ever thought about this, so this isn't possible at this point (Without putting in a huge amount of work to rework our internal GUI stuff + People would have to adjust their scripts)

**Comment by PlatinMTA** [comment]
I think that, if this is going to be implemented, it should make you refonnect to the server you were playing, or at least it should ask you to disconnect first.

But this would work only if the main menu and other GUI elements can be recalculated and resize or deleted and created for the new resolution without restarting.
