### ISSUE TITLE
Ctrl+Backspace gives white symbol in chat instead of removing one word to the left

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2534]
**Describe the bug**
Ctrl+Backspace is bugged in chat input. It gives some white symbol instead of removing one word.

**To reproduce**
Open chat, type in ctrl+backspace

**Expected behaviour**
Delete one word to the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/12304071/151850791-21e7072f-fe61-4bc3-a755-82681dddac89.png)

**Version**
Multi Theft Auto v1.5.9-release-21125

**Comment by Allerek** [comment]
https://defkey.com/what-means/ctrl-backspace

**Comment by bum8hj** [comment]
I noticed that too and thought it's an issue on my end.

**Comment by Pirulax** [comment]
Windows has the same issue when editing filenames in the file explorer... Maybe it's some Windows low level issue?

**Comment by patrikjuvonen** [comment]
> Windows has the same issue when editing filenames in the file explorer... Maybe it's some Windows low level issue?

Seems to work on Windows 11 at least.
