### ISSUE TITLE
dxGetTexturePixels returns blank pixels after svg creation

### ISSUE THREAD

**Issue by flashmta** [multitheftauto/mtasa-blue#2537]
**Describe the bug**

(Not sure if it's related to buggy svg async behaviour and might be fixed in #2521 but i'll post just in case)

You're unable to retrieve svg texture pixels right after calling `svgCreate` (seems like svg functions work in an asynchronous way even without providing a callback function)

**To reproduce**

[svgtest.zip](https://github.com/multitheftauto/mtasa-blue/files/7989789/svgtest.zip)

**Expected behaviour**

Svg pixels should be available right after calling svg functions

**Screenshots**

**Version**

Multi Theft Auto v1.5.9-release-21125

**Comment by Pirulax** [comment]
Currently they work in async, so this is expected.
https://github.com/multitheftauto/mtasa-blue/blob/da49960feb6651e1cb6efb8a63408eb8ad89c30e/Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.cpp#L245-L266
https://github.com/multitheftauto/mtasa-blue/blob/da49960feb6651e1cb6efb8a63408eb8ad89c30e/Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.cpp#L189-L202
