### ISSUE TITLE
Make server files downloadable without downloading installer

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2538]
**Is your feature request related to a problem? Please describe.**
If server files were downloadable without installer, server developers could make auto-server updater.

**Describe the solution you'd like**
Adding CDN links just line in alt:V -> https://wiki.altv.mp/wiki/Scripting:CDN_Links

**Additional context**
https://github.com/Stuyk/altv-pkg

**Comment by botder** [comment]
You can download the latest x64 server installer for Windows here: https://nightly.mtasa.com/. You can decompress the NSIS installer with 7-Zip (`7z.exe x <path to setup.exe> -y -o<destination>`) and there you go.

**Comment by TheNormalnij** [comment]
The Linux last package has [permanent link](https://linux.mtasa.com/dl/multitheftauto_linux_x64.tar.gz) as well. You can download it via curl or wget.
Auto updating can cause regressions and incompatibility. Test your server after update. 
Don't use auto update in prod! Make backups before update.

**Comment by Xenius97** [comment]
@TheNormalnij we're using windows version because of performance reasons.
Maybe botder's commend could work.

**Comment by Disinterpreter** [comment]
> we're using windows version because of performance reasons.

Can I ask offtop question? What is the performance reasons?

**Comment by attilaimre99** [comment]
> > we're using windows version because of performance reasons.
> 
> Can I ask offtop question? What is the performance reasons?

https://forum.mtasa.com/topic/101326-which-os-is-best-for-the-server/?do=findComment&comment=888542

I don't know if this statement is still valid, it would probably require some testing.

**Comment by botder** [comment]
For me it seems like that statement is about connecting to a locally hosted server. Of course you're going to have a performance penalty from going through abstraction layers (WSL or a VM), but that shouldn't really matter and impact you heavily on a local computer.

On a dedicated server host I would always prefer Linux over Windows, unless you have special requirements for the operating system - and it's much easier to operate a Linux host IMHO.
