### ISSUE TITLE
Remove/change DFF file warnings

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [multitheftauto/mtasa-blue#2541]
Some dff files will output a warning to the server log like this:
`WARNING: File 'file_path.dff' in resource 'resource_name' contains errors.`

I suggest either these warnings are removed entirely or that there is a way to turn them off via a mtaserver.conf setting.

Why: these warnings are wrong/irrelevant for many models that work perfectly fine as far as I've tested.

**Comment by PlatinMTA** [comment]
In my experience I have this sort of warnings on encrypted models. We had briefly discussed before (on discord) to give the servers owners a way to disable certain warnings because they are annoying.
