### ISSUE TITLE
Outdated link in SECURITY.md

### ISSUE THREAD

**Issue by MickaToast** [multitheftauto/mtasa-blue#2542]
**Is your feature request related to a problem? Please describe.**
Links for `private bugtracker` is outdated in https://github.com/multitheftauto/mtasa-blue/blob/master/.github/SECURITY.md. Won't open for a non registered forum member at least.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Allerek** [comment]
I think thats the way it should be, you can't view posts there or create ones without account anyways.

**Comment by patrikjuvonen** [comment]
That is intended indeed since we don't really have another way to do it at the moment. You basically need to register an account on the forum to be able to post a private bug report. Do you have any other ideas?

**Comment by patrikjuvonen** [comment]
I added a note about account requirement to the policy.
