### ISSUE TITLE
setVehiclesLODDistance not working for trains and planes

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2543]
**Describe the bug**
setVehiclesLODDistance not working for trains and planes

**To reproduce**
```
Client runcode: setVehiclesLODDistance(70, 500)
Result: true [boolean]
Client runcode: getVehiclesLODDistance()
Result: 70 [number], 149.80000305176 [number]
```

**Expected behaviour**
Update lod distance

**Version**
Multi Theft Auto v1.5.9-release-21129

**Additional context**
Vehicle distance can't be set 70+

**Comment by lopezloo** [comment]
Duplicate of 2510

**Comment by lopezloo** [comment]
Duplicate of #2510
