### ISSUE TITLE
onClientCursorMove returns 65k on X or Y axis if moving the cursor too fast.

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#256]
**Describe the bug**
So, if you move ur mouse too fast on an axis(X or Y) it sometimes returns(depends on the speed you are moving ur mouse with) it returns 65k (between 65500 and 65600) for some reason.

**To Reproduce**
1. Add an event handler on onClientCursorMove:
`addEventHandler("onClientCursorMove", root, 
function(_, _, cx, cy) 
    if (cx>65000) or (cy>65000)  then
        print(cx, cy)
    end
end)`
2. Move ur mouse like a total idiot
3. Here u go

**Expected behavior**
It should return a normal value

**Screenshots**
no pls

**MTA Client (please complete the following information):**
 - Multi Theft Auto v1.5.5-release-12411
 - Running in Wine? Nein

**MTA Server (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17134.112]
 - Version: Multi Theft Auto v1.5.5-release-12411

**Additional context**
I ran my game in windowed mode, maybe that causes the problem, because my cursor goes out from the screen.

**Comment by qaisjp** [comment]
Neither @patrikjuvonen or myself can reproduce this.

Please can you download [this file](https://ci.appveyor.com/api/buildjobs/9ssxv33qpv2yu0me/artifacts/InstallFiles.zip) and test to see if the problem has been fixed?

@patrikjuvonen perhaps push a change ignoring out of boundary coords and send him a link so he can compare and see which would be best? ref https://github.com/multitheftauto/mtasa-blue/pull/259#issuecomment-407600123

@Pirulax in the meantime can you perhaps try and figure out a more reliable way to reproduce this issue? more details like what resolution you are running windowed mode in, the kind of windowed mode, how many monitors you have, or anything else you think might be relevant? perhaps what might be relevant is the kind of mouse and if it is a high dpi one.

**Comment by patrikjuvonen** [comment]
I have now pushed a second commit at #259 that ignores out of bounds coordinates instead of clamping them. Let us know which one seems better.

**Comment by qaisjp** [comment]
thanks @patrikjuvonen. @Pirulax you can get the second copy ("ignore-outofbounds-coords") from [this link](https://ci.appveyor.com/project/multitheftauto/mtasa-blue/build/ci-1486/artifacts) when the build server is done. The file will be called "InstallFiles.zip"

(p.s. I accidentally edited the wrong comment... sorry 😛)

**Comment by Pirulax** [comment]
Hihi, I was running MTA in 1280x720 in windowed mode, but my monitor's native resolution is 1920x1080.
I made a little if statement which ignored high numbers, it worked just fine.
Is there still need of testing the build?

**Comment by qaisjp** [comment]
@Pirulax do you have multiple monitors?

**Comment by qaisjp** [comment]
Can you try this build ( https://ci.appveyor.com/project/multitheftauto/mtasa-blue/build/ci-1493/artifacts ) when it appears? This _might_ fix it.

**Comment by patrikjuvonen** [comment]
For future reference that commit (87879d47db30ffb34a021d5ff8771b1661f759c9) fixed the issue.
