### ISSUE TITLE
Adding C# as scripting language

### ISSUE THREAD

**Issue by ERAGON007** [multitheftauto/mtasa-blue#2561]
**Is your feature request related to a problem? Please describe.**
The point of this issue is to discuss about adding C# as an alternative to Lua.

There are ways to include C# without modifying current Lua API, adding new languages can attract more developers for both maintaining that section and making new resources with new capabilities.

**Describe the solution you'd like**

I've had some researches about including C#, and i've found 2 main ways of doing so:

1- Including `Mono` which is a `C` project and can be included in any `C++` project
2- Hosting `.NET`, this is a bit complex and can only include `.NET` supported languages

Both of these solutions are cross-platform meaning that MTAs platforms support won't be affected.

**Additional context**

If approach 1 `(Mono)` is used, it will be possible to use these languages too:
C#, F#, Java, Scala, Boo, Nemerle, VB.NET, Python, Obereon, PHP, Object-pascal, Lua, Cobra, Synergy-DBL.

most of these languages won't be used like `Nemerle` or `Object-pascal` and `Obereon`.

`Javascript` implementation is also possible but it's useless now because [IronJS](https://github.com/fholm/IronJS) is out-of-date for about 8 years.

all of these languages said are implementations of them for `.NET` and `Roslyn` platform which means they basically use `C#` so you don't have to include/modify security patches to all these languages.

Client-side security can be retained by using `.NET Reflection` capabilities to detect whether a namespace like `System.IO` is included or not, and reject code if used unsecure namespaces/methods.

`Mono`: https://www.mono-project.com/
`.NET Hosting`: https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

A real-world usage of `Mono` is https://github.com/citizenfx/fivem/tree/master/data/client

*EDIT: Added library links to resources mentioned

**Comment by Disinterpreter** [comment]
Seems good, but there were thousand attempts for adding another scripting language.

IMHO: I don't support C#, I support all .NET platform (because I prefer F#)

**Comment by ERAGON007** [comment]
> I don't support C#, I support all .NET platform (because I prefer F#)

This is why you can add `Mono`, because it support F# too. https://www.mono-project.com/docs/about-mono/languages/

> Seems good, but there were thousand attempts for adding another scripting language.

This is just because of staffs decision about these kinda actions about MTA.
If you want something good and advanced, you have to get project bigger than before. and they decline to accept this kind of PRs. I know that this idea will be rejected like others mainly because of Maintaining,Security..... But at least i gave it a try, hope they reconsider.

**Comment by Disinterpreter** [comment]
> This is why you can add `Mono`, because it support F# too. https://www.mono-project.com/docs/about-mono/languages/

For example, you cannot use F# in s&box or FiveM ;) I mean, if you want to do it, you should make an option for using it.

**Comment by ERAGON007** [comment]
> For example, you cannot use F# in s&box or FiveM

That's because they don't have an API for F#, they just use C# from whole Mono

**Comment by Pirulax** [comment]
So they have their own C# compiler?
Is the VM MS's VM? Or their own? 
Just curious, because MS's VM/Compiler probably has superior performance.

**Comment by ERAGON007** [comment]
> So they have their own C# compiler?
> Is the VM MS's VM? Or their own?


yes they have their own C# compiler too:
https://www.mono-project.com/docs/about-mono/languages/csharp/

But i have already run a regular `.NET Framework` project on ubuntu using mono. it worked pretty well. this means that you can also run code compiled by MS compiler and run it in mono.

Mono can use LLVM / JIT. and about the usage in C++ applications like MTA you can read following page:
https://www.mono-project.com/docs/advanced/embedding/scripting/

Sounds like we can use Mono to include a lot of languages by an interface.

**Comment by fresholia** [comment]
C# is not a scripting language.
(I also don't support platforms that use it as a scripting language.)

**Comment by CrosRoad95** [comment]
Mono is HUGE, size of server and maybe client will grow significantly. Could not find any premake5.lua file to add mono to the mta, one of the option is to write own from scratch

**Comment by Disinterpreter** [comment]
> Mono is HUGE, size of server and maybe client will grow significantly. Could not find any premake5.lua file to add mono to the mta, one of the option is to write own from scratch

I don't understand why you pay so much attention to Mono when https://github.com/dotnet is exist, opensource and clearly accessible, instead of old, legacy Mono?
