### ISSUE TITLE
Add a way to get the entry points to a vehicle

### ISSUE THREAD

**Issue by MegadreamsBE** [multitheftauto/mtasa-blue#2565]
**Is your feature request related to a problem? Please describe.**

Right now the only ways to make a ped enter a vehicle doesn't allow you to pick a specific seat. The closest you can get is by using setPedEnterVehicle and specifying whether it has to be a driver or passenger seat. However you can still not decide which passenger seat the ped takes.

**Describe the solution you'd like**

It would be nice to have a function that returns all entry points to a vehicle (note that entry points and seats are not exactly the same thing, a vehicle can have more entry points than seats). Having these entry points would make it possible to first make the ped walk to  the location of one of these entry points before using the setPedEnterVehicle function, thus allowing you to choose the resulting seat. This solution is also necessary for my Co-Op project (Sphene) to properly implement its task logic.

**Describe alternatives you've considered**

You could technically manually build a list of offsets of each entry points and use that but it would be a huge amount of work and won't work with custom vehicles.

**Comment by bum8hj** [comment]
What if `onClientStartVehicleEnter` returned the selected entry point?

We could cancel the event and use `setPedEnterVehicle` to change the entry point (assuming you implement that too 😩)

Anyway, it's not a necessary or highly demanded feature afaik.

**Comment by MegadreamsBE** [comment]
> What if `onClientStartVehicleEnter` returned the selected entry point?
> 
> We could cancel the event and use `setPedEnterVehicle` to change the entry point (assuming you implement that too 😩)
> 
> Anyway, it's not a necessary or highly demanded feature afaik.

I don't see how that would be any better than having a function that can give you this information right away. And sure, this function might not have a high demand but that doesn't take away that there's a good use for it. My own project which aims to add the storyline to MTA and then Co-Op on top of it depends on it for example.

**Comment by bum8hj** [comment]
> I don't see how that would be any better than having a function that can give you this information right away. And sure, this function might not have a high demand but that doesn't take away that there's a good use for it. My own project which aims to add the storyline to MTA and then Co-Op on top of it depends on it for example.

Oh no...absolutely.

I wasn't suggesting this as a replacement. I meant that having an `entryPoint` parameter in `onClientVehicleStartEnter` could be useful for some, to get the entry point that a ped/player is currently heading towards.

**Comment by MegadreamsBE** [comment]
> > I don't see how that would be any better than having a function that can give you this information right away. And sure, this function might not have a high demand but that doesn't take away that there's a good use for it. My own project which aims to add the storyline to MTA and then Co-Op on top of it depends on it for example.
> 
> Oh no...absolutely.
> 
> I wasn't suggesting this as a replacement. I meant that having an `entryPoint` parameter in `onClientVehicleStartEnter` could be useful for some, to get the entry point that a ped/player is currently heading towards.

Fair enough! Yeah, that'd be nice but I feel is out of the scope of this issue. In terms of setPedEnterVehicle, that'd be nice as well but unfortunately requires quite a lot of work, I have looked into it before.
