### ISSUE TITLE
Where is (whowas) command ?

### ISSUE THREAD

**Issue by ALBANDER2022** [multitheftauto/mtasa-blue#2567]
Please return whowas command

**Comment by MegadreamsBE** [comment]
This can be entirely implemented in Lua. I don't see a reason to have it directly in MTA.

**Comment by Lpsd** [comment]
See removal - https://github.com/multitheftauto/mtasa-blue/commit/0cffa9215f4601e42b2dfbc254040aeda3caa8f0

This will not be re-implemented in MTA, as mentioned above you can create this yourself entirely in Lua.

**Comment by ALBANDER2022** [comment]
How ?

**Comment by ALBANDER2022** [comment]
Give me lua code please

**Comment by AlexTMjugador** [comment]
@PlatinMTA submitted an implementation of the `whowas` command to the MTA resources repository that you might find useful: https://github.com/multitheftauto/mtasa-resources/pull/161

**Comment by Lpsd** [comment]
If you have any other scripting questions please visit our [Discord](https://mtasa.com/discord).
