### ISSUE TITLE
Replace type model

### ISSUE THREAD

**Issue by MichaelFarad** [multitheftauto/mtasa-blue#2568]
hello everyone, please help me with advice on how to implement a change in the type of transport. I would like to change the trailer type (truck van id 435) to a passenger car, I can't get inside the trailer when the player exits. I would like to replace the trnyler with a car model. Thanks in advance...

**Comment by Lpsd** [comment]
Please direct your question to the scripting channels on [Discord](https://mtasa.com/discord).
