### ISSUE TITLE
setElementFrozen() should work per resource

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2569]
**Is your feature request related to a problem? Please describe.**
If two resources have frozen the player it will eventually lead to an early unfreeze in one of the resources.

**Describe the solution you'd like**
It would be nice that ``setElementFrozen`` worked per resource, like ``showCursor``.

You could use 
```lua
-- setElementFrozen(boolean freeze, [[ boolean force = true]])
setElementForce(true, true)
```
To have it change on all resources. It shouldnt brake backwards compatibility.

In case of ``isElementFrozen(me) == true`` at the end of the resource (``isElementFrozen`` should return true while frozen, always) then the status shouldnt change but the resource state should not be counted for the next ``setElementFrozen(true)``

**Describe alternatives you've considered**
There could be a priority list going from 0 to 99. Being:

``setElementFrozen(boolean freeze, [[ integer priority = 99 ]]``

For example if you use ``setElementFrozen(true, 58)`` only ``setElementFrozen(false, 58 and above)`` could unfreeze them. The priority only changes if another freeze = true with higher priority is passed.

This is kinda innecesary but it could be faster than checking in an array that there arent any resources having the player frozen. Maybe.

**Additional context**
You can already do this in lua, but you need to use elementDatas or exports, which are slow.

Also we already have functions like this, for example ``showCursor``.

**Comment by patrikjuvonen** [comment]
No.
