### ISSUE TITLE
Bullet sync with sniper doesn't work properly

### ISSUE THREAD

**Issue by ALBANDER2022** [multitheftauto/mtasa-blue#2576]
Bullet sync with sniper doesn't work properly

Some sniper shots do not damage the player

Please fix this bug and keep sniper with bullet sync 100%

I mean sniper (id 34) not rifle

**Comment by ghost** [comment]
Make use of issue template, don't delete it.

**Comment by ALBANDER2022** [comment]
> Make use of issue template, don't delete it.

I don’t understand you

**Comment by Vadya963** [comment]
> > Make use of issue template, don't delete it.
> 
> I don’t understand you

when you created the problem, there was an example of how to properly design the problem, do as it was in the template

**Comment by Vadya963** [comment]
**Describe the bug**


**To reproduce**


**Expected behaviour**


**Screenshots**


**Version**


**Additional context**

**Comment by ALBANDER2022** [comment]
aha  this old bug but i want to fix it

**Comment by ALBANDER2022** [comment]
> **Describe the bug**
> 
> **To reproduce**
> 
> **Expected behaviour**
> 
> **Screenshots**
> 
> **Version**
> 
> **Additional context**




i can’t recording video because my PC is weak

**Comment by MegadreamsBE** [comment]
> > **Describe the bug**
> > **To reproduce**
> > **Expected behaviour**
> > **Screenshots**
> > **Version**
> > **Additional context**
> 
> i can’t recording video because my PC is weak

You don't necessarily have to if it's easy to reproduce. But please fill in this template in the description of your issue including proper steps on how to reproduce.

**Comment by ALBANDER2022** [comment]
Some sniper shots doesn’t damage the player


This is simple reproduce


Please fix it

**Comment by Dutchman101** [comment]
As someone that has used sniper often for years on bulletsync-enabled servers without noticing a lower quality of sync, i will take your habit of submitting invalid issues (and general tracker annoyances) into consideration for closing this. Cannot reproduce or confirm.
