### ISSUE TITLE
Add Discord RPC

### ISSUE THREAD

**Issue by AliiiAm** [multitheftauto/mtasa-blue#2579]
**Add Discord rich response**

please add discord rich response function 

That we can leave one rich response for each player

![Capture](https://user-images.githubusercontent.com/84466647/160598501-d78a125a-4381-47f7-9692-da0a8c61c832.PNG)

This is a sample photo

**Comment by Lpsd** [comment]
This is already a work in progress.

Please refer to #2499 and #2577

**Comment by Lpsd** [comment]
Resolved by #3167
