### ISSUE TITLE
on(Client)ElementModelChange doesn't triggered when vehicle variant is changed

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2580]
**Describe the bug**
on(Client)ElementModelChange doesn't triggered when vehicle variant is changed
Only triggers streamIn & streamOut

**To reproduce**
```
addEventHandler("onClientElementModelChange", root, function(oldModel, newModel)
	iprint(source, oldModel, newModel)
end)
```

**Expected behaviour**
Should be triggered

**Version**
Multi Theft Auto v1.5.9-release-21135

**Comment by Lpsd** [comment]
Please provide a full reproduction resource if possible, which satisfies all cases for the purpose of testing (stream in/out, changing vehicle variant, etc).

**Comment by Xenius97** [comment]
@Lpsd https://mega.nz/file/BY4z1BwL#FHTmjjueSVwShbFdrsbEl3JSrw89K-rTs9mnhU4hd-E

**Comment by Lpsd** [comment]
Thanks - also just incase you aren't aware, you can upload files directly to GitHub by either dragging into the reply box or clicking the "attach files by dragging [...]" ribbon at the bottom of the reply box.

**Comment by Xenius97** [comment]
[variant_test.zip](https://github.com/multitheftauto/mtasa-blue/files/8389154/variant_test.zip)
I'm using megasync always, sorry :D
