### ISSUE TITLE
Add new car IDs

### ISSUE THREAD

**Issue by ElPendejoN** [multitheftauto/mtasa-blue#2590]
I've seen that we still haven't made any similar function in our API or even made an official MTA plugin for it.

My idea is that maybe we should add the feature for developers to make new car IDs, or models that should have the base of a selected car so we don't waste time replacing the sounds, etc

In summary, I suggest for devs be able to create new car models so we don't have to add mods to the same vehicles

for example, imagine having two models of rhinos one with a mod of a T-90 and another with an M1 Abrams, in order to do that we have to add another car ID.

![image](https://user-images.githubusercontent.com/76622708/161442781-c7731ada-a324-455b-b3f3-122a578f36dd.png)

**Comment by Lpsd** [comment]
Why isn't a resource sufficient enough to handle this?

**Comment by ElPendejoN** [comment]
Maybe because there is no function such as CreateVehicleID?

**Comment by ghost** [comment]
@ElPendejoN [perhaps?](https://wiki.multitheftauto.com/wiki/EngineRequestModel); [ready solution](https://forum.mtasa.com/topic/133212-rel-add-new-models-library/). I am not sure if that's what you mean.

**Comment by ElPendejoN** [comment]
What does that do?

**Comment by ElPendejoN** [comment]
Does that create a new model vehicle instead of replacing

**Comment by PlatinMTA** [comment]
> Does that create a new model vehicle instead of replacing

Yeah, but you need to sync the models yourself. You can use [this resource](https://forum.mtasa.com/topic/133212-rel-add-new-models-library/) (srslyyyy linked it) instead and you won't need to think about it.

**Comment by ElPendejoN** [comment]
Amazing

**Comment by Fernando-A-Rocha** [comment]
> Amazing

Thanks for mentioning it @PlatinMTA

I tried creating what this post suggests: a tool to make adding models (like new car IDs) easy and optimised.

MTA API for this only gives two new functions which are rather low-level and you need to make your own scripts to be able to use them efficiently (that resource does that)

**Comment by ElPendejoN** [comment]
I have a question, does this function add new objects (DFFs) instead of replacing them?
Like adding a elevator DFF instead of replacing an already existing dff

**Comment by ElPendejoN** [comment]
according to https://wiki.multitheftauto.com/wiki/EngineRequestModel it does

**Comment by patrikjuvonen** [comment]
> I have a question, does this function add new objects (DFFs) instead of replacing them? Like adding a elevator DFF instead of replacing an already existing dff

@ElPendejoN Yes, that function was added in 1.5.8 release. Please ask for help on the [scripting forum](https://forum.mtasa.com/forum/71-scripting/) or [scripting-help channel](https://discord.com/channels/278474088903606273/278520948347502592) on Discord on how to use it if you have any trouble using the Wiki example.
