### ISSUE TITLE
BASS ERROR 41 in LoadMedia

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2596]
### Describe the bug

[Output] : BASS ERROR 41 in LoadMedia  path:C:\Games\MTA San Andreas\mods\deathmatch\resources\ex_gates\files\gate.mp3  3d:1  loop:0

Game freezes for 1-5 seconds

### Steps to reproduce

Use mp3 at playSound or playSound3D

### Version

Multi Theft Auto v1.5.9-release-21150

### Additional context

This bug is from 21135
After converting to .wav it will work without any errors.

Script + mp3 file:
[gate.zip](https://github.com/multitheftauto/mtasa-blue/files/8457362/gate.zip)

> addEvent("playGateSound", true)
> addEventHandler("playGateSound", root, function(sound,x,y,z)
> 	local mx, my, mz = getElementPosition(localPlayer)
> 	if getDistanceBetweenPoints3D(x, y, z, mx, my, mz) <= 50 then
> 		local sound = playSound3D(sound, x,y,z, false)
> 		setSoundVolume(sound, 0.3)
> 		setSoundMinDistance(sound, 10)
> 		setSoundMaxDistance(sound, 15)
> 	end
> end)

### Relevant log output

```shell
[2022-04-08 12:16:09] [Output] : BASS ERROR 41 in LoadMedia  path:C:\Games\MTA San Andreas\mods\deathmatch\resources\ex_gates\files\gate.mp3  3d:1  loop:0
[2022-04-08 12:16:42] [Output] : BASS ERROR 41 in LoadMedia  path:C:\Games\MTA San Andreas\mods\deathmatch\resources\ex_gates\files\gate.mp3  3d:1  loop:0
[2022-04-08 12:16:44] [Output] : BASS ERROR 41 in LoadMedia  path:C:\Games\MTA San Andreas\mods\deathmatch\resources\ex_gates\files\gate.mp3  3d:1  loop:0
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
I am unable to reproduce, using the attached resource i can play your .mp3 file without any problems.
[soundtest.zip](https://github.com/multitheftauto/mtasa-blue/files/8457547/soundtest.zip)

If this works for you, then you have interference from something
@Xenius97 

*Note: in a realistic environment (my server), hundreds of players have played a huge variety of .mp3 files with recent builds, without reporting any issue and having a long average play duration. My speaker resource collects stats for that.

**Comment by ffsPLASMA** [comment]
Tested on my local map editor with v1.5.9-release-21166
Works fine, no errors.

**Comment by PlatinMTA** [comment]
I have seen this error before but it's seems to be random (and I have seen it for custom user speakers, which could simply lead to broken mp3s or whatever). This didn't lag me tho.

Do  you have an HDD or an SSD? This could be a factor for your lag.

**Comment by Xenius97** [comment]
Now it works fine for me, don't know what happened. :)
