### ISSUE TITLE
createWater doesn't work 

### ISSUE THREAD

**Issue by borsuczyna** [multitheftauto/mtasa-blue#2607]
### Describe the bug

createWater doesn't work at all when resource is restarted, it works only when resource is already started and you join server or any water wasn't created yet 

### Steps to reproduce

1. Make simple createWater script 
2. Start resource - water will (probably) create
3. Restart resource - water will not create 

### Version

Client: 1.5.9-release-21140

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by CrosRoad95** [comment]
Any code to reproduce? any resource?

**Comment by borsuczyna** [comment]
https://pastebin.com/JdDtUGmU

**Comment by PlatinMTA** [comment]
I can't reproduce this issue. Did you try your code on a default server?

**Comment by ffsPLASMA** [comment]
Don't know why you set the position of the water elements to the same coords again but okay.
Works fine for me, might be a dimension issue?
Try to add setElementDimension(water, getElementDimension(localPlayer)) to your script or check if player and water elements are in same interior/dimension.

**Comment by patrikjuvonen** [comment]
Unable to reproduce.
