### ISSUE TITLE
Issue with setMaxPlayers, you can pass 0 as max players.

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#261]
**Describe the bug**
You shoulden't able to set 0 slots on server.

**To Reproduce**
/srun iprint(setMaxPlayers(0))

**Expected behavior**
Should print warning that said that you can set only 1 or more slots.

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/43215255-e6fadc2c-903b-11e8-9113-54ab49e941ff.png)

**MTA Client (please complete the following information):**
Working on any version

**MTA Server (please complete the following information):**
Working on any version

**Additional context**
I'm lazy, and i want to report it insted of add 2 lines of code 😂

**Comment by qaisjp** [comment]
I do not think this is a bug.

**Comment by Pirulax** [comment]
then just ignore my pr :D

**Comment by 4O4** [comment]
Well, it's not really a feature neither :)
