### ISSUE TITLE
setElementData's "subscribe" mode does seems to be sending the data to every player

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2619]
### Describe the bug

Seeing the ``Event Packet usage`` using ``performancebrowser`` shows that element data that has been set with the ``suscribe`` mode will still try to get synced to every player on the server, even if it does not have any suscriber.

I have noticed this on my own server. I had some elementdata being synced only to a few suscribed players, but on the ``performancebrowser`` they showed as being shared to every player on the server. Because of that, I made a test script:
[testSubscribe.zip](https://github.com/multitheftauto/mtasa-blue/files/8703278/testSubscribe.zip)
 
 The test script will start setting two element datas every second for an object. One key is called ``data-suscribe`` which is trying to be read by the client and shown on screen (which will always be seen as ``false`` because it's not synced). The other key is a random number from 1-1000.
 
 

### Steps to reproduce

1. Start ``testSuscribe`` or make an script that changes an element's data with ``suscribe`` mode
2. Check that the data is indeed not changing clientside
3. Open ``performancebrowser`` and go to ``Event Packet usage``
4. You will see that the server is sending updates on the element's data even tho there aren't any suscribers

![unknown (14)](https://user-images.githubusercontent.com/23291573/168678722-7263e155-a07d-4650-8605-3c51bb71385f.png)

### Version

Server: v1.5.9 r21022 WINDOWS | v1.5.9 r21203 LINUX
Client: v1.5.9 r21210

### Additional context

The packets could be shown as being sent but in reality they aren't really tried to be sent. Eitherway, this should be fixed.

Also, element datas that have been set using ``false`` mode will NOT show on the ``Event Packet usage``, implying that they are, indeed, not synced.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by tederis** [comment]
Yes, perfomance stats are wrong about subcribed element data. I'll send the fix soon.

**Comment by tederis** [comment]
Fixed in #2620
