### ISSUE TITLE
ERROR: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by stefanofabi** [multitheftauto/mtasa-blue#2622]
### Describe the bug

Error installing the latest update dated 2022-05-20  ( https://linux.mtasa.com )

SO: Ubuntu 16.04

### Steps to reproduce

See the instruccions on https://linux.mtasa.com

### Version

MTA 1.5.9 - Linux server package
R2 (build 21238) - Updated 2022-05-20

### Relevant log output

```shell
MTA:BLUE Server for MTA:SA

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/tcagame_svc2699/4evergaming/2699/x64/deathmatch.so)

ERROR: Loading mod (/home/tcagame_svc2699/4evergaming/2699/x64/deathmatch.so) failed!
Press Q to shut down the server!
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
This is a dependency issue - not an issue with MTA.

Ubuntu 16.04 is end of life since April 2021

Ubuntu 18.04 is the minimum version to support glibc 2.25, but upgrade to Ubuntu 20.04 ideally.
