### ISSUE TITLE
Crash on reconnect after replacing dff

### ISSUE THREAD

**Issue by LILERF** [multitheftauto/mtasa-blue#2626]
### Describe the bug

Version = 1.5.9-release-21240.0.000
Time = Mon May 23 15:52:43 2022
Module = C:\Program Files (x86)\MTA San Andreas 1.5\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x0004B08E

EAX=00000000  EBX=00000001  ECX=00B6BC90  EDX=00000001  ESI=00000000
EDI=FFFFFFFF  EBP=0177FD10  ESP=0177FD10  EIP=78E4B08E  FLG=00010202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

happens after replacing a dff on ped skin and /reconnec after.
it does not crash on joining or quiting!!

### Steps to reproduce

create a ped
set a skin for ped
/reconnect

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
Is this specific to a model you are using? Please provide your dff file and skin ID.

**Comment by Xenius97** [comment]
I think your dff is corrupted.

**Comment by Dutchman101** [comment]
Thanks for the report, but what really happened in your case is described in issue #2621 (last comment specifically: [here](https://github.com/multitheftauto/mtasa-blue/issues/2621#issuecomment-1134898228))

It has nothing to do with model replacement, but on the other hand, if you remember what else you or a client script was doing before disconnecting (with interiors, radio's etc) or can isolate it, please leave a comment in that issue #

@RayomDevelopmentGroup

**Comment by Lpsd** [comment]
@RayomDevelopmentGroup Hello, are you available on Discord? If so, please join our [development Discord server](https://discord.com/invite/GNN6PRtTnu) so we can investigate this issue

**Comment by LILERF** [comment]
> @RayomDevelopmentGroup Hello, are you available on Discord? If so, please join our [development Discord server](https://discord.com/invite/GNN6PRtTnu) so we can investigate this issue

Certainly. 
@ BigErf#8319
