### ISSUE TITLE
Add "servername" to setServerConfigSetting()

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2636]
### Is your feature request related to a problem? Please describe.

Add "servername" to setServerConfigSetting()
Updating server name without restarting it would be nice.

### Describe the solution you'd like

setServerConfigSetting("servername", "Default MTA Server")

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
I don't think this will ever be added: https://forum.multitheftauto.com/topic/28765-setservername-what-happened-to-it/

**Comment by PlatinMTA** [comment]
> I don't think this will ever be added: https://forum.multitheftauto.com/topic/28765-setservername-what-happened-to-it/

If that is the reason then we should probably think of adding this back.

A more reasonable excuse imo would be server name abuse on the mta masterlist.

You could, for example, change the name of your server for one of the most populars every 15 minutes or something like that.

**Comment by Lpsd** [comment]
I don't agree with adding this. There's no need to change server name so often. It will be used more for abuse than legit purposes.
