### ISSUE TITLE
CefLauncher Crashing

### ISSUE THREAD

**Issue by xMechaniC** [multitheftauto/mtasa-blue#2643]
### Describe the bug

Our server also has HTML sourced systems. When I run these systems on my server, 5 ceflaunchers are running simultaneously from the task manager. When this launcher runs, it complicates the player's client in the background and first low FPS in the game, then kicking it out of the game. We searched for the solution in many sources. We set up a default server and ran a system that only brought HTML white screen, and again 4 ceflaunchers became operational. I can't find the solution. When we start an HTML system, 5 of them are running at once, and when we stop them, 1 of them closes and 4 of them remain open. We don't know the source of the problem.

### Steps to reproduce

local sX, sY = guiGetScreenSize()
local webBrowser = false
local timer_state = 0
local theMarker = createMarker ( 1739.2626953125, -1363.521484375, 12.74843788147, "cylinder", 1.5, 179, 236, 255, 50 )
local showroom_x, showroom_y, showroom_z = 1748.5324707031, -1358.3552246094, 13.74843788147
function markerHit ( hitPlayer, matchingDimension )
	if hitPlayer == getLocalPlayer() and source == theMarker then
		showCursor(true)
		timer_state = 1
		webBrowser = createBrowser(sX, sY, true, true)
		addEventHandler("onClientBrowserCreated", webBrowser, 
			function()
				loadBrowserURL(webBrowser, "http://mta/safakroleplay-arac-galeri-sistemi/index.html")
				addEventHandler("onClientRender", root, renderPanel, true, "low-1")
				addEventHandler("onClientKey", root, onKey)
			end
		)
		addEventHandler("onClientClick", root,
			function(button, state)
				if webBrowser then
					if state == "down" then
						injectBrowserMouseDown(webBrowser, button)
					else
						injectBrowserMouseUp(webBrowser, button)
					end
				end
			end
		)
		addEventHandler("onClientCursorMove", root,
			function (relativeX, relativeY, absoluteX, absoluteY)
				if webBrowser then
					injectBrowserMouseMove(webBrowser, absoluteX, absoluteY)
				end
			end
		)
	end
end
addEventHandler("onClientMarkerHit", root, markerHit)
function onKey(button)
	if webBrowser then
		if button == "mouse_wheel_down" then
			injectBrowserMouseWheel(webBrowser, -40, 0)
		elseif button == "mouse_wheel_up" then
			injectBrowserMouseWheel(webBrowser, 40, 0)
		end
	end
end
local state_rend = 0
function renderPanel()
	if timer_state == 1 then
		if state_rend == 0 then
			state_rend = 1
			setTimer(function()
			local sayim = 1
			for k, val in ipairs(vehicleIds) do
				for i, value in ipairs(vehicles) do
					if val == value[1] then
						if sayim == 1 then
							aracGoruntule(value[1])
						end
						executeBrowserJavascript(webBrowser, "liste_doldur("..sayim..", "..value[1]..", '"..value[3].."', '"..exports.global:formatMoney(value[2]).."', '"..getVehicleNameFromModel(value[1]).."');")
						sayim = sayim + 1
					end
				end
			end
			end, 1000, 1)
		end
		dxDrawImageSection(0,0,sX,sY,0,0,sX,sY, webBrowser,0,0,0,tocolor(255, 255, 255,255))
	end
end
local goruntulenen_arac
function aracGoruntule(MODELID)
	if timer_state == 0 then return end
	destroyElement(goruntulenen_arac)
	goruntulenen_arac = createVehicle(MODELID, showroom_x, showroom_y, showroom_z +0.2)
	addEventHandler("onClientRender", root, aracRender, true, "low-1")
	setCameraMatrix(1740.9582519531, -1353.4089355469, 14.64843788147, 1746.2119140625, -1357.08203125, 13.748435974121)
end
addEvent("safakroleplay-arac-galeri-sistemi:aracGoruntule", true)
addEventHandler("safakroleplay-arac-galeri-sistemi:aracGoruntule", root, aracGoruntule)

local duration = 8000
function aracRender()
	if timer_state == 0 then return end
	setElementRotation(goruntulenen_arac, 0,0, (getTickCount() % duration) / duration * 360 )
end
setCameraTarget(localPlayer) 
function panelKapat()
	if timer_state == 0 then return end
	setCameraTarget(localPlayer) 
	destroyElement(goruntulenen_arac)
	destroyElement(webBrowser)
	webBrowser = nil
	showCursor(false)
	timer_state = 0
	state_rend = 0
	removeEventHandler("onClientRender", root, aracRender)
end
addEvent("safakroleplay-arac-galeri-sistemi:panelKapat", true)
addEventHandler("safakroleplay-arac-galeri-sistemi:panelKapat", root, panelKapat)

function satinalmaBitir()
	panelKapat()
	timer_state = 0
end
addEvent("safakroleplay-arac-galeri-sistemi:satinalmaBitir", true)
addEventHandler("safakroleplay-arac-galeri-sistemi:satinalmaBitir", root, satinalmaBitir)

function CsatinAl(MODELID)
	if timer_state == 0 then return end
	for i, value in ipairs(vehicles) do
		if value[1] == tonumber(MODELID) then
			--local color1, color2, color3, color4 = getVehicleColor(goruntulenen_arac)
			local col = { getVehicleColor(goruntulenen_arac) }
			triggerServerEvent("safakroleplay-arac-galeri-sistemi:satinAl", localPlayer, localPlayer, MODELID, value[3], value[2], col)
		end
	end
end
addEvent("safakroleplay-arac-galeri-sistemi:CsatinAl", true)
addEventHandler("safakroleplay-arac-galeri-sistemi:CsatinAl", root, CsatinAl)

### Version

Multi Theft Auto v1.5.9-release-21244
Copyright (C) 2003 - 2022 Multi Theft Auto

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
You have a logic issue whereby `webBrowser` is being overwritten with each browser being created, so you lose the 'reference' to the previously created browsers; therefore being unable to destroy them. 

You should use a table to store the browser elements, and loop this table when you want to destroy them.

Anyway - GitHub isn't for general scripting support. You should join the [Discord ](https://discord.com/invite/mtasa) and post in one of the #scripting-help channels.
