### ISSUE TITLE
Gunfire effect doesn't show

### ISSUE THREAD

**Issue by ElPendejoN** [multitheftauto/mtasa-blue#2646]
### Describe the bug

I've been in multiple servers, including default MTA servers, and an RPG.

Every time a player shoots, his gun doesn't show the gunfire effects as if it was only enabled client-sided, although, in some servers where the effect is modded, it does show, and if you test with PEDs they show it too.

Credits to Hex for peer review/testing
examples:

modded server:
https://cdn.discordapp.com/attachments/468783796750254100/971449313798529074/MedalTVGrandTheftAutoSanAndreas20220504123159.mp4

Without mod server:
https://cdn.discordapp.com/attachments/468783796750254100/971448115875942400/MedalTVGrandTheftAutoSanAndreas20220504122526.mp4

PED testing by Hex

https://cdn.discordapp.com/attachments/468783796750254100/971450624795349062/unknown.png

### Steps to reproduce

Go to any server to reproduce the bug, and invite a friend to be your test subject.

### Version

Any version as far as I know

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by lopezloo** [comment]
Looks like it was fixed in 80b17d96097c6977915c91f31ae2161a1bce1fdc. Please retest on [latest nightly](https://nightly.mtasa.com/).

**Comment by lopezloo** [comment]
Fixed in 80b17d96097c6977915c91f31ae2161a1bce1fdc.
