### ISSUE TITLE
Bug MTA  Version 1.5.9

### ISSUE THREAD

**Issue by AzevedoUnico** [multitheftauto/mtasa-blue#2648]
### Describe the bug

Olá encontrei recentemente o bug de resolução de pixels no mta versão 1.5.9, as opção disponíveis são somente de x32 e as outras opções de x16 estão  com as resoluções totalmente bagunçada e bugada.

### Steps to reproduce

4

### Version

Client v1.5.9-release-21140 (Windows 10, 64-bit)

### Additional context

[https://i.imgur.com/bxaXtdpl.png?1](url)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Please use the [MTA Discord](https://discord.com/invite/mtasa) and post in the #help-support channel

**Comment by PlatinMTA** [comment]
![image](https://user-images.githubusercontent.com/23291573/174929985-c991dc20-d3f0-439e-8531-843641bdda14.png)
This is the image he tried to post btw
