### ISSUE TITLE
Corrupted archive multitheftauto_linux_x64.tar.gz

### ISSUE THREAD

**Issue by DicoSky** [multitheftauto/mtasa-blue#2653]
### Describe the bug

Hi
i think there is a bug in this archive : https://linux.mtasa.com/dl/multitheftauto_linux_x64.tar.gz
my host can't extract the files , and when i download the file on windows and add everything on archive zip , its working.

this something happend just recently and i tested the extract for many types (zip , tar , tar.gz , .gz).
just this archive where i got the problem.

this archive is working too (https://linux.mtasa.com/dl/baseconfig.tar.gz) so the problem is only in this (https://linux.mtasa.com/dl/multitheftauto_linux_x64.tar.gz)

### Steps to reproduce

just archive on the web

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Archive is not corrupted. I can easily download and extract every single file. mta-server64 is also working well

Maybe it got corrupted during a downloading somehow?

**Comment by Lpsd** [comment]
Works fine for me, can you specify what you mean by corrupted? How have you come to this conclusion?

Can you provide md5/sha256 checksum of the file as it exists on your machine?

Also

> my host can't extract the files

What exactly are you running to extract it? Any errors / warnings?

**Comment by Disinterpreter** [comment]
Can't reproduce.


https://user-images.githubusercontent.com/3816155/176736047-9239c923-61b4-4826-b3ad-be7e3b79f1ce.mp4

**Comment by DicoSky** [comment]
Oh it was because the archive type was changed , so rather than using this command ( -xzvf multitheftauto_linux_x64.tar.gz)  i change it to this ' -xvf multitheftauto_linux_x64.tar.gz) and it works.

**Comment by patrikjuvonen** [comment]
> Oh it was because the archive type was changed , so rather than using this command ( -xzvf multitheftauto_linux_x64.tar.gz) i change it to this ' -xvf multitheftauto_linux_x64.tar.gz) and it works.

Thanks for the update, it seems the archive was actually not gzip compressed, only a plain tar archive. They should be gzip compressed now, but no reason to use the -z option when extracting anyway, as it's just an explicit way to force tar to use a specific decompression algorithm.
