### ISSUE TITLE
Upgrade from tinyxml to pugixml

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#267]
**Is your feature request related to a problem? Please describe.**
TinyXML development has stopped and all development has moved to TinyXML-2.

**Describe the solution you'd like**
@sbx320 opened a branch to upgrade to _pugixml_ and seems to have done a lot of progress on it.

**Describe alternatives you've considered**
[TinyXML-2](https://github.com/leethomason/tinyxml2)

**Additional context**
Is there a specific reason why the branch has not been merged in yet?

**Comment by qaisjp** [comment]
Card already here https://github.com/multitheftauto/mtasa-blue/projects/5#card-11515474
