### ISSUE TITLE
MTA does not render grass correctly

### ISSUE THREAD

**Issue by TFP-dev** [multitheftauto/mtasa-blue#2677]
### MTA grass rendering:
![mta-screen_2022-07-22_09-01-57](https://user-images.githubusercontent.com/72511827/180405696-0d307858-e555-49d9-b13e-265558537809.png)
### MTA grass rendering without "HOOK_CPlantMgr_Render" in CMultiplayerSA:
![mta-screen_2022-07-22_08-45-25](https://user-images.githubusercontent.com/72511827/180405986-efcfdc15-acee-4c8d-a3c6-22b037f20d5e.png)

As you can see, there is less grass rendered in current version of MTA.

### Steps to reproduce

None

### Version

Current

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Able to add comparisons for vanilla SA?

**Comment by TFP-dev** [comment]
> Able to add comparisons for vanilla SA?
![Screenshot_5](https://user-images.githubusercontent.com/72511827/180414615-e3c8ff04-eca8-4683-9abc-80f9eba41cac.png)
