### ISSUE TITLE
Rocket launcher projectiles spawn too many effects on high fps

### ISSUE THREAD

**Issue by Merlin** [multitheftauto/mtasa-blue#2688]
### Describe the bug

Rocket launcher projectiles spawn too many effects on high fps

### Steps to reproduce

Shoot a rocket launcher

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by forkerer** [comment]
Mentioned also in project related to FPS issues:
https://github.com/multitheftauto/mtasa-blue/projects/14
