### ISSUE TITLE
Wheels spawning too many surface effects on high fps

### ISSUE THREAD

**Issue by Merlin** [multitheftauto/mtasa-blue#2690]
### Describe the bug

Driving on certain surfaces makes the wheel spawn way too many effects on high fps

### Steps to reproduce
Enable "Tyre Smoke etc" option in video settings.
Drive on grass, sand etc. with high fps.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by forkerer** [comment]
Mentioned also in project related to FPS issues:
https://github.com/multitheftauto/mtasa-blue/projects/14
