### ISSUE TITLE
Stuntplane and Cropduster spawning too many smoke trail particles on high fps

### ISSUE THREAD

**Issue by Merlin** [multitheftauto/mtasa-blue#2692]
### Describe the bug

Activating smoke trail on stuntplane or cropduster will spawn too many particles on high fps.

### Steps to reproduce

Activate smoke trail in stuntplane on high fps

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by forkerer** [comment]
Mentioned also in project related to FPS issues:
https://github.com/multitheftauto/mtasa-blue/projects/14
