### ISSUE TITLE
Add `colorCoded` to event `onClientChatMessage`

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2701]
### Is your feature request related to a problem? Please describe.

If you want to something like adding timestamps to your server (like this resource does: https://community.multitheftauto.com/?p=resources&s=details&id=18737), you will be unable to know if the message was inteded to have colorcoded activated or not. This could lead to have undesired effects on texts that should not display hexadecimal text as color.

Adding an argument will fix this issue.

### Describe the solution you'd like

Add `colorCoded` to ``onClientChatMessage`, making it have these paraments:

```lua
string text, int r, int g, int b, int messageType, bool colorcoded
```

### Describe alternatives you've considered

None.

### Additional context

https://community.multitheftauto.com/?p=resources&s=details&id=18737

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Lpsd** [comment]
Duplicate of #2635
