### ISSUE TITLE
Camera Shake stay after disconnect

### ISSUE THREAD

**Issue by etrnl1337** [multitheftauto/mtasa-blue#2709]
### Describe the bug

setCameraShakeLevel sets shake level globally i.e. let's say you use this on local server then come back to any online server and your camera is shaking.

TODO:
setCameraShakeLevel to 0 for client after disconnect/reconnect.

It is very easy to block on any online server just by setting setCameraShakeLevel(0) onClientResourceStart but i think it should not be working by default.

### Steps to reproduce

1. Go to local server or any server
2. use crun setCameraShakeLevel(255)
3. Go to another server
4. Boom! your camera is shaking!

### Version

Multi Theft Auto v1.5.9-release-21261

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Unable to replicate. Using this script on local server:

```lua
function setCameraShakeCommand(cmd, amount)
    amount = tonumber(amount) and math.max(0, math.min(255, amount)) or 0
    setCameraShakeLevel(amount)
end
addCommandHandler("shake", setCameraShakeCommand)
```

Methods attempted:

1) `/shake 255` -> `/reconnect`
2) `/shake 255` -> Escape -> Disconnect -> Server Browser -> Connect to any public server
3) `/shake 255` -> Escape -> Server Browser -> Connect to any public server

Servers tried:

- local
- mtasa://54.38.29.219:22014
- mtasa://45.125.66.147:22002

**Comment by lopezloo** [comment]
Reproduced. Looks like it resets on player spawn but it doesn't on server join. Only `runcode` needs to be running to reproduce that.

Repro:
```lua
crun setCameraShakeLevel(255)
```
reconnect
```lua
crun fadeCamera(true)
```

**Comment by Lpsd** [comment]
Ah right, so it's the spawnPlayer which resets the shake level (had `play` running). Reproduced also

**Comment by etrnl1337** [comment]
> Reproduced. Looks like it resets on player spawn but it doesn't on server join. Only `runcode` needs to be running to reproduce that.
> 
> Repro:
> 
> ```lua
> crun setCameraShakeLevel(255)
> ```
> 
> reconnect
> 
> ```lua
> crun fadeCamera(true)
> ```

Exactly. When i've used crun on local and returned to my online server camera was still shaking, but after i've logged in and spawned camera shake level reseted. Later i'll check if any other camera effect stays on too.

**Comment by Lpsd** [comment]
I have submitted a pull request for this issue already, see above. If you find other issues please report them separately.
