### ISSUE TITLE
Mta Vehicle Bug

### ISSUE THREAD

**Issue by ilkerakbulut** [multitheftauto/mtasa-blue#2712]
### Describe the bug

i am using car mods in my server but my server vehicles is bugged video : [https://drive.google.com/file/d/1TNomtKkl3FIm2RU1gT7w7R8QR6lmJKj0/view?usp=sharing]

### Steps to reproduce

a

### Version

1.5.9 win10pro

### Additional context

a

### Relevant log output

```shell
no log
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by lopezloo** [comment]
That link doesn't work. Please set visibility settings to public and provide more information about this issue.

**Comment by ilkerakbulut** [comment]
https://drive.google.com/file/d/1TNomtKkl3FIm2RU1gT7w7R8QR6lmJKj0/view try this
