### ISSUE TITLE
Objects stream limit change

### ISSUE THREAD

**Issue by FiloniJ** [multitheftauto/mtasa-blue#2717]
### Is your feature request related to a problem? Please describe.

On my server I have very many objects and often stream is loaded maximum with 500 objects (no LODs). For powerful PC it's not problem, but players with slow PC will drop their FPS.  And without it it's hard for SAMP players play in MTA because need more power PC, but with max stream loading with objects make game more worse.

### Describe the solution you'd like

Need server and client function for change max number of objects that will be streaming in render. 500 objects for weak PC is very many. Need common function on server and on clientside for use it on weak PC. Not MTA settings, only MTA function for developers.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Allerek** [comment]
https://wiki.multitheftauto.com/wiki/SetFarClipDistance
Just use this to cut render distance.

**Comment by FiloniJ** [comment]
> https://wiki.multitheftauto.com/wiki/SetFarClipDistance Just use this to cut render distance.

It's not fully decide my problem. I want save default render distance of default objects and reduce amount of objects in render that was created by MTA. Because MTA objects require more CPU power than default objects.

Here is no and function for change render distance of certain object. Can change render distance only of certain model.

**Comment by FiloniJ** [comment]
> https://wiki.multitheftauto.com/wiki/SetFarClipDistance Just use this to cut render distance.


It's not fully decide my problem. I want save default render distance of default objects and reduce amount of objects in render that was created by MTA. Because MTA objects require more CPU power than default objects.

Here is no and function for change render distance of certain object. Can change render distance only of certain model.

**Comment by FiloniJ** [comment]
1
