### ISSUE TITLE
"New" shadows flicker when they are far away from the camera, add an option to change them

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2723]
### Is your feature request related to a problem? Please describe.

On #1699, TFP worked on a setting that let you lower the shadows in game. Original SA has the shadows a bit too high. This fix works and makes shadows not appear floatty, but this makes them flicker.

There were plans to add a function to change the shadows height, or at least let the client decided whenever they would want the fix or not.

#2018 added this, but without an option to toggle it, since botder argued that this was a general improvement and no one would want it to be disabled. I disagree, because since this change I have been noticing a lot of flickering on far away shadows. I'm 90% sure this didn't happen before, but I could be wrong since this change was added so far ago.

https://user-images.githubusercontent.com/23291573/187042864-c3c0673d-73a6-4b91-88a7-4a3501a00bb1.mp4

We should have an option to enable or disable this, or even better, set the shadow height to whatever we want.

### Describe the solution you'd like

Consider adding the setting proposed on #1699.

### Describe alternatives you've considered

Alternatively add a clientside function in which we can set the shadows height.

### Additional context

This visual error COULD be happening for other reason that #2018 (particulary that broken traffic light), I didn't test older versions and I didn't try to compile MTA with the default shadows. If you have encountered this issue, please let me know.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Pirulax** [comment]
That just seems to be Z fighting, which yes, is most likely why they were higher off the ground originally.
I guess not much can be done about it, but I do agree that, in light of this, it the option should be opt in instead of opt out by default.

**Comment by TFP-dev** [comment]
I knew there could be problems with this, so I wanted to add it as an option in the settings.

**Comment by Pirulax** [comment]
Most people aren't knowledgeable enough to figure out this causes the issue, and I'm pretty sure most of them find this annoying when it happens, so I stand by my above comment.

**Comment by thisdp** [comment]
maybe caused by collisions doesn't match the dff, and thus it causes Z fighting.
