### ISSUE TITLE
Bugged area while mapping

### ISSUE THREAD

**Issue by semisuno** [multitheftauto/mtasa-blue#2729]
### Describe the bug

Im creating a map and at this specific part, the wallride doesnt seem to spawn in until i warp again to that spot to load it.
Without testing the map too you are able to go to that spot and notice that it doesnt spawn in until u wait a few seconds

I have tried to fix this bug by moving the whole map's location using XYZ and it still happens
I have also tried to delete the wallride and add a new one / tried also to make an entirely different part but the bug still happens at that same spot
I have also tried to again make something new on the map while its in a different location but nope
I have also tried to remove every single script in the map and try that part again but also nope

https://user-images.githubusercontent.com/62650128/188657364-0eebb133-9346-4a00-ae83-49eacc5f9e94.mp4

### Steps to reproduce

i have yet to find out the reason. no matter what i do to the map, that spot is always bugged

### Version

Multi Theft Auto v1.5.9-release-21261
Copyright (C) 2003 - 2022 Multi Theft Auto

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by semisuno** [comment]
[themap.zip](https://github.com/multitheftauto/mtasa-blue/files/9497790/themap.zip)

i have attached the map that causes this
the bug happens at around XYZ: 6158.3701171875,  -3351.3740234375,  4036.5571289062

**Comment by etrnl1337** [comment]
Try
https://wiki.multitheftauto.com/wiki/SetElementStreamable

**Comment by patrikjuvonen** [comment]
> Try https://wiki.multitheftauto.com/wiki/SetElementStreamable

That, or something like https://community.multitheftauto.com/index.php?p=resources&s=details&id=18113 could work. I think streaming is a common issue for race maps - maybe something other creators would be able to help with? I tested draw-distance resource on this map and seems to work.
