### ISSUE TITLE
Dynamic ped shadows

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#2736]
### Is your feature request related to a problem? Please describe.

In MTA, peds (and players) are always using static shadows. In single player, it's based on visual quality option.

### Describe the solution you'd like

Enable dynamic shadows for peds and players and add new checkbox in visual settings for that.

### Additional context

I requested this feature many years ago at bugs.mtasa.com and it was rejected but to be honest I still don't quite understand why. I think it's possible to implement it.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Haxardous** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/6b854c4e31d229ac17b9b8fec96546daa90390b7/Client/game_sa/CSettingsSA.cpp#L360

Attempted to disable that check, not sure if they're different than volumetric shadows but they have a different look in SP.

(disabled blob shadows)
![image](https://user-images.githubusercontent.com/30158626/189558659-32ccf33e-b2b3-4a18-a40e-f9075b3cf0a6.png)

(singleplayer, very high settings)
![image](https://user-images.githubusercontent.com/30158626/189559036-3f6f7167-40f1-4599-8946-906c1819c056.png)

**Comment by lopezloo** [comment]
> Attempted to disable that check, not sure if they're different than volumetric shadows but they have a different look in SP.

I got similar response from @ccw808 years ago - "context switching issues". But I don't understand what issues exactly. Maybe it produces crashes or something. These shadows are disabled in SA-MP aswell.

In single player, these dynamic shadows are enabled for player ped only when visual quality option is set to "high". When quality is set to "very high", these are also enabled for non-player peds. In MTA, there are context switches and non player peds are sometimes processed as player ped, right? Maybe that was the cause. But if so, then we could just make it working for every ped (when enabled in MTA settings).

I have quickly commented a bit of code and it seems to be working only for the last created ped. But in single player, it's possible for many peds to have these shadows.

**Comment by ffsPLASMA** [comment]
Two possible reasons why its disabled:

1) The dynamic shadows do not work on custom placed objects.

2) Theres a hardcoded limit on how many dynamic shadows can be drawn at once which could easily be reached with a specific amount of people in multiplayer.

Both could results visual bugs or crashes, but maybe ccw can answer that for us.

**Comment by lopezloo** [comment]
I made some progress:
https://streamable.com/d8qdfo

Works properly so far. Currently testing it more. The limit is ~15~ 16 shadows, after that it starts rendering blob shadows.
