### ISSUE TITLE
Broken sync

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2742]
### Describe the bug

Sync is broken since 09.13. ~9:00PM (gmt+2)
Tested multiple times, don't know what's wrong. On foot sync works fine. No new scripts.

Server settings (now):
```
<bandwidth_reduction>maximum</bandwidth_reduction> (since 2016)
<player_sync_interval>100</player_sync_interval>
<lightweight_sync_interval>1500</lightweight_sync_interval>
<camera_sync_interval>500</camera_sync_interval>
<ped_sync_interval>100</ped_sync_interval>
<unoccupied_vehicle_sync_interval>1000</unoccupied_vehicle_sync_interval>
<keysync_mouse_sync_interval>100</keysync_mouse_sync_interval>
<keysync_analog_sync_interval>100</keysync_analog_sync_interval>
<bullet_sync>1</bullet_sync>
<vehext_percent>0</vehext_percent>
<vehext_ping_limit>150</vehext_ping_limit>
<latency_reduction>0</latency_reduction>
<busy_sleep_time>0</busy_sleep_time>
<idle_sleep_time>10</idle_sleep_time>
```

### Steps to reproduce

https://streamable.com/0f1z4q

Sometimes happens only when playeres goes faster than a speed (eg.: over 150km/h)

### Version

MTA:SA Server v1.5.9-release-21318 (updated today, old: 21261)
Multi Theft Auto v1.5.9-release-21299 (21244 has this issue too)

### Additional context

Only 10 / 3 player sync is bugged like in the video.

### Relevant log output

```shell
No server error logs, no lagg. Specs: i9-9900k 5ghz, 32gb ram, SSD
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
This can't be confirmed, and is likely a result of something on your server (as many times in the past when you were confident otherwise). Especially given that

> Multi Theft Auto v1.5.9-release-21299 (21244 has this issue too)

r21244 is older than our previous main release, which was r21261 and has been that for almost 2 months, with no one else reporting something like this. The start of this issue on your server last week doesn't add up then, and besides that it started on a similarly old or older server version as you initially thought it may have been uptime related (20days+)

So just to say this won't prompt investigation for recent changes

**Comment by Xenius97** [comment]
Tested with server version 21290 and 21318, same issue. 21292/21295 instant crash on server start.
Here is a new video to confirm this issue, 2 different players with same vehicle. One has bad sync, second has no issues.
https://streamable.com/psv29u
Crash dumps: https://upload.mtasa.com/u/720902310/dumps.zip_

I've test with latest client 21299 and 21244 and same issue. Saw yesterday once on FFS server too, but have no video about that.

**Comment by Dutchman101** [comment]
> 21292/21295 instant crash on server start

That crash is unrelated and got fixed in 6220faa3

> Tested with server version 21290 and 21318, same issue. 21292/21295 instant crash on server start. Here is a new video to confirm this issue, 2 different players with same vehicle. One has bad sync, second has no issues. https://streamable.com/psv29u Crash dumps: https://upload.mtasa.com/u/720902310/dumps.zip_
> I've test with latest client 21299 and 21244 and same issue. Saw yesterday once on FFS server too, but have no video about that

I didn't need to watch that because of the thing i previously explained. Let me put it in another way: there have been tens of thousands of players on r21261 for the past 2 months (also for the same period, many servers started using it as it was the main release - regarding your statement `MTA:SA Server v1.5.9-release-21318 (updated today, old: 21261)`) and that build 21244 is already older. Sync on your server got broken in the past week

Any server issue that's behind this can lead to 2 players having a different result, depending on its nature

**Comment by Xenius97** [comment]
> Any server issue that's behind this can lead to 2 players having a different result, depending on its nature

That guy, who was on video, i've ask him to restart his client. After restarting client & reconnecting he has no issues. No server update come in past week. Don't know what cause this bug, but i think, script can't cause something like that. (we have reset all source code to prevorius update which have no issues)
Something is wrong, and don't know what's this. I think the problem is not at us.

**Comment by Xenius97** [comment]
Tried to reproduce with default MTA resources, could only produce this now: https://streamable.com/osfnbv 
Everyone had vehicle, only bugged for him, but maybe this is different issue. (up to date everything, no script errors)

**Comment by Dutchman101** [comment]
> Any server issue that's behind this can lead to 2 players having a different result, depending on its nature
>> After restarting client & reconnecting he has no issues
>> Don't know what cause this bug, but i think, script can't cause something like that

Clientside scripts decide for themselves when to execute what, so of course a player can enter a bugged state at a random or specific moment (depending on the bug and all circumstances).

The relevant discussion on dev discord: [https://imgur.com/a/tSjpxQO](https://imgur.com/a/tSjpxQO) (click to zoom) has some valuable feedback on this matter. It's not even neccesarily an easily spottable script mistake, it may be any complex interaction with your server's environment. Like i did in past comments, the discussion reinforces that we work facts/evidence based and that this issue triage means we can't do much with this report until more comes to light.

**Comment by Xenius97** [comment]
Today caught on FFS Gaming too, hard to reproduce but somehow i've start recording in good time.
https://streamable.com/2g4p7b

**Comment by Xenius97** [comment]
A guy write in hungarian chat, a player have sync lagg. When i was spectating him, i see too. New record: https://streamable.com/spr1wo

**Comment by Lpsd** [comment]
and is it not possible this player (who has inconsistent ping) also has packet loss? 

Also, regarding your previous FFS video, that could also be the same thing (packet loss at the start). I actually don't see an issue with the dinghy, can you provide a better explanation of what's wrong in that video aside from the start where it takes a few seconds to sync?

**Comment by Xenius97** [comment]
On our server happens also when player has no packet loss, same as saw in other videos. Ping is okay, no server / client packet loss and moving laggy. Sometimes changing vehicle model or entering/exit vehicle solves it, sometimes not. We test it on default MTA server too, and had desync. (proof in comments). It's not local bug, cause when someone desync it will desync for everyone (everyone see the same laggy move)

**Comment by Lpsd** [comment]
How have you identified the packet loss of players on servers you don't manage?

**Comment by Lpsd** [comment]
If that player had packet loss, then everyone would see the same lag too. Again, just trying to go off the facts here so let's stick to em and not bend the truth. We want to help but can only do that with accurate info.

**Comment by Lpsd** [comment]
Have you considered to approach the servers to see if they're willing to help? It will certainly increase your chances of finding the issue

**Comment by Xenius97** [comment]
Look like 21326 or Windows Update solved, don't know how but it works.
