### ISSUE TITLE
New animation functions and improvement for current ones

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#275]
**Is your feature request related to a problem? Please describe.**
- [ ] **1.** When you load an IFP file, there's no way to know what animations are loaded. You have to keep a track of animation names, which can sometimes be really frustrating, same thing goes for internal default animations, there's no way to know how many animations already exist and their names.
- [x] **2.** There's no way to modify animation speed. 
- [ ] **3.** `engineReplaceAnimation` requires you to replace animation for every ped individually, it's useful sometimes but sometimes it's not. 
- [x] **4.** `engineReplaceAnimation` does not immediately apply animation, it requires you to switch to another animation, and then switching back to the replaced animation will play the new animation.
- [ ] **5.** A function to get all animation block names.

**Describe the solution you'd like**
**1.** Add a new function `getBlockAnimations`. This function should take a string as parameter for block name and return a Lua table containing all animations for that block.
**2.** Add a new function `setPedAnimationSpeed` and `setPedAnimation` should take an extra parameter for animation speed. 
**3.** If first parameter is not provided, i.e., ped, then `engineReplaceAnimation` should replace that animation for all players and server-side peds within the server.
**4.** The fix is pretty simple, when `engineReplaceAnimation` is called, simply get the animation association, delete its animation blend nodes `pAnimAssociation->pAnimBlendNodeArray` by calling `CAnimBlendAssociationSAInterface::FreeAnimBlendNodeArray`, and then reinitializing the same animation association with the new animation hierarchy by calling its constructor.
**5.** Add a new function `getAnimationBlocks`. This function should take first parameter as bool to include IFP blocks or not, and return the animation block names in a Lua table.

**Additional context**
These requested features related to animations are very useful, especially the 4th one.

**Comment by qaisjp** [comment]
You might find [Projects](https://github.com/multitheftauto/mtasa-blue/projects) useful for this :P

**Comment by ghost** [comment]
Sure, I could use that. I need to get a hang of it :D
