### ISSUE TITLE
Gang driveby on bikes disables player collisions

### ISSUE THREAD

**Issue by SScorpyo** [multitheftauto/mtasa-blue#2754]
### Describe the bug

Apparently using `setPedDoingGangDriveby` on a player who is riding an NRG-500 or an FCR-900 disables their ped collisions and you are no longer able to damage them.  (Not sure if this happens with any other bikes )

### Steps to reproduce

1. Get a player to ride an NRG-500
2. Run `setPedDoingGangDriveby(player, true)`
3. Shoot the player
No damage will be received

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by PlatinMTA** [comment]
Duplicate of #556

Drive-by in general works really bad

**Comment by lopezloo** [comment]
Duplicate of #556
