### ISSUE TITLE
Serial number

### ISSUE THREAD

**Issue by EternalSleep88** [multitheftauto/mtasa-blue#2758]
### Describe the bug

Hi all. The situation is the following. I had a PC, I played MTA on it, but my brother also had a PC, one for two, but 2 hard drives. I recently moved, took my hard drive away and bought a new PC. I installed MTA there and my brother and I decided to play, but then one of us could not enter the server with an error "this account is already in use" or something like that. The bottom line is that then I started the proceedings and found out that we have 2 completely different computers, different nicknames in the MTA, but one serial number for two. Can MTA support somehow change it? Or do something so that we can play together on the server. Bans never happened for nothing. 
It's not our fault that the serial number is assigned somehow in its own way for MTA users.

Всем привет. Ситуация следующая. У меня был ПК, на нём я играл в MTA, но пк также был и моего брата, один на двоих, но 2 жестких диска. Недавно я переехал, забрал свой жёсткий диск и купил новый ПК. Установил туда MTA и мы с братом решили поиграть, но далее один из нас не мог зайти на сервер с ошибкой " данный аккаунт уже используется" или по типу того. Суть в том, что далее я начал разбирательство и выяснил, что у нас 2 совершенно разных компьютера, разные ники в МТА, но один серийный номер на двоих. Может ли поддержка MTA как-то его поменять? Либо сделать что-нибудь, чтобы мы могли играть вдвоём на сервере.  Банов никогда и не за что не было. Мы ведь не виноваты, что серийный номер присваивается как-то по своему для пользователей MTA.

### Steps to reproduce

Please read and help
Пожалуйста прочтите и помогите

### Version

v.1.5.9 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
GitHub is not suitable for this kind of support query. Please head over to the community Discord (https://mtasa.com/discord).
