### ISSUE TITLE
Camera (weapon) image compression

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2759]
### Is your feature request related to a problem? Please describe.

In this case, the problem is that photos taken by camera are highly compressed. Propably due to limited space on PS2 memory cards. 
F.e. one of the below images is Screenshot(F12) and the other one is actual photo.
Screenshot is around ~2MB, while photo is around 200 KB
[Screenshot]
![mta-screen_2022-09-20_21-24-25](https://user-images.githubusercontent.com/12304071/191348149-95e59eac-57b7-4707-890d-925cb09a3923.png)
[Photo]
![gallery3](https://user-images.githubusercontent.com/12304071/191348289-f529c98c-5157-4443-8cd5-26e44ea9610a.jpg)

### Describe the solution you'd like

Prevent photo compression, its no longer needed due to high disk capacities now.

### Describe alternatives you've considered

Instead of trying to fix GTA:SA way of taking photos, just recreate entire function from scratch using modern libraries and solutions.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by lopezloo** [comment]
GTA also captures wrong screen area when game is running in windowed mode and window is scaled by system:

![gallery271](https://user-images.githubusercontent.com/7338099/220684117-87eb1dd3-52b3-4a06-9c78-752f55c89549.jpg)
