### ISSUE TITLE
crashando 

### ISSUE THREAD

**Issue by LEOMCR** [multitheftauto/mtasa-blue#2763]
### Describe the bug

portugue: entro em algum server e o mta fecha ou para de funcionar do nada depois da atualização e não consigo jogar mais English: I join a server and the mta closes or stops working out of nowhere after the update and I can't play anymore

### Steps to reproduce

1 abra o jogo 2 tente entrar em algum server 
1 open the game 2 try to join some server

### Version

v1.5.9

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by lopezloo** [comment]
Please post here for support: https://forum.multitheftauto.com/forum/83-client/
