### ISSUE TITLE
dxSetShaderValue accepts only 16 floats

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#277]
**Describe the bug**
https://github.com/multitheftauto/mtasa-blue/blob/bee6c7f245e962541e07a2abfe7ae41ea31f2d73/Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp#L952
Maybe there is a better solution for this, because, this way I cant push my 18(or if I get ps_3_0 working 200) values to an array.

**Comment by jushar** [comment]
I assume it's set to 16, because it's only used for 4x4 matrices. What do you need it for exactly?

**Comment by Pirulax** [comment]
Nah, I solved it differently at the end.
But I wanted to pass 18 numbers to an array in the shader
`iVar[18]`

**Comment by qaisjp** [comment]
@Pirulax for others reading this issue, please can you describe how you solved the problem?

**Comment by Pirulax** [comment]
Actually, I haven't solved it the way you think.
I just used a different idea at the end.
So, the issue can be reopened to solve this, because sometimes there is a need to pass more than 16 floats.
In my case for example, or for a shader that my friend made(It manipulated the positions of bones(actually, only the texture))
There are 90 bones if i remembered it correctly.
Look at [this ](https://forum.mtasa.com/topic/103727-help-tables-as-shader-value/?tab=comments#comment-899753)topic for more info.
He still haven't solved it.

**Comment by Pirulax** [comment]
@qaisjp
