### ISSUE TITLE
Kicking player after redirecting

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#2774]
### Describe the bug

If you kick player after player got redirected to an another server hides an ip and port of the server player got redirected

### Steps to reproduce

just execute this command:
```lua
addCommandHandler("redirect", function()
  local plr = getRandomPlayer()
    redirectPlayer(plr, "ip of some server", 22003)
  kickPlayer(plr)
  print("ok?")
end)
```
if you kick player after redirect, you will not be able to see an ip of redirect

### Version

server: v.1.5.9-release-21331

### Additional context

![image](https://user-images.githubusercontent.com/22455534/193592204-71f9b782-3c95-4b7e-a289-0322a186dd97.png)

### Relevant log output

```shell
/
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TeteX1** [comment]
Kicking a player who is being redirected to another server appears to be a highly unusual scenario. Although it's unclear why someone would want to kick a player immediately after redirecting them, I thought it might be a good idea to create a future-proof fix for this issue on #2955. This fix also introduces a new function to check if a player is being redirected, which could be useful in addressing other bugs or adding new features in the future.
