### ISSUE TITLE
Make volumetric shadows slighty darker

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#2778]
### Is your feature request related to a problem? Please describe.

Volumetric shadows look ugly IMO. These would look a lot better if were blurred and little darker like blob shadows and dynamic ped shadows. Blurring them may be hard but changing their color is one byte change.

### Describe the solution you'd like

Make volumetric shadows a bit darker, maybe? It would be a _breaking_ (?) change, like, it would be different than it is in single player, so we could discuss that but I think these would seriously look better.

### Additional context

This is how blob shadows look: https://i.imgur.com/IdIy20b.png
This is how it looks now (initial alpha set to 50): https://i.imgur.com/Mu1gEVL.png
This is how it looks with alpha set to 95:
https://i.imgur.com/xpB4Eeq.png
https://i.imgur.com/WqZ61bd.png

This is how it looks with alpha set to 85:
https://i.imgur.com/FKnUPBS.png

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Lpsd** [comment]
Does this have to be a 'breaking' change? Surely we can have a function to enable/disable this (disabled by default)?

Edit: could have a function to set the shadow alpha?

**Comment by lopezloo** [comment]
We could introduce a function for that but I'm more interested in altering default behaviour.

**Comment by PlatinMTA** [comment]
I would only like this if server owners are the ones to opt in to use this new settings. We should avoid making the same mistake we made with the lowering of shadows (even if no z-fighting would occur because of this change).

**Comment by lopezloo** [comment]
> Edit: could have a function to set the shadow alpha?

We could introduce cvar for that. That way it wouldn't be breaking change.
