### ISSUE TITLE
Blip size is not checked the same way as on server-side

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#278]
**Describe the bug**
You can create a blip with size over 25, which is what the limit is server-side. Code is inconsistent.

**To reproduce**
- `createBlip( 0, 0, 3, 0, 500 )` -> works
- `createBlipAttachedTo( localPlayer, 0, 500 )` -> works
- `setBlipSize( blip, 500 )` -> works

**Expected behavior**
Clamped between 0 and 25.

**Screenshots**
![mta-screen_2018-07-29_20-05-55](https://user-images.githubusercontent.com/22572159/43368747-d7fe263e-936a-11e8-9d86-fb06d2060b87.png)

**MTA Client & Server:**
- Multi Theft Auto v1.5.5-release-13816
- Windows 10.0.17134.165

**Additional context**
- Discovered by **zHooP** on Discord. Thanks.
- This bug has been in the client code forever.
- Better to make it backwards compatible and clamp the size instead of returning false upon invalid size.

**Comment by qaisjp** [comment]
What do you think about also throwing a warning if the size exceeds the limits?

**Comment by patrikjuvonen** [comment]
That sounds like a fair enough addition, but that should be added only client-side, as that is the only part affected.

**Comment by qaisjp** [comment]
fixed in #279 

[p.s. @patrikjuvonen](https://help.github.com/articles/closing-issues-using-keywords/)
