### ISSUE TITLE
Set process priority automatically

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2780]
### Is your feature request related to a problem? Please describe.

Configurable process priority in mtaserver.conf which set automatically when starting server just like in Client -> Advanced (Windows Server)

### Describe the solution you'd like

mtaserver.conf:
<process_priority>high/normal/realtime/above_normal</process_priority> (everything, except low)

### Describe alternatives you've considered

setServerProcessPriority() or add to setServerConfigSetting

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Lpsd** [comment]
Usage of a function would require restarting the server.

Linux needs to be considered also

Why can't you just write a shell script to start your server with?

```
start "MTA Server" /high "c:\path\to\MTA Server64.exe"
```

Also there are other concerns if you need to raise process priority of MTA server, probably need to do a health check on your box

**Comment by CrosRoad95** [comment]
but, why? is is just some hack to increase server performancE?
