### ISSUE TITLE
Boats are slower on high FPS 

### ISSUE THREAD

**Issue by Brian9221** [multitheftauto/mtasa-blue#2782]
### Describe the bug

Boats are significatly slower when you set a high FPS limit on yourself:

Take a Squalo or another fast boat, do

crun setFPSLimit(144) -> boat is slow
crun setFPSLimit(45) -> boat is faster

I tested this on CIT server, we have a speedometer that outputs vehicle speed on screen. To verify this bug you might need a separate script to check speed.

### Steps to reproduce

Take a Squalo or another fast boat, do

crun setFPSLimit(144) -> boat is slow
crun setFPSLimit(45) -> boat is faster

### Version

Client v1.5.9 release 21342 (Win 10 64bit)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by PlatinMTA** [comment]
Also boats slide less distance on high fps. These two things are marked on the framerate fixes project.

**Comment by lopezloo** [comment]
Fixed in 7c8a1ab93d091b06262749b482d6c8142ca69eea
