### ISSUE TITLE
Allow custom interval for setWeatherBlended

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2785]
### Is your feature request related to a problem? Please describe.

Currently if you change minute duration setWeatherBlended is unuseable.

### Describe the solution you'd like

```
setWeather(0)
setWeatherBlended(9, 10000) -- changes blended weather in 10 secs
```

### Describe alternatives you've considered

```
setWeatherBlendTime()
resetWeatherBlendTime()
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by TFP-dev** [comment]
You can create custom weather blending via scripting, but I know it's not the same thing.
