### ISSUE TITLE
add engineStreamingGetUsedMemoryLimit

### ISSUE THREAD

**Issue by geeldon** [multitheftauto/mtasa-blue#2786]
### Describe the solution you'd like

return *reinterpret_cast<std::uint32_t*>(0x08A5A80); 
(streaming memory limit from showmemstat)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Merlin** [comment]
You can get the streaming memory limit from [dxGetStatus](https://wiki.multitheftauto.com/wiki/DxGetStatus).
`crun print(dxGetStatus().SettingStreamingVideoMemoryForGTA * 1024)`
will show you the exact limit showmemstat shows.

**Comment by Merlin** [comment]
Yes. The value changes with the settings.

`streaming_memory = 128` will change it to the lowest possible value. (same as the slider in the game settings)
`crun print(dxGetStatus().SettingStreamingVideoMemoryForGTA * 1024)` will output 131072. same value as showmemstat

If you now set it to 256 which is the highest value `streaming_memory` can have
`crun print(dxGetStatus().SettingStreamingVideoMemoryForGTA * 1024)` will output 262144.

**Comment by geeldon** [comment]
<3
