### ISSUE TITLE
Disabling jump control blocks possibility to zoom with lshift

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2788]
### Describe the bug

For some reason, if you gonna disable jump control, then zoom-in won't be possible, unless you re-enable it.

### Steps to reproduce

1. Disable jump control.
2. Try to zoom with sniper with lshift.
3. Profit.

### Version

Client/server: Multi Theft Auto v1.5.9-release-21353

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by lopezloo** [comment]
That's because it shouldn't be possible to zoom in using jump control. It doesn't work this way in single player.
