### ISSUE TITLE
 appearing random things

### ISSUE THREAD

**Issue by audimarley** [multitheftauto/mtasa-blue#2802]
### Describe the bug

never happened even a bug after any update for me only what happened now after you made the update these strange things started to appear like the items are buggy in all serves that I enter is as you can see in the video right after I wanted them to solve it soon because I do live and I need a lot and the only game I love and the only game I play please help me
### Steps to reproduce

https://youtu.be/5UeULkOjvwE

### Version

Multi Theft Auto v1.5.9-release-21382

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by PlatinMTA** [comment]
#2801

It's going to get fixed, if you are a server owner ask your players to download and play with this version: https://nightly.multitheftauto.com/mtasa-1.5.9-rc-21374-20221023.exe

**Comment by audimarley** [comment]
it works the first time I enter this version but when I enter again it updates and comes back with the problem again

**Comment by PlatinMTA** [comment]
> it works the first time I enter this version but when I enter again it updates and comes back with the problem again

You don't need to update, if it asks you to update, don't do it. I doubt any server is asking to update if you want to play.

**Comment by audimarley** [comment]
as soon as I close the mta and open it again it appears doing an update on the desktop

**Comment by audimarley** [comment]
Do you have a deadline when can you solve this?

**Comment by patrikjuvonen** [comment]
Thanks for the report, we are tracking this on #2801 so please subscribe to that issue to receive further updates on the issue.
