### ISSUE TITLE
Model replacement fails when using raw data in engineImportTXD/engineLoadDFF with engineRestoreModel 

### ISSUE THREAD

**Issue by JeViCo** [multitheftauto/mtasa-blue#2803]
### Describe the bug

I cannot reuse TXD & DFF elements for some reason after i pass them to engineImportTXD and engineReplaceModel functions once. This only occurs when i use raw data in engineLoadTXD/engineLoadDFF. Those functions work perfectly if i use filepath instead

### Steps to reproduce

1. Pick any custom vehicle model and download it
2. Read TXD/DFF file content via fileRead
3. Use raw data in engineLoadTXD/engineLoadDFF
4. Import & replace via engineImportTXD/engineReplaceModel
5. Use engineRestoreModel to restore a vehicle
6. Repeat step 4. You'll get false on both engineImportTXD and engineReplaceModel

### Version

Client: v1.5.9-release-21384
Server: v1.5.9-release-21258

### Additional context

Example code:
```
local txd, dff
local model = 604
local filename = 'merit'

function getFileContent(filePath)
	local f = fileOpen(filePath)
	local data = fileRead(f, fileGetSize(f))
	fileClose(f)
	return data
end

addCommandHandler('load', function()
	txd = engineLoadTXD(getFileContent(filename .. ".txd"))
	dff = engineLoadDFF(getFileContent(filename .. ".dff"))
end)

addCommandHandler('loadmodel', function()
	iprint(engineImportTXD(txd, model))
	iprint(engineReplaceModel(dff, model))
end)

addCommandHandler('unloadmodel', function()
	engineRestoreModel(model)
end)

addCommandHandler('unload', function()
	destroyElement(txd)
	destroyElement(dff)
end)

addCommandHandler('printData', function()
	iprint(txd, dff)
end)
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
Is this a new problem or have you had this before as well?

**Comment by botder** [comment]
You can't apply engineImportTXD/engineReplaceModel more than once with ~~a TXD/DFF element~~ a raw buffer.
This is not a new issue, by the way (@ patrik)
Here is the commit: 78f1d0bc42067e289f8dbdc429e15ffc074189d2, 45c264ecf1d1f3a9ec52383b8306a6fc7b362dca

**Comment by JeViCo** [comment]
I've just downgraded client a couple of times
First downgrade: v1.5.9-release-21372 -> Error
Second downgrade: v1.5.9-release-21338 -> Error
It seems to be an old issue

As i said, i can't reuse TXD & DFF elements with raw data but i can with filepath. Tech limitations?

**Comment by botder** [comment]
It is the default behavior for raw data since 2015.

**Comment by botder** [comment]
In conclusion, this is not a bug. If you want to see a different behavior, create a feature request issue.
