### ISSUE TITLE
getUserdataType returns "userdata" for fetchRemote return object

### ISSUE THREAD

**Issue by Yamsha75** [multitheftauto/mtasa-blue#2807]
### Describe the bug

Passing "request" object returned from fetchRemote or getRemoteRequests to getUserdataType function returns a string "userdata".

### Steps to reproduce

Run this code (requires ACL permissions for fetchRemote):
```lua
req = fetchRemote("example.com", function() end) -- callback is not important here
print(getUserdataType(req)) -- => "userdata"
```

### Version

Client: Multi Theft Auto v1.5.9-release-21331
Server: Multi Theft Auto v1.5.9-release-21331

### Additional context

I was instructed to try removing "class" keyword from [these lines in CLuaFunctionParseHelpers.h](https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h#L173-L176) by lopsi on the MTASA Discord ([link to chat](https://discord.com/channels/278474088903606273/667831778563719182/1037116806470578266)), but I have no means to build MTA and test this myself.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
> I was instructed to try removing "class" keyword from [these lines in CLuaFunctionParseHelpers.h](https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h#L173-L176) by lopsi on the MTASA Discord ([link to chat](https://discord.com/channels/278474088903606273/667831778563719182/1037116806470578266)), but I have no means to build MTA and test this myself.

This is incorrect - upon further research it's just the same as a forward declaration (required, since the header for CRemoteCall isn't included here). So it needs further investigation
