### ISSUE TITLE
setLowLODElement not working properly with custom objects

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2809]
### Describe the bug

setLowLODElement not working properly with custom objects. If you're in a specified distance then it will be darker.
Video: https://streamable.com/p6pxn1
With default objects i've didn't notice this bug.

### Steps to reproduce

Run this resource
[bug.zip](https://github.com/multitheftauto/mtasa-blue/files/9951217/bug.zip)

### Version

All versions

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TFP-dev** [comment]
Everything works as it should, the problem is with your model, if you are using 3ds MAX then use deniska's export DFF script.
