### ISSUE TITLE
Make setAccountSerial() function

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#281]
Hi! On my own server I have a system that checks whenever the serial account is the same to the PC serial, if thats the case they log in, if not, the system checks other stuff.

The thing is that this serial changes to the serial of the PC that it logged last (if that sentence makes sense), so in order to check I need to get the account and account serial, and do the checks.

I think this is very annoying, because if one mistake is made, the serial could be one that isn't meant to be.

So I was thinking now that some people gave the function getAccountByID() and setAccountName(), maybe you could work on setAccountSerial(). This maybe could help some people which are still using the main MTA db instead of MySQL for example.

Thanks!

**Comment by qaisjp** [comment]
Does [`setAccountData('serial', serial)`](https://wiki.multitheftauto.com/wiki/SetAccountData) fit your use case?

**Comment by CrosRoad95** [comment]
This could be never added to mta due some programmers are dummy. You could disable auth serial if you want and use your own check's, security etc.

**Comment by patrikjuvonen** [comment]
Some servers have worked around this issue by having a fixed length list of user-defined/pre-approved serials that they allow using their account.

Related Mantis issue: https://bugs.mtasa.com/view.php?id=9862

**Comment by PlatinMTA** [comment]
There are ways to make what I want without editing the Serial. Using and accountData is one, but I think that isn't really needed if you can just, you know, edit the one you have.

**Comment by Lpsd** [comment]
I don't think we need a dedicated function for this when you can already implement it with setAccountData, or your own database.

This issue has been inactive for 3 years, so I'll close this. If you can provide a good reason why this function is needed and you can't use existing functionality to achieve it, please feel free to comment.
