### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by JoseD909** [multitheftauto/mtasa-blue#2816]
### Describe the bug

necesito ayuda para recuperar mi cuenta de mta. presiono el boton de recuperar contraseña, pongo mi correo pero no llega nada al correo. si me pueden ayudar, se los agradezco.
intente crear otra cuenta con otro correo que tengo pero me fue imposible tambien 

### Steps to reproduce

a

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
GitHub is not for generic client support. Use the community Discord or forum.

https://mtasa.com/discord
https://forum.mtasa.com
