### ISSUE TITLE
GPU/Resolution selection window appears behind splash screen

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#2819]
### Describe the bug

Recently, the tiny window to select GPU and game resolution appears behind the splash screen.

Likely caused by [e1119f5](https://github.com/multitheftauto/mtasa-blue/commit/e1119f5a54095ef26a8fd857d986a1ef15da4c84)

### Steps to reproduce

Use latest MTA version with that window appearing.

### Version

Multi Theft Auto v1.5.9-release-21415

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
Caused by ab2a1b974fc29f9ae8fc009b633283a77a3c4825
