### ISSUE TITLE
get/setEffectScale was added in 1.6 r7485, but should be merged in 1.5.5 nightlies

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#282]
get/setEffectScale() has been merged in 2015 according to this site:
https://wiki.multitheftauto.com/wiki/SetEffectScale

However there is no MTA 1.6 available and i think this function should be merged into current nightlies, there is no point in leaving this dead behind for over 3 years.

Does this code actually exist or did someone create a wiki article about something that has not been made yet?

**Comment by qaisjp** [comment]
I am not sure where you got 2015 from as the wiki page was created in 2017.

I can't find `setEffectScale` anywhere in the code and the wiki page references [r7485](https://buildinfo.mtasa.com/?Author=&Branch=&Revision=7485) which contains commits unrelated to a setEffectScale function.

I vaguely remember the function existing... maybe this got lost when we moved to just having master and xp-vista? This is an odd one...

**Comment by patrikjuvonen** [comment]
Might've been related to EIR branch or some other custom branch at the time.

**Comment by Timic3** [comment]
It was supposed to be implemented by the wiki page author, but he gave up.

**Comment by qaisjp** [comment]
@Einheit-101 if your questions have been answered, are you okay to close this issue?

**Comment by Einheit-101** [comment]
Well this is unfortunate but yeah, it can be closed then.
