### ISSUE TITLE
MTA updater wrong download percent

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2825]
### Describe the bug

Downloading window showing false percentage of download state
![image](https://user-images.githubusercontent.com/6568348/205577445-821c713f-4ff3-4cc9-9a4b-5aed04129c8f.png)

### Steps to reproduce

Update MTA

### Version

Multi Theft Auto v1.5.9-release-21429

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Fernando-A-Rocha** [comment]
Happened to me too
