### ISSUE TITLE
Custom object property for light and shadow's

### ISSUE THREAD

**Issue by iEriic** [multitheftauto/mtasa-blue#2834]
### Is your feature request related to a problem? Please describe.

First time here, sorry if I said something wrong or my English is questionable.
I've already seen the issue of creating new id's for permanent objects other than renting and I agree and agree, but there's something I haven't seen being discussed that I, as a modeler and detailer, really miss would be the issue of object properties referring to omnis shadows and lighting.
I've seen a post here from the community talking about it and I did the test and confirmed that the lighting property comes from the object created and not from the model itself so I thought of something I've seen done by servers that modify the map through your own launcher engines.

`The property I'm referring to is this`
https://imgur.com/a/G03WG7c

### Describe the solution you'd like

A more direct way that I thought would be that when creating the object using createObject it had an optional boolean parameter which, if activated, would set the property to reflect shadows from the ped, vehicle etc... and omni lighting as well as custom shadows

exemple: `createObject (modelID, x, y, z, [rx, ry, rz, isLod, lightingProperty = false or true])`

### Describe alternatives you've considered

or if you can also enter the SetObjectProperty option

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by lopezloo** [comment]
Duplicate of #450
