### ISSUE TITLE
Add optional 'property' argument to getVehicleHandling

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#2852]
### Is your feature request related to a problem? Please describe.

There should be an easier way to get a particular handling value, instead of the entire table

### Describe the solution you'd like

Add `property` argument to getVehicleHandling function.

**Comment by CrosRoad95** [comment]
but we have already get/setVehicleHandling?

**Comment by PlatinMTA** [comment]
> but we have already get/setVehicleHandling?

``getVehicleHandling`` always returns a full table

**Comment by Zangomangu** [comment]
I suggest adding an optional `property` argument to getVehicleHandling instead of 30 individual functions
