### ISSUE TITLE
scriptdebugloglevel in mtaserver.conf has no effect for outputDebugString

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2857]
### Describe the bug

Disabling it fully or changing to different level of this setting has no effect, debug strings will still appear in log file.

### Steps to reproduce

1. Set [scriptdebugloglevel](https://wiki.multitheftauto.com/wiki/Server_mtaserver.conf#scriptdebugloglevel) to 0 in mtaserver.conf
2. Do: ```outputDebugString("test", 4, 255, 127, 0)```
3. Log will appear:

```
[2022-12-29 16:11:21] test
```

### Version

Client: Multi Theft Auto v1.5.9-release-21488 - Windows 10 x64
Server: MTA:SA Server v1.5.9-release-21487 - Windows 10 x64

### Additional context

It seems to be a case only for level 0 and 4. I'm assuming those are not counted as info message.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
Related info:

Level 4 added at https://github.com/multitheftauto/mtasa-blue/pull/1167

**Comment by patrikjuvonen** [comment]
cc @Addlibs in case he'd like to look at it
