### ISSUE TITLE
Add function isAccountLoggedIn

### ISSUE THREAD

**Issue by F2BShady** [multitheftauto/mtasa-blue#2863]
### Is your feature request related to a problem? Please describe.

The function of this code is as follows,For example, if an account is logged in,return true false if that account is logged in or not
,because for example a player has 2 computers and joins the same server,logged in to the first PC,but it tries to open on 2nd PC as well,we must prevent this...

### Describe the solution you'd like

by the way, the function prototype could be bool isAccountLoggedIn ( account theAccount )

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Lpsd** [comment]
Why isn't https://wiki.multitheftauto.com/wiki/GetAccountPlayer sufficient for this?

**Comment by F2BShady** [comment]
These are confusing, require a lot of code but it's easier to do this way
```lua
local account = getAccount("blabla")
if(isAccountLoggedIn(account)) then return end
```

**Comment by Lpsd** [comment]
```lua
function isAccountLoggedIn(account)
    return getAccountPlayer(account) ~= false
end
```

**Comment by F2BShady** [comment]
> ```lua
> function isAccountLoggedIn(account)
>     return getAccountPlayer(account) ~= false
> end
> ```

Bad argument @ 'getPlayerAccount' [Expected element at argument 1, got account]
 didnt work

**Comment by Lpsd** [comment]
I had originally wrote the incorrect function (`getPlayerAccount`), but the code has since been updated. Check again, you need to use `getAccountPlayer`

Let me know once you've verified and I can close this issue

**Comment by F2BShady** [comment]
yes it can be checked thanks i learned another new information

**Comment by Lpsd** [comment]
Thanks
