### ISSUE TITLE
Using dxCreateTexture with raw data makes textures blurry

### ISSUE THREAD

**Issue by JeViCo** [multitheftauto/mtasa-blue#2881]
### Describe the bug

dxCreateTextures makes all textures blurry. It might not be noticable on high res images however it becomes critical when it comes to icons. dxCreateTexture arguments does nothing, same thing with dxSetBlendMode.

Side by side comparison (using raw data on the left and using path on the right):
![Screenshot](https://user-images.githubusercontent.com/103533191/214028895-49c45332-fbaf-4a77-8f33-607cbf0deb09.png)

### Steps to reproduce

Sample resource:
[resource_test.zip](https://github.com/multitheftauto/mtasa-blue/files/10479171/resource_test.zip)

### Version

Client: v1.5.9-release-21519
Server: v1.5.8-release-20817

### Additional context

Q: Why are you using raw data?
A: First things first, i want to protect my assets. I put a lot of effort into making some images (like creating custom gta map from scratch or drawing custom vehicle liveries). I also don't want to share paid textures (stock images, ui elements and so on).

Q: But you can still screenshot everything
A: Yeah, but keep in mind that some images can be layered one on top of another (gta map + ui elements, for example). On the other hand, you cannot screenshot some images like vehicle liveries (not sure if that's even physically possible)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by JeViCo** [comment]
Should i preprocess images somehow to make the quality better?

**Comment by TFP-dev** [comment]
Your texture size should be a power of two(16, 32, 64 etc.). I can't reproduce blurry texture after converting image from your resource to 512x512.
![obraz](https://user-images.githubusercontent.com/72511827/214342946-7cc02945-49f8-4b4b-b1f0-ea529e6105e0.png)

**Comment by JeViCo** [comment]
It seems to be the power of two problem. It automatically stretches somewhere. We can simply add a note on wiki like "just deal with it - make the size correct" OR we can continue this discussion and dig the code a bit deeper

**Comment by samr46** [comment]
> It seems to be the power of two problem. It automatically stretches somewhere. We can simply add a note on wiki like "just deal with it - make the size correct" OR we can continue this discussion and dig the code a bit deeper

From [Wikipedia](https://wiki.multitheftauto.com/wiki/DxCreateTexture):
```
width: Desired width, preferably power of two (16, 32, 64 etc.), maximum is 16384
height: Desired height, preferably power of two (16, 32, 64 etc.), maximum is 16384
```

**Comment by JeViCo** [comment]
Okay, then. The reason behind creating this issue is to investigate the texture creation process and search for the the problem source). I'm closing this issue, since there's already a note on wiki, and it doesn't affect gameplay much
