### ISSUE TITLE
Help/Info button in connection refused/kicked Error

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [multitheftauto/mtasa-blue#2884]
### Is your feature request related to a problem? Please describe.

When kicked / refused connection to a server because of anti cheat or another MTA verification, the player gets a popup message usually with a code and/or brief reason.
Most people end up asking on Discord in #help-support or go search the web and may stumble upon old forum threads of people asking about the same, often with unclear solutions.

### Describe the solution you'd like

I've noticed we tend to have clear explanations of why X error code is happening on Discord (notably pinned messages by @Dutchman101).
My suggestion is the following:

1. Index all the possible error messages etc in a wiki page
2. Create individual pages for each error code or problem type
3. Explain why it's happening there and give eventual solutions
4. Add a button to the error popup GUI "Help" that opens a link to the wiki page of all the indexed problems where the player will then be able to easily find the one corresponding

### Describe alternatives you've considered

If we don't do this, people will keep flooding forums and discord with "*screenshot of error popup" how to solve help?" where they could simply be going to a webpage and finding the explanations.

### Additional context

I can provide an images of how the changed GUI popup with the help button would look, but it's pretty easy to imagine.

Also, I'm sure setting up wiki pages or maybe even hosting these help pages on the mtasa site like the existing ones for Help with .ASI files etc shouldn't be too difficult as it's something MTA staff is used to doing already, the pages just need to be more complete and more easily accessible (this suggestion).

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
e.g. search Google for "mta sa kicked by anticheat": most results are forum posts. We could improve this by having a central page for all problems and their solutions. Would make everyone's lives easier, especially if there's a button linking directly to it when you get the popup.

**Comment by Lpsd** [comment]
Not saying this isn't a good idea, or won't have any effect at all - but the types of users who are visiting the Discord raising these issues are likely not going to have the intuition to refer to any kind of documentation and resolve the issue themselves. They need directly telling what to do.

As you said, for most issues a solution is already available either by searching the Discord or viewing the pinned messages. Most users are already failing to utilize this.

**Comment by Fernando-A-Rocha** [comment]
> Not saying this isn't a good idea, or won't have any effect at all - but the types of users who are visiting the Discord raising these issues are likely not going to have the intuition to refer to any kind of documentation and resolve the issue themselves. They need directly telling what to do.
> 
> As you said, for most issues a solution is already available either by searching the Discord or viewing the pinned messages. Most users are already failing to utilize this.

Some people are indeed incapable of finding documentation, but the core of my suggestion is adding a big red button in that popup window that includes the problem, which opens a webpage on your browser when clicked. I think that's dumb-proof xD
