### ISSUE TITLE
Bug for immortality and absenteeism using the windowed MTA client

### ISSUE THREAD

**Issue by x8BaLLx** [multitheftauto/mtasa-blue#2885]
### Describe the bug

When a player in window mode calls up the window options on his top bar he becomes immortal and completely absent from the game, no interaction is possible with him until he returns to the game.

Player View --- https://www.youtube.com/watch?v=HHpWVb3OnIU
View of the bug person --- https://www.youtube.com/watch?v=dxW0fE24e-4
 

### Steps to reproduce

1. go to the window mode of the game 
2. bring up the mouse and window options on the top bar of the program
3. the game stutters and you are absent to any interaction until you return to the game

### Version

Multi Theft Auto v1.5.9-release-21545

### Additional context

Player View --- https://www.youtube.com/watch?v=HHpWVb3OnIU
View of the bug person --- https://www.youtube.com/watch?v=dxW0fE24e-4
 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
I believe the most sufficient method to resolve this, would be to capture certain events within our message loop and prevent them.

It seems like we're actually attempting this within CMessageLoopHook (see https://github.com/multitheftauto/mtasa-blue/blob/master/Client/core/CMessageLoopHook.cpp#L175-L186) but it isn't currently working? Needs investigating further.

Would we really want to disable window dragging for users who actually play in windowed mode though? I can see that being rather frustrating.

Short of this, we would need to move all rendering outside of the main thread - which if you're aware of multi-threading implications (especially when it comes to MTA) is not an easy task.
