### ISSUE TITLE
Script jetpack warnings

### ISSUE THREAD

**Issue by ccw808** [multitheftauto/mtasa-blue#289]
**Is your feature request related to a problem? Please describe.**
Latest nightly server version outputs "Replaced with setPedWearingJetpack. Refer to the wiki for details" warnings.

**Describe the solution you'd like**
Remove warnings.

**Additional context**
Are the warnings are important? Do the old functions still work as expected?

**Comment by qaisjp** [comment]
The old functions still work as expected.

The warnings are just to encourage the use of the new function but perhaps we can renew the script warnings for 1.6 (or reintroduce the warnings right before 1.5.6 releases?)

I've created a pull request for this if that's the direction we want to go. I have also pushed a branch reverting these changes so we can bring back the warnings later.
