### ISSUE TITLE
getSoundMetaTags not supporting utf8

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2892]
### Describe the bug

getSoundMetaTags works incorrectly when stream title has utf8 characters

Actual ingame:
![image](https://user-images.githubusercontent.com/6568348/217793012-e7b85cff-db11-49e4-bd72-e50a343cd34d.png)
![image](https://user-images.githubusercontent.com/6568348/217793313-2fe38fb2-12a0-4b21-8a16-c4e380d42645.png)

Real song:
![image](https://user-images.githubusercontent.com/6568348/217793048-0680719b-3ac1-49c9-b769-419a0e2f2119.png)
![image](https://user-images.githubusercontent.com/6568348/217793238-a4f2b31c-bd86-4414-8b69-98218bcf4db0.png)

### Steps to reproduce

getSoundMetaTags(sound)["stream_title"]

### Version

All versions

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Is this relevant? https://discord.com/channels/801330706252038164/801330706252038170/862013452179996682 (dev discord)

**Comment by Xenius97** [comment]
Solved via script, thanks @Lpsd
