### ISSUE TITLE
Luac bugs

### ISSUE THREAD

**Issue by F2BShady** [multitheftauto/mtasa-blue#2896]
### Describe the bug

Luac tool seems to be modifiable with one line of code,I can say a few bugs in Luac.
variables that are local, their functions do not change.

`local asd = setTimer(function()
-- codes
end,0,1)
`this way it can't break at all, it returns a blank page

### Steps to reproduce

I can only suggest the following code as a method:
`local asd = setTimer(function()
-- codes
end,0,1)
`

### Additional context

https://imgur.com/zCqRcrw
https://imgur.com/eiWGdZ6
https://imgur.com/iKnUa5D
**When calling the codes that cannot be called with local with setTimer as a local variable, it does not break anything.**
https://imgur.com/40Mdwqh

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
This line of code is invalid, you started a comment which means the function call isn't actually closed.

**Comment by Lpsd** [comment]
@F2BShady I'm assuming this can now be closed, unless you have anything else to raise here?
