### ISSUE TITLE
Update default radar.jpg image (F11 map)

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [multitheftauto/mtasa-blue#2904]
### Is your feature request related to a problem? Please describe.

The current [`radar.jpg`](https://github.com/multitheftauto/mtasa-blue/blob/master/Shared/data/MTA%20San%20Andreas/MTA/cgui/images/radar.jpg) image contains some imperfections and it's 1024x1024 pixels (rather small resolution). As soon as you zoom in, it will lose quality and become blurred.

### Describe the solution you'd like

It could be improved with a better quality and higher resolution GTA:SA map render.

E.g.: [Patrick2562/mtasa-map-images](https://github.com/Patrick2562/mtasa-map-images/) (mta_noshadow_2048.jpg seems adequate). If @Patrick2562 agrees of course.

### Describe alternatives you've considered

Have several resolutions radar.jpg images. Client can select the one they want via `Settings`, similar to how you can select the `Interface` style. E.g. 1024x1024, 2048x2048, 4096x4096, etc.

### Additional context

Similar enhancements have recently been approved: #2829 #2854

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by bum8hj** [comment]
Having the night-time version would be cool too!

**Comment by Fernando-A-Rocha** [comment]
> Having the night-time version would be cool too!

Quite honestly I would love to have it the way I suggested it under Alternative way, where you could select the map theme you want from the settings menu. Seems like the best option so far, all things considered.

**Comment by Fernando-A-Rocha** [comment]
Bonus would be creating a Lua function for servers to force a certain map theme their players.

Bonus++ would be the ability for servers to even replace this image with a custom one using a function too.

And finally, since this hasn't been mentioned yet, what about the map blip images? Those can be upscaled and improved too. @Haxardous 😁

**Comment by Haxardous** [comment]
> And finally, since this hasn't been mentioned yet, what about the map blip images? Those can be upscaled and improved too. 

Actually, @Dutchman101 helped with upscaling some of the assets, it would be great if he could help us with that too.

**Comment by patrikjuvonen** [comment]
I remade the blip images recently in vector format and those are in use on MTA right now. What needs improving?

**Comment by Fernando-A-Rocha** [comment]
Bump. Can we use this (https://github.com/Patrick2562/mtasa-map-images/blob/master/noshadow/mta_noshadow_4096.jpg) as F11 map?
