### ISSUE TITLE
function `tocolor` server side

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#291]
There's nothing to describe, just make tocolor possible to use serverside.

Example if you making group system with tag/group color, you have to rewrite tocolor function serverside or store color as table { r, g, b[, a] }

**Comment by qaisjp** [comment]
This sounds fine. If you're interested in sending a pull request for this, it would be useful to move the code here: https://github.com/multitheftauto/mtasa-blue/blob/master/Shared/mods/deathmatch/logic/luadefs/CLuaUtilDefs.cpp
