### ISSUE TITLE
Can't login to HTTP

### ISSUE THREAD

**Issue by edicik** [multitheftauto/mtasa-blue#2910]
### Describe the bug

Server logs "HTTP: 'httpaccess' entered correct password from 127.0.0.1"
but response is StatusCodeError: 401 - "Access denied, please login"

### Steps to reproduce

1. Create account
2. Login with account to http

### Version

MTA:SA Server v1.5.9-release-21554

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
Try to update to 21595, it works fine for us.
![image](https://user-images.githubusercontent.com/6568348/221900343-ad589987-962d-4302-852f-a16190f177b2.png)

**Comment by patrikjuvonen** [comment]
Unable to reproduce.
