### ISSUE TITLE
Make getResourceName take current resource as a default argument

### ISSUE THREAD

**Issue by TracerDS** [multitheftauto/mtasa-blue#2927]
### Is your feature request related to a problem? Please describe.

As in the title. Make `getResourceName` take current resource as a default argument.

### Describe the solution you'd like

 Make `getResourceName` take current resource as a default argument.
Simple change but may come in handy

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by MegadreamsBE** [comment]
What's the point though?

**Comment by Xenius97** [comment]
getResourceName(resource) will return current resource name :)
resource global variable = getThisResource()

**Comment by TracerDS** [comment]
> getResourceName(resource) will return current resource name :) resource global variable = getThisResource()

Yes, i thought about it but hey, we have `getResourceRootElement` so why not `getResourceName` too, ya know?
(I meant with arguments)

Or at least make a global `resourceName` that will hold the name of the resource.

**Comment by dmi7ry** [comment]
> Or at least make a global `resourceName` that will hold the name of the resource.

There is `resource.name` already (although it requires OOP is enabled).

**Comment by TracerDS** [comment]
> > Or at least make a global `resourceName` that will hold the name of the resource.
> 
> There is `resource.name` already (although it requires OOP is enabled).

Exactly. The POP version right now is `getResourceName(resource)`. And OOP is... slow and not really good in mta
