### ISSUE TITLE
Toggling car lights makes windows invisible when viewed from inside 

### ISSUE THREAD

**Issue by DryxioBackup** [multitheftauto/mtasa-blue#2936]
### Describe the bug

If you are inside the car and toggle the lights, the car windows become invisible. 
This bug only occurs when you are viewing the windows from inside the car; if you are viewing the car from outside or from a different camera angle, the windows will appear normal.

Here is the bug : 
![mta-screen_2023-03-26_01-28-21](https://user-images.githubusercontent.com/76913694/227748780-8706d0cf-eaac-44f0-92e8-f8a47f088cef.png)

When lights are turnt off : 
![mta-screen_2023-03-26_01-28-34](https://user-images.githubusercontent.com/76913694/227748790-55b1cbba-3a4d-49ab-8a46-14b77734bd7c.png)

### Steps to reproduce

1. Enter a car
2. Turn lights on
3. Exit the car, but leave the door opened
4. Look at the inside of the car (from the opened door)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by DryxioBackup** [comment]
SilentPatch fixes this issue so I asked to Silent for more infos. I'm not into development at all, but here you go if it can help :

<img width="330" alt="image" src="https://user-images.githubusercontent.com/76913694/227749012-2c14cffc-6cc5-4f8d-9763-ea3d7a766f56.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/76913694/227749023-fa699824-eedc-47f9-84bc-30870b3f9d14.png">

**Comment by TFP-dev** [comment]
It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.

**Comment by DryxioBackup** [comment]
> It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.

Shader needs to be applied on a specific texture right? Vehicles doesn't have a texture for glass/windows (but maybe I'm wrong)

**Comment by TFP-dev** [comment]
> > It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.
> 
> Shader needs to be applied on a specific texture right? Vehicles doesn't have a texture for glass/windows (but maybe I'm wrong)

Vehicle windows uses "vehiclegeneric256" texture.

**Comment by Fernando-A-Rocha** [comment]
Tested ✅ 

```lua
local VEH_WIN_SHADER = [[
    technique TexReplace
    {
        pass P0
        {
            CullMode = 1;
        }
    }
]]
local vwShader = dxCreateShader(VEH_WIN_SHADER,1,100,true,"vehicle")
if vwShader then
    engineApplyShaderToWorldTexture(vwShader, "vehiclegeneric256")
end
```

CullMode 1 means none, see https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dcull

**Comment by DryxioBackup** [comment]
> It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.

Worked. But it creates a bug where the car wheel disappear when viewed from the front (when lights are ON)

<img width="259" alt="image" src="https://user-images.githubusercontent.com/76913694/229566151-4549e02d-ad74-4fda-ba75-285229bb2bd9.png">

**Comment by TFP-dev** [comment]
> > It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.
> 
> Worked. But it creates a bug where the car wheel disappear when viewed from the front (when lights are ON)
> 
> <img alt="image" width="259" src="https://user-images.githubusercontent.com/76913694/229566151-4549e02d-ad74-4fda-ba75-285229bb2bd9.png">

Because you only applied this shader on windows. You should also apply this shader to steering wheels and to other textures with this problem.

**Comment by Fernando-A-Rocha** [comment]
> > > It can be fixed by a simple shader, just set "CullMode" render state in shader to "None" and apply this shader to vehicle.
> > 
> > 
> > Worked. But it creates a bug where the car wheel disappear when viewed from the front (when lights are ON)
> > <img alt="image" width="259" src="https://user-images.githubusercontent.com/76913694/229566151-4549e02d-ad74-4fda-ba75-285229bb2bd9.png">
> 
> Because you only applied this shader on windows. You should also apply this shader to steering wheels and to other textures with this problem.

Thanks chief. I applied that same shader to "vehiclesteering128" and now the wheels don't disappear.

**Comment by Lord-Henry** [comment]
Don't forget **vehicleshatter128** or the window will be invisible from inside when the glass is shattered.
```lua
local VEH_WIN_SHADER = [[
    technique TexReplace
    {
        pass P0
        {
            CullMode = 1;
            SlopeScaleDepthBias = 65;
        }
    }
]]
local vwShader = dxCreateShader(VEH_WIN_SHADER,1,100,true,"vehicle")
if vwShader then
    engineApplyShaderToWorldTexture(vwShader, "vehiclegeneric256")
    engineApplyShaderToWorldTexture(vwShader, "vehiclesteering128")
    engineApplyShaderToWorldTexture(vwShader, "vehicleshatter128")
end
```
