### ISSUE TITLE
callRemote will always return a nil errno even if successful

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#294]
**Describe the bug**
[callRemote](https://wiki.multitheftauto.com/wiki/CallRemote) returns a nil errno although the request was successful. This behavior is not consistent with [fetchRemote](https://wiki.multitheftauto.com/wiki/FetchRemote).

**To Reproduce**
1. Send a request with [callRemote](https://wiki.multitheftauto.com/wiki/CallRemote).
2. Inspect the _errno_ argument provided by the callback function.

**Expected behavior**
CURLE_OK (0) as the errno if the request went through okay (see [error codes](https://wiki.multitheftauto.com/wiki/Template:Error_codes_for_callRemote_and_fetchRemote) on Wiki). If the request did not go through alright then it should return the corresponding error code for that error.

**MTA Client & Server:**
- Multi Theft Auto v1.5.5-release-13959
- Windows 10.0.17134.165

**Additional context**
Initially committed here: https://github.com/multitheftauto/mtasa-blue/pull/271#issuecomment-408574297
Will create a new PR for this.

**Comment by jushar** [comment]
Can this be fixed without breaking backwards compatibility?

**Comment by patrikjuvonen** [comment]
If you prefer, we can use some sort of a version check, if that is okay to do?
