### ISSUE TITLE
Chatbox layout "size" setting is not correctly scaling the bounding box of debug text

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#2945]
### Describe the bug

Adjusting chatbox size does scale text of chatbox and debug info correctly, but the bounding box of the debug info is too small as soon as any value beyond 1.1 is set. This makes debug info unreadable.

![image](https://user-images.githubusercontent.com/17533547/230234345-db514efc-f2b9-45fd-b5f4-776245f02e47.png)

### Steps to reproduce

-Go into settings / interface / Layout 
-Set "size" to anything bigger than 1.1 / 1.1
-Cause an debug message and see that some letters are cut at the left border

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
Unable to reproduce.

**Comment by Einheit-101** [comment]
> Unable to reproduce.

How is that possible? I use the following code and chatbox layout scale X/Y 1.4 and i can reproduce it without any problem:
outputDebugString("WARNING: [TESTING]/dl_core/dl_plugin.lua:22: File not found @ dxCreateTexture [skins/41_body.dds]")

Maybe different screen resolutions cause different results on this issue?

<img width="683" alt="mta-screen_2023-04-16_20-17-57" src="https://user-images.githubusercontent.com/17533547/232333446-76962fe7-533a-4e2a-9b7f-f4e1c6f22dd3.png">

**Comment by patrikjuvonen** [comment]
What is your monitor resolution and your game resolution

**Comment by Einheit-101** [comment]
> What is your monitor resolution and your game resolution

I have a 4K TV and run MTA in 1366x768, Fullscreen mode. And Windows 11 is set to 150% UI scale.
