### ISSUE TITLE
IMG doesn't unload on resource stop

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2957]
### Describe the bug

When you replace a model, and then stop the resource, model won't unload.

### Steps to reproduce

https://streamable.com/egykqa
Use resource linked here: https://github.com/multitheftauto/mtasa-blue/pull/1677#issuecomment-1371090822

### Version

Multi Theft Auto v1.6-release-21715

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
Did you try engineRestreamWorld ?

**Comment by Xenius97** [comment]
> Did you try engineRestreamWorld ?

Ye, it's on the video too.

**Comment by Xenius97** [comment]
Idk what happened, now works properly.
