### ISSUE TITLE
Show newest versions in server browser

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2961]
### Describe the bug

When MTA:SA releases a new version (eg. 1.3, 1.4, 1.5, 1.6 etc.) then you will see older versions in server browser, but you won't see newest versions in server browser. You could lose many players by upgrading, server browser should show newest versions too (just like 1.6 showing 1.5 servers too)

### Steps to reproduce

Start MTA 1.5
Try to view 1.6 servers

### Version

1.5, 1.6

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
Should be resolved now.
