### ISSUE TITLE
engineRequestModel vehicle open doors bug

### ISSUE THREAD

**Issue by seriusvgf** [multitheftauto/mtasa-blue#2968]
Hi, I downloaded the 1.6 update for testing purposes, there are still a few problems in the engineRequestModel function, for example, I am cloning the model of a four closed vehicle, but only two doors of the vehicle are working. I need to code a special script for this vehicle or is it a bug? For example, "Sunrise", but only two doors open, as soon as I press g, other doors are not processed, even if I press it next to a different door, it goes back to the twond seat.

**Comment by seriusvgf** [comment]
![mta-screen_2023-04-14_03-41-17](https://user-images.githubusercontent.com/129703533/231912444-73f4aac8-660a-4d16-8f0d-751f906e5f11.png)
![mta-screen_2023-04-14_03-41-21](https://user-images.githubusercontent.com/129703533/231912453-22bb999a-3b6c-4372-85c2-8ddf56f6529d.png)


I think it perceives every model as "Elegy", that's why the system perceives it as 2-door I guess.. My cloned vehicle was the 550 "Sunrise" 4-door

**Comment by MegadreamsBE** [comment]
It sounds like this issue belongs in the mtasa-blue repository (https://github.com/multitheftauto/mtasa-blue/issues) instead

**Comment by seriusvgf** [comment]
> It sounds like this issue belongs in the mtasa-blue repository (https://github.com/multitheftauto/mtasa-blue/issues) instead

ah sorry i put it in the wrong place thank you for showing the right way

**Comment by patrikjuvonen** [comment]
Moved to #2967
