### ISSUE TITLE
Deleting chat messages ( deleteChatBoxMessage(message) )

### ISSUE THREAD

**Issue by szampanszampon** [multitheftauto/mtasa-blue#2970]
### Describe the solution you'd like

I think the titles speaks for itself, 

	message = outputChatBox( "Hello" )
	deleteChatBoxMessage(message)

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by PlatinMTA** [comment]
Messages should not be elements otherwise I have a strong feeling that they will be laggy
