### ISSUE TITLE
Dead connection spam hangs the server

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#2977]
### Describe the bug

6 days ago I updated the server to mtasa_x64-1.5.9-rc-21630-20230407.exe and one that day a bug occurred which I thought might have been a 1 off but it just happened again and the bug causes so much spam it makes the server unusable.

The first time it happened, I was in-game and I did a command which reconnects me using redirectPlayer, I couldn't join as it said "nick already in use", then when I did get back in-game I couldn't login because I was already logged in. My player was stuck there as if still playing and the server console was spamming like this which happened just now:

![image](https://user-images.githubusercontent.com/253404/233938635-6ccacc61-dba3-4a7c-b2fb-687e1b5cf2ba.png)

The spam is so bad can't even type in a command to safely shut down the server. So anyway first time it happened we tried kickPlayer and such on that old me but nothing worked so had to restart the server but turns out this is definitely some new bug that was introduced when I updated the server. server.log had ballooned to 37 gb in size from this spam.

### Steps to reproduce

No idea.

### Version

mtasa_x64-1.5.9-rc-21630-20230407.exe

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
This happens because the revert commit ada63d1e67af8b10de70ef601e146d498edc31c6 is only in 1.6, and was not backported to 1.5.9. We never backport changes after a version bump, but we are making an exception in this case, since we have had to backport a couple other things too.

**Comment by patrikjuvonen** [comment]
Resolved via https://github.com/multitheftauto/mtasa-blue/commit/9739a5ea42d482331190e7fadd50e8320480f1f4
