### ISSUE TITLE
Support for markdown in cegui

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#298]
**Describe the solution you'd like**
Add support fork markdown syntax.

**Additional context**
https://sourceforge.net/p/cegui/wiki/markdown_syntax/

**Comment by jushar** [comment]
The link you posted doesn't refer to a CEGUI feature, but is just sourceforge's formatting help page for wikis.

Also, I can't find Markdown parsers/renderers for CEGUI on the internet plus you can alternatively use CEF to render Markdown. Therefore, close.
