### ISSUE TITLE
MTA 1.6: setVehicleLocked no longer works for Bloodring Banger (ID: 504)

### ISSUE THREAD

**Issue by Rob3681** [multitheftauto/mtasa-blue#3000]
### Describe the bug

A vehicle of the model Bloodring Banger (ID: 504) can no longer be locked in version 1.6. The call `setVehicleLocked(vehicle, true)` returns true and a subsequent call `isVehicleLocked(vehicle)` also returns true and indicates that the vehicle is locked, but you can still enter as a driver or as a passenger.

In MTA 1.5, the Blooding Banger can be successfully locked.

It seems to be related to [2c6058d](https://github.com/multitheftauto/mtasa-blue/commit/2c6058d3772ef8dae77df6ad0b2421a86abbe746)

### Steps to reproduce

1. Use MTA 1.6.
2. local vehicle = createVehicle(411, 2479.1999, -1666.699, 13.3)
3. setVehicleLocked(vehicle, true)
4. You can still enter the vehicle.

### Version

Client: v1.6-release-21797
Server: v1.6-release-21765

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by lopezloo** [comment]
https://wiki.multitheftauto.com/wiki/SetVehicleLocked
> This function only prevents the player from opening the vehicle doors. It means that a player can still access a locked vehicle if there's an opened door. Also, vehicles that doesn't have doors can still be accessed aswell.

This vehicle lacks doors.

**Comment by patrikjuvonen** [comment]
1.6 documentation amended with this as a backwards incompatibility note.

Wont fix.

**Comment by lopezloo** [comment]
It's possible to restore old behaviour by just making this vehicle have doors again. Ex.
```lua
run veh = Vehicle(504, 0, 0, 4)
run veh.locked = true
run veh:setDoorState(2, 0)
```
