### ISSUE TITLE
OOP syntax would indexing userdata

### ISSUE THREAD

**Issue by marci8500** [multitheftauto/mtasa-blue#3008]
### Describe the bug

The following code:
```lua
local created_ped = createPed(57, -2407.13184, -600.81421, 132.64844)
created_ped:setData(created_ped, "testable", true)
```
gives the following error: "attempt to index local 'created_ped' (a userdata value)"
The code is written following the instructions in the documentation.

### Steps to reproduce

Use Copy and paste the code which I provided

### Version

Client: v1.5.9-release-21643
Server: v1.5.9-release-21643

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
In OOP the _object_ you are executing the _method_ on is `theElement`. You must omit the object from the arguments.

```lua
    created_ped:setData ( "testable", true ) -- Do not pass created_ped as an argument, you are calling setData on it already
--  ↑ object   ↑ method   ↑ arguments
```

Please use our [scripting forum](https://forum.multitheftauto.com/forum/71-scripting/) or [Discord scripting channels](https://discord.com/channels/278474088903606273/278520948347502592) for help with scripting related issues.

https://wiki.multitheftauto.com/wiki/OOP_Introduction
https://www.lua.org/pil/16.html

**Comment by marci8500** [comment]
Yes. Sorry, I pasted the wrong code. That code would never return with the error that I wrote.
The following code gives the error which I have:
```lua
local created_ped = createPed(57, -2407.13184, -600.81421, 132.64844)
created_ped:setData("testable", true)
```

@patrikjuvonen

**Comment by matheustkn** [comment]
Did you enable OOP on the resource's meta?

**Comment by marci8500** [comment]
> Did you enable OOP on the resource's meta?

Sorry, I did not. That was the problem.
