### ISSUE TITLE
executeBrowserJavascript related crash

### ISSUE THREAD

**Issue by JeViCo** [multitheftauto/mtasa-blue#3015]
### Describe the bug

executing executeBrowserJavascript with empty string cause crash

### Steps to reproduce

Run commands in order:
1. /createTestBrowser
2. /crashMyClient

Sample code:
```Lua
local browser
local size = 200

local function getFakeHtml()
	return "<html><body><h2>Hello world<h2></body></html>"
end

addCommandHandler("createTestBrowser", function()
	browser = createBrowser(size, size, true, false)
	setBrowserAjaxHandler(browser, "assets/index.html", getFakeHtml)

	addEventHandler("onClientBrowserCreated", browser, function ()
		loadBrowserURL(browser, "http://mta/local/assets/index.html")

		addEventHandler("onClientRender", root, function()
			dxDrawImage(200, 200, size, size, browser)
		end)

		addCommandHandler("crashMyClient", function()
			executeBrowserJavascript(browser, "")
		end)
	end)
end)
```

### Version

Client: Multi Theft Auto v1.5.9-release-21643

### Relevant log output
```shell
Version = 1.5.9-release-21643.0.000
Time = Fri May 19 21:43:54 2023
Module = C:\Program Files (x86)\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0x80000003
Offset = 0x013379B6

EAX=60187A20  EBX=00000000  ECX=00000000  EDX=00000000  ESI=0177E4C0
EDI=0000004B  EBP=0177E8D4  ESP=0177E498  EIP=57A479B6  FLG=00000246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by patrikjuvonen** [comment]
So the problem is in executeBrowserJavascript and not executeCommandHandler, instead like how you've titled and described it.

**Comment by JeViCo** [comment]
> So the problem is in executeBrowserJavascript and not executeCommandHandler, instead like how you've titled and described it.

Oops. Fixed

**Comment by CrosRoad95** [comment]
it indeed crashing:
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/3c3b960b-c6cb-42c5-bd10-e95dd5a8ae48)
