### ISSUE TITLE
engineImageLinkDFF and engineImageLinkTXD don't work correctly on some IDs

### ISSUE THREAD

**Issue by Meine1** [multitheftauto/mtasa-blue#3032]
### Describe the bug

When replacing peds or vehicles using a IMG file with engineImageLinkDFF and engineImageLinkTXD, some models don't get replaced 100% of the time as they should. The more models you replace, the more likely these IDs won't work, the most problematic IDs I have found are 280, 60, 58, 44, 22, 17, 13, 7 but there's likely more as I didn't test all of them.

### Steps to reproduce

1. Use MTA 1.6.
2. Start the attached resource (VCskins) [VCskins.zip](https://github.com/multitheftauto/mtasa-blue/files/11543454/VCskins.zip)
3. Change skin to the replaced models (IDs  1, 7, 13, 20, 60, 90, 280, 281 )
4. They should all be GTA Vice City characters, almost all IDs work most of the time but ID 7 and ID 280 rarely work.
5. If they are all correctly replaced, restart the resource until the problem appears.

### Version

Client: v1.6-release-21902
Server v1.6-release-21902

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Pirulax** [comment]
ID 7 (male01) is a very special model, as it's used as some kind of a base for all other models, and it must be loaded at all times [otherwise the game just crashes].
The issues with model 280 are caused by [this](https://github.com/multitheftauto/mtasa-blue/issues/3162#issuecomment-1693954333).

**Comment by TheNormalnij** [comment]
engineImageLinkDFF doesn't change a model immediately. You should use `engineRestreamWorld` to reload models.
