### ISSUE TITLE
Many player functions behave inconsistently when passing an invalid player element

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#304]
**Describe the bug**
Many player functions process the element provided as `CElement*` instead of `CPlayer*`, causing inconsistency between some of the functions. For example, by providing `root` as the element, it will not throw a warning, while some of the functions do.

**To Reproduce**
1. `getPlayerIP(root)` -> `false`, **no warning**
2. `getPlayerSerial(root)` -> `false`, **warning**

**Expected behavior**
Make all functions work consistently. Specific class function -> require that specific class element.

**MTA Client & Server**
Multi Theft Auto v1.5.5-release-13977

**Additional context**
- Should probably also check out other classes while at it.
- I stumbled across to this problem while helping someone with a script problem on our Discord #scripting channel. They were using these two functions together and they asked me why does it throw an error on serial, but not on IP (IP was before serial). I then investigated and found these inconsistencies. And I agree, it is a stupid inconsistency that has to be fixed.
- Does not require backwards compatibility as the only thing changing is we're essentially adding a warning.

**Comment by Addlibs** [comment]
The reason why getPlayerIP (along with getPlayerName and getPlayerAccount) didn't give warnings when passed with a wrong type of element is because they work for multiple element types (that is, _player_ as well as _console_). I've submitted a PR that adds warnings where necessary.

**Comment by patrikjuvonen** [comment]
Thanks for looking into the issue! Much appreciated. That's good info, I didn't quite even think of the *console* type at the time.
