### ISSUE TITLE
dxCreateFont issue

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3061]
### Describe the bug

Drawing custom font sometimes drawing unreadable strings for UTF8 characters (eg. hungarian letters)

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/9255d737-9d68-461a-9457-83f0227a9951)
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/c9a2e3f1-42c0-4191-bcbe-e8790f2b7f32)
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/09ccfc89-3182-4825-af92-3890154d2709)

### Steps to reproduce

dxCreateFont & dxDrawText (using Roboto, OpenSans)

### Version

v1.5.9-21643

### Relevant log output

```shell
No error logs, now testing with v1.5.9-21630 (maybe an update broke it)
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by CrosRoad95** [comment]
are you sure script file is saved as utf8?

**Comment by Xenius97** [comment]
Yes, it's saved as UTF-8.

**Comment by Xenius97** [comment]
Happens when you create font before onClientResourceStart

Wrong:
`local font = dxCreateFont()`

Good:
`onClientResourceStart() -> dxCreateFont()`
