### ISSUE TITLE
Using IMG feature causes map loading issue

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3065]
### Describe the bug

After started using .img feature, map doesn't load like before. 1.5.9 is working fine, 1.6 too with old script, but when we load one .img map will be blinking.
https://streamable.com/umrhmt

### Steps to reproduce

Use custom img (~700mb)

### Version

Multi Theft Auto v1.6-release-21834

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Insigne** [comment]
Can confirm it, the same thing happened to me and the img file size was around ~700mb for me as well.

**Comment by Meine1** [comment]
I have the same issue, it looks like as soon as the streaming memory used by the loaded mods via custom IMG reaches 250+ MB the map starts bugging up like that, also you get insane input lag that makes the game unplayable if there are other players nearby.
