### ISSUE TITLE
Window mode problem

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#307]
**Describe the bug**
Window mode cut bottom of window

My monitor is 1920x1080 pixels

**To Reproduce**
1. Enable window mode
2. Connect to any server
3. You can't see mta version,
4. open client console and move mta window few pixels up
5. now you can see mta version and sometimes explorer bar shows up above mta

**Expected behavior**
MTA Should be displaying properly, don't cut bottom of window

**Screenshots**
Right down corner invisible,
![image](https://user-images.githubusercontent.com/22455534/43739916-f75c89ca-99c9-11e8-8313-8f9e8bfd4540.png)
If i moved window few pixels up, then everything seems to be ok
![image](https://user-images.githubusercontent.com/22455534/43739953-100fc23e-99ca-11e8-9981-b61e4a825a71.png)

**MTA Client (please complete the following information):**
 - Version: newstest, nightly
 - Running in Wine? NO

**Additional context**

**Comment by Citizen01** [comment]
You can not have a 1920x1080 game resolution + the window borders to fit in your 1920x1080 monitor.
Feels like this is the intended behavior to me. I don't see any valid reason to automatically change the game resolution so the game and the borders can fit inside your monitor.

If you want to have the advantages of the windowed mode (like faster alt+tab) and keep all your 1920x1080 game resolution inside your monitor, then you need uncheck the **Windowed** checkbox and select **Borderless window** in the **Fullscreen mode**
![image](https://user-images.githubusercontent.com/626947/43745759-ce8eddce-99e0-11e8-84aa-b0753a2489f6.png)

And then the bottom of the screen won't be cut off (but you won't be able to drag it around).
