### ISSUE TITLE
Some language codes have been changed

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#3077]
### Describe the bug

I don't know if this is intended or not but it has stopped my in-game translation system working properly as many language codes have been changed and I'm not seeing anything in the "important script changes" on this.

For example getLocalization().code would have returned "it" for Italian now it returns "it_IT"

The old language codes are in a table here: https://wiki.multitheftauto.com/wiki/GetLocalization

So I would like to know if I'm going to have to change my script to handle the new codes or if this was an unintended change that will be fixed.

### Steps to reproduce

Change language to something like Italian and use getLocalization().code

### Version

Multi Theft Auto v1.6-release-21852

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by sbx320** [comment]
Looks like an oversight from https://github.com/multitheftauto/mtasa-blue/pull/2505. But I guess we might as well keep it this way, as those are the standard language codes anyway.

**Comment by ArranTuna** [comment]
Is there a list of the country codes so I can update the list on the wiki?

**Comment by TracerDS** [comment]
> Is there a list of the country codes so I can update the list on the wiki?

I think [this](https://community.inriver.com/hc/en-us/community/posts/360010064099-List-of-country-codes-Windows-Language-Culture-Names) has every code you want

**Comment by sbx320** [comment]
> Is there a list of the country codes so I can update the list on the wiki?

It should be each folder in 
https://github.com/multitheftauto/mtasa-blue/tree/master/Shared/data/MTA%20San%20Andreas/MTA/locale

There's also some odd code handling a few select extra cases here https://github.com/multitheftauto/mtasa-blue/pull/2505/files#diff-3e7b37552f0f1951eaf6b3a6aaf918718dea3857881686cd5e4bd67138603e98R49 but that doesn't need to be documented in the wiki.

**Comment by ArranTuna** [comment]
Updated the wiki with all the new codes.
