### ISSUE TITLE
Road bug

### ISSUE THREAD

**Issue by JacobItaly** [multitheftauto/mtasa-blue#3083]
### Describe the bug

Road bug in the Docks. If you'll go with any car in the position, showed in the screenshot - your car is going to get a little bit under textures. It didn't happen in 1.5 btw.

![LCyNLXL](https://github.com/multitheftauto/mtasa-blue/assets/22572159/59fe3662-36c7-4c28-a6ba-0626396e11ed)

![qbHiRAh](https://github.com/multitheftauto/mtasa-blue/assets/22572159/f4d19a47-ad8b-4320-a332-58b660dd7d06)

### Steps to reproduce

- Go to the place like in the picture

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
This is default GTA stuff. Re-export collision file and replace.

**Comment by MegadreamsBE** [comment]
MTA doesn't modify the default map of the game so this is quite unlikely to be caused by MTA.

**Comment by Dark-Dragon** [comment]
Happens in singleplayer as well, so unless just installing MTA breaks the object in the game files, it's not related.

![image](https://github.com/multitheftauto/mtasa-blue/assets/127808/167aad5c-49f8-41ab-9b7d-c0617a0690f7)
