### ISSUE TITLE
Main menu cursor alpha issues

### ISSUE THREAD

**Issue by Daemant** [multitheftauto/mtasa-blue#3088]
### Describe the bug

There are some cases when the cursor becomes invisible in main menu.
It appeared in 1.6, 1.5.9 didn't have this issue, so I think it connected with #2944 and #3034.
I use this script to control cursor visibility:
```lua
function updateVisibility()
	local showDefault = isMainMenuActive() or isConsoleActive()
	setCursorAlpha((showDefault) and 255 or 0)
end
setTimer(updateVisibility, 250, 0)
```
The thing is, that cursor visibility have not always been restored by MTA when player opens main menu. And after blocking setCursorAlpha in main menu, I can't set it visible too, so player stays without cursor at all.

P.S. `isMainMenuActive()` returns `true` when main menu opened with no cursor, so it's not a culprit here. Also, `F8` opened in main menu can repair cursor alpha.

### Steps to reproduce

1. Hide cursor with `setCursorAlpha(0)` in a timer.
2. Start using `Esc` at some intervals, because bug does not always happen.

### Version

Client: v1.6-release-21943 (Windows 7, 64-bit)

### Additional context

Video demonstration: https://streamable.com/uesbqm

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
what about `showCursor`?

**Comment by Daemant** [comment]
It has a lot of side-effects: moving cursor moves camera, controls like character movement are still enabled, and I'm not sure if I can use MTA GUI with cursor hidden by `showCursor`.
