### ISSUE TITLE
Fix unhelpful destroyElement error messages

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#310]
**Is your feature request related to a problem? Please describe.**
Some error messages are unhelpful, like the one from :destroy() method: **Bad argument @ 'destroy'[Expected element at argument 1]**
But if I use the destroyElement() function it actually outputs what it got(**...1 got nil***)

**Describe the solution you'd like**
Adding the type of self to **:destroy()'s** debug message, and to other methods/functions.
I tried to fix it myself, but wasn't able to find the function(GetFullErrorMessage()) which outputs those messages.

**Comment by qaisjp** [comment]
This is because when you so `destroyElement(nil)` you are giving it a nil type and not an element.

What does it say if you so this?

```
e = cresteObject(1337, 0, 0, 0)
desttoyElement(e)
desttoyElement(e)
```

**Comment by qaisjp** [comment]
Can't reproduce 
![image](https://user-images.githubusercontent.com/923242/101414905-d907e300-38de-11eb-8a2d-a700b584beda.png)
