### ISSUE TITLE
Extend exporting (variable exporting)

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#311]
**Is your feature request related to a problem? Please describe.**
My idea is to make possible export variables, for read and write.
Yes, i already can export variable by using functions.

**Describe the solution you'd like**
New new <export> attribute:
```<export type="variable" name="variableName" readOnly = "true" />```
readOnly = true by default.

New Functions:
```lua
mixed value = getVariable( resource, variableName )
bool success = setVariable( resource, variableName, value ) -- return false if is read only.
```
New event:
```lua
"onVariableChanged" with attributes; source of change, resource, variable name, old value, new value
```
**Describe alternatives you've considered**
There's no alternatives.

**Additional context**
-

**Comment by Pirulax** [comment]
If Im not mistaken, every resource has its own luaVM which means, that "exporting" variables'd be slow, just like the normal call() function

**Comment by qaisjp** [comment]
Correct

**Comment by Pirulax** [comment]
Maybe use setElementData as a variable, that's faster if you want a 'very' global(TM) variable.

**Comment by jushar** [comment]
It doesn't introduce new capabilities and might be rather confusing considering that there are exports already.
