### ISSUE TITLE
Turning off the read-only for config folder

### ISSUE THREAD

**Issue by efexc** [multitheftauto/mtasa-blue#3113]
### Describe the bug

We cant turn off
https://streamable.com/b4flob

### Steps to reproduce

Go to settings
Try turn off

### Version

1.6

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Haxardous** [comment]
fixed via https://github.com/multitheftauto/mtasa-blue/commit/2eebc79c443e3033a7f07eb17a42ed2bcf5bdbdb

**Comment by Xenius97** [comment]
> fixed via [2eebc79](https://github.com/multitheftauto/mtasa-blue/commit/2eebc79c443e3033a7f07eb17a42ed2bcf5bdbdb)

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/171218ba-7120-4ab9-8d31-5ec0b3b34295)
