### ISSUE TITLE
setElementInterior/Dimension resets attachElements

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3114]
### Describe the bug

Attached elements will reset if element changes interior/dimension. Need to re-attach.

### Steps to reproduce

attachElements()
then setElementInterior/Dimension()

### Version

Multi Theft Auto v1.6-release-21889 (all prev versions too)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Haxardous** [comment]
https://wiki.multitheftauto.com/wiki/OnElementDimensionChange & https://wiki.multitheftauto.com/wiki/OnElementInteriorChange needs to be used in this scenario as FUNC_AttachEntityToEntity doesn't rely on dimension nor interior. https://github.com/multitheftauto/mtasa-blue/blob/caac437832a967fabb0b3dbad37176b0e2f40ada/Client/game_sa/CPhysicalSA.cpp#L293

**Comment by Xenius97** [comment]
i think this was solved in the past, it works fine now as i see
