### ISSUE TITLE
dxDrawCircle crashes the client

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#313]
After updating to MTA r13987, the game crashes as soon as i want to spawn on a certain map with custom objects.

-Go to my server (SAAW WW2)
-Ask a staff member to open map "Iceberg"
-Try to spawn, game will crash

Server and client is version r13987.

Crash reason: Core.dll

Crash dumps:
https://www.dropbox.com/s/xg5z76ld995hdbm/client_1.5.5-release-13987.0.000_core_001f8874_7363_DPxMb_6D01A8C0_55F3_0C7_7564F_20180807_2129.dmp?dl=0
https://www.dropbox.com/s/6p43qlxugkqms2r/client_1.5.5-release-13987.0.000_core_001f8874_7363_DPxMb_6D01A8C0_55F3_08C_7564F_20180807_2132.dmp?dl=0
https://www.dropbox.com/s/wzf7y8022so1sin/client_1.5.5-release-13987.0.000_core_001f8874_7363_DPxMb_6D01A8C0_55F3_021_7564F_20180807_2129.dmp?dl=0

**Comment by Einheit-101** [comment]
Crash reason is dxDrawCircle.
If stopAngle = 0, game will crash.

**Comment by patrikjuvonen** [comment]
Bug was introduced in PR #266 

cc @CrosRoad95

**Comment by CrosRoad95** [comment]
@Einheit-101 can you give me start and stop angle ?

**Comment by Dutchman101** [comment]
client_1.5.5-release-13987.0.000_core_001f8874_7363_DPxMb_6D01A8C0_55F3_0C7_7564F_20180807_2129.dmp:

https://pastebin.com/51ENhTg8 (dumptrace)

odd..

Caught std::bad_alloc exception: bad allocation
RethrowException

I believe we only use this at 1 place in the source, which is something that @Necktrox added for timer abuse

**Comment by Einheit-101** [comment]
start and stop angle are 0, but it seems like the crash always occurs when start and stop angle are the same.
I retried with start/stop angle at -90, but the crash occured aswell. Now i try with startAngle -90 and stopAngle -89, everything is fine.

**Comment by CrosRoad95** [comment]
so, start angle cannot be equal stop angle and vice versa

**Comment by Einheit-101** [comment]
This code crashes the game:
crun dxDrawCircle(500, 500, 100, 0, 0, tocolor(0,200,0,200), tocolor(0,0,0,0), 32, 1)

**Comment by Dutchman101** [comment]
I confirmed that the above code reproduces the crash. Got similar dumptrace output while reproducing the crash on my own PC;

[https://pastebin.com/vtCyRDBE](https://pastebin.com/vtCyRDBE)

The "RethrowException" therefore is no coincidence.

https://blogs.msdn.microsoft.com/oldnewthing/20100730-00/?p=13273
(debugging a C++ Exception of this type)

I believe it's the responsibility of @CrosRoad95 to continue debugging it.
