### ISSUE TITLE
POR FAVOR OLHEM O MEU POR FAVOR!!!

### ISSUE THREAD

**Issue by Maxinho12010Max** [multitheftauto/mtasa-blue#3137]
### Describe the bug

GENTE EU QUERIA REPORTAR UM BUG QUE EU NAO SEI O QUE ESTA ACONTEÇENDO O MEU PERSONAGEM QUANDO EU ENTRO EM QUALQUER SERVIDOR ELE NAO ANDA EU JA DESINSTALEI O MTA E ABAIXEI DE VOLTA MAIS NAO RESOLVE POR FAVOR ME AJUDEM SERIAMENTE PRECISO FAZER MANUNTEÇAO NO MEU SERVIDOR PRECISO DE AJUDA DE VOCES POR FAVOR FICAREI GRATO SE ME AJUDAREM|

### Steps to reproduce

Eu entro no servidor,e eu fico parado ja apertei varios botoes e nao consigo/ERRO PERSONAGEM NAO ANDA!

### Version

windows 7 64 bits

### Additional context

...

### Relevant log output

```shell
...
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Maxinho12010Max** [comment]
...

**Comment by TracerDS** [comment]
Can you translate that to english?
