### ISSUE TITLE
Server browser not showing all players

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3138]
### Describe the bug

Server browser showing only first 70-80 rows at players tab

### Steps to reproduce

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/0d5c73cf-72f3-4040-9044-e015838a6e42)

### Version

all versions

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by adem-hosni** [comment]
The ase packet size is 1350 bytes is not enough to show 100 players, so it's not a bug.

https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/ASE.cpp#L467
