### ISSUE TITLE
Chat background not working after latest update

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#3148]
### Describe the bug

Henlo,

The chat background is not working anymore after updating to 1.6-release-21923.0.000.
Last version I used which worked was r21890

![grafik](https://github.com/multitheftauto/mtasa-blue/assets/33094646/d450ddd3-9f56-49cd-960b-fbaf2552907f)

![grafik](https://github.com/multitheftauto/mtasa-blue/assets/33094646/23d07fa3-4fc9-48c8-976a-a2954d33c2e2)

Before update, it looked like this:

![grafik](https://github.com/multitheftauto/mtasa-blue/assets/33094646/cc8a1024-2a7d-4bdb-bee4-1d55fb9529b1)

### Steps to reproduce

Add chat background.

### Version

Multi Theft Auto v1.6-release-21923

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
Fixed in 73379e48c68d036fc8e90cb54463d750ecd43749

**Comment by botder** [comment]
Bug introduced in 269c4ac6d97f1e6f829b20e4a2f29480af430962
