### ISSUE TITLE
Add script files loading pattern.

### ISSUE THREAD

**Issue by W3lac3** [multitheftauto/mtasa-blue#3151]
### Is your feature request related to a problem? Please describe.

A feature to assist in loading script files. Many scripts need a vast amount of images, such as an inventory, where you will have images for each item. This feature will allow loading in a more simplified way, allowing programmers to create their `meta.xml` much more easily without the need to put in the meta each new file that enters the script.

### Describe the solution you'd like

Create a pattern to load the files of a resource. Possible patterns:

- assets/*.png
- assets/**/*.png
- assets/subfolder/**/*

```xml
<meta>
    <script src="client/**/*.lua" type="client" cache="false" />
    <script src="server/**/*.lua" type="server" />

    <file src="assets/**/*" />
</meta>
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by botder** [comment]
Duplicate of #2200
