### ISSUE TITLE
engineGetModelTXDID is always 3230 when using on requested skin

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3153]
### Describe the bug

Currently requested skins cannot be replaced via new img feature. Skin will have no textures, cause engineGetModelTXDID returning false info.

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/f6415cae-38e4-432d-8452-37340cfdddaf)

### Steps to reproduce

Use test resource. /skin to change your skin.

[skin.zip](https://github.com/multitheftauto/mtasa-blue/files/12322493/skin.zip)

### Version

Multi Theft Auto v1.6-release-21923

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
Implemented in #3120
