### ISSUE TITLE
engineImageLinkDFF issue

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3162]
### Describe the bug

Some vehicle model replacement isn't working properly.
When you spawn in the game, these vehicles will have default GTA:SA models.
After going far away, and going back it will be modded vehicle again.
I've found these id's only have this issue: 596, 597, 598 (police cars)

https://streamable.com/2hlxey
https://streamable.com/0s9v4b

### Steps to reproduce

Replace 596, restart mta
Then connect to server
Used model:
[596.zip](https://github.com/multitheftauto/mtasa-blue/files/12427179/596.zip)

### Version

Multi Theft Auto v1.6-release-21956

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Meine1** [comment]
I encountered the same issue but with some skin model IDs, mainly 280, 60, 58, 44, 22, 17, 13, and 7 , might be related #3032

**Comment by Pirulax** [comment]
Police cars are cached on a per-region [eg LS, SF, LV] basis, and so are gang vehicles [and maybe even gang ped models].
It is possible that `engineRestreamWorld()` doesn't actually unload those models.
The function [CStreaming::RemoveLoadedVehicle()](https://github.com/gta-reversed/gta-reversed-modern/blob/40691280f3f3a091610e593388225c0b2d28161f/source/game_sa/Streaming.cpp#L2402) is responsible for removing these models.
Now, the cop cars and peds for a specific zone are made `STREAMING_GAME_REQUIRED` in [CStreaming::StreamCopModels(eLevelName level)](https://github.com/gta-reversed/gta-reversed-modern/blob/40691280f3f3a091610e593388225c0b2d28161f/source/game_sa/Streaming.cpp#L3171).
I believe simply disabling these functions [as they simply exist for optimization purposes - as in, faster load times on CD, reducing pop-in] should solve the problem.

**Comment by TheNormalnij** [comment]
`engineRestreamWorld` works for police vehicles

**Comment by Xenius97** [comment]
> `engineRestreamWorld` works for police vehicles

Sometimes yes, sometimes not. Sometimes vehicle will not replace, sometimes it will not have textures just like tunable vehicles.

![image](https://github.com/user-attachments/assets/ef848111-3ee5-451a-9a59-d7bd80fb07cc)

```lua
engineStreamingSetModelCacheLimits(0, 0)
```

**Comment by Xenius97** [comment]
![image](https://github.com/user-attachments/assets/9b0621ff-0e1e-4545-988b-950072e1d956)

This issue isn't solved yet.
