### ISSUE TITLE
engineRemoveImage crash when closing MTA

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3165]
### Describe the bug

When closing MTA, game will not shut down properly
Crash dump: https://upload.mtasa.com/u/251079514/client_1.6-release-22184.0.000_gamesa_0005c40d_5_CGMb_00000001_55F3_256_D6D03_20230828_1655.dmp_

```
Version = 1.6-release-22184.0.000
Time = Mon Aug 28 17:07:08 2023
Module = C:\Games\MTA San Andreas 1.6\mta\game_sa.dll
Code = 0xC0000005
Offset = 0x0005C40D

EAX=23A2A988  EBX=00000002  ECX=23B0AB3C  EDX=33E0391C  ESI=33E0391C
EDI=473360E8  EBP=0177E234  ESP=0177E234  EIP=6725C40D  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

### Steps to reproduce

```
addEventHandler("onClientResourceStop", resourceRoot, function()
	if img then
		engineRemoveImage(img)
	end
end)
```

### Version

Multi Theft Auto v1.6-release-22184

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
I'm unable to replicate this issue from the information provided.

Please can you provide a full, working reproduction script (including loading the IMG container) as well as a copy of the IMG file itself?

**Comment by Xenius97** [comment]
> Please can you provide a full, working reproduction script

Sent in dm
