### ISSUE TITLE
IMG Containers not loading when install directory has special characters

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3166]
### Describe the bug

IMG Containers not loading when install directory has special characters
Eg:
```
"C:\Játékok\GTA San Andreas"
"D:\Játékok\MTA San Andreas"
```

### Steps to reproduce

Load img container
```
modloader_c.lua:85: Error loading IMG
```

### Version

21190

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Pirulax** [comment]
Seems like it's `ParseResourcePathInput` returning `false`.
I guess using `std::string` for utf8 isn't all that good after all.
Also, doesn't this happen with any other function as well?
Like `fileOpen`?

**Comment by TheNormalnij** [comment]
This check failed
```c++
    if (!fs::exists(filePath))
        return false;
```
