### ISSUE TITLE
onPlayerMarkerHit doesnt work when second argument of event is different than "root"

### ISSUE THREAD

**Issue by xaynn** [multitheftauto/mtasa-blue#3169]
### Describe the bug

If you create a marker and use a different second parameter than 'root' in an event, the event doesn't trigger. 

### Steps to reproduce

local marker = createMarker(2422.3276367188,-1519.5313720703,22.828125, "cylinder")

function markerHandler(markerHit,matchingDimension)
outputChatBox("triggered")
print("triggered")
end
addEventHandler("onPlayerMarkerHit",marker,markerHandler) -- it wont work. 
addEventHandler("onPlayerMarkerHit",getRootElement(),markerHandler) -- it works

also same situation in onPlayerMarkerLeave

### Version

Client: Multi Theft Auto v1.6-release-22184
Server: Latest

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
`onPlayerMarkerHit` will work for players only (source is the player). Hence attaching it to the marker does nothing.
See [Element Tree](https://wiki.multitheftauto.com/wiki/Element_tree)

**Comment by bum8hj** [comment]
In your case, consider using `onMarkerHit` and `onMarkerLeave` since you're attaching the handler to a marker.

https://wiki.multitheftauto.com/wiki/OnMarkerHit
