### ISSUE TITLE
Modern style!

### ISSUE THREAD

**Issue by DetectedStorm** [multitheftauto/mtasa-blue#317]
**Is your feature request related to a problem? Please describe.**
No, as a kind of players may feel bored of the classic style, so decided to design a new style dgs
I would like the administration to make it a sub-style Example: dgs, This style is only designed to wait for my suggestion to be accepted.
best wishes!

**Comment by Pirulax** [comment]
dgs is written in pure lua and has nothing to do with the mtasa-blue project itself
go to [this gh repo](https://github.com/thisdp/dgs)

**Comment by DetectedStorm** [comment]
I mean I have a theme, as an example : 
![cgui](https://user-images.githubusercontent.com/33987614/43859801-6acaa784-9b5a-11e8-959c-ca92cff55e3f.png)
@qaisjp 
@Pirulax

**Comment by qaisjp** [comment]
If there's a nice theme you think would be nice please do showcase it!

**Comment by Pirulax** [comment]
That's the default "Lighter black" theme.

**Comment by DetectedStorm** [comment]
I would like to say that I will create a theme for the game using the DGS technology, so that it will become the most beautiful thing that I want to put in the list of designs only, after viewing it.

**Comment by Pirulax** [comment]
DGS is just a simple dx lib thingy as I said.
The MTA client itself uses CEGUI and C++ not Lua.

**Comment by DetectedStorm** [comment]
![screenshot004](https://user-images.githubusercontent.com/33987614/43865860-796e801e-9b6c-11e8-8d81-4d1537fc6671.jpg)
I want to put themes here with the dgs technology.

**Comment by patrikjuvonen** [comment]
DGS is written in Lua. MTA menu system is CEGUI and cannot be replaced. If it would be replaced, it would be replaced by a CEF interface because that's the only thing that makes sense for the future (considering all the advantages of CEF).

**Comment by Dutchman101** [comment]
What you could do is create a new theme using GUI elements that were made to reproduce DGS's appearance, or similar looking. Get permission from the DGS creator, put in some effort into (learning) theme creation and showcase the resulting MTA theme as suggested.

I think that hosting some sort of design contest to pick custom themes made by the community and add them to the official package, is pretty nice to do.. I will discuss it internally.

**Comment by Pirulax** [comment]
And DGS isn't a technology, it's just a simple dx lib.
