### ISSUE TITLE
GitHub Version and server.log version different

### ISSUE THREAD

**Issue by dgibbs64** [multitheftauto/mtasa-blue#3176]
### Describe the bug

I am the lead developer of LinuxGSM
The release version on Github is listed as v1.6.0 however the version on the server.log is listed as v1.6

This is a problem as these numbers are compared to check if an update is available for mta. Having the numbering different causes the linuxgsm updater to update every time
![image](https://github.com/multitheftauto/mtasa-blue/assets/4478206/2ba8bab8-6aee-4567-8897-a5bc7188da3d)

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/modules/update_mta.sh

### Steps to reproduce

Check the version of server.log outputs v1.6 check version on GitHub returns v1.6.0

### Version

v1.6.0

### Relevant log output

```shell
= Multi Theft Auto: San Andreas v1.6 [64 bit]
==================================================================
= Server name      : Default MTA Server
= Server IP address: auto
= Server port      : 22003
=
= Log file         : ..serverfiles/mods/deathmatch/logs/server.log
= Maximum players  : 32
= HTTP port        : 22005
= Voice Chat       : Disabled
= Bandwidth saving : Medium
==================================================================
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Have you considered tracking the versions yourself within LinuxGSM? You could create a file or database entry with the current version (each time you download new server binaries).

Wouldn't this also be better anyway since you can track actual build numbers like 21959 instead of just 1.6?

**Comment by botder** [comment]
You can get the server version with `mta-server -v`.

**Comment by dgibbs64** [comment]
Thanks for your responses

@botder Sadly it returns the following which doesn't match the GitHub version.
```
./mta-server64 -v
MTA:SA Server v1.6-release-21959
```
@Lpsd I prefer to get the version number directly from the application via a flag or log file when possible as its a better source of truth. However, if that is not possible I create a file called build.txt that will log the remote version when it is initially downloaded. In the case of MTA the version number on github and in the logs had previously matched up. However, since the v1.6.0 release, this is no longer the case.

So I think there are two solutions to this:
Solution 1 (you guys): The GitHub release number is altered to match the application release number.
Solution 2 (me): I implement the build.txt solution in LinuxGSM. 

I don't mind which is done personally. But please let me know a preference I will update LinuxGSM as required 😄

**Comment by botder** [comment]
You should really switch to comparing revision numbers instead. We could also place a revision text file on `linux.multitheftauto.com` host.

**Comment by dgibbs64** [comment]
@botder Happy to change to using revision numbers. if the txt file could match `MTA:SA Server v1.6-release-21959` that would be perfect as I could then easily compare against `mta-server -v`

**Comment by botder** [comment]
https://linux.multitheftauto.com/revision/latest.txt
https://linux.multitheftauto.com/revision/1.6.txt
https://linux.multitheftauto.com/revision/1.5.9.txt

**Comment by dgibbs64** [comment]
Brilliant thank you! I will get the MTA updater sorted for the next LinuxGSM release
