### ISSUE TITLE
Desync animation when ped/player leaving the vehicle

### ISSUE THREAD

**Issue by znvjder** [multitheftauto/mtasa-blue#318]
I discovered this bug since last(?) nightly update ( one week ago, maybe two )
![GIF](https://i.imgur.com/tXjXNdl.gif)

**Comment by patrikjuvonen** [comment]
Related PR #143

cc @lopezloo

**Comment by Pirulax** [comment]
could you please fill the form for bug report?

**Comment by StifflersMom** [comment]
The buggy vehicle exit animation sequence was coming with r12195

**Comment by ccw808** [comment]
r12195 is [Implement custom IFP animations](https://github.com/multitheftauto/mtasa-blue/commit/15f99b2fcf70b8d5b82883c49cb2413cd39dee4b)
@saml1er

**Comment by ghost** [comment]
Thanks for the report. I'll fix this asap.
