### ISSUE TITLE
Crash when connecting to passworded server

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3184]
### Describe the bug

Today update broke something, when you try to connect first to passworded server MTA will instantly crash

```
Version = 1.6-release-22204.0.000
Time = Sun Sep 17 11:13:18 2023
Module = C:\ProgramData\MTA San Andreas All\1.6\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x0032F4F4

EAX=00000000  EBX=253DA800  ECX=00000000  EDX=00000000  ESI=00000000
EDI=000004EC  EBP=0177FB50  ESP=0177FB1C  EIP=0072F4F4  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

### Steps to reproduce

Open MTA
Connect to passworded server
(If you connect first to non-passworded server and disconnect then will work)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
https://upload.mtasa.com/u/397017812/client_1.6-release-22204.0.000_gtasa_0032f4f4_5_CGMb_96D2DD25_55FA_001_D6D03_20230917_1115.dmp_

**Comment by botder** [comment]
Crash happens on this line:
https://github.com/multitheftauto/mtasa-blue/blob/725c622b518602a04a905238593b3ad9795ae638/Client/mods/deathmatch/logic/CClientGame.cpp#L377

Introduced in commit 6c86ebbf0801c45d5e0bcbb9d9f2e8fd55525b15 by @Pirulax

**Comment by botder** [comment]
`void* CStreamingSA::ms_pStreamingBuffer[2]` has two null pointers. It crashes here:
https://github.com/multitheftauto/mtasa-blue/blob/725c622b518602a04a905238593b3ad9795ae638/Client/game_sa/CStreamingSA.cpp#L464
