### ISSUE TITLE
MTA 1.6 downloads server cache into MTA 1.5 folder

### ISSUE THREAD

**Issue by JeViCo** [multitheftauto/mtasa-blue#3185]
### Describe the bug

For some reason server cache goes to old MTA folder. Personally, i didn't see anywhere mentioning that MTA 1.6 would use old folder (or i'm just blind). It's probably a bug, since in-game screenshots (F12) go to the 1.6 folder.

### Steps to reproduce

1. Go to your MTA 1.6 cache folder. In my case it is C:\Program Files (x86)\MTA San Andreas 1.6\mods\deathmatch\resources
2. Try modifying anything on your local server, restart resource and go to MTA 1.5 folder
3. See changes in 1.5 folder

### Version

Client: v1.6-release-22204 (Window 10, 64 bit)
Server: v1.6-release-21956 (Window 10, 64 bit) (local server)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
It is working as designed. The cache is shared to avoid redownloads.

**Comment by JeViCo** [comment]
> It is working as designed. The cache is shared to avoid redownloads.

Oh, so it was intentional. User should probably being asked with prompt or additional checkmark like "Do you want to import/transfer/migrate files & settings to a new location?".

I'll mark this issue as "not planned" since the original question was answered.
