### ISSUE TITLE
Assertion failed! CModelInfoSA.cpp

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3192]
### Describe the bug

After using engineRequestTXD and engineSetModelTXDID i get randomly this error and game crashing (disconnect or quit game)

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/1e4656cf-7cf0-432e-a331-669457e2d154)

### Steps to reproduce

Use linked resource from https://github.com/multitheftauto/mtasa-blue/issues/3153

### Version

22195

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
@TheNormalnij  https://github.com/multitheftauto/mtasa-blue/blob/1f7937bf9df9d80d88551624f24f3e0a3d55d091/Client/game_sa/CModelInfoSA.cpp#L817

**Comment by botder** [comment]
Introduced in commit 3e9a3735a8022a0acabaa3041c8a3f8d91e547b7. @TheNormalnij @Pirulax

**Comment by Pirulax** [comment]
If there's no model info, there's nothing to reset, so I think just adding an `if (mi)` guard would be enough
