### ISSUE TITLE
Hanging client on nightly

### ISSUE THREAD

**Issue by jayceon123** [multitheftauto/mtasa-blue#3193]
### Describe the bug

After upgrading to the latest nightly version (r22219), when spawning (mostly) or teleporting, the client keeps freezing and you can only exit by killing the process.
I started to try the older nightly versions one by one and it turns out that the problems start with r22200.
I have not yet managed to reproduce it on a default server.

### Steps to reproduce

Unknown

### Version

Client: v1.6.0-9.22200.0 (and onwards) (Windows 10, 64-bit)
Server: v1.6-release-22219 (Windows 10, 64-bit)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
The issue started in 22200? Are you sure?
![image](https://github.com/multitheftauto/mtasa-blue/assets/38703318/2fe3e314-228b-47c1-8f76-03b7b181b030)

**Comment by jayceon123** [comment]
Okay, so it turns out I was wrong, it's not the r22200 but the r22199 and the problem goes away on r22197 (atleast I installed it back and forth 3 times).
I dont have any clue whats would be the problem, most of the time it happens on spawn and on teleports, it's not even a 50-50% but a 95% to happen and 15% to not.
I checked my unsaved and pushed commits too and there are no changes that can cause this type of client freeze.

E.: My previous version before the upgrade, was rc-22175-20230816.
E2.: The server doesn't even kick me out when the freeze happens

**Comment by jayceon123** [comment]
So the client freeze was caused by a vehicle mod that is in an IMG archive, it's weird as this mod is there for a long time now and only started producing this client freeze nowadays, anyway, if someone wants to go further to see why it's not producing a client crash then I can send the model files and script codes.

**Comment by Dutchman101** [comment]
> anyway, if someone wants to go further to see why it's not producing a client crash then I can send the model files and script codes

@jayceon123 yes, please send it to https://upload.mtasa.com/ and share the link here, as you know only MTA staff can access those links. Just so we can make sure the behavior from those bad models is the same as on previous builds

**Comment by jayceon123** [comment]
As requested: [https://upload.mtasa.com/u/154298295/issue_3193.rar_](https://upload.mtasa.com/u/154298295/issue_3193.rar_)
