### ISSUE TITLE
'CenterOfMass' handling setting affecting vehicle water physics.

### ISSUE THREAD

**Issue by chris1384** [multitheftauto/mtasa-blue#3204]
### Describe the bug

Changing any of the CenterOfMass setting (e.g. Z arg. to -1 or less) can affect the localPlayer if it had driven a vehicle with that setting changed.
Now anytime the vehicle driven by localPlayer gets close to the water, it'll flip the vehicle upside down.
This bugs out indefinitely even after changing to any vehicle or joining another server, the only fix is a game restart.

### Steps to reproduce

1. Use 'hedit' resource. Press 'B' to open its menu
2. Go to 'Body' and change the third setting of CenterOfMass to -3 or something similar
3. Additionally, go to 'Wheels' and change 'Suspension Lower Limit' to the same value as CenterOfMass Z setting
4. profit ig

### Version

client: Multi Theft Auto v1.6-release-22268 (Windows 10 x64)
server: 1.6.0-9.22005.0 (Linux)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Proxy-99** [comment]
I can't reproduce it

```lua
local vheicle = getPedOccupiedVehicle(localPlayer)

local value = setVehicleHandling(vheicle,"centerOfMass",{-1,-1,-1})
local value2= 	setVehicleHandling(vheicle,"suspensionLowerLimit",-1)

print(value)
print(value2)
```

**Comment by chris1384** [comment]
Looks like it doesn't happen anymore.
