### ISSUE TITLE
Change how toJSON works

### ISSUE THREAD

**Issue by TracerDS** [multitheftauto/mtasa-blue#3208]
### Is your feature request related to a problem? Please describe.

Currently `toJSON` will return json encoded string additionally wrapped in an array. That can cause troubles and you have to manually remove the array by doing substring on the string.

### Describe the solution you'd like

It would be best if `toJSON` returned valid values;
for this code
```lua
local tbl = { 1, 2, 3, 4 }

iprint(toJSON(tbl))
```
`toJSON` should return `[ 1, 2, 3, 4 ]`

For this code
```lua
local tbl = { key = 'value', [1] = 12, ['pi'] = 3.14 }

iprint(toJSON(tbl))
```
`toJSON` should return `{ "1": 12, "key": "value", "pi": 3.14 }` and not `[ { "1": 12, "key": "value", "pi": 3.14 } ]`

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
same as #1073
