### ISSUE TITLE
addVehicleSirens for clientside

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#3215]
### Is your feature request related to a problem? Please describe.

This function should have a clientside version, mostly for custom vehicles.

### Describe the solution you'd like

Add ``addVehicleSirens`` clientside.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Proxy-99** [comment]
also we need to add removeVehicleSirens to client side
