### ISSUE TITLE
passwordHash options

### ISSUE THREAD

**Issue by SirLancelot06** [multitheftauto/mtasa-blue#3221]
### Describe the bug

Hello everybody.
I am trying to support the passwordHash function's option with a custom cost for the salt length,
but no matter what I do besides setting the option's table to an empty {} table it always gives me this error in the console:

> [08:39:05] Resource 'loginpanel' changed, reloading and starting
> [08:39:05] Starting loginpanel
> [08:39:05] loginpanel restarted successfully
> [08:39:06] ERROR: loginpanel/sh_actions.lua:19: invalid key to 'next'

I am doing it like this:
`passwordHash(password, "bcrypt", {20,""}, passwordHashed)`
since it said an empty sting but I tried setting it to **nil** or just making the table like this: **{20}**
but I always get the same error, unless I set the table to an empty table like this: **{}**

Do I miss something or just dumb for this or is this a bug (I higly doubt this is a bug tho)?

### Steps to reproduce

`passwordHash(password, "bcrypt", {20}, passwordHashed)`
Setting the options table to anything else than **{}** (Empty table) causes this for me.

### Version

MTA:SA Server v1.5.9-release-21258
Debian

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
So, your line 19 is `passwordHash`.

Can you show your full script if you dont mind?

**Comment by SirLancelot06** [comment]
Yep:
Here is the full server-sided script:
```
function performAccountRegistration(playerSource, commandName, ...)
    if ( playerSource ) then
        local args = {...}
        local parameterCount = #args

        -- Username, E-mail, Password
        if ( parameterCount < 3 ) then
            outputChatBox("Not enough arguments.", playerSource, 255,0,0)
            return
        end

        local username = args[1]

        if ( not isUsernameValid(username) ) then
            outputChatBox("The username can only contain numbers and letters!", playerSource, 255,0,0)
            return
        end

        passwordHash(args[3], "bcrypt", {20}, passwordHashed)
    end
end
addCommandHandler("createAccount", performAccountRegistration)

function isUsernameValid(username)
    if string.find(username, "[^a-zA-Z0-9]") then
        return false
    end

    return true
end

function passwordHashed(hashedPassword)
    outputChatBox("You password was successfully hashed: " ..hashedPassword, playerSource, 100,255,100)
end
```
The options table right now is {20} which is **bad** and it doesn't work (which is fine cause you know... it's bad), but as I said if it set it to {20,""} or {20,nil} it still makes that error. :/
In the documentation it says that if the second argument is an empty string it should generate the salt randomly by itself.
Yet it only works when I set the options table to empty with {}.

**Comment by TracerDS** [comment]
You were supposed to provide a valid key for them
Try this:
```lua
passwordHash(password, 'bcrypt', {
    cost = 20
}, callback) 
```

**Comment by SirLancelot06** [comment]
Thank you very much for helping me and thank you for your time.

I though it just needed a table of values and not Key-Value pairs.
but hey! It works now 😄 Thanks!
