### ISSUE TITLE
Marge lua-package branch

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#323]
**Is your feature request related to a problem? Please describe.**
I asked few weeks ago darkdreamingdan about lua-package branch that he made, and reply that this is done but not marged yet.

**Describe the solution you'd like**
Marge lua-package branch.

**Describe alternatives you've considered**
No alternatives

**Additional context**
https://github.com/multitheftauto/mtasa-blue/tree/feature/lua-packages
![image](https://user-images.githubusercontent.com/22455534/43989169-061f4b04-9d45-11e8-99ef-c57606f3d551.png)

**Comment by qaisjp** [comment]
Replaced with project https://github.com/multitheftauto/mtasa-blue/projects/11
