### ISSUE TITLE
Shaders on markers

### ISSUE THREAD

**Issue by VO1D3V** [multitheftauto/mtasa-blue#3230]
### Is your feature request related to a problem? Please describe.

I wanted to create shader on markers, everything's good but I can't invidually change settings.

The issue is **engineApplyShaderToWorldTexture**
parameter _targetElement_ works only for vehicles, object and peds.

### Describe the solution you'd like

make engineApplyShaderToWorldTexture work also with the markers

### Describe alternatives you've considered

Making them invisible and placing custom object in their place which on i can put shaders invidually.

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by xLive** [comment]
Duplicate of #1111

**Comment by VO1D3V** [comment]
duplicate
