### ISSUE TITLE
Discord RPC gets reset when ANY resource stops

### ISSUE THREAD

**Issue by VulpyWags** [multitheftauto/mtasa-blue#3236]
### Describe the bug

Due to changes in https://github.com/multitheftauto/mtasa-blue/pull/3224 when any resource stops the default Discord RPC starts being used and any custom implementation is gone.

Based on the PR this looks like intended behaviour but I don't think this is expected behaviour for server scripters. 

Can this be removed or improved upon?

### Steps to reproduce

1. Start your Discord RPC resource implementation
2. Stop any resource
3. Your Discord RPC is gone

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by matheustkn** [comment]
Do you have any code examples? It seems to be a problem with how it is being used.

EDIT: The problem really is happening.

**Comment by VulpyWags** [comment]
No it isn't. Due to this commit: https://github.com/multitheftauto/mtasa-blue/pull/3224/commits/b51f43d93d124c54eda83ee6ad4c3fc2ce46385e when ANY resource stops the custom Discord RPC implementation is gone

This is my current implementation, it worked pefectly before mentioned PR: https://github.com/MrGreenGaming/MTA-Resources/tree/master/resources/%5Bmisc%5D/%5Bdiscord%5D/discord_rich_presence

**Comment by znvjder** [comment]
I must have missed that, my bad - fix is already in the PR. Thank you for reporting this!

**Comment by VulpyWags** [comment]
Can confirm that the bug has been solved with the latest nightly build.
