### ISSUE TITLE
Update dbConnect

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3240]
### Describe the bug

The current MTASA database management is very outdated and does not support the latest MySQL authentication plugins. The mysql_native_password is a very old, deprecated authentication method. Currently, if you are using MySQL version 8 or above, it will continuously generate warnings due to the use of this outdated authentication method.

When you try to use newest authentication method:
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/d23a5475-f927-4f81-afac-3325b410a772)

I have 3GB of warning logs due to this issue, and I tried to disable them, but unfortunately, there is no way to do so.
```2023-11-12T19:37:23.178991Z 1350957 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2023-11-12T19:37:23.199353Z 1350958 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2023-11-12T19:37:23.323502Z 1350959 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2023-11-12T19:37:23.699421Z 1350960 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
```

Mysql version: 8.0.34 - MySQL Community Server - GPL

### Steps to reproduce

Use mysql 8+

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Relates to #2772

**Comment by znvjder** [comment]
We can update the MySQL library to the latest version, but I think it might break backward compatibility, requiring every user using MySQL relational databases to change the default authentication plugin to mysql_native_password.

**Comment by Xenius97** [comment]
> but I think it might break backward compatibility

Could be add a new argument, which defines what version are you using. Mysql 5.7 is no longer supported since 2023 October.

**Comment by MegadreamsBE** [comment]
> We can update the MySQL library to the latest version, but I think it might break backward compatibility, requiring every user using MySQL relational databases to change the default authentication plugin to mysql_native_password.

Breaking compatibility is a necessary evil sometimes if it means forcing communities to adopt the latest security standards. I'd consider forcing them to update their MySQL databases as one of those necessary changes. Just give them a decent enough heads up that it will happen and in what version.

**Comment by znvjder** [comment]
>
> Could be add a new argument, which defines what version are you using. Mysql 5.7 is no longer supported since 2023 October.

I don’t see the point of using two identical libraries just so users can choose the version they’ll be compatible with.

>
> I'd consider forcing them to update their MySQL databases as one of those necessary changes. Just give them a decent enough heads up that it will happen and in what version.

I think it’s a very good idea. 👍
