### ISSUE TITLE
mtaserver.conf.template

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3254]
### Describe the bug

After last serverupdate, i've noticed an error message when server starts.
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/d222b176-56dc-410c-916b-cf37bdf2522e)

### Steps to reproduce

Everything works normal, except this error message.

### Version

22313

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
Thanks. It is a harmless error introduced by #3251 - need to add a file exists check before this line https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CMainConfig.cpp#L851
