### ISSUE TITLE
UTF8 Encoding of traffic

### ISSUE THREAD

**Issue by Derbosik** [multitheftauto/mtasa-blue#3256]
### Describe the bug

Traffic sent outside and into my mta server is not utf8 encoded (dbQuery, fetchRemote, etc..).

Traffic sent through an event and then fetchRemote (discord webhooks, etc..) is not encoded properly, resulting in corruption like this: ÄŒ (Original was Č). Same goes for dbQuery, although only with strings from the old mysql module, others are read fine.
This issue seems host-dependant (As it works perfectly fine on a different hosting provider, while on a dedicated machine it doesn't [Latest Ubuntu 22.04 with Latest MTA:SA Nightly Linux 64-bit server].) but I haven't been able to find a fix.

### Steps to reproduce

1. Write a script using a triggerServerEvent with some string and use it in a fetchRemote (Sending a discord webhook for example) function on the server.
2. Launch the script.
3. See the result.

### Version

Client: v1.6-release-22309
Server: v1.6-release-22313

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Derbosik** [comment]
![obrázok](https://github.com/multitheftauto/mtasa-blue/assets/99475875/08ba2eec-8b80-4963-b9d5-d9771aab0e38)
![obrázok](https://github.com/multitheftauto/mtasa-blue/assets/99475875/c8a80aac-9402-4c0e-af76-6d4ebccf767c)
Harcoded utf8 string, same issue (MariaDB server)

**Comment by Xenius97** [comment]
This can be solved easy by running this query after your mysql connection is established:
```lua
dbExec(connection, "SET NAMES 'utf8mb4'")
```

Tested, and problem is solved
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/f940019b-2489-4426-9806-a90b7251f3e6)

**Comment by Xenius97** [comment]
I cannot reproduce discord part, everything works fine.
Maybe your script or file encoding is wrong, use UTF8 - BOM
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/b68d1dba-f274-46a3-9689-6c3904e2d721)
