### ISSUE TITLE
Enable CEF's experimental features

### ISSUE THREAD

**Issue by oaojmiguel** [multitheftauto/mtasa-blue#326]
**Is your feature request related to a problem? Please describe.**
It isn't a problem, just a desire to use CEF's experimental features to create some effects and use it in my server. For example, CEF's experimental features has gaussian blur.

GTMP, a Multiplayer modification for GTA V, has enabled CEF Experimental Features: https://gt-mp.net/forum/thread/1223-gt-mp-server-client-patch-v0-1-638-634/
> Enabled CEF "experimental-web-platform-features" for newer CSS features

**Describe the solution you'd like**
Follow the solution by ed123 in this thread: http://magpcss.org/ceforum/viewtopic.php?f=6&t=12695

> Got this solved. You need to override OnBeforeCommandLineProcessing method of CefApp class.
> 
> In cefsimple project, place the function below inside SimpleApp class:
> 
> virtual void OnBeforeCommandLineProcessing(
> const CefString& process_type,
> CefRefPtr<CefCommandLine> command_line) {
> command_line->AppendSwitch("enable-experimental-web-platform-features");
> }

**Comment by jushar** [comment]
I'm not a fan of generally enabling experimental features. In most cases, it has a reason that they're considered unstable.
