### ISSUE TITLE
Setting flag disable_backface_culling doesn't work

### ISSUE THREAD

**Issue by Zangomangu** [multitheftauto/mtasa-blue#3279]
### Describe the bug

using `engineSetModelFlag` on this flag makes no difference.
engineGetModelFlag works fine.

### Steps to reproduce

Example location: 2305.15, -1089.17, 48.12

Changing through LAhills.ide works fine:
`13743, CEmulwire01, mulveg2lahills, 200, 2097284`
`13743, CEmulwire01, mulveg2lahills, 200, 132`

But this makes no difference
`engineSetModelFlag(13743, "disable_backface_culling", false)`
`engineSetModelFlag(13743, "disable_backface_culling", true)`

Other flags seem to work fine from my testing

### Version

v1.6-release-22345

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
The game applies this flag before object spawning. For me it works. But this flag is reversed in MTA :(

**Comment by Zangomangu** [comment]
See discussion in #3281
