### ISSUE TITLE
Support for basic physics

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#328]
**Is your feature request related to a problem? Please describe.**
support to make simple physics ( boxes and spheres ) with attaching elements to physics.
Calculating physics in lua isn't a good idea.

inside blowVehicle ( hardcoded function in gtasa ) is something that couse that doors, windows fly away from vehicle ( you can get damage from that )

client and server side if it possible ( not too hard )

**Comment by Pirulax** [comment]
There is.
setElementVelocity(0, 0, 0) does it.

**Comment by Einheit-101** [comment]
You need to create a dynamic object, make it invisible, attach your wanted object with it and then use setElementVelocity()
