### ISSUE TITLE
Allow server to change CEGUI skin

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#329]
**Is your feature request related to a problem? Please describe.**
Make function that change cegui style because
![image](https://user-images.githubusercontent.com/22455534/44416876-74d97d80-a574-11e8-8d36-58b76deb4a70.png)
![image](https://user-images.githubusercontent.com/22455534/44416886-799e3180-a574-11e8-9d9b-9008ad021485.png)

**Additional context**
![image](https://user-images.githubusercontent.com/22455534/44416846-5ecbbd00-a574-11e8-8c59-6eb08071666f.png)

**Comment by qaisjp** [comment]
i can't believe i've done this

**Comment by qaisjp** [comment]
https://github.com/multitheftauto/mtasa-blue/commit/d2e3a4342ccdddd3084f3ed135aed14f494b0717, https://bugs.mtasa.com/view.php?id=5802
