### ISSUE TITLE
After the update, the local server and map editor stopped working

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3290]
### Describe the bug

When you try to start the local server or map editor from the MTA menu, you get an "Error loading mod" error. It only works through MTA Server.exe, but why did it stop working in the menu?

I don't know which update exactly broke it, but on version **22345** everything still worked. Today, people reported problems to me and I updated MTA to the latest version and indeed this problem occurs for many people, including me.

![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/193924a8-5c1b-4080-ba12-1ba28bd5b33d)

### Steps to reproduce

1. Click "Start local server" or "Run Map Editor" in the MTA Launcher menu.

### Version

Multi Theft Auto v1.6-release-22361

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
@FileEX Please try again with build https://nightly.multitheftauto.com/mtasa-1.6-rc-22363-20240113.exe

**Comment by FileEX** [comment]
Now the map editor works, but the "local server host" option still doesn't work and I get an "error loading mod" error.
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/11c31a64-a749-48c0-898d-a064bc48ba95)

There is still nothing interesting in the report.log file

**Comment by Dutchman101** [comment]
My results:
pre-r22363: can't use "Host game" or Map editor
r22363: both "Host game" and "Map editor" work again

@FileEX i can't reproduce what you see, please double check

**Comment by FileEX** [comment]
@Dutchman101 @botder  As you can see in the screenshot, the local server still does not start.

Maybe it has something to do with it, but after clicking "host game", the fields with name and number of players are empty (filling them in does nothing and the server still does not start)

![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/393f9498-a8a2-40ce-be51-ea7acf7586c2)

The selected resources list is also empty
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/308254dd-c4bb-4efe-9100-2978adecb9fd)

**Comment by znvjder** [comment]
Newest nightly works for me too.

![a13221](https://github.com/multitheftauto/mtasa-blue/assets/6306267/f5de4f9f-1615-4db5-8fba-4e52fc8bd3a5)

**Comment by Dutchman101** [comment]
@FileEX Maybe you got isolated problem in your files, or bad local.conf, reinstall MTA (or delete "server" folder and run installer with default server components selected) then try again.

**Comment by TheNormalnij** [comment]
@FileEX Run `MTA Server.exe` from `MTA_PATH/server` folder. It gives your more useful information. Fresh install should work too.

**Comment by FileEX** [comment]
Version ``Multi Theft Auto v1.6-release-22364`` works for me. So issue has been fixed :)
