### ISSUE TITLE
fileRead bug

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3297]
### Describe the bug

When we read a file via fileRead, for some reason it is not read correctly (maybe empty lines are being removed?) - I know that it worked correctly half a year ago.

```
[Title]
Some title

[Body]
Some text

[Date]
22.01.2024
```

Lua code

```lua
	        local file = fileOpen('file.txt', true);
	        local data = fileRead(file, fileGetSize(file));

	        local title = string.match(data, '%[Title%]\n(.+)\n\n%[Body%]'); -- nil
	        local content = string.match(data, '%[Body%]\n(.+)\n\n%[Date%]'); -- nil
	        local date = string.match(data, '%[Date%]\n(.+)\n'); -- nil

	        print(title,content,date)
```

Why do I say it's a file reading problem? Because if we insert the same text as a string, everything will be read correctly

```lua
	        local data = [[[Title]
Some title

[Body]
Some text

[Date]
22.01.2024
]]

	        local title = string.match(data, '%[Title%]\n(.+)\n\n%[Body%]'); -- Some title
	        local content = string.match(data, '%[Body%]\n(.+)\n\n%[Date%]'); -- Some text
	        local date = string.match(data, '%[Date%]\n(.+)\n'); -- 22.01.2024

	        print(title,content,date)
```

### Steps to reproduce

Described in the explanation

### Version

Multi Theft Auto v1.6-release-22364

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
On Windows line ends with **\r**\n.
On Unix line ends with \n

Did you also try to print the data itself?

**Comment by FileEX** [comment]
Indeed, changing \n to \r\n helped. I'm just wondering how it worked before (I used old code I wrote once and it worked)

**Comment by Pirulax** [comment]
We open the files in binary mode, thus you get no character normalization.
