### ISSUE TITLE
Fix alpha channel rendering of replaced objects

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#330]
**Describe the bug**
Currently there seems to be an issue with engineLoadDFF or engineLoadTXD that breaks alpha channel of objects. Object ID 3851 (A glass window) has perfectly fine alpha channel rendering and no issues occur.
However, if you try to replace that object with itself (carshowwin_SFSX.dff + carshowglass_SFSX.txd), you do NOT get the same result.

Notice how car and Ped are only visible behind the left window (original object), but they are invisible behind another object that has been replaced by engineLoadDFF/TXD to mimic the original:

![image](https://user-images.githubusercontent.com/923242/44428305-de18bb00-a58b-11e8-9210-d92a4f6d3dff.png)

Notice how some default SA map objects (the house etc) are only visible through the left (original) object, but rendering issues occur through the right object:

![image](https://user-images.githubusercontent.com/923242/44428310-e40e9c00-a58b-11e8-9083-0316b6027c9a.png)

These issues are the exact same if you replace the object with itself, so there must be an issue with model replacing.

**To Reproduce**
-Go to map editor
-Create object 3851 - everything looks good
-start this resource: [issue.zip](https://github.com/multitheftauto/mtasa-blue/files/2307742/issue.zip)
-Notice how alpha channel is suddenly broken

**Expected behavior**
Replacing an object with alpha channel should work the same way like an original object

**MTA VERSION**
Multi Theft Auto v1.5.5-release-14005

*Additional context*
Because some objects are still visible while others are not, it seems like there is a problem with the rendering order.

Maybe i am not aware of a speciality that i need to look out for when replacing an object - if i made a mistake and there is a way to fix this without patching MTA itself, let me know.

**Comment by ccw808** [comment]
When calling [engineReplaceModel](https://wiki.multitheftauto.com/wiki/EngineReplaceModel), try setting `alphaTransparency` to true

**Comment by Einheit-101** [comment]
This does indeed almost fix the problem, thanks. Only the good old GTA SA alpha rendering issues remain, the object culls itself in some camera angles, but i can live with that...

![image](https://user-images.githubusercontent.com/923242/44451411-9b86cb00-a5eb-11e8-891e-b1960aa290a0.png)


What is the disadvantage of doing this for all "engineReplaceModel" calls? To avoid any issues like that i could simply use "true" all the time...

**Comment by ccw808** [comment]
GTA draws objects marked as semitransparent from back to front, which can cause GPU overdraw i.e. use up fillrate.

**Comment by tut001** [comment]
From what I can understand from talking to SAMP and MTA modelers/scripters, GTA SA has Alpha flag 1 and Alpha flag 2 (which you can find on MED). MTA though only has 1 being the flag set on 'engineReplaceModel'.
I have heard that rearranging materials in your model should fix alpha rendering priority by moving materials with transparency to the last material IDs. 
When using textures or materials that are <100% opaque, anything that uses cut out alpha (e.g gang tags, mesh fences) is seen disappearing, although from certain angles the semi transparent (glass etc) will render behind it.
https://www.youtube.com/watch?v=hNc9Yc6vods&feature=youtu.be - I hope we'll one day be able to model windows that doesn't have these issues, it is very big struggle!

**Comment by Wolfee-J** [comment]
It's due to the rendering order. MTA needs a way to force rendering orders.

**Comment by TurkishSparroW** [comment]
add flag your models

local modelID = 7513

engineSetModelFlag(modelID, "draw_last", true)
engineSetModelFlag(modelID, "additive", false)
engineSetModelFlag(modelID, "no_zbuffer_write", true)
engineSetModelFlag(modelID, "disable_backface_culling", true)

**Comment by TurkishSparroW** [comment]
Here are some codes for those who still have this problem.

**Method 1#**

```
local modelsToReplace = {
    { -- Replace object
        colFile = "1.col",
        txdFile = "1.txd",
        dffFile = "1.dff",
        modelID = 1859,
        alphaTransparency = true,
        filteringEnabled = true,
    },
}

local function onClientResourceStartReplaceModels()
    for assetID = 1, #modelsToReplace do
        local modelData = modelsToReplace[assetID]
        local modelCol = modelData.colFile
        local modelTxd = modelData.txdFile
        local modelDff = modelData.dffFile
        local modelID = modelData.modelID

        -- Replace COL file
        if modelCol then
            local colData = engineLoadCOL(modelCol)
            if colData then
                engineReplaceCOL(colData, modelID)
            end
        end

        -- Replace TXD file
        if modelTxd then
            local filteringEnabled = modelData.filteringEnabled
            local txdData = engineLoadTXD(modelTxd, filteringEnabled)
            if txdData then
                engineImportTXD(txdData, modelID)
            end
        end

        -- Replace DFF file
        if modelDff then
            local dffData = engineLoadDFF(modelDff)
            if dffData then
                local alphaTransparency = modelData.alphaTransparency
                engineReplaceModel(dffData, modelID, alphaTransparency)
            end
        end
    end
end
addEventHandler("onClientResourceStart", resourceRoot, onClientResourceStartReplaceModels)

setOcclusionsEnabled( false )
```

**Method 2 #**

```
local modelID = 7513

engineSetModelFlag(modelID, "draw_last", true)
engineSetModelFlag(modelID, "additive", false)
engineSetModelFlag(modelID, "no_zbuffer_write", true)
engineSetModelFlag(modelID, "disable_backface_culling", true)
```
