### ISSUE TITLE
onResourceLoadStateChange not triggering

### ISSUE THREAD

**Issue by TracerDS** [multitheftauto/mtasa-blue#3304]
### Describe the bug

`onResourceLoadStateChange` event is not triggering at all

### Steps to reproduce

1. Create 2 resources
2. Paste this codeblock into resource1
```lua
addEventHandler('onResourceLoadStateChange', root, function(res, oldState, newState)
    iprint(res, 'changed. Old state:', oldState, 'New state:', newState)
end)
```
3. Start resource1
4. Start resource2
5. No output

### Version

Server: MTA:SA Server v1.6-release-22351
Client: Multi Theft Auto v1.6-release-22385

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by bum8hj** [comment]
I believe loading/unloading is different from starting/stopping. As far as I know, it's referring to when (for example) a resource is removed from the resources directory and the resources are refreshed with `refreshResources()`

**Comment by TracerDS** [comment]
> I believe loading/unloading is different from starting/stopping. As far as I know, it's referring to when (for example) a resource is removed from the resources directory and the resources are refreshed with `refreshResources()`

Oh, yeah. After physically removing the resource from the `resources` folder it triggered. So its only when a resource is removed or added to the `resources` folder.
But it should still trigger for resource stopping/starting nonetheless

**Comment by bum8hj** [comment]
> But it should still trigger for resource stopping/starting nonetheless

Well, stopping and starting a resource doesn't change the load state (i.e. the resource folder is still there).
We have `onResourceStop` and `onResourceStart` for that.

**Comment by TracerDS** [comment]
> > But it should still trigger for resource stopping/starting nonetheless
> 
> Well, stopping and starting a resource doesn't change the load state (i.e. the resource folder is still there). We have `onResourceStop` and `onResourceStart` for that.

It does. `getResourceState` rreturns `loaded` when the resource is loaded but not running

**Comment by TracerDS** [comment]
> > But it should still trigger for resource stopping/starting nonetheless
> 
> Well, stopping and starting a resource doesn't change the load state (i.e. the resource folder is still there). We have `onResourceStop` and `onResourceStart` for that.

Right, forgot it just changes the state and not the loading state.
