### ISSUE TITLE
Add new event: onResourceStateChange

### ISSUE THREAD

**Issue by TracerDS** [multitheftauto/mtasa-blue#3305]
### Is your feature request related to a problem? Please describe.

Following #3304 there should be an event for tracking state changes of all resources. `onResourceLoadStateChange` only triggers for load changes (aka removing and creating a resource)

### Describe the solution you'd like

`onResourceStateChange` would trigger when a resource has been stopped, started or refreshed

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by R4ven47** [comment]
How is this event going to behave any different than onResourceStart/onResourceStop?

**Comment by TracerDS** [comment]
> How is this event going to behave any different than onResourceStart/onResourceStop?

it would be much easier to communicate between one event handler and 2 separate event handlers.
With that function you will have more flexibility with managing your resources
