### ISSUE TITLE
Marker size problem

### ISSUE THREAD

**Issue by xAbdulKariM** [multitheftauto/mtasa-blue#331]
hi
i am have problem with markers

the problem is if i am set marker size for example 100 and if i am  used isElementWithinMarker or "onMarkerHit" or "onMarkerLeave"

will isElementWithinMarker return true and i am not in it

or events will run if i am not in it

and i m made function for solved the problem and Which it

[https://wiki.multitheftauto.com/wiki/IsElementInMarker](url)

and this function

[https://wiki.multitheftauto.com/wiki/GetElementsInMarker](url)

and i'm putting this functions in  https://wiki.multitheftauto.com/wiki/Useful_Functions Someone delete pages

and this pic explain what i'm talking about

![image](https://user-images.githubusercontent.com/923242/50401698-816f1c00-0788-11e9-974f-44e1d37cf93c.png)

the code :

```
testMarker = createMarker ( 2492 , -1666 , 12.5 , "cylinder" , 100 , 255 , 255 , 255 , 120 )
setTimer( function( )
outputChatBox ( tostring ( isElementWithinMarker ( getElementsByType ( "player" ) [ 1 ] , testMarker ) ) )
end , 100 , 1 )
```

but if you used my function will the result is

![image](https://user-images.githubusercontent.com/923242/50401574-9dbe8900-0787-11e9-9c49-ee4f4ea1639d.png)

the code :

```
local testMarker = createMarker ( 2492 , -1666 , 12.5 , "cylinder" , 100 , 255 , 255 , 255 , 120 )
setTimer( function( )
outputChatBox ( tostring ( isElementInMarker ( getElementsByType ( "player" ) [ 1 ] , testMarker ) ) )
end , 100 , 1 )
```

i hope approval my functions

**Comment by znvjder** [comment]
IsElementWithinMarker only works as a marker''ll be created and ped must be synced with client.

It works: TRUE
`local marker=createMarker( 2045.56,1533.65,10.67-0.99, "cylinder" , 10, 255, 0, 0, 120 )
local ped=createPed( 10, 2045.56,1533.65,12.67 )
setTimer( function( )
  outputChatBox( tostring( isElementWithinMarker( ped, marker ) ) )
end, 1000, 1 ) `

It doesn't work: FALSE
`local marker=createMarker( 2045.56,1533.65,10.67-0.99, "cylinder" , 10, 255, 0, 0, 120 )
local ped=createPed( 10, 2045.56,1533.65,12.67 )
outputChatBox( tostring( isElementWithinMarker( ped, marker ) ) )
`

Concluding:
i don't know if it's a bug. For me, this function doesn't check the height difference of element what we actually check with the marker. I propose to add argument if we want check the height difference.

**Comment by xAbdulKariM** [comment]
yeh if you used the codes in server side you should use setTimer
but client you don't need setTimer
Concluding:
if used setTimer or not whether client or server the result will return true
and events will run and functions isElementWithinMarker will return true and getElementsWithinMarker will return table is not empty 
but you can use my functions and see the result
and for height it's not problem if you used isElementWithinMarker will fixed it
thank you for your post

**Comment by xAbdulKariM** [comment]
anyone here ?

**Comment by Dutchman101** [comment]
@xAbdulKariM "anyone here?" > For that kind of thing you should join the #development channel in the MTA official discord server.

otherwise, you should just wait patiently till someone properly triages this issue and determines whether or not it's a bug.

**Comment by xAbdulKariM** [comment]
@Dutchman101  Thanks , it's bug , see the images

**Comment by xAbdulKariM** [comment]
hi again , i fixed the marker height in isElementInMarker

https://wiki.multitheftauto.com/wiki/IsElementInMarker#Code

**Comment by Lpsd** [comment]
This isn't a bug, the collision of the marker is slightly bigger than the visual (default SA behaviour).

This difference obviously becomes more noticeable the larger the marker is.

Use colshapes if you want to be more accurate.
