### ISSUE TITLE
Unable to get remaining ammo (as shown by HUD)

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3317]
### Describe the bug

The GTA:SA hud shows ammo, e.g. 69-7. The number 7 is the amount of ammunition in the clip (getPedAmmoInClip), and 69 is the amount of ammunition outside the clip (getPedTotalAmmo - getPedAmmoInClip).

The problem is that when you fire, getPedTotalAmmo changes its value by the number of bullets fired (Because this function returns the total amount of ammo). However, in the GTA SA hud, when you shoot, only the amount of ammunition in the magazine changes, and the total amount changes only when you change the magazine/clip.

For example, we have 69-7 ammo. I shoot 5 times and the GTA HUD will show 69-2, while the MTA functions will show
74-2.

I understand that getPedTotalAmmo returns the total amount of ammo in and out of the clip, so there is a missing feature that allows you to get the amount of ammo only outside the clip (So that this value only changes when the weapon is reloaded). At the moment, we cannot display ammo in MTA in the same way as in the GTA SA hud, because getPedTotalAmmo changes after each shot.

### Steps to reproduce

1. Get some weapon
2. Look at the GTA SA HUD ammo and try to do the same text

### Version

Multi Theft Auto v1.6-release-22396

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dark-Dragon** [comment]
Wouldn't you get the desired amount with getPedTotalAmmo + [Magazine size] - getPedAmmoInClip ?

**Comment by FileEX** [comment]
The main problem is that there is no way to get the amount of remaining ammo outside of the magazine, as shown by GTA's HUD. Because the getPedTotalAmmo function changes its value after each shot. For example if I do

getPedTotalAmmo - getPedAmmoInClip then I will get false values.

getPedTotalAmmo returns me 74, getPedAmmoInClip returns me 5. Meanwhile, hud gta shows 69-5.

And yes, if I do getPedTotalAmmo (74) - getPedAmmoInClip (5), I will get the 69 that the HUD indicates. However, then after the shot I will have 68, 67, 66 etc, and this will not be true, because it should be 69 all the time until I reload the gun.

**Comment by PlatinMTA** [comment]
```lua
local total = getPedTotalAmmo(localPlayer)
local clip = getPedAmmoInClip(localPlayer)

local firstText = total-clip
local secondText = clip
dxDrawText(firstText.." - "..secondText, 800, 600)
```

lets say I have 107 deagle bullets:

107-7 = 100
7 = 7

first display: 100 - 7

now I fire two bullets

105-5 = 100
5 = 5

Im on phone but im pretty sure its that easy, this is a non issue

**Comment by FileEX** [comment]
So I didn't fully understand how getPedTotalAmmo worked. Indeed, the effect is the same as in hud gta sa. Thanks for the explanation!
