### ISSUE TITLE
Incorrect colors for 3D draws

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3320]
### Describe the bug

With any 3D DirectX drawing function, if we specify our exact color code using tocolor, but do not draw as postgui, we get an unexpected result: The color will be different from the specified color.

### Steps to reproduce

1. Test resource - [Download](https://www.file.io/A8Nt/download/yVb11KPRcxsc)
2. Test resource - Run
3. See the difference between the colors

### Version

Client: v1.6.0-release-22408 (Windows 11, 64-bit)
Server: v1.6.0-release-22408 (Windows 11, 64-bit)

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
During later tests, it turned out that this problem only occurs with CLine3D.

**Comment by tederis** [comment]
Did you try `setColorFilter (0, 0, 0, 0, 0, 0, 0, 0)`? The function was added to address this problem.

**Comment by tederis** [comment]
Just as I thought, the problem lay in the color correction. `setColorFilter` function is enough to fix it. The details: https://github.com/multitheftauto/mtasa-blue/pull/3321#issuecomment-1960703565.

If you don't want to disable color filters, you can use `getColorFilter` for calculating the inverse coefficients.

**Comment by ghost** [comment]
> If you don't want to disable color filters, you can use `getColorFilter` for calculating the inverse coefficients.

So should we also remove this code from the material line batcher?
@tederis

**Comment by tederis** [comment]
> > If you don't want to disable color filters, you can use `getColorFilter` for calculating the inverse coefficients.
> 
> So should we also remove this code from the material line batcher? @tederis

I'm inclined to the opinion that it should indeed be removed from the material line batcher, yes. Just because the division by two isn't obvious at all and don't even fix the bug.

**Comment by ghost** [comment]
> I'm inclined to the opinion that it should indeed be removed from the material line batcher, yes. Just because the division by two isn't obvious at all and don't even fix the bug.

Done.
