### ISSUE TITLE
Buildings are not counted to performance stats

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3332]
### Describe the bug

getPerformanceStats() doesnt not showing buildings as elements

### Steps to reproduce

IPB + 
```lua
createBuilding(1337, 0, 0, 3, 0, 0, 0)
createBuilding(1337, 1, 0, 3, 0, 0, 0)
createBuilding(1337, 2, 0, 3, 0, 0, 0)
createBuilding(1337, 3, 0, 3, 0, 0, 0)
createBuilding(1337, 4, 0, 3, 0, 0, 0)
createBuilding(1337, 5, 0, 3, 0, 0, 0)
```

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/b72dfb12-e69b-4287-99c4-88c0216213eb)

### Version

Multi Theft Auto v1.6-release-22410

### Additional context

My suggestion is getPerformanceStats() should display buildings in separated column

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Pirulax** [comment]
AFAIK They aren't MTA elements, that's the whole point of them.

**Comment by TheNormalnij** [comment]
> AFAIK They aren't MTA elements, that's the whole point of them.

They are MTA elements, but they are not streamable by the MTA streamer for elements.
