### ISSUE TITLE
Add a "sync" argument for vehicles, as is done for peds

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3333]
### Is your feature request related to a problem? Please describe.

In the case of peds, when we create static peds that only stand, we can disable their synchronization by setting the "sync" argument to false, which is good for performance.

I think this possibility would also be useful in the case of vehicles, when we create some static vehicles that just stand and do not require synchronization.

I know - You can create a vehicle on the client side, but a ped can also be created on the client side. Why add such a synchronization argument for vehicles? Why not? Since it was added for peds, it would also be useful for vehicles, especially since sometimes a vehicle needs to be created, e.g. from a database, and this is a better solution than sending data from the database to the client.

### Describe the solution you'd like

Add a "sync" argument for vehicles in createVehicle, as was done for peds in createPed

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by znvjder** [comment]
Great idea. I've already added a PR that addresses that. We can also do the same for make static objects on serverside.

#3334

**Comment by MrDadosz** [comment]
I don't know if that's possible with RenderWare but there's should be option to disable vehicle physics for better client's performance and they should behave like objects. A lot of servers are using setElementFrozen for handbrake and they don't need to update vehicle physics, and it's CPU consuming. Even when they are frozen, they react to environment (they are jumping, glitching when you put an object inside it). That would boost up performance. Probably it should be another issue topic.
