### ISSUE TITLE
engineSetModelVisibleTime returns false for custom ID's from engineRequestModel

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3341]
### Describe the bug

`engineSetModelVisibleTime` doesn't work for custom ids

### Steps to reproduce

![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/0b219ccf-3675-4c7a-9d52-a5722cbad9d1)

### Version

Multi Theft Auto v1.6-release-22396

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
Cannot reproduce
```
Executing client-side command: engineRequestModel("timed-object")
Command results: 74 [number]
[20:14:26] TheNormalnij executed client-side command: engineSetModelVisibleTime( 74, 12, 10 )
Executing client-side command: engineSetModelVisibleTime( 74, 12, 10 )
Command results: true [boolean]
[20:14:29] TheNormalnij executed client-side command: engineSetModelVisibleTime( 74, 10, 12 )
Executing client-side command: engineSetModelVisibleTime( 74, 10, 12 )
Command results: true [boolean]
```

**Comment by FileEX** [comment]
Edit: I was probably blind and used "object" instead of "timed-object". However, I encountered a crash when trying to load collisions for this type of object. I know they don't have collisions, but it shouldn't end in a crash. I have already opened a new issue.
