### ISSUE TITLE
МТА - Система GPS

### ISSUE THREAD

**Issue by Andromadauda** [multitheftauto/mtasa-blue#3349]
### Describe the bug

Я загрузил систему GPS от Next RP, при нажатии на бинд в консоли пишет это: 
gpsSystem/lib.lua:1: attempt to call global 'guiGetScreenSize' (a nil value)
Подскажите пожалуйста, как это исправить

### Steps to reproduce

local sx, sy = guiGetScreenSize()

function mkvDrawText(text, x, y, w, h, color, font, pos)
    dxDrawText(text, x, y, x + w, y + h, color, 1, font, pos, "center")
end

function mkvDrawBtnImage(text, x, y, w, h, img1, img2, colorText, font, pos)
    local img = img1
    if isCursorOverRectangle(x, y, w, h) then img = img2 end
    dxDrawImage(x, y, w, h, img)
    dxDrawText(text, x, y, x + w, y + h, colorText, 1, font, pos, "center")
end

function isCursorOverRectangle(x, y, w, h)
    if isCursorShowing() then
        local mx, my = getCursorPosition()
        local cursorX, cursorY = mx*sx, my*sy
        if cursorX > x and cursorX < x + w and cursorY > y and cursorY < y + h then
            return true
        end
    end
    return false
end

### Version

MTA 1.6, Windows 10, DragonHost

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by ffsPLASMA** [comment]
We dont provide support for lua scripts on Github.
Please use MTA forum or discord.

Forum: https://forum.multitheftauto.com/
Discord: https://discord.com/invite/mtasa

**Comment by dmi7ry** [comment]
Вам мама в детстве не объясняла, что воровство — это плохо?

**Comment by dmi7ry** [comment]
> We dont provide support for lua scripts on Github. Please use MTA forum or discord.

Moreover, it's a stolen script/system.
