### ISSUE TITLE
Constant crash with engineRequestModel for timed-object

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3354]
### Describe the bug

When restarting a resource or doing a reconnect, it keeps crashing - Every time or every other time. It occurs in everyone, not just me.
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/e39776ca-d36f-4cda-ad6d-926df8431519)

Then a message appears that there was a problem loading the model with id 74.
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/24f61d37-8a9a-4e1c-8b17-f369fe35f69e)

I believe this is a problem with timed-object because I've never had this problem with regular objects or peds. Currently, I only have 1 custom id on the server, so no other script causes the crash.

@TheNormalnij 

### Steps to reproduce

1. Request ID for timed-object
2. Load/replace model & txd
3. Restart the resource several times or do recononect several times
4. Crash

### Version

Multi Theft Auto v1.6-release-22396

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
Do you have repro resource?

**Comment by FileEX** [comment]
> Do you have repro resource?

Yeah, 
[crash_resource.zip](https://github.com/multitheftauto/mtasa-blue/files/14827722/crash_resource.zip)

Just restart the resource several times or reconnect
