### ISSUE TITLE
SVG artifacts

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3368]
### Describe the bug

At small sizes, such as 16x16, there are artifacts in the form of pixels that should not be there.
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/83b2c19e-45a5-47a0-853b-5a44fb9d0787)

Everything is rendered correctly in the browser
![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/39493ce5-4a66-42f8-8c17-7cb8aefa888e)

### Steps to reproduce

```xml
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.356 10 .714.242h11.27z" fill="red"/></svg>
```

### Version

Multi Theft Auto v1.6-release-22396

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
```lua
dxSetTextureEdge(svg, "clamp")
```

**Comment by FileEX** [comment]
Lol, I didn't realize svg was just a texture. I thought MTA rendered SVG like the browser did
