### ISSUE TITLE
Development mode isn't shared?

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3376]
### Describe the bug

The wiki says that ```setDevelopmentMode``` and ```getDevelopmentMode``` functions are shared. These functions actually exist in the game, but they do not work properly. Changing ```setDevelopmentMode``` on the server side does nothing. For example, the showcol command does not work because it shows the message that development mode is off. In addition, the result from ```getDevelopmentMode``` is different on the client and server sides

### Steps to reproduce

Server side:
1. srun setDevelopmentMode(true) -- returns true
2. type showcol command
3. "showcol will have no effect because development mode is off"
4. srun getDevelopmentMode() -- returns true
5. crun getDevelopmentMode() -- returns false

### Version

Multi Theft Auto v1.6-release-22396

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by bnt0p** [comment]
From what I can see on wiki, both setDevelopmentMode and getDevelopmentMode are Client-Side, not shared.
https://wiki.multitheftauto.com/wiki/SetDevelopmentMode
https://wiki.multitheftauto.com/wiki/GetDevelopmentMode

**Comment by Lpsd** [comment]
The wiki template for those pages is wrong, both commands exist on the server and client respectively. They are independent, meaning changing the development mode on the server will not affect the client and vice-versa.

https://wiki.multitheftauto.com/wiki/DebugSleep appears to be the only development-mode bound function for the server. The `showcol` and `showsound` commands are clientside only.

**Comment by FileEX** [comment]
Okay, I'll add the appropriate information about it to the wiki.
