### ISSUE TITLE
RAM Limit

### ISSUE THREAD

**Issue by Heinemann21** [multitheftauto/mtasa-blue#3390]
### Is your feature request related to a problem? Please describe.

as you know, GTA has a RAM limit, which is expanded with the help of plug-ins, while MTA does not have such a possibility

### Describe the solution you'd like

increase the size of RAM, or find out how to increase it yourself

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Heinemann21** [comment]
when trying to upload your own map to the MTA, the game just freezes due to lack of RAM, maybe there are some solutions about this?

**Comment by TracerDS** [comment]
you cannot increase the amount of ram used because gta is 32bit and thus is limited to max 4GB of ram

**Comment by TracerDS** [comment]
> you cannot increase the amount of ram used because gta is 32bit and thus is limited to max 4GB of ram

You'd have to recompile gta as 64bit version in order to increase that cap

**Comment by Heinemann21** [comment]
> you cannot increase the amount of ram used because gta is 32bit and thus is limited to max 4GB of ram

one gigabyte would be enough, but MTA uses the standard GTA limit of 256mb

**Comment by TracerDS** [comment]
> one gigabyte would be enough, but MTA uses the standard GTA limit of 256mb

limit of 256mb for what, exactly? What limit are you talking about?

**Comment by Heinemann21** [comment]
> > one gigabyte would be enough, but MTA uses the standard GTA limit of 256mb
> 
> limit of 256mb for what, exactly? What limit are you talking about?

RAM memory

**Comment by TracerDS** [comment]
> > > one gigabyte would be enough, but MTA uses the standard GTA limit of 256mb
> > 
> > 
> > limit of 256mb for what, exactly? What limit are you talking about?
> 
> RAM memory

max amount of ram gta can use is 4 GBs, not 256 MBs

**Comment by Heinemann21** [comment]
> > > > one gigabyte would be enough, but MTA uses the standard GTA limit of 256mb
> > > 
> > > 
> > > limit of 256mb for what, exactly? What limit are you talking about?
> > 
> > 
> > RAM memory
> 
> max amount of ram gta can use is 4 GBs, not 256 MBs

how can she use four gigabytes without plugins? its standard limit is 256mb

**Comment by TracerDS** [comment]
> how can she use four gigabytes without plugins? its standard limit is 256mb

by plugins you mean mta resources or...?
And no, the limit is not 256mb. 32bit applications can use up to 4GBs of memory because 2^32 = 4,294,967,296 bytes which is exactly 4 GB

**Comment by Heinemann21** [comment]
stream memory

**Comment by Heinemann21** [comment]
the GTA limit is 256mb

**Comment by TracerDS** [comment]
#2221 related

**Comment by Heinemann21** [comment]
> #2221 related

unfortunately, there is no solution

**Comment by Lpsd** [comment]
Closed as duplicate of #2221
