### ISSUE TITLE
dxDrawMaterialLine3D malfunction in the latest MTA:SA versions

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3399]
### Describe the bug

Since the latest update of MTA:SA, i've encountered a problem with the dxDrawMaterialLine3D function.

### Steps to reproduce

Textures drawn with dxDrawMaterialLine3D are significantly brighter than expected. Colors are rendered incorrectly, resulting in an overly bright appearance that deviates from the intended design.

Original:
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/9901acb7-3ed7-4875-b8ad-3605c6dd2009)

Latest nightly:
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/11e0e14d-0ac1-4bd9-994e-f35f4f8f8e5c)

### Version

I think, caused by: https://github.com/multitheftauto/mtasa-blue/commit/1f2c6e75fb71b01f0053f151e766a232ed33692b

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
Marker color code: #00a6ff

**Comment by tederis** [comment]
That is not an issue. In the latest nightly build you finally have accurate colors. Before 1f2c6e7 colors were distorted by the division by two. See my comment under the PR: https://github.com/multitheftauto/mtasa-blue/pull/3321#issuecomment-1960703565

**Comment by Xenius97** [comment]
> That is not an issue.

It is, these are 2 different colors. This will cause problems on all servers, all 3d stuff needs to be recolored (even if you recolor, you won't get that real color)

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/42d2624c-e298-440f-b89b-4209545523c4)
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/dd51fbd3-aece-443a-9676-af0ad68ab788)

**Comment by ghost** [comment]
The old solution wasn't correct either.
The fix is ​​up to the division has been removed, so it is now possible to specify the colors correctly, but for this you have to use the getColorFilter function, see the example on wiki:
https://wiki.multitheftauto.com/wiki/GetColorFilter

**Comment by tederis** [comment]
Okay. I have conducted a little research. The color should be converted to a linear space before being sent to GPU. That the reason. But it's important to note that before the PR colors were invalid as well. I'll fix it the the next 24 hours.

**Comment by tederis** [comment]
Here is the fix #3402

**Comment by Dutchman101** [comment]
Fixed in 8414476

**Comment by Xenius97** [comment]
> Fixed in [8414476](https://github.com/multitheftauto/mtasa-blue/commit/841447684c2d1992656555f81d73da52b2ce5c4f)

For 3d stuff works fine, but there is a new issue, see: https://github.com/multitheftauto/mtasa-blue/pull/3402#issuecomment-2136843658
