### ISSUE TITLE
`getAccountType` crashes on latest nightly

### ISSUE THREAD

**Issue by TracerDS** [multitheftauto/mtasa-blue#3406]
### Describe the bug

When you download [nightly version](https://nightly.multitheftauto.com), the `getAccountType` will crash if you dont provide an account as an argument to it.
Cloning mta repo and building it manually will properly detect invalid arguments provided to the `getAccountType` function.

### Steps to reproduce

1. Download mta server [from nightly](https://nightly.multitheftauto.com/mtasa_x64-1.6-rc-22470-20240526.exe)
2. Run the server with the runcode resource
3. Running `getAccountType()` - Crash
4. Running `getAccountType('')` - Crash
5. Running `getAccountType(false)` - Crash
6. Running `getAccountType(validAccount)` - Doesn't crash

### Version

Server v1.6-release-22470

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
still crashing on r22485

**Comment by theSarrum** [comment]
It crashes only on x64 builds _(not sure about Linux)_.
And it seems that a similar issue occurs with `fileGetContents`.

**Comment by TheNormalnij** [comment]
I think `CAccount` isn't an element and argument parser doesn't generate checks for it

**Comment by TracerDS** [comment]
but then why would compiling directly work fine?

**Comment by TheNormalnij** [comment]
Hmm. I checked on windows x64 Release and it crashes with `getAccountType('lol')`
It crashes at error handling. I believe `std::optional<std::string>` is the clue

**Comment by TheNormalnij** [comment]
Is there any reason to use `std::optional<std::string>` if the function throws an error?

**Comment by TracerDS** [comment]
> Is there any reason to use `std::optional<std::string>` if the function throws an error?

if its `pcall`ed (or it throws warning) then it should return `false`, hence the `std::optional`

**Comment by TracerDS** [comment]
~~I'd guess `std::optional<std::string>` would crash. `pathListDir` doesnt crash and only 2 other functions use `std::optional`~~
> It crashes at error handling. I believe `std::optional<std::string>` is the clue

yes. `pathListDir` doesnt crash and only 2 other functions use `std::optional`, so...
It would make sense why only these 2 functions crash, but why would it crash on release?
![image](https://github.com/multitheftauto/mtasa-blue/assets/43095317/09a6d321-c615-420c-ad6e-36f185b871f2)

**Comment by TheNormalnij** [comment]
> if its `pcall`ed (or it throws warning) then it should return `false`, hence the `std::optional`

 `pcall` returns true and functions result when success and only false in case of errors. Is this true?
 getAccountType doesn't crash when it returns `std::string`

**Comment by TracerDS** [comment]
> `pcall` returns true and functions result when success and only false in case of errors. Is this true? getAccountType doesn't crash when it returns `std::string`

when function doesnt error then pcall return true + any arguments returned from the function.
when function errors, pcall returns false + error message

**Comment by TheNormalnij** [comment]
So there is no reason to use `std::optinal`

**Comment by TracerDS** [comment]
~~in theory optional would return null in this case~~
Unless it errors, then it would return nothing ;c
Still, it shouldnt crash at all. Something is broken with the release/nightly version
![image](https://github.com/multitheftauto/mtasa-blue/assets/43095317/597d9dad-0410-4a06-a78c-7be14008c9ec)

**Comment by TheNormalnij** [comment]
We can return an empty string or "unknown".
Maybe you could add  lua enum definition for account type and the code won't compile unless all account types have string representation. But im not sure

**Comment by TracerDS** [comment]
> We can return an empty string or "unknown". Maybe you could add lua enum definition for account type and the code won't compile unless all account types have string representation. But im not sure

Or we could focus on fixing `std::optional` on release builds

**Comment by TheNormalnij** [comment]
> Unless it errors, then it would return nothing ;c

There is `ArgumentParserWarn` for that.

**Comment by TracerDS** [comment]
It would throw a warning instead of hard error, I dont think `getAccountType` should throw a soft warning instead of hard error

**Comment by TheNormalnij** [comment]
I dont get why there should be `std::optional`

**Comment by TracerDS** [comment]
> I dont get why there should be `std::optional`

🤔 actually, you're right. Appendum coming right up.

**Comment by TheNormalnij** [comment]
`fileGetContents` could be fixed with `ArgumentParserWarn<nullptr, fileGetContents>` i think

**Comment by TracerDS** [comment]
\+ some refactoring ig
