### ISSUE TITLE
setVehicleModelExhaustFumesPosition for vehicle-specific

### ISSUE THREAD

**Issue by nohear** [multitheftauto/mtasa-blue#341]
Currently it's model-specific, which interferes with tuning-features on certain servers. Vehicle-specific enables more extreme tuning options for players and modellers on servers.

Fumes position should be vehicle-specific, so each player has their own exhaust fume position applied.

Additionally, an option for one fume exhaust for cars with two exhaust fumes would be appreciated (currently available in setVehicleHandling).

Mantis issue: https://bugs.mtasa.com/view.php?id=9778
Related GitHub PR (relation, **to keep in mind**): #390

**Comment by patrikjuvonen** [comment]
Original Mantis issue at https://bugs.mtasa.com/view.php?id=9778
