### ISSUE TITLE
onPlayerProjectileCreation does not work properly

### ISSUE THREAD

**Issue by ffsPLASMA** [multitheftauto/mtasa-blue#3410]
### Describe the bug

The event does not trigger for following actions:
- Shooting a tank
- creating projectiles via createProjectile

Event works fine for:
- Shooting hunter rockets and hydra flare/rockets
- Shooting with rocketlauncher, throwing grenades/molotovs on foot

### Steps to reproduce

Add the event and shoot a tank or use the code:

crun setTimer(createProjectile, 1000, 5, localPlayer, 19)

### Version

Server: MTA:SA Server v1.6-release-22472

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
As far i remember tank only creates explosion, and not projectile.

**Comment by ffsPLASMA** [comment]
> As far i remember tank only creates explosion, and not projectile.

Isnt it a tank grenade which is sort of projectile, could be totally wrong here.
Even then there should be a hint saying about that.

**Comment by ghost** [comment]
> > As far i remember tank only creates explosion, and not projectile.
> 
> Isnt it a tank grenade which is sort of projectile, could be totally wrong here. Even then there should be a hint saying about that.

I don't see tank grenade in createProjectile wiki page. But it is here, see: [explosion types](https://wiki.multitheftauto.com/wiki/Explosion_types)

**Comment by MegadreamsBE** [comment]
I believe tank grenades are indeed not an actual projectile. The game just creates an explosion at the location you're aiming at but does not create a projectile in the process.

**Comment by ffsPLASMA** [comment]
Alright but why is it not triggering for createProjectile?

**Comment by botder** [comment]
> Alright but why is it not triggering for createProjectile?

I guess because the event is coming from a hook when projectiles get created, and the game never creates an actual projectile for explosions.

**Comment by ffsPLASMA** [comment]
> > Alright but why is it not triggering for createProjectile?
> 
> I guess because the event is coming from a hook when projectiles get created, and the game never creates an actual projectile for explosions.

so the wiki entry is wrong:

This event is triggered every time a projectile is created by a [player](https://wiki.multitheftauto.com/wiki/Player) - either through a weapon, a vehicle weapon or [createProjectile](https://wiki.multitheftauto.com/wiki/CreateProjectile).

**Comment by botder** [comment]
> so the wiki entry is wrong:
> 
> This event is triggered every time a projectile is created by a [player](https://wiki.multitheftauto.com/wiki/Player) - either through a weapon, a vehicle weapon or [createProjectile](https://wiki.multitheftauto.com/wiki/CreateProjectile).

Sorry, I was thinking about the client-side. This is server-side:
https://github.com/multitheftauto/mtasa-blue/blob/06d1f1daf55a97bddd2fdf2ce80ad4a01085fbb0/Server/mods/deathmatch/logic/CGame.cpp#L2809
and some lines below:
https://github.com/multitheftauto/mtasa-blue/blob/06d1f1daf55a97bddd2fdf2ce80ad4a01085fbb0/Server/mods/deathmatch/logic/CGame.cpp#L2839

**Edit:** Each "clientside local" projectile that triggers `onClientProjectileCreation` sends a projectile sync packet to the server.

**Comment by Zangomangu** [comment]
> Alright but why is it not triggering for createProjectile?

The reason is that the game doesn't spawn a projectile if it gets instantly blocked, it's documented on the wiki page srsly linked

![image](https://github.com/multitheftauto/mtasa-blue/assets/59518113/7d4662a7-ab01-4844-bc02-3ff4856f0f0e)

**Comment by ffsPLASMA** [comment]
> > Alright but why is it not triggering for createProjectile?
> 
> The reason is that the game doesn't spawn a projectile if it gets instantly blocked, it's documented on the wiki page srsly linked
> 
> ![image](https://private-user-images.githubusercontent.com/59518113/334888914-7d4662a7-ab01-4844-bc02-3ff4856f0f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTYxNDIsIm5iZiI6MTcxODAxNTg0MiwicGF0aCI6Ii81OTUxODExMy8zMzQ4ODg5MTQtN2Q0NjYyYTctYWIwMS00ODQ0LWJjMDItM2ZmNDg1NmYwZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEwMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTVmYTBkN2UwNmJhZDM2YzhiMTExZjE3MjRkNzUyNjY2MjViOWJhMTIxMDYyMjNhMmViOWJkYjE5NmEzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xj7WGjyBI0TQUmKuJgxV9sewcZDziJ_Qak21LRS-PYU)

Thanks for clarification :3

**Comment by ffsPLASMA** [comment]
resolved
