### ISSUE TITLE
Shader is not working propoerly after r22320

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#3415]
### Describe the bug

It looks like the release after r22320 breaks some shaders.

Screens:
![image](https://github.com/multitheftauto/mtasa-blue/assets/2988235/8a42f3a3-2ac1-4e2d-b4bb-17a21704323f)
![image](https://github.com/multitheftauto/mtasa-blue/assets/2988235/ce0f3d31-e836-433f-98f5-77fa965e15dc)

### Steps to reproduce

I'm not sure what exactly caused this issue. To reproduce it, just try [OSWS (MTA community water shader made by Einheit-101)](https://community.multitheftauto.com/index.php?p=resources&s=details&id=18239), it results a black screen.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Works fine for me (Server: 22470, Client: 22388).
~~I'll try on a newer version~~
works fine for 22476

**Comment by gta191977649** [comment]
Looks like 22485 solves the problem, I'll close it for now 
![image](https://github.com/multitheftauto/mtasa-blue/assets/2988235/a7475bc4-5207-4134-99ef-b91bf3fecafb)
