### ISSUE TITLE
ac #4 6666

### ISSUE THREAD

**Issue by DicoSky** [multitheftauto/mtasa-blue#3418]
### Describe the bug

Hey everyone,

Just wanted to share a recent issue we encountered. We received a kick for AC 4 6666 without any explanation or description—just a kick followed by a one-hour ban. I've tried several troubleshooting steps, including:

Reinstalling MTA
Using multiple antivirus programs (Avast, Avira, Bitdefender, Kaspersky...)
Formatting Windows 10
Formatting with Windows 11
Unfortunately, none of these steps have resolved the problem, and still receiving the AC 4 6666 kick.

some logs : 
>7411: 2024-06-06 08:02:53 [9.22476.0.000 10.0] [07236-20032] - CClientGame::SetFileCacheRoot - Is shared 'H:\Program Files (x86)\MTA San Andreas 1.6\mods\deathmatch'
>6402: 2024-06-06 08:02:56 [] [13804] - [app64] Started
>567: 2024-06-06 08:02:57 [9.22476.0.000 10.0] [07236-20032] - CAnimManager::ms_aAnimAssocGroups Address - CAnimManager::ms_aAnimAssocGroups = 0x236c83bc
>7107: 2024-06-06 08:03:29 [9.22476.0.000 10.0] [07236-20032] - Game - Disconnected ( [CD48]) ()
>7045: 2024-06-06 08:03:29 [9.22476.0.000 10.0] [07236-20032] - Disconnect from 127.0.0.1:22003 []
>7411: 2024-06-06 08:20:08 [9.22476.0.000 10.0] [07236-20032] - CClientGame::SetFileCacheRoot - Is shared 'H:\Program Files (x86)\MTA San Andreas 1.6\mods\deathmatch'
>7107: 2024-06-06 08:22:48 [9.22476.0.000 10.0] [07236-20032] - Game - Disconnected ( [CD46]) (Disconnected: You were kicked by  (AC #4 6666))

![Screenshot 2024-05-30 180610](https://github.com/multitheftauto/mtasa-blue/assets/32613334/7941c92e-025e-4159-b9a9-9043f39d8ef5)

https://youtu.be/ho95mXaY6Vw

Also, I'd like to address something else. I've been banned from the forum and Discord for allegedly supporting terrorists, which I find absurd. I'm simply expressing support for my second home, Palestine, and I hope this matter can be understood without unnecessary interference.

### Steps to reproduce

i don't know

### Version

final version

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Please edit your issue name so it would address the issue you're having.

> Also, I'd like to address something else. I've been banned from the forum and Discord for allegedly supporting terrorists, which I find absurd. I'm simply expressing support for my second home, Palestine, and I hope this matter can be understood without unnecessary interference.

Discord bans are not handled in github issues.
If you can contact MTA Staff bot (`MTA Staff#6122`) on discord, you may receive a response to your ban.

**Comment by DicoSky** [comment]
> Discord bans are not handled in github issues. If you can contact MTA Staff bot (`MTA Staff#6122`) on discord, you may receive a response to your ban.

Yeah, but I'm not seeking an unban. Just saying it to avoid the question of why you haven't added this to the forum or Discord.

**Comment by DicoSky** [comment]
and for ac # 4 6666, this issue is really serious and many players are complaining about it.

**Comment by DicoSky** [comment]
and here is a video for that : https://youtu.be/ho95mXaY6Vw
