### ISSUE TITLE
Event called when player paste something

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#343]
**Is your feature request related to a problem? Please describe.**
mta should have event that detect detect when player paste something, if they pressed ctrl + v, then event onPlayerPaste become called with content of clipboard, for security reason, mta could distinguish when player paste something from outside mta and add option to disable this event if player copy something not by setClipboard.
for now, scripters have to do trick with hidden edit box.
Also, could be nice if this will work with files copied from windows too.

**Describe the solution you'd like**
add event `onPlayerPaste` with string containing clipboard called when player press ctrl + v.
for security should be added option to disable this event.

**Describe alternatives you've considered**
add getClipboard that instant return content of clipboard 😂 

**Additional context**
Mantis Bug Report at https://bugs.mtasa.com/view.php?id=7370

**Comment by jushar** [comment]
See 1d9b1efcc7e562df64d897442af38479879e1c67
