### ISSUE TITLE
Building LODs not showing until parent element stream in

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3431]
### Describe the bug

https://streamable.com/yoxezq

### Steps to reproduce

Use createBuilding and make it lod
(Code snippet: #3430 )

### Version

1.6-release-22485.0.000

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Sucupinga** [comment]
- Um arquivo LOD é uma modelagem em low poly com texturas de baixíssima resolução para representar as modelagens pesadas quando os jogadores não estão perto delas, otimizando o jogo e trazendo uma gameplay mais confortável.

 - Adicione os elementos (tanto a modelagem normal como a de Low level(LOD)) em um script replace. EX:

-- exemplo de replace de uma modelagem do jogo por uma externa --

txd = engineLoadTXD([diretório e nome do arquivo txd], [id do modelo] )
engineImportTXD(txd, [id do modelo])
dff = engineLoadDFF([diretório e nome do arquivo dff], 0 )
engineReplaceModel(dff, [id do modelo], true)
col = engineLoadCOL ( [diretório e nome do arquivo col] )
engineReplaceCOL ( col, [id do modelo] )
setOcclusionsEnabled( false )

-- após o replace do objeto pai e filho adicione uma distancia máxima para o OBJETO PAI:
engineSetModelLODDistance([id do modelo], 300) -- 300 é a distancia máxima que o OBJETO PAI pode ter.

-- fim do exemplo --

 - agora crie os objetos, tanto pai quanto filho:

local elementoPai = createObject ([id do modelo], posX, posY, posZ, rotX, rotY, rotZ) 
local elementoFilho = createObject ([id do modelo], posX, posY, posZ, rotX, rotY, rotZ, true)

 - faça de um o filho do outro:
setLowLODElement(elementoPai, elementoFilho)

 - abaixo adicione a distancia que será dada ao OBJETO FILHO:
engineSetModelLODDistance ( [id do modelo] , 5000 )

 - Lembrando que você pode pegar a posição dos objetos que deseja substituir pelo edit map, caso queira adicionar novos modelos sem substituir os antigos existem vários ids de objetos nao usados originalmente no game que você pode substituir e colocá-lo em qualquer lugar do mapa, se usar o exemplo acima além de ter uma nova modelagem ela também nao sumirá assim que você se distanciar dela, dando ao cenário mais originalidade e melhorando a gameplay dos jogadores.
