### ISSUE TITLE
mtasa.com wrong default version

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3433]
### Describe the bug

I've installed a fresh install, and version doesn't match with auto-update default (Multi Theft Auto v1.6-release-22476)

https://nightly.mtasa.com/ver/
Auto-update default: 1.6.0-9.22388.0

### Steps to reproduce

Download client from mtasa.com

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
For future readers: full installer distribution was set to 22476, client auto-updater was set to 22388
