### ISSUE TITLE
onClientDebugMessage/onDebugMessage recognize level 4 as 0

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3439]
### Describe the bug

As in title.

### Steps to reproduce

```lua
outputDebugString("test", 4, 255, 255, 255)

-- client

function onClientDebugMessage(debugMessage, debugLevel)
	iprint(debugMessage, debugLevel)
end
addEventHandler("onClientDebugMessage", root, onClientDebugMessage)

-- server

function onDebugMessage(debugMessage, debugLevel)
	iprint(debugMessage, debugLevel)
end
addEventHandler("onDebugMessage", root, onDebugMessage)
```

### Version

r22489

### Additional context

Level 4 was added in #1167 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Hmm, looks like level 4 calls `LogCustom` which calls `LogString` with level = 0
[![image](https://github.com/multitheftauto/mtasa-blue/assets/43095317/5a59c347-7e80-43f8-b411-c965109943d1)](https://github.com/multitheftauto/mtasa-blue/blob/master/Shared/mods/deathmatch/logic/CScriptDebugging.cpp#L66)
