### ISSUE TITLE
isVehicleRespawnable & getVehicleRespawnDelay & getVehicleIdleRespawnDelay

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3441]
### Is your feature request related to a problem? Please describe.

There are already [getVehicleRespawnPosition](https://wiki.multitheftauto.com/wiki/GetVehicleRespawnPosition), [getVehicleRespawnRotation](https://wiki.multitheftauto.com/wiki/GetVehicleRespawnRotation) but there is no respective getters for: whether vehicle is respawnable (based on [toggleVehicleRespawn](https://wiki.multitheftauto.com/wiki/ToggleVehicleRespawn)), vehicle respawn delay and vehicle idle respawn delay.

### Describe the solution you'd like

```lua
bool isVehicleRespawnable ( vehicle theVehicle )
```

Returns true if vehicle respawn is enabled, false otherwise.

```lua
int getVehicleRespawnDelay ( vehicle theVehicle )
```

Returns time in milliseconds, false if unsuccessful.

```lua
int getVehicleIdleRespawnDelay ( vehicle theVehicle )
```

Returns time in milliseconds, false if unsuccessful.

### Describe alternatives you've considered

Wrappers

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by ghost** [comment]
I'm interested.
If everything goes well, the pull request will come soon.

**Comment by TracerDS** [comment]
> I'm interested. If everything goes well, the pull request will come soon.

Yes 😎

**Comment by ghost** [comment]
> > I'm interested. If everything goes well, the pull request will come soon.
> 
> Yes 😎

You were a bit faster than me 🤣
