### ISSUE TITLE
Getting files and directories in specified path

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#346]
**Is your feature request related to a problem? Please describe.**
Years/two ago i made function for it but was rejected.
I want function to this serverside that return every file in path even isn't inside meta.xml and slightly different function clientside, this return only every file belonging to selected resource.

If function return path as raw string, then should be added function to convert pathes into better format ( example table ).

**Comment by ricksterhd123** [comment]
Using wildcards to filter search will be nice too, e.g '*.map'.

**Comment by Fernando-A-Rocha** [comment]
Close this, already implemented
