### ISSUE TITLE
setPedEnterVehicle dimension issues

### ISSUE THREAD

**Issue by Serius41** [multitheftauto/mtasa-blue#3473]
### Describe the bug

In the 1st video, when I set the dimension of the pad and the car to 0, everything works normally, no problem, but 
Video1: https://streamable.com/mhx1es

In the 2nd video, when I set the dimension of the pad and the car to 50, the functions do not work, what could be the problem
Video2:https://streamable.com/m9er18

### Steps to reproduce

.

### Version

Multi Theft Auto v1.6-release-22512
Copyright (C) 2003 - 2024 Multi Theft Auto

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by MegadreamsBE** [comment]
Are you setting the player responsible for calling setPedEnterVehicle to dimension 50 on the server as well? If not, that's intended behavior as you are not the syncer of the ped nor vehicle in the eyes of the server.

**Comment by Serius41** [comment]
> Are you setting the player responsible for calling setPedEnterVehicle to dimension 50 on the server as well? If not, that's intended behavior as you are not the syncer of the ped nor vehicle in the eyes of the server.

I give the same dimension to all elements, but the process is triggered only at 0.

I tried with the code given on the wiki and the same problem persists.

**Comment by MegadreamsBE** [comment]
> > Are you setting the player responsible for calling setPedEnterVehicle to dimension 50 on the server as well? If not, that's intended behavior as you are not the syncer of the ped nor vehicle in the eyes of the server.
> 
> I give the same dimension to all elements, but the process is triggered only at 0.
> 
> I tried with the code given on the wiki and the same problem persists.

In your video you only set the dimension of the player to 50 on the client. Thus, they will fail the check on the server that makes them the syncer. Intended behavior, change the dimension of the player on the server.
