### ISSUE TITLE
Vehicles falling out of map becoming useless without syncer caused by new vehicle_contact_sync_radius

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3484]
### Describe the bug

https://streamable.com/q66fh3

### Steps to reproduce

Create a vehicle under the map
Fly away
Go back and vehicle will be useless

### Version

Multi Theft Auto v1.6-release-22518

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by MegadreamsBE** [comment]
Not specifically an issue with vehicle_contact_sync_radius nor something that would happen normally.

Basically, you leave the radius in which you are a syncer before the vehicle hits the bottom of the map. Your client will still try and move the vehicle back to the ground when you get nearby enough (but out of radius), but this won't be reflected on the server.

The difference now is that in the past, if you touched the vehicle, you'd become its syncer and the vehicle would be moved to your point (this was a bug). This is no longer the case. Mind you, that if you didn't touch the vehicle the issue would be the exact same on older versions.

**Comment by MegadreamsBE** [comment]
To add to my previous comment, the vehicles are not actually useless. If you move them on the server in range of a syncing player (or use setElementSyncer to do so manually), they will function as normal. Similarly, if you bring the player close enough to the actual position of the vehicle (within a range of 130) it will also work as intended.
