### ISSUE TITLE
outputDebugString level 4 colors not working

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3489]
### Describe the bug

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/aae4c628-6140-440c-8297-8132634b6a97)

### Steps to reproduce

for i=1, 5 do outputDebugString("aaaaaaaa"..getTickCount()+i, 4, 255, 0, 0) end

### Version

MTA:SA Server v1.6-release-22518

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
#3471 -> #3474

**Comment by Xenius97** [comment]
on client side works well, i think only server side is broken

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/67566bf7-aef4-445b-a627-dbfb31262388)

Multi Theft Auto v1.6-release-22518
MTA:SA Server v1.6-release-22518

**Comment by ghost** [comment]
It has been fixed, just wait for new nightly build.

**Comment by TracerDS** [comment]
Related #3471 
(just for github reference)

**Comment by Xenius97** [comment]
okay, thanks
