### ISSUE TITLE
Map Editor bugs out

### ISSUE THREAD

**Issue by JacobItaly** [multitheftauto/mtasa-blue#3527]
### Describe the bug

Hello there!

Recently noticed a strange behaviour from Map Editor. My friend and other friends also got it. It started when MTA started launching weirdly. Yes I do have ASI Mods but they never affected the game, and usually prompt about "Installed ASI" things popped up fast. Recently however, when I launched MTA:SA it showed the logo, but then without any prompt about installing new updates or something icon dissapeared 3 times and it launched. It's still going to this time, but at that time still editor was fine. Yesterday editor was also fine for me, however today I wanted to do a new RACE map and it half-worked. Checkpoints didn't had any arrows when I put them and when you usually select the Checkpoint by just clicking on it, and duplicating it - it already sets nextid for the next correct checkpoint. It didn't happen. I needed to manually re-add nextid to every checkpoint but that's just tip of the iceberg. When I quit, the worse thing started to happen that my friends and others report to me. As soon as I go to the editor i have problems:

[17:23:18] WARNING: editor_main\server\mapsettingssync.lua:158: The resource isn't active
[17:23:18] ERROR: editor_main\server\mapsettingssync.lua:159: bad argument #1 to 'lower' (string expected, got boolean)
[17:23:24] WARNING: editor_main\server\mapsettingssync.lua:158: The resource isn't active

![2](https://github.com/multitheftauto/mtasa-blue/assets/68738193/408709b0-6d86-447b-833f-f4ba5cf9f0fd)
![1](https://github.com/multitheftauto/mtasa-blue/assets/68738193/358b3428-55f6-4ea2-b2ce-c45cebbb57ee)

What the hell is happening? I clearly have all gamemodes in, but in the next screenshot im about to show you there are no gamemodes, no nothing. I can't ever save and it says at the beginning that editor_dump is missing (it randomly vanished, wtf?)

[17:34:41] ERROR: editor_main\server\mapsettingssync.lua:159: bad argument #1 to 'lower' (string expected, got boolean)
![mta-screen_2024-06-30_17-34-44](https://github.com/multitheftauto/mtasa-blue/assets/68738193/0cdd2cc8-748b-42c7-ba3b-1cef5d90ba5f)
![mta-screen_2024-06-30_17-34-51](https://github.com/multitheftauto/mtasa-blue/assets/68738193/43ae645c-5111-44ec-88fe-91b477f164b7)

Can you please explain, what might be happening? I don't want to reinstall my MTA yet again. And strangely enough, when my friend reinstalled MTA problem came back.

### Steps to reproduce

- Just simply enter the editor
- In my case I did a RACE map in the Unity Station with Glendale - 22 checkpoints
- I saved the map, everything is fine up to this point
- I tested the map, it worked fine
- I quit the editor
- I quit the game
- I came back to the game
- Opened editor again
- The error pops up about editor_dump
- And first thing I see in the console is 
![3](https://github.com/multitheftauto/mtasa-blue/assets/68738193/7baf7868-3ef7-4992-8af9-b67efc4a3b20)
- I try to make a new map - nothing happens, nothing loads
- I try to open Map Settings / Definitions / in Map Settings / Gamemodes (nothing is there)
- I try to load the map (nothing works)

### Version

Multi Theft Auto: San Andreas v1.6

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
#3363 related.
Its probably due to the
```cpp
if (!resource->IsActive())
```
check

**Comment by botder** [comment]
Fixed by the revert 13f366d8f2ccc2ba4662c8ac58f70e678afc9e87
Revision 22596 contains the revert
