### ISSUE TITLE
Syncing custom animations?

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#353]
**Is your feature request related to a problem? Please describe.**
Custom animations are not synced when you call `setPedAnimation` or `engineReplaceAnimation`.  There is a resource [ifp_demo](https://drive.google.com/open?id=1L2NkQYuLS0YdoHECvxVRMdPBbEgaYUfH) on engineLoadIFP wiki page that shows how to sync animations properly in Lua. I think it's better if we add an option somewhere to sync animations without the need for writing code for it in Lua, because apparently most scripters (especially newbies) simply don't understand how sync works.

**Additional context**
I don't know how we should do it. Should they take an extra parameter for syncing custom animations from client side? This is how they currently look:

`bool setPedAnimation ( ped thePed [, string block=nil, string anim=nil, int time=-1, bool loop=true, bool updatePosition=true, bool interruptable=true, bool freezeLastFrame=true, int blendTime=250] )`

`bool engineReplaceAnimation ( ped thePed, string InternalBlockName, string InternalAnimName, string CustomBlockName, string CustomAnimName )`

The main reason why I haven't implemented sync for client side animation functions is because not everyone wants to sync animations when you call these functions from client side. It should be optional, if it's not optional, client side animations will get synced for old scripts as well, so we need to make it optional in a nice way. Let me know if anyone has any suggestions.

**Comment by Einheit-101** [comment]
It should definitely be optional. I implemented custom animations a long time ago and definitely need some players using other animations than the rest of the players.

The only downside of the current system is the fact that its impossible to use "setPedAnimation" on server side because that will always use the original GTA animation. Server side function should have a parameter like "useModified" that causes clients to use the modified animation that is currently loaded.
Currently we have to trigger a client event and do setPedAnimation on the client side.

**Comment by qaisjp** [comment]
I think setPedAnimation with original blockName/animName should use the custom one client-side. You could force original animations by prefixing the blockName with `sa.`

There's also a backwards compatibility implication if we change how serverside setPedAnimation works... that should either be fixed or somehow disabled

**Comment by CrosRoad95** [comment]
what if server play custom animation which doesn't exists clientside? should return false? or make callback if user want get real result ?

**Comment by qaisjp** [comment]
If I recall correctly, setPedAnimation serverside always returns true (unless there's a problem with the ped)

**Comment by ghost** [comment]
I made a mistake in the original post, `setPedAnimationProgress` actually works for custom animations on server side, fixed it.
@Einheit-101 
> The only downside of the current system is the fact that its impossible to use "setPedAnimation" on server side because that will always use the original GTA animation

That's how it's suppose to work. If you want to play a custom animation, you should be able to give the custom IFP block and animation name. For example, this should play the custom animation if executed on server side (synced):
```
setPedAnimation ( ped, "customBlockName", "customAnimName")
```
It won't work now because there's no support for custom anims on server side, but that's how I plan to make it work. The only problem comes with client side, should we allow sync for setPedAnimation or engineReplaceAnimation when executed on client side? I think this will make things a lot more easier for people who are trying to take full advantage of custom animations.

@qaisjp yes, we need to make it backwards compatible.  That's why I asked whether we should add another parameter to setPedAnimation and engineReplaceAnimation like `bool syncAnimation` which will be false by default:

`bool setPedAnimation ( ped thePed [, string block=nil, string anim=nil, int time=-1, bool loop=true, bool updatePosition=true, bool interruptable=true, bool freezeLastFrame=true, int blendTime=250, bool syncAnimation=false] )`

`bool engineReplaceAnimation ( ped thePed, string InternalBlockName, string InternalAnimName, string CustomBlockName, string CustomAnimName [, bool syncAnimation=false] )`

@CrosRoad95 Nothing will happen if the animation doesn't exist on client side. Why would someone even want to play animations that don't exist? :thinking:

**Comment by Einheit-101** [comment]
@saml1er 

> ....Should we allow sync for setPedAnimation or engineReplaceAnimation when executed on client side?....

It would make things easier, but is not a must-have imho.
engineReplaceAnimation(thePed, InternalBlockName, InternalAnimName, CustomBlockName, CustomAnimName, sync[TRUE, FALSE] )

> setPedAnimation ( ped, "customBlockName", "customAnimName")

...it is good to see that this is planned. Thats the best way to achieve it and i look forward to it.

**Comment by ghost** [comment]
I'm going to implement new synchronization system. This won't be needed.
