### ISSUE TITLE
onClientObjectBreak is not triggered when break the glass with an explosion

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3532]
### Describe the bug

When the glass is broken by an explosion, e.g. of a grenade, the satchel to event ``onClientObjectBreak`` is not triggered at all.

### Steps to reproduce

1. crun addEventHandler("onClientObjectBreak", root, function(attacker) outputChatBox(tostring(attacker)) end)
2. run me.position = Vector3(0, 0, 4)
3. crun obj = Object(1649, 0, 5, 4)
4. Throw a grenade or satchel etc

### Version

Multi Theft Auto v1.6-release-22518

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
Fixed in dca5e20
