### ISSUE TITLE
From some reson getResourceName returns "resource isn't active"

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#3535]
### Describe the bug

Clean mta server, official resources downloaded from https://mirror-cdn.multitheftauto.com/mtasa/resources/, and suddenly getResource name throw weird error i can't find in sources of mta. It happen only on newest builds
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/a1b0594b-3521-41ba-a1cb-50a0be28756a)

### Steps to reproduce

1. download newest mta from https://nightly.multitheftauto.com/
2. download resources from https://mirror-cdn.multitheftauto.com/mtasa/resources/
3. add loadstring to acl
4. type code to getResourceName ( example from image above )

### Version

Server version: 1.6-release-22592

### Additional context

gjm

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Fixed in latest nightly.
#3527 related

**Comment by ghost** [comment]
Fixed in r22596
