### ISSUE TITLE
Custom Animations are requiring improvements in a way

### ISSUE THREAD

**Issue by dretax** [multitheftauto/mtasa-blue#354]
**Describe the bug**
You cannot use the running animation of a custom animation, but for CJ.
I believe the setPedStat could be atleast faked on other skins, without trying to apply the visual look on them.
Take a look at the following forum post:
https://forum.mtasa.com/topic/110961-custom-animations-question/

**Expected behavior**
Able to set 1000 stat of 23 to any player without skin checking.
Any other solution is fine also.

**Screenshots**

**MTA Client (please complete the following information):**

**MTA Server (please complete the following information):**
Linux, Latest. 

**Additional context**

**Comment by qaisjp** [comment]
Please can you edit your issue using the format outlined here: https://github.com/multitheftauto/mtasa-blue/issues/new?template=bug_report.md

Thanks.

**Comment by ghost** [comment]
> **Expected behavior**
Able to set 1000 stat of 23 to any player without skin checking.

Just saw this on wiki:
> Visual stats (FAT and BODY_MUSCLE) can only be used on the CJ skin

23 is BODY_MUSCLE. Your title contains "Custom Animations" keyword. This is not related to custom animations. You want to make setPedStat skin independent for BODY_MUSCLE as it currently supports CJ only.

**Comment by dretax** [comment]
It IS RELATED. It is a solution that could solve the issue.
The running animation cannot be used hence It requires the player's skill to be 1000 to run with an M4.
I used setPedAnimation to obviously allow the players to run with a weapon, but only then the running animation won't trigger.
This is something I thought could be the easiest way to resolve the issue.

**Comment by ghost** [comment]
> I used setPedAnimation to obviously allow the players to run with a weapon

Why not use engineReplaceAnimation? It will make things a lot more easy, you won't need any extra code for it.

**Comment by dretax** [comment]
What difference would It trigger? I don't really see why would that give me a constant ped animation. 
Basically I am doing almost the same, just loading a new one, but since by default I cannot run with an M4, I cannot have the animation that was made for It.

**Comment by ghost** [comment]
If you replace the idle_stance animation from "ped" block, the animation will automatically play for you when you get idle i.e., you don't move. The animation will change when you move, if you don't move and go to idle state, the custom animation will play again because you are idle. In the same way, if you replace the running animation with weapon, the animation will play for you when you are running with a weapon and change automatically when you are not. 

Now, if you use setPedAnimation like you are using now, you'll need to detect keys and change animation accordingly which can be hard, like moving right, left, forward, and backward. You don't have to worry about this problem if you use engineReplaceAnimation.

**Comment by dretax** [comment]
Sorry I used setPedWalkStyle.
Is there a way for me to know which one is the default armed running animation or swat armed running animation?
Maybe run_armed in ped?

**Comment by ghost** [comment]
I forgot which one, but I think it can be "run_1armed" or "run_armed" from ped block, sometimes "musclerun_armed" is played from muscular block. I'm currently working on a new event that will trigger when an animation is being played for any ped, you can get the block and animation name from there easily.

**Comment by dretax** [comment]
Alright. I believe musclerun shouldn't trigger as long as you lack the skill.
Will test tomorrow.

**Comment by ghost** [comment]
Last time I tested it, it was getting triggered without any skill.

**Comment by dretax** [comment]
Nope. There is no point in replacing the run_armed animation as long as I cannot run with a weapon.
setPedStat(source, 23, 1000) on server side, does not allow running with a weapon as stated on forums, and It seems like as the guy on the forums said, he managed to run with ONLY in the CJ skin, but I can't do that either.

Server side:
setPedStat(source, 22, 1000)
setPedStat(source, 23, 1000)

The only real solution i see is replacing the swat run animation, i just dont know which one is the one...

**Comment by dretax** [comment]
Yup.
engineReplaceAnimation(getLocalPlayer(), "ped", "run_armed", "MuscularC", "musclerun_armed")
engineReplaceAnimation(getLocalPlayer(), "ped", "run_1armed", "MuscularC", "musclerun_armed")
engineReplaceAnimation(getLocalPlayer(), "ped", "walk_armed", "MuscularC", "musclerun_armed")


[muscular.zip](https://github.com/multitheftauto/mtasa-blue/files/2339530/muscular.zip)

I tried everything. The run animation with an armed weapon will never ever trigger unless you have 1000 skill on 23. I even tried replacing the walk animation but didn't work. All of the replace functions returned true.

**Comment by Addlibs** [comment]
Did you try
```Lua
engineReplaceAnimation(me, "muscular", "musclerun_armed", "MuscularC", "musclerun_armed")
```
It works perfectly fine for me, you just gotta replace the right animation block (`muscular`, not `ped`)
https://wiki.multitheftauto.com/wiki/Animation_Groups#player2armedm_.5Bmuscular.5D_.2862.29 (yeah, I know, this page is pretty hidden. [No page on the wiki links to it as of right now](https://wiki.multitheftauto.com/wiki/Special:WhatLinksHere/Animation_Groups))

I've tested this with a non-CJ skin using walking style 56 (this one correctly uses armed where appropriate) and using 62 (always armed even without correct weapon), and with a CJ skin using the same walking styles as well as using stat 23 set to 1000. All of them correctly trigger the custom replaced animation rather than the original.

**Comment by dretax** [comment]
Are you sure that is what I am looking for? That enabled sprinting?
[ped.zip](https://github.com/multitheftauto/mtasa-blue/files/2341344/ped.zip)

Whats the situation with this animation then?
Replace musclerun_armed with run_armed?

**Comment by dretax** [comment]
Just changed my walkstyle from 128, having 1000 skill, and used the code that you provided.
Pressing space, and still not sprinting. Doesn't work.

**Comment by ghost** [comment]
> Pressing space, and still not sprinting. Doesn't work.

There isn't just one sprinting animation, there are many. Show your full code.

**Comment by dretax** [comment]
It would be hard to do that, esspecially for a private mod.
Basically there is a custom inventory system. Upon weapon give, player gets stats to 1000 of 23, and I change the setPedWalkStyle to the suggested animation.

Upon client side resourcestart I use the exact given method to replace the muscle animation. The method returns true.  I even tried the default walkstyle, and then select a weapon which gives me 1000 skill, CJ became da muscleman, but I still cannot sprint with a weapon. Ofc if i change the walkstyle i can, but not with the required animation.

**Comment by ghost** [comment]
Different walkstyles will play different animations. I think your problem is that you don't know which animation to replace. Some weapons have their own animations for running, walking, etc., like minigun.

**Comment by dretax** [comment]
No. The problem is that I cannot get the character to sprint as i have said numerous times =)
Same deal goes on other people on the forum link which i have already provided.

**Comment by ghost** [comment]
Which weapon exactly are you holding while sprinting? Is it M4? I'll check which animation it plays

**Comment by dretax** [comment]
M4. I am trying to use the default walkstyle, and 128. But i still highly doubt this will help. The animation wont be played unless it allows me to run.

**Comment by ghost** [comment]
The animations are `WALK_start` and `WALK_civi`. They are played when you set the walkstyle to 128. `WALK_start` is played at first and it ends quickly, then `WALK_civi` is played in a loop. Also, this animation gets triggered for every ped skin, so it's not restricted to CJ.

Also, your ifp file (from ped.zip) does not even contain `musclerun_armed` animation. How do you expect engineReplaceAnimation to work?

This is what you need to do:
```
engineReplaceAnimation (localPlayer, "ped", "WALK_civi", "CustomIFPName", "AnimationNameInsideTheIFPFile")
```

**Comment by dretax** [comment]
...

Please see the comments above that it was a test to replace an animation using an exported muscle animation file.

What I am saying is. Sprint animation cannot be accesed, and will never play ever. It does NOT matter if i replace any running animation with anything. Running WILL NOT BE TRIGGERED. Replacing isn't the option here, I think you are lost in the comments. My intention is NOT TO REPLACE an armed walk style.
My intention is to USE the running animation of armed.
Running style WONT WORK unless you have setPedStat(23, 1000).
BUT you CANNOT have stat 1000 on a non-cj skin. As someone else is stating the same thing here: https://forum.mtasa.com/topic/110961-custom-animations-question/?do=findComment&comment=926472
It just doesn't work.
If I had the stat of 1000 then my character would be able to run using space, otherwise the animation will never be triggered. Replacing won't help, since my intention again, IS NOT TO replace the walk armed animation.

**Comment by ghost** [comment]
Closing this. We'll talk on forum.
