### ISSUE TITLE
Add the possibility that the camera (weapon) does not create screenshots in a folder

### ISSUE THREAD

**Issue by T-MaxWiese-T** [multitheftauto/mtasa-blue#3542]
### Is your feature request related to a problem? Please describe.

Currently, screenshots are always created in a GTA: San Andreas folder when you take a photo with the camera (weapon). However, the problem is that if you have a game mode where many photos have to be taken, the folder becomes cluttered and the player may not even know about it.

### Describe the solution you'd like

There should be a function with which you can activate or deactivate the screenshot function for the camera (weapon). For example, it could be called `setCameraScreenshot` and there could also be a `getCameraScreenshot` function.
And it would be nice if a player could also activate or deactivate screenshots for the camera (weapon) in the MTA settings.

### Describe alternatives you've considered

None

### Additional context

None

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
It would be nice to have an MTA setting for this (enabled by default). I don't see the need for scripting functions. Servers shouldn't be able to override the player's setting imo. If they don't want to clutter their disk, it's their final choice.

**Comment by T-MaxWiese-T** [comment]
> It would be nice to have an MTA setting for this (enabled by default). I don't see the need for scripting functions. Servers shouldn't be able to override the player's setting imo. If they don't want to clutter their disk, it's their final choice.

This wouldn't really solve the problem that the GTA: San Andreas screenshots folder might be flooded with unnecessary screenshots and some players don't know about it.
How many players know that when they take a photo with the camera (weapon) it is created in a GTA: San Andreas screenshots folder and where this folder is, for example to view the screenshots or delete unnecessary ones?
I have suggested a setting in the MTA settings to enable or disable it and it would also be desirable. But how many players would know and configure this setting and activate and deactivate it at the right moments?
If this function could be changed by the server during runtime, which I assume is the case, the server could deactivate it for gameplay elements, for example, and activate it otherwise. The player also always has the option of taking screenshots with the "F12" key or other options, for which the camera is not necessarily required.
What would also be desirable is that the information that a screenshot has been taken would be more visible, not just in the console where many players probably don't look.
And yes, this can be solved with a custom solution, but it's about a general solution to the problem.

**Comment by RedGuard17** [comment]
I remember that disabling the option from Single Player's settings (settings > display > store gallery photos > off) was working for MTA servers too but it seems like it doesn't anymore. I tested it in some servers and even tho the option is disabled the photos from the camera keep getting saved. Maybe it's MTA's bug with version 1.6?

**Comment by T-MaxWiese-T** [comment]
> I remember that disabling the option from Single Player's settings (settings > display > store gallery photos > off) was working for MTA servers too but it seems like it doesn't anymore. I tested it in some servers and even tho the option is disabled the photos from the camera keep getting saved. Maybe it's MTA's bug with version 1.6?

I think this is due to this change: https://github.com/multitheftauto/mtasa-blue/pull/2765 .
