### ISSUE TITLE
Support "older" bcrypt hashes

### ISSUE THREAD

**Issue by dretax** [multitheftauto/mtasa-blue#356]
**Is your feature request related to a problem? Please describe.**
Add support for older bcrypt hashes. https://wiki.multitheftauto.com/wiki/PasswordHash

**Describe the solution you'd like**
I really do not know what is the problem with the 2a hashes, and It would be great to implement It.
Xenforo uses those type of hashes, and I wouldn't have to use an external module.

**Describe alternatives you've considered**
https://github.com/mabako/mta_bcrypt

**Comment by qaisjp** [comment]
Is there a reason why the external module does not work for you?

**Comment by dretax** [comment]
Not really, but I thought why isn't a simple thing isn't supported in the platform It self. If the github has gone missing or the module comes unable to work, it would be great to have it. Thanks.
