### ISSUE TITLE
my PC's Serial was duplicated, causing me to receive bans on MTA servers

### ISSUE THREAD

**Issue by Angeloshx** [multitheftauto/mtasa-blue#3561]
### Describe the bug

the Serial on my PC was duplicated, causing me to receive bans on MTA servers. But my computer was recently purchased, but the Serial or Ip has already been used.

### Steps to reproduce

the Serial on my PC was duplicated, causing me to receive bans on MTA servers. But my computer was recently purchased, but the Serial or Ip has already been used.

### Additional context

the Serial on my PC was duplicated, causing me to receive bans on MTA servers. But my computer was recently purchased, but the Serial or Ip has already been used.

### Relevant log output

```shell
the Serial on my PC was duplicated, causing me to receive bans on MTA servers. But my computer was recently purchased, but the Serial or Ip has already been used.
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Fernando-A-Rocha** [comment]
@Angeloshx You should send your MTA serial via private discord message to the @MTA Staff Bot. This is not the place to get help from the anti cheat team.
