### ISSUE TITLE
engineImageLinkDFF not working with some mods

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3563]
### Describe the bug

Game will instantly freeze if you spawn a modded vehicle. Default replacement works.

### Steps to reproduce

Start this resource and spawn 411
[vehtest.zip](https://github.com/user-attachments/files/16198163/vehtest.zip)

### Version

Multi Theft Auto v1.6-release-22596

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
If i import into default gta3.img it works fine in base game @TheNormalnij 
https://streamable.com/h2mf1r

**Comment by TheNormalnij** [comment]
`engineStreamingSetBufferSize` changed function return from blocks to bytes. That breaks resize after engineAddImage
