### ISSUE TITLE
dxDrawMaterialLine3D causing graphical bugs

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#357]
**Describe the bug**
3d lines drawing incorrectly

**To Reproduce**
Just draw 2 material lines 3d and one will cover other one

**Expected behavior**
Draw properly

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/44949435-78e98300-ae31-11e8-9985-7c79fa9dddd1.png)
Both are in same place but rotated by 90 degree

**MTA Client (please complete the following information):**
Newstest mta and windows 10

**MTA Server (please complete the following information):**
not applicable

**Additional context**
Add any other context about the problem here

**Comment by forkerer** [comment]
Material lines don't draw onto depth buffer, so it can't handle mixed z-ordering well, dunno what would be good choice of handling it, making copy of depth buffer before batching 3d lines, and drawing onto that copy with z buffering enabled?

**Comment by ccw808** [comment]
Using a shader with `ZWriteEnable = TRUE;` might fix it
