### ISSUE TITLE
Migration to GitHub Issues

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#358]
This is for tracking progress of our move to GitHub Issues.

Here's a copy of the task list from the developer chat:

- [x] Enable issue tracker on GitHub and provide issue templates
- [x] Update 'submit issue' instructions to refer to GitHub
- [x] Make mantis read-only
- [ ] Go through all non-resolved mantis issues and close irrelevant/obsolete/unrealistic ones
    - I believe @patrikjuvonen has already gone over a lot of this stuff
- [ ] Finalise labels
- [ ] Manually or automatically (depending on the overall amount of remaining issues) migrate relevant issues

**Comment by ArranTuna** [comment]
I guess I should help with that.

**Comment by ArranTuna** [comment]
I have begun work on this and will do a bit each day, will be done in 1 to 2 months.

**Comment by patrikjuvonen** [comment]
I am assigning specific issues to specific people who know about them the most or have dealt with them lately. They can reassign if they do not want to work on the issue. I also recommend self-assigning issues if there is anything you can do. We can easily end up with thousands of issues from Mantis to GitHub and nobody is taking responsibility.

I have also started to look at Mantis issues and been testing and closing them as I go.

**Comment by qaisjp** [comment]
Thanks for helping out with this @ArranTuna 🙂

I've gone through the issues you've submitted (so many!) and updated them. It would be fantastic if you could use the issue template — it does take a little bit more time, but we should hopefully have it all done soon, esp. because we should have some more hands on deck for this!

All help is appreciated!

**Comment by qaisjp** [comment]
Also, the current plan is to ignore all the issues in the "Feature Request" project. (Don't migrate)

**Comment by ArranTuna** [comment]
Ok will use issue template.

So I don't need to migrate any in the "New Feature Requests" project?

**Comment by qaisjp** [comment]
Thanks ❤️. No need to migrate any in the new feature requests project (unless you want a feature that's in there)

**Comment by qaisjp** [comment]
Oh also, if an issue is confirmed please add the issue to the "Backlog" milestone! cheers

**Comment by qaisjp** [comment]
I made this chrome extension to make migration easier: https://github.com/qaisjp/mantismigrate

**Comment by qaisjp** [comment]
Extension has been updated to automatically include a link back to the old mantis issue in the github issue

**Comment by qaisjp** [comment]
Extensions has now also been updated to make interface side-by-side. Let me know if you prefer the old style and I can make it a setting.
