### ISSUE TITLE
Transparent Vehicles when turning lights ON

### ISSUE THREAD

**Issue by Trojkaaa** [multitheftauto/mtasa-blue#3588]
### Describe the bug

Car turn transparent when turning the lights of the vehicle it appears to any vehicle possible in the game even the custom ones.

![mta-screen_2024-07-20_01-57-13](https://github.com/user-attachments/assets/58759fc6-5274-4758-8f69-803ca91e6000)

With help of @Nico i got the game right and working again!
![mta-screen_2024-07-20_02-22-25](https://github.com/user-attachments/assets/54b5b078-9830-4518-80c1-2728b00bd2b4)

### Steps to reproduce

I dont really know how to reproduce it - It started with latest update 1.6 auto download when it finished and i started the game it just appear without reason. 

I did  not seen any report of this bug online thats why i did join MTA:SA official discord server and there i got help from MTA team member "Nico" - He did send me a diffrent version installer and it started working again after installing.

### Version

*Seen in the pictures*

### Additional context

-

### Relevant log output

```shell
-
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
The issue occurs after merging pull request #3581, after switching to the previous release (22624) the problem ceases to exist.
The issue can be temporarily fixed with installing the previous version from [here](https://nightly.multitheftauto.com/mtasa-1.6-rc-22624-20240719.exe) until the fix is ​​created.

**Comment by ghost** [comment]
@FileEX
