### ISSUE TITLE
Building LOD && no-collision bug

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3601]
### Describe the bug

1. When you replace a model and place as a building, and re-join into game it will have no collisions (https://streamable.com/l9vcje)
----> Only solves when you create building after model was replaced.

2. Building LOD's will not work as it should, doesn't matter what lod distance u set it will not load as default GTA LOD's from a distance.
----> https://streamable.com/n50vhp
----> how it should load:
![image](https://github.com/user-attachments/assets/11e516ff-f85e-4119-b69e-dcfcaca7be47)
----> how objects load:
![image](https://github.com/user-attachments/assets/0b81b345-ce96-45d2-94e4-190a6679af90)
----> createBuilding:
![image](https://github.com/user-attachments/assets/7fd8dc58-8928-47e7-a0d5-fc478749ed04)

### Steps to reproduce

createBuilding & custom model replace

### Version

Multi Theft Auto v1.6-release-22628

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by MrSol0** [comment]
obj = createBuilding(id,objData.x,objData.y,objData.z,objData.rx,objData.ry,objData.rz)

        lodObj = createObject(id,objData.x,objData.y,objData.z-0.001,objData.rx,objData.ry,objData.rz,true)

        setLowLODElement(obj,lodObj)

        engineSetModelLODDistance(id,400)

        setElementCollisionsEnabled(obj,true)

        setElementCollisionsEnabled(lodObj,true)`

Using this fixes some of these issues for me, but i also have that collision issue sometimes for some buildings, it's weird and i haven't figured out how or why, because i'm replacing COL the last thing after TXD & DFF
