### ISSUE TITLE
Impossible to disable shakeCamera

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3608]
### Describe the bug

shakeCamera will run infinite, doesn't matter what u do - respawn or die - it won't reset

https://streamable.com/uyknty

### Steps to reproduce

shakeCamera(100)

### Version

22634

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Proxy-99** [comment]
I think it should have time parameter which is not added @TracerDS 
or a way to destory the effect

**Comment by TracerDS** [comment]
#3585 

There is no time parameter.
`shakeCamera(5)` is already too big yet you call `shakeCamera(100)`

**Comment by FileEX** [comment]
Some maximum strength limit should be set to avoid such behavior. Camera shake processing is based on calculation
```cpp
m_fCamShakeForce - (CTimer::m_snTimeInMilliseconds - m_dwCamShakeStart) * 0.00028000001;
```

The greater the force, the longer it takes before the camera stops shaking

**Comment by Proxy-99** [comment]
> Some maximum strength limit should be set to avoid such behavior. Camera shake processing is based on calculation
> 
> ```c++
> m_fCamShakeForce - (CTimer::m_snTimeInMilliseconds - m_dwCamShakeStart) * 0.00028000001;
> ```
> 
> The greater the force, the longer it takes before the camera stops shaking

is it possible to stop or short the process of the function on that location x,y,z 
so something like resetShakeCamera (float x, float y, float z ] )

**Comment by TracerDS** [comment]
There is no unshakeCamera function in gta source code so I really doubt it

**Comment by Proxy-99** [comment]
> There is no unshakeCamera function in gta source code so I really doubt it

maybe the screen effect can be removed but still it will not be very good solution, will need to use setCameraShakeLevel(0)

**Comment by TracerDS** [comment]
> maybe the screen effect can be removed but still it will not be very good solution, will need to use setCameraShakeLevel(0)

You mean `setCameraDrunkLevel`?

**Comment by FileEX** [comment]
setCameraDrunkLevel and shakeCamera are completely different functions. We shouldn't mix them. Just set the maximum force limit into shakeCamera and the problem is solved. Probably using the shakeCamera with a very small force like 0.01 would also stop the camera from shaking

**Comment by TracerDS** [comment]
> setCameraDrunkLevel and shakeCamera are completely different functions. We shouldn't mix them. Just set the maximum force limit into shakeCamera and the problem is solved. Probably using the shakeCamera with a very small force like 0.01 would also stop the camera from shaking

one would overwrite the other, yes

**Comment by Proxy-99** [comment]
> setCameraDrunkLevel and shakeCamera are completely different functions. We shouldn't mix them. Just set the maximum force limit into shakeCamera and the problem is solved. Probably using the shakeCamera with a very small force like 0.01 would also stop the camera from shaking

yeah that make sense to limit it to a safe range

**Comment by AlexTMjugador** [comment]
Unless the game crashes or stops rendering correctly when the camera shake intensity is set to a very large value, like `math.huge` (infinity), I believe keeping the power value unlimited and documenting that the duration of the shake is determined by its strength is the best course of action. Script developers may find it useful to have a camera that keeps shaking until they choose to stop it, which is something they can achieve with a very large shake strength.

However, it is inconvenient for MTA scripting purposes that the default GTA camera shaking method ignores any new camera shake power values if `newPower <= std::clamp(currentPower, 0.0f, 2.0f)`. This explains why using `shakeCamera(0)` in the attached clip didn't work. In fact, any other reasonably small power value won't work either, so scripters currently have no precise control on when the effect stops. To fix this, I propose that the Lua function uses a reimplementation of the `CCamera::CamShake` method's logic without that strength check before updating the camera shake strength fields, allowing the scripting function to always override any current shaking strength.

Edit: an even better option to cater for everyone's use cases would be to make the behavior change outlined in the previous behavior toggleable, so script developers can choose to still repurpose the GTA camera shake coalescing logic to e.g. avoid shortening a long shake created by some nearby explosion, for example.

**Comment by FileEX** [comment]
Then we should add the ability to disable this effect by ```shakeCamera(false)``` and then manually disable camera shake by making appropriate changes to the memory

**Comment by AlexTMjugador** [comment]
> Then we should add the ability to disable this effect by `shakeCamera(false)` and then manually disable camera shake by making appropriate changes to the memory

I think it's more powerful to just make the function signature be like `bool shakeCamera(float power, [float x, float y, float z, bool alwaysOverride = false])`, where setting `alwaysOverride` to `true` skips that GTA check before modifying the camera shake strength attributes. It can be documented as allowing the camera shake strength to be modified no matter what shake strength is going on at the time. (Any ideas on how to better name that `alwaysOverride` parameter are welcome!)
