### ISSUE TITLE
3D wheel collider

### ISSUE THREAD

**Issue by CarlRayanitch** [multitheftauto/mtasa-blue#3615]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a limitation in MTA (Multi Theft Auto) where we don't have the vehicles.ide functionality. This limitation prevents vehicles' tires from acting like the monster truck, which has a 3D wheel collider. This impacts the realism and functionality of vehicle modifications within the game.

**Describe the solution you'd like**
I would like to add an option in the hedit tool that allows users to check or uncheck if a vehicle's wheels should behave like monster truck wheels. This would enable a 3D wheel collider for selected vehicles.

**Describe alternatives you've considered**
none

**Additional context**
The addition of this feature would significantly improve vehicle modding in MTA by providing more flexibility and realism. Currently, the lack of vehicles.ide functionality limits the extent to which vehicle physics can be customized. By integrating this option into hedit, modders would have greater control over vehicle behavior.

https://www.youtube.com/watch?v=LxKlHOgp5XE

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by lopezloo** [comment]
Duplicate of #3709
