### ISSUE TITLE
Walk control state is always true with id 125 walking style

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3618]
### Describe the bug

getPedControlState(localPlayer, "walk") is always true with ID 125 walking style

### Steps to reproduce

crun setPedWalkingStyle(localPlayer, 125)
crun getPedControlState(localPlayer, "walk")

### Version

Multi Theft Auto v1.6-release-22634

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by FileEX** [comment]
Cannot reproduce

![image](https://github.com/user-attachments/assets/6c08c599-370d-4a40-a871-2d60402f2c92)

**Comment by Xenius97** [comment]
Idk what was this, now seems like it works
