### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3622]
### Describe the bug

When opening MTA:SA, Windows immediately centers the cursor in the middle of the screen. As you attempt to join a server, Windows continuously repositions the cursor back to the center, making the computer nearly unusable until the game fully loads. This issue occurs while playing in windowed mode.

### Steps to reproduce

Open MTASA and join to a server in windowed mode

### Version

Multi Theft Auto v1.6-release-22650

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
https://github.com/user-attachments/assets/14bf4b66-0007-4a3f-b277-8ad1934c4d79

**Comment by FileEX** [comment]
I have always played in windowed mode and I can only confirm that this bug has been around for a long time and has nothing to do with #2855

**Comment by Xenius97** [comment]
I think https://github.com/multitheftauto/mtasa-blue/commit/c61cf4cf31bc2b66367202ff024b86583cf1e285 broke it, before this commit it was better.

**Comment by Xenius97** [comment]
The main problem is that when you connect to a server and minimize the window (the MTA window is not active), as soon as the game loads, it immediately centers the cursor, making the whole computer unusable until you somehow switch back to the window with ALT+Tab. @lopezloo

**Comment by lopezloo** [comment]
Please check if this issue exists before c61cf4cf31bc2b66367202ff024b86583cf1e285. If not, revert c61cf4cf31bc2b66367202ff024b86583cf1e285.

**Comment by lopezloo** [comment]
> When opening MTA:SA, Windows immediately centers the cursor in the middle of the screen.

No. (`Multi Theft Auto v1.6-release-22653`)

**Comment by lopezloo** [comment]
Unable to reproduce. Please create clear reproduction step instructions or full video with reproduction steps.
`Multi Theft Auto v1.6-release-22653`

**Comment by lopezloo** [comment]
> The main problem is that when you connect to a server and minimize the window (the MTA window is not active), as soon as the game loads, it immediately centers the cursor, making the whole computer unusable until you somehow switch back to the window with ALT+Tab. @lopezloo

It does in fact hide system cursor during connecting to the server and asset load even if game window is not active (`Multi Theft Auto v1.6-release-22653`). No idea if it's new issue. Needs to be tested.

**Comment by Xenius97** [comment]
> Unable to reproduce. Please create clear reproduction step instructions or full video with reproduction steps. `Multi Theft Auto v1.6-release-22653`

https://streamable.com/3cxp2z
https://streamable.com/w5sx5v

As you see, if MTA window is not focused it moves cursor to centre of screen. Sometimes it fully stucks there, cant move it until switching back via ALT + Tab

**Comment by lopezloo** [comment]
Yeah, it's new issue. Doesn't happen on `Multi Theft Auto v1.6-release-22639`, before c61cf4cf31bc2b66367202ff024b86583cf1e285.

**Comment by Xenius97** [comment]
I've tested 22634 just now and works fine for me too
