### ISSUE TITLE
mtasa:// protocol not working

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3629]
### Describe the bug

MTA SA protocol is broken when you try to connect while MTA is already started.

```
connection: Connecting to 127.0.0.1:22003...
connection: Unable to connect to mtasa://127.0.0.1:22003/:22003!
connection: Connecting to 127.0.0.1:22003...
connection: Unable to connect to mtasa://127.0.0.1:22003/:22003!
connection: Connecting to 127.0.0.1:22003...
connection: Unable to connect to mtasa://127.0.0.1:22003/:22003!
connection: Connecting to 127.0.0.1:22003...
connection: Unable to connect to mtasa://127.0.0.1:22003/:22003!
```

### Steps to reproduce

Start the game
Open in browser via your IP: mtasa://127.0.0.1:22003

### Version

Multi Theft Auto v1.6-release-22650

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
22634 works fine, maybe https://github.com/multitheftauto/mtasa-blue/commit/98837049b0f7ede95b0e1c7e78382444c2c64944 ?

**Comment by botder** [comment]
Issue introduced in b2cf02943924c4972d2a695cdbfd7c9873fc3cbb
