### ISSUE TITLE
ASE port leaking people ip addresses

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#3639]
### Describe the bug

Because of how ase server is implemented, bad actor can create server that log what ip addresses connected to server through ase port. It working automatically, user don't even have chance to prevent it. I can name my server with name simillar to popular servers so i have high chance that ip addresses of people from that server will be logged.

### Steps to reproduce

1. open server browser

### Version

*

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
And what are you going to do with random IPs? You get the same when you host a web server.

**Comment by CrosRoad95** [comment]
ddos players playing on competitive server.

> You get the same when you host a web server.

Yes, but i have to type "mtasa.com" and press enter. Imagine googling "mtasa" in google, and suddenly mtasa.com website know my ip. Thats the difference

**Comment by botder** [comment]
But you don't know if that random IP is actually a player on a server, and it would be insane if you were to blast random IPs with (many) DDoS attacks. Also, in many cases you're not going to accomplish anything if you try to DDoS dynamic ISP ip addresses.

**Comment by Dutchman101** [comment]
Every time a client opens server browser, their current IP (most countries use dynamic ones, as botder indicated) gets transmitted in an ASE query packet to servers that are queried, this includes servers down the list that aren't yet actively rendered to the user.

By network design and the way querying server list data works, this is neccesary and totally expected, and you can find a ton of similar scenario's everywhere on the internet, including the 1000's of APIs and privately owned services your IP queries when you load any given page. There is no point in expecting secrecy on the web, where you rely on 3rd parties to reveal their services and for you to make use of them. People that want secrecy on the internet can use a good VPN. This is really a non-issue or perhaps light trolling.
