### ISSUE TITLE
Enabling <oop> in resources breaks module functions

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#364]
**Describe the bug**

@botder says:

> The usage of OOP in resources breaks the functionality of modules (in this case 'sockets'). The module uses a static way to trigger events on the server, but the root element is being sent as 'userdata' instead of using the element. This behaviour breaks the event-trigger and shows a warning:
>
> `Bad argument @ 'triggerEvent' [Expected element at argument 2]`

**To Reproduce**
1. Use <oop>true</oop> in a resource, which uses the socket module functions
2. Notice WARNINGs in script debug
3. Event's do not get called at all

**Expected behavior**
OOP should not affect modules.

**Additional context**
From https://bugs.mtasa.com/view.php?id=9137

**Comment by qaisjp** [comment]
@4O4 wanted to fix this for the sockets module. Is this a general problem with sockets or a problem with the module system? #680 will probably close this, though.

**Comment by sbx320** [comment]
This is due to OOP using full userdatas rather than light userdatas for elements. This needs to be fixed in the individual modules, rather than in MTA itself. Modules need to push elements using `lua_pushelement`, rather than `lua_pushlightuserdata`.
