### ISSUE TITLE
Some client settings are no longer saved if set from console

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3648]
### Describe the bug

When you modify client settings in F8, it will reset after MTA restarted.

In the past it was saved.

https://github.com/multitheftauto/mtasa-blue/blob/bca4dff8dc490328000d7653a9166704d859b7e5/Client/core/CClientVariables.cpp#L230

### Steps to reproduce

F8->
mtavolume=0.25

### Version

Multi Theft Auto v1.6-release-22676

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
++
"mastervolume" wont change until pressing ESC (or works total random idk)

**Comment by FileEX** [comment]
Cannot reproduce

**Comment by Xenius97** [comment]
> Cannot reproduce

Yep, idk what was the issue
