### ISSUE TITLE
Add unloadMapData

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3649]
### Is your feature request related to a problem? Please describe.

as you uses [loadMapData](https://wiki.multitheftauto.com/wiki/loadMapData)
you need a way unload them 

### Describe the solution you'd like

Add unloadMapData 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Xenius97** [comment]
> as you uses [loadMapData](https://wiki.multitheftauto.com/wiki/loadMapData)

```
Returns an element object that corresponds to the root of the new data added, i.e. an element that represents the node xmlnode passed to the function. Returns false if the arguments are invalid.
```

You can use `destroyElement` i think.

**Comment by Proxy-99** [comment]
> > as you uses [loadMapData](https://wiki.multitheftauto.com/wiki/loadMapData)
> 
> ```
> Returns an element object that corresponds to the root of the new data added, i.e. an element that represents the node xmlnode passed to the function. Returns false if the arguments are invalid.
> ```
> 
> You can use `destroyElement` i think.

well this works
maybe we should add a note and example for this in the wikipage that was not more info in this
