### ISSUE TITLE
Add a new function resetAllWorldPropertis

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3650]
### Is your feature request related to a problem? Please describe.

a function to reset all world resetAllWorldPropertis values
doing something like will take so much time to list all possible functions

```lua
setWaterLevel(0) resetSkyGradient() resetWaterColor()resetWaterLevel()setWaveHeight(0)resetHeatHaze()
	resetWindVelocity()resetAmbientSounds()resetWorldSounds()resetRainLevel()resetSunSize()resetSunColor()
	resetFogDistance()resetFarClipDistance()setGravity(0.008)setGameSpeed(1)setWeather(0)
``` 

### Describe the solution you'd like

add new function client-function or make it possible to target a single resource not all

### Describe alternatives you've considered

make argment for resetMapInfo() to select which resource element to reset map info ?

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by TheNormalnij** [comment]
Does it work like resetMapInfo but client side?

**Comment by Proxy-99** [comment]
> resetMapInfo

well resetMapInfo works differetnly **"restore a player to his default state as if he had just joined the server, without any scripts affecting him**" so all scripts resources will be not working which affecting everything, you can not select a specific resource target

**Comment by Fernando-A-Rocha** [comment]
> ```lua
> setWaterLevel(0) resetSkyGradient() resetWaterColor()resetWaterLevel()setWaveHeight(0)resetHeatHaze()
> 	resetWindVelocity()resetAmbientSounds()resetWorldSounds()resetRainLevel()resetSunSize()resetSunColor()
> 	resetFogDistance()resetFarClipDistance()setGravity(0.008)setGameSpeed(1)setWeather(0)
> ```

This is, in fact, a lot of functions!! 😯
