### ISSUE TITLE
Mta Sa Cheat Mod Issue

### ISSUE THREAD

**Issue by OmiduAnjane** [multitheftauto/mtasa-blue#3652]
### Describe the bug

Can you give a solution to this? Otherwise mta sa death will happen. This is the biggest problem right now. Please solve it as soon as possible.

### Steps to reproduce

Can you give a solution to this? Otherwise mta sa death will happen. This is the biggest problem right now. Please solve it as soon as possible.

### Version

All Verson

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Proxy-99** [comment]
but how the death happens

**Comment by TracerDS** [comment]
What is the actual issue

**Comment by Rilot06** [comment]
Learn to secure your scripts and stop crying

**Comment by Lpsd** [comment]
Didn't you see the big text before submitting this issue?

# Stop right now if you're reporting a cheat or security vulnerability!
**Please read our [Security Policy](https://github.com/multitheftauto/mtasa-blue/security/policy) to learn where to responsibly report security issues. Thank you.**
