### ISSUE TITLE
setPedFootBloodEnabled doesn't work

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3654]
### Describe the bug

``setPedFootBloodEnabled`` doesn't work.

Even after setting it to false, we still leave bloody footprints when we walk over a dead ped

### Steps to reproduce

1.
```lua
crun setPedFootBloodEnabled(me,false)
```
2. Kill some ped and walk over him

### Version

1.6.0

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by MegadreamsBE** [comment]
What happens if you call it immediately after? If I look at explanation on the wiki, it seems to just toggle bloody feet on at will, not whether the behavior you described will happen or not.

**Comment by bum8hj** [comment]
> What happens if you call it immediately after?

Calling `setPedFootBloodEnabled(localPlayer, false)` immediately after walking on a dead body stops the localPlayer from creating bloody footsteps.

> If I look at explanation on the wiki, it seems to just toggle bloody feet on at will, not whether the behavior you described will happen or not.

That's what I understood as well. Walking on a dead ped will always (by default) cause bloody feet. The function `setPedFootBloodEnabled` is there to force the bloody feet effect.

However, I noticed an issue while testing this.
When you `setPedFootBloodEnabled` to `true`, it works as expected (creates bloody footsteps that go on forever). However, after stepping on a dead body, the bloody footsteps turn off after 6 steps.

So, someone who wants this effect turned on/off at all times would probably need to call it on render or a recurring timer. Edit: or using the ped step event

### A solution
A possible solution would be to add a 3rd parameter `bool - always` which when set to true ensures that the state is respected even after stepping on a dead body.

**Comment by Proxy-99** [comment]
> > What happens if you call it immediately after?
> 
> Calling `setPedFootBloodEnabled(localPlayer, false)` immediately after walking on a dead body stops the localPlayer from creating bloody footsteps.
> 
> > If I look at explanation on the wiki, it seems to just toggle bloody feet on at will, not whether the behavior you described will happen or not.
> 
> That's what I understood as well. Walking on a dead ped will always (by default) cause bloody feet. The function `setPedFootBloodEnabled` is there to force the bloody feet effect.
> 
> However, I noticed an issue while testing this. When you `setPedFootBloodEnabled` to `true`, it works as expected (creates bloody footsteps that go on forever). However, after stepping on a dead body, the bloody footsteps turn off after 6 steps.
> 
> So, someone who wants this effect turned on/off at all times would probably need to call it on render or a recurring timer.
> 
> ### A solution
> A possible solution would be to add a 3rd parameter `bool - always` which when set to true ensures that the state is respected even after stepping on a dead body.

maybe the function trigger the effect should be attach to an event onPedDeadBodyStep or a way to cancel the effect when it trigger that function

**Comment by FileEX** [comment]
So it looks like the function works but in a slightly strange way
