### ISSUE TITLE
Can only run forward bug

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#366]
**Describe the bug**
Not being able to turn left, right or back. Is fixed by jumping.

**To Reproduce**
Unknown

https://bugs.mtasa.com/view.php?id=1309

**Comment by Sergeanur** [comment]
Normally it happens when something interrupts the task chain before it was finished, like calling setPedAnimation.
To reproduce you can create a marker that'll play some animation on hit, and then jump into the marker.

**Comment by qaisjp** [comment]
All we need now is a neat reproduction resource so we can integrate this into our test suite. Regression testing is important.

**Comment by Loki214** [comment]
Repro code
`/crun bindKey("e","both",function( _, state ) localPlayer.frozen = state == 'down' end)`

Then just press e when you are in the landing or stumble animation after a jump or falling.
https://gfycat.com/pertinentoldfashionedgalapagosmockingbird

**Comment by StifflersMom** [comment]
This bug exists as long as I know MTA ... And YES!!! I can reproduce this with our AFK resource, which uses also setElementFrozen to freeze players position while afk. If I do this at the moment when the player hit the ground, there are two possible behaviors:
- Can ony run / walk forward until jump once
- Falling animation keeps running even if you are on ground (may be this is another bug)

**Comment by WADmitry** [comment]
> * Can ony run / walk forward until jump once
> * Falling animation keeps running even if you are on ground (may be this is another bug)

Same here (boths quoted problems). The falling animation after interior+dimenson were changed is so annoying (and then you can't moving until jump)

**Comment by ghost** [comment]
@Loki214 @StifflersMom @WADmitry  Thanks for the code and info.

**Comment by Icensow** [comment]
This bug also occurs when using setPedAnimation while landing

**Comment by ghost** [comment]
It is possible that this still exists because the game thinks the ped still needs to land. Although, it won't happen via SetElementFrozen anymore. If anybody experiences this, then reply here, this time we'll check for the landing in a loop and fix it if it's bugged.

> 
> 
> This bug also occurs when using setPedAnimation while landing

How to reproduce it?

**Comment by Icensow** [comment]
> How to reproduce it?

```
addEventHandler ("onClientRender", root, function () 
    if isPedDoingTask (localPlayer, "TASK_SIMPLE_LAND") then 
        setPedAnimation (localPlayer, "VENDING","VEND_Drink2_P", 100, true, true, true, false) -- any anim
    end 
end)
```

**Comment by ghost** [comment]
@Icensow Thanks. Any other possible instances? or it just happens via SetElementFrozen and SetPedAnimation?
@WADmitry About the falling animation problem, if you can send me a code snippet to reproduce the issue, I can fix it. It's a separate issue, so I'll close this.

**Comment by Icensow** [comment]
@saml1er, just checked, same with setElementModel and warpPedIntoVehicle

**Comment by ghost** [comment]
> 
> 
> @saml1er, just checked, same with setElementModel and warpPedIntoVehicle

Fixed in 426ad3fcf71b4d41af877a860b371ad2f98f6d17

**Comment by bsa11b** [comment]
Please make video of this bug maybe i remember it.

**Comment by CrosRoad95** [comment]
Really, you didn't see this bug?
