### ISSUE TITLE
Game crashes when leaving a local server on windows

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3672]
### Describe the bug

When I set up a local server and do some things on it, if I leave it in any way (disconnect, quitting the game, kick or ban etc.) the game will exit in a crash. This happens on windows x86 x64 servers both. Tried server versions 22676, 22681, 22685.

(On an other server which runs 22676 on X64 Linux, there is no problem with leaving the game.)
[Crash](https://i.imgur.com/axXWwWo.png)
The crash reports were sent. 

### Steps to reproduce

1. Clean fresh install Client & Server from nightly.
2. Launch server
3. Launch client, connect to the local server
4. Disconnect or Quit or Kick/Ban

### Version

I tried with Client Versions 22676, 22680, 22684 and Server versions 22676, 22681, 22685

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by tederis** [comment]
I confirm. But I can't reproduce it on a custom build.

**Comment by Proxy-99** [comment]
same with me when I disconnect from my server it crash 
Multi Theft Auto v1.6-release-22684

**Comment by botder** [comment]
Caused by `CResourceModelStreamer::FullyReleaseModel`
