### ISSUE TITLE
Crashes caused by disconnecting / server stopping

### ISSUE THREAD

**Issue by chris1384** [multitheftauto/mtasa-blue#3689]
### Describe the bug

If you join a freshly started server, the clients joining it can occur a weird crashlog upon disconnecting from it by will or at server stop.
https://www.youtube.com/watch?v=0VkT_CcQ9g8

PS: No, it's not from `Ultrathing`, I tested with clean GTA:SA files and it still happens.
Server has the latest resources from https://github.com/multitheftauto/mtasa-resources.

### Steps to reproduce

1. Open MTA:SA client
2. Start a local server
3. Join it
4. Close the server using CTRL+C

### Version

client: Multi Theft Auto v1.6-release-22684
server: MTA:SA Server v1.6-release-22684

### Additional context

In some cases, CEGUI also bugs out causing overlapping texts. It's caused only at server start.
Example from Race:
![Screenshot_24](https://github.com/user-attachments/assets/eaf02218-e692-4a17-9dd8-1e906feda7a1)

### Relevant log output

```shell
** -- Unhandled exception -- **

Version = 1.6-release-22684.0.000
Time = Sun Sep  1 22:52:04 2024
Module = D:\Games\Rockstar Games\MTA San Andreas 1.6\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x000E19B2

EAX=00000000  EBX=0177FAF4  ECX=2AD79250  EDX=00000038  ESI=2AF71934
EDI=2A6E04A8  EBP=0177FA94  ESP=0177FA94  EIP=560A19B2  FLG=00210202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **


** -- Unhandled exception -- **

Version = 1.6-release-22684.0.000
Time = Sun Sep  1 22:52:38 2024
Module = D:\Games\Rockstar Games\MTA San Andreas 1.6\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x000E19B2

EAX=00000000  EBX=0177FAF4  ECX=2B49E9E0  EDX=00000038  ESI=2B5CF34C
EDI=2AF630B0  EBP=0177FA94  ESP=0177FA94  EIP=560A19B2  FLG=00210202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **


** -- Unhandled exception -- **

Version = 1.6-release-22684.0.000
Time = Sun Sep  1 22:57:41 2024
Module = D:\Games\Rockstar Games\MTA San Andreas 1.6\mods\deathmatch\client.dll
Code = 0xC0000005
Offset = 0x000E19B2

EAX=00000000  EBX=0177FAF4  ECX=2BD5E0E0  EDX=00000038  ESI=2C89C184
EDI=2B9641C8  EBP=0177FA94  ESP=0177FA94  EIP=561019B2  FLG=00210202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TheNormalnij** [comment]
fixed in #3675
