### ISSUE TITLE
Tow truck logic has been broken

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3691]
### Describe the bug

When we lower the tow truck arm down (NUM 5), it cannot be visually raised back up (NUM 8).

The vehicle is being towed, so logically the arm is raised, but visually the arm component remains lowered.

### Steps to reproduce

1. Spawn towtruck
2. Hold num 8 to lower the towtruck arm
3. Hold num 5 to try to raise up the towtruck arm

### Version

Multi Theft Auto v1.6-release-22650

### Additional context

![image](https://github.com/user-attachments/assets/612a797c-6199-4ac1-92de-6ca09239ff6f)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Fernando-A-Rocha** [comment]
?
