### ISSUE TITLE
SVG colors are wrong

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#3695]
### Describe the bug

I created a simple graphic in figma:
![image](https://github.com/user-attachments/assets/d26f1095-c29b-48c2-a476-0b8ee5314054)
I exported as SVG. Then copied the SVG code and used it in ``svgCreate``.

Result in SVG Viewer (https://www.svgviewer.dev)
![image](https://github.com/user-attachments/assets/d1ccd361-1d03-407f-a4a5-7fbc06a5ccc7)

Result in MTA:
![image](https://github.com/user-attachments/assets/d443bb32-9f32-4062-87b6-0d01d4dae0ba)

The colors are completely different and there is no shadow. The only way to solve this problem is to use ``dxCreateTexture`` instead of ``svgCreate``. Right now svg has a lot of problems and the longer we use it, the more it becomes unusable due to bugs.

### Steps to reproduce

```xml
<svg width="350" height="115" viewBox="0 0 350 115" fill="none" xmlns="http://www.w3.org/2000/svg"><g filter="url(#a)"><path fill="#30444D" fill-opacity=".6" d="M0 0h350v115H0z"/></g><defs><filter id="a" x="0" y="0" width="350" height="115" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feColorMatrix in="SourceAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/><feMorphology radius="5" in="SourceAlpha" result="effect1_innerShadow_1269_65"/><feOffset/><feGaussianBlur stdDeviation="5"/><feComposite in2="hardAlpha" operator="arithmetic" k2="-1" k3="1"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/><feBlend in2="shape" result="effect1_innerShadow_1269_65"/></filter></defs></svg>
```

### Version

Multi Theft Auto v1.6-release-22650

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Proxy-99** [comment]
I think there is an issue when rendering alpha or the colors idk I have same rendering  problem with createBrowser maybe this is related

**Comment by PlatinMTA** [comment]
Im not home to check this yet but couldnt this be related to `setColorFilter`?

**Comment by Lpsd** [comment]
You need to ensure that the features you’re using are supported by LunaSVG, otherwise yes it will appear different in MTA compared with the browser (note: filters)

**Comment by Lpsd** [comment]
Follow up; tools that try to export SVGs from a rasterised graphic aren’t going to be great in terms of efficiency or optimisation of the SVG output. For such a simple SVG, why not just write it yourself or use an actual SVG tool to create it from scratch?

SVG in MTA is for simple, scalable graphics. More advanced features that do eventually get supported in LunaSVG are a bonus.

**Comment by FileEX** [comment]
I see, that explains why there is no shadow and some effects. However, I still don't understand why the colors are different? Since in the svg file it is exactly the same color as set in the program (#30444D)

**Comment by Lpsd** [comment]
> However, I still don't understand why the colors are different

I don't see a fair comparison to determine this, considering the graphic has a transparency which is being measured against two different background colors in your examples.

**Comment by Xenius97** [comment]
I had same issue before, but changing blend mode fixed it.
```lua
dxSetBlendMode("modulate_add")
-- draw svg here
dxSetBlendMode("blend")
```
