### ISSUE TITLE
Something like getFetchRemoteStatus and cancelFetchRemote to client fetchRemote

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#370]
I am amazed by the all the new possibilities client-side fetchRemote has brought to MTA (even if it is restricted to the server you are connected to). It is astonishingly fast compared to triggerLatentClientEvent and saves lots of server-side CPU power. Imagine how fastly and efficiently huge custom maps like GTA III conversions could be downloaded if just all those server owners would finally upgrade their servers to use client-side fetchRemote...

But for all that fetchRemote is still missing useful functions that might come in handy when downloading big files. I would love to see a system similar to the one of latent event handlers: Being able to get the status/progress of HTTP GET (aka fetchRemote) requests and also being able to cancel those aswell.

https://bugs.mtasa.com/view.php?id=7629
https://bugs.mtasa.com/view.php?id=8040

**Comment by botder** [comment]
Pull request: #660
