### ISSUE TITLE
engineReplaceAnimation does not apply the replaced animation if it is currently used

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#371]
**Describe the bug**
By using engineReplaceAnimation it is possible to replace the "idle standing" animation. However, if this function is used to replace that animation, it will not get applied immediately. The player has to perform another action and the new animation gets applied afterwards.

**To Reproduce**
- replace the idle stand animation of your local player
- Notice that your animation does not change
- press any movement key: The animation gets applied as soon as the player model returns to "idle"

**Additional context**
I recommend modifying "engineReplaceAnimation" in such a way that it applies replaced animations to ped models if the replaced animation is currently in use - if that is possible.
I wrote a script that lets the player go into a prone position instead of crouch, but everytime the "prone" animation replaces the "crouching", the player has to stand up and re-crouch because the replaced animation will never be applied otherwise.

Now i COULD use "setPedAnimation" to play the "idle_prone" animation - however there is another MTA bug that removes the "crouch state" everytime an animation is being applied with setPedAnimation. So when the player presses "crouch", the "prone" animation plays and as soon as its finished he will stand up...

https://bugs.mtasa.com/view.php?id=9910

**Comment by Einheit-101** [comment]
Now since saml1er modified this it is possible to change the idle_stand animation without an issue, but the "weapon_crouch" animation still requires you to stand up and crouch again, otherwise it wont play.

**Comment by ghost** [comment]
@Einheit-101 I'm unable to reproduce this. Can you give me a test resource?

**Comment by Einheit-101** [comment]
Yes, here is a test resource.
It replaces the crouch idle animation with a prone animation when you type "/prone".
Typing it again resets the animation.
It shows the current state with a dx image at the radar.

When you are crouching, it doesnt work. You have to stand up and crouch again, otherwise the replaced animation wont play...

[bug.zip](https://github.com/multitheftauto/mtasa-blue/files/3096769/bug.zip)

**Comment by qaisjp** [comment]
(
> @Einheit-101 — thanks for the resource! I've converted your Dropbox link to a GitHub link so that we don't lose anything if you delete your account / Dropbox shuts down / the link expires in some other way.
>
> If you'd like to try this yourself another time, all you need to do is drag the zip into the comment box. Thanks again!

)

**Comment by Einheit-101** [comment]
Oh okay, but you can be sure that my dropbox will last pretty much forever lol

**Comment by ghost** [comment]
Thanks for the resource. It was helpful.

**Comment by Einheit-101** [comment]
Ooooohhhh boi, i will test the fix asap, that is going to get an amazing end result at one day, thanks.
Can you look at the bug that resets the crouching state of a player? Thats pretty much the last thing that prevents us from ultimate greatness. 

https://github.com/multitheftauto/mtasa-blue/issues/462

**Comment by ghost** [comment]
> 
> Can you look at the bug that resets the crouching state of a player? Thats pretty much the last thing that prevents us from ultimate greatness.
> 
> #462

Alright! I'lll check it out tomorrow.
