### ISSUE TITLE
Game crash when leaving local server on windows

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3710]
### Describe the bug

Launch a local server on windows, connect it, then disconnect by any method (ban/kick/disconnect ... etc)
The game will exit with a crash.

I previuosly reported this bug and the issue was closed. The problem still exists.

### Steps to reproduce

Get latest version from nightly.
Launch server x64 or x86
Launch client, connect to the localserver
Disconnect from it

### Version

Client & Server: 22714
Both x86 & x64 (Windows)

### Additional context

https://imgur.com/a/TJZZYiM

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by FileEX** [comment]
Previous report: #3672 - The offset is a little different

**Comment by tederis** [comment]
Can confirm. The crash is still here.

**Comment by Satooro** [comment]
Is happen here too but offset is different https://imgur.com/FKQE0Iv
EDIT: sorry, the offset is the same as the report #3672 i didn't see it

**Comment by ghost** [comment]
I noticed sometimes i get this offset: https://i.imgur.com/tuRQOGE.png

**Comment by PlatinMTA** [comment]
Offset seems to have been changed again (crashed after reloading some models)

``0x000E2142``
