### ISSUE TITLE
dxDrawModel3D issues

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3712]
### Describe the bug

dxDrawModel3D not working after object stream out, it won't draw anything cause model is unloaded.
https://youtu.be/T3vhhOxFIG4

### Steps to reproduce

```lua
addEventHandler("onClientRender", root, function()
	local interpolate = interpolateBetween(0, 0, 0, 360, 0, 0, getTickCount() / 2500, "SineCurve")
	local x, y, z = getElementPosition(localPlayer)
	dxDrawModel3D(1337, x, y, z, 0, 0, interpolate)

	local screenX, screenY = getScreenFromWorldPosition(x, y, z + 1)
	if screenX and screenY then
		dxDrawText("3D Model", screenX, screenY, screenX, screenY, tocolor(255, 255, 255), 1, "default-bold", "center", "center")
	end
end)
```

### Version

Multi Theft Auto v1.6-release-22721

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
@tederis @TheNormalnij

**Comment by Xenius97** [comment]
Seems like `engineStreamingRequestModel` solved it, but idk how should this properly work.

**Comment by tederis** [comment]
That's how it was intended to work. See wiki page: `Note that a model must be loaded at the time this function is called. A model can be loaded and unloaded with the help of engineStreamingRequestModel and engineStreamingReleaseModel functions.`
