### ISSUE TITLE
Add option to lunch the local server automatically on game lunch

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3721]
### Is your feature request related to a problem? Please describe.

Make it way easier to get started to code and setup server, each time I have to lunch the game then the server 

### Describe the solution you'd like

Add option to game settings to automatically  start the server program while lunch the game program

### Describe alternatives you've considered

Could be even extended to join any global server automatically while finishing lunching the game

### Additional context

could be a game setting or a server setting to allowe this

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
Joining a server when finishing launching the game is already possible with mtasa:// protocol 

As for launching the server automatically... I don't think developers need that, just launch the server exe, set up your own permissions etc ...

**Comment by Proxy-99** [comment]
> Joining a server when finishing launching the game is already possible with mtasa:// protocol
> 
> As for launching the server automatically... I don't think developers need that, just launch the server exe, set up your own permissions etc ...

I do not see why I have to press and lunch the server program every time while it can be automatically started in game lunch as I code a lot in my local server that just makes it painful to devs

**Comment by bum8hj** [comment]
Create a batch script or something. Launch both the game and server at once.

**Comment by Proxy-99** [comment]
> Create a batch script or something. Launch both the game and server at once.

I know I can do work arounds but I still want it to be part of the game program to include this feature xd

**Comment by TracerDS** [comment]
Whats the point?

**Comment by botder** [comment]
Just launch the MTA Server when you start your computer, this should save you more time than us adding such a feature.

**Comment by Proxy-99** [comment]
> Just launch the MTA Server when you start your computer, this should save you more time than us adding such a feature.

I think I will just code a bat file instead to run both programs
