### ISSUE TITLE
Maperi MTa

### ISSUE THREAD

**Issue by sobhantr** [multitheftauto/mtasa-blue#3727]
### Describe the bug

Hi, I wanted an MTA mapper, but I can't find it in the mapper section

### Steps to reproduce

Map photo

### Version

1.6

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
This is not a place for that

**Comment by Dutchman101** [comment]
This (the issue tracker/repository) is not the place for asking support, or mappers.

The community is your only option for that.
Places of the community:
- MTA discord (https://discord.gg/RygaCSD) > [#advertisements](https://discord.com/channels/278474088903606273/1024325234121244712) channel, or affinity channel [#mapping](https://canary.discord.com/channels/278474088903606273/592475992149196841)

- MTA Forums > ["Looking for staff"](https://forum.multitheftauto.com/forum/149-looking-for-staff/) board or affinity board ["Mapping"](https://forum.multitheftauto.com/forum/72-maps/)

If there are no offerings that suit you, then that's unfortunate. But please don't post here in GitHub again, thanks for understanding @sobhantr

**Comment by sobhantr** [comment]
Excuse me, so where should I find it?

**Comment by Dutchman101** [comment]
> Excuse me, so where should I find it?

Please refer to my reply above yours.
@sobhantr
