### ISSUE TITLE
pathListDir doesn't work when used on resource's main directory

### ISSUE THREAD

**Issue by neku172** [multitheftauto/mtasa-blue#3729]
### Describe the bug

Pretty much as in title, pathListDir should return all files inside a resource folder but instead it throws a warning

### Steps to reproduce

1. Run `srun pathListDir(':admin')` - result:  Cannot parse provided path: ":admin"
2. Run `srun pathListDir(':admin/server')` - everything works

### Version

Server version: MTA:SA Server v1.6-release-22731

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
`:resourceName` is not a valid path for the `pathListDir`.
`pathListDir` requires a valid unix-like path. It will be limited to the current resource's directory.

**Comment by neku172** [comment]
then why running `srun pathListDir(':admin/server')` works

**Comment by TracerDS** [comment]
> then why running `srun pathListDir(':admin/server')` works

Probably a bug

**Comment by neku172** [comment]
even [this wiki page](https://wiki.multitheftauto.com/wiki/GetFilesInResourceFolder) suggests that it should be possible to list other resources' directories with pathListDir

**Comment by TracerDS** [comment]
> even [this wiki page](https://wiki.multitheftauto.com/wiki/GetFilesInResourceFolder) suggests that it should be possible to list other resources' directories with pathListDir

Not really. That useful function was just a temporary replacement for `pathListDir`.

**Comment by TracerDS** [comment]
When you type just `:resourceName`, MTA interprets it as `resources/ResourceName/:resourceName`
To actually list the path of other resource, use `:resourceName/.`
