### ISSUE TITLE
Add option to treat warnings as errors

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#3737]
### Is your feature request related to a problem? Please describe.

Steal i mean, borrow concept of treating warnings as errors. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings

### Describe the solution you'd like

Assign id to every warning, add option to treat them as errors, for example:
`setElementPosition(false, 0, 0, 0)` - `WARNING: [1] server.lua:1: Bad argument @ 'setElementPosition' [Expected element at argument 1, got boolean]` where "[1]" is id of warning.
But in practice this should be an error. so, you go to mtaserver.conf, find and add warning: <warningsAsErrors>1</warningsAsErrors>, next time code will stop execution and you will see error instead of continuing execution

This is 101% backwards compatible

### Describe alternatives you've considered

/

### Additional context

/

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by TracerDS** [comment]
Appendum: Make a way to catch warnings too

**Comment by CrosRoad95** [comment]
Warnings are just warnings, like you put "0" instead of 0, mta converted it but you should use numeric zero, not string, or like example i gave before: setting position of something what is not element should be error, but isn't, there is many such cases, we can not change it because even if your code is broken, we can not break your broken code.

Again, this warning above can cause server/client to fall into invalid state, let's say after you set position you print log to admin, but this log doesn't depend on this element - "platform was moved", now you get log, but imaginary platform didn't move. You can see in logs both but if you have tons of logs you may get lost

**Comment by TracerDS** [comment]
I mean, if a warning is thrown then most of the time the function returns false so you can check against that.

**Comment by CrosRoad95** [comment]
> you can check against that.

Yes, you can, but making code in shape of pyramid of doom is not good

**Comment by TracerDS** [comment]
```lua
if (!setElementPosition(...)) then
    error("Invalid args")
end
```
?
In some cases, it is unavoidable. This is the way if you want to have errors when warning is thrown

**Comment by CrosRoad95** [comment]
> ```lua
> if (!setElementPosition(...)) then
>     error("Invalid args")
> end
> ```
> 
> ? In some cases, it is unavoidable. This is the way if you want to have errors when warning is thrown

Yes, and you double your codebase, i probably prefer to just fork mta and replace all warnings with errors instead of dealing with that shit

**Comment by qaisjp** [comment]
i see no problem with this proposal

**Comment by Fernando-A-Rocha** [comment]
> Appendum: Make a way to catch warnings too

This. This would be useful, as I think the intention here by turning warnings into errors is to be able to catch them and treat them in the code

**Comment by CrosRoad95** [comment]
> > Appendum: Make a way to catch warnings too
> 
> This. This would be useful, as I think the intention here by turning warnings into errors is to be able to catch them and treat them in the code

it is not only that reason,
you often have code like:

```lua
function moveElement(element)
  setElementPosition(element, ...) -- warning, expected element got nil
  setElementRotation(element, ...) -- warning, expected element got nil
  setElementDimension(element, ...) -- warning, expected element got nil
  outputChatBox("element moved") -- prints element moved, but it doesn't
end
```

last outputChatBox can be any output, for example output to server logs what can over time pollute your logs with many false logs + extra 3 warnings for no reason, because if element position can not be changed, then for sure it can't be rotated next line.
Also, search for any setTimer, trigger, fetchRemote, in every such case you should check if arguments are valid, often people don't do this and you endup with problem i described before.

**Comment by TracerDS** [comment]
> > > Appendum: Make a way to catch warnings too
> > 
> > 
> > This. This would be useful, as I think the intention here by turning warnings into errors is to be able to catch them and treat them in the code
> 
> it is not only that reason, you often have code like:
> 
> ```lua
> function moveElement(element)
>   setElementPosition(element, ...) -- warning, expected element got nil
>   setElementRotation(element, ...) -- warning, expected element got nil
>   setElementDimension(element, ...) -- warning, expected element got nil
>   outputChatBox("element moved") -- prints element moved, but it doesn't
> end
> ```
> 
> last outputChatBox can be any output, for example output to server logs what can over time pollute your logs with many false logs + extra 3 warnings for no reason, because if element position can not be changed, then for sure it can't be rotated next line. Also, search for any setTimer, trigger, fetchRemote, in every such case you should check if arguments are valid, often people don't do this and you endup with problem i described before.

Skill issue. If you dont check for stuff, shit happens. Most of the time these kidn of issues can be easily solved without throwing errors.

**Comment by CrosRoad95** [comment]
If you have large code base then have a fun catching all such cases

**Comment by TracerDS** [comment]
Thats not a problem. Just script properly. 
Sometimes though it is really out of your control if the function fails or not but you still can catch that (while also flooding the debugscript (e.g. when something didnt load client side))

**Comment by TheNormalnij** [comment]
I agree with @CrosRoad95. Fail fast concept is preferable in most cases

**Comment by CrosRoad95** [comment]
> I agree with @CrosRoad95. Fail fast concept is preferable in most cases

this is skill issue

**Comment by CrosRoad95** [comment]
Just wonder how many bugs on servers could be prevented if script fail faster rather than trying to execute broken code.
Lucky me, i use c# and this problem is not my problem :) i have ~1000 line of code lua code, rest 2000 files are c#.

![image](https://github.com/user-attachments/assets/b96f80fe-b72a-42ed-a56a-f4df0e40c7a3)

skill issue in mta itself, feature that let you read random memory from lua
