### ISSUE TITLE
createBuilding optional arguments not handled correctly

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3738]
### Describe the bug

doing code below will throw error for arg 5 expect vector get none

### Steps to reproduce

`createBuilding ( 3534, -2412.30884, -601.68127, 132.56250)`
or
`createBuilding ( 3534, -2412.30884, -601.68127, 132.56250,90)` without rz or ry gives error

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
`createBuilding` expects 7 parameters
![image](https://github.com/user-attachments/assets/680fb2cb-77cc-4761-826b-6b05f74041b3)

Providing just the model and position works though

**Comment by Proxy-99** [comment]
> `createBuilding` expects 7 parameters ![image](https://private-user-images.githubusercontent.com/43095317/369123372-680fb2cb-77cc-4761-826b-6b05f74041b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzA3ODcsIm5iZiI6MTcyNjc3MDQ4NywicGF0aCI6Ii80MzA5NTMxNy8zNjkxMjMzNzItNjgwZmIyY2ItNzdjYy00NzYxLTgyNmItNmIwNWY3NDA0MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE4MjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzI0NjcyYTM1YWE1YmU4M2Y4NDE5ZmYxMTQ2MDRiYTQ4ZTZlNTUxMjkyODQ3OTc3Y2IxYWUwMmU4NDFiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-h8_3g8EkB4ftekh8aQYrFjgxYHWjdDk-TJxOhGlz0)
> 
> Providing just the model and position works though

but doing createBuilding ( 3534, -2412.30884, -601.68127, 132.56250,90,0) will break it xd

**Comment by TracerDS** [comment]
> > `createBuilding` expects 7 parameters ![image](https://private-user-images.githubusercontent.com/43095317/369123372-680fb2cb-77cc-4761-826b-6b05f74041b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzA3ODcsIm5iZiI6MTcyNjc3MDQ4NywicGF0aCI6Ii80MzA5NTMxNy8zNjkxMjMzNzItNjgwZmIyY2ItNzdjYy00NzYxLTgyNmItNmIwNWY3NDA0MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE4MjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzI0NjcyYTM1YWE1YmU4M2Y4NDE5ZmYxMTQ2MDRiYTQ4ZTZlNTUxMjkyODQ3OTc3Y2IxYWUwMmU4NDFiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-h8_3g8EkB4ftekh8aQYrFjgxYHWjdDk-TJxOhGlz0)
> > Providing just the model and position works though
> 
> but doing createBuilding ( 3534, -2412.30884, -601.68127, 132.56250,90,0) will break it xd

because you need to provide full vector

**Comment by Proxy-99** [comment]
> > > `createBuilding` expects 7 parameters ![image](https://private-user-images.githubusercontent.com/43095317/369123372-680fb2cb-77cc-4761-826b-6b05f74041b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzA3ODcsIm5iZiI6MTcyNjc3MDQ4NywicGF0aCI6Ii80MzA5NTMxNy8zNjkxMjMzNzItNjgwZmIyY2ItNzdjYy00NzYxLTgyNmItNmIwNWY3NDA0MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE4MjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzI0NjcyYTM1YWE1YmU4M2Y4NDE5ZmYxMTQ2MDRiYTQ4ZTZlNTUxMjkyODQ3OTc3Y2IxYWUwMmU4NDFiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-h8_3g8EkB4ftekh8aQYrFjgxYHWjdDk-TJxOhGlz0)
> > > Providing just the model and position works though
> > 
> > 
> > but doing createBuilding ( 3534, -2412.30884, -601.68127, 132.56250,90,0) will break it xd
> 
> because you need to provide full vector

we should correct it anyway if not ry given it should be set 0 as for createObject does

**Comment by TracerDS** [comment]
> we should correct it anyway if not ry given it should be set 0 as for createObject does

Then we should use x,y,z instead of CVector

**Comment by Proxy-99** [comment]
> > we should correct it anyway if not ry given it should be set 0 as for createObject does
> 
> Then we should use x,y,z instead of CVector

we still could use vectors but handled them in a correct way 

if you look for 

```c++
CClientObject* CStaticFunctionDefinitions::CreateObject(CResource& Resource, unsigned short usModelID, const CVector& vecPosition, const CVector& vecRotation,       bool bLowLod)
```

**Comment by TracerDS** [comment]
`CStaticFunctionDefinitions::CreateObject` is a terrible example.
CVector is already constructed when you call `CreateObject`, whereas in `createBuilding` it is being constructed when calling the function from lua.
