### ISSUE TITLE
createBrowser causes crashes.

### ISSUE THREAD

**Issue by ZbyK77** [multitheftauto/mtasa-blue#3748]
### Describe the bug

Calling the 'createBrowser' function in the latest release causes a '0x01979AC7' crash. This also happens when entering the web browser settings in the main menu.

### Steps to reproduce

1. Run MTA
2. Click 'Settings'
3. Click 'Web browser'
4. Crash.

### Version

Client: Multi Theft Auto v1.6-release-22741
Server: --

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
Download and install this directly
https://mirror-cdn.multitheftauto.com/mtasa/main/mtasa-1.6.exe
Ingame updater is broken

**Comment by Xenius97** [comment]
This can be closed, it's fixed
