### ISSUE TITLE
Full Report on Memory Leak Issues and Solutions in MTA 

### ISSUE THREAD

**Issue by r8dr** [multitheftauto/mtasa-blue#3751]
### Describe the bug

Memory Leak Issue:
Memory leaks were detected in several files within the MTA
source code. These leaks occur when memory is allocated using new but not properly released using delete. This can lead to increased memory usage, performance issues, and potential crashes as the memory is not freed after use.

### Steps to reproduce

 Locate the Source Files:
Navigate to the following files in the source code:
Client/ceflauncher/Main.cpp
Client/ceflauncher_DLL/Main.cpp
Client/ceflauncher_DLL/CCefApp.h
2. Check for Memory Allocation:
In each of these files, search for lines of code where memory is allocated using the new keyword.
3. Check for Memory Release:
In the same files, look for corresponding delete statements that should free the allocated memory,
4. Run the Application:
Compile and run the game (or the specific client/server components) with these files unchanged.
As the game continues to run, you can observe an increasing memory usage over time. This will be especially noticeable during repeated use of features or functions where memory is allocated but not freed.
5. Monitor Memory Usage:
Use a tool like Valgrind (for Linux) or Visual Studio Memory Profiler (for Windows) to track memory allocation and identify leaks.
You should see that memory usage continues to grow, and the profiler will report the areas where memory is not being freed.
6. Observe the Effects:
Over time, the increasing memory usage can lead to performance degradation and potentially cause the game to crash, especially if the system runs low on memory resources.

### Version

so

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
None of the file you posted have memory leaks. At least not with the `new` keyword.
In fact only one file has the `new` keyword but as far as I see its being deallocated properly via the smart pointer

**Comment by Lpsd** [comment]
smells like ChatGPT
