### ISSUE TITLE
Server should reject empty serials

### ISSUE THREAD

**Issue by MegadreamsBE** [multitheftauto/mtasa-blue#3763]
### Describe the bug

@ArranTuna reported this, but can't post it here (likely due to the world 'serial' being flagged).

If a user connects to a server while not having a serial (which is rare - but plausible) the server should reject the player. At the moment it seems like this is not happening.

Servers could of course do a check themselves in Lua, but it's still a good idea to incorporate a check like this.

### Steps to reproduce

N/A

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Player should also **not** have 2 serials to choose from (https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CPlayer.h#L419)

**Comment by ArranTuna** [comment]
> Player should also **not** have 2 serials to choose from (https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CPlayer.h#L419)

That is there for a reason, trust me.

**Comment by TracerDS** [comment]
> > Player should also **not** have 2 serials to choose from (https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CPlayer.h#L419)
> 
> That is there for a reason, trust me.

Whats the reason beside making it all more complex? Both serials are fetched from the client at the exact same time based on the client-server packets

**Comment by CrosRoad95** [comment]
"Server should reject empty serials" i would rather reject INVALID serials, serial that doesn't match regex: `^[A-F0-9]{32}$`

**Comment by Fernando-A-Rocha** [comment]
yeah serial should be validated by the server!!
