### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3769]
### Is your feature request related to a problem? Please describe.

Currently WebGL is disabled
see: https://github.com/multitheftauto/mtasa-blue/pull/2933

### Describe the solution you'd like

Could be very useful for HTML based apps.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by CrosRoad95** [comment]
If WebGL get enabled you can also think about WebGPU

**Comment by Xenius97** [comment]
fixed via #2933
