### ISSUE TITLE
Many collisionless objects - no way to fix

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#377]
**Describe the bug**
I'm experiencing a problem with many objects on my server.

I create objects using `createObject`. Some objects have their col/dff/txd replaced, and this works fine.

There are some typical objects which frequently simple don't have any collisions.

**To Reproduce: Test 1**
I found another object that after being replaced with a custom col, loses it's collisions. 

[TestResource.zip](https://github.com/multitheftauto/mtasa-blue/files/2343674/TestResource.zip)

The resource above changes model ID **5323** (wires object) and applies custom files in the order suggested by ccw. Though, after starting the resource and restarting MTA, object ID 5403 loses its collisions.

I added a fix for collisions to object ID 5403 and later the whole Glen Park area became collisionless. If I disable `engineLoadCOL` and `engineReplaceCOL`, said bugs do not appear.

**To Reproduce: Test 2**

[TestResourceBug2.zip](https://github.com/multitheftauto/mtasa-blue/files/2343675/TestResourceBug2.zip)

I've made another test resource, this time it replaces a common building in Idlewood, the Pizza Shop. After starting the resource, do

```
crun setElementPosition(localPlayer, 1849.2609, -1402.8617, 13.3906)
```

You will fall through the road. The 2 objects aren't even related as they are far away. (World model ID of the bugged road: `5498`)

Using `testresourcebug2` I was wondering if there was pattern between model ID that is applied to and model ID that gets bugged, and it turns out that there is.

That resource applies a mod to `5418` and then `5498` becomes collisionless. That's a `+80` model ID difference.

So then I tried applying the same mod to `5419` and then... `5499` became collisionless. That's `+80` model ID difference again.

Then I tried `1257` to see if `1337` was bugged. It wasn't, this could be because `1257` is a destroyable bus stop, so I will check a solid object.

Tried a mod on `10308` and `10388` (both were buildings) didn't become bugged.

Tried `5400` and `5480` became bugged, so 3 times out of 5 it was `+80` model ID that became bugged.

**Expected behavior**
All replaced collisions should work.

**Additional context**
It's not a script problem, when I go join another server, it still occurs.

Typically about 30% of players have the 'problematic' collisionless objects. Other players can play without any problems. When this starts to happen, it keeps bugging until you restart MTA.

From https://bugs.mtasa.com/view.php?id=8012. Lots of discussion there.

**Comment by ghost** [comment]
I'll try to fix this. Related to #927

**Comment by ghost** [comment]
I'd appreciate if anyone can help me in reproducing this bug. I tried both test resources and couldn't reproduce the bug.
