### ISSUE TITLE
bani njustamente

### ISSUE THREAD

**Issue by psico42** [multitheftauto/mtasa-blue#3802]
### Describe the bug

tomei ban injustamente https://cdn.discordapp.com/attachments/1295919211809341512/1295921146822393867/image.png?ex=6710681e&is=670f169e&hm=92e64d3c08fc0f9121e18a1759f9b82dbf6c9d62228f81d05f25ba3a15d54c74&

### Steps to reproduce

injustamente

### Version

injustamente

### Additional context

injustamente

### Relevant log output

injustamente

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by MegadreamsBE** [comment]
Github is not for ban appeals (which aren't accepted anyways)
