### ISSUE TITLE
add killPedTask as a function

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-blue#3806]
### Is your feature request related to a problem? Please describe.

functions already exist
```c++
bool CClientPed::KillTask(int iTaskPriority, bool bGracefully)

bool CClientPed::KillTaskSecondary(int iTaskPriority, bool bGracefully)
``` 

### Describe the solution you'd like

add new functions 

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Fernando-A-Rocha** [comment]
what are the practical uses of killing ped task? and which tasks would u kill?

**Comment by Proxy-99** [comment]
> what are the practical uses of killing ped task? and which tasks would u kill?

well u can killed the active ped task and cancel the action animation
