### ISSUE TITLE
Can't delete dynamic objects like rocks or desert trees

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#381]
Like in summary, i can't delete dynamic objects like rocks ( these small one ), and desert trees. 

**How to reproduce?**
Use code removeWorldObject or in map editor, try to delete these objects:

[bugmapeditor.jpg](https://dl.dropboxusercontent.com/u/38267354/SerwerPYL/bugmapeditor.jpg) (404), [bugmapeditor2.jpg](https://dl.dropboxusercontent.com/u/38267354/SerwerPYL/bugmapeditor2.jpg) (404)

Simple code to delete these objects. Here some bushes and rocks on flat hill in Bayside Marina:

```
removeWorldModel(905, 20, -2402.84,2553.87,23.60)
removeWorldModel(905, 20, -2407.31,2558.97,23.60)
removeWorldModel(865, 20, -2456.68,2555.44,23.15)
removeWorldModel(815, 20, -2456.68,2555.44,23.15)
removeWorldModel(864, 20, -2456.68,2555.44,23.15)

removeWorldModel(865, 20, -2410.63,2557.15,23.60)
removeWorldModel(815, 20, -2410.63,2557.15,23.60)
removeWorldModel(864, 20, -2410.63,2557.15,23.60)
```

There is a workaround I used to stop, at least, procedural vegetation from generating on a surface. I simply deleted the world object where it generates on and then recreated it as a MTA object, and when I left the area and entered back in no plants were generated. In case you are wondering, to get the exact coordinates where the world object was I used MEd.

Well, I've been testing a memory address that I found in forums:

'0x53C159' It is an array of 5 bytes which by default they are:

E8 42 0E 0A 00

if the 5 has changed

90 90 90 90 90 (hexadecimal)

Stop created random foliage! (I've tested)

Someone who can create a patch for this?
Example: (similar to 'setInteriorFurnitureEnabled')

setFoliageEnabled(bool enabled)
isFoliageEnabled()...

him to be tried! :)

https://bugs.mtasa.com/view.php?id=7657

**Comment by samr46** [comment]
Function: [setWorldSpecialPropertyEnabled](https://wiki.multitheftauto.com/wiki/SetWorldSpecialPropertyEnabled)
Option: randomfoliage

**Comment by patrikjuvonen** [comment]
Along with the fact that those links don't work, I agree with @samr46, you can use setWorldSpecialPropertyEnabled, unless I'm missing something. Closing.
