### ISSUE TITLE
handling and nitro bug

### ISSUE THREAD

**Issue by mahlukat5** [multitheftauto/mtasa-blue#3814]
### Describe the bug

When you change handling while nitro is on in the car, the handling breaks.

### Steps to reproduce

1. spawn a vehicle and add nitro
2. change any handling value twice

### Version

Client: 1.6.0-9.22780.0
Server: 1.6.0-9.22628.0

### Additional context

https://www.youtube.com/watch?v=8cyjfLG6078

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Proxy-99** [comment]
could be related to the last change in (https://github.com/multitheftauto/mtasa-blue/commit/f96836397a075585d4d112eb7d0240f1abf361d4)
or just another bug

**Comment by FileEX** [comment]
Can you check version r22755 or earlier?

**Comment by mahlukat5** [comment]
> Can you check version r22755 or earlier?

I tested r22755 and there are no bug with this version.

and i noticed one thing maybe it helps

in version r22755 when u change handlings, handling flags "8" disabled. but after version r22755 handling flags "8" is becoming active when u change hand twice (u can see this in the video)

**Comment by FileEX** [comment]
Fixed in #3815
