### ISSUE TITLE
Ability to allocate new object IDs

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#384]
From https://bugs.mtasa.com/view.php?id=6571

**Comment by qaisjp** [comment]
Just going to outright close this one as it needs to be split into individual issues.

**Comment by Fernando-A-Rocha** [comment]
Which issues @qaisjp ?

**Comment by qaisjp** [comment]
The task is too far and wide reaching and so individual proposals (for implementation) need to be created by contributors.
