### ISSUE TITLE
Ability to switch off street lights

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#385]
This is a request from "zencro":

**Is your feature request related to a problem? Please describe.**
> It's currently impossible to turn off the lights at night time.

**Describe the solution you'd like**
> Perhaps a setAmbientLightingEnabled/toggleAmbientLighting()?

**Describe alternatives you've considered**
> I checked to see if this is possible with shaders and it's not. Disabling `coronastar` makes the lampposts not shine, but it doesn't get rid of the actual light on the ground and also ends up disabling the stars and the sun. Maybe there's a more complex shader solution than that though.
>
> I think a function that makes everything darker would be more useful than something that disables street lights because even with all the street lights removed the world is still way too bright at night time and the only way to get close to proper darkness is one of those super dark weathers. Though this is almost realistic dark:
>
> ```
> crun setWeather(159)
> crun setSkyGradient(0, 0, 0, 0, 0, 0)
> ```

**Additional context**
> It's precisely for roleplay, and mainly for ambience. If a roleplay is set during a blackout, it would be nice to actually not have lights.

From https://bugs.mtasa.com/view.php?id=5543

**Comment by samr46** [comment]
I'm not sure if it's exactly what author wanted but it will be possible to disable street lights with a timecycle option from PL #276

**Street lights off**
![image](https://user-images.githubusercontent.com/923242/50401714-9d72bd80-0788-11e9-9aae-62eb5d558d5c.png)

**Insane street lights**
![image](https://user-images.githubusercontent.com/923242/50401717-a3689e80-0788-11e9-84a0-8115319a2ee9.png)

**It doesn't affect other coronas (moon, sun, markers, etc.)**
![image](https://user-images.githubusercontent.com/923242/50401721-a95e7f80-0788-11e9-92db-0bac9a72eaa7.png)

**Comment by qaisjp** [comment]
Neat, I've edited the issue to reflect that.
