### ISSUE TITLE
Make the window edges dark when Windows is in dark mode

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3859]
### Is your feature request related to a problem? Please describe.

Currently if you run MTA in windowed mode, window edge is white
![Image](https://github.com/user-attachments/assets/ac4ffb5f-2ccd-445b-b356-5f5043536c98)

### Describe the solution you'd like

Detect system mode and use dark edges line other programs
![Image](https://github.com/user-attachments/assets/5c52a52b-6bc8-4ce4-bcff-357b6130d94a)

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by botder** [comment]
Just set `DWMWA_USE_IMMERSIVE_DARK_MODE` to `TRUE` via `DwmSetWindowAttribute` from `dwmapi.dll`.
https://github.com/libsdl-org/SDL/blob/f8468d580d903e106640800034a4721aca24264c/src/video/windows/SDL_windowswindow.c#L2227-L2239
