### ISSUE TITLE
Bug in the compiled mta library for windows 7/8.x

### ISSUE THREAD

**Issue by nweb** [multitheftauto/mtasa-blue#3865]
### Describe the bug

For some unknown reason, the compiled loader.dll library in MTA for Windows 7/8.x indicates completely different MD5 hashes of the client files being checked, in particular bass_aac.dll. The files themselves in both assemblies (Win 7/8/10+) are the same, have the same hash as in the [source](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/loader/MainFunctions.cpp#L866), but when starting the launcher an error occurs (Data file %s is missing. Possible virus activity).

### Steps to reproduce

1. Go to mtasa.com
2. Download both versions of the game
3. Extract mta/bass_aac.dll files from the installers
4. Make sure that the MD5 hash of each file is 80CDC5A50B27C47E53B99DE4D4523698
5. Extract mta/loader.dll files from the installers
6. Make sure that the integrityCheckList table is built with an error for Win 7/8.x
![Image](https://github.com/user-attachments/assets/ada55703-0593-4bc7-a589-52f097d5c5c8)

### Version

Client: v1.6.0-release-22789 (Windows 7/8.x)

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
From the `release/maetro` branch:
https://github.com/multitheftauto/mtasa-blue/blob/9df22bfe2927d67b4cf7b5f20d19ecda24eccb8b/Client/loader/MainFunctions.cpp#L862-L875

**Comment by nweb** [comment]
> From the `release/maetro` branch:
> 
> [mtasa-blue/Client/loader/MainFunctions.cpp](https://github.com/multitheftauto/mtasa-blue/blob/9df22bfe2927d67b4cf7b5f20d19ecda24eccb8b/Client/loader/MainFunctions.cpp#L862-L875)
> 
> Lines 862 to 875 in [9df22bf](/multitheftauto/mtasa-blue/commit/9df22bfe2927d67b4cf7b5f20d19ecda24eccb8b)
> 
>  struct 
>  { 
>      const char* expected; 
>      const char* fileName; 
>  } integrityCheckList[] = {{"36CB1B284BC7CBB4F25CD00BBB044550", "bass.dll"},           {"1B909B47946167D153FB94020393E781", "bass_aac.dll"}, 
>                            {"E7E69A3B369F0ABA1A4A18C831BC4364", "bass_ac3.dll"},       {"E20A57EA7D845FADC9A48A0AA919121A", "bass_fx.dll"}, 
>                            {"F47DCE69DAFAA06A55A4BC1F07F80C8A", "bassflac.dll"},       {"F246D72BA73E9624FE8BE66E785FB5C5", "bassmidi.dll"}, 
>                            {"5DEEC10A943E352EF7E0223327E8B48C", "bassmix.dll"},        {"2F87C5E0A1B7B28C8FC0D7E74116DDFC", "bassopus.dll"}, 
>                            {"0F1B2FC6C0C703A43A24DC05352E7ADA", "basswebm.dll"},       {"893113C6C49DC1E1EF288310E68DB306", "basswma.dll"}, 
>                            {"C6A44FC3CF2F5801561804272217B14D", "D3DX9_42.dll"},       {"D439E8EDD8C93D7ADE9C04BCFE9197C6", "sa.dat"}, 
>                            {"B33B21DB610116262D906305CE65C354", "D3DCompiler_42.dll"}, {"02ECD2919B3DAA59D6014EEFD29FC294", "tags.dll"}, 
>                            {"0B3DD892007FB366D1F52F2247C046F5", "d3dcompiler_43.dll"}, {"D5D8C8561C6DDA7EF0D7D6ABB0D772F4", "xinput1_3_mta.dll"}, 
>                            {"E1677EC0E21E27405E65E31419980348", "d3dcompiler_47.dll"}, {"E2BAC93166B0C2AD4D83E97FC1E88F8F", "XInput9_1_0_mta.dll"}};

Really. But the hashes are still not correct, make sure that [bass_aac.dll](https://github.com/multitheftauto/mtasa-blue/blob/release/maetro/Shared/data/MTA%20San%20Andreas/MTA/bass_aac.dll) from maetro does not have hash 1B909B47946167D153FB94020393E781.

You forgot to update hashes after commit https://github.com/multitheftauto/mtasa-blue/commit/c6a79fe532f885b5fb526c4e891012869eb4d731

**Comment by botder** [comment]
Fixed in 189db457c5d5802c6b8c8ee64b93ca1eeab08182
