### ISSUE TITLE
Ability to use classic cylinder marker

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3875]
### Is your feature request related to a problem? Please describe.

Hello.
I'm not sure how many of you know but there are two types (two looks) of the cylinder marker in singleplayer.

MTA uses only one of them, maybe it would be a cool feature to add the classic too (which comes from GTA3 & VC) 
(The classic one has 2 outer circles around the main one.)

https://i.imgur.com/kEiUjhd.png

Left: current one, right: classic

(btw1. both of these cylinders have a base rotating animation which doesn't work in MTA. Checkpoint type of markers have it too and they work, so I guess its a bug in MTA. I understand why arrows can't have their base animation as sometimes you want moving and non-moving arrows) 
(btw2. I know I can make it rotate if I want with lua, but it should have as default)

### Describe the solution you'd like

```lua
createMarker(x, y, z, "classicCylinder")
```
or

```lua
createMarker(x, y, z, "cylinder2")
```

### Describe alternatives you've considered

creating 3 markers at the same position but with smaller sizes. Won't work due to marker's heights are calculated by their size. If we would have a setMarkerHeight that would help as well.

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Xenius97** [comment]
You can replace `1317` Cylinder model to classic.

https://dev.prineside.com/en/gtasa_samp_model_id/model/1317-Cylinder/
https://github.com/multitheftauto/mtasa-blue/pull/3059

**Comment by ghost** [comment]
I'm closing this because this can be done by the following way: 
Mission markers:

```lua
createMarker(x, y, z, "cylinder", 2, 255, 0, 0, 64)
```
Markers inside interiors:
```lua
createMarker(x, y, z, "cylinder", 1, 255, 0, 0, 64)
createMarker(x, y, z, "cylinder", 0.9, 255, 0, 0, 64)
createMarker(x, y, z, "cylinder", 0.8, 255, 0, 0, 64)
```
Describe alternatives you've considered: I noted this at the main post but it turned out that this is the expected behaviour in singleplayer.
(I might add this to the `createMarker` on wiki for others who "run into the same issue")

**Comment by Xenius97** [comment]
> I'm closing this because this can be done by the following way: Mission markers:

Why you creating 3 markers instead of replacing to a classic model? Open the default cylinder model and copy 2 times (a smaller and a bigger) and save & replace 1317 model.
If you create 3 markers to one interior, you will have sync-issues for too many interiors (Markers will blink-disappear if you reach the limit, which is 32)
Eg. if you create 10 interiors in a small zone, you will reach the limit.

**Comment by ghost** [comment]
> Why you creating 3 markers instead of replacing to a classic model? 

There is no classic model. I'm pretty sure the base game do place 3 markers too on top of each other.

> Open the default cylinder model and copy 2 times (a smaller and a bigger) and save & replace 1317 model. 

Not everyone is as experienced like you with editing models. I've just opened this issue but I know other scripters who want to create classic cylinders in their server. Doing this is way faster and easier and the planned usage will never ever reach the marker limit at all.

> If you create 3 markers to one interior, you will have sync-issues for too many interiors

Not sure I understand what are you trying to say here. I will have sync-issues in every interior if i place 3 markers on top of each other?

 How does that come? Just think about ammu-nations with shooting ranges. There are at least 3 markers there, two cylinders, one for buying weapons, one for the shooting range and one for the yellow leaving arrow. There will be no problem with having 3 markers inside one interior.  Even if i placed all of them on the same position. This is not how it works.

> (Markers will blink-disappear if you reach the limit, which is 32)

They won't blink, they will simply won't be rendered. As I wrote it already, the planned usage of this will never ever reach this limit at all.
If I wanted to place 10 (30) cylinders next to each other, then I would probably place even more, not just 10 but I can't think of any good reason why I would do that.

By the way the only interior and place where marker limit is an issue is Kickstart. If you want to recreate it, then you have to place more than 32 coronas there. We have it in our server. All of them are rendered, even if we have more than the limit. In the past we faced the problem that some of the coronas doesn't get rendered (not blinking) but nowadays they all do.

The other interiors, food shops, barbers, tattos etc are not in the same interior and they are not as close to each other to be in the same streamed-in zone. So even if in your server you have a .map file where you put these cylinders in every shop, you won't notice any problem at all.

The intented/planned way of creating cylinders like this are in interiors (shops) which are in different interiors by default and will be set to different dimensions as well. There will be like 2-3 cylinders placed like this. The limit won't be reached.
I don't see the point of searching about a tool which can edit the model and do the work which possibly takes way more time than the benefit I get. 

iirc there is a PR which aims to increate this limit but might be abandoned.
