### ISSUE TITLE
createProjectile crashes the game after quitting / getting kicked

### ISSUE THREAD

**Issue by q8X** [multitheftauto/mtasa-blue#3876]
### Describe the bug

as in title, after quitting / getting kicked, the game crashes right before the explosion, For some reason the crash happened if you created a +15 projectile, tested on ID (16,18,19,20,21)
```
Version = 1.6-release-22789.0.000
Time = Thu Dec  5 21:52:41 2024
Module = C:\ProgramData\MTA San Andreas All\1.6\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x00171BA0

EAX=80808080  EBX=00000000  ECX=100F0F00  EDX=C417A19C  ESI=00C89018
EDI=00C89030  EBP=100F0F00  ESP=0177ED60  EIP=00571BA0  FLG=00210282
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

### Steps to reproduce

1. start runcode
2. `crun for i = 1, 15 do createProjectile(me, 16, me.position) end`
3. use /quit or click on **Disconnect** button in the main menu 

### Version

Multi Theft Auto v1.6-release-22789

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by FileEX** [comment]
Fixed in #3878
