### ISSUE TITLE
Enhance Custom Model Support: Remove ID Limitations and Enable User-Defined IDs

### ISSUE THREAD

**Issue by A0M2P1** [multitheftauto/mtasa-blue#3881]
### Is your feature request related to a problem? Please describe.

In MTA, when adding an object to the game world, you must assign it an ID, position, and other properties. However, there are limitations when working with custom models:
1. ID Range Limitation: The model IDs must fall within the range of 1 to 32,000. This restricts flexibility and should be improved to allow any natural number as a valid ID without limitations.
2. Custom ID Assignment: It is not currently possible to assign specific, user-defined IDs to models. This capability should be added to provide more control over custom object integration.

Addressing these issues would greatly enhance the ability to work with custom models in MTA.

### Describe the solution you'd like

I would like a function to be added that allows defining a model ID with a custom range. This function should enable assigning a specific ID to the model, regardless of predefined limitations. Additionally, the function should provide the ability to link the model ID to its corresponding TXD, DFF, and COL files seamlessly. This would give developers more flexibility and control when integrating custom models into the game.

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by A0M2P1** [comment]
https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CModelNames.h line 15:\
```#define INVALID_MODEL_ID        32000```

**Comment by Fernando-A-Rocha** [comment]
Model IDs will always have the number range problem, and they don't carry a meaning.

I would prefer model name strings defined by the developer e.g. `"my_fridge"`

Btw, see #2251

**Comment by Fernando-A-Rocha** [comment]
Also see #2533
