### ISSUE TITLE
setServerConfigSetting crashes on latest nightly

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3882]
### Steps to reproduce

```lua
setServerConfigSetting("ped_sync_interval", 200, true)
```

### Version

22815 x64 (may x86 too)

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by ALBANDER2022** [comment]
please explain more and add video about your issue

**Comment by Xenius97** [comment]
> please explain more and add video about your issue

What explanation you want? Run this command and entire server crashes.

**Comment by TheNormalnij** [comment]
A broken bitstream version check causes this. 
We will remove all old checks with 1.6.1

reason: https://github.com/multitheftauto/mtasa-blue/commit/514a3b36d09906f09bb32e900c39dc09b1c29d10#r150343612

**Comment by ALBANDER2022** [comment]
> > please explain more and add video about your issue
> 
> What explanation you want? Run this command and entire server crashes.

Are you mean that if you execute this code in runcode or in admin panel server crashes ?

**Comment by Xenius97** [comment]
> Are you mean that if you execute this code in runcode or in admin panel server crashes ?

Yep, but i've talk with TheNormalnij and only setServerConfigSetting is broken.
