### ISSUE TITLE
i'm unable to join server at all

### ISSUE THREAD

**Issue by CArg22** [multitheftauto/mtasa-blue#3885]
### Describe the bug

I have been running my server for long time but today suddenly noobody can join it, even after i reinstalled it with all original files noobody can join.
Can't see any logs in console, server normally runnings, scripts started. Doesn't matter if i'm running it inside docker or not. Reinstalled vps and still same issue, my hosting provider says it is not his fault, what can i do?

When i run the same server on another machine, locally and remotely on friend hosting it just working and everyone can join.

### Steps to reproduce

idk

### Version

server debian 1.6 22823

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
That sounds like a misconfigured vps.
Have you tried checking if the ports are open?
Can you join the server or only others cant?
I dont think this is an issue with mta itself but rather, as mentioned above, a misconfigured server and so github is not really the place for such problems.

**Comment by CArg22** [comment]
I doubt it is my fault. Everything worked until yesterday, ort tester says that all three ports are open.
It looks like my server was blocked from mta side.

**Comment by TracerDS** [comment]
I can join just fine ¯\_(ツ)_/¯
How are you trying to join your server?

**Comment by CArg22** [comment]
i can't join my server, but i have no problem to join any other server. I do it like everyone else, go to server browser and double click on my server

**Comment by TracerDS** [comment]
> i can't join my server, but i have no problem to join any other server. I do it like everyone else, go to server browser and double click on my server

1. Are you sure the server you click on is **your** server?
2. Did you try connecting directly (via console)?

**Comment by CArg22** [comment]
1. yes
2. yes
everyone experience the same issue as i, noobody can join and i'm sure that's not my fault

**Comment by TracerDS** [comment]
This happens only on the vps, right?

**Comment by CrosRoad95** [comment]
Indeed they can block the server https://www.youtube.com/watch?v=dfFoTLGvRQ0&feature=youtu.be

**Comment by Dutchman101** [comment]
> I doubt it is my fault. Everything worked until yesterday, ort tester says that all three ports are open. It looks like my server was blocked from mta side.

@CArg22 
What's the server ip:port?

Even though this isn't the right place, i will see if i can help to diagnose the issue. I'll even do some network/HQ tests while trying to establish a connection. Unless of course i find you have been blocked for a reason.

**Comment by CrosRoad95** [comment]
Better tell people you just destoryed my server https://www.youtube.com/watch?v=dfFoTLGvRQ0&feature=youtu.be

> > I doubt it is my fault. Everything worked until yesterday, ort tester says that all three ports are open. It looks like my server was blocked from mta side.
> 
> [@CArg22](https://github.com/CArg22) What's the server ip:port?
> 
> Even though this isn't the right place, i will see if i can help to diagnose the issue. I'll even do some network/HQ tests while trying to establish a connection. Unless of course i find you have been blocked for a reason.

**Comment by Dutchman101** [comment]
@CrosRoad95 This issue on tracker isn't about you or your server, posts cleared.. here is your last warning to stay out of it (and any other issues) or face a repository ban as well.

**Comment by CrosRoad95** [comment]
> [@CrosRoad95](https://github.com/CrosRoad95) This issue on tracker isn't about you or your server, posts cleared.. here is your last warning to stay out of it (and any other issues) or face a repository ban as well.

There is no other way to contact you

And if "This issue on tracker isn't about you or your server, " i'm creating new  my own :)

**Comment by ffsPLASMA** [comment]
Are you turkish/going online from turkey? They are well known for blocking certain internet routes to other server providers.
