### ISSUE TITLE
DxDrawModel3D Problems

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3891]
### Describe the bug

At the moment I'm using DxDrawModel3D, the lighting looks like this only on id models of the weapons

![Image](https://github.com/user-attachments/assets/40c2422e-6ae2-44e7-ab01-44ebdf6fabe2)

### Steps to reproduce

Using the same structure as in the wiki but adding more models to DxDraw
https://wiki.multitheftauto.com/wiki/DxDrawImage3D

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
The first image is using the [mtasa-pAttach](https://github.com/Patrick2562/mtasa-pAttach) system:
![Image](https://github.com/user-attachments/assets/2abe4fd2-6238-4b79-a52b-5f59286edeba)

The second image uses the [dxDrawModel3D](https://wiki.multitheftauto.com/wiki/DxDrawModel3D) function:
![Image](https://github.com/user-attachments/assets/31fd93e5-e365-4446-acf6-0cb3c6ce0eeb)

**Comment by ghost** [comment]
Another problem, when I define an id for an interior, the ids defined in `DxDrawModel3D` do not appear, but when I am in interior 0 and define any dimension, it is successful.

**Comment by tederis** [comment]
Lighting is a property of objects (CObject). dxDrawModel3D doesn't operate with objects and cannot apply any lighing on it. You can use a shader for it in conjunction with getElementLighting.

**Comment by tederis** [comment]
> Another problem, when I define an id for an interior, the ids defined in `DxDrawModel3D` do not appear, but when I am in interior 0 and define any dimension, it is successful.

You mean dxDrawModel3D doesn't work in interiors?

**Comment by ghost** [comment]
> > Another problem, when I define an id for an interior, the ids defined in `DxDrawModel3D` do not appear, but when I am in interior 0 and define any dimension, it is successful.
> 
> You mean dxDrawModel3D doesn't work in interiors?

That's right, I've tested it and it's only working for the outdoors but not for the indoors

**Comment by vshiroshi** [comment]
@lynconsix up!

**Comment by tederis** [comment]
> > > Another problem, when I define an id for an interior, the ids defined in `DxDrawModel3D` do not appear, but when I am in interior 0 and define any dimension, it is successful.
> > 
> > 
> > You mean dxDrawModel3D doesn't work in interiors?
> 
> That's right, I've tested it and it's only working for the outdoors but not for the indoors

Cannot reproduce it. I'd be grateful if you create a test resource or describe concrete steps of reproducing.

**Comment by tederis** [comment]
Fixed in #3904

**Comment by ghost** [comment]
> > > > Another problem, when I define an id for an interior, the ids defined in `DxDrawModel3D` do not appear, but when I am in interior 0 and define any dimension, it is successful.
> > > 
> > > 
> > > You mean dxDrawModel3D doesn't work in interiors?
> > 
> > 
> > That's right, I've tested it and it's only working for the outdoors but not for the indoors
> 
> Cannot reproduce it. I'd be grateful if you create a test resource or describe concrete steps of reproducing.

Okay, I was making a “bone_attach” with this function, I also used `engineRequestModel`, the lights were also as I presented above 
[attach_model3d.zip](https://github.com/user-attachments/files/18240832/attach_model3d.zip)
