### ISSUE TITLE
Typo in CResourceChecker.cpp

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3892]
### Describe the bug

"Please replace with XY before Tuesday."

### Steps to reproduce

https://github.com/multitheftauto/mtasa-blue/blob/6768df5d6266ec2357779cbb5e9d34c328dd0bc9/Server/mods/deathmatch/logic/CResourceChecker.cpp#L732

```
setControlState is deprecated and may not work in future versions. Please replace with setPedControlState before Tuesday.
```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
We already answered you this in dev discord; it's figurative speech.
