### ISSUE TITLE
Shaders used on vehicles no longer have backward compatibility and the components have incorrect textures applied [after #3837]

### ISSUE THREAD

**Issue by C0DELEVEL** [multitheftauto/mtasa-blue#3893]
### Describe the bug

This PR probably broke backward compatibility of some shaders. Also after recent update (ver. 22829) texture of vehiclegrunge256 are not correctly displayed on vehicles and components.

Vehicle components probably use now different materials or texture and they are not shown up on shader_tex_names (displayed only on 'chassis' of ZR-350, missing on doors, bonnet, rear bumper, extra1 and whole Premier)
![Image](https://github.com/user-attachments/assets/4a1816aa-fc72-49a2-b255-d93d05d149a2)
![Image](https://github.com/user-attachments/assets/be876307-2221-48d2-b870-6a72616f512d)

ver. 22789 - shader works perfectly fine
![Image](https://github.com/user-attachments/assets/928d9551-c230-4700-a60c-c058c654f099)

ver. 22829 - shader does not work on vehicle components as bonnet and boot resulting in different shades of paint
![Image](https://github.com/user-attachments/assets/1347f19c-c88f-45e1-a85f-a77c2838de99)

### Steps to reproduce

- self-explained above with screenshoots

### Version

Client - r22829

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
Thanks, ff84958
