### ISSUE TITLE
Incorrect position in some functions after "Fix CVector..." (ZYX instead of XYZ in createBuilding and getElementsWithinRange).

### ISSUE THREAD

**Issue by ZbyK77** [multitheftauto/mtasa-blue#3895]
### Describe the bug

Since the last update, buildings are being created at reversed coordinates from those entered (X/RX is swapped with Z/RZ). The same issue affects getElementsWithinRange, which returns elements at a different position than the one provided. It's most likely broken by the "Fix CVector optional arguments - #3738 (#3782)" update.

### Steps to reproduce

1. run 
``` 
building = createBuilding(6295,10,20,30,0,0,90);
iprint("position",getElementPosition(building));
iprint("rotation",getElementRotation(building)) 
```
2. Look at result

### Version

Multi Theft Auto v1.6-release-22837

### Additional context

![Image](https://github.com/user-attachments/assets/29138b5a-a7a8-4990-8f40-562bd14595bb)

### Relevant log output

```shell
"position" 30 20 10  
"rotation" 90 0 0
```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
I can proof this, getElementsWithinRange no longer works.
![Image](https://github.com/user-attachments/assets/fbd2f5b0-d8dd-4325-935f-8a579920cc8f)

**Comment by TracerDS** [comment]
#3896 should fix this issue. For now lets rollback to previous version
