### ISSUE TITLE
setModelHandling return always false

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3898]
### Describe the bug

After 22837 this function returns always false but it changes handling

### Steps to reproduce

```lua
setModelHandling(574, "maxVelocity", 1000)
```
-> This should return true, cause handling is changed as it should be

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment]
Maybe the issue lies in r22837 (#3848)?

**Comment by Xenius97** [comment]
I've tested, this problem started at 22837 (22841 for x64), pr: #3848

**Comment by TracerDS** [comment]
I see the issue
![Image](https://github.com/user-attachments/assets/527908bf-be90-4042-a1e6-95c0b9563c38)
It returns false when it successfully changes the handling

**Comment by G-Moris** [comment]
Sorry, thanks for the decision.

**Comment by TracerDS** [comment]
No need to be sorry. Happens to all of us.
