### ISSUE TITLE
Game is crashing when joining any server

### ISSUE THREAD

**Issue by ONLIGHT2115** [multitheftauto/mtasa-blue#3913]
### Describe the bug

When I try to connect any server, it's just downloading the map and crashing or when I type in console showmemstat it crashes too.

### Steps to reproduce

1. Browse server
2. Connecting to a server
3. Downloading map
4. Crash

Or:
1. Open console 
2. Type: showmemstat
3. Crash

### Version

Client: v1.6-release-22850 (Windows 10, 64-bit)

### Additional context

https://youtu.be/BKY-m1kEAMw

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by ghost** [comment]
Can't reproduce on [r22862](https://buildinfo.multitheftauto.com/?Revision=22862&Branch=)

**Comment by botder** [comment]
Try joining FFS server, I crashed there

**Comment by botder** [comment]
The crash trace is:

1. `CLuaElementDefs::SetElementModel` for CDeathmatchVehicle and model 425
2. `CStaticFunctionDefinitions::SetElementModel` in `case CCLIENTVEHICLE:` block calling `Vehicle.SetModelBlocking(usModel, 255, 255);`
3. `CClientVehicle::SetModelBlocking` calling `m_pModelInfo->Request(BLOCKING, ...)`
4. `CModelInfoSA::Request` loading anim file index 114 from anim id 25689 via `pAnim->Request(requestType, szTag);`
5. `CModelInfoSA::Request` crashing on `dassert(0);`

**Comment by botder** [comment]
Crash introduced by bae4ca9f0184772e2175e1ed5c22bbaa68ae4f3d
