### ISSUE TITLE
Players glued to a vehicle can't switch weapons

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#392]
**Describe the bug**
Scrolling weapons doesn't work, but scripts are able to change your weapon slot (for example if a server has key binds selecting weapons)

**To Reproduce**
1. Get [glue](https://community.mtasa.com/index.php?p=resources&s=details&id=51)
1. Get on top of a vehicle
1. `give ak-47`
1. Press `x` to glue to vehicle
1. Scroll mouse wheel and notice how you can't switch weps

**Expected behavior**
Weapon switching should work

**Additional context**
From https://bugs.mtasa.com/view.php?id=2276

**Comment by CrosRoad95** [comment]
Reason why you can't switch weapon
![image](https://user-images.githubusercontent.com/22455534/45884127-4f2dd700-bdb3-11e8-82a7-77de91627b26.png)
offset: 0x60D8AE
in function CPlayerPed::ProcessWeaponSwitch(CPad *)	.text	0x60D850

how this should be resolved?
1. just remove this condition
2. add something, example new property for setWorldSpecialPropertyEnabled to enable/disable this?

**Comment by qaisjp** [comment]
just remove condition sounds good to me

**Comment by qaisjp** [comment]
fixed in #533
