### ISSUE TITLE
Hotring Racers share handlings when set by model ID

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#397]
**Describe the bug**

joaosilva099 said:

> Setting the handling of modelid 502, 494, 503 (Hotring Racers) also sets the handling on all the other Hotring Racers

**To Reproduce**

> ```
> run getModelHandling(494).engineInertia, getModelHandling(502).engineInertia, getModelHandling(503).engineInertia
> run setModelHandling(494, "engineInertia", 1)
> run getModelHandling(494).engineInertia, getModelHandling(502).engineInertia, getModelHandling(503).engineInertia
> ```
> 
> See all that the hotrings have had their handlings changed.
> 
> PS: Used engineInertia as an example, works with all the other properties
> 

**Expected behaviour**

> Only that individual model ID should be affected.

**MTA version**: 1.5.2

**Additional context**
From https://bugs.mtasa.com/view.php?id=9332

**Comment by qaisjp** [comment]
BrainAndrews said:
> Same bug with ID 466 'Glendale' and its twin ID 604 'Damaged Glendale'

@Bonus1702 said:
> It's handled in "eHandlingTypes CHandlingManager::GetHandlingID":
> https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CHandlingManager.cpp#L176
> 
> But why?
