### ISSUE TITLE
Command to clear server-side resources cache

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#400]
**Is your feature request related to a problem? Please describe.**
I just want to save space on server.

**Describe the solution you'd like**
Add command that clear cache by removing unneeded files.

**Describe alternatives you've considered**
There's no alternatives, i don't want to restart server every time i going to clear cache.

**Comment by jushar** [comment]
Why do you need to clear your cache so often?

I'd assume if it's really a disk space problem, clearing it right before the server starts is sufficient in most cases.

**Comment by qaisjp** [comment]
Closing as stale & author never responded
