### ISSUE TITLE
Strip the beginning of a server name from repeating chars

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#402]
**Is your feature request related to a problem? Please describe.**
People abuse this to get their server on top of the list when sorting alphabetically.

**Describe the solution you'd like**
- [ ] Remove leading spaces for all servers
- [ ] If a server contains no alphanumeric characters, hide from server list (this might be easier to enforce within the master server list?)
- [ ] When sorting by name it would be neat to only consider alphanumeric characters (CEGUI limitation?)

**Additional context**
https://bugs.mtasa.com/view.php?id=5070

**Comment by Citizen01** [comment]
(Talking about the 2nd point)
So 
`[FR][RPG] My awesome french server`
would appear like this in the server list ?
`FRRPG My awesome french server`
I don't feel like it's a good thing if that's the case.

The points 1 and 2 sound good to me.

**Comment by qaisjp** [comment]
If you mean the third point.. it would sort by that string, but display as the original string

**Comment by Citizen01** [comment]
No, understood the 3rd point, was talking about the 2nd point (I see that I said points 1 & 2 sound good to me but I wanted to say 1 & 3 instead).
I just read the 2nd point again and I thought you wanted to hide the non alphanumeric characters from the server's name while in fact, you want to hide completly a server from the list if it has not a single alphanumeric character. My bad.

In the end, all 3 points are good to me.
