### ISSUE TITLE
cloneElement can't clone colshapes

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#403]
**Describe the solution you'd like**
Write code so that cloneElement works on colshapes.

**Additional context**
Blocked by #182.
https://bugs.mtasa.com/view.php?id=8193

**Comment by patrikjuvonen** [comment]
cc @emre1702

**Comment by emre1702** [comment]
Will do it later when I got enough time after adding the cloneElement method first (virtual method "clone" for elements).
