### ISSUE TITLE
SQLite crash

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#405]
**Describe the bug**

TAPL said:

> I just was doing some mess with SQL and found a code crash the server.

**To Reproduce**
```lua
db = dbConnect("sqlite", "database.db")
dbExec(db, "CREATE TABLE IF NOT EXISTS A1 (accName)")
dbExec(db, "CREATE TABLE IF NOT EXISTS A2 (accName)")
for i=1, 5000 do
    dbExec(db, "INSERT INTO A1 VALUES(?)", i)
    dbExec(db, "INSERT INTO A2 VALUES(?)", i)
end

local h = dbQuery(db, "SELECT * FROM A1, A2")
local result = dbPoll(h, -1)
```

TAPL also said:

> If I used * to select everything it will crash, if I specify the column it won't crash and an error will appear "ambiguous column name".

**MTA Server (please complete the following information):**
 - r13804

**Additional context**
From [mantis 8336](https://bugs.mtasa.com/view.php?id=8336), @sbx320 said:

> For some reason "SELECT * FROM A1, A2" leads to sqlite3_step always(?) returning SQLITE_ROW, which results in an infinite loop with memory allocations. The crash occurs due to an out-of-memory exception.

**Comment by qaisjp** [comment]
Is this a bug in vendor code or a bug in our code?

**Comment by StifflersMom** [comment]
The sqlite3 client itself does not crash by doing
`sqlite3 database.db 'select * from A1,A2' >out.txt`
The memory usage of the sqlite3 process is normal and out.txt ends with
5000|4998
5000|4999
5000|5000
(END)

The demo code above does not crash a mta-server64 running on a machine with 32G RAM, but every time doing h = dbQuery(db, "SELECT * FROM A1, A2") it eats up ~ 7G memory. Doing this 2 times:
![image](https://user-images.githubusercontent.com/12788736/45080649-a36b6280-b0f5-11e8-9d88-2019462cfb2b.png)

There should be a memory limit for such operations :)

**Comment by qaisjp** [comment]
oh so it's just trying to load 25000000 rows into memory?

**Comment by sbx320** [comment]
Yup. 5000^2 results is a bit much for x86 servers. The command line sqlite3 will usually be x64 on most machines and therefore is unaffected.
