### ISSUE TITLE
Camera clips through objects outside game area

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#407]
**Describe the bug**
If you turn your camera a certain way, you can "see through" any objects created beyond the 3000x3000 XY area.

**To Reproduce**

```
/start runcode
/run createObject(1336,2980,2980,1)
/run createObject(1336,3010,3010,1)
/run me.position = Vector3(3000, 3000, 0)
```

**Expected behavior**
No clip

**Additional context**

From https://bugs.mtasa.com/view.php?id=1329

**Comment by lopezloo** [comment]
It was already partially fixed. It wasn't working only for positions beyond -3000 Y.

History:
f11cc1a0f2ceef5a98cc89bbdad51f08837e6333 - original fix
70a730c849d9b61c255b55254339c9e7c1f6c425 - addendum
5658387c3c4fbd26220c00df43f3a0b102fb2a45 - revert
ad0abf785eda5520637ff69b3faf1368bb6b0d0f - revert of revert
662613429017b722a4a1f11cc58394e22db3fdef - fix for positions beyond -3000 Y
