### ISSUE TITLE
Replace getTickCount with os.clock

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#408]
**Is your feature request related to a problem? Please describe.**
Can be related to [mantis 5115](https://bugs.mtasa.com/view.php?id=5115).

**Describe the solution you'd like**

Pending merge of #316, redirect getTickCount to os.clock.

Try one of these:

- Doing an assignment using the Lua API when we create functions
- Change Luadef for getTickCount to just call os.clock (don't do this, just unclean)
- Edit autoload Lua script to say `getTickCount = os.clock` (maybe don't do this, C is preferred)

**Comment by ccw808** [comment]
os.clock returns seconds, so cannot be used as a drop in replacement for getTickCount

**Comment by qaisjp** [comment]
And so it is!
