### ISSUE TITLE
Ped position not synced to server after falling through the ground

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#416]
**Describe the bug**

Slothman said:

> if a ped falls through the world and their position gets reset to the street, the server does not see the new position and reports the ped to be at its original coordinates.

**To Reproduce**

> Steps to reproduce the behavior:
>
> 1. spawn a ped
> 2. make the ped fall through the world and wait for it to respawn on a sidewalk
> 3. have the server report the peds position. it will no longer be accurate.

**Expected behavior**
That should not happen.

**MTA Client (please complete the following information):**
 - Version 1.0.4

**MTA Server (please complete the following information):**
 - Version 1.0.4

**Additional context**

@x86 said:
>  This is sometimes with vehicles and players too.

From https://bugs.mtasa.com/view.php?id=5840

**Comment by StifflersMom** [comment]
I can't reprouce this with Server v1.5.5-release-14280 and client v1.5.5-release-14273

**Comment by qaisjp** [comment]
Closing as @StifflersMom can't reproduce
