### ISSUE TITLE
Question about 'next' branch

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#417]
I see that some things have been merged to next and not master, though it's not on nightly.mtasa.com and I can't find any information on it any where else. I'm guessing next is going to serve a bit like how nightly.mtasa.com used to have unstable branch for new release and if so then we need next to be runnable if we are to test these new features.

**Comment by patrikjuvonen** [comment]
It hasn't been documented yet to Wiki but to get ahold of these branch builds you can navigate to https://nightlytest.mtasa.com and download a prebuilt package.

**Comment by qaisjp** [comment]
Next is an extremely temporary branch. It's just for features we don't want to merge into 1.5.6.

Once 1.5.6 has released we'll merge `next` into `master`, and delete `next`
