### ISSUE TITLE
Rename getVehicleSirensOn to areVehicleSirensOn

### ISSUE THREAD

**Issue by patrikjuvonen** [multitheftauto/mtasa-blue#426]
**Is your feature request related to a problem? Please describe.**
`getVehicleSirensOn` does not follow our function naming conventions.

**Describe the solution you'd like**
As per our naming conventions, `getVehicleSirensOn` should be renamed `areVehicleSirensOn`.

**Additional context**
- Issue originally noted by @qaisjp on the [Wiki article](https://wiki.multitheftauto.com/wiki/GetVehicleSirensOn) 15th of June 2014.

**Comment by moon91210** [comment]
Wouldn't it make make more sense to change it to getVehicleSirensState?

**Comment by patrikjuvonen** [comment]
I don't believe it does.

**Comment by moon91210** [comment]
You should be consistent with naming functions. Naming it getVehicleSirensState would be consistent with functions like getVehicleEngineState and getVehicleWheelStates as well as numerous other functions. Using _are_ wouldn't make any sense and would only complicate things.

**Comment by qaisjp** [comment]
I agree that `getVehicleSirenState` is probably a better name. The only other `are` function is https://wiki.multitheftauto.com/wiki/AreTrafficLightsLocked

**Comment by qaisjp** [comment]
tbh, there's not really a point changing this at all
