### ISSUE TITLE
Create shaders from raw data

### ISSUE THREAD

**Issue by Timic3** [multitheftauto/mtasa-blue#430]
**Describe the solution you'd like**
Like engine functions, where you can load raw data from DFF, TXD or COL files, it would be also nice to have this feature in dxCreateShader.

**Additional context**
From https://bugs.mtasa.com/view.php?id=9343. This issue was closed on Mantis and I couldn't find it here.
@qaisjp pointed out that it would probably require a refactor of CRenderItem.

**Comment by samr46** [comment]
Interesting request. I can make a PR. But should it support includes inside shader code?
