### ISSUE TITLE
dxDrawCircle: Incorrect rendering order

### ISSUE THREAD

**Issue by jushar** [multitheftauto/mtasa-blue#431]
**Describe the bug**
It seems that circles rendered via `dxDrawCircle` are always behind other dxDraw-calls.
See code below for reproduction steps.

**To Reproduce**
```lua
addEventHandler("onClientRender", root,
    function()
        dxDrawRectangle(100, 100, 300, 300, tocolor(255, 0, 0, 200))
        dxDrawCircle(150, 150, 100)
    end
)
```

**Expected behavior**
I expect the rectangle to be behind the circle. In reality, it's vice versa.

**MTA Client (please complete the following information):**
 - Version: 1.5.6
 - Running in Wine? No

**Comment by ccw808** [comment]
Circles need their own EDrawMode in CGraphics.cpp

**Comment by ghost** [comment]
Issue is related to #434. Check ccw's [comment](https://github.com/multitheftauto/mtasa-blue/issues/434#issuecomment-419728610) on how to render primitives properly with dxDrawPrimitive, which should be used for dxDrawCircle internally as it calls DrawPrimitiveUP.
