### ISSUE TITLE
dxDrawCircle: Not rendered at all if postGUI is enabled

### ISSUE THREAD

**Issue by jushar** [multitheftauto/mtasa-blue#432]
**Describe the bug**
If `postGUI` is set to `true`, circles are not rendered at all.

**To Reproduce**
```lua
addEventHandler("onClientRender", root,
    function()
        dxDrawCircle(150, 150, 100, 0, 360, tocolor(255, 255, 255), tocolor(255, 255, 255), 32, 1, true)
    end
)
```

**Expected behavior**
I expect a circle to be rendered

**MTA Client (please complete the following information):**
 - Version: 1.5.6
 - Running in Wine? No

**Additional context**
Maybe it's somehow related to #431

**Comment by codenulls** [comment]
This is bad. dxDrawPrimitive fixes this problem. We can pass the STL container of vertices to dxDrawPrimitive within dxDrawCircle call.

**Comment by ghost** [comment]
This is bad. dxDrawPrimitive fixes this problem. We can pass the STL container of vertices to dxDrawPrimitive within dxDrawCircle call.
