### ISSUE TITLE
dxDrawPrimitive doesn't enforce proper queue order

### ISSUE THREAD

**Issue by forkerer** [multitheftauto/mtasa-blue#434]
**Describe the bug**
As title suggest, currently primitives are drawn as separate queue after main drawing queue. It isn't necessarily wrong, but could be an issue for people that want to do layered stuff using the primitive drawer. It was done like that to make drawing performance better, as no render states have to be changed while processing all primitives. It can be countered by just replacing all other dxDraws with their primitive based version, but that would be a pain in the ass for most people. This issue will be most noticeable for people doing DX GUIs.

**To Reproduce**
```lua
dxDrawPrimitive(someArgs, ...)
dxDrawRectangle(someArg2, ...)
-- Primitive will draw over the rectangle
```

**Expected behavior**
Draw primitives and non primitives in order passed by script.

**MTA Client (please complete the following information):**
Latest nightly i guess.

**Additional context**
I can make a pull request that changes it to use single queue that other drawables use, but would need someone to approve that it is the correct solution to this problem.

**Comment by ccw808** [comment]
There already is an system to ensure 2D draws are done in the right order. The problem is dxDrawPrimitive is using the 3D draws method. (It seems to copying the way dxDrawLine3D operates). The solution would be to use the 2D method. e.g. Copy the way dxDrawImage/DrawTextureQueued/TileBatcher works
