### ISSUE TITLE
Add getCommandHandlers client-side

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#436]
I was looking the discord today and I saw that botder posted a code like this: https://pastebin.com/eTPH8ZwD

I was thinking of implementing something like that to my server, but i discovered an issue, getCommandHandlers() doesn't register the clientside ones, but onPlayerCommand triggers client-sided ones (and also some others like Say, Next, Toggle, Previous, etc)

You can still make a function like that work, with another table that has all the commands than also exists so it wont spam you whenever you change weapons or execute clientsided commands. Maybe we can get a clientsided version of this function.

If you can, please try to make this function to get the Client-sided commands too.

Thanks!

**Comment by patrikjuvonen** [comment]
It's because it's specifically a server-side function and would need to be implemented client-side as well. https://wiki.multitheftauto.com/wiki/GetCommandHandlers
