### ISSUE TITLE
CEF much laggier in 1.5.6

### ISSUE THREAD

**Issue by robsoncezario** [multitheftauto/mtasa-blue#438]
Ok, before 1.5.6 I had some perform issues with CEF related to multiple animations at sametime, that was lame but now it looks MUCH WORSE. My speedo make I lose 20FPS in 1.5.6. Compared to 1.5.5 sometimes my FPS was down of 100 to 96 MAX BUT RARELY. Now I get 82 FPS sometimes. 

all I do in my speedo is a transform to rotate the RPM circle and a KM/H change. Even life/gear or thigns like that are optimized and just change when needed. So its not a bad optimization or something

**Comment by Dutchman101** [comment]
Cannot reproduce the difference in FPS (tested with 2 PC's; fast and slower hardware configuration)

**Comment by robsoncezario** [comment]
Hello dutchman, could you tell me your PC config? Its a problem for me because my community use shitty cpu config in most cases. 

My whole team noticed the diff, I have a mid config hardware. I even use will-change to optimize those kinda of constantly changes but seems to not make a difference.

**Comment by Dutchman101** [comment]
Please upload the resource handling those animations/speedo to http://upload.mtasa.com/ and provide the link.
Additionally if possible, please collect and list hardware configurations of your affected players

**Comment by robsoncezario** [comment]
Hello, Dutch. Sorry but my speedo is not intended to be public. 

there's no animation on my speedo at all. Theres no transitions either. This is what being changed in onClientRender

`	executeBrowserJavascript(speedoBrowser, 
		'document.getElementById("speed").innerHTML = "' .. speed .. '";' ..
		'document.getElementById("gear").innerHTML = "' .. gear .. '";' ..
		'document.getElementById("odometer").innerHTML = "' .. mileage .. '";' .. 
		'document.getElementById("rpm").style.transform = "rotate(' .. angle .. 'deg)";'
	)`

this is enough to make me lose 20FPS drop diff from 1.5.5 to 1.5.6
 
and about animations I've related FPS drop with multiple animations (I mean like 2 animations being played at same time) even if they're just simple animations like scale or left top move 

I don't even use jQuery or any framework at all. Just pure JS and css

Just to notice my server has FPS limit 100.

Later I'm going to get other people specs mine is 4th gen i5, gtx 1050, 8gb ram

**Comment by Dutchman101** [comment]
I suggested http://upload.mtasa.com/ because it's not public, only MTA devs can access shared files.

Please provide us with the full resource of both speedo and the separate resource that features the animations FPS drop.

This is neccesary for a failsafe reproduction by us, as initial tests do not seem to confirm anything.

**Comment by qaisjp** [comment]
@Jusonex is there a specific commit that fixes this?

**Comment by Dutchman101** [comment]
> @Jusonex is there a specific commit that fixes this?

3b85dd6

quoting jusonex (on slack): update to chrome 76 fixes performance problems

besides the specifics of this issue probably being invalid (and that performance was less than ideal all along) which is now improved in general
