### ISSUE TITLE
playSound3D High FPS drop in 1.5.6

### ISSUE THREAD

**Issue by robsoncezario** [multitheftauto/mtasa-blue#439]
**Describe the bug**
playSound3D is causing a high FPS drop.

**To Reproduce**
I faced the problem with playSound3D in onClientWeaponFire, it wasn't happening in 1.5.5

**Expected behavior**
no FPS drop?

**Screenshots**

**MTA Client (please complete the following information):**
Version 1.5.6

**MTA Server (please complete the following information):**
Windows 10

**Comment by Dutchman101** [comment]
Cannot reproduce the difference in FPS (tested with 2 PC's; fast and slower hardware configuration)

**Comment by robsoncezario** [comment]
Today I tried it again and the fps drop was gone apologizes
