### ISSUE TITLE
Experimental features as a option? CEF

### ISSUE THREAD

**Issue by robsoncezario** [multitheftauto/mtasa-blue#440]
**Is your feature request related to a problem? Please describe.**
No, its not a problem just a awesome feature that's sadly missing.

**Describe the solution you'd like**
Enable experimental features

**Describe alternatives you've considered**
Experimental feature as a option

**Additional context**
I saw a guy asking to add the experimental features flag to CEF. I know you guys rejected and I understand parcially. But may I ask to reconsider the idea? Maybe make it as a option to enable it? Experimental flag is being used in rage and gt-mp and fivem at moment to draw nice UI.

**Comment by Woovie** [comment]
What exactly from the experimental feature set do you think would be beneficial to you having access to?

**Comment by robsoncezario** [comment]
Hello my friend theres 2 things that make a big difference in experimental features:
gaussian blur
conical gradient

Eclipse-RP have been holding a large community nowdays and uses gaussian blur on most system so I think theres no bugs about it. Theres alot of other german servers using gaussian blur in there systems too.

https://forum.eclipse-rp.net/uploadsnew/monthly_2018_08/unknown.png.aacd173362e22e73456d0f0e6eeeb738.png

**Comment by Woovie** [comment]
I'm not positive that we need to be using experimental features for gaussian blur. It is in Chrome already on the main branch, and it appears to work fine in my local install without activating it. Conical gradient still looks extremely new to Chrome even, and is in literally no other browser. I will bring this discussion up with the devs.
