### ISSUE TITLE
Segmentation fault (core dumped) in linux server

### ISSUE THREAD

**Issue by LukexM** [multitheftauto/mtasa-blue#444]
**Describe the bug**

"MTA:SA Server v1.5.6-r14370-release crash report.
2018-09-11 17:39
Caught 5 addresses ...

Backtrace:
#0 - ./x64/core.so(+0x693bd) [0x7f76421913bd]
#1 - ./x64/core.so(+0x8d588) [0x7f76421b5588]
#2 - ./x64/core.so(+0x8da3a) [0x7f76421b5a3a]
#3 - /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7f7642871330]
#4 - [0x49d0001]"

"Segmentation fault (core dumped)"

**To Reproduce**
In Editor, when i try to copy any object of the files that i have the server crashed 

**MTA Client (please complete the following information):**
 - Version 1.5
 - Running in Wine? No

**MTA Server (please complete the following information):**
 - OS: Debian Stretch
 - Version 1.5.6

**Comment by botder** [comment]
If this still happens, please create a new issue.
