### ISSUE TITLE
Crash: attaching a truck-trailer to a towtruck

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#445]
**Describe the bug**
when using attachTrailerToVehicle to attach a truck-trailer to a towtruck GTA crashes

**To Reproduce**
attaching a trailer to a towtruck via attachTrailerToVehicle

**Expected behavior**
no crash

**Screenshots**

**MTA Client (please complete the following information):**
 1.5.5

**MTA Server (please complete the following information):**
n/a

**Additional context**
https://bugs.mtasa.com/view.php?id=8668

**Comment by Dutchman101** [comment]
I just want to reference this fix in another branch: [https://github.com/patrikjuvonen/mtasa-blue/commit/3d1cf454d2a58e24504d4fe9c33396693655497e](https://github.com/patrikjuvonen/mtasa-blue/commit/3d1cf454d2a58e24504d4fe9c33396693655497e)

Is there any reason for it not to be ready yet, @patrikjuvonen?

**Comment by patrikjuvonen** [comment]
> I just want to reference this fix in another branch: [patrikjuvonen@3d1cf45](https://github.com/patrikjuvonen/mtasa-blue/commit/3d1cf454d2a58e24504d4fe9c33396693655497e)
> 
> Is there any reason for it not to be ready yet, @patrikjuvonen?

My fix is only partial as it fixes the crash but not what happens afterwards which is basically that the camera gets stuck somewhere on the map. Will need further work but haven't had the time to investigate entirely. Also my fix only takes into account towtrucks. Technically you can tow using any vehicle.

**Comment by Dutchman101** [comment]
> > I just want to reference this fix in another branch: [patrikjuvonen@3d1cf45](https://github.com/patrikjuvonen/mtasa-blue/commit/3d1cf454d2a58e24504d4fe9c33396693655497e)
> > Is there any reason for it not to be ready yet, @patrikjuvonen?
> 
> My fix is only partial as it fixes the crash but not what happens afterwards which is basically that the camera gets stuck somewhere on the map. Will need further work but haven't had the time to investigate entirely. Also my fix only takes into account towtrucks. Technically you can tow using any vehicle.

Ah, that's fine, i just asked the question for issue documentation.

Further documentation:
1) There has been another (test)fix applied for this crash in the past: [https://github.com/multitheftauto/mtasa-blue/commit/370e358b2c0b202de890e480fedf76a83ab3dbc3](https://github.com/multitheftauto/mtasa-blue/commit/370e358b2c0b202de890e480fedf76a83ab3dbc3)

^ Might shed a light on what's going on, @patrikjuvonen 
The crash continues to exist on same offset (gta_sa @ 002ac57c) after said fix. It may be a split cause (that only one of the causes leading to it has been fixed), but you could talk to @sbx320 for details about his investigation.

This crash is around #15th most popular SA crash. Servers that are affected should modify their scripts to stop doing things that trigger the issue; refer to bug description above.
