### ISSUE TITLE
onVehicleExplode triggers twice [server-side]

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#455]
**Describe the bug**
When you call blowVehicle and a player is in a vehicle, onVehicleExplode triggers twice.

**To Reproduce**
srun addEventHandler ( "onVehicleExplode", root, function ( ) outputChatBox "Triggered" end )
srun player = getRandomPlayer ( )
srun local x, y, z = getElementPosition ( player ); warpPedIntoVehicle ( player, createVehicle ( 429, x, y, z + 1 ) )
srun blowVehicle ( getPedOccupiedVehicle ( player ) )

**Expected behavior**
Not to be triggered twice.

**Screenshots**

**MTA Client (please complete the following information):**
1.3.4 last tested

**MTA Server (please complete the following information):**
1.3.4 last tested

**Additional context**
https://bugs.mtasa.com/view.php?id=7817
https://github.com/multitheftauto/mtasa-blue/pull/213

**Comment by patrikjuvonen** [comment]
Fixed by #1997
