### ISSUE TITLE
Bone positions and rotations are 1 frame lagging even when using onClientPreRender

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#465]
**Describe the bug**
(Moved from https://bugs.mtasa.com/view.php?id=8055 ) 
The bone positions seem to be 1 frame laggy. It seems that the ped rotation is set after onClientPreRender.

**To Reproduce**
1. Go to my server, SAAW World War II
2. Spawn with any class at any team
3. Aim your weapon and move the screen
4. Weapon position/rotation is 1 frame delayed
5. Use first Person mode to see it better ( /fps command ) 

I am using modified bone_attach, so you could easily reproduce it with that resource anywhere. 

Resource by Ren712:
https://bugs.mtasa.com/file_download.php?file_id=1105&type=bug

**Expected behavior**
Custom attachements onClientPreRender should not be delayed by 1 frame

**Video**
http://www.youtube.com/watch?v=U95ls5931lE

**MTA version 1.5.6 stable

**Additional context**
Ren712 reported that this bug only happens with AK47/M4 aiming (his report was MTA 1.3), but you can clearly see on my server that all weapons are affected, in fact, i think bone positions are updated too late in any case and it has nothing to do with weapons at all.

**Comment by ghost** [comment]
This one is pretty annoying. I've noticed it too with bone_attach resource, especially when you have weapons attached to bones, it looks even more horrible. I'll fix it soon.

**Comment by Einheit-101** [comment]
I think this should be a milestone for the next release.
