### ISSUE TITLE
setVehicleComponentRotation has no effect for some vehicle nodes

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#469]
**Describe the bug**
setVehicleComponentRotation has no effect if node controlled by GTA:SA.
For example - misc_a in ZR-350 (animated headlights), misc_b in Firetruck with ladder, wheels (wheel_rf_dummy, wheel_lf_dummy and etc).

**To Reproduce**
unstated

**Expected behavior**
unstated

**Screenshots**
unstated

**MTA Client (please complete the following information):**
unstated

**MTA Server (please complete the following information):**
unstated

**Additional context**
https://bugs.mtasa.com/view.php?id=7421
https://github.com/multitheftauto/mtasa-blue/pull/390

**Comment by qaisjp** [comment]
fixed by #390
