### ISSUE TITLE
setObjectBreakable is unreliable

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#483]
**Describe the bug**
Objects set as _unbreakable_ can still be broken.

**To Reproduce**
Xenius said:

> Example from mta wiki:
> ```
> function toggleObjectVulnerability()
> 	local object = createObject(3036, 1479.55078125, -1761.5847167969, 13.546875)
> 	if isObjectBreakable(object) then
> 		setObjectBreakable(object, false)
> 		outputChatBox("The object is now not breakable.")
> 	else
> 		setObjectBreakable(object, true)
> 		outputChatBox("The object is now breakable.")
> 	end
> end
> addEventHandler("onClientResourceStart", resourceRoot, toggleObjectVulnerability)
> ```
> If you hit this object, you can break it.

I tested with that object, punching it works as intended. Ramming it works as intended. Spawning a vehicle that lands on it causes it to break (falls through the ground, not into pieces)

**To reproduce**

- `crun setElementPosition(localPlayer, 1480.522, -1704.648, 14.047)`
- `crun a = createObject(3036, 1476, -1710, 14) setObjectBreakable(a, false)`

I noticed that adding this:

`crun addEventHandler("onClientObjectBreak", a, function() outputChatBox("broken") cancelEvent() end)`

And then when I make a car spawn on top of it and it falls through the ground `onClientObjectBreak` isn't even triggered.

**Expected behavior**
Object shouldn't be breakable.

**MTA Client (please complete the following information):**
1.5.2

**MTA Server (please complete the following information):**
1.5.2

**Additional context**
From https://bugs.mtasa.com/view.php?id=9293

**Comment by qaisjp** [comment]
_Walid\_ said:_

> I tried what you said and still working fine for me. (falls into pieces) even if i spawned a car on top of it.
> ```lua
> function toggleObjectVulnerability()
>    local position = Vector3(getElementPosition(localPlayer))
>    local object = createObject(3036,position.x,position.y,position.z+1)
>    setTimer(function()
>       setObjectBreakable(object, true)
>       outputChatBox("The object is now breakable.")
>    end,1000,1)
> end
> addCommandHandler("obj",toggleObjectVulnerability)
> 
> addEventHandler("onClientObjectBreak", root, 
> function() 
>    if getElementModel(source) == 3036 then
>       outputDebugString("broken")
>       cancelEvent()
>    end 
> end
> )
> ```

**Comment by PlatinMTA** [comment]
This also happens with 3034, setting it unbreakable doesn't do anything.

**Comment by lopezloo** [comment]
It doesn't break. It moves because it's dynamic object. If you want it to stay in position then you should use `setElementFrozen`.
