### ISSUE TITLE
onClientPlayerStuntFinish's stuntDistance always returns 0

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#484]
**Describe the bug**
onClientPlayerStuntFinish the stuntDistance parameter always returns 0.

**To Reproduce**
Use the example from http://wiki.mtasa.com/wiki/OnClientPlayerStuntFinish

**Expected behavior**
To not always return 0.

**Screenshots**

**MTA Client (please complete the following information):**
unstated

**MTA Server (please complete the following information):**
unstated

**Additional context**
From https://bugs.mtasa.com/view.php?id=5335

**Comment by qaisjp** [comment]
Callum said:

> The distance query for onClientPlayerStuntFinish only works when the player jumps out of the vehicle whilst doing the stunt. Otherwise (without jumping out) it always returns 0.
> 
> See video on YouTube: https://www.youtube.com/watch?v=FKBe0wJg_PM
>

**Comment by botder** [comment]
Fixed in 1f464d61c8c5f1400faa5472ccb67d2436d52903
