### ISSUE TITLE
After you abort entering a vehicle with a ped driver, you cannot enter other vehicles

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#485]
**Describe the bug**
After you abort entering a vehicle with a ped driver, you cannot enter other vehicles

**To Reproduce**
Create a ped:
- `run ped = createPed(101,0,0,0)`
- `run veh = createVehicle(411,0,0,0)`
- `run ped.vehicle = veh`
- `sp 0 0 2`
- enter the peds vehicle. You must abort the entering...
- After this you cant enter Vehicles...

**Expected behavior**
To be able to enter other vehicles still.

**Screenshots**
unstated

**MTA Client (please complete the following information):**
unstated

**MTA Server (please complete the following information):**
unstated

**Additional context**
https://bugs.mtasa.com/view.php?id=6114

https://github.com/multitheftauto/mtasa-blue/pull/58

**Comment by Zangomangu** [comment]
I believe this can be closed now

**Comment by qaisjp** [comment]
Fixed in 94c6aba300460199690b66a38b6db36f4fe63a20
