### ISSUE TITLE
Client 'isPedDead' returns 'false' when not yet spawned

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#487]
**Describe the bug**
Client version of function 'isPedDead' returns 'false' after client resource started. Server 'isPedDead' will returns 'true' in this case.

**To Reproduce**
It seems that you can't see a message about your own player in onPlayerJoin so had to srun isPedDead(getRandomPlayer()) and it does indeed return true whereas client side it returns false. Have no resources that spawn the player started.

**Expected behavior**
Return true when not yet spawned.

**Screenshots**

**MTA Client (please complete the following information):**
1.5.3

**MTA Server (please complete the following information):**
1.5.3

**Additional context**
https://bugs.mtasa.com/view.php?id=9496

**Comment by botder** [comment]
See PR #140
