### ISSUE TITLE
onClientExplosion does not get triggered when a barrel explodes

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#491]
**Describe the bug**
If a barrel explodes it is supposed to trigger the onClientExplosion event but it does not.

**To Reproduce**
Spawn a barrel object ID 1225 then try to blow it by either going into it by a vehicle or shooting at it.

- `crun addEventHandler("onClientExplosion", root, function() outputChatBox("explode") end)`
- `srun a = createObject(1225, getElementPosition(getRandomPlayer()))`

**Expected behavior**
Event should trigger.

**Screenshots**

**MTA Client (please complete the following information):**
1.5.3

**MTA Server (please complete the following information):**
1.5.3

**Additional context**
From https://bugs.mtasa.com/view.php?id=9506

**Comment by CrosRoad95** [comment]
CObject::Explode(void)
offset: 0x5A1340
is executed if object explode
