### ISSUE TITLE
Moving in opposite direction stops the player from moving

### ISSUE THREAD

**Issue by PwN3RB0T** [multitheftauto/mtasa-blue#500]
This bug ONLY occurs on foot:
For example pressing W and S afterwards, makes the character stop immediately, which makes it impossble for run-weapon (Sawnoff-Uzi) players to play properly. You just have to press the opposite-direction key and the player will stop walking/running.

**Comment by ghost** [comment]
A workaround for the problem by Vektor: https://gist.github.com/saml1er/3f744edc2b13f2a784aef6afac118000

**Comment by ghost** [comment]
This can be fixed in Lua. Should we fix it in MTA? @qaisjp

**Comment by PwN3RB0T** [comment]
> This can be fixed in Lua. Should we fix it in MTA? @qaisjp

Yes it can but if you test every single key-combination with the movement-keys you will realize that it has issues where the running-direction is STUCK like this and the character will move even when you don't press any key anymore..please fix this bug in MTA with high priority. I was promised that this will be done in December 2018 already :/ Many people (specially those who play runnies weapons like Sawnoff and Uzi) will see this as a MAJOR BUG. How am I supposed to play MTA when I can't even move properly. Pople like me are used to the SA-MP movement where you can press any key any time with any combination and it works - switching to MTA makes it impossible to play

**Comment by qaisjp** [comment]
> Should we fix it in MTA?

Yes. gta_sa itself applies the following order of precedence:

- `right > left` (no matter what, move right if `right` is pressed, even if `left` is pressed)
- `down > up`

Personally I think a "last pressed" order of precedence would be better, though. i.e. if you hold right and then hold left, you will move left. when you let go of left, you will move right.

**Comment by PwN3RB0T** [comment]
> > Should we fix it in MTA?
> 
> Yes. gta_sa itself applies the following order of precedence:
> 
> * `right > left` (no matter what, move right if `right` is pressed, even if `left` is pressed)
> * `down > up`
> 
> Personally I think a "last pressed" order of precedence would be better, though. i.e. if you hold right and then hold left, you will move left. when you let go of left, you will move right.

Yes I agree this would be indeed much better

**Comment by ghost** [comment]
@PwN3RB0T @qaisjp Okay, I'll do it.
