### ISSUE TITLE
Cannot move sideways while aiming when FPS is higher than ~75

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#502]
**Describe the bug**
This is a well known bug that annoys alot of people.

**To Reproduce**
1. Set FPS limit to any value above 73 (74-100)
2. Get (for example) a deagle
3. Aim and keep aiming, then try to move sideways without moving forward or backward
4. The character will not move or it takes a while until he starts moving

**Expected behavior**
FPS should have no impact on gameplay

**Multi Theft Auto v1.5.6-release-14394**
 
**Additional context**
The original bug report was about 48 fps but problems start happening at 73 fps for me, it gets worse with even more fps.

From https://bugs.mtasa.com/view.php?id=4291

**Comment by martonp96** [comment]
```cpp
	// Fix walk weapons strafe with high fps

	static float FixedDeltaMoveCommand = 10.1f;

	patch::SetPointer(0x61E0C0 + 2, &FixedDeltaMoveCommand);

	patch::Nop(0x61E0CA, 0x6); // nop multiplying by 0.07
```
^that fixes this problem
@saml1er

**Comment by ghost** [comment]
Hmm, for how long do I have to aim before I start moving sideways? I'm unable to reproduce the problem. I don't think I understand it. I set my FPS to 100, and I still can't see much difference.

**Comment by Haxardous** [comment]
> Hmm, for how long do I have to aim before I start moving sideways? I'm unable to reproduce the problem. I don't think I understand it. I set my FPS to 100, and I still can't see much difference.

set your FPS to 70+(e. g. 71) you'll notice the character getting frozen for a while when aiming & walking in any direction with a weapon, it even works with Rocket Launcher's & snipers(anything aim-able actually).

-----------------------

from that older mantis post(https://bugs.mtasa.com/view.php?id=4291):
> ah, this bug with <latency_reduction>1</latency_reduction>
> 
> if latancy_reduction disable all OK.

I can't reproduce this, it works completely casual with/without having that option on.

**Comment by Haxardous** [comment]
Seems like you can actually move above that framerate by trying to move your cursor and move with AWSD/move buttons, also even if you succeed the moving animation will be "flickering"

**Comment by Dutchman101** [comment]
As server owners dealing with this issue regularly end up here, i want to share this script workaround:
[https://forum.mtasa.com/topic/129649-rel-script-to-fix-strafing-walking-sidewards-bug-on-high-fps-move-with-a-gun-on-100-fps/](https://forum.mtasa.com/topic/129649-rel-script-to-fix-strafing-walking-sidewards-bug-on-high-fps-move-with-a-gun-on-100-fps/)

Then you can use higher FPS limits without worrying about this bug until it's fixed
