### ISSUE TITLE
Network trouble if falling into water while attempting to enter a vehicle

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#521]
**Describe the bug**
If you fall in water whilst attempting to enter a vehicle, when you reach land again you'll get a short Network Trouble message. This is followed by a warp back to your original position when you first pressed the enter key.

**To Reproduce**
- put a vehicle near a cliff over some water
- attempt to enter it (make sure the auto route will let you fall down in the water)
- swim to the closest land you can stand on

**Expected behaviour**
Not to get network trouble.

**Additional context**
From https://bugs.mtasa.com/view.php?id=7951

**Comment by Zangomangu** [comment]
#1680 

These two are the same issue
