### ISSUE TITLE
Zoom in/out binds are inverted

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#524]
**Describe the bug**
Well, basically in the 'Bindings' tab in 'Settings' the 'Zoom in' and 'Zoom out' bindings are named incorrectly, they should be switched.

Apparently 'Zoom in' is meant to decrease the field of view, whilst 'Zoom out' is meant to increase the field of view, it is like this in Single Player.

**To Reproduce**
Get sniper rifle, aim it, use zoom stuff.

**Expected behavior**
To zoom the right way.

**Screenshots**

**MTA Client (please complete the following information):**
Unstated.

**MTA Server (please complete the following information):**
Unstated.

**Additional context**
From https://bugs.mtasa.com/view.php?id=4781

**Comment by ricksterhd123** [comment]
From MantisBT:
2009-08-10 15:05 Flobu:
pageup zooms out but mouse_wheel_up zooms in

Only the alternate binds are switched so the solution might not be that simple.
