### ISSUE TITLE
Water elements are unable to change interiors

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#528]
**Describe the bug**
I am unable to change the interior of any custom water element. Maddogg's mansion has water elements that are swimable in, and it's an interior!

**To Reproduce**
```
run water = createWater ( 1866, -1444, 10, 1968, -1442, 10, 1866, -1372, 10, 1968, -1370, 10 )
run water.interior = 1 -- still exists in int 0, invisible in int 1
run water.interior -- returns 1
```
**Expected behavior**
To change interior.

**Additional context**
From https://bugs.mtasa.com/view.php?id=4892

**Comment by botder** [comment]
See also issue #527

**Comment by patrikjuvonen** [comment]
Duplicate of #527
