### ISSUE TITLE
setElementVisibleTo doesnt works correctly in some case

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#548]
**Describe the bug**
You cant set invisible a element to one player (except if you set visibility for root to false and then set visible to all player except one)

the second example @ https://wiki.multitheftauto.com/wiki/SetElementVisibleTo indicates that this should work.

**To reproduce**
- `srun x,y,z = getElementPosition(getRandomPlayer())`
- `srun m = createMarker(x,y,z,'corona')`
- `srun setElementVisibleTo (m,getRandomPlayer(),false)` --> still visible

**Expected behaviour**
To make it invisible to specified elements.

**Screenshots**

**MTA Client:** 
 - Version: 
 - Running in Wine? 

**MTA Server:** 
 - Version 
 - OS: 

**Additional context**
Add any other context about the problem here

From https://bugs.mtasa.com/view.php?id=8487

**Comment by FileEX** [comment]
it will be work:

srun x,y,z = getElementPosition(getRandomPlayer())
srun m = createMarker(x,y,z,'corona')
srun setElementVisibleTo(m,getRandomPlayer(),true) -- will return true
srun setElementVisibleTo (m,getRandomPlayer(),false) -- marker will be hide (if getRandomPlayer() will be the same)

**Comment by qaisjp** [comment]
@FileEX you can use `me` to refer to yourself

**Comment by qaisjp** [comment]
Duplicate of https://bugs.mtasa.com/view.php?id=4423
