### ISSUE TITLE
Building DFF replacement doesn't work when close to object

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#550]
**Describe the bug**
Replacing original GTA's building with custom model is imposible when you are close to it and sometimes fails when you see LOD (depends on object). Function returns true but client still see old building on mta. Although mta object has the right model (the custom one).

**To reproduce**
- Get close to building on screenshot
- Replace 10052 model with custom dff,txd and col (command /replace)
- Create 10052 object and see the difference (command /obj)
- Restore 10052 model if you want (command /restore)

[replace_bug.zip](https://github.com/multitheftauto/mtasa-blue/files/2406253/replace_bug.zip)

(Confirmed, and if you leave the area and come back, it gets applied.)

**Expected behaviour**
For the mod to apply when nearby it.

**Screenshots**
Example in map editor (original GTA object and MTA created one):

![image](https://user-images.githubusercontent.com/923242/45894645-eb150e00-bdc6-11e8-8d20-ab99be46b2e3.png)

**MTA Client:** 
 - Version: 
 - Running in Wine? 

**MTA Server:** 
 - Version 
 - OS: 

**Additional context**

From https://bugs.mtasa.com/view.php?id=8087

**Comment by Vadya963** [comment]
![mta-screen_2021-01-18_19-22-55](https://user-images.githubusercontent.com/38101660/104920926-2772cc00-59cb-11eb-911d-d891c7bd0a23.png)
well replaced, no problem

**Comment by Vadya963** [comment]
https://wiki.multitheftauto.com/wiki/EngineRestreamWorld
for such cases, this function was added, I did not use it

**Comment by PlatinMTA** [comment]
I think that this was fixed on #1735
