### ISSUE TITLE
Impossible to stop helicopter rotor if it has a driver

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#552]
**Describe the bug**
Using setHelicopterRotorSpeed will stop it but then it will start spinning again.

**To reproduce**
Drive a helicopter.
setHelicopterRotorSpeed(localPlayer.vehicle, 0)

**Expected behaviour**
Well it'd be nice if the rotor would stay not spinning maybe if engine state was set to off, though I haven't checked to verify it doesn't.

**Screenshots**

**Version**
Unstated at mantis.

**Additional context**

From https://bugs.mtasa.com/view.php?id=6105

**Comment by PlatinMTA** [comment]
I just comment to say that indeed, the rotor does not stop even if the engine is set to off. I saw it on my RP server a couple of times.
