### ISSUE TITLE
createTrayNotification not working for Windows 10

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#580]
**Describe the bug**
function createTrayNotification doesn't pop out notification text in balloon when client runs Windows 10. Only on Windows XP, 7 and 8.1 it works.

The MTA app icon will appear in the taskbar without showing any dialogue, when the function is triggered including a notification text that's supposed to show.

**To reproduce**
crun setTimer(function() createTrayNotification( "Hello World", "default", false ) end, 2000, 1)

**Expected behaviour**

**Screenshots**

**Version**

**Additional context**
We figured out that the problem was the main GTA window is not 100% unicode compatible.
Solutions are:
a) Use non-unicode tray notifications
b) Hook GTA to create main unicode window at startup (might not be possible)
c) Create an extra hidden unicode window to use for tray notifications

Isn't a dummy window created to handle non-blocking window drags? Maybe that window could be used to create notifications?

From https://bugs.mtasa.com/view.php?id=9447

**Comment by rambolger** [comment]
I am offering a 10€ bounty for this issue to be solved.
