### ISSUE TITLE
Getting folders and files in path

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#610]
**Is your feature request related to a problem? Please describe.**
I want get content of directory, i can't do this in mta ( without modules ) and completly impossible clientside.

**Describe the solution you'd like**
Make function that return folders and files in path

**Describe alternatives you've considered**
no alternatives

**Additional context**

https://github.com/multitheftauto/mtasa-blue/pull/141

**Comment by Samake** [comment]
As i remember those sort of functions and features are disabled for
security reasons. Nobody has to know what types of files and content is
located on any client computer folder. I dont think that´s planned to bring
this ability to mta cause its a big door opener for doing really bad things.

Am Fr., 28. Sep. 2018 um 16:11 Uhr schrieb CrosRoad95 <
notifications@github.com>:

**Comment by CrosRoad95** [comment]
not clientside, but only serverside should be enabled

**Comment by ghost** [comment]
I think it should be implemented serversided only (with acl permission ofcourse) and ONLY in mta resources - nothing outside resources folder. This might be good for some sort of Multigaming servers which have tons of maps (loading map cache, caches in general).

- Luxy.c

**Comment by LilDolla97** [comment]
A module for that already exists.

Link: https://wiki.multitheftauto.com/wiki/Modules/FileSystem

**Comment by ghost** [comment]
Yeah but i think that a module for that is kinda "stupid"

- Luxy.c
