### ISSUE TITLE
onClientLocalizationChange

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#619]
**Is your feature request related to a problem? Please describe.**
So, I'd need this event called 'onClientLocalizationChange' for my multi-lang server. This event should be triggered every time the player changes the language of the UI.
The first argument should be the new localization code, and the second one could be the old one.

**Describe the solution you'd like**
Just add a new event called 'onClientLocalizationChange'

**Describe alternatives you've considered**
I can do it in lua with onClientRender(or a timer) but thats just stupid.

**Comment by ccw808** [comment]
Localization can not be changed when connected to a server, so the event would never be triggered
