### ISSUE TITLE
Using guiGridListSetItemText with already exists row will reset the row font to the default

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#622]
**Describe the bug**
guiSetFont change the font of all rows in the grid list, however when an already exists row text changed with guiGridListSetItemText its font will reset to the default while the font of the rest of the rows will remain the same.

Also guiSetFont won't have any effect to any row afterwards.

**To reproduce**
```lua
local x, y = guiGetScreenSize()

gridList = guiCreateGridList((x-200)/2, (y-200)/2, 200, 200, false)
guiGridListAddColumn(gridList, "Test", 0.9)
guiSetFont(gridList, "default-bold-small")


for i=0, 10 do
	guiGridListSetItemText(gridList, guiGridListAddRow(gridList), 1, "#"..i, false, false )
end

addCommandHandler("xx",
function()
	for i=0, 5 do
		guiGridListSetItemText(gridList, i, 1, "#"..i, false, false)
	end
end)
```
Run that then do /xx.

**Expected behaviour**
For the font that was set on the GUI element to be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/253404/46255969-1620f100-c49c-11e8-9b02-8391aa227528.png)

**Version**
Both v1.5.6-release-14414

**Additional context**

From https://bugs.mtasa.com/view.php?id=9080

**Comment by FileEX** [comment]
If you set 'section' parameter to true, font will be 'default-bold-small'.

**Comment by qaisjp** [comment]
I used a modified version of this script:

```lua
local x, y = guiGetScreenSize()

gridList = guiCreateGridList(x-600, (y-200)/2, 200, 200, false)
guiGridListAddColumn(gridList, "Test", 0.9)
guiSetFont(gridList, "default-bold-small")
showCursor(true)

for i=0, 7 do
	local text = "#" .. i
	local isSection = i == 2 or i == 1
	if isSection then
		text = "section"
	end
	guiGridListSetItemText(gridList, guiGridListAddRow(gridList), 1, text, isSection, false )
end

addCommandHandler("xx",
function()
	for i=0, 5 do
		local text = guiGridListGetItemText(gridList, i, 1)
		if i == 1 then
			text = "not section"
		end
		guiGridListSetItemText(gridList, i, 1, text .. " (modified)", i == 2, false)
	end
end)
```

and also tested with line 5 commented out (guiSetFont)
