### ISSUE TITLE
Exports should transfer metatables and functions

### ISSUE THREAD

**Issue by moon91210** [multitheftauto/mtasa-blue#633]
**Is your feature request related to a problem? Please describe.**

You should be able to export classes from one resource to another.

**Describe the solution you'd like**

I'd like to be able to import my own classes like this:
```lua
local InfoMarker = exports.infomarkers

local jobMarker = InfoMarker.new(211.05, 100.0, 3)

jobMarker:setInfo('Press X to apply for this job.')

jobMarker:onKey('x', function(player)
    outputChatBox('Congratulations with your new job', player, 0, 255, 0)
end)
```

Alternatively there could be a global import function which can load in functions/classes from other resources as long as those resources are exporting them in some way.

**Describe alternatives you've considered**

I have made my own utils class before which I then imported with exports where I triggered a function and got back an import function in a string, which I then loaded in with loadstring.

I have tried BakaGaijin (http://anirudh.katoch.me/project/bakagaijin/)

**Comment by jushar** [comment]
It's not possible to implement this in a performant way. From my point of view, having such a functionality would imply the opposite.

**Comment by CrosRoad95** [comment]
mta could suport magic method like __mtapack __mtaunpack which are used to transfer such thing across resources, client <-> server,
example you have
```lua
function Vector2:__mtapack()
  return {self.x,self.y}
end
function Vector2:__mtaunpack(packedVector)
  return Vector2(packedVector[1], packedVector[2])
end
```
exports, trigger automaticly will use this

and for it you attach information what is this

**Comment by jushar** [comment]
Implementing that is more complicated than it might seem at first glance. The main challenge is to map corresponding types on the server and client (i.e. how do you know that the table `Vector2` on the server is `Vector2` on the client) and what happens across resource boundaries.

I again think it's better to solve this problem with a new type of resources that run in the same Lua VM as the calling resource.
