### ISSUE TITLE
Breakdown of client CPU usage

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#635]
**Is your feature request related to a problem? Please describe.**
Players including myself getting unstable and low FPS with unknown causes. I can play GTA V and get a stable 60 FPS but can't get that on MTA in a busy area. The script CPU usage may only add up to 20% but the core is on full load and there's no way to know what features (such as object mods) are using the rest up.

**Describe the solution you'd like**
So if this is possible, something like '/showmemstat' but for CPU usage with a list of main things that are done each frame and how much time was spent doing each of those things, so that server owners can diagnose poor performance which is not caused directly by scripts as there is performance browser for that (this could be a new tab in performance browser or it could be like '/showcpustats'). Also maybe this would be useful for anyone working on developing MTA.

**Describe alternatives you've considered**
I've tried disabling certain features and then using trial and error to see what uses what but it's just such an unreliable and frustrating method.

**Additional context**
I have made a list of example things which could be in the list:

    Misc. MTA (Miscellaneous MTA stuff like player join)
    Misc. GTA (Miscellaneous GTA stuff that isn't in this list)
    Lua Scripts (All time spent on Lua stuff)
    Shaders (Does this use some CPU as well as GPU?)
    DX (Time spent rendering DX stuff)
    ColShapes (Time spent processing colshape stuff)
    Objects (Time spent processing object collisions)
    Vehicles (Time spent processing vehicle collisions)
    Peds (Time spent processing ped collisions)
    GTA Audio (Time spent on GTA audio if possible)
    MTA Audio (Time spent on MTA created sounds)
    CEF (Time spent on CEF stuff)
    Clothes (Time spent processing clothes if possible)
    GTA FX (Time spent on effects such as smoke)
    Files (Time spent opening files etc)
    GUI (Time spent processing CEGUI stuff)
    Lights (Maybe time spent on the GTA lights)
    Markers (Maybe time spent on markers)
    Pickups (Maybe time spent on pickups)

This would be useful because in the past we had an object mod, all it was were some sandbags yet the collision model of the object was so complex a few of these objects could cause a significant FPS drop to nearby players but we almost missed this as the cause. If there was '/showcpustats' and it displayed how much time was spent by GTA SA processing object collisions we'd be able to see that it was the problem.

I think the main CPU problem is that GTA SA seems to process collisions inefficiently because:

crun for i=1, 200 do createPed(1, getElementPosition(localPlayer)) end -- Gives me 15 FPS.

crun for i=1, 200 do setElementCollisionsEnabled(createPed(1, getElementPosition(localPlayer)), false) end -- FPS stays at 60.

**Comment by ccw808** [comment]
We have /showframegraph. Maybe someone can adapt that to also show collision timings

**Comment by ArranTuna** [comment]
I just saw a file in my MTA directory called timings.log which seemed to log something like this:

16:33:36.717 - Started timing checkpoints [Ver:1.5.6-9.14664] [Date:2018-10-29]
16:33:42.050 - >Detected slow frame: 61ms    (Prev frame was 20ms)  (Game time 00:15)
16:33:42.051 -     Frame slow points: [CallIdle1 53ms (calls:1)]   [CallIdle2 7ms (calls:1)]   [CClientGame::DoPulses 6ms (calls:1)]   [pcall 5ms (calls:39)]   
16:33:49.746 - >Detected slow frame: 74ms    (Prev frame was 25ms)  (Game time 00:15)
16:33:49.747 -     Frame slow points: [CallIdle1 16ms (calls:1)]   [CallIdle2 13ms (calls:1)]   [OnPresent2 8ms (calls:1)]   [CClientGame::DoPulses 5ms (calls:1)]   
16:33:49.748 - Stopped timing checkpoints

**Comment by Pirulax** [comment]
Options -> Advanced -> Debug: Log Timing

**Comment by ghost** [comment]
> 
> crun for i=1, 200 do createPed(1, getElementPosition(localPlayer)) end -- Gives me 15 FPS.

It gives you low fps because you created peds in the same location. This is avoidable. Moreover, you have already explained the problem to me, so we'll continue the conversation in #905.
