### ISSUE TITLE
onPlayerJoin source variable incorrect if passed as 'self'(so, to a class method)

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#637]
**Describe the bug**
So, I attached an event handler to 'onPlayerJoin' event, that was fine, but..
I have a function called Player.assignID(), which is called from the function 'onPlayerJoin' calls, there I, you guessed it, set a playerID, which'd work fine, in principle, but in practice it doesn't, it simply doesn't...

**To reproduce**
[onPlayerJoin_bugtest.zip](https://github.com/multitheftauto/mtasa-blue/files/2452264/onPlayerJoin_bugtest.zip)

**Expected behaviour**
I'd expect my element data to be set properly(if you do self:getData("id") it'll print the id, but, if you try the same with player:getData("id") in the timer it'll output false.

**Version**
Client: Multi Theft Auto v1.5.6-release-14640
Server: same

**Comment by botder** [comment]
![image](https://user-images.githubusercontent.com/38703318/46568745-7d322000-c94a-11e8-901d-a804a42cc10e.png)
![image](https://user-images.githubusercontent.com/38703318/46568749-8e7b2c80-c94a-11e8-91f5-cb57f9e865eb.png)

Please update your server and client and try again.

**Comment by Pirulax** [comment]
That's interesting, it works for me too now, but it wasn't before, so I'll try to reproduce it too.
Btw, if I copy+paste my code from Player.assignID directly into the function that onPlayerJoin calls then, it works as intetned.

**Comment by botder** [comment]
Since the issue cannot be reproduced with the provided nor debug client/server, I will close the issue. If you encounter this problem again, then open a new issue and reference this one.
