### ISSUE TITLE
Script load fail messages no longer pass to onDebugMessage

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#639]
**Describe the bug**
When a script fails to load, onDebugMessage does not trigger with the info even though it used to and it does show up in debug script.

**To reproduce**
1. /debugscript 3
2. srun addEventHandler("onDebugMessage", root, function(msg, lvl, file, line) outputDebugString("you won't see this") end)
3. Add something like ==== to any script and restart it.
4. Observe a ERROR in debugscript but no debug message saying "you won't see this".

**Expected behaviour**
I'm certain that this used to appear because I have a script that logs debugs to a web page and on IRC chat and so I could do scripting from IRC and would see load fails but now I don't see the load fails any more.

**Version**
Server v1.5.6-release-14414

**Additional context**

**Comment by botder** [comment]
I hope the commit fixed the issue above.
