### ISSUE TITLE
ProcessLineOfSight returns with UV Coords

### ISSUE THREAD

**Issue by grzcrown** [multitheftauto/mtasa-blue#645]
The function ProcessLineOfSight should return with the elements UV coordinate where the hit was detected. It would be very helpful when using shaders and render targets. Of course, that will only work with correct UV Maps.

**Comment by CrosRoad95** [comment]
impossible, because collision ( .col file ) doesn't contain UV maps

**Comment by botder** [comment]
Please use the "Feature request" issue template next time.

**Comment by Pirulax** [comment]
It is possible by doing a ray-cast against the `RpClump` of the entity hit.
