### ISSUE TITLE
New function: testSphereAgainstWorld

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#646]
**Is your feature request related to a problem? Please describe.**
Nothing to describe, simillar to processLineOfSight but instead of a line, it tests the sphere
This could be helpful for fancy scripts.

**Describe the solution you'd like**
/

**Describe alternatives you've considered**
/

**Additional context**
int __cdecl CWorld::TestSphereAgainstWorld(CVector sphereCenter, float sphereRadius, CEntity *ignoreEntity, char buildings, char vehicles, char peds, char objects, char dummies, char doIgnoreCameraCheck)

offset 0x00569E20

**Comment by Einheit-101** [comment]
Whoa whoa whoa, hold on :o
Nice. Is performance similar to 1x processLineOfSight?

**Comment by Pirulax** [comment]
seems interesting, wonder why it wasnt added in the first place?
Anyways, heres the corrected prototype:
```c
int __cdecl CWorld__TestSphereAgainstWorld(CVector sphereCenter, float sphereRadius, CEntity *ignoreEntity, bool buildings, bool vehicles, bool peds, bool objects, bool dummies, bool doIgnoreCameraCheck)
```
Also, seems like this function is like `isLineOfSightClear`(not `processLineOfSight`). It doesnt return any info about where it hit or anything.

**Comment by Proxy-99** [comment]
#3787
