### ISSUE TITLE
playSound3D don't support setSoundPosition

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#650]
**Describe the bug**
setSoundPosition don't work at sound which is created with playSound3D. Only don't work if path is URL.

**To reproduce**
```lua
local x,y,z = getElementPosition(localPlayer)
local snd = playSound3D('music.mp3',x,y,z,false,false)

addCommandHandler('ps',function(cmd,p)
    setSoundPosiiton(snd,p) -- will return true but don't change position
end)
```

**Expected behaviour**

**Screenshots**

**Version**
1.5.6

**Additional context**
3D sounds don't support setSoundPosition

**Comment by CrosRoad95** [comment]
`setSoundPosiiton` i think you make typo in function name, should be `setSoundPosition`
or, you pass string as position, and script could not be able to convert it to float

**Comment by FileEX** [comment]
Yes, it setSoundPosition, my mistake on github :P

**Comment by FileEX** [comment]
And the same code with playSound instead playSound3D will work.

**Comment by ghost** [comment]
Its working just fine - cant reproduce it.
The only thing i've noticed: When passing an invalid position argument to it, it will start from 0 instead of returning false

```lua
local uSound = false

addEventHandler("onClientResourceStart", resourceRoot, function()
    uSound = playSound3D("music.mp3", 0, 0, 3.5, true)
end)

addCommandHandler("ssp", function(strCMD, position)
    outputChatBox("Seting sound position: " .. tostring(setSoundPosition(uSound, position)))
end)
```

- Luxy.c

**Comment by FileEX** [comment]
So playSound3D don't support setSoundPosition only if path is url instead file. I use release, and i was tested it on URL, i wasn't tested it on file path.

**Comment by ghost** [comment]
Oh, sorry - yeah - it`s obviously that you cant change the sound position of a stream because it would require MTA to cache the song locally. For streams, it should return false.

- Luxy.c

**Comment by FileEX** [comment]
But i can change the sound position of a stream, only in playSound :P So this don't work only on playSound3D

**Comment by ghost** [comment]
I've tested it with playSound and also with playSound3D - streamed songs (ex: podcasts) wont work for both.

- Luxy.c

**Comment by FileEX** [comment]
Convert music from yt and use download url as sound url. With playSound it work and can change position, but with 3D don't work.

**Comment by Einheit-101** [comment]
What does setElementPosition() do with the streamed sound?

**Comment by FileEX** [comment]
I mean playback position instead position as sound element. With playSound it work, with playSound3D it don't work.

**Comment by jushar** [comment]
(Not) fixed in https://github.com/multitheftauto/mtasa-blue/commit/fa4cbe62511bcf2778699c152dbf43bce003f99f
