### ISSUE TITLE
MTA:SA Server v1.5.6-r14489-release crash report

### ISSUE THREAD

**Issue by haron4igg** [multitheftauto/mtasa-blue#652]
**Describe the bug**
At first crash appeared today at v1.5.5-11747 version, after more than 3 months of runtime. After first crash, i updated server to 1.5.6, all the resources and db's remain the same as before the crash, i started server and its crashed just after 15 minutes. I tried one more time, result was the same. The dump files in attachment.

[Crash.zip](https://github.com/multitheftauto/mtasa-blue/files/2476723/Crash.zip)

**Version**
- v1.5.6-r14489
- Some Linux distributive. (classified by hosting)

**Additional context**
 I have other servers which are running exactly the same resources but still on 1.5.5 ver of server. The only difference between them - is the players progress (database) So probably this could be related to same in-game situation with some script. There are plenty of them, so i have no idea where to look. This is the first incident during last 5 years. Last resources update was at July. 6 more servers are still running with same resources since July, without restarts. I hope somebody could suggest where to look, based on crash dumps.

**Comment by ccw808** [comment]
Try using build from https://linux.mtasa.com/

**Comment by haron4igg** [comment]
@ccw808 already created request to update binaries on hosting... and i also was thinking that it could be related to Matrixes crash, fixed not so long ago. But i'm not using matrixes on server side, only on client. And also it is not explaining the first crash accident on 1.5.5 ver. 

Meanwhile, server without players stands for more then 20 minutes so far. So it is happened due to some in-game situation. Is it possible to get any info from dump, so i can narrow the search?

**Comment by ccw808** [comment]
Looks like a crash in getElementMatrix with a ped element

**Comment by haron4igg** [comment]
@ccw808 so, it means that r14493 will fix the issue on 1.5.6. But what caused initial crash on 1.5.5 then?...((
probably we will never know the answer :(

**Comment by haron4igg** [comment]
Last crash was fixed by update, but reason of the first one is unknow, so will close ticket for now.
