### ISSUE TITLE
Add bCache to dx* functions

### ISSUE THREAD

**Issue by Pirulax** [multitheftauto/mtasa-blue#661]
**Is your feature request related to a problem? Please describe.**
So, since, most of the time, you don't actually want to re-add something to the drawing queue, but just have it on the screen, like a guiLabel, adding a bCache option to dx* functions'd be a very neat feature.

**Describe the solution you'd like**
Adding a bCache option to dx* functions'd be a very neat feature.
If bCache is enabled then the function should return an element, which should point to the specific queue item.
Maybe, also add some functions like setPosition, setRotation too(so, we can still do animations with them without the need of re-adding them to the queue.)

**Describe alternatives you've considered**
Just keep using render targets all over the place, thus wasting vram.

**Comment by CrosRoad95** [comment]
render targets not enough ?
