### ISSUE TITLE
Wrong warning in executeBrowserJavascript

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#662]
**Describe the bug**
If you use executeBrowserJavascript(arg1) function and the browser as the first argument does't exist, an error "Expected texture at argument 1, got X" is shown. There's should be warning "Expected browser at argument 1, got X".

**To reproduce**
1. /debugscript 3
2, executeBrowserJavascript("test")
3, Look at debug

**Expected behaviour**
There's should be warning "Expected browser at argument 1, got X".

**Screenshots**
-

**Version**
Multi Theft Auto v1.5.6-release-14664.4

**Additional context**

**Comment by qaisjp** [comment]
This happens to other functions as well (focusBrowser, getBrowserTitle)
