### ISSUE TITLE
add function to generate string, lorem ipsum

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#671]
**Is your feature request related to a problem? Please describe.**
Helps with debugging things that need put long string

**Describe the solution you'd like**
add function that generate string, lorem ipsum

**Describe alternatives you've considered**
copy&paste string from random website

**Additional context**
/

**Comment by botder** [comment]
A decent code editor should be able to paste lorem ipsum text from a predefined snippet. See https://code.visualstudio.com/docs/editor/userdefinedsnippets.
