### ISSUE TITLE
line spacing in dxDrawText

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#677]
**Is your feature request related to a problem? Please describe.**
it's hard to fit text in gui if you wanna use one dxDrawText, you have to use two of them or more for each line

**Describe the solution you'd like**
add line spacing argument for dxDrawText

**Describe alternatives you've considered**
draw multiple dxDrawText at once, one for each line

**Additional context**
/

**Comment by botder** [comment]
Duplicate of #611?

**Comment by CrosRoad95** [comment]
yes, my mistake
