### ISSUE TITLE
Debug/chat messages are not consistent across platforms

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#684]
**Describe the bug**

Debug messages on the client allow newlines whereas messages on the server do not.

**To reproduce**

```
crun outputDebugString("A\n\tB\n\t\tC")
run outputDebugString("A\n\tB\n\t\tC")
```

**Expected behaviour**

Should be the same.

**Screenshots**

![image](https://user-images.githubusercontent.com/923242/47945802-9d7add80-defc-11e8-8fd7-be72fdc00c45.png)

**Version**

1.5.6

**Additional information**
It would be useful to also convert `\t` to four spaces.

**Comment by theSarrum** [comment]
Same with _outputChatBox_ function
![outputchatbox](https://user-images.githubusercontent.com/12110157/47946032-94e3d080-df17-11e8-9c3a-28b4d9afce21.png)

**Comment by StrixG** [comment]
This is due to the [StripControlCodes](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CPacketHandler.cpp#L1403) function in Packet_DebugEcho and Packet_ChatEcho.
We could just remove this function calls to allow all control characters including new line.

**Comment by qaisjp** [comment]
Nice find. That should work. Which control codes are currently stripped?

**Comment by StrixG** [comment]
> Nice find. That should work. Which control codes are currently stripped?

All below code 32

**Comment by AlexTMjugador** [comment]
> 
> 
> This is due to the [StripControlCodes](https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CPacketHandler.cpp#L1403) function in Packet_DebugEcho and Packet_ChatEcho.
> We could just remove this function calls to allow all control characters including new line.

Perhaps that's too easy for a good fix of this issue. Does removing the call to that function introduce any side effect? I _guess_ the call is there for a reason.

Edit: While checking a bit the code in order to make a (hopefully) better response, I've found that Packet_ConsoleEcho also calls StripControlCodes, so maybe that also creates inconsistencies across platforms on the treatment of control characters when outputting strings to the console.

**Comment by qaisjp** [comment]
If we check where StripControlCodes is used we could just edit StripControlCodes to allow tabs and newlines (tabs and newlines most definitely won't break anything... he says). Otherwise a flag to that function would also work.
