### ISSUE TITLE
setElementCollisionsEnabled OOP variable

### ISSUE THREAD

**Issue by misterquestions** [multitheftauto/mtasa-blue#685]
It would be great to have 'collisions' variable for element using OOP

**Comment by StrixG** [comment]
This variable is already there
![image](https://user-images.githubusercontent.com/8400907/47951703-10bc3800-df6d-11e8-99f7-26f817b08c42.png)

**Comment by patrikjuvonen** [comment]
I agree with @StrixG. Unable to reproduce them missing client or server-side in v1.5.6-release-16068.
