### ISSUE TITLE
setElementCollidableWith camera support

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#689]
**Is your feature request related to a problem? Please describe.**
camplement for ghostmode

**Describe the solution you'd like**
setElementCollidableWith should support camera element from `getCamera()`

**Describe alternatives you've considered**
no alternatives

**Additional context**
https://www.youtube.com/watch?v=GXrlWX1VH6o 00:00:08 you can see camera colliding with vehicles

**Comment by Timic3** [comment]
You can get around that with setCameraClip, although it would be nice to have that for specific element.

**Comment by Einheit-101** [comment]
This needs to support projectiles. It is stupid that the camera collides with projectiles that are flying around.

**Comment by lopezloo** [comment]
@CrosRoad95 video is private.
