### ISSUE TITLE
getChatboxLayout should have offset and other features

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#695]
**Is your feature request related to a problem? Please describe.**
getChatboxLayout doesn't have X-Offset, Y-Offset, Text-Align, Vertical and Horizontal. Now you can't set eg. OOC chat for RP servers under normal chat, because it will be in wrong position after changes in game menu. 

**Describe the solution you'd like**
Add these variables to getChatboxLayout()

**Additional context**
![image](https://user-images.githubusercontent.com/923242/48292756-9b240080-e473-11e8-832b-e65574fbf189.png)

**Comment by botder** [comment]
The code should support that. Maybe the wiki is outdated?

https://github.com/multitheftauto/mtasa-blue/blob/5d682ba6bce939be9c71395078bdc2d4ad156295/Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp#L14-L35

**Comment by patrikjuvonen** [comment]
Thanks for the report. I have added the missing CVars to the [Wiki page](https://wiki.multitheftauto.com/wiki/GetChatboxLayout) ([see diff](https://wiki.multitheftauto.com/index.php?title=GetChatboxLayout&curid=5108&diff=61881&oldid=60840)).
