### ISSUE TITLE
commands issue with double letters?

### ISSUE THREAD

**Issue by KWKSND** [multitheftauto/mtasa-blue#697]
after finding an old command "/peds follow" no longer working in my resource i found this issue

peds command
peds all
peds follow
peds hold
all use the same command handler in my resource

to fix it i tried changing the command from follow to ollow llow, no luck, but low did work as a command

wondered if its because the other command "peds all" is being used before "peds follow" 
so i changed the order so /peds all comes after /peds follow and now both commands works fine.

there must be an issue because of the 2 l's in all and follow.

the command "follow" didnt pass as "all" but it didnt fail either the script just stopped at all and didnt do the next elseif to find the match with "follow"

**Comment by qaisjp** [comment]
Seems odd. Do you have any example code?

**Comment by KWKSND** [comment]
function prespawnPed(player,command,req,free,type)
	if req == "follow" then
		outputChatBox("KWK Peds: follow",player,0,255,0)
	elseif req == "command" or req == "all" then
		outputChatBox("KWK Peds: command or all",player,0,255,0)
	elseif req == "hold" then
		outputChatBox("KWK hold",player,0,255,0)
	elseif req == "attack" and free == "mode" then
		outputChatBox("KWK attack",player,0,255,0)
	elseif tonumber(req) then
		outputChatBox("KWK Peds: ".. tostring(req),player,0,255,0)
	end
end
addCommandHandler ( "peds", prespawnPed )

i edited this from my resource it should have the same issues if you put the follow command after the all command

**Comment by KWKSND** [comment]
found the problem i'm a dummy lol
