### ISSUE TITLE
Improve calling gta functions

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#700]
**Is your feature request related to a problem? Please describe.**
current way of executing gta functions is weak, generally problematic

**Describe the solution you'd like**
copy functions from plugin-sdk that allow to comunicate between mta and gta

**Describe alternatives you've considered**
/

**Additional context**
example https://github.com/DK22Pac/plugin-sdk/blob/8d4d2ff5502ffcb3a741cbcac238d49664689808/plugin_sa/game_sa/CCustomCarEnvMapPipeline.cpp#L21

**Comment by Pirulax** [comment]
What's the exact problem with the current way of calling GTA functions?

**Comment by CrosRoad95** [comment]
old code, as Botder said.

**Comment by qaisjp** [comment]
I'm going to close this as while there's a good idea somewhere here, it's too surface level and doesn't put forward an actionable proposal.

I see you've backlogged this, so feel free to re-open @botder if you think it should not be closed.
