### ISSUE TITLE
Inaccurate GTA z-buffer causes z-fighting

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#710]
**Describe the bug**
I dont know if this can be considered a "bug", but the depth calculations in GTA seem to be inaccurate. Complex objects where faces are somewhat close to each other will suffer from ZFighting at longer distances.
setNearClipDistance() at a lower value than default makes this worse and causes z-fighting even for default GTA objects.

Ren712 also had massive problems. He wanted to create shadow shaders and some other nice stuff but as far as i know he never managed to fix the zfighting issues. I think this is the same problem.

**To reproduce**
1. Go to SAAW World War II
2. Use the binocular
3. Use a great zoom
4. See zfighting on far away objects
->Here it happens especially on ships and aircraft or generally high-complex objects, default GTA objects are often not "dense" enough, but setting something double-sided increases the chance for this bug to occur

You can alternatively use this in Editor F5 mode:
crun setNearClipDistance(0.1)
crun setFarClipDistance(2000)
crun obj = createObject(10828, 3500, -1781, 13, 0, 0, 90, true)
crun setElementDoubleSided(obj, true)
crun setElementPosition(me, 2900, -1667, 12)
-> Now use the camera and look at the far away drydock object, you see z-fighting

**Expected behaviour**
No zfighting, no matter if something is 100m away or 1300m
The distance at which elements start to render (nearClipDistance) should not alter Z-Fighting (technically possible?)

**Screenshots**
Ship with double-sided body far away:
![image](https://user-images.githubusercontent.com/923242/48688656-15186000-ebbf-11e8-88c8-a93afcf8d899.png)

With binocular:
![image](https://user-images.githubusercontent.com/923242/48688663-19dd1400-ebbf-11e8-8463-341956f41f53.png)

Ren712s test shader: 
![image](https://user-images.githubusercontent.com/923242/48688674-206b8b80-ebbf-11e8-886d-e01d291d997f.png)

Low distance to camera: 
![image](https://user-images.githubusercontent.com/923242/48688679-23ff1280-ebbf-11e8-960e-19f08f5ad265.png)

More distance to camera: 
![image](https://user-images.githubusercontent.com/923242/48688686-28c3c680-ebbf-11e8-9787-26a0d5e88688.png)

Even more distance to camera: 
![image](https://user-images.githubusercontent.com/923242/48688693-2cefe400-ebbf-11e8-8c7a-77fb45d3248c.png)

**Multi Theft Auto v1.5.6-release-15949**

**Additional context**
Why has setNearClipDistance() an impact on z-fighting?

**Comment by Einheit-101** [comment]
I found that this issue is actually a result of how the gta depth buffer works. 
Long story short: the accuracy of the depth buffer in the distance reduces greatly the lower you set nearClipDistance, because a lot of the 32 bit depth resolution is "wasted" in a very short distance to the camera. 
https://developer.nvidia.com/content/depth-precision-visualized

I think this should be renamed because the only way to improve depth calculations is by using a logarithmic depth buffer, and i dont know if it is technically possible:

https://www.gamasutra.com/blogs/BranoKemen/20090812/85207/Logarithmic_Depth_Buffer.php

If this issue is something that we simply have to deal with because of a technical limitation then feel free to close it. 
We then have the Following choices:
-very near clip plane but more zfighting at distance
-far clip plane but much less zfighting at distance

**Comment by Wolfee-J** [comment]
Technically can be fixed in MTA, however requires more knowledge of the graphical engine.
