### ISSUE TITLE
OOP for strings

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#713]
**Is your feature request related to a problem? Please describe.**
strings are only a bit oop friendly

**Describe the solution you'd like**
add support for more various operators, methods for string if oop enabled.
The best would be enable oop just for strings

**Describe alternatives you've considered**
/

**Additional context**
we can copy functions name and applications from other language, eg. https://www.programiz.com/python-programming/methods/string not all, but most common used

example, `string = "a%sdf"`
1. `#string` return length = 5 -- this working for now.
2. `string / "d"` will split string, = {"a%s","f"}
3. `string("s")` work as string format result: "asdf"
4. `string:startswith("a")` return true
5. `string[4]` return `d`

**Comment by jushar** [comment]
I personally wouldn't hardcode such things. (1) works already, (2) and (3) don't look very intuitive and the latter (and even all others) can trivially be implemented in Lua.

Also, I'm sure there are lots of string manipulation libraries for Lua out there, thus a more general approach (i.e. library resources we talked about a couple of times) is the preferred way.

Closing this for now. If someone from the MTA team has objections, feel free to reopen though.

**Comment by Kenix157** [comment]
You can do this via debug.setmetatable
