### ISSUE TITLE
dxCreateTexture, gif support

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#715]
**Is your feature request related to a problem? Please describe.**
You can't use gif 😢 

**Describe the solution you'd like**
make dxCreateTexture support gif, thats generate wide image with each frame thats can be displayed using `dxDrawImageSection`

**Describe alternatives you've considered**

**Additional context**
Botder i know that gifs are big 😠

**Comment by Einheit-101** [comment]
Isnt there a program that generates a spritesheet from gif?

**Comment by CrosRoad95** [comment]
there is, https://ezgif.com/gif-to-sprite

**Comment by AlexTMjugador** [comment]
If file size is a concern, it might be interesting to implement support for the APNG (animated PNG) format instead. Although it's not as widespread as GIF, it is much more recent, offering the improved compression algorithms and color depth we all know and love from PNG. This animated image format is currently supported by the major web browsers Chromium, Opera, Firefox and Safari.

**Comment by qaisjp** [comment]
An animated texture format will never be supported. Rendering an animation from a spritesheet is the way to go.

I'm not against natively supporting _video players_ but for the time being, you can use CEF.
