### ISSUE TITLE
setModelWheelSize to set vehicle model wheel size

### ISSUE THREAD

**Issue by Grafu** [multitheftauto/mtasa-blue#719]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm replacing car models and the wheel size does not match the original model (wheels stick into the ground).

**Describe the solution you'd like**
I'd love MTA to have a function something like setModelWheelSize (or even setVehicleWheelSize) to set vehicle/model wheel sizes.

**Describe alternatives you've considered**
I do not see any alternatives for this, except matching custom model to original model considering wheel sizes. This is very frustrating and I run out of matching car slots fast. + They are not perfectly matched.

**Additional context**
Attaching googled memory address offsets for vehicle wheel sizes: https://pastebin.com/mt7eLw0Z
According to this source, wheel memory addresses have offset +1112 [Float] from vehicle pointer (ctrl + f Car Wheel Size). Considering this context...

+1108 [DWord] modding data as in garage info
+1112 [Float] Car Wheel Size from vehicle.ide
+1116 [DWord] Time left for car alarm to sound in ms
+1120 [DWord] Pointer to driver

...neighbour values of Car Wheel Size are DWords offset every 4 bytes. But Car Wheel Size is Float instead of DWord I guess it is 2 bytes and there are 2 wheel sizes (front and rear) in that position??

Mantis: https://bugs.multitheftauto.com/view.php?id=7441

**Comment by Einheit-101** [comment]
Original bug report:
https://bugs.mtasa.com/view.php?id=7441

**Comment by Wolfee-J** [comment]
This'd be perfect for the 'Vehicle streamer' system I'm planning.

**Comment by Dutchman101** [comment]
Practical example:
![image](https://user-images.githubusercontent.com/12105539/81773482-9fa5fb00-94e8-11ea-96da-61b489aa2a58.png)

This has been the biggest annoyance for modellers in the past years I guess.. it severely limits their freedom. It's an MTA problem (in GTA, you can easily modify wheel size in vehicles.ide to accomodate your mod) and therefore, a lot of GTA vehicle mods that are turned into server mods will never look like in single-player.

I've seen a lot of modellers, including myself, trying to play around with the wheel dummy position and pivot placement, but it won't help. That is before the person discovers the existence of this bug.

**Comment by MrSol0** [comment]
original suggestion was made in 
2012-12-10 01:08
--
anyone thinks it's time to make this matter urgent? or is it gonna be forgotten about for another 10 years.

**Comment by AlexTMjugador** [comment]
Just for the record, the `+1112 [Float] Car Wheel Size from vehicle.ide` float is not related to the `vehicle.ide` file at all. The PR #1641 documents it.

**Comment by CarlRayanitch** [comment]
> ## original suggestion was made in
> 2012-12-10 01:08
> anyone thinks it's time to make this matter urgent? or is it gonna be forgotten about for another 10 years.

it already has lol, vehicles.ide is super important and we should of had it at least since 2015
