### ISSUE TITLE
[Question] How to install MTA on Ubuntu

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#724]
**Describe the bug**
Crash when trying to run mta

**To reproduce**
Install gta.
Install mta.
Install directx, font by winetricks

**Expected behaviour**
```Mta run```

**Version**
System information:
    Wine build: wine-3.6 (Ubuntu 3.6-1)
    Platform: i386
    Version: Windows 5.1 (0)
    Host system: Linux
    Host version: 4.15.0-39-generic```

Last mta version for windows xp

**Advanced**
[Backtrace log](https://vk.com/doc111177654_483321842?hash=4de7fc7baeaaf48798&dl=8159b94f5ed500cafa)

**Comment by botder** [comment]
MTA only supports Microsoft Windows and not Wine. You have to figure out the solution yourself.
