### ISSUE TITLE
Clientside version of setVehicleVariant

### ISSUE THREAD

**Issue by Brian9221** [multitheftauto/mtasa-blue#727]
**Is your feature request related to a problem? Please describe.**
When creating clientside static vehicles there's no way to set their variants. It would be better to have a clientside  version of setVehicleVariant to use locally. One could have up to 255 different ways customize a vehicle clientside. 

**Describe the solution you'd like**
Have setVehicleVariant clientside.

**Comment by qaisjp** [comment]
You missed the opportunity to say "Clientside variant of setVehicleVariant"
