### ISSUE TITLE
Moon function

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#729]
**Is your feature request related to a problem? Please describe.**
Already we have 'setSunSize' and 'setSunColor' functions and setMoonSize, but we haven't 'setMoonColor' function, it'll would be usefull e.g on 'apocalyptic' gamemode.

**Describe the solution you'd like**
Adding setMoonColor function

**Describe alternatives you've considered**
We can make it with using shader and texture but if we have setSunColor, so why we can't have setMoonColor.

**Additional context**

**Comment by CrosRoad95** [comment]
use shader 🙄 and set custom moon graphic

**Comment by FileEX** [comment]
So, setSunColor is unnecessary, because we can change sun color with shader and custom graphic.

**Comment by CodyJL** [comment]
You cannot modify the moon shader @CrosRoad95

**Comment by Dutchman101** [comment]
> You cannot modify the moon at all at the moment @CrosRoad95

You can, i took the screenshot below after replacing the moon with a planet;

[https://i.imgur.com/4PuRMYZ.png](https://i.imgur.com/4PuRMYZ.png)

Resource: [https://www.dropbox.com/s/scydsuxjasv4anu/moonmod.zip?dl=1](url)

**Comment by CodyJL** [comment]
Well that's odd, last time I attempted I could not find anything on it.
