### ISSUE TITLE
setVehicleHandling crash when setting numberOfGears property

### ISSUE THREAD

**Issue by Fierelier** [multitheftauto/mtasa-blue#731]
**Describe the bug**
When setting the numberOfGears lower than the current gear of the vehicle, Multi Theft Auto crashes. When done server-side, this also seems to crash other players in stream-range of the vehicle.

**To reproduce**
Steps to reproduce the behaviour:
1. [Download hedit](https://community.multitheftauto.com/index.php?p=resources&s=details&id=3716).
2. Start the resource.
3. Get in a car.
4. While driving, press B on your keyboard and quickly adjust the "Number of Gears" option to be lower than your current gear.
5. Game crash.

**Expected behaviour**
I expected the vehicle to downshift to the new maximum gear.

**Version**
Client: 1.5.6
Server: 1.5.6

**Comment by StifflersMom** [comment]
I can confirm this - The client freezes with 100% CPU usage. It freezes also all streamed in players.
