### ISSUE TITLE
Full HD tearing bug

### ISSUE THREAD

**Issue by Kenix157** [multitheftauto/mtasa-blue#732]
Screen is flickering on Full HD Display (1920x1080) but you can reproduce it on a different screen sizes (1366x768).

Steps to reproduce:
1. Full HD Display (1920x1080)
2. Rotate camera/Move ped.

Video:
https://youtu.be/F7zWLa7GNZc

MTA Client Version:
Multi Theft Auto v1.5.6-release-16068.3

MTA Diag:
Mine: https://pastebin.mtasa.com/691300845
Other: https://drive.google.com/file/d/1O0AuwPVtIHAIiOoCCsMsyIsfmkvn2KHW/view?usp=sharing

**Comment by Kenix157** [comment]
It's very urgent, because 20% of MTA players use this screen size (Display's like this).

Stats:
https://imgur.com/MiZhP8F

**Comment by Citizen01** [comment]
It's called screen tearing and it has already been reported here: #643

**Comment by Kenix157** [comment]
Thank you, i didn't saw.

I'll test it on a different MTA builds.

**Comment by qaisjp** [comment]
Duplicate of #643
