### ISSUE TITLE
Freecam (onClientCursorMove) 1.5.6 Randomly Freezing

### ISSUE THREAD

**Issue by bVidDa** [multitheftauto/mtasa-blue#735]
When I use any script (included the Editor) that makes use of onClientCursorMove,
most often to move the cam in some scripts, I get a very irritating behavior ...
The mouse seems to Freeze, it gets stuck so each movement takes
half a second to load, and also i don't get all the movement
of the cursor that I made in that half of a second, so ...
is more irritating than just Low Mouse FPS ...

In the other end, it doesn't seems to have any to do
with my game Fps, i can keep moving with keys
while the mouse hangs and i am moving it.

I was pretty sure it was a problem with my Os (hardware)
i tried any combination of Compatibility on windows
installed the nightly buid and also reinstalled Mta.
There was a clue about this I ignore at first and
is that the mouse still works fine while i am
playing with this, and also with Freelook.

So i was able to play in a laptop, also Windows 7
and there it works just fine, i know it's some
incompatibility with my hardware, but it
still worked very well until the update.

I know this is a new bug, and hope it will be fixed
but i also want to fix this myself sooner, because
it seems to be working sometimes and I'm
not yet sure that it's a Software thing.
I mean: something fixable be me ...

I am working on a mapping project and this
is important for me right now. I went for
the changelog of this release and I
don't found nothing related that
can serve me of any hint to
know the source of this.

https://pastebin.mtasa.com/347168247

Anyway, there is my MtaDiag link, but
it's giving an Error 500 for me now,
were can i find a copy? please.

**Comment by Wolfee-J** [comment]
https://github.com/multitheftauto/mtasa-resources/issues/134 (Related?)

**Comment by bVidDa** [comment]
Thank you Cody. Yes, this is the same bug, i will keep that Issue in watch.
It seems a bug coming from a directx glitch (tearing) so i will take a look
to my graphic setting now. But is not an issue from the resource itself,
i didn't look in the Resources repository, but I consider this closed,
so we can keep in touch from the other Thread. I hope there will
be any Beta update soon, there are so many mappers affected.

Thank you very much. I'm coming.

**Comment by Pirulax** [comment]
Maybe it's related to the fix of integer overflow bug in onClientCursorMove?

**Comment by qaisjp** [comment]
Duplicate of #763
