### ISSUE TITLE
onClientMarkerLeave matchingDimension returns false even if on same dimension

### ISSUE THREAD

**Issue by Feche** [multitheftauto/mtasa-blue#736]
**Describe the bug**
onClientMarkerLeave matchingDimension argument only works on dimension 0, here are some tests that I did:

Player dimension is 0, and marker is 0: 
Player dimension: 0, Marker dimension: 0, onClientMarkerLeave same dimension: true
Returns true, expected result.

Player dimension is 4, and marker is 0:
Player dimension: 4, Marker dimension: 0, onClientMarkerLeave same dimension: false
Returns false, expected result.

Player dimension is 4, and marker is 4:
Player dimension: 4, Marker dimension: 4, onClientMarkerLeave same dimension: false
Both elements are on same dimension and returns false, it should return true.

Player dimension is 4, and marker is 0:
Player dimension: 0, Marker dimension: 4, onClientMarkerLeave same dimension: true
Both elements are on different dimensions, and returns true, it should return false.

**To reproduce**
```lua
local marker = createMarker(0, 0, 2, "corona", 6, 255, 255, 255, 255)
setElementDimension(marker, 5)

addEventHandler("onClientMarkerHit", root,
	function(player, samedimension)
		if player == localPlayer and source == marker and samedimension then
			outputChatBox'hit'
		end
	end
)

addEventHandler("onClientMarkerLeave", root,
	function(player, samedimension)
		if player == localPlayer and source == marker and samedimension then
			outputChatBox'leave'
		end
	end
)
```

Only 'hit' will show up in chatbox, since onClientMarkerHit works as intended.

**Version**
Client: Multi Theft Auto v1.5.6-release-16068.3
Server: MTA:SA Server v1.5.6-release-16068

**Comment by theSarrum** [comment]
I can confirm. I remember there was a similar problem a few years ago and I thought that the problem in the script. Now I realize that it is not so.
