### ISSUE TITLE
Radarareas created with map files are not being destroyed after the map is stopped

### ISSUE THREAD

**Issue by 4O4** [multitheftauto/mtasa-blue#737]
**Describe the bug**
RadarArea defined in .map is not being destroyed after map is stopped. It gets duplicated over and over on each restart of the map. 

After the map is stopped, the radararea somehow becomes a direct child of root element (you can see that in the Element browser in web panel).

Note that this doesn't happen with radarareas created by Lua scripts with `createRadarArea`. 

**To reproduce**
1. Get the demo resource [from here](https://github.com/multitheftauto/mtasa-blue/files/2706242/radararea-bug.zip) and put it into server resources. This is just a simple map like this:
```
<map edf:definitions="editor_main">

<radararea posX="-2017,18688" posY="-2966,11035" sizeX="2136,6816" sizeY="2656,3564" color="#401a4285" dimension="0" />

</map>
```
2. Before starting the map, count radarareas on the server for reference
```
srun #Element.getAllByType("radararea")
```
3. Start the map
4. Restart it a few times and stop it
5. Compare the current radarareas count with the previous reference count. It increases with each restart of the map resource. Radarareas are not destroyed and become parentless (root element is the parent).

**Expected behaviour**
Radarareas created using map files should behave like all other entities and thus disappear when the parent resource is stopped.

**Version**
Latest stable linux server release, that is:
MTA 1.5.6 - Linux server package
R7 (build 14688) - Updated 11th October 2018

Also confirmed on local windows server MTA:SA Server v1.5.6-release-16068

**Additional info**
The last version of the server I am sure it worked correctly on is 1.5.3/1.5.4

**Comment by qaisjp** [comment]
Quick investigation. Here's a modified version of the resource that creates a radar area (id=`bugarea`) and vehicle (id=`fineveh`): [radararea-bug.zip](https://github.com/multitheftauto/mtasa-blue/files/2706378/radararea-bug.zip)


The below snippet shows that the vehicle and the radararea have the same parent, yet when you stop the resource, only the vehicle is deleted. The radararea's parent is indeed `root`.

```
run v.parent
[22:54:34] Console executed command: v.parent
[22:54:34] Command results: userdata: 07845840 [element:map]
run r.parent
[22:54:39] Console executed command: r.parent
[22:54:39] Command results: userdata: 07845840 [element:map]
run r.parent == v.parent
[22:54:43] Console executed command: r.parent == v.parent
[22:54:43] Command results: true [boolean]
stop radararea-bug
[22:54:47] stop: Requested by Console
[22:54:47] stop: Resource stopping
[22:54:47] Stopping radararea-bug
run r.parent
[22:54:51] Console executed command: r.parent
[22:54:51] Command results: userdata: 075AE250 [element:root]
run v.parent
[22:54:54] Console executed command: v.parent
[22:54:54] WARNING: [admin]\runcode\server.lua:21: Bad argument @ 'parent' [Expected element at argument 1] [string "return v.parent"]
[22:54:54] Command results: false [boolean]
```

**Comment by 4O4** [comment]
@botder Thanks!
