### ISSUE TITLE
Allow loading pre-compiled shaders as raw data

### ISSUE THREAD

**Issue by nbredikhin** [multitheftauto/mtasa-blue#742]
**Is your feature request related to a problem? Please describe.**
There is a new way to [pass raw shader code to dxCreateShader](https://github.com/multitheftauto/mtasa-blue/issues/430) as string. But it doesn't work for shaders pre-compiled using [FXC](https://docs.microsoft.com/en-us/windows/desktop/direct3dtools/dx-graphics-tools-fxc-using). MTA sees binary shader data as a path and throws a "File doesn't exist" error.

**Additional context**
Currently you can load compiled shader from files, but it doesn't allow to add an encryption level. Anyone could take pre-compiled shader file from client cache and load it.

To compile with FXC I use the following command:
`fxc /T fx_2_0 /Fo myShader.fxc myShader.fx /E PixelShaderFunction`

**Comment by botder** [comment]
Can you confirm that precompiled shaders begin with the four `01 09 FF FE` header bytes? Three shaders gave me these four bytes at the beginning. I could use that to detect precompiled shaders in dxCreateShader.

**Comment by qaisjp** [comment]
What if we just used "contains newline" as a heuristic?

**Comment by samr46** [comment]
@botder i can confirm that.

But if it's about security then i would suggest to not store shaders in cache at all. Compiled shaders can be easily decompiled.

@dcr30 check [example](https://wiki.multitheftauto.com/wiki/DxCreateShader) about possible raw data usage for shaders. It may be useful in your case.

**Comment by botder** [comment]
> What if we just used "contains newline" as a heuristic?

If you are sure that this approach can identify all compiled shaders, then of course.
