### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by SkyBadPT** [multitheftauto/mtasa-blue#754]
I can't join one server and the message that appears is "SD # 14 CNQ This server does not allow virtual machines" but I'm not running in a virtual machine, the only change that I have made on my computer was installing Visual Studio and Android and SQL components for visual studio. but then I uninstalled them. but still get that message... need help fixing it, I already reinstalled GTA SA and MTA

**Comment by SkyBadPT** [comment]
I also reintalled mta and still have the same problem.

**Comment by ccw808** [comment]
[Download and run MTADiag](https://mirror.mtasa.com/mtasa/utils/MTADiag.exe) and follow the instructions.

Press 'n' when asked.

Post any Pastebin URL MTADiag gives you

**Comment by SkyBadPT** [comment]
@ccw808 here is the result: https://pastebin.mtasa.com/9063194

**Comment by SkyBadPT** [comment]
Line 7636 shows the error that I'm getting when I join the server and get kicked

**Comment by ccw808** [comment]
Looks like problem started on 2019-01-01 or 2019-01-02
Did you install anything recently?
When did you enable Hyper-V for Windows?

**Comment by SkyBadPT** [comment]
@ccw808 Problem started yesterday 02-01-2019, and I did installed Visual Studio 2015 and some components of it. And I didn't enable Hyper-V also don't know from where that Hyper-V came from.

**Comment by ccw808** [comment]
Try installing MTA with https://nightly.mtasa.com/mtasa-1.5.6-rc-16068-20181121.exe

**Comment by SkyBadPT** [comment]
@ccw808 I removed the Hyper-V and reinstalled to the version that you posted and it's working thanks!!
