### ISSUE TITLE
Motion Blur into Video Settings

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#756]
**Is your feature request related to a problem? Please describe.**

A lot people hate motion blur and would like to have it disabled on any server. This would be usefull because not every server offers options for players to change their motion blur setting.

**Describe the solution you'd like**

There should be added a bar for the strengh of motion blur effect in video settings and a tick box which allows scripts to overwrite the motion blur value and resets motion blur value on server leave.
Bar:
0 |-----------| 100
tick box:
☐ Allow scripts to overwrite Motion Blur setting.

Related script function:
setPlayerBlurLevel / setBlurLevel
https://wiki.multitheftauto.com/wiki/SetPlayerBlurLevel

**Comment by qaisjp** [comment]
I think servers should be in control of blur level, and there to just be a single checkbox "Enable blur" to set the default on-join (servers should be able to override this freely). Thoughts?

**Comment by qaisjp** [comment]
A problem here is that there is no `resetBlurLevel` function, so existing servers will not be able to get the default. Perhaps we could add `resetBlurLevel` (and then also add a blur level bar, as originally described in the issue).

Blur level could be updated whilst ingame, but only apply if the blur level is currently "reset". That way servers can use resetBlurLevel to relinquish control to the user's preference, or use `setBlurLevel(defaultValue)` to force it to a certain value.

**Comment by Guillaume57** [comment]
The blur level is restored to its default value when starting a game (joining a server or map editor), so why need resetBlurLevel function ? If server want to reset player's default blur level, it can first save the value of getPlayerBlurLevel when player join and then setPlayerBlurLevel to this value to reset it.

**Comment by qaisjp** [comment]
Wait. Do we really need `resetBlurLevel` if we had something like `getClientSetting` https://github.com/multitheftauto/mtasa-blue/issues?q=is%3Aissue+sort%3Aupdated-desc+getClientSetting

Sorry for kind of breaking #1266

**Comment by ghost** [comment]
Well, i added `resetBlurLevel` since i felt like it was kinda missing. I also added it cause i thought about `resetBlurLevel` to reset to be used in this PR to reset blur level to clients preference or default GTA value.

Quite unsure about `getClientSetting` tbh
