### ISSUE TITLE
setSoundPanningEnabled doesn't seem to work on looped sounds

### ISSUE THREAD

**Issue by dretax** [multitheftauto/mtasa-blue#757]
**Describe the bug**
[setSoundPanningEnabled](https://wiki.multitheftauto.com/wiki/SetSoundPanningEnabled) doesn't seem to work on looped sounds.

**To reproduce**
```lua
local playedsound = playSound3D(url, x, y, z, true)
elements[source] = playedsound
outputChatBox("Pan: " .. tostring(isSoundPanningEnabled(playedsound)))
local succcc = setSoundPanningEnabled(playedsound, false)
outputChatBox("Pan2: " .. tostring(isSoundPanningEnabled(playedsound)) .. " xd " .. tostring(succcc))
```

**Expected behaviour**
Should be set to false.
Currently it gives:
Pan: true
Pan2: true xd true

**Version**
Latest MTA client on Windows

**Comment by dretax** [comment]
@qaisjp

**Comment by StrixG** [comment]
setSoundPanningEnabled doesn't work even with not looped sounds. The sound is not ready when setSoundPanningEnabled is called.

**Comment by dretax** [comment]
Yeah at last I also noticed that. Thanks for the fix.
