### ISSUE TITLE
getCameraMatrix() server-side allways returns false

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#762]
**Describe the bug**
getCameraMatrix() does not work on serverside.

**To reproduce**
1. Start runcode
2. /srun getCameraMatrix(p)

This will return false every time.

**Expected behaviour**
Should give the matrix of the camera.

**Version**
Server: MTA:SA Server v1.5.6-release-16103
Client: Multi Theft Auto v1.5.6-release-16183

**Additional context**
camera_sync_interval setting has been setted to 1000. In clientside it works fine (I used some events to get past this bug)

**Comment by Citizen01** [comment]
> Note: The server-side version of this function returns the last camera matrix that was set by the server, and thus does not necessarily indicate the current matrix of the camera (since it may have been changed client-side).

So if you never used **setCameraMatrix** on serverside for that player, then it will return false.
But for me that note makes me think that the **getCameraMatrix** function is useless on the server side.

The server part has no idea what a camera is, in fact only the client side should be aware of the camera aspect as this is the only part that needs to render stuff on the screen.

But this issue starts a new debate:
Should we remove camera related functions from the server side or make those functions work as everyone would expect by fixing them ?

**Comment by qaisjp** [comment]
I was going to set this as invalid, but hmm, camera_sync_interval has been on the [Sync interval settings](https://wiki.multitheftauto.com/wiki/Sync_interval_settings) page since it was created in 2012:

> How often to tell the server of any client side changes to the local players camera position and target.

However as far as I can remember getCameraMatrix server-side has always had the functionality described by @Citizen01 in https://github.com/multitheftauto/mtasa-blue/issues/762#issuecomment-452160044, so I'm not sure about this one.

**Comment by PlatinMTA** [comment]
Ok I misunderstood the function, my bad. I don't think we should delete that function tho.

**Comment by Citizen01** [comment]
yeah `camera_sync_interval` makes me think there is no reason for the serversided version of `getCameraMatrix` to not report the values from the latest sync correctly other than a problem winthin the code.

**Comment by jushar** [comment]
The documentation is not exactly correct about the described behaviour.
`getCameraMatrix` returns the matrix of the __fixed/static camera__ that is enabled by calling `setCameraMatrix` on the server. 

Technically, the camera sync (adjusted via the _camera_sync_interval_ setting) syncs the matrix if the camera is in static/fixed mode and the target player (only) if in following-mode (see https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CNetAPI.cpp#L1943-L1966).

I updated the documentation accordingly, but apart from that, I don't see a reason to change any behaviour.
