### ISSUE TITLE
Vehicle/bike won't accelerate after getting on water

### ISSUE THREAD

**Issue by Feche** [multitheftauto/mtasa-blue#764]
**Describe the bug**
If a vehicle/bike enters water, and you set the position outside the water, it won't accelerate (W key)

**To reproduce**
Get in a vehicle/bike, go to water and let the car sink, when the car is fully on water, setElementPosition of the vehicle somewhere outside the water -> vehicles won't accelerate, and bikes will only go backwards (S key)

**Expected behaviour**
Should accelerate after being removed of the water

**Version**
Client: Multi Theft Auto v1.5.6-release-16068.3 - Windows
Server: MTA:SA Server v1.5.6-release-16068 - Windows

**Comment by Woovie** [comment]
What happens if you setVehicleEngineState to true?

**Comment by Feche** [comment]
Thank you very much, now it is working, you can dismiss this bug!
