### ISSUE TITLE
Please add a whitelist feature to Anti-Cheat SDs

### ISSUE THREAD

**Issue by Traace** [multitheftauto/mtasa-blue#773]
**Is your feature request related to a problem? Please describe.**
I'm playing on CIT2 MTA Server for a few years now and have almost 300 hours playtime on that server.
However when I try to connect from my wine client, I get the disconnect message SD #28 "Wine clients are not allowed"
We understand its important to have all SDs enabled on that server in general to prevent hackers from just changing their wine installation thus get a new serial.
First what I did ofc: Wrote a message at CIT2 forums, but the Admin Arran says its currently not possible to whitelist me because MTA itself didnt implant such a feature for anti-cheat yet. So here we are.

**Describe the solution you'd like**
What we like to see is a whitelist feature, approved players should be able to get whitelisted via their serial.
For example via a simple .conf like "ac_whitelist.conf" on that server.

**Describe alternatives you've considered**
I don't think there is a more easy solution then enable a whitelist feature.
Multibooting just for MTA is unfortunately to much sometimes.

**Additional context**
Using wine with MTA again would be amazing. Maybe it also increate playerbase again. Many ppl I know have osx or linux, they can't play newers like GTA-V at all but would like to enjoy some bigger MTA San Andreas servers again.

**Comment by ccw808** [comment]
It is possible for servers to implement whitelists via scripting.
See the 3rd example on https://wiki.multitheftauto.com/wiki/OnPlayerACInfo

**Comment by Traace** [comment]
Thanks for the fast replay

Maybe this information should be linked to https://wiki.multitheftauto.com/wiki/Anti-cheat_guide

Even some bigger Admins aren't aware that these features already exist.
