### ISSUE TITLE
onClientMinimize doesn't work when player has windowed mode

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#774]
**Describe the bug**
onClientMinimize doesn't work when player has windowed mode in game settings.

**To reproduce**
1. run this script:
```
addEventHandler("onClientMinimize", root, function()
	outputDebugString("Minimized")
end)
```
2. set your game to fullscreen and do alt + tab
there's message in debug
3. set your game to windowed mode and do alt + tab
there's no message in debug

**Version**
Multi Theft Auto v1.5.6-release-16068.8
Copyright (C) 2003 - 2018 Multi Theft Auto

**Comment by StifflersMom** [comment]
Can't reproduce with Multi Theft Auto v1.5.6-release-16273 on Windows 7.
Also, alt+tab is not "minimize".

**Comment by SDraw** [comment]
Alt-Tab combination doesn't minimize game window, therefore event isn't called.
Currently there is pull request #185 for implementation of correlated event.
At the mean time, you can make your own custom event using **onClientRender**/**onClientPreRender** event and **isMTAWindowActive** function to detect window switching.

**Comment by MrDadosz** [comment]
@SDraw thanks. There should be information about it on wiki.
