### ISSUE TITLE
setDevelopmentMode

### ISSUE THREAD

**Issue by 1B0Y** [multitheftauto/mtasa-blue#780]
**Describe the bug**
Using setDevelopmentMode serverside does not set the player's dev mode to what's defined. Only client-side setDevelopmentMode works correctly.

**To reproduce**
Runcode the following commands like before:
1B0Y executed command: setDevelopmentMode(true)
Command results: true [boolean]
showcol is now set to 1
showcol will have no effect because development mode is off
Executing client-side command: setDevelopmentMode(true)
Command results: true [boolean]
showcol is now set to 1

**Expected behaviour**
Running clientside setDevelopmentMode will set the correct dev mode as defined. However, when trying to set a player (or the entire server)'s dev mode, it will return as true, however development mode will still be off.

**Version**
Multi Theft Auto v1.5.6-release-16068.8
Copyright (C) 2003 - 2018 Multi Theft Auto

**Additional context**
N/A

**Comment by botder** [comment]
`setDevelopmentMode` works independently on client and on server. There is no synchronization between server and clients. Currently, `setDevelopmentMode` enables `debugSleep` on server and nothing more. **showcol** and **showsound** require `setDevelopmentMode` enabled on client.

The [wiki page](https://wiki.multitheftauto.com/wiki/SetDevelopmentMode) should probably include that information. It's working as intended, but if you want synchronization, then create a new issue for that.
