### ISSUE TITLE
Server repeatedly crashing

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#781]
**Describe the bug**
I restarted the server for windows updates and then started the server up using the same version as before the restart but the server crashed after a few minutes of uptime 3 times. I have since updated to the newest nightly to see if that might help.

No crash dump is being generated but there is an event viewer log:

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: deathmatch.dll, version: 1.5.6.14414, time stamp: 0x5ba45855
Exception code: 0xc0000005
Fault offset: 0x0000000000380eac
Faulting process id: 0x102c
Faulting application start time: 0x01d4ae66045a3cf5
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: D:\Servers\MTA San Andreas 1.5\server\x64\deathmatch.dll
Report Id: b5615c93-1a59-11e9-80dc-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

and

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: deathmatch.dll, version: 1.5.6.14414, time stamp: 0x5ba45855
Exception code: 0xc0000005
Fault offset: 0x0000000000380eac
Faulting process id: 0x13d8
Faulting application start time: 0x01d4ae65bb4dd04b
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: D:\Servers\MTA San Andreas 1.5\server\x64\deathmatch.dll
Report Id: 41cf24dc-1a59-11e9-80dc-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

and 

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: deathmatch.dll, version: 1.5.6.14414, time stamp: 0x5ba45855
Exception code: 0xc0000005
Fault offset: 0x000000000023b3a9
Faulting process id: 0x12f8
Faulting application start time: 0x01d4ae653aad1c0d
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: D:\Servers\MTA San Andreas 1.5\server\x64\deathmatch.dll
Report Id: f8c0e371-1a58-11e9-80dc-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

and with the newest build:

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: lua5.1.dll, version: 1.5.6.16345, time stamp: 0x5c3be3a9
Exception code: 0xc00000fd
Fault offset: 0x0000000000016480
Faulting process id: 0x155c
Faulting application start time: 0x01d4ae6727a37c9d
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: D:\Servers\MTA San Andreas 1.5\server\x64\lua5.1.dll
Report Id: dbe62cf6-1a5a-11e9-80dc-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

and

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: lua5.1.dll, version: 1.5.6.16345, time stamp: 0x5c3be3a9
Exception code: 0xc0000005
Fault offset: 0x0000000000016400
Faulting process id: 0x1794
Faulting application start time: 0x01d4ae68283cd804
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: D:\Servers\MTA San Andreas 1.5\server\x64\lua5.1.dll
Report Id: db73d83e-1a5b-11e9-80dc-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

and

Faulting application name: MTA Server64.exe, version: 1.10739.0.0, time stamp: 0x581fd5b9
Faulting module name: ntdll.dll, version: 6.3.9600.19153, time stamp: 0x5b93ffa7
Exception code: 0xc00000fd
Fault offset: 0x0000000000030d62
Faulting process id: 0x1070
Faulting application start time: 0x01d4ae6c31bb313c
Faulting application path: D:\Servers\MTA San Andreas 1.5\server\MTA Server64.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: efd59483-1a5f-11e9-80de-0cc47a02577f
Faulting package full name: 
Faulting package-relative application ID: 

The fact that different modules have crashed, does this mean that it is almost certainly not an MTA bug? This reminds me of something that happened many years ago, I think something to do with windows being stupid and crashing MTA server because it thought there was no RAM left when there is because no page file / small page file was set. I haven't changed that setting for years, checked it now and it was set to 4 GB, I've changed it to "system managed" just in case.

**Version**
1.5.6.16345 64 bit windows server 2012

**Additional context**

Tried removing all recent windows updates and restarting - didn't help.
Trying 32 bit windows maybe at least it will give a dump file, 20 minutes in and no crash yet, maybe it was the 64 bit that was for some reason causing a crash, even though it worked fine before the restart :/

It makes no sense, everything is as it was before the server was restarted, the only thing that's changed recently (unless a script change is causing it) was updating the minclientversion to 1.5.6-9.16276.0

**Comment by 1B0Y** [comment]
Bill gates at it again. Tried rolling back the update (if it's applicable in 2012)?

**Comment by ArranTuna** [comment]
All the updates were uninstalled and the server was restarted, it didn't help. 32 bit survived about 5 hours before crashing at least there is a dump file with 32 bit but the dump file looks empty...
[crash.zip](https://github.com/multitheftauto/mtasa-blue/files/2770813/crash.zip)

Maybe some troll found another way to crash servers. I've still got mtadbg3.exe which is something that helps debugging crashes and I guess runs it in some debug mode because the server is laggy with it which I've had for many years, could try that if it keeps happening.

**Comment by ccw808** [comment]
32 bit crash dump was invalid.

Try creating a crash dump for the 64 bit server by following these instructions: https://forum.mtasa.com/topic/113157-help-me-installation/?tab=comments#comment-939054
(Replace **mtasa-1.5.6.exe** with **MTA Server64.exe** in the reg file)

**Comment by ArranTuna** [comment]
Thanks, I did as you said and the server was up for 24 hours with no crash, I then restarted the whole server and launched it again, no crash and it's been 7 hours, so whatever was causing this has randomly fixed itself. I will post another bug report if I ever get a proper crash dump.
