### ISSUE TITLE
CEF performance

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#787]
**Describe the bug**
CEF is lagging when using animations 

**To reproduce**
[mtasa-cef-performance-test.zip](https://github.com/multitheftauto/mtasa-blue/files/2790650/mtasa-cef-performance-test.zip)

**Expected behaviour**
Smooth animations

**Version**
server / client: v1.5.6-release-16349
windows 8.1 x64

**Additional context**
You can compare ingame performance and browser by open the index.html

**Comment by patrikjuvonen** [comment]
Probably because we haven't enabled hardware acceleration.
