### ISSUE TITLE
MTA Dont Give Any Sound Windows 10

### ISSUE THREAD

**Issue by MiniBoss420** [multitheftauto/mtasa-blue#788]
**Describe the bug**
 All other games and mediaplayers give Sound Only mta Dosent.

**To reproduce**

**Expected behaviour**

**Screenshots**

**Version**

**Additional context**

**Comment by jushar** [comment]
Is your sound muted in the MTA settings? (Check the sliders in _Settings -> Audio tab_)
Are you sure MTA is unmuted in the Windows 10 audio mixer? (right-click on sound tray icon -> open volume mixer)

**Comment by MiniBoss420** [comment]
Vulume mixer are working fine ALso settings in MTA are all On

**Comment by MiniBoss420** [comment]
https://pastebin.mtasa.com/807717433 Heres Pastebin if it helps

**Comment by Woovie** [comment]
Please post this over to https://forum.mtasa.com/forum/83-client/ instead of a bug report. This issue is not caused by MTA most likely until proven otherwise. If an issue is discovered in the forum thread, a proper bug report will be made.
