### ISSUE TITLE
Doors model opening bug

### ISSUE THREAD

**Issue by Cyber52** [multitheftauto/mtasa-blue#791]
**Describe the bug**
Player can open the doors (model ID 1569) when hit it with fist. The doors opens and closes when player is not stopping them. When doors close you cant open it anymore unless you go away and render them again.

**To reproduce**
1. Creating doors model with ID 1569 using CreateObject() function
2. Hit the created doors with fist
3. Doors are opening and closing slowly
4. Doors are locked

**Expected behaviour**
Doors should be closed right after creating them or there should be some MTA functions to control that behaviour (e.g. setDoorLocked(element, true/false) ) (in this case the opening function would be added to more doors models)

**Screenshots**
I think Its very easy to reproduce/understand what does "door" opening means but If you really need it I can record it.

**Version**
Server: 1.5.6 / Windows
Client: 1.5.6-9.16068.8 / Windows
 

**Additional context**

**Comment by MrDadosz** [comment]
Reported in https://github.com/multitheftauto/mtasa-blue/issues/766

**Comment by qaisjp** [comment]
Duplicate of #766
