### ISSUE TITLE
onPlayerWeaponFire doesn't run for Spray can, but It does for client side

### ISSUE THREAD

**Issue by dretax** [multitheftauto/mtasa-blue#797]
**Describe the bug**
Not sure if this is a bug.

**Expected behaviour**
Server event should be running for spray can also.

**Version**
Latest of client and server, linux x64

**Comment by MrDadosz** [comment]
It doesn't work with spray and minigun. Spray is "shooting" every frame, it could hurt server performance.

**Comment by dretax** [comment]
Yeah thats why I wrote "Not sure if this is a bug"

**Comment by CrosRoad95** [comment]
`it could hurt server performance.` server already know when someone spraying, but calling event for this - no

**Comment by dretax** [comment]
That's also true though I dunno if this is on purpose.

**Comment by lopezloo** [comment]
This event works only with weapons which have enabled bullet sync.
