### ISSUE TITLE
Improving MTA

### ISSUE THREAD

**Issue by DicoSky** [multitheftauto/mtasa-blue#802]
My name is dico , and i'm a programmer (c++/dx9-dx12) , i want to ask if the MTA software have a chance to rebuild the gta sa with my 3d  engine to improve graphics and give more control inside gta world (3d models ,Animations , Particles , Physic engine, Gui and more ...). so in the future the MTA will not need to inject anything because everything will be used directly (3d library).
thanks

**Comment by Samake** [comment]
The most important thing is,that current inject implementation make the whole project law safe, i think. If u switch to any other 3D engine than u have to use resources and assets which are claimed by Rockstar directly and then u will get in trouble. Better way will be improving the whole renderer by more modern techniques and keep handling how MTA works itself untouched.

**Comment by CrosRoad95** [comment]
for first: whether it is needed?
windows 10 that support dx12 have less than 50% of users, 2 versions of mta are worth?

mta team should decide

**Comment by DicoSky** [comment]
The best thing is the 3d engine can work on (Xp, 7 , 8 and 10) , with the same graphic

**Comment by DicoSky** [comment]
This is just a project , the main MTA will not be touched until this project have a succeed work.
Currently MTA take much ram. and much time to just loading resources or changing models.
I'm just want to begin this project with a team has its own experience and not alone.
Anyway waiting other feedbacks.

**Comment by LosFaul** [comment]
I believe you may should get in contact with @saml1er

**Comment by Einheit-101** [comment]
The biggest problem of MTA is ridiculous CPU usage + low draw distance, the second issue had been resolved in MTA:Eir but the project was buried, A guy named "The_GTA" created a new streamer that simply streams as much stuff as the PC can handle. The GTA engine itself is not even that bad if all the small errors get resolved (Alpha rendering, bugs of MTA functions....)

**Comment by qaisjp** [comment]
We have no plans to change away to another engine right now. If you would like to continue the discussion, please feel free to [create a forum topic](https://forum.mtasa.com/forum/107-open-source-contributors/).
