### ISSUE TITLE
Blips desync

### ISSUE THREAD

**Issue by Grafu** [multitheftauto/mtasa-blue#804]
[AV]Grafu executing server-side command: #getElementsByType("blip")
Command results: 64 [number]

Executing client-side command: #getElementsByType("blip")
Command results: 26 [number]

I don't know how that happens but this is definitely not correct. How can server have more blips than client? It has been happening for some time, suddenly blips disappear and only freshly created blips appear.

**Comment by 1B0Y** [comment]
1B0Y executed command: #getElementsByType("blip")
Command results: 1531 [number]

Executing client-side command: #getElementsByType("blip")
Command results: 1548 [number]

Similar results on my test server. (Ignore the fact that I have over 1500 blips)

**Comment by Grafu** [comment]
@1B0Y You sure you don't have blips clientside? You can get those numbers by creating some blips clientside (they won't appear serverside because they are client elements). In my case there are more server blips (automatically syncable to clients) than client blips - a result of a desync.

**Comment by ghost** [comment]
As far as i know all MTA elements will be destroyed when they get streamed out (you are > 150 units away) and recreated when you get closer.

**Comment by Citizen01** [comment]
@Grafu 
Try to set the visibleDistance to the max value (65535 which is the entire map size) and see if you still have a difference between both sides.

**Comment by Citizen01** [comment]
@Grafu Try to set the visibleDistance up to the max (65535 which is the entire map size) and check if you still have a difference between both sides.
https://wiki.multitheftauto.com/wiki/CreateBlip

By the way I stand on your side and it should not only report streamed-in blips. There should be a list to hold all the blips available which `getElementsByType` should use and another one for the list of streamed-in blips.

**Comment by Grafu** [comment]
Yes. We always have a high distance for blips. When the bug happened, all blips on minimap were visible, but only a few (for freshly joined players only) were returned through getElementsByType("blip") clientside.

**Comment by Citizen01** [comment]
All in the same dimension as the player ?

**Comment by Grafu** [comment]
Player and all blips in dimension 0. getElementsByType returns blips in all dimensions by the way.

**Comment by Citizen01** [comment]
Hmmm checked the code and the dimension does not come into play. Same goes for the stream distance if you don't set `true` for the 3rd argument of `getElementsByType`:
https://github.com/multitheftauto/mtasa-blue/blob/e11685cab4beb7958ab202261f9c9d9b4ce71e58/Client/mods/deathmatch/logic/CClientEntity.cpp#L1384-L1414
There is indeed a bug somewhere but I don't see anything wrong in the `getElementsByType` code, so it needs further investigations.

**Comment by ghost** [comment]
I've tested this now serveral times on a Server with only runcode running and i'm ALWAYS getting the right results back by using:
```lua
srun for i = 1, 200 do createBlip(math.random(-3000, 3000), math.random(-3000, 3000), 0, 4) end
```
Are you sure that you guys dont delete them anywhere ?

Edit: Use the following to check whenever a blip is being destroyed and see if you destroy it anywhere
````lua
addDebugHook("postFunction", function(uResource, _, _, strLuaFile, iLine, uElement)
    if(getElementType(uElement) == "blip" or uElement == root or uElement == resourceRoot) then
        iprint("Blip destroyed", uResource, strLuaFile, iLine, uElement)
    end
end, {"destroyElement"})
```

Edit 2: Which client / server version are you using @Grafu

**Comment by patrikjuvonen** [comment]
What is the set distance on the blips? Can you try different values and see what happens?

**Comment by Grafu** [comment]
Reproduction steps:

1. Create blip using createBlipAttachedTo(player, 0, 2, 255, 255, 255) serverside.
2. Blip appears on the minimap, but not listed in getElementsByType("blip") clientside.
3. Blip appears in getElementsByType("blip") clientside after reconnect.

**Comment by StifflersMom** [comment]
The bug can't be reproduced by runcode, because the problem is the blips creation server side inside an "onResourceStart" event (may be inside other events also, not tested).
The following server side code reproduces it **always**:

```
addEventHandler ( "onResourceStart", root, function ( resource )
	if ( resource == getThisResource() ) then
		for i = 1, 200 do createBlip(math.random(-3000, 3000), math.random(-3000, 3000),math.random(-3000, 3000), 0) end
	end
end)

```

**Comment by StifflersMom** [comment]
I've tested some other elements also.
Summary: **Blips, Markers and Radarareas** are not counted client side by getElementsByType, if they are created server side within an onResourceStart event and the client is already connected. If the client reconnects, they are counted correctly.

**Comment by qaisjp** [comment]
Thanks for investigating this. Is this a new bug?

**Comment by Grafu** [comment]
I think it is.

**Comment by StifflersMom** [comment]
It's a new bug :

Works:
Multi Theft Auto v1.5.6-release-16103
Broken:
Multi Theft Auto v1.5.6-release-16257

Edit:
Works: Multi Theft Auto v1.5.6-release-16210
Broken: Multi Theft Auto v1.5.6-release-**16213** <--- That's it.
