### ISSUE TITLE
onClientMarkerHit(Leave) ignores new markers created inside onResourceStart event

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#807]
**Describe the bug**
onClientMarkerHit and onClientMarkerLeave ignores new markers created inside onResourceStart event. The bug only works if you create markers in this event.

**To reproduce**
[[testmarkerbug].zip](https://github.com/multitheftauto/mtasa-blue/files/2846867/testmarkerbug.zip)
1. start marker-create & marker-events & runcode
2. join the server
3. crun setElementPosition(localPlayer, 0, 0, 3)
4. hit the marker and check that the events are working properly
5. restart marker-create
6. now only server events messages are displayed in the chat
7. srun createMarker(5, 0, 2, "cylinder", 2, 255, 255, 0, 200)
8. hit the new marker and look in the chat, client/server events are triggered

**Expected behaviour**
onClientMarkerHit(Leave) should work on markers created inside onResourceStart.

**Version**
Client: 1.5.6-r16177
Server: 1.5.6-r16213

**Additional context**
Checked on the client r16177 / server r16210 and there was no such bug.

**Comment by ghost** [comment]
I'm unable to verify this with
* latest release version (Win10 build)
* latest nightly version (Win10 build)
* custom build from github (Win10 build)

- LuX

**Comment by StifflersMom** [comment]
Can't reproduce with server / client 1.5.6-release-16362

**Comment by theSarrum** [comment]
No idea why you couldn't reproduce this bug, but it was fixed in 379a2ff (r16365).

**Comment by dretax** [comment]
Also ran into this.
The client doesn't detect when entering a server side blip.

**Comment by botder** [comment]
If you can reproduce it, report your client and server version and a small resource to reproduce it.

**Comment by dretax** [comment]
Is It still required? They mentioned above that this was fixed.

**Comment by botder** [comment]
If you can reproduce it on the latest client/server then we can re-open this issue.

**Comment by dretax** [comment]
Ahh nah, I am testing on the 1.5.6 server version, and I was just checking if there is an issue of this.
