### ISSUE TITLE
loadBrowserURL crashes the client

### ISSUE THREAD

**Issue by Loki214** [multitheftauto/mtasa-blue#814]
**Describe the bug**
Using [loadBrowserURL](https://wiki.multitheftauto.com/wiki/LoadBrowserURL) crashes the client.

**To reproduce**
Using runcode
crun browser = createBrowser( 0, 0, false )
crun loadBrowserURL( browser, "https://mtasa.com/" )

**Expected behaviour**
load the page

**Version**
```
Version = 1.5.6-release-16350.8.006
Time = Thu Feb 14 11:35:30 2019
Module = C:\Program Files (x86)\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0x80000003
Offset = 0x0397FA1C

EAX=00000000  EBX=4695D788  ECX=BC0EB10B  EDX=00000003  ESI=448EF4E8
EDI=448EF4FC  EBP=448EF524  ESP=448EF4F0  EIP=4001FA1C  FLG=00000246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

**Additional context**
Not sure at which version it started doing this but it worked fine at v1.5.6-release-16068.8.010 before updating my client a few minutess ago.
No wonder half of the players on my server were crashing when trying to listen to music from yt. 😬

EDIT: found a [topic](https://forum.mtasa.com/topic/114565-crash/) that has the same problem with an earlier version.

**Comment by botder** [comment]
This probably happens because of a CEF update. It might be exiting/crashing because the texture size is smaller than 1x1.

**Comment by Loki214** [comment]
@botder Tested what you said and it seems that was the problem
