### ISSUE TITLE
clearChatBox() returns false serverside if the player is root

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#817]
**Describe the bug**
When using clearChatBox() or clearChatBox(root) it returns false even when the chatBox is cleared for every user. This only happens serverside.

**To reproduce**
/srun clearChatBox()

It will return false

**Expected behaviour**
It should return true.

**Version**
Client: v1.5.6-release-16183
Server: v1.5.6-release-16362

**Comment by patrikjuvonen** [comment]
cc @CrosRoad95

**Comment by qaisjp** [comment]
This is because `root` isn't a player (the argument passed can be any node in the element tree, and it won't know if players exist downstream).

I think this issue exists for many other functions as well (say, `setPedArmor(root, 100)`).

**Comment by PlatinMTA** [comment]
> This is because `root` isn't a player (the argument passed can be any node in the element tree, and it won't know if players exist downstream).
> 
> I think this issue exists for many other functions as well (say, `setPedArmor(root, 100)`).

I can confirm that this also happens with setPedArmor, setElementHealth, setElementModel and probably many others.
