### ISSUE TITLE
Auto included scripts

### ISSUE THREAD

**Issue by miusman** [multitheftauto/mtasa-blue#823]
**Is your feature request related to a problem? Please describe.**
For example, if I want to use [mta-lua-async](https://github.com/inlife/mta-lua-async) in my resources, I will have to manually add the script to all resources and their meta. Then, if this script is updated, I will have to manually replace the old script with a new one.
It's tiring when you have a lot of resources.

**Describe the solution you'd like**
Automatically include scripts from ``includes`` folder in all resources.
Example:
```
includes
   async.lua

firstResource
   ...

secondResource
   ...
```
async.lua will be included in all resources.

**Comment by jushar** [comment]
A global `includes` folder as you described it would break portability (e.g. you would need to upload both includes and the resource to the community site).

Instead, we've been focussing a slightly different approach that would resolve your problem too: https://github.com/multitheftauto/mtasa-blue/pull/680

**Comment by miusman** [comment]
You're right. It would be nice
