### ISSUE TITLE
Mta sa against ddos

### ISSUE THREAD

**Issue by DicoSky** [multitheftauto/mtasa-blue#828]
Hi Guys
I have an idea to protect servers from ddos attackers after the ban (global ban).
the idea is to hide servers ip from mta sa client. and what we will have or see is just the title of the server.
when the player want to connect the mta client will request the ip from the server then connect . all that will happen internaly. if a player has a ban then the ip will not requested.
the best thing is when the server change his ip the client will not affected and he always will connect to the right ip via server title or somethingelse

what you thing guys ?

**Comment by DicoSky** [comment]
i mean here by server is a web server

**Comment by ghost** [comment]
This Idea doesnt have any effect. Peoples who are banned will always find a way to get the IP from a Server (game monitors). Also as far as i remember, nobody has been banned for DDosing other projects. Besides that, MTA is not responsible to deal with such attacks but your hosting provider is.

**Comment by DicoSky** [comment]
i think game monitors will not work here . because the player is banned and the mta webserver will not send the ip to him.

**Comment by ghost** [comment]
Still, it wouldnt make any sense. It wouldnt prevent anything plus **MTA is not responsible for such things**

**Comment by Haxardous** [comment]
You can't just hide IP's from the client, the system can't connect to anything without an IP, even encryption won't work.

**Comment by DicoSky** [comment]
i'm not stupid , the mta client will request the ip from mta web server and not from nothing. and ofcourse the webserver has an ip but its not game server ip.

**Comment by patrikjuvonen** [comment]
Unfortunately this comes down to bad mitigation, which is more of a network design problem that any game server should spend a little time researching, considering network is what it's all about at the end of the day. You should research how to mitigate the effect of DDoS attacks for a game server. Making it harder for clients to get server IP addresses is a waste of time.

**Comment by DicoSky** [comment]
i think no one can understand this , even if i explain better . hope someone close this

**Comment by patrikjuvonen** [comment]
> i think no one can understand this , even if i explain better . hope someone close this

I understand what you're suggesting, but unfortunately that does not stop or prevent anyone with the capability of launching a DDoS attack to get your server's single IP address (also considering the IP has to come from MTA at the end of the day).

**Comment by DicoSky** [comment]
he just will get the ip if he has someone inside the server and he has enough knowledge to get the ip or at least use some software. 
i know it will take time to implement but its a good idea atleast for me since we get ddos just from childs.

**Comment by ghost** [comment]
Still. Its a waste of time. Ip addresses can be easily obtained EVEN when the ip is returned from the master server. Its more or less a Problem for yourself / your hosting provider to get rid of ddos attacks. Nobody else can really do anything about it. Even when mta would work like you suggested: it would still be attackable. Those who know how to d(d)os are also able to use f.e wireshark to spoof server ip.

**Comment by DicoSky** [comment]
-_- , im not talking about normal players , i'm talking about banned players. they can't get any ip even if he use any tool in this world . the ip will requested for normal players . so please stop talking about he will use softwares to get the ip . if we talked here about the normal player then yes he can get the ip .

**Comment by DicoSky** [comment]
okay guys just forget this idea.

**Comment by sbx320** [comment]
If a player is banned, the client still attempts to connect to the server. The server then rejects the connection. This requires a connection between the server and the client. Therefore the client always needs the IP of the server. No matter how well we hide it in the UI, you can easily figure the IP out by monitoring traffic.

**Comment by DicoSky** [comment]
i'm not talking here about game server , i'm talking about web server (MTA WEB SERVER) ---> Website (php) and database

**Comment by DicoSky** [comment]
okay this is an image for the idea : 

![image](https://user-images.githubusercontent.com/923242/53137356-5c293f00-357a-11e9-9abf-669550db79f4.png)

**Comment by miusman** [comment]
Maaan. You have already been told that this will not help, because computer will still know the server's IP. This IP can be seen in any network monitoring program:
![scn](https://user-images.githubusercontent.com/46474300/53159169-22425200-35e7-11e9-84c6-167467aeb190.jpg)
![scn2](https://user-images.githubusercontent.com/46474300/53159170-22425200-35e7-11e9-9c31-edbc31fd60b0.jpg)

**Comment by DicoSky** [comment]
-_- , guys you not understand exactly what i say

**Comment by DicoSky** [comment]
really bad :/

**Comment by MegadreamsBE** [comment]
Simply said your idea won't solve anything. It never would be hard to get the IP despite such protections in place. For a start servers rarely change IP's so people can build a listing of said IP's in case they get banned. Let us not waste time on something that won't solve the problem whatsoever.

**Comment by MegadreamsBE** [comment]
For the record: I know exactly what you mean and this is my final response on that matter.

**Comment by DicoSky** [comment]
> Simply said your idea won't solve anything. It never would be hard to get the IP despite such protections in place. For a start servers rarely change IP's so people can build a listing of said IP's in case they get banned. Let us not waste time on something that won't solve the problem whatsoever.

thats why i told above to make title or server id , so we can change ip easely without lose players

**Comment by DicoSky** [comment]
> For the record: I know exactly what you mean and this is my final response on that matter.

this topic was closed , i just want to response others about the idea because they not understand it.
but , good , and really good.
My next game i will apply this theory on it.

**Comment by miusman** [comment]
IP can be hidden only with a proxy (intermediate) server. Like this:
Client: I want to get a servers list (without IPs)
Proxy: no problem, to take
Client: I want to connect to first server
Proxy: ok, now your traffic sent to me will be sent to this server

But this is not what you suggest!

**Comment by DicoSky** [comment]
bro do you know what is mta web server ?

**Comment by MegadreamsBE** [comment]
How would the web server know if you're even the person it thinks you are? VPN for different IP and sending a fake serial (you could easily recreate the HTTP request to it with a made-up serial...) and suddenly it thinks you're not banned!

**Comment by DicoSky** [comment]
yes i know , but hope mta not doing this mistake , the data must be encrypted first then it must sent to web server otherwise we must forgot all of this.

**Comment by MegadreamsBE** [comment]
That can also be modified... as long as you access to the client you can misuse it any way you'd like.

**Comment by MegadreamsBE** [comment]
Beside, people can still keep a list and have it somewhere online. The only way to defend against a DDoS is by having proper network mitigation.

**Comment by DicoSky** [comment]
> That can also be modified... as long as you access to the client you can misuse it any way you'd like.

yeah ,but every serial used must be blocked , because no one will give his request data to anyone otherwise he is an attacker too

**Comment by DicoSky** [comment]
> The only way to defend against a DDoS is by having proper network mitigation.

and yes a host with Anti DDos really important
