### ISSUE TITLE
Model replace bug

### ISSUE THREAD

**Issue by ccw808** [multitheftauto/mtasa-blue#829]
User report from https://forum.mtasa.com/topic/114934-replace-bug-after-update

> Replace Bug after update
> 
> when update mta to version "1.5.6-9.16413.0" some replaces has bugging, look at this, i just want to know whats happening
> http://prntscr.com/mnt6wq

**Comment by botder** [comment]
Might be caused by the recent change to `onClientElementStreamIn`. It doesn't get triggered for model changes anymore (why should it?). There is `onClientElementModelChange` (parameters: oldModel, newModel) now.

**Comment by botder** [comment]
Should be fixed after 66823bd0911c14ed5567a3a9d424c057dbcfbe21
