### ISSUE TITLE
curl 7.64.0 crash on Windows XP

### ISSUE THREAD

**Issue by ccw808** [multitheftauto/mtasa-blue#831]
Unhandled exception 0xC0000005: Access violation reading location 0x00000920.

Stack trace:
```
[Inline Frame] pre_receive_plain(connectdata *)  curl\lib\sendf.c(161)
[Inline Frame] Curl_send_plain(connectdata *)  curl\lib\sendf.c(381)
Curl_write_plain(connectdata * conn, unsigned int sockfd, const void * mem, unsigned int len, int * written)  curl\lib\sendf.c(438)
Curl_schannel_shutdown(connectdata * conn, int sockindex)  curl\lib\vtls\schannel.c(2016)
Curl_ssl_shutdown(connectdata * conn, int sockindex)  curl\lib\vtls\vtls.c(560)
Curl_disconnect(Curl_easy * data, connectdata * conn, bool dead_connection)  curl\lib\url.c(804)
multi_done(Curl_easy * data, <unnamed-enum-CURLE_OK> status, bool premature)  curl\lib\multi.c(620)
multi_runsingle(Curl_multi * multi, curltime now, Curl_easy * data)  curl\lib\multi.c(2119)
curl_multi_perform(Curl_multi * multi, int * running_handles)  curl\lib\multi.c(2223)
```

Source code at exception:
```
curl\lib\sendf.c(161):
        psnd->allocated_size = 2 * conn->data->set.buffer_size;
```

```
num = 0
conn->data = 0x00000000
conn->handler->protocol = 2 CURLPROTO_HTTPS
conn->recv[0] = Curl_recv_plain
conn->sock[0] = 2680
conn->postponed[0].buffer = 0x00000000
conn->postponed[0].allocated_size = 0
conn->postponed[0].recv_size = 0
conn->postponed[0].recv_processed = 0
```

**Comment by patrikjuvonen** [comment]
I'm thinking curl has likely fixed this bug by either or both of these commits that point to `conn->data` related issues:
https://github.com/curl/curl/commit/4015fae044ce52a639c9358e22a9e948f287c89f
https://github.com/curl/curl/commit/38d8e1bd4ed1ae52930ae466ecbac78e888b142f

Let's keep the reverted version for XP and push the next stable curl out next month to see if it has indeed been fixed by either these or some other commit.

**Comment by ccw808** [comment]
CURL crash is occurring on non XP builds as well, although a lot rarer:

- XP crash was #1 most popular, with 25% of crashes for build 16538
- Non-XP crash is #10 most popular, with 2% crashes for build 16535

I checked (non-XP) build 16350 and there are no CURL crashes, so problem did not occur with previous CURL version

**Comment by patrikjuvonen** [comment]
I believe I've found the crash at https://github.com/curl/curl/issues/3412 and https://github.com/curl/curl/issues/3505

Curl fixed in https://github.com/curl/curl/commit/927a5bd1b4f95fe2331c9d9923c620ba8e274d6c

I will cherry-pick these commits to see if they fix the crashing.
