### ISSUE TITLE
Easy method to report MTA cheats and hackers

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#838]
Hi ,

I have﻿﻿﻿ ﻿an idea about MTA cheats and cheaters

﻿ ﻿  

﻿ MTA Arabs ﻿players have more and more cheats undetected by mta anti cheat﻿

 ﻿﻿

so , i want ﻿a easy method to report mta cheats and hacks for MTA arabs players

 (except PM message because this old method and useless in this time)

﻿ ﻿  ﻿﻿﻿

Note : i request this b﻿﻿ecause most Arab players don’t know english language

 

And they want to report cheats and hackers serials but they don’t know !

 

﻿ So we want easy method for arabs players to report their cheats and hacker serial.﻿

**Comment by Dutchman101** [comment]
Hello,

While we do appreciate the effort you put into this, you already asked me the same question by forum PM as seen and answerred by me in this printscreen:
[https://i.imgur.com/tmRaOjR.png](https://i.imgur.com/tmRaOjR.png)

This POV is unchanged, bugtracker unfortunately isn't for matters like this, or trying to second-opinion. The bug bounty program is described at [https://forum.mtasa.com/topic/66858-bounty-for-finding-security-flaws-and-working-cheats-in-mta/](https://forum.mtasa.com/topic/66858-bounty-for-finding-security-flaws-and-working-cheats-in-mta/), if you want to report something or suspect a player of using cheats, you can use our regular methods to get in touch, as I described, simply send me or ccw a forum PM or email.

You can forward any anti-cheat related matters or possibly bug-bounty egilible reports to:
[https://forum.mtasa.com/profile/38052-dutchman101/](https://forum.mtasa.com/profile/38052-dutchman101/) - PM
[https://forum.mtasa.com/profile/7264-ccw/](https://forum.mtasa.com/profile/7264-ccw/) - PM

Alternatively, email addresses for said 2 contacts:
ccw808@gmail.com (ccw)
mcak105@outlook.com (me)

**Comment by dretax** [comment]
At this moment, It is sort of easy to get MTA's driver manipulated, and kernel inject into the MTA process.

**Comment by Dutchman101** [comment]
> At this moment, It is sort of easy to get MTA's driver manipulated, and kernel inject into the MTA process.

It's not. Please don't use github for off-topic matters.
Basically, everyone that is a bit informed knows that MTA beats the worldwide top 5 of commercial games/anti-cheat engines to it

No further discussion is desired
