### ISSUE TITLE
setPedAnimationSpeed does not change the speed of the current animations

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#839]
**Describe the bug**
setPedAnimationSpeed function does not change the speed of the current animation.

**To reproduce**
1. start runcode
2. srun setPedAnimation(getPlayerFromName("NAME"), "ped", "bomber")
3. srun setPedAnimationSpeed(getPlayerFromName("NAME"), "bomber", 0.1)

**Expected behaviour**
It should change the speed of the animation.

**Version**
Client: Multi Theft Auto v1.5.6-release-16557
Server: MTA:SA Server v1.5.6-release-16564

**Additional context**
The problem began with the client version r16352.

**Comment by qaisjp** [comment]
Which commit caused this bug?

**Comment by botder** [comment]
See commit 3996027e9f2eb39a425349ce6b992b0cc7a91013
