### ISSUE TITLE
setServerConfigSetting("enablesd","whatever") returns always true

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#844]
**Describe the bug**
setServerConfigSetting("enablesd","whatever") returns always true

**To reproduce**
runcode:
StifflersMom executed command: setServerConfigSetting("enablesd","12",true)
Command results: true [boolean]

**Expected behaviour**
Should return false, because it seems, that enablesd can't be set while server is running
**Version**
MTA:SA Server v1.5.6-release-16542

**Comment by StrixG** [comment]
It can be set while server is running. You must restart the server after setting _enablesd_.

**Comment by StifflersMom** [comment]
Indeed - It's saved to mtaserver.conf by shutdown. I think this can be closed because it's no bug :)
