### ISSUE TITLE
Functions to facilitate the creation of artificial intelligence

### ISSUE THREAD

**Issue by Muurilo** [multitheftauto/mtasa-blue#850]
Hello, in this issue I give a suggestion to implement functions in the MTA to facilitate the creation of artificial intelligence, it is now very difficult to create artificial intelligence because it does not have certain functions necessary in the MTA

Sorry for English. I used the google translator

**Comment by qaisjp** [comment]
What functions are you looking for?

**Comment by Muurilo** [comment]
I'm looking for functions to facilitate scripting that adds traffic to the map, NPCs among other things, but for the creation of this is practically impossible because there are no functions to for example create an area around the NPC to check what's next to it , if there are walls, other npcs, cars, objects and other things

Again, I'm sorry for bad English.

**Comment by Citizen01** [comment]
> create an area around the NPC to check what's next to it

- [getElementsWithinRange](https://wiki.multitheftauto.com/wiki/GetElementsWithinRange)
- [createColXXX](https://wiki.multitheftauto.com/wiki/Server_Scripting_Functions#Collision_shape_functions) functions with [getElementsWithinColShape](https://wiki.multitheftauto.com/wiki/GetElementsWithinColShape)
- [getElementsByType](https://wiki.multitheftauto.com/wiki/GetElementsByType) along with [getDistanceBetweenPoints2D](https://wiki.multitheftauto.com/wiki/GetDistanceBetweenPoints2D) or [getDistanceBetweenPoints3D](https://wiki.multitheftauto.com/wiki/GetDistanceBetweenPoints3D)


> if there are walls, other npcs, cars, objects and other things

- [processLineOfSight](https://wiki.multitheftauto.com/wiki/ProcessLineOfSight) or [isLineOfSightClear](https://wiki.multitheftauto.com/wiki/IsLineOfSightClear)

So the answer is **yes ! you can !** And you already could a lot of basic "AI" implementations back in 2012 !
**Example**: https://www.youtube.com/watch?v=5nVnt7Iiia0
**Resource**: https://forum.mtasa.com/topic/39776-npc-traffic-released/ ([mirror](http://scriptsformta.blogspot.com/2016/10/mtasanpc-traffic-script-download.html))

**Comment by Muurilo** [comment]
Thank you!
