### ISSUE TITLE
Race pickups produce massive amount of traffic and workload

### ISSUE THREAD

**Issue by jakub12123** [multitheftauto/mtasa-blue#855]
Hello, i found new smth. How to ddos servers by bug Nitro check video if 2 people stay in nos and nos respawning its makes lags server. Test that and look on video.

https://www.youtube.com/watch?v=cCUViwhqj9s

**Comment by CrosRoad95** [comment]
poorly written script, whether it is default mta script?

**Comment by jakub12123** [comment]
it's map, gamemode is Race. nothing more.

[race-[dd]zayatraining.zip](https://github.com/multitheftauto/mtasa-blue/files/2972095/race-.dd.zayatraining.zip)

**Comment by CrosRoad95** [comment]
i can't find this map in default resources
https://github.com/multitheftauto/mtasa-resources/tree/master/%5Bgamemodes%5D/%5Brace%5D/%5Bmaps%5D

**Comment by jakub12123** [comment]
so i have to remove respawn of nos? ;/

**Comment by botder** [comment]
Please create an issue at [multitheftauto/mtasa-resources](https://github.com/multitheftauto/mtasa-resources) because this seems like a race script bug.

**Comment by jakub12123** [comment]
ccw said that i have to add it to issues. ❌
