### ISSUE TITLE
No such mod installed (Deatmatch)

### ISSUE THREAD

**Issue by gcardozo2809** [multitheftauto/mtasa-blue#862]
I've come accross this old error recently, but none of the existing solutions have worked. 

I have tried: 

- Reinstalling GTA & MTA
- Trying the latest Nightly
- Running both GTA & MTA as Admin
- Running in Compatibitlity Mode
- Created a new Windows User Account 
- Replacing my deatmatch folder 
- Replacing only client.dll 

And none of the above have worked. 

I am running the latest MTA stable version now, in Windows 10. 

Any tips at all will be appreciated!

**Comment by ccw808** [comment]
Usually caused by a virus https://forum.mtasa.com/topic/64715-install-anti-virus/

If that doesn't help, add a new topic to https://forum.mtasa.com/forum/83-client/
