### ISSUE TITLE
Element rotations are different for certain element types

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#866]
**Description**
Now for a very long time using setElementRotation gives different results for Peds, vehicles and objects. Even if i choose the same rot order and conformPedRotations i still cant rotate a ped exactly like an object. 

**To reproduce**
-Create a ped, set his rotation to 45, 45, 0
-Create an object, set its rotation to 45, 45, 0
-Note how the rotation of the ped never matches with the object, i could not make it, no matter what rot order i use for the ped. 

**Expected behaviour**
setElementRotation should have an Option to work the same way for everything. 

**Additional context**
Maybe i oversee something here or maybe there is a custom conversion formula like "convertObjectToPedRotation" ?

**Comment by javier2409** [comment]
could be related to this, maybe? 
[https://github.com/multitheftauto/mtasa-resources/issues/150](https://github.com/multitheftauto/mtasa-resources/issues/150)
I posted it as a resource bug, not mta bug, but I think we are talking about the same thing

**Comment by Einheit-101** [comment]
Yes this is exactly whats happening for you

**Comment by javier2409** [comment]
You mentioned a conversion formula, well, there actually is one after all (found it after struggling with my issue all day yesterday), read the optional arguments for set/getElementRotation. It's not a conversion formula actually, but you can tell the functions to interpret the rotation as a certain type (ped/object/vehicle).

**Comment by qaisjp** [comment]
Sounds like an issue with gimbal locking. I don't think this is fixable, you'll have to use matrices.
