### ISSUE TITLE
Wheels and lights are desynced when player damage it

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#868]
**Describe the bug**
When someone damage lights or wheels (shoot at wheels/hit a wall and damage lights), they will be desynced. Player has to stream out his vehicle and stream it in, after that other players will see that lights or tires are broken. I reported this on MantisBT and I can't find link to this bug, but it's still broken.

**To reproduce**
https://youtu.be/JkzLQ5bUgLU

**Expected behaviour**
Damages should be visible after player damage his wheels or lights, not after streamOut and streamIn

**Screenshots**

**Version**
client: Multi Theft Auto v1.5.6-release-16588
server: Multi Theft Auto v1.5.6-release-16609

**Comment by botder** [comment]
Fixed in commit fe48d0968042b0bc5e5375c0c2f8f9ee2ed951ba (pull request #2399).
