### ISSUE TITLE
All markers are invisible

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#872]
**Describe the bug**
All markers are invisible (new bug obviously)

**To reproduce**
1. Update to v1.5.6-release-16607
2. Join a server that has markers or join default server
3. See that markers are invisible but they are there as can interact with them
4. Minimise the game with a marker on screen, maximise game and see the marker for 1 second.

**Expected behaviour**
Markers be visible.

**Screenshots**
Can't take a screenshot of invisible bug.

**Version**
v1.5.6-release-16607

**Additional context**

**Comment by botder** [comment]
Could be caused by e0fa528fcd6fb6b3717320fc197b83a18edb074c
Try with r16601 client

**Comment by ArranTuna** [comment]
The bug does not occur in v1.5.6-release-16601
