### ISSUE TITLE
Http functions and events

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#875]
**Is your feature request related to a problem? Please describe.**
You can only a bit customize http server

**Describe the solution you'd like**
make functions and events to manage http requests

**Describe alternatives you've considered**
/

**Additional context**
I made test branch
https://github.com/CrosRoad95/mtasa-blue/commit/e1df08836bf2055ed8cf4d0243a9da6654039da0
and example script
```lua
addEventHandler("onHTTPRequest", root, function(...)
    iprint("onHTTPRequest",...)

    --cancelEvent() -- if canceled, skip default mta behaviour
end)
```
And his result
![image](https://user-images.githubusercontent.com/22455534/56289678-c812c880-6121-11e9-9a3f-8d640674af14.png)

Idea is simple, 1 event, 2 functions
event: `onHTTPRequest` with 2 arguments: url and account for permissions
functions:
`setHTTPResponde( key, value )` and `getHTTPRequest(key)`
where key would be "cookie", "body", "host" and other http data.

**edit1:**
and i almost forgotten, function to request login

what do you think?

**Comment by qaisjp** [comment]
Please can you comment exactly what you're trying to do, as "You can only customise the http server a little bit" isn't very helpful. What are you trying to achieve, what have you tried, and why doesn't what's currently available work for you?

MTA's http server feature is due an overhaul and needs to be carefully thought about, so I'm hesitant for us to add new features that we'll later need to support.

I'll leave this issue open for now, but it will likely be closed when an overhaul of the HTTP server is proposed.
