### ISSUE TITLE
Allow to copy mod details to acpanel or clipboard Ctrl + C in admin panel

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#878]
Image : https://e.top4top.net/p_1206jv93g1.png

i want to select all mod files and copy it to acpanel resource or clipboard ctrl + c

**it is hard to find mod files and write it in acpanel manually**

**Comment by qaisjp** [comment]
Hi, please resubmit your issue to https://github.com/multitheftauto/mtasa-resources following the [issue template](https://github.com/multitheftauto/mtasa-resources/issues/new/choose).
