### ISSUE TITLE
fileOpen always give warning after last update

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#879]
**Describe the bug**
fileOpen function always give warning 

> Bad usage @ 'open' [unable to load file]

This function give warning about unable load file but open him and can read etc.... See code to reproduce, print will return file content.

**To reproduce**
```lua
local structure = {
	language = '?',
}

addEventHandler('onClientResourceStart', resourceRoot, function()
	if not fileExists('data/config.txt') then
		local file = fileCreate('data/config.txt');
		fileWrite(file, toJSON(structure));
		fileClose(file);
	end
	--[[local file = File.exists('data/config.cfg');
	if not file then
		file = File.new('data/config.cfg');
		file:write(toJSON(structure));
		file:close();
	end]]
end);

function applyData(key, value)
	local file = fileOpen('data/config.txt');
	if file then
		local d = fromJSON(fileRead(file, fileGetSize(file)));
		print(d[key]);

		fileClose(file);
	end
	--[[local f = File.open('data/config.cfg', false);
	local d = fromJSON(f:read(f.size));

	if d[key] then
		d[key] = value;
		f.pos = 0;
		f:write(toJSON(unpack(d)));
	end

	f:close();]]
end

applyData('language', 'a');
```
**Expected behaviour**
Fix this function

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/56512482-cbe28880-652f-11e9-9587-84d9f7eef2b7.png)

**Version**
1.5.6

**Additional context**

**Comment by qaisjp** [comment]
I think your example warns because `applyData` is called before the `onClientResourceStart` event is fired

**Comment by LosFaul** [comment]
applyData('language', 'a') is called before the event "onClientResourceStart" is fired
so your applyData function tries to open/read/close/... a non existing file
