### ISSUE TITLE
Extend object omnipresence to work for all elements

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#890]
**Is your feature request related to a problem? Please describe.**

It is not possible to have players occupy the same space (apartments) whilst being able to see out into the street.

> What he's saying is, he wants to have the﻿ exterior﻿ players in all dimensions, but the﻿ interior players in their own dimensions﻿﻿.

**Describe the solution you'd like**

Extend `setElementDimension(obj, -1)` to work for more than just objects. It should work for all elements.

**Describe alternatives you've considered**

It was mentioned that:

> Can be done client side set all of the exterior players to your dimension **client side.**

Does this actually work? Is this a suitable solution? Does this cause any sort of desync?

**Additional context**

See https://forum.mtasa.com/topic/96692-1-dimension-for-everything/

**Comment by PlatinMTA** [comment]
I think this may have a problem, what should it mean to be on -1 dimension on serverside? The player can see all the things attached to all dimensions? Or only the player can be seen but he can only see things on one dimension (preferibly the 0 dimension or the one that he was changed from?)

I think this should be worked arround on another function maybe, like setPedAllwaysVisible() or something like that. And... what would be the purpose? If you want to see all the players on the same dimension then you just don't change the dimension and you are good to go.
