### ISSUE TITLE
Add 'forceHide' argument for showCursor

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#891]
**Is your feature request related to a problem? Please describe.**
Now we can hide cursor only in the same resource in which show cursor. If eg. cursor will be showed in resource a and we use showCursor(false) in resource b, the cursor will be still showed 

**Describe the solution you'd like**
Add forcedHide - optional argument (default false) for showCursor function. 

**Describe alternatives you've considered**

**Additional context**
I think that is not bad idea, because now if we has showed  in resource x we have to try hide in same resource. Sometimes we must search which resource shown cursor.

**Comment by qaisjp** [comment]
I'm not too sure about this one.

> because now if we has showed in resource x we have to try hide in same resource

Imo each resource should be performing its own cleanup.

The only scenario I can think of is a "message box" resource that shows its own cursor, but even then you the messagebox resource can hide the cursor for the resource when the box is closed. This works well with whatever the initial cursor state is.

What situation requires you to have this function? 

> Sometimes we must search which resource shown cursor.

Would you find it useful to have a debug command to tell you what the current cursor ref count is + what resources have the cursor shown?

**Comment by Proxy-99** [comment]
Reopen this issue @FileEX  ?

**Comment by FileEX** [comment]
> Reopen this issue @FileEX ?

I can't reopen it because I wasn't the one who closed it
