### ISSUE TITLE
engineSetModelLODDistance can break the default map

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#894]
**Is your feature request related to a problem? Please describe.**
There are many objects which have a LOD distance > 325.
If you do any engineSetModelLODDistance to these objects, you can't restore the default until reconnect.

**Describe the solution you'd like**
engineResetModelLODDistance would be nice.

one line runcode to see the desaster:
`crun for i=1337,18000 do test=engineGetModelLODDistance(i)  if test then engineSetModelLODDistance(i,test) end end
`

**Comment by qaisjp** [comment]
Relevant commits:
1. https://github.com/multitheftauto/mtasa-blue/commit/b77dbfa2913f60b8ef2aa1b247da3a15b2749038 "Fixed SetLODDistance to take into account GTA's limitations."
1. https://github.com/multitheftauto/mtasa-blue/commit/a6fd9d9fde45e55c8f2969d512de2ddd22de682d Revert of the above (see comment on this commit)
1. https://github.com/multitheftauto/mtasa-blue/commit/8915fdbffc1e060653bb105562803bf8040f1383#diff-0c91596c2f4fd3ae848fda94d28aae1bR538 (Clamp to 325)

engineResetModelLODDistance sounds reasonable to me.
