### ISSUE TITLE
Request : MTA Chat like discord

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#897]
Hi ,

I have an idea

Make new mta chat like discord and ability to chat players even they don’t in one server

Example : i’m in CIT server and I want to chat with player in FFS server without connect to FFS server.

Select a player in server browser and chat with him.

This good idea

**Comment by qaisjp** [comment]
Thanks for suggestion! I think this is out of scope for MTA.

It's theoretically possible for something like this to be introduced with Discord RPC but it's not something we'd be implementing otherwise.

**Comment by Citizen01** [comment]
Already seeing bad users abusing this system to spam everyone with a server IP or a discord server to join.
Bad idea in my opinion. Or else it would need a friend system so you can't receive messages from unknown players.
