### ISSUE TITLE
Cycle map in tactics gamemode doesn’t work in MTA SA 1.5.6

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#900]
Cycle map in tactics gamemode doesn’t work in MTA SA 1.5.6

To reproduce:

1- download tactics gamemode and arena 20 below :

Tactics gamemode : https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mtasa-tactics/tactics-12-r20.zip

Arena 20 map and other maps :

http://bpb-team.ru/star-tR/files/maps.zip

2- give tactics gamemode full ACL rights

3- start tactics gamemode

3- press F1 , in maps tab add arena 20 only and change the mode from lobby to cycle

The arena 20 map repeat and repeat  , doesn’t work

In mta sa 1.5.1 or 1.5 version this problem doesn’t exist 

But in mta sa 1.5.6 version the problem exist

Please fix the bug

**Comment by bsa11b** [comment]
Someone reproduce ?

**Comment by qaisjp** [comment]
Hi, thanks for your bug report. Please be patient whilst we get round to reproducing your issue.

**Comment by patrikjuvonen** [comment]
Seems that's a resource created by @lex128 who may be able to help you. If there indeed is a bug in MTA and not the script source, feel free to reopen the issue.

**Comment by bsa11b** [comment]
We want from from lex128 give to us tactics-12-r20 source 

I pm him in forum and e-mail but he doesn’t response to me

**Comment by qaisjp** [comment]
~v1.2 r20 source is listed here https://code.google.com/archive/p/mtasa-tactics/downloads~ sorry this is compiled source

1.3 can be found here https://github.com/lex128/mtasa-tactics

**Comment by bsa11b** [comment]
Just edf ، language and modes folders available 

But the client and server files are complied private

EDIT # 1 : he has account in vk website :

http://www.vk.com/lex128 or http://www.vk.com/lexr128

This site blocked in my country i can’t open it.
