### ISSUE TITLE
Remove crouch slide bug for all MTA Clients

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#901]
This bug : https://bugs.multitheftauto.com/view.php?id=8978

Fixed by nocrouchslide resource

But is useless !

I want to remove bug for all mta clients , not for one server include it this resource

nocrouchslide :

https://community.mtasa.com/index.php?p=resources&s=details&id=13368

**Comment by sbx320** [comment]
See https://bugs.multitheftauto.com/view.php?id=8978#c24900

**Comment by qaisjp** [comment]
Also, @bsa11b, you may want to simply ask some servers to install that resource you linked.

I have updated the wiki to include a link to that resource, as well.
