### ISSUE TITLE
restoreTaskOnAnimEnd in setPedAnimation improvement

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#902]
**Description**
The new restoreTaskOnAnimEnd is a step into the right direction, but it has issues.
-If an animation is played in crouched state, the player no longer counts as "ducked" while the animation is running.

-A previously crouching player will attempt to stand up after the applied animation is finished and then quickly return to crouched state. This is not really smooth. Especially not for me, because i try to create a resource that allows players to crawl / prone.

-The camera moves into the elevated "standing" position while the animation is running, because he does no longer count as "crouched" in that time.

**Describe the solution you'd like**
It would be better if restoreTaskOnAnimEnd would completely prevent GTA from resetting the crouch state at all, if thats somehow possible. It would then be called "retainTaskOnAnimStart".

**Video of the problem**
https://youtu.be/T-ayeiELAdY

Another video, showing the issue with a prone animation:
https://youtu.be/wcHM7tI_hgo

**Comment by qaisjp** [comment]
Your video mentions this:

> setPedAnimation behaviour: [After animation completes], Camera moves upwards, isPedDucked returns false, Player attempts to stand up as soon as the animation is finished. [Then the ped continues to duck again.]

If this is with the `restoreTaskOnAnimEnd` enabled, I think this issue definitely should be fixed.

**Comment by Einheit-101** [comment]
Yes, the crouched state does not return before the animation is finished, it would be much better if the crouched state would not even be changed at all. GTA can do it when we crouch-roll with our weapons, like the video shows.

€DIT::: I added another video, the prone animation shows the issue more clearly.
