### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#903]
**Is your feature request related to a problem? Please describe.**

There are many things that are not possible todo or cause performance problems because standart Lua is too slow.

**Describe the solution you'd like**

Yes, you can try to optimice things as much as you can, but everything has it's limits.

I would say we first try to gather examples were LuaJIT, would bring us better performance.

Here are also a few examples were LuaJIT profits over standart Lua: http://luajit.org/performance_x86.html

**Comment by MegadreamsBE** [comment]
Here is an example of where I would benefit from LuaJIT:

Sphene (a SCM virtual machine in MTA with the purpose of building a Co-Op experience on top of the singleplayer missions) only really uses MTA functions to read the files and for the implementation of the actual game logic.

All the other logic (which is a lot of code, easily ran over hundreds of time per second) is just regular Lua that actually would see a nice performance boost if LuaJIT is available, this includes the logic that properly parses the parameters, handles if-statements, etc. This can finally help us get closer to getting Sphene to maintain a stable framerate which it currently is still struggling with.

**Comment by patrikjuvonen** [comment]
Here is our original LuaJIT branch as reference: https://github.com/multitheftauto/mtasa-blue/commits/LuaJIT

**Comment by LosFaul** [comment]
Simulations on cars
- complex aerodynamics: downforce, custom airresitance
- tempratures for different car parts e.g. engine, breaks, tires, cooling system, weather
- engine simulation (*1): rpm, power output
- gearbox simulation (*1): power translation from engine for each gear
- ...


Note: I will edit my message when i find more


(*1) requires fix of setAnalogControlState: https://github.com/multitheftauto/mtasa-blue/issues/567#issuecomment-487266103

**Comment by AlexTMjugador** [comment]
> 
> 
> All the other logic (which is a lot of code, easily ran over hundreds of time per second) is just regular Lua that actually would see a nice performance boost if LuaJIT is available, this includes the logic that properly parses the parameters, handles if-statements, etc. This can finally help us get closer to getting Sphene to maintain a stable framerate which it currently is still struggling with.

In the meantime, on the server side, it's possible to use modules to interface Lua code with native C/C++ code, which can result in a nice performance boost, and the ability to communicate more easily with other languages and/or the underlying operating system. For a project like that, I guess you run most player-independent or synchronization logic in the server, so it could benefit from it. But nobody uses modules :(

Back on topic, I think LuaJIT is a good choice, but I'm concerned that it may generate some inconvenience for server owners that use compiled scripts, because the bytecode generated with the standard Lua interpreter isn't compatible with LuaJIT's. I think that any change in the Lua VM which affects bytecode should be carefully done, with these pros and cons in mind.

**Comment by MegadreamsBE** [comment]
> For a project like that, I guess you run most player-independent or synchronization logic in the server, so it could benefit from it. But nobody uses modules :(
Most of Sphene actually runs on the client (especially SCM interpretation) and even synchronization will mostly not be done on the server as it adds a lot of unnecessary overhead (including the fact that the server has no knowledge about the map). Naturally sending the information between the clients still would go through the server and could be moved into a module if we'd add extra checks to validate this data.

**Comment by WADmitry** [comment]
LuaJIT has a huge overhead when switches context (call Lua code from C-side), AFAIK.
Also it has limit 1GB per process (IDK, whether it was fixed)

**Comment by blockspacer** [comment]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by patrikjuvonen** [comment]
I have no idea.

@Cazomino05 worked on LuaJIT, perhaps he might remember what the status was at the time on the attempt.

**Comment by Pirulax** [comment]
Theres a waay bigger context switch penalty with JIT than with regular Lua, thus having LuaJIT would only benefit if you dont use MTA functions a lot, which isnt feasible that much(bc of dx rendering)

**Comment by Kenix157** [comment]
Please checkout this
https://github.com/iponweb/luavela

It uses Lua 5.1.
