### ISSUE TITLE
Master volume setting is not properly loaded

### ISSUE THREAD

**Issue by brzys** [multitheftauto/mtasa-blue#904]
**Describe the bug**
Master volume is not applied for GTA:SA sounds after launching the game.

**To reproduce**
1. Set master volume to 0%
2. Relaunch MTA
3. Enter the game, GTA:SA sounds are not muted
4. Sounds will be muted after opening Settings

**Expected behaviour**
Master volume should be set after the game is initiated

**Screenshots**
unnecessary

**Version**
Multi Theft Auto v1.5.6-release-16588

**Additional context**
unnecessary

**Comment by patrikjuvonen** [comment]
Thank you for the bug report! I've confirmed this, and will release a fix for this in the next nightly.
