### ISSUE TITLE
Player / vehicle desync after car jacking, if jacker die

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#908]
**Describe the bug**
If player A drives a car and player B starts jacking the car and player B dies at the moment, where he starts to pull player A out of the vehicle, player A become desynced:
From sight of player A: He is on foot, near the car.
From sight of player B and all others: Player a is stuck in the middle of vehicle.

Clientside player A:
getPedOccupiedVehicle(localPlayer) results to his vehicle
isPedInVehicle(localPlayer) results to false (!!!)

Serverside player A and all other clients:
getPedOccupiedVehicle(Player A) results to his vehicle
isPedInVehicle(Player A) results to true

While player A is on foot, he can run out of the streamig range. This results to being immortal for other player, while they see him in his car.

**To reproduce**
You need 2 players.
- start play
- as player A get in a vehicle as driver.
- as player B press F near the vehicle
- at the moment, where B opens the door, kill B

**Expected behaviour**
No desync. If A performs the vehicle exit animation, he should be on foot for all :)

**Screenshots**
Player A before jacked
![grafik](https://user-images.githubusercontent.com/12788736/57102752-8474ad00-6d24-11e9-9b05-c1362fa528c2.png)
Player A after jacked
![grafik](https://user-images.githubusercontent.com/12788736/57102866-b0902e00-6d24-11e9-97bf-c930c5a52e5d.png)
Player B before jacking
![grafik](https://user-images.githubusercontent.com/12788736/57103089-25636800-6d25-11e9-93d7-d848885fe129.png)

Player B after killed respawned while jacking
![grafik](https://user-images.githubusercontent.com/12788736/57102970-e0d7cc80-6d24-11e9-8ff8-4d61bc31f190.png)

**Version**
MTA:SA Server v1.5.6-release-16612 , Client v1.5.6-release-16705

**Additional context**
**In case this is being used for fun to "ruin" players game, this should be fixed with priority, I think.**

**Comment by Neproify** [comment]
IMO it is related to issue #928. I think if dead players would send sync packets, then it would work as it should. Is it working after you spawn player A again? @StifflersMom

**Comment by Neproify** [comment]
@StifflersMom Can you check if this problem still exists on latest master?

**Comment by StifflersMom** [comment]
Checked with
MTA:SA Server v1.5.6-release-18572
Multi Theft Auto v1.5.6-release-18560
The bug still exists like described.

**Comment by StifflersMom** [comment]
**Because players starting "desync parties",** I checked again with Multi Theft Auto v1.5.7-release-20383
The bug still exist.
If the jacking player dies within the jacked player ist thrown out of the car, the jacked player is **totally desynced** !
