### ISSUE TITLE
setVehicleModelDummyPosition crash

### ISSUE THREAD

**Issue by Icensow** [multitheftauto/mtasa-blue#909]
**Describe the bug**
Using setVehicleModelDummyPosition on a vehicle with a replaced model causes a crash when leaving the server.

**To reproduce**
1. Start [this resource](https://github.com/multitheftauto/mtasa-blue/files/3139765/dummy_bug.zip)
2. Quit server.
3. See crash.

**Comment by qaisjp** [comment]
This issue still occurs even after #1021

```
Version = 1.5.6-release-18729.0.000
Time = Thu Jul 18 12:08:20 2019
```

This must be fixed before 1.5.7 is released

**Comment by ccw808** [comment]
I noticed all the vehicle dummy functions except `CModelInfoSA::ResetAllVehicleDummies` have a ` if (!IsVehicle())` check at the beginning.
Maybe add the check to `ResetAllVehicleDummies` as well?

**Comment by forkerer** [comment]
The IsVehicle check has to be passed in other functions before the entry in map is even added, so all the changed dummies stored in it have passed that check already

**Comment by Dutchman101** [comment]
Refer to this comment: [https://github.com/multitheftauto/mtasa-blue/issues/1009#issuecomment-516689379](https://github.com/multitheftauto/mtasa-blue/issues/1009#issuecomment-516689379) for additional information sources
