### ISSUE TITLE
Enable WebRTC for CEF

### ISSUE THREAD

**Issue by brzys** [multitheftauto/mtasa-blue#915]
**Is your feature request related to a problem? Please describe.**
Voice in MTA is unstable since 1.1 and I don't think that this state will improve.
Enabling WebRTC in CEF will allow to capture microphone devices and make your own backend for voice system.

**Describe the solution you'd like**
`requestBrowserWebRTC` for scripters (shows request for a player similar to domain window) allow to enable feature.

**Additional context**
Surely there will be some security concerns.

**Comment by Dutchman101** [comment]
> Voice in MTA is unstable since 1.1 and I don't think that this state will improve.

Actually there's already some work going on: [https://github.com/multitheftauto/mtasa-blue/pull/895](https://github.com/multitheftauto/mtasa-blue/pull/895)

Besides that, there recently was a discussion about the possibility of using Core Audio API.

**Comment by patrikjuvonen** [comment]
Indeed, it is being worked on. Core Audio API related code and design was started by @Cazomino05 at https://github.com/multitheftauto/mtasa-blue/tree/CoreVoice which will also be merged in and polished.

**Comment by qaisjp** [comment]
I'm going to close this in favour of the above comments but feel free to re-open
