### ISSUE TITLE
getKeyState() returns nil for some reason

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#916]
**Describe the bug**
I discovered that getKeyState() returns nil in one of my scripts. I cannot reproduce it with another resource. There must be a function that collides with getKeyState. So far i had no luck finding out what could be causing it.
When i open chat or console, it starts to return "false" instead of "nil"...
The problem is that this script has 5000 lines of code and its not easy to find out where the problem is.

**To reproduce**
-under research-
-It seems that only certain keys are affected, "lshift" or "lalt" works, "mouse1" and "mouse2" does not

**v1.5.6-release-16718**

**Comment by Pirulax** [comment]
did you look into the C++ code?

**Comment by Einheit-101** [comment]
I am not familiar with c++, i only see the result on my server and many players started to complain now.
local state = getKeyState("mouse1")
outputChatBox(tostring(state))
= "nil"

I try stable mta build, i guess this bug does not appear there.

**Comment by Einheit-101** [comment]
My goodness... Please delete this.
After doing more research i discovered that i included the "freecam" script from the editor in my resource and i found in it a wrapper function named "getKeyState" that messed everything up. It caused this behaviour.... Shame on my head.

**Comment by patrikjuvonen** [comment]
No worries! Thanks for continuing your search to pinpoint the problem. If you believe that behavior is incorrect you can report that on [mtasa-resources](https://github.com/multitheftauto/mtasa-resources) since freecam is a default resource.
