### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by RouatbiH** [multitheftauto/mtasa-blue#931]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add Discord Rich Presence
**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/23016064/57587337-63b60f80-74fb-11e9-8fb0-7b55ca62d72f.png)

**Comment by qaisjp** [comment]
Duplicate of #721
