### ISSUE TITLE
Toolchain updates broke GLIBC support for Linux

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-blue#943]
Toolchain updates broke GLIBC support for Linux.

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /root/mtaserver/x64/deathmatch.so)

ERROR: Loading mod (/root/mtaserver/x64/deathmatch.so) failed!

**Reproduction:**
1) get Linux server r16641 (last known working build)
2) update that build to r16705 (introduction of issue) or just latest

At least reproducable on: Debian 9 (ships GLIBC 2.24-11+deb9u4); not sure if relevant

**Expected behavior:** updating MTA server build should never result in breaking compatibility/a total block, no matter the Linux distribution or local GLIBC version (when it worked prior to the changes in r16705).

If further investigation points this way, we should evaluate if it's appropiate for MTA server to refuse operation on Linux servers without updated GLIBC version. It seems to be less than ideal; for example, the latest Debian release doesn't ship 2.27. Although, something with patching was mentioned (see below) of which feature I don't know the technical details.. I believe that is, MTA server forces any distribution to inherit MTA's glibc version rather than the native, which then became bugged due to the update.

@sbx320's thoughts on this issue:

> sbx320 [7:38 PM]
that glibc patching might've been broken by the gcc 8 update
Probably some new symbol version was introduced for something that we don't patch yet

CC: @Jusonex (suspected commit: 8be9c1d)

**Comment by sbx320** [comment]
That has likely been caused by the internal build server migration to gcc 8. 

>If further investigation points this way, we should evaluate if it's appropiate for MTA server to refuse operation on Linux servers without updated GLIBC version.

Breaking compat this way is to be expected. There is no reason to support ancient systems just because it worked before. Probably not in this case though, as we'd drop support for Debian entirely (as 9 is the latest release).

>MTA server forces any distribution to inherit MTA's glibc version rather than the native, which then became bugged due to the update.

That's not quite how it works. MTA links to specific glibc symbols, which are versioned. So if we (or rather: our compiler) decide to use a new symbol (or a new version of a symbol) that defines the minimum glibc version that is required to execute MTA. If it's only a new version, we can patch it to use the old variant. If it's a new symbol, we'd need to drop compatibility with old glibc versions.

It's not realistic to ask people to upgrade glibc versions, as they're usually bound to kernel versions as well. They'd need to change distributions.

**Comment by Einheit-101** [comment]
The server starts but immediately crashes now.

```
MTA:SA Server v1.5.6-r18317-release crash report.
2019-05-16 00:47
Caught 4 addresses ...

Backtrace:
#0 - ./x64/core.so(+0x1ac91) [0x7f8f057e3c91]
#1 - ./x64/core.so(+0x3e947) [0x7f8f05807947]
#2 - ./x64/core.so(+0x3ef99) [0x7f8f05807f99]
#3 - /lib64/libpthread.so.0(+0xf5d0) [0x7f8f05e2f5d0]
--------------------------------------------------------------------------------
MTA:SA Server v1.5.6-r18317-release crash report.
2019-05-16 00:47
Caught 5 addresses ...

Backtrace:
#0 - ./x64/core.so(+0x1ac91) [0x7f4a3dacac91]
#1 - ./x64/core.so(+0x3e947) [0x7f4a3daee947]
#2 - ./x64/core.so(+0x3ef99) [0x7f4a3daeef99]
#3 - /lib64/libpthread.so.0(+0xf5d0) [0x7f4a3e1165d0]
#4 - [0x55a0f991c5b0]
--------------------------------------------------------------------------------
MTA:SA Server v1.5.6-r18317-release crash report.
2019-05-16 00:47
Caught 11 addresses ...

Backtrace:
#0 - ./x64/core.so(+0x1ac91) [0x7f5931d0bc91]
#1 - ./x64/core.so(+0x3e947) [0x7f5931d2f947]
#2 - ./x64/core.so(+0x3ef99) [0x7f5931d2ff99]
#3 - /lib64/libpthread.so.0(+0xf5d0) [0x7f59323575d0]
#4 - /HGSYN/MTA/editor/x64/net.so(+0xa7d5b) [0x7f592acd8d5b]
#5 - /HGSYN/MTA/editor/x64/net.so(+0xb5196) [0x7f592ace6196]
#6 - /HGSYN/MTA/editor/x64/net.so(+0xa55ee) [0x7f592acd65ee]
#7 - /HGSYN/MTA/editor/x64/net.so(+0xe2984) [0x7f592ad13984]
#8 - /HGSYN/MTA/editor/x64/deathmatch.so(+0x4b6a25) [0x7f5929b00a25]
#9 - /lib64/libpthread.so.0(+0x7dd5) [0x7f593234fdd5]
#10 - /lib64/libc.so.6(clone+0x6d) [0x7f5932078ead]
--------------------------------------------------------------------------------
```

**Comment by Dutchman101** [comment]
Re-opened until we fix the crash.
It's confirmed that it always crashes after these changes

**Edit**: there's a chance this crash is related to another recent change, so it's subject to further notice.
**Edit 2**: unrelated crash, anyone reading this should know we're working on a separate fix aswell.

**Comment by sbx320** [comment]
#944 is the issue for the crash
