### ISSUE TITLE
retainPedState not really working on the server

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#947]
**Describe the bug**
retainPedState of setPedAnimation() works fine on my local server (map editor), but it doesnt work on my online server. I thought it was caused by an old server build, but i updated to the latest server version and the problem persists.

**To reproduce**
1. Go to a live server
2. Crouch
3. srun setPedAnimation(me, "grenade", "weapon_throwu", -1, false, true, false, false, 250, true)
4. Player stands up again

The player attempts to crouch down again, but he decides to stands up instead...

**Expected behaviour**
It should work like on the local server

**Comment by qaisjp** [comment]
I haven't confirmed this bug but I'm attaching it to 1.5.7 because this issue MUST be closed before 1.5.7 is released (either for invalidity or via commit fix).

/cc @saml1er

**Comment by ghost** [comment]
I fixed the issue. Once latest nightly is up, then verify it.

**Comment by qaisjp** [comment]
On master: before the fix is applied I can reproduce the bug, and I can reproduce that 65ae168 fixes it.

**Comment by ghost** [comment]
> 
> 
> On master: before the fix is applied I can reproduce the bug, and I can reproduce that [65ae168](https://github.com/multitheftauto/mtasa-blue/commit/65ae16887ae374b1e9b748436f244d2502ad2869) fixes it.

How about this? 
`crun setPedAnimation(me, "grenade", "weapon_throwu", -1, false, true, false, false, 250, true)`

**Comment by qaisjp** [comment]
That works too!

**Comment by ghost** [comment]
So fixed?

**Comment by Einheit-101** [comment]
This is amazing. Now please someone fix the 1-frame delay in onClientPreRender 😍

**Comment by Einheit-101** [comment]
Ehhhh... it still doesnt work. It works perfectly fine on the local server, but it doesnt work on my live server. I just updated the live server to MTA Linux 64 Bit 1.5.7-rc-20157,
my local server is Windows v1.5.7-release-20157
