### ISSUE TITLE
onElementModelChange can't be cancelled using setElementModel

### ISSUE THREAD

**Issue by Lord-Henry** [multitheftauto/mtasa-blue#948]
**Describe the bug**
Using the script below doesn't work.

**Steps to reproduce**
Create a server-side script with this: (sorry, this website doesn't support indentation nor highlights)

```lua
addEventHandler ("onElementModelChange", root, function (oldModel, newModel)
        if (getElementType (source) == "player") then
            if (newModel == 12) then
                outputChatBox ("Skin locked! You can't use it.", source, 255, 30, 30)
                setElementModel (source, oldModel) -- According to Wiki, this should work.
            end
        end
end)
```

**Expected behaviour**
Skin should change back.

**How to "fix" the issue**
Just make setElementModel inside a timer, like this:

```lua
addEventHandler ("onElementModelChange", root, function (oldModel, newModel)
        if (getElementType (source) == "player") then
            if (newModel == 12) then
                outputChatBox ("Skin locked! You can't use it.", source, 255, 30, 30)
                setTimer (function (thePlayer)
                    setElementModel (thePlayer, oldModel)
                end, 100, 1, source)
            end
        end
end)
```

**Version**
Both v1.5.6-release-16616

**Comment by qaisjp** [comment]
Thanks for the issue! 

> (sorry, this website doesn't support indentation nor highlights)

Please refer to the _Code_ section [here](https://guides.github.com/features/mastering-markdown/). This is what the small button (see below) links to when editing a comment.
![image](https://user-images.githubusercontent.com/923242/57988491-11d73180-7a87-11e9-8f94-b0beba642e6a.png)

**Comment by FileEX** [comment]
Can you test your script on the client side?

**Comment by Einheit-101** [comment]
̶h̶̶e̶̶ ̶̶c̶̶a̶̶n̶̶t̶̶ ̶̶t̶̶e̶̶s̶̶t̶̶ ̶̶t̶̶h̶̶i̶̶s̶̶ ̶̶s̶̶c̶̶r̶̶i̶̶p̶̶t̶̶ ̶̶o̶̶n̶̶ ̶̶c̶̶l̶̶i̶̶e̶̶n̶̶t̶̶ ̶̶s̶̶i̶̶d̶̶e̶̶ ̶̶b̶̶e̶̶c̶̶a̶̶u̶̶s̶̶e̶̶ ̶̶t̶̶h̶̶i̶̶s̶̶ ̶̶e̶̶v̶̶e̶̶n̶̶t̶̶ ̶̶d̶̶o̶̶e̶̶s̶̶n̶̶t̶̶ ̶̶e̶̶x̶̶i̶̶s̶̶t̶̶ ̶̶c̶̶l̶̶i̶̶e̶̶n̶̶t̶̶ ̶̶s̶̶i̶̶d̶̶e̶̶.̶

Oh, the event does exist, but the wiki page is missing. The code works client side.
