### ISSUE TITLE
changePlayerSettings

### ISSUE THREAD

**Issue by heyB2sv** [multitheftauto/mtasa-blue#950]
In some servers we need to up mta volume to 10%
or edit brightness etc..
so we need functions to do this for mta players settings only on edited server
and when he quit server settings reset

```
onPlayerSettingsChange
changePlayerSettings
getPlayerSettings
```

like this ^
Sorry for my bad English

**Comment by CrosRoad95** [comment]
no, instead that you should just check player settings, if he have volume higher then 10%, kick or do something to force player manually change that. ill accept only `getPlayerSettings` for some settings but i think there is already simillar function

**Comment by forkerer** [comment]
I also disagree with giving ability to alter client settings, but i think that onPlayerSettingsChange event could be useful, same as getPlayerSettings

**Comment by qaisjp** [comment]
We won't be implementing this or giving control over volume, but feel free to suggest _specific_ settings _you_ need.

**Comment by PlatinMTA** [comment]
Again, doing something like getPlayerSettings() would be nice, but I think making getPlayerSoundLevel() only will be far better and easy because you can already get a lot of information of the specs of the player (resolution, videocard, some visual settings) using dxGetStatus().

I use that previous function to check for things to improve players fps or tell them why they see something green on the shadows (bcuz they're playing on 16bit).

**Comment by patrikjuvonen** [comment]
We do need a `getClientSetting` function. Also at least 1 PR is on hold because this feature is missing. I think getPlayerSoundLevel could be a nice shorthand, but not sure if we need a shorthand if we add a universal getter.

**Comment by PlatinMTA** [comment]
> We do need a `getClientSetting` function. Also at least 1 PR is on hold because this feature is missing. I think getPlayerSoundLevel could be a nice shorthand, but not sure if we need a shorthand if we add a universal getter.

What should that function get tho? dxGetStatus() brings almost all if not all of the client video settings. Maybe the settings on the advanced tab + video settings + sound settings?

**Comment by dmi7ry** [comment]
Get (only get, not set) sound settings would be useful for own implementation of radio, etc.
