### ISSUE TITLE
Restarting resource in onResourcePreStart causes an infinite loop

### ISSUE THREAD

**Issue by StrixG** [multitheftauto/mtasa-blue#958]
**Describe the bug**
Restarting resource in onResourcePreStart causes an infinite loop.

**To reproduce**
Restart `starting` resource in onResourcePreStart.

**Expected behaviour**
Resource should not be restarted while in `starting` state.

**Comment by botder** [comment]
Is it really a bug when you produce an infinite loop and then complain it shouldn't loop forever?
Furthermore, the resource restart is a queued task and not immediate, so that means the resource probably starts successfully and then gets restarted, and not during the onResourcePreStart event.

**Comment by patrikjuvonen** [comment]
I don't think this is a concern and to be honest expected behavior.

**Comment by StrixG** [comment]
You are right.
