### ISSUE TITLE
Client is unable to create DX stuff

### ISSUE THREAD

**Issue by brzys** [multitheftauto/mtasa-blue#966]
**Describe the bug**
I use dxCreateTexture on my server very often. I'm creating textures only when it is necessary to keep video memory usage under 100-200 MB. 

Usually the bug happens after longer play sessions.
MTA stops to draw mipmaps on high resolution textures (they're transparent).
Textures and shaders are not being created, even with enough FreeForMTA memory.
Creating screenshots also fails: `Screenshot failed (CreateOffscreenPlainSurface failed (0x8007000e))`
After some time with those issues, client crashes from core.dll module.

**To reproduce**
unable to reproduce

**Expected behaviour**
no crashes

**Screenshots**
![unknown (7)](https://user-images.githubusercontent.com/5489020/58410842-4d6b9000-8073-11e9-80a6-cd3d6d1f09bc.png)
![unknown (8)](https://user-images.githubusercontent.com/5489020/58411949-c370f680-8075-11e9-9d90-0dedce556a08.png)

**Version**
1.5.6

**Additional context**
Dumps: 
[dumps.zip](https://github.com/multitheftauto/mtasa-blue/files/3223335/dumps.zip)
[dumps2.zip](https://github.com/multitheftauto/mtasa-blue/files/3223433/dumps2.zip)

Connected forum topic with this issue: https://forum.mtasa.com/topic/98970-d3dxcreateeffectfromfile-failed-8007000e-the-bane-of-our-server

You can say that players just don't have video memory to create textures.
That's not true, you can see the topic I've mentioned. While developing resources, those issues also happened to me, but it is totally random (some memory leak?).
I checked my FreeForMTA memory and there was 3GB free, MTA was just unable to create new DX-connected stuff. I had to restart client.

**Comment by Pirulax** [comment]
No wonder why:
`05:00:25 - [DEBUG] nvhacks.nvidia: 0 
05:00:25 - [DEBUG] nvhacks.optimus-force-detection:  
05:00:25 - [DEBUG] nvhacks.optimus-export-enablement: 0 
05:00:25 - [DEBUG] nvhacks.optimus: 0 
05:00:25 - [DEBUG] nvhacks.optimus-rename-exe: 0 
05:00:25 - [DEBUG] nvhacks.optimus-alt-startup: 0 
05:00:25 - [DEBUG] nvhacks.optimus-force-windowed: 0 
05:00:25 - [DEBUG] nvhacks.optimus-dialog-skip:  
05:00:25 - [DEBUG] nvhacks.optimus-startup-option:  `

**Comment by Allerek** [comment]
![unknown (1)](https://user-images.githubusercontent.com/12304071/58962782-2ec07400-87ac-11e9-92aa-6550dae04aa9.png)
Got this on his server.
