### ISSUE TITLE
Add file and function names in `ERROR: Aborting; infinite running script in ...`

### ISSUE THREAD

**Issue by dmi7ry** [multitheftauto/mtasa-blue#967]
**Is your feature request related to a problem? Please describe.**
At the moment the message is little useless because shows only resource's name.

**Describe the solution you'd like**
Would be good if it also shows names of the file and the function where it was happen

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by FileEX** [comment]
I think only resource name and file name will be enough. Because if u write some code, you know where u write code and where can be this error.

**Comment by dmi7ry** [comment]
If you used a third-party resource you may not know where the problem may be.
