### ISSUE TITLE
dxUpdateScreenSource gives warning "expected texture, got texture"

### ISSUE THREAD

**Issue by zo3n** [multitheftauto/mtasa-blue#974]
**Describe the bug**
Parsing normal texture to dxUpdateScreenSource causes an illogical (misleading) warning: **expected texture, got texture**

**To reproduce**
1. crun dxUpdateScreenSource(dxCreateRenderTarget(1,1))

**Expected behaviour**
Expected behaviour is to throw warning "Bad argument @ 'dxUpdateScreenSource' [expected screen-source-texture at argument 1, got texture]"

**Screenshots**
http://prntscr.com/nvyeam

**Version**
Multi Theft Auto v1.5.6-release-18537

**Additional context**

**Comment by ccw808** [comment]
The error message is misleading. It should say **[expected screen source texture at argument 1, got texture]**

The problem is with this line:
` t.screenSource = t:applyBlurH(t.screenSource, SCREEN_WIDTH, SCREEN_HEIGHT, t.strength)`
as is overwrites t.screenSource

**Comment by zo3n** [comment]
Thanks @ccw808 for a solution to this. I've updated the issue to feature an easier way to reproduce the problem.
