### ISSUE TITLE
Curl update in r18534 seems to break resources download from external http

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#975]
**Describe the bug**
The resources download from external http server fails with serval error messages.

**To reproduce**
Connect to a server which has an external http server for resource downloading
Server log:
```
[19-05-31 23:54:16] DIAGNOSTIC: Playername #1012 External HTTP file download error:[1007] Error downloading requested files. Failed to initialize download. (Disabling External HTTP) [file path]
[19-05-31 23:58:41] DIAGNOSTIC: Playername #1012 External HTTP file download error:[200] Error downloading requested files. Timeout was reached. [Operation too slow. Less than 10 bytes/sec transferred the last 6 seconds] [filename] (Disabling External HTTP) [filename]

```

**Expected behaviour**
No errors :)

**Screenshots**
Client side:
![grafik](https://user-images.githubusercontent.com/12788736/58737590-7d63bc00-8402-11e9-8714-652086d26b61.png)
![grafik](https://user-images.githubusercontent.com/12788736/58737612-93717c80-8402-11e9-8510-8bb38ec7e0b7.png)

**Version**
v1.5.6-release-18537

**Additional context**
I tried the same with client r18445 with no problems.

**Comment by ccw808** [comment]
Please try lastest nightly

**Comment by StifflersMom** [comment]
checked with v1.5.6-release-18560 by deleting random download intense resources from client resource folder and let them download again from external http by connecting our server.
There were **NO PROBLEMS** :)

**Comment by StifflersMom** [comment]
![grafik](https://user-images.githubusercontent.com/12788736/59207090-a0cafb80-8ba6-11e9-9916-c5306212d908.png)

`[19-06-10 17:36:38] DIAGNOSTIC: Playername #1012 External HTTP file download error:[1007] Error downloading requested files. Failed to initialize download. (Disabling External HTTP) [filepath]`

Getting this again with client v1.5.6-release-18574

**Comment by StifflersMom** [comment]
Additional: Trying to delete the affected file on the client while NOT connected but client leaved open after this error:
![grafik](https://user-images.githubusercontent.com/12788736/59207688-d45a5580-8ba7-11e9-8b37-84b446d448ee.png)
The affected file is locked by MTA WOW64 Helper
The error was gone after closing an re-opening the client without doing anything with the resource client folder, so I think it is more related to file locking?
The affected file was changed and the resource was restarted before connecting...

Edit: Exiting the client completely and start / connect the server again corrects the problem every time. I can reproduce that every time.

**Comment by qaisjp** [comment]
Can you repro with r18445 https://nightly.mtasa.com/mtasa-1.5.6-rc-18445-20190525.exe

**Comment by StifflersMom** [comment]
Sadly, I changed some more files and now, I can't reproduce it at all. It seems that the amount of files is also related. I will look for a 100% reproduceable state, may take some time.

**Comment by qaisjp** [comment]
cheers
