### ISSUE TITLE
Allow CEF Lua <=> JS communication for localhost

### ISSUE THREAD

**Issue by Timur2915** [multitheftauto/mtasa-blue#976]
**Is your feature request related to a problem? Please describe.**

For now, localhost CEF urls handled as a remote node, so it's impossible to use Lua <=> JS communication. I think it needs to be handled as local node. It can be very useful for development purposes, especially on modern frontend framework usages.

**Describe the solution you'd like**

Allow CEF Lua <=> JS communication for localhost urls

**Describe alternatives you've considered**

Allow CEF Lua <=> JS for remote nodes as an option. Maybe add additional param to whitelist?

**Comment by jushar** [comment]
> especially on modern frontend framework usages.

Can you describe that in detail? Why do you think so?   

Unless there's a specific reason, I think it's a too specialised case that isn't worth implementing and exposes the user to unnecessary security risks.

**Comment by Timur2915** [comment]
For now it's impossible to use webpack dev server for hot module reloading. It can be useful for UI development, i.e. with React. I don't see any secutiry risks here.
