### ISSUE TITLE
Animations crash

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#986]
**Describe the bug**
Animations crash in some case

**To reproduce**
Just start mta ( that's my conclusion from stack frame)

**Expected behaviour**
Crash shouldn't happend
**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/59156364-578d8580-8a9a-11e9-93a2-45ed8d3eebf8.png)
in `Client\game_sa\CAnimBlendStaticAssociationSA.h`

Stack frame
![image](https://user-images.githubusercontent.com/22455534/59156371-683dfb80-8a9a-11e9-9119-aee1d2af27c8.png)

**Version**
1.5.6 release 18427

**Additional context**

**Comment by Dutchman101** [comment]
Fixed in 1e234b6
