### ISSUE TITLE
UncompressAnimation crash

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#987]
**Describe the bug**
Unhandled exception thrown: read access violation.
**pHierarchy** was nullptr. occurred

file: `Client\game_sa\CAnimManagerSA.cpp`

**To reproduce**

**Expected behaviour**

**Screenshots**
Stack frame
![image](https://user-images.githubusercontent.com/22455534/59156436-9112c080-8a9b-11e9-92b2-75b0f6f63d61.png)

![image](https://user-images.githubusercontent.com/22455534/59156445-c1f2f580-8a9b-11e9-81ec-006016e35bf7.png)

**Version**
1.5.6 release 18427

**Additional context**
/

**Comment by qaisjp** [comment]
This is quite close to #986. Are you able to reproduce either of these consistently?

/cc @saml1er

**Comment by ghost** [comment]
@qaisjp Anim crashes have disappeared after disabling the unloading code in 1e234b6786bc5c6aab85baba37946d637d00f474

**Comment by Dutchman101** [comment]
Fixed in 1e234b6
