### ISSUE TITLE
AddProjectile crash

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#988]
**Describe the bug**
crash happened in that function
https://github.com/multitheftauto/mtasa-blue/blob/e11685cab4beb7958ab202261f9c9d9b4ce71e58/Client/game_sa/CProjectileInfoSA.cpp#L123-L170

**To reproduce**
Shoot homing missile from hydra in unexisted target ( that is my conclusion )

**Expected behaviour**
Crash shouldn't happened

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/59156624-8279d880-8a9e-11e9-8835-4673aadc45b9.png)
![image](https://user-images.githubusercontent.com/22455534/59156681-9540dd00-8a9f-11e9-887b-45a29e663642.png)
![image](https://user-images.githubusercontent.com/22455534/59156683-9d991800-8a9f-11e9-93d0-9951a5322a92.png)
![image](https://user-images.githubusercontent.com/22455534/59156687-aee22480-8a9f-11e9-90fb-bb96decd38ef.png)

**Version**
1.5.6 release 18427

**Additional context**
/

**Comment by qaisjp** [comment]
Are you able to reliably reproduce this?

**Comment by ghost** [comment]
> 
> 
> Are you able to reliably reproduce this?

@CrosRoad95 ?

botder fixed this crash long ago. If it's still there, then let me know.
