### ISSUE TITLE
Network trouble, chat lines disappearing 

### ISSUE THREAD

**Issue by rhaeee** [multitheftauto/mtasa-blue#989]
**Describe the bug**

So recently I reinstalled MTA and unusual bug occured. The "Network Trouble" text started popping up whenever I am spectating someone. My internet connection works fine so that cannot be the issue why the text is showing up. If my game is minimized the text isn't showing while I'm spectating someone and shows up after about 20 seconds when I go back into the game. 

**To reproduce**

1. Spectating someone and text shows up
2. Playing and text is not shown
3. Player (me) dies
4. starts spectating someone and the text shows up again 

**Expected behaviour**

Network trouble text shouldn't pop up if my internet connection is stable. 

**Version**

- Multi Theft Auto v1.5.6-release-18560

**Comment by Woovie** [comment]
Adding to this, I've seen similar reports in Discord.

**Comment by patrikjuvonen** [comment]
Is the version of these affected clients r18534 or later? (give us the smallest version that is known to be affected)
Also, has this happened before? If so, when did it start (version?)

**Comment by rhaeee** [comment]
> Is the version of these affected clients r18534 or later? (give us the smallest version that is known to be affected)
> Also, has this happened before? If so, when did it start (version?)

I'm not sure on what client version this issue started to occur. (for me it started on the version listed above)
And no this has not happened before (atleast not for me). It started after I reinstalled MTA.

**Comment by ccw808** [comment]
Please test with https://nightly.mtasa.com/mtasa-1.5.6-rc-18445-20190525.exe

**Comment by ccw808** [comment]
Pretty sure "Network Trouble" is being caused by #964

**Comment by rhaeee** [comment]
> Pretty sure "Network Trouble" is being caused by #964

Using version 18445 works. The "Network Trouble" text didn't show up. But should I keep playing with the downgrade version or do something else?
