### ISSUE TITLE
Serversided setObjectBreakable()

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#990]
**Is your feature request related to a problem? Please describe.**
Now setObjectBreakable() is clientside only. This can be worked arround using triggerClientEvent() on some clever places of your code to make objects unbreakable/breakable for all the users of your server, but this isn't ideal.

**Describe the solution you'd like**
Making a serverside version of setObjectBreakable()

**Additional context**
This isn't really that important because, as I said, you can already change the breakability of objects for all the players with a clever use of triggerClientEvent(), but imho this isn't really convenient to do, it would be easier if we had a serverside version of setObjectBreakable() avaliable.

Maybe #483 should be fixed before implementing a serverside version of this function?

**Comment by Allerek** [comment]
Can be bypassed with `onClientObjectBreak` and `cancelEvent()` but ye, its useful

**Comment by tederis** [comment]
Already implemented in https://github.com/multitheftauto/mtasa-blue/commit/9b9396ea82346b6f99862afd87bfb20d4673270c
