### ISSUE TITLE
Alter vehicles.ide tire size values

### ISSUE THREAD

**Issue by Woovie** [multitheftauto/mtasa-blue#994]
**Is your feature request related to a problem? Please describe.**
Some (Read: most) vehicle mods have tire sizes different than what line up with the original model. This is an issue when replacing vehicles over other vehicles that are also not of the same "type", ie, a race car over a Rancher. The tire size value set in vehicles.ide is hardcoded.
**Describe the solution you'd like**
Add the ability to dynamically adjust this value.
**Additional context**
Documentation of where this value is read:

https://www.gta-modding.com/san_andreas/tutorials/vehicles_ide.html

**Comment by dmi7ry** [comment]
https://github.com/multitheftauto/mtasa-blue/issues/719

**Comment by Woovie** [comment]
Oops

**Comment by qaisjp** [comment]
Duplicate of #719
