### ISSUE TITLE
onResourceChange

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#995]
**Is your feature request related to a problem? Please describe.**

Always when you do refresh or refreshall on server, you have always have to do additional user interaction in your managment resources to update all the changed resources. I would like an event that gets called when the refresh command has done it's job and gives a table of all changes resources.

**Describe the solution you'd like**

add an event "onResourceChange" that gives a table of all resources that changed
{ {resName1, changeInfo}, {resName2, changeInfo}, ... }
changeInfo should be a string with an information such as:
"loaded", "unloaded", "meta changes", "file changes", "error loading", ...

**Describe alternatives you've considered**

you always have to loop through all resources, which is annoying and can block the main thread when there are thousands of resources

**Comment by ghost** [comment]
What about the following:
```lua
handler(resource resource, table changedFiles)
```
instead of a string saying "meta changed" or "file changed" - they're not really helpful and would require re-parsing meta.xml in which you would again validate changed files (check against cached checksums) ?

**Comment by qaisjp** [comment]
should there be a resource source? if there's a resource source, will the event trigger for each resource? this might be less than ideal because then you can't react to them in bulk. 

> `handler(resource resource, table changedFiles)`

the idea sounds good. please can you flesh out what you mean @xLuxy it's not exactly clear.


> `{ {resName1, changeInfo}, {resName2, changeInfo}, ... }`

probably shouldn't use resource names, should use resource elements. how will this behave for unloaded resources?

I'd suggest each table inside the outer array to be a dict rather than a tuple

**Comment by ghost** [comment]
something like that @qaisjp i guess:
```lua
handler(table changes)
	
changes = {
    {
        resource = element,
        changes = {
            [fileName] = "added / removed / changed",
            ...
        }
    },
    ...
}
```

If we want to trigger that event per resource, then the handler would be like above `handler(resource theResource, table changes)`

**Comment by qaisjp** [comment]
This works fine for meta changes / file updates. But what about "loaded", "unloaded", "error loading"?

Do we even have a resource handle for an "unloaded" event?

> If we want to trigger that event per resource, then the handler would be like above `handler(resource theResource, table changes)`

source = resource?

**Comment by LosFaul** [comment]
looking back at this topic after some time
ghost seems to have a nice idea for the passed table
but i think this could be a better structure
```lua
-- table structure
local changes = {
    {
        resource = resource1, -- resource:userdata
        --> added - resource was added/loaded
        --> removed - resource was removed/unloaded
        --> changed - resource was changed (resource files)
        state = "added/removed/changed",
        --> changes should include meta.xml
        changes = {
            --> added - file was added
            --> removed - file was removed
            --> changed - file was changed
            [fileName1]  = "added/removed/changed",
            [fileName2]  = "added/removed/changed",
            ...
        }
    },
    {
        resource = resource2,
        state = "added/removed/changed",
        changes = {
            ...
        }
    },
    ...
}
```
(the event should only fire when refresh/refreshall or refreshResources() was used)

**Comment by LosFaul** [comment]
i also thought about the other variant here:
```lua
addEventHandler("onResourceChanged", root,
  function(resource, state, changes)
    -- resource - userdata
    -- state - string -> added/removed/changed
    -- changes = { [fileName1] = state, ... }
    -- basicly as in my aboth comment

  end
)
```
(should only fire when refresh/refreshall or refreshResources() was used)


the change checks could also run async/multihtreaded and fire when the checks are done
